### PR TITLE
MC-38931: Product URL Rewrites are not removed when product removed from website

### LINKED ISSUE #24184: Product URL Rewrites are not removed when product removed from website
### Preconditions (*)
1. 2.4-develop

### Steps to reproduce (*)
1. Deploy 2.4-develop
2. Create 2nd Website, 2nd Store, 2nd Store View
3. Create New Cateogory
4. Create New Product in New Category
5. Add product to Main Website and 2nd Website
6. Check URL table contains entries for Product, Category/Product for each store in each website
7. Remove Product from 2nd Website

### Expected result (*)
6. Check URL table contains entries for Product, Category/Product for only the stores in the first website

### Actual result (*)
1. URL Rewrites remain for all stores in all websites

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)

Fixes URL rewrite delete/generation on website remove/assign
### Fixed Issues (if relevant)

1. Fixes magento/magento2#24184

### Manual testing scenarios (*)

1. test URL rewrite generation/delete from admin
2. test URL rewrite generation/delete by REST API requests (productRepository POST/PUT/DELETE)
3. test URL rewrite generation/delete by mass update (corn should be enabled)
4. test URL rewrite generation/delete through import 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 1]
```diff
@@ -3,73 +3,167 @@
...
+        if ($this->isNeedUpdateRewrites($product)) {
+            $this->deleteObsoleteRewrites($product);
+            $oldWebsiteIds = $product->getOrigData('website_ids');
+            $storesToAdd = [];
+            if ($oldWebsiteIds !== null) {
+                $storesToAdd = $this->getStoresListByWebsiteIds(
+                    array_diff($product->getWebsiteIds(), $oldWebsiteIds)
+                );
+            }
+            $this->appendRewrites->execute([$product], $storesToAdd);
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:85]: $this->appendRewrites->execute() may throw UrlAlreadyExistsException. Please make sure it will be processed or process it here.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+                $urls[] = $this->generateUrls($product, Store::DEFAULT_STORE_ID);
+            } elseif ($product->getStoreId() === Store::DEFAULT_STORE_ID
+                || in_array($product->getStoreId(), $product->getStoreIds())) {
+                $product->unsUrlPath();
+                $product->setUrlPath($this->productUrlPathGenerator->getUrlPath($product));
+                $urls[] = $this->productUrlRewriteGenerator->generate($product);
+            }
+        }
+        if (!empty($urls)) {
+            $this->urlPersist->replace(array_merge(...$urls));
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: $this->urlPersist->replace() may throw UrlAlreadyExistsException. Please add it to annotations.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 3]
```diff
@@ -0,0 +1,150 @@
...
+     */
+    private $urlPersist;
+
+    /**
+     * @var ProductUrlRewriteDataLocator
+     */
+    private $dataLocator;
+
+    /**
+     * AppendUrlRewritesToProducts constructor.
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: Please remove.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 4]
```diff
@@ -0,0 +1,150 @@
...
+use Magento\Catalog\Model\ResourceModel\Product\ProductUrlRewriteDataLocator;
+use Magento\CatalogUrlRewrite\Model\ProductUrlPathGenerator;
+use Magento\CatalogUrlRewrite\Model\ProductUrlRewriteGenerator;
+use Magento\CatalogUrlRewrite\Service\V1\StoreViewService;
+use Magento\Store\Model\Store;
+use Magento\Store\Model\StoreManagerInterface;
+use Magento\UrlRewrite\Model\UrlPersistInterface;
+
+/**
+ * Update url rewrites to products class
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: It's a bit confusing description and class name. Could you please add more clear description and/or class name?

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 5]
```diff
@@ -3,73 +3,167 @@
...
+    private function getStoresListByWebsiteIds(array $websiteIds): array
+    {
+        $storeIdsArray = [];
+        if (!empty($websiteIds)) {
+            foreach ($websiteIds as $websiteId) {
+                $storeIdsArray[] = $this->storeWebsiteRelation->getStoreByWebsiteId($websiteId);
             }
         }
+
+        return array_merge([], ...$storeIdsArray);
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: Please add result to local cache. This method already used twice during observer execution.
Also it would be better to use $product instead on $websiteIds as parameter to avoid code duplication. 
Lines 
$oldWebsiteIds = $product->getOrigData('website_ids') ?? []
$websiteIds = array_diff($oldWebsiteIds, $product->getWebsiteIds())
could be moved in this method. Rename method to more appropriate one after this changes.

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 6]
```diff
@@ -3,73 +3,167 @@
...
+    private function deleteObsoleteRewrites(Product $product): void
+    {
+        $oldWebsiteIds = $product->getOrigData('website_ids') ?? [];
+        $storesToRemove = $this->getStoresListByWebsiteIds(
+            array_diff($oldWebsiteIds, $product->getWebsiteIds())
+        );
+        if ((int)$product->getVisibility() === Visibility::VISIBILITY_NOT_VISIBLE) {
+            $storesToRemove[] = $product->getStoreId();
+        }
+        if (!empty($storesToRemove)) {
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: Could be simplified to if ($storesToRemove) ...

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 7]
```diff
@@ -0,0 +1,150 @@
...
+                $urls[] = $this->productUrlRewriteGenerator->generate($product);
+            }
+        }
+        if (!empty($urls)) {
+            $this->urlPersist->replace(array_merge(...$urls));
+        }
+    }
+
+    /**
+     * Generate urls for sprcific store
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: Please fix typo

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 8]
```diff
@@ -0,0 +1,150 @@
...
+                if ($hasScopeUrlKey) {
+                    $urls[] = $this->generateUrls($product, (int)$storeId);
+                } else {
+                    $forceGenerateDefault = true;
+                }
+            }
+            if ($forceGenerateDefault && $product->getStoreId() !== Store::DEFAULT_STORE_ID) {
+                $urls[] = $this->generateUrls($product, Store::DEFAULT_STORE_ID);
+            } elseif ($product->getStoreId() === Store::DEFAULT_STORE_ID
+                || in_array($product->getStoreId(), $product->getStoreIds())) {
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: This check is confusing, could you please add comment or extract this verification into private method with clear name and description?

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 9]
```diff
@@ -0,0 +1,150 @@
...
+    public function __construct(
+        ProductRepositoryInterface $productRepository,
+        ProductUrlRewriteGenerator $urlRewriteGenerator,
+        StoreViewService $storeViewService,
+        StoreManagerInterface $storeManager,
+        ProductUrlPathGenerator $urlPathGenerator,
+        UrlPersistInterface $urlPersist,
+        ProductUrlRewriteDataLocator $dataLocator
+    ) {
+        $this->productRepository = $productRepository;
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: Unused dependency. Please remove.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php [hunk 10]
```diff
@@ -0,0 +1,150 @@
...
+        $this->productUrlRewriteGenerator = $urlRewriteGenerator;
+        $this->storeViewService = $storeViewService;
+        $this->storeManager = $storeManager;
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: Unused dependency. Please remove.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 11]
```diff
@@ -0,0 +1,138 @@
...
+use Magento\Catalog\Model\Product\Visibility;
+use Magento\Eav\Model\Config;
+use Magento\Framework\App\ResourceConnection;
+use Magento\Framework\EntityManager\MetadataPool;
+use Magento\Store\Model\Store;
+
+/**
+ * Product data needed for url rewrite generation locator class
+ */
+class ProductUrlRewriteDataLocator
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: This class name is confusing. Please rename it to something like GetProductUrlRewriteData and make it as a wrapper, not resource.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 12]
```diff
@@ -0,0 +1,138 @@
...
+{
+    /**
+     * @var MetadataPool
+     */
+    private $metadataPool;
+
+    /**
+     * @var array
+     */
+    private $productStoreData = [];
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Please rename to $urlRewriteData

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 13]
```diff
@@ -0,0 +1,138 @@
...
+     * @param Config $eavConfig
+     */
+    public function __construct(
+        MetadataPool $metadataPool,
+        Visibility $visibility,
+        ResourceConnection $connection,
+        Config $eavConfig
+    ) {
+        $this->metadataPool = $metadataPool;
+        $this->visibility = $visibility;
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Unused dependency. Please remove.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 14]
```diff
@@ -0,0 +1,138 @@
...
+    }
+
+    /**
+     * Retrieves data for product by store
+     *
+     * @param ProductInterface $product
+     * @param int $storeId
+     * @return array
+     */
+    public function getRewriteGenerateData(ProductInterface $product, int $storeId = Store::DEFAULT_STORE_ID): array
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: After renaming class, please rename method to execute

Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Why $storeId is optional? Please make $storeId as required parameter.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 15]
```diff
@@ -0,0 +1,138 @@
...
+    {
+        $storeId = $storeId ?? $product->getStoreId();
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Remove after $storeId become required.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 16]
```diff
@@ -0,0 +1,138 @@
...
+        if (isset($this->productStoreData[$product->getId()])) {
+            return $this->productStoreData[$product->getId()][$storeId]
+                ?? ($this->productStoreData[$product->getId()][Store::DEFAULT_STORE_ID]
+                    ?? []);
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Redundant fallback, please simplify it to return $this->productStoreData[$product->getData($linkField)][$storeId];

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 17]
```diff
@@ -0,0 +1,138 @@
...
+        }
+
+        $storesData = $this->fetchData($product);
+        foreach ($storesData as $storeData) {
+            $this->productStoreData[$product->getId()][$storeData['store_id']] = [
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Please use $product->getData($linkField) for consistency.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 18]
```diff
@@ -0,0 +1,138 @@
...
+                'visibility' => (int)($storeData['visibility'] ?? $storesData[Store::DEFAULT_STORE_ID]['visibility']),
+                'url_key' => $storeData['url_key'] ?? $storesData[Store::DEFAULT_STORE_ID]['url_key'],
+            ];
+        }
+
+        return $this->productStoreData[$product->getId()][$storeId]
+            ?? ($this->productStoreData[$product->getId()][Store::DEFAULT_STORE_ID]
+                ?? []);
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Redundant fallback. Please simplify.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php [hunk 19]
```diff
@@ -0,0 +1,138 @@
...
+    }
+
+    /**
+     * Fetches product store data required for url key generation
+     *
+     * @param ProductInterface $product
+     * @return array
+     */
+    private function fetchData(ProductInterface $product): array
```
Comment (engcom-Kilo) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: Please move this logic to separate resource service.

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php [hunk 20]
```diff
@@ -0,0 +1,126 @@
...
+    public function __construct(
+        ProductUrlRewriteGenerator $productUrlRewriteGenerator,
+        SearchCriteriaBuilder $criteriaBuilder,
+        UrlPersistInterface $urlPersist,
+        RequestInterface $request,
+        StoreWebsiteRelationInterface $storeWebsiteRelation,
+        Collection $productCollection,
+        AppendUrlRewritesToProducts $appendRewrites
+    ) {
+        $this->productUrlRewriteGenerator = $productUrlRewriteGenerator;
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: Unused dependency. Please remove.

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php [hunk 21]
```diff
@@ -0,0 +1,126 @@
...
+        $this->urlPersist = $urlPersist;
+        $this->request = $request;
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: Unused dependency. Please remove.

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php [hunk 22]
```diff
@@ -0,0 +1,126 @@
...
+        $this->storeWebsiteRelation = $storeWebsiteRelation;
+        $this->criteriaBuilder = $criteriaBuilder;
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: Unused dependency. Please remove.

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php [hunk 23]
```diff
@@ -0,0 +1,126 @@
...
+     * @param ProductAction $subject
+     * @param mixed $result
+     * @param array $productIds
+     * @param array $websiteIds
+     * @param string $type
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
+     */
+    public function afterUpdateWebsites(
+        ProductAction $subject,
+        $result,
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: Result is not mixed. Please fix.

File: app/code/Magento/CatalogUrlRewrite/etc/di.xml [hunk 24]
```diff
@@ -27,6 +27,9 @@
     <type name="Magento\CatalogUrlRewrite\Model\Storage\DbStorage">
         <plugin name="dynamic_storage_plugin" type="Magento\CatalogUrlRewrite\Plugin\DynamicCategoryRewrites"/>
     </type>
+    <type name="Magento\Catalog\Model\Product\Action">
+        <plugin name="url_rewrite_product_action_plugin" type="Magento\CatalogUrlRewrite\Plugin\Catalog\Model\Product\ProductToWebsiteChange"/>
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/etc/di.xml]: Name is confusing. Please change it to something like update_url_rewrites_after_websites_update_plugin

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php [hunk 25]
```diff
@@ -0,0 +1,126 @@
...
+use Magento\Framework\Api\SearchCriteriaBuilder;
+use Magento\Framework\App\RequestInterface;
+use Magento\Store\Api\StoreWebsiteRelationInterface;
+use Magento\UrlRewrite\Model\UrlPersistInterface;
+use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
+
+/**
+ * Update URL rewrites after website change
+ */
+class ProductToWebsiteChange
```
Comment (engcom-Kilo) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: Plugin name is confusing. Please change it to url rewrite related.

File: dev/tests/integration/testsuite/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrlTest.php [hunk 26]
```diff
@@ -65,8 +65,8 @@ protected function setUp(): void
     /**
      * Test switching stores with non-existent cms pages and then redirecting to the homepage
      *
-     * @magentoDataFixture Magento/UrlRewrite/_files/url_rewrite.php
      * @magentoDataFixture Magento/Catalog/_files/category_product.php
+     * @magentoDataFixture Magento/UrlRewrite/_files/url_rewrite.php
```
Comment (engcom-Kilo) [inline dev/tests/integration/testsuite/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrlTest.php:69]: Looks like this file could be reverted.

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php [hunk 27]
```diff
@@ -0,0 +1,107 @@
...
+     * @var StoreWebsiteRelationInterface
+     */
+    private $storeWebsiteRelation;
+
+    /**
+     * @inheritdoc
+     */
+    protected function setUp(): void
+    {
+        parent::setUp();
```
Comment (engcom-Kilo) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php]: No need to call parent construct

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php [hunk 28]
```diff
@@ -0,0 +1,107 @@
...
+    }
+
+    /**
+     * @param $websiteCode
+     * @return Website
+     */
+    private function loadWebsiteByCode($websiteCode)
+    {
+        $websiteRepository = Bootstrap::getObjectManager()->get(WebsiteRepository::class);
+        try {
```
Comment (engcom-Kilo) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php]: No need to wrap it in try-catch.

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php [hunk 29]
```diff
@@ -0,0 +1,107 @@
...
+    }
+
+    /**
+     * @param string $sku
+     * @param int|null $storeId
+     * @return ProductInterface
+     */
+    private function getProductModel(string $sku, int $storeId = null): ProductInterface
+    {
+        try {
```
Comment (engcom-Kilo) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php]: No need to wrap it in try-catch

**Review by engcom-Kilo — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 5 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: there is no code duplication, as we use the different order of sub-arrays to compare and getting result of website ids. A cache can be added but in the current implementation, it won't give any result of performance improvement. Don't see a possibility to add and delete the same website at the same time.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 16 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: don't see why we should use $linkField here instead fo id

File: dev/tests/integration/testsuite/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrlTest.php (hunk 26 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/UrlRewrite/Model/StoreSwitcher/RewriteUrlTest.php:69]: In this case, changing the order of fixture loading have sense, as product save generates rewrites for all assigned websites. Then can not be checked logic of redirect from unexisting rewrite to home page.

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 1 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:85]: Don't need to handle this exception. This is expected behavior in case when admin tries to save a product with url-key that already assigned to another item either product or category. See \Magento\CatalogUrlRewrite\Model\ProductUrlRewriteTest::testUrlRewriteOnProductSaveWithExistingUrlKey

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 2 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: In this case, if an exception is thrown in a sub-routine, then @throws must not be used in the parent method.
https://devdocs.magento.com/guides/v2.4/coding-standards/docblock-standard-general.html

**Comment by engcom-Golf** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 3 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: removed

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 4 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: updated

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 6 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: updated

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 7 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: fixed

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 8 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: added clarification

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 9 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: removed

File: app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php (hunk 10 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/AppendUrlRewritesToProducts.php]: removed

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 11 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: updated, moved to CatalogUrlRewrite module

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 12 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: renamed

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 13 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: removed

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 14 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: renamed

Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: updated

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 15 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: removed

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 17 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: don't see why we should use $linkField here instead fo id

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 18 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: made refactoring

File: app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php (hunk 19 above)
Comment (engcom-Golf) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/ProductUrlRewriteDataLocator.php]: fixed

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php (hunk 20 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: removed

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php (hunk 21 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: removed

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php (hunk 22 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: removed

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php (hunk 23 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: fixed

File: app/code/Magento/CatalogUrlRewrite/etc/di.xml (hunk 24 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/etc/di.xml]: updated

File: app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php (hunk 25 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChange.php]: renamed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php (hunk 27 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php]: removed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php (hunk 28 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php]: removed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php (hunk 29 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/ProductToWebsiteChangeTest.php]: removed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php [hunk 30]
```diff
@@ -0,0 +1,91 @@
...
+            $product->getUrlKey() . '.html',
+            $url
+        );
+    }
+
+    /**
+     * @param $websiteCode
+     * @return Website
+     */
+    private function loadWebsiteByCode($websiteCode)
```
Comment (engcom-Kilo) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php]: No need to extract couple code lines into separate method.

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php [hunk 31]
```diff
@@ -0,0 +1,91 @@
...
+        $websiteRepository = Bootstrap::getObjectManager()->get(WebsiteRepository::class);
+        return $websiteRepository->get($websiteCode);
+    }
+
+    /**
+     * @param string $sku
+     * @param int|null $storeId
+     * @return ProductInterface
+     */
+    private function getProductModel(string $sku, int $storeId = null): ProductInterface
```
Comment (engcom-Kilo) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php]: No need to extract couple code lines into separate method.

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 1 above)
Comment (engcom-Kilo) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:85]: In this case please add exception to annotaions.

**Review by engcom-Kilo — CHANGES_REQUESTED** [review]

**Comment by engcom-Golf** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php (hunk 30 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php]: fixed

**Review by engcom-Kilo — APPROVED** [review]

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php (hunk 31 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Plugin/Catalog/Model/Product/UpdateProductWebsiteUrlRewritesTest.php]: fixed

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 1 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:85]: added

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31106`.

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31106`.

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 32]
```diff
@@ -3,73 +3,168 @@
...
     }
 
     /**
      * Generate urls for UrlRewrite and save it in storage
      *
-     * @param \Magento\Framework\Event\Observer $observer
+     * @param Observer $observer
      * @return void
-     * @throws \Magento\UrlRewrite\Model\Exception\UrlAlreadyExistsException
+     * @throws UrlAlreadyExistsException
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:72]: You should not add Exception to annotation if your method does not throw exception directly

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 33]
```diff
@@ -3,73 +3,168 @@
...
+     * Is website assignment updated
+     *
+     * @param Product $product
+     * @return bool
+     */
+    private function isWebsiteChanged(Product $product)
+    {
+        $oldWebsiteIds = $product->getOrigData('website_ids');
+
+        return array_values($oldWebsiteIds) != array_values($product->getWebsiteIds());
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: This array comparison is unreliable. Better use array_diff instead

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 34]
```diff
@@ -3,73 +3,168 @@
...
+    }
+
+    /**
+     * Retrieve list of stores by website ids
+     *
+     * @param array $websiteIds
+     * @return array
+     */
+    private function getStoresListByWebsiteIds(array $websiteIds): array
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: Could you move this code in separate class since you use it also in UpdateProductWebsiteUrlRewrites
Store module should be right place for it

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php [hunk 35]
```diff
@@ -3,73 +3,168 @@
...
+    }
+
+    /**
+     * Return product use category path in rewrite config value
+     *
+     * @return bool
+     */
+    private function isRewriteUseCategoryPath(): bool
+    {
+        return $this->scopeConfig->isSetFlag('catalog/seo/product_use_categories');
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: Looks like you check flag for default scope but not for particular scope

File: app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php [hunk 36]
```diff
@@ -0,0 +1,66 @@
...
+     *
+     * @param ProductInterface $product
+     * @param int $storeId
+     * @return array
+     */
+    public function execute(ProductInterface $product, int $storeId): array
+    {
+        $productId = $product->getId();
+        if (isset($this->urlRewriteData[$productId][$storeId])) {
+            return $this->urlRewriteData[$productId][$storeId];
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php:48]: Its a little bit dangerous to have cache here. You should at least have method to reset cache and do it after rewrites changed

File: app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml [hunk 37]
```diff
@@ -0,0 +1,23 @@
...
+-->
+
+<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+        xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
+    <actionGroup name="AdminSearchByRequestPathAndStoreViewActionGroup" extends="AdminSearchByRequestPathActionGroup">
+        <annotations>
+            <description>Goes to the Admin URL Rewrite grid page. Searches the grid based on the provided Redirect Path and StoreView name. Validates that the provided Redirect Path, Type and Target Path are present and correct in the grid.</description>
+        </annotations>
+        <arguments>
+            <argument name="redirectPath" type="string"/>
```
Comment (zakdma) [inline app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml]: No need to repeat arguments declaration from parent AG (this row and following two)

File: app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml [hunk 38]
```diff
@@ -0,0 +1,23 @@
...
+<!--
+ /**
+  * Copyright © Magento, Inc. All rights reserved.
+  * See COPYING.txt for license details.
+  */
+-->
+
+<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+        xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
+    <actionGroup name="AdminSearchByRequestPathAndStoreViewActionGroup" extends="AdminSearchByRequestPathActionGroup">
```
Comment (zakdma) [inline app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml]: Please give descriptive name for AG. There is no any word about URL rewrite grid
Ex. AdminFilterUrlRewriteGridByRequestPathAndStoreViewActionGroup

File: dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php [hunk 39]
```diff
@@ -254,6 +255,58 @@ public function testUpdateWithDeleteWebsites()
         );
     }
 
+    /**
+     * Test removing association between product and website 1 then chek url rewrite removed
```
Comment (zakdma) [inline dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php]: then **check**

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 40]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+        //Add product to websites corresponding to all 4 stores.
+        //Rewrites should not be present as the product is hidden
+        //at the global scope.
+        $product->setWebsiteIds(
+            array_unique(
+                [
+                    $testStore1->getWebsiteId(),
+                    $testStore2->getWebsiteId(),
+                    $testStore3->getWebsiteId(),
+                    $testStore4->getWebsiteId()
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 41]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                'redirect_type' => 0,
+                'store_id' => $testStore3->getId(),
+            ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore4->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:336]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 42]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                'redirect_type' => 0,
+                'store_id' => $testStore2->getId(),
+            ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore3->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 43]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                [
+                    $testStore1->getWebsiteId(),
+                    $testStore2->getWebsiteId(),
+                    $testStore3->getWebsiteId(),
+                    $testStore4->getWebsiteId()
+                ]
+            )
+        );
+        $this->productRepository->save($product);
+        $expected = [
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:308]: You newer use this array and redeclared it again on L350

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 44]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                    $testStore2->getWebsiteId(),
+                    $testStore3->getWebsiteId(),
+                    $testStore4->getWebsiteId()
+                ]
+            )
+        );
+        $this->productRepository->save($product);
+        $expected = [];
+        $actual = $this->getActualResults($productFilter);
+        foreach ($expected as $row) {
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:442]: Why do you need this if $expected is actually empty?

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 45]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                'redirect_type' => 0,
+                'store_id' => $testStore1->getId(),
+            ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore4->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:412]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 46]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+            $this->assertContains($row, $actual);
+        }
+
+        //Set product to be not visible at global scope
+        $this->storeManager->setCurrentStore(Store::DEFAULT_STORE_ID);
+        $product->setVisibility(Visibility::VISIBILITY_NOT_VISIBLE);
+        $this->productRepository->save($product);
+        $expected = [];
+        $actual = $this->getActualResults($productFilter);
+        foreach ($expected as $row) {
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: Why do you need this if $expected is actually empty?

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 47]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                'redirect_type' => 0,
+                'store_id' => $testStore3->getId(),
+            ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore4->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 48]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                'redirect_type' => 0,
+                'store_id' => $testStore1->getId(),
+            ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore4->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 49]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+        $product->setVisibility(Visibility::VISIBILITY_NOT_VISIBLE);
+        $this->productRepository->save($product);
+        $expected = [
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore1->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 50]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
-                'store_id' => $testStore->getId(),
+                'store_id' => $testStore2->getId(),
             ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore3->getId(),
+            ]
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: add comma

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php [hunk 51]
```diff
@@ -210,25 +223,410 @@ public function testUrlKeyHasChangedInStoreviewContextWithoutPermanentRedirectio
...
+                'store_id' => $testStore3->getId(),
+            ],
+            [
+                'request_path' => "product-1.html",
+                'target_path' => "catalog/product/view/id/" . $product->getId(),
+                'is_auto_generated' => 1,
+                'redirect_type' => 0,
+                'store_id' => $testStore4->getId(),
+            ]
+        ];
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:629]: add comma

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 32 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:72]: required by https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html#5-exceptions in 5.3

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 33 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: array_diff returns empty result in case if new websites added

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 34 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: done

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 35 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: wrong configuration was taken, changed to Generate "category/product" URL Rewrites global config instead

File: app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php (hunk 36 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php:48]: added clearing of local cache by product after generation

File: app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml (hunk 37 above)
Comment (engcom-Golf) [reply app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml]: fixed

File: app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml (hunk 38 above)
Comment (engcom-Golf) [reply app/code/Magento/UrlRewrite/Test/Mftf/ActionGroup/AdminSearchByRequestPathAndStoreViewActionGroup.xml]: fixed

File: dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php (hunk 39 above)
Comment (engcom-Golf) [reply dev/tests/api-functional/testsuite/Magento/Catalog/Api/ProductRepositoryInterfaceTest.php]: fixed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 40 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 41 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:336]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 42 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 43 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:308]: fixed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 44 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:442]: changed asseration

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 45 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:412]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 46 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: fixed

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 47 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 48 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 51 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php:629]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 50 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: added

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php (hunk 49 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserverTest.php]: added

**Comment by engcom-Golf** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 32 above)
Comment (zakdma) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:72]: @engcom-Golf please refer to docblock magento standards
https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#functions-methods
A declaration of possible exceptions using the @throws tag, **if the actual body of function triggers an exception**.

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 33 above)
Comment (zakdma) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: No. Check this
http://sandbox.onlinephpfunctions.com/code/5f1d5a8f31414027b9f5962569e9a6d7d54f9b3b

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 32 above)
Comment (zakdma) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:72]: @engcom-Golf please refer to docblock magento standards
https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html#functions-methods
A declaration of possible exceptions using the @throws tag, **IF THE ACTUAL BODY OF FUNCTION TRIGGERS AN EXCEPTION**.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php [hunk 52]
```diff
@@ -0,0 +1,76 @@
...
+
+        return $this->urlRewriteData[$productId][$storeId];
+    }
+
+    /**
+     * Clears product url rewrite data in local cache
+     *
+     * @param ProductInterface $product
+     */
+    public function clearProductRewriteData(ProductInterface $product)
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php]: Please name it **clearProductUrlRewriteDataCache** to clarify that we clear exactly cache, not url rewrite data itself

File: app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php (hunk 36 above)
Comment (zakdma) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php:48]: Please name it **clearProductUrlRewriteDataCache** to clarify that we clear exactly cache, not url rewrite data itself

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 33 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: and what about this case 
http://sandbox.onlinephpfunctions.com/code/c2007754d416a55aea54a6630a990b984cb08c6d

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 32 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php:72]: Some kind of collision, but I'd like to not hide the possible exception throwing. This was required by @engcom-Kilo review as well. 
https://github.com/magento/magento2/pull/31106#discussion_r535227589

File: app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php (hunk 36 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/GetProductUrlRewriteDataByStore.php:48]: done

**Comment by engcom-Golf** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php (hunk 33 above)
Comment (engcom-Golf) [reply app/code/Magento/CatalogUrlRewrite/Observer/ProductProcessUrlRewriteSavingObserver.php]: added check both variants with array diff

**Review by zakdma — APPROVED** [review]

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31106`.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31106`.
