### PR TITLE
33589 fix array values in catalogsearch parameters

### LINKED ISSUE #33589: strlen() expects parameter 1 to be string, array given | magento/module-catalog-search
### Preconditions (*)

- Magento 2.4.2
- PHP 7.4

### Steps to reproduce (*)

1. Go to `/catalogsearch/advanced/result/?price[from][]=1&price[to]=1`
2. On trying to access above URL from front-end, "There has been an error processing your request" error message is getting displayed on UI:
http://magento2.4.local/catalogsearch/advanced/result/?price[from][]=1&price[to]=1 
image

### Expected result (*)

It should not throw an unhandled error.

### Actual result (*)

```
Exception #0 (Exception): Warning: strlen() expects parameter 1 to be string, array given in vendor/magento/module-catalog-search/Model/Advanced.php on line 380

#1 strlen() called at [vendor/magento/module-catalog-search/Model/Advanced.php:380]
#2 Magento\CatalogSearch\Model\Advanced->getPreparedSearchCriteria() called at [vendor/magento/module-catalog-search/Model/Advanced.php:206]
#3 Magento\CatalogSearch\Model\Advanced->addFilters() called at [vendor/magento/module-catalog-search/Controller/Advanced/Result.php:62]
#4 Magento\CatalogSearch\Controller\Advanced\Result->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#5 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#6 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#7 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#8 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#9 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:23]
#10 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#11 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:32]
#15 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#16 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#17 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#18 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#19 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#20 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#21 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#22 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#23 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#24 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#25 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#26 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#27 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```

**Issue 2:** strpos() expects parameter 1 to be string, array given | magento/module-eav #33588
**Steps to reproduce:**
1. Admin: Stores -> Attributes -> Product - > Add New Attribute /Choose existing attribute ex: color
Input Type should be: Dropdown
Storefront Properties: Use in Search: Yes, Visible in Advanced Search: Yes
2. Front-end - Go to http://yourmagentostore.com/catalogsearch/advanced/result/?attributename[][error]=1
Ex: https://magento2.4.local/catalogsearch/advanced/result/?test_data[][error]=1
 **Issue: There has been an error processing your request Error message is getting displayed
    Note: There is no issue with Text Attribute. URL is working for Text attribute. Issue is observed for dropdown attribute.**

Magentoroot/var/log/exception.log:
```
Exception #0 (Exception): Warning: strpos() expects parameter 1 to be string, array given in vendor/magento/module-eav/Model/Entity/Attribute/Source/Table.php on line 152

#1 strpos() called at [vendor/magento/module-eav/Model/Entity/Attribute/Source/Table.php:152]
#2 Magento\Eav\Model\Entity\Attribute\Source\Table->getOptionText() called at [vendor/magento/module-catalog-search/Model/Advanced.php:404]
#3 Magento\CatalogSearch\Model\Advanced->getPreparedSearchCriteria() called at [vendor/magento/module-catalog-search/Model/Advanced.php:206]
#4 Magento\CatalogSearch\Model\Advanced->addFilters() called at [vendor/magento/module-catalog-search/Controller/Advanced/Result.php:62]
#5 Magento\CatalogSearch\Controller\Advanced\Result->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#6 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#7 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#8 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#9 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#10 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:23]
#11 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#12 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#13 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#14 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#15 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->___callPlugins() called at [generated/code/Magento/CatalogSearch/Controller/Advanced/Result/Interceptor.php:32]
#16 Magento\CatalogSearch\Controller\Advanced\Result\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#17 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#18 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#19 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#20 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]
#21 Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#22 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:71]
#23 Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#24 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#25 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#26 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#27 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#28 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by SilinMykola**
### Description (*)
I changed a method that prepare values for advanced search. Model: `\Magento\CatalogSearch\Model\Advanced`

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33589

### Manual testing scenarios (*)

1. Open page with parameters: `/catalogsearch/advanced/result/?price[from][]=1&price[to]=1`
For example: `htps://base_url/catalogsearch/advanced/result/?price[from][]=1&price[to]=1`

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento give me test instance

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @SilinMykola, could you please cover these changes by an integration test?

Thank you.

**Comment by andrewbess** [comment]
@magento give me test instance

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
> Hi @SilinMykola, could you please cover these changes by an integration test?
> 
> Thank you.

Hi! @eduard13 ! Ok, I'll create integration test for this model.

**Comment by eduard13** [comment]
@SilinMykola, additionally, could you please check how the `catalogsearch/result` handles such cases?
Thanks.

File: app/code/Magento/CatalogSearch/Model/Advanced.php [hunk 1]
```diff
@@ -368,6 +368,13 @@ protected function getPreparedSearchCriteria($attribute, $value)
                 if (!empty($value['from']) || !empty($value['to'])) {
                     $from = '';
                     $to = '';
+                    if (is_array($value['from'])) {
+                        $value['from'] = $this->getFirstArrayElement($value['from']);
+                    }
+                    if (is_array($value['to'])) {
+                        $value['to'] = $this->getFirstArrayElement($value['to']);
+                    }
```
Comment (ihor-sviziev) [inline app/code/Magento/CatalogSearch/Model/Advanced.php]: I think, in case if we got an incorrect type - it's better to do assume that this parameter doesn't exist at all. I think we're expecting here the only string.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogSearch/Model/Advanced.php (hunk 1 above)
Comment (SilinMykola) [reply app/code/Magento/CatalogSearch/Model/Advanced.php]: @ihor-sviziev Hi! May be you are right and we should create a redirect if `$value['from']` or `$value['to']` is array. But I think we can check this arrays for some values and create a valid response.

cc: @andrewbess, @eduard13

Comment (Den4ik) [reply app/code/Magento/CatalogSearch/Model/Advanced.php]: @SilinMykola I'm agree with @ihor-sviziev that we should ignore this parameter if it's not valid instead of trying to understand what we received and extract some data from it.
Looks like patch for all occasions.

Comment (SilinMykola) [reply app/code/Magento/CatalogSearch/Model/Advanced.php]: Ok, @Den4ik! Locally I removed this code and work on tests.

Comment (ihor-sviziev) [reply app/code/Magento/CatalogSearch/Model/Advanced.php]: The following comment is related to this discussion https://github.com/magento/magento2/issues/33589#issuecomment-893702664

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B, WebAPI Tests, Unit Tests

**Comment by Den4ik** [comment]
@SilinMykola Please check failed integration tests

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run Functional Tests EE

**Review by Den4ik — APPROVED** [review]
After discussion with @SilinMykola in slack and test possible one another solution I approve this PR as easiest an fast solution for now.
@SilinMykola Thanks for the work

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9197](https://jira.corp.magento.com/browse/ENGCOM-9197) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9197](https://jira.corp.magento.com/browse/ENGCOM-9197) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Install fresh Magento instance with sample data.


**Manual testing scenario:**

1. Front end: Click on "advanced search" link from the footer.

2. Set the price 1 to 1 and do search
 
3. Edit the resulted URL from _/***/advanced/result/?name=&sku=&description=&short_description=&price%5Bfrom%5D=1&price%5Bto%5D=1_ to _/***/advanced/result/?price[from][]=1&price[to]=1_

4. Validate the edited URL response in the web page.


**Before:** :heavy_multiplication_x: Used to get an error message

image


**After:** :heavy_check_mark:  Gives the search result information

With no result data
image

With result data
image

There is no additional regression is required since it is a specific case where we are doing an URL tampering. It has no impact on any other features as well.
