### PR TITLE
[Performance] Fix array merge in loop

### LINKED ISSUE #30183: [Issue] [Performance] Fix array merge in loop
This issue is automatically created based on existing pull request: magento/magento2#30153: [Performance] Fix array merge in loop

---------

### Summary (*)
Continuing #30002 - fix array merge in loop in different places.
Also this is follow up on my old PR #22248, so it should a bit improve static content deploy.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
Continuing https://github.com/magento/magento2/pull/30002 - fix array merge in loop in different places.
Also this is follow up on my old PR https://github.com/magento/magento2/pull/22248, so it should a bit improve static content deploy.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30183: [Performance] Fix array merge in loop

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run Integration tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
Would like to identify what actually breaks the integration tests, for now tried to revert some parts, will see where it start fails

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php [hunk 1]
```diff
@@ -73,10 +73,9 @@ public static function getBlacklist(string $pattern)
     {
         $blacklist = [];
         foreach (glob($pattern) as $list) {
-            //phpcs:ignore Magento2.Performance.ForeachArrayMerge
-            $blacklist = array_merge($blacklist, file($list, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES));
+            $blacklist[] = file($list, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
         }
-        return $blacklist;
+        return array_merge([], ...$blacklist);
```
Comment (lbajsarowicz) [inline dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:78]: Could you replace `*****list` with less controversial word? Eg. `IgnoredList`?

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-8260](https://jira.corp.magento.com/browse/ENGCOM-8260) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

File: dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php (hunk 1 above)
Comment (ihor-sviziev) [reply dev/tests/static/testsuite/Magento/Test/Integrity/ComposerTest.php:78]: That’s not purpose of current PR. We have a lot such places in code, they need to be reviewed all and fixed at once

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
QA not applicable

**Comment by gabrieldagama** [comment]
@magento give me new instance with env php 7.3 database 5.7

**Comment by gabrieldagama** [comment]
@magento give me new instance with edition b2b with env php 7.3 database 5.7
