### PR TITLE
REST API Product update url_key doesnt re-gerenate url_rewites when single store enabled

### LINKED ISSUE #30316: REST API Product update url_key doesnt re-gerenate url_rewites (INSANE)
### Summary
Updating product `url_key` via REST API ; Product Url Rewrites are not re-generated. (yeah, i know, thats crazy)

This occurs on actually "Simple" setup, out of the box : Single-store mode and calls on "all" Rest Endpoint `{{magento_url}}/rest/all/V1/products/{{sku}}`, elementary school level

I use the term "Url Rewrites" (with a "s") because that involves category-path-product-urls also. But i focus on product "direct" url

### Preconditions
1. Magento CE 2.3.4 - Single store mode
2. Magento 2.4-develop
3. Calls made on "all" : **`PUT`** `{{magento_url}}/rest/all/V1/products/{{sku}}`
:warning: **Note:** 2.4-develop doesn't contain `POST` call for  `{{magento_url}}/rest/all/V1/products/{{sku}}`
image
4. **Stores->Configuration->General->Single-Store Mode->Enable Single-Store Mode=Yes**

### Steps to reproduce
1. Given a standard product (simple product, dont try to overcomplicate things)
   - Said product has id=10 : `entity_id=10`
   - Current `url_key="my-product-url"` (In Admin Product View : Section "Search Engine Optimization")
2. Check current Url_Rewrites in (Marketing / SEO & Search / Url Rewrites)
   - Search for target_path like `catalog/product/view/id/10`
   - Current url_rewrite should exist : `"my-product-url.html"` (i suppose ".html" as most used case prefix)
3. REST PUT Update on product :
   _Sorry, no time to write a one line curl call. If you read this, you're smart enough to use Postman and already have this call ready to go._
   - **`PUT`** {{magento_url}}/rest/all/V1/products/{{sku}}
   - Json pload : 
```
{
  "product": {
    "custom_attributes": [
        {
            "attribute_code": "url_key",
            "value": "my-new-url"
        }
    ]
  }
}
```
4. Check Url_key has been updated (In Admin Product View : Section "Search Engine Optimization")
   - Url_key is `my-new-url` (whaou)
5. Check Url_Rewrites in (Marketing / SEO & Search / Url Rewrites)
   - Search for target_path like `catalog/product/view/id/10`(or update tab/search, as you want, take your time)
   - **URL rewrites not updated**

### Expected result
   - URL Rewrites should have been updated

### Actual result
   - URL Rewrites NOT updated

### Additional info
- There is absolutely NOTHING related to async, indexing, cache... No, thats really crazy : follow....
- Url rewrites ARE generated on product CREATION, but NOT ON UPDATE
- Passing websites_id on extension_attributes does not help (wait, it should, but wait...)
- Calling update on "default" rest endpoint instead of "all" would work BUT : IT IS A REALLY BAD IDEA :
  You will not see "real value" for the store (1) in Admin product view (and NO way to see it in Single store mode)
  There is another BUG that leads to almost ALL attributes to be copied for store 1 scope, not JUST the one you updated and, sorry but that sucks. I will ckeck if issue is already reported and eventually post. But poor chance to get a fix on that.

### Debugging
Actually deep debugged code and i think the issue is on Product Model getStoreIds() even if it HARD to admit on such a central class :
Line `$websiteIds = array_keys($websiteIds);` gets array_keys()... ???
Does not have much sense... : Website_ids being either an array from json OR retreived from DB : NO WAY that array_keys would be some website_ids !

Checked current 2.4 develop, still there : https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product.php#L832

### Workaround / I would say "Hack"
To congratulate you for your patience reading me, i offer you this hack if you promise to have a good laugh :

The FACT is that the array_keys() "bug" CAN be used as a temporary workaround hack :
You can pass values so that there will be a key for the targeted website id.
**If you pass twice (here) the website_id in extension attribute, you'll exploit the bug and pass => Will work.**
Hopefully, these arrays are not "cleaned" by any interceptor before being in product data object... Not surprising.

I think you got what you have to do if you want to re-gen website id 4... LOL

```
{
  "product": {
    "custom_attributes": [
        {
            "attribute_code": "url_key",
            "value": "my-url-key-16"
        }
    ],
    "extension_attributes": {
        "website_ids": [
            1,1
        ]
    }
  }
}
```

Exract from Magento\Catalog\Model\Product.php
```
...
public function getStoreIds()
    {
        if (!$this->hasStoreIds()) {
            $storeIds = [];
            if ($websiteIds = $this->getWebsiteIds()) {
                if (!$this->isObjectNew() && $this->_storeManager->isSingleStoreMode()) {
                    $websiteIds = array_keys($websiteIds);
                }
                foreach ($websiteIds as $websiteId) {
                    $websiteStores = $this->_storeManager->getWebsite($websiteId)->getStoreIds();
                    $storeIds[] = $websiteStores;
                }
            }
            if ($storeIds) {
                $storeIds = array_merge(...$storeIds);
            }
            $this->setStoreIds($storeIds);
        }
        return $this->getData('store_ids');
    }
...
```

### PR DESCRIPTION
**Pull request by engcom-Charlie**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30316

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by danielrussob** [comment]
@magento give me test instance

**Comment by danielrussob** [comment]
@magento give me 2.4-develop instance

**Comment by danielrussob** [comment]
Issue reproduced on vanilla 2.4

image

**Comment by danielrussob** [comment]
Issue solved on new instance

SKU: 24-MB01
Payload:
{
  "product": {
    "custom_attributes": [
      {
        "attribute_code": "url_key",
        "value": "nuovissimo-url-key-ahaha"
      }
    ]
  }
}

image

**Comment by danielrussob** [comment]
Checking commit 558d5279f200d4e9753aae715f2d7f4f44a0d5c4 in data 10 september 18 there was a refactor on foreach that could cause bug

image

image

File: app/code/Magento/Catalog/Model/Product.php [hunk 1]
```diff
@@ -828,9 +828,6 @@ public function getStoreIds()
         if (!$this->hasStoreIds()) {
             $storeIds = [];
             if ($websiteIds = $this->getWebsiteIds()) {
-                if (!$this->isObjectNew() && $this->_storeManager->isSingleStoreMode()) {
-                    $websiteIds = array_keys($websiteIds);
```
Comment (aleron75) [inline app/code/Magento/Catalog/Model/Product.php:832]: Hi @engcom-Charlie, thanks for your PR.

I agree that removing this code solves the issue and, as we read in the issue, this code doesn't seem to have any meaning. Actually, @danielrussob found the point in time where the `array_keys` was introduced causing the error.

But there is a unit test asserting that the method `isSingleStoreMode()` is called once; indeed now it fails because the method is no more called.

So in order for this PR to be processed, we also need to remove that expectation from the failing unit test.

Comment (danielrussob) [reply app/code/Magento/Catalog/Model/Product.php:832]: I confirm

**Review by danielrussob — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-8754](https://jira.corp.magento.com/browse/ENGCOM-8754) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin Panel, go to _Stores - Configuration - General_ and set **Single Store Mode** to _Yes_
2. Create a Simple product with setting **URL Key** under _Search Engine Optimization. **Save** the product
seo_product
3. Open Swagger, and perform `{{magento_url}}/rest/all/V1/products/{{sku}}` **PUT** request to change the _URL Key_
```
{
  "product": {
    "custom_attributes": [
        {
            "attribute_code": "url_key",
            "value": "my-new-url"
        }
    ]
  }
}
```
4. Go to _Marketing - URL Rewrites_ and check if the _Request Path_ has been changed for the previously created Simple Product

**BEFORE** applying changes provided in the PR, the _Request Path_ did not change
url_rewrite_before

**AFTER** switching to the PR, the  _Request Path_ changed according to the value set in the PUT request
url_rewrite_after

**Review by danielrussob — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @danielrussob, thank you for the review.
[ENGCOM-8754](https://jira.corp.magento.com/browse/ENGCOM-8754) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The result is the same as in the report above https://github.com/magento/magento2/pull/32009#issuecomment-777419318
