### PR TITLE
Inheriting from a class that doesn't exist#33334

### LINKED ISSUE #33334: Inheriting from a class that doesn't exist
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php#L151

Preconditions:
Install Magento 2.4-develop

Steps to reproduce :
1. Open file magento2/app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php
2. Check line number 151
3. It has a function call getPrice(BundleDiscountPrice::PRICE_CODE), with reference of BundleDiscountPrice class

Expected Result;
The class BundleDiscountPrice must be declare.

Actual Result:
This class is not defined

### PR DESCRIPTION
**Pull request by monteshot**
- Changed PRICE_CODE constant from non-exist class to $this class
This class already have its own constant on 28 line.
const PRICE_CODE = self::CONFIGURED_PRICE_CODE;
The related issue https://github.com/magento/magento2/issues/33334

### Description (*)

The class that responsible for getting price value uses not valid constant.
I was remove incorrect constant and add the constant from this class that can be correctly overrided. 
### Fixed Issues (if relevant)

1. Fixes magento/magento2#33334

### Manual testing scenarios (*)

1. On any properly created bundle product will be executed \Magento\Catalog\Pricing\Render\ConfiguredPriceBox because the 
\Magento\Catalog\Pricing\Price\ConfiguredPriceInterface::CONFIGURED_PRICE_CODE is in Magento\Bundle\Pricing\Price\Pool
2. The render mechanism will found the template app/code/Magento/Catalog/view/base/templates/product/price/configured_price.phtml that will get the class \Magento\Bundle\Pricing\Price\ConfiguredRegularPrice that inherits from \Magento\Bundle\Pricing\Price\ConfiguredPrice with the problem get value method
3. On line 18 of app/code/Magento/Catalog/view/base/templates/product/price/configured_price.phtml will be invoked code from \Magento\Bundle\Pricing\Price\ConfiguredPrice::getValue
4. If item was previously set using setItem the getValue code will throw exception
5. I change to self::PRICE_CODE and code no longer crash
### Questions or comments

Comments:
The class that inherits this class already have the Unit test
\Magento\Catalog\Test\Unit\Pricing\Price\ConfiguredPriceTest but it.
Also i wrote unit for getValue method

Normally on frontend the code with error not invokes. It seems to be fallback.
This code may crash when unit tests executing

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by monteshot** [comment]
@magento run all tests

File: app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php [hunk 1]
```diff
@@ -146,10 +152,9 @@ public function getValue()
     {
         if ($this->item) {
             $configuredOptionsAmount = $this->getConfiguredAmount()->getBaseAmount();
-            return parent::getValue() +
-                $this->priceInfo
-                    ->getPrice(BundleDiscountPrice::PRICE_CODE)
-                    ->calculateDiscount($configuredOptionsAmount);
+            if (!empty($this->item->getProduct())) {
```
Comment (bgorski) [inline app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php]: The `getProduct()` method should always return a product instance according to the interface and its implementations. Therefore this will never be empty. Did you mean to check if the product has an ID? If so, I think this can be simplified to reduce nesting, for example to 
```
if ($this->item && $this->item->getProduct()->getId()) {
    $configuredOptionsAmount = $this->getConfiguredAmount()->getBaseAmount();
    
    return parent::getValue() + $this->discountCalculator->calculateDiscount(
        $this->item->getProduct(),
        $configuredOptionsAmount
    );
}

return parent::getValue();
```

**Review by bgorski — CHANGES_REQUESTED** [review]

File: app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php (hunk 1 above)
Comment (monteshot) [reply app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php]: I did it in this way because $this->item can be the instance of null|ItemInterface. And this interface also implements another models. And as this branch of code is fallback. I did not reserch so deep but i think that "if" statement need to  check only $this->item. Maybe i wrong.
@bgorski

**Comment by monteshot** [comment]
Hello. 
What should i do with this semantic error @bgorski 
image

Thanks.

**Comment by monteshot** [comment]
Neither module.xml nor composer.json i cannot change version because its absent in both files

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @monteshot 
Thank you for your contribution.
Could you please rename your new tests?
The tests are related with Magento\Bundle\Pricing\Price\ConfiguredPrice
I think it should be named Magento\Bundle\Test\Unit\Pricing\Price\ConfiguredPriceTest.
How do you think about it?

**Comment by monteshot** [comment]
@andrewbess my mistake. i'll change the comment of php file

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run Functional Tests B2B

**Comment by monteshot** [comment]
@magento run Adobe CLA Signed?

**Comment by monteshot** [comment]
Unit test fail due a "Flaky test"

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+
+    /**
+     * @var MockObject
+     */
+    protected $calculator;
+
+    /**
+     * @var MockObject
+     */
+    protected $priceInfo;
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]:
```suggestion
    /**
     * @var Base|MockObject
     */
    private $priceInfoMock;
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 3]
```diff
@@ -0,0 +1,182 @@
...
+{
+    /**
+     * @var float
+     */
+    protected $basePriceValue = 100.;
+
+    /**
+     * @var MockObject
+     */
+    protected $item;
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Since these aren't the real objects, I would name the properties with a `Mock` suffix. Also. please mark each property as private.
```suggestion
     * @var ItemInterface|MockObject
     */
    private $itemMock;
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 4]
```diff
@@ -0,0 +1,182 @@
...
+
+    /**
+     * @var MockObject
+     */
+    protected $product;
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]:
```suggestion
     * @var Product|MockObject
     */
    private $productMock;
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+    /**
+     * @var ConfiguredPrice
+     */
+    protected $model;
+
+    /**
+     * @var PriceCurrencyInterface|MockObject
+     */
+    protected $priceCurrencyMock;
+    /**
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Please preserve an empty line after each property.
```suggestion
    protected $priceCurrencyMock;

    /**
```

File: app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php [hunk 6]
```diff
@@ -48,6 +48,10 @@ class ConfiguredPrice extends CatalogPrice\FinalPrice implements ConfiguredPrice
      * @var ConfiguredPriceSelection
      */
     private $configuredPriceSelection;
+    /**
+     * @var \Magento\Bundle\Pricing\Price\DiscountCalculator
```
Comment (eduard13) [inline app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php]: Please preserve an empty row and do not use FQPN. Please import the class name.
```suggestion

    /**
     * @var DiscountCalculator
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 7]
```diff
@@ -0,0 +1,182 @@
...
+            $this->priceCurrencyMock,
+            null,
+            $this->jsonSerializerMock,
+            $this->configuredPriceSelectionMock,
+            $this->discountCalculator,
+        );
+        $this->model->setItem($this->item);
+    }
+
+    private function prepareAndReturnSelectionPriceDataStub()
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Please move the private method after the public ones. Also provide the method's docblock with a short description.
```suggestion
    private function prepareAndReturnSelectionPriceDataStub(): array
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 8]
```diff
@@ -0,0 +1,182 @@
...
+        return [
+            $first,
+            $second
+        ];
+    }
+
+    /**
+     * Test of value getter when item presented
+     */
+    public function testGetValueMethod()
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]:
```suggestion
    public function testGetValueMethod(): void
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 9]
```diff
@@ -0,0 +1,182 @@
...
+    {
+        $valueFromMock = $this->model->getValue();
+        $this->assertEquals(95., $valueFromMock);
+    }
+
+    /**
+     * Test of value getter if no product item
+     */
+    public function testGetValueMethodNoItem()
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]:
```suggestion
    public function testGetValueMethodNoItem(): void
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 10]
```diff
@@ -0,0 +1,182 @@
...
+    {
+        unset($this->item);
+        $this->product = $this->getMockBuilder(Product::class)
+            //->setMethods(['getPriceInfo', 'getOptionById', 'getResource', 'getId'])
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: I believe we can remove the commented out line.

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 11]
```diff
@@ -0,0 +1,182 @@
...
+        $valueFromMock = $this->model->getValue();
+        $this->assertEquals(95., $valueFromMock);
+    }
+
+    /**
+     * Test of value getter if no product item
+     */
+    public function testGetValueMethodNoItem()
+    {
+        unset($this->item);
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Could you please clarify the reason of removing and re-creating the `$this->item` object? Usually for a better structure and clearance, the needed objects should be instantiated within the test case.

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 12]
```diff
@@ -0,0 +1,182 @@
...
+     */
+    private $discountCalculator;
+
+    /**
+     * Initialize base dependencies
+     */
+    protected function setUp(): void
+    {
+        $basePrice = $this->getMockForAbstractClass(PriceInterface::class);
+        $basePrice->expects($this->any())->method('getValue')->willReturn($this->basePriceValue);
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php:91]: Basically the `setUp` method, is used to mock the needed objects, that will be used later by different test cases. Please move all the assertions into a separate test case instead.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @monteshot, thank you for your contribution. Could you please review the below suggestions? Please let me know if there are any concerns or questions.

Thank you.

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php (hunk 12 above)
Comment (monteshot) [reply app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php:91]: Ok. But in setUp I dont have assertions

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run Functional Tests EE

**Comment by monteshot** [comment]
@magento run Functional Tests B2B

**Comment by monteshot** [comment]
@magento run Functional Tests EE

File: app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php [hunk 13]
```diff
@@ -48,6 +48,10 @@ class ConfiguredPrice extends CatalogPrice\FinalPrice implements ConfiguredPrice
      * @var ConfiguredPriceSelection
      */
     private $configuredPriceSelection;
+    /**
```
Comment (eduard13) [inline app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php:52]: You have missed adding an empty line above the property declaration.
```suggestion

    /**
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 14]
```diff
@@ -0,0 +1,185 @@
...
+
+    /**
+     * @var Product|MockObject
+     */
+    private $productMock;
+
+    /**
+     * @var MockObject
+     */
+    private $calculator;
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]:
```suggestion
    /**
     * @var Calculator|MockObject
     */
    private $calculatorMock;
```

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 15]
```diff
@@ -0,0 +1,185 @@
...
+        $this->productMock = $this->getMockBuilder(Product::class)
+            ->setMethods(['getPriceInfo', 'getOptionById', 'getResource', 'getId'])
+            ->disableOriginalConstructor()
+            ->getMock();
+        $this->productMock->expects($this->once())->method('getPriceInfo')->willReturn($this->priceInfoMock);
+        $this->productMock->expects($this->any())->method('getId')->willReturn(123);
+
+        $this->itemMock = $this->getMockBuilder(ItemInterface::class)
+            ->getMock();
+        $this->itemMock->expects($this->any())->method('getProduct')->willReturn($this->productMock);
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: I believe it would be much better if you will move this part to `testGetValueMethod` method.

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 16]
```diff
@@ -0,0 +1,185 @@
...
+            $this->productMock,
+            1,
+            $this->calculator,
+            $this->priceCurrencyMock,
+            null,
+            $this->jsonSerializerMock,
+            $this->configuredPriceSelectionMock,
+            $this->discountCalculatorMock,
+        );
+        $this->model->setItem($this->itemMock);
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Same this, should be in `testGetValueMethod`, as it represents a different case that you cover in `testGetValueMethodNoItem`

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php [hunk 17]
```diff
@@ -0,0 +1,185 @@
...
+
+/**
+ * Test for \Magento\Bundle\Pricing\Price\ConfiguredPrice
+ */
+class ConfiguredPriceTest extends TestCase
+{
+    /**
+     * @var float
+     */
+    private $basePriceValue = 100.;
```
Comment (eduard13) [inline app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Is there any reason of not specifying the decimals as well (and in the other parts as well)?

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @monteshot, please check the below suggestions. Looks like it were missed some of the previous ones. 
Moreover, could you please provide the exact steps to reproduce the mentioned issue (maybe some piece of code)? Just to be easier to test this one.

Thank you.

File: app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php (hunk 17 above)
Comment (monteshot) [reply app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: > Hi @monteshot, please check the below suggestions. Looks like it were missed some of the previous ones.
> Moreover, could you please provide the exact steps to reproduce the mentioned issue (maybe some piece of code)? Just to be easier to test this one.
> 
> Thank you.

This code executes on bundle product page. But i think the code in the configured price class is some type of fallback.

This code invokes in renderrer in \Magento\Catalog\Pricing\Render\FinalPriceBox block
image

I did debug only if i emulate some data that will allow proceed to the if statement
image
image

@eduard13

Comment (monteshot) [reply app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: image

Comment (monteshot) [reply app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: > Is there any reason of not specifying the decimals as well (and in the other parts as well)?

No reason. I will add decimal after the point

Comment (monteshot) [reply app/code/Magento/Bundle/Test/Unit/Pricing/Price/ConfiguredPriceTest.php]: Additionally you may check the original task to get steps to reproduce
https://github.com/magento/magento2/issues/33334#issue-929044829

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run Functional Tests CE

**Comment by monteshot** [comment]
@magento run Functional Tests CE

**Comment by monteshot** [comment]
@magento run Functional Tests CE

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run Unit Tests

File: app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php (hunk 13 above)
Comment (monteshot) [reply app/code/Magento/Bundle/Pricing/Price/ConfiguredPrice.php:52]: I have add the missing line but github not see it

**Comment by monteshot** [comment]
> Hello @monteshot
> Thank you for your contribution.
> Could you please rename your new tests?
> The tests are related with Magento\Bundle\Pricing\Price\ConfiguredPrice
> I think it should be named Magento\Bundle\Test\Unit\Pricing\Price\ConfiguredPriceTest.
> How do you think about it?

I have rename the test class to appropriate name

**Review by bgorski — APPROVED** [review]
Looks good to me and all the tests are passing - clicking the approve button. Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9161](https://jira.corp.magento.com/browse/ENGCOM-9161) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9161](https://jira.corp.magento.com/browse/ENGCOM-9161) has been created to process this Pull Request

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by monteshot** [comment]
image
Another flaky test failed
@engcom-Hotel I will restart tests

**Comment by monteshot** [comment]
@magento run Functional Tests EE
