### PR TITLE
[32279][GraphQL] Fixed issue with tier price 

### LINKED ISSUE #32279: Graphql price tiers returning data from previous item in foreach
### Preconditions 

1. Clean Magento 2.4.2 with sample data
1. 2.4-develop

### Steps to reproduce (*)

1. Install clean Magento 2.4.2 with sample data
1. Add tier pricing to any item (for this example we added tier prices to items ID 1 & 2)
1. run Graphql query with search that will include the item with tier prices and items without tier prices
```
{
  products(pageSize: 20, currentPage: 1, search: "24-MB0") {
    items {
      id
      price_tiers {
        quantity
        final_price {
          value
        }
      }
    }
  }
}
{code}

### Expected result (*)

1. Items with tier price return correct tier pricing, items without tier pricing return no tier prices
{code}
{{
{
    "data": {
        "products": {
            "items": <
                {
                    "id": 42,
                    "price_tiers": []
                },
				...
                {
                    "id": 17,
                    "price_tiers": []
                },
                {
                    "id": 1,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 23,
                    "price_tiers": []
                },
                {
                    "id": 19,
                    "price_tiers": []
                },
				...
            ]
        }
    }
}
}}
{code}

### Actual result (*)

1. All items coming after an item with tier pricing have tier pricing in the response
1. The tier pricing data that it's returning is from the last item in the loop that had tier pricing
1. in our example, items ID 1 & ID 2 are the only ones that have tier pricing, yet here is the result

{code}
{
    "data": {
        "products": {
            "items": [
                {
                    "id": 42,
                    "price_tiers": []
                },
                {
                    "id": 2046,
                    "price_tiers": []
                },
                {
                    "id": 11,
                    "price_tiers": []
                },
                {
                    "id": 12,
                    "price_tiers": []
                },
                {
                    "id": 6,
                    "price_tiers": []
                },
                {
                    "id": 3,
                    "price_tiers": []
                },
                {
                    "id": 41,
                    "price_tiers": []
                },
                {
                    "id": 18,
                    "price_tiers": []
                },
                {
                    "id": 39,
                    "price_tiers": []
                },
                {
                    "id": 17,
                    "price_tiers": []
                },
                {
                    "id": 1,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 23,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 19,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 8,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 13,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 15,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 16,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 22,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 43,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                },
                {
                    "id": 44,
                    "price_tiers": [
                        {
                            "quantity": 1,
                            "final_price": {
                                "value": 34
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 32
                            }
                        }
                    ]
                }
            >
        }
    }
}
```

1. The issue started happening since commit https://github.com/magento/magento2/commit/b2021d55c022719af7adec3f5e5fb6b1776e6fef#diff-8d1c1372668a97ccd40b222f73acfe4c6b5ce24ad261215306610ae8817cdc65 

cc: @Usik2203 

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- <x] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes issue https://github.com/magento/magento2/issues/32279 
(**Confirmed issue case** https://github.com/magento/magento2/issues/32279#issuecomment-786684071)
### Preconditions
Tier price was added for product with name 
`banana` and `banana-1`

**BEFORE:**
Screenshot 2021-03-03 at 13 36 48
**AFTER:**
Screenshot 2021-03-03 at 13 38 58

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32279

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 1]
```diff
@@ -152,7 +155,7 @@ private function formatAndFilterTierPrices(
         array $tierPrices,
         string $currencyCode
     ): array {
-
+        $this->resetFormatAndFilterTierPrices();
```
Comment (eduard13) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: Why not simply cleaning the `formatAndFilterTierPrices`? Any concerns about that?
```suggestion
        $this->formatAndFilterTierPrices = [];
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 2]
```diff
@@ -117,6 +117,34 @@ public function testGetLowestPriceForGuest()
         $this->assertEquals(round(7.25, 2), $this->getValueForQuantity(8, $itemTiers));
     }
 
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/three_simple_products_with_tier_price.php
+     */
+    public function testGetCorrectDisplaingTierPriceForProducts()
```
Comment (eduard13) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: Most probably we'll have to improve the test coverage, by having at least 1 product without tierPrices, in order to make sure it doesn't return anything.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Usik2203, could you please review the comments below?

Thank you.

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 1 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: Hi @eduard13 
Unfortunately this approach isn't working in this case 
We are losing some data
We will get tier price only for first item in this case 
**Example:**
Screenshot 2021-03-03 at 15 51 11
But actually  `banana-1` product has tier price

Comment (eduard13) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: But, I think you do the same in `resetFormatAndFilterTierPrices ` below, cleaning the `formatAndFilterTierPrices`. Am I wrong?

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by SirCoolness** [comment]
@magento give me test instance

**Comment by Usik2203** [comment]
@magento run WebAPI Tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Static Tests

**Comment by eduard13** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php (hunk 2 above)
Comment (Usik2203) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: **DONE ** 
Added one product  without tier price.

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 1 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: Hi @eduard13 
Yes you are right. It was my mistake 🤦 
Fixed this one 
Thanks!

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 3]
```diff
@@ -117,6 +117,40 @@ public function testGetLowestPriceForGuest()
         $this->assertEquals(round(7.25, 2), $this->getValueForQuantity(8, $itemTiers));
     }
 
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/simple_product_without_tier_price.php
```
Comment (eduard13) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: Just wondering, why can't we use any already existing fixture that doesn't have tier prices? For example:
- dev/tests/integration/testsuite/Magento/Catalog/_files/second_product_simple.php
- dev/tests/integration/testsuite/Magento/Catalog/_files/product_simple_tax_none.php

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 4]
```diff
@@ -117,6 +117,40 @@ public function testGetLowestPriceForGuest()
...
+}
+QUERY;
+        $response = $this->graphQlQuery($query);
+        foreach ($response['products']['items'] as $key => $item) {
+            if ($item['sku'] == 'simple_19') {
+                $this->assertCount(0, $response['products']['items'][$key]['price_tiers']);
+            }
+            if (in_array($item['sku'], ['simple_1','simple_2','simple_3'])) {
+                $this->assertCount(1, $response['products']['items'][$key]['price_tiers']);
+            }
```
Comment (eduard13) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: For a better code readability, I would refactor it this way. In case you have a better and cleaner way, feel free to implement it.

```suggestion
            $productsWithTierPrices = ['simple_1','simple_2','simple_3'];
            
            if (in_array($item['sku'], $productsWithTierPrices)) {
                $this->assertCount(1, $response['products']['items'][$key]['price_tiers']);
            } else {
                $this->assertCount(0, $response['products']['items'][$key]['price_tiers']);
            }
```

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Usik2203 could you please review my below minor adjustments? Feel free to reach me, if there are any questions.

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by eduard13** [comment]
@magento run Functional Tests B2B, Functional Tests EE

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 5]
```diff
@@ -117,6 +117,41 @@ public function testGetLowestPriceForGuest()
         $this->assertEquals(round(7.25, 2), $this->getValueForQuantity(8, $itemTiers));
     }
 
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/second_product_simple.php
+     * @magentoApiDataFixture Magento/Catalog/_files/three_simple_products_with_tier_price.php
+     */
+    public function testGetCorrectDisplaingTierPriceForProducts()
```
Comment (eduard13) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: There is a typo within test name, so let's adjust it into something like:
```suggestion
    public function testProductTierPricesAreCorrectlyReturned()
```

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests EE

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8985](https://jira.corp.magento.com/browse/ENGCOM-8985) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  **QA passed**

:x: **Before**
{
   "data": {
       "products": {
           "items": [
               {
                   "id": 2,
                   "price_tiers": [
                       {
                           "quantity": 3,
                           "final_price": {
                               "value": 140
                           }
                       },
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 130
                           }
                       }
                   ]
               },
               {
                   "id": 1,
                   "price_tiers": [
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 130
                           }
                       },
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 90
                           }
                       },
                       {
                           "quantity": 10,
                           "final_price": {
                               "value": 80
                           }
                       }
                   ]
               },
               {
                   "id": 6,
                   "price_tiers": [
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 130
                           }
                       },
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 90
                           }
                       },
                       {
                           "quantity": 10,
                           "final_price": {
                               "value": 80
                           }
                       }
                   ]
               },
               {
                   "id": 5,
                   "price_tiers": [
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 130
                           }
                       },
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 90
                           }
                       },
                       {
                           "quantity": 10,
                           "final_price": {
                               "value": 80
                           }
                       }
                   ]
               },
               {
                   "id": 4,
                   "price_tiers": [
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 130
                           }
                       },
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 90
                           }
                       },
                       {
                           "quantity": 10,
                           "final_price": {
                               "value": 80
                           }
                       }
                   ]
               },
               {
                   "id": 3,
                   "price_tiers": [
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 130
                           }
                       },
                       {
                           "quantity": 5,
                           "final_price": {
                               "value": 90
                           }
                       },
                       {
                           "quantity": 10,
                           "final_price": {
                               "value": 80
                           }
                       }
                   ]
               }
           ]
       }
   }
}

:heavy_check_mark:  **After:**
{
    "data": {
        "products": {
            "items": [
                {
                    "id": 2,
                    "price_tiers": [
                        {
                            "quantity": 3,
                            "final_price": {
                                "value": 140
                            }
                        },
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 130
                            }
                        }
                    ]
                },
                {
                    "id": 1,
                    "price_tiers": [
                        {
                            "quantity": 5,
                            "final_price": {
                                "value": 90
                            }
                        },
                        {
                            "quantity": 10,
                            "final_price": {
                                "value": 80
                            }
                        }
                    ]
                },
                {
                    "id": 6,
                    "price_tiers": []
                },
                {
                    "id": 5,
                    "price_tiers": []
                },
                {
                    "id": 4,
                    "price_tiers": []
                },
                {
                    "id": 3,
                    "price_tiers": []
                }
            ]
        }
    }
}
