### PR TITLE
magento/magento2#37039: Not generating 301 redirects for product

### LINKED ISSUE #37039: Moving a category to a new parent does not generate 301 redirects for product URLs
### Preconditions and environment

- Magento 2.4.6 and potentially all prior versions

### Steps to reproduce

1. Install any recent version of Magento (2.4.4 - 2.4.6)
2. Enable the following settings under Catalog -> Catalog -> SEO
Screenshot 2023-03-08 at 1 16 39 PM
3. Create two categories under the root category with one child category under the first one.
4. Create a product and assign it to the child category.
5. Enable all categories and products.
6. Using the drag & drop feature of the category tree, move the child category to be underneath the second parent you created.
7. Navigate to Marketing -> URL Rewrites, and observe that a 301 redirect was created for the original category URL, but not for the original product URL within the original parent category.

### Expected result

A 301 redirect will be created for every category / product URL path within the original parent category pointing to the new category / product path under the new parent category.
Frontend visitors will get redirected to the new product URL path if they try to access the original path.

### Actual result

A 301 redirect was created from the old category path to the new one, but no redirects were created for product URLs.
Frontend visitors receive a 404 if they try to access the original product URL path.

### Additional information

The issue appears to lie in this observer `Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteMovingObserver`.
It calls this method `$this->urlRewriteHandler->deleteCategoryRewritesForChildren($category)`, which results in the product level rewrites being deleted before this method is run `$productUrlRewriteResult = $this->urlRewriteHandler->generateProductUrlRewrites($category)`, which looks for those rewrites for the purpose of creating 301 redirects.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by yaroslav-kozar**
fixed issue with generating 301 redirects for product after moving a category to a new parent

According to #37039 observer declared in  \Magento\CatalogUrlRewrite\Observer\CategoryProcessUrlRewriteMovingObserver.php has not proper order of actions for generating 301 redirects for products.

### Description (*)
- Fix for generating url rewrites for product before deleting category rewrites for children

### Related Pull Requests
no

### Fixed Issues (if relevant)
1. Fixes magento/magento2#37039

### Manual testing scenarios (*)
1 Go to Stores > Settings > Configuration > Catalog > Catalog > Search Engine Optimization
2. Make sure that configs: "Use Categories Path for Product URLs", "Generate "category/product" URL Rewrites" and "Create Permanent Redirect for URLs if URL Key Changed" set as "Yes"
3.Create 2 categories under the "Default" category,  on the same level and then create a new one as a sub-category of one that you just created.
4.Create a new product and assign it to the sub-category that you have created on step 3 of this guide
5.Open on a storefront your product, which should contins the path like `<Base URL>/<category-url-key>/<sub-category-url-key>/<product-url-key>.<Product URL Suffix>`
6.Go back to the admin and move with "drag and drop functionality" your sub-category to another category that you created on step 2.
7.Go to the storefront and reload your URL (from step 5) and it will redirect you to the new category(if you use my PR) or you wil get 404 error without this PR.

### Questions or commens
Additionaly I noticed that when indexer "catalog_category_product" configured as "update on save"  and if you act as I described in block "Manual testing scenarios", so in that case after moving sub-category for both created categories the indexer "catalogsearch_fulltext" not reindexed or even not invalidated. That's leading us to bad storefront look as the first category does not contain new products from recently moved sub-category and the second one stil contains those products in it. This issue is causing \Magento\Elasticsearch\Model\Indexer\Fulltext\Plugin\Category\Product\Action\Rows by this class on line 79 as there exists condition for scheduled indexer 
image
Please let me know if it should be removed, so I will add a new PR for this as for now I'm confusing as it can increase save timeout Or should I invalidate related index?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
Unit Test app/code/Magento/Reports/Test/Unit/Model/ResourceModel/Order/CollectionTest.php is not related to my PR.

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests CE

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests EE

**Comment by Yaroslav1301** [comment]
1. Unit Test app/code/Magento/Reports/Test/Unit/Model/ResourceModel/Order/CollectionTest.php is not related to my PR.
2. Test WebAPI  Magento\AsynchronousOperations\Api\OperationRepositoryInterfaceTest::testBulkGetListByStartTime not related to my PR
3. Functional Tests CE,Functional Tests EE failures are different on last two run on same commit:
Run 1 Functional Tests CE
image
Run 1 Functional Tests EE
image
Run 2 Functional Tests CE
image
Run 2 Functional Tests CE
image

File: app/code/Magento/CatalogUrlRewrite/Observer/CategoryProcessUrlRewriteMovingObserver.php [hunk 1]
```diff
@@ -103,13 +103,19 @@ public function execute(\Magento\Framework\Event\Observer $observer)
                 ScopeInterface::SCOPE_STORE,
                 $category->getStoreId()
             );
+            $catProdRewritesEn = $this->isCategoryRewritesEnabled();
```
Comment (hostep) [inline app/code/Magento/CatalogUrlRewrite/Observer/CategoryProcessUrlRewriteMovingObserver.php]: Please use readable non-abreviated variable names, `cat` and `prod` are understandable, but `en` isn't. So in this case I would suggest `$catProdRewritesEnabled`.

Thanks! 🙂

Comment (yaroslav-kozar) [reply app/code/Magento/CatalogUrlRewrite/Observer/CategoryProcessUrlRewriteMovingObserver.php]: Hi @hostep. Thank you for reviewing my PR. I have added my chnages regarding the variable name. However I replaced it to $catRewritesEnabled because it contains less than 20 symbols, so phpmd passed that checking successfully.

Thanks for your attention!

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Yaroslav1301** [comment]
Functional Tests CE, Functional Tests B2B failures are different on last two run on same commit:
Run 1 Functional Tests CE
image
Run 1 Functional Tests B2B
image

Run 2 Functional Tests CE
image
Run 2 Functional Tests B2B
image

Functional Tests EE not related to my PR
image

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests B2B

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Yaroslav1301,

Please cover the changes with some automated tests.

Thanks

**Comment by Yaroslav1301** [comment]
https://github.com/magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run all tests

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]

**Comment by Yaroslav1301** [comment]
@magento run  Functional Tests B2B, Functional Tests EE

**Comment by Yaroslav1301** [comment]
Functional Tests B2B,Functional Tests EE failures are different on last two run on same commit:
Run 1 Functional Tests EE
image
Run 2 Functional Tests EE
image


Run 1 Functional Tests B2B
image
Run 2 Functional Tests B2B
image

**Comment by Yaroslav1301** [comment]
@engcom-Hotel  Hello! The is some problem with Integration Tests. It's executing 2 days and cannot finish. Is there some way how to fix it?

**Comment by engcom-Hotel** [comment]
Hello @Yaroslav1301,

Just checked Jenkins, and it seems the build is stuck due to some temporary issue. Try to rerun the tests.

Thanks

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Go to **Stores > Settings > Configuration > Catalog > Catalog > Search Engine Optimization**
2. Make sure that configs: "Use Categories Path for Product URLs", "Generate "category/product" URL Rewrites" and "Create Permanent Redirect for URLs if URL Key Changed" set as "Yes"
3. Create two categories under the root category with one child category under the first one.
4. Create a product and assign it to the child category.
5. Enable all categories and products.
6. Using the drag & drop feature of the category tree, move the child category to be underneath the second parent you created.
7. Navigate to Marketing -> URL Rewrites, and observe that a 301 redirect was created for the original category URL, but not for the original product URL within the original parent category.

**Before:** :heavy_multiplication_x: Getting error as 404 in Frontend.
Screenshot 2023-05-03 at 5 06 30 PM


**After:** :heavy_check_mark:  
Screenshot 2023-05-03 at 5 12 15 PM

Builds are failed. Hence, moving this PR to **Extended Testing**

**Comment by Yaroslav1301** [comment]
@magento run Integration Tests

**Comment by Yaroslav1301** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by Yaroslav1301** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B failures are different on last two run on same commit.
Run1
image

Run2
image
