### PR TITLE
Resolve Export Coupon Code Grid redirect to DashBoard when create New Cart Price Rule issue24468

### LINKED ISSUE #24468: Export Coupon Code Grid redirect to DashBoard when create New Cart Price Rule
Coupon Grid in create new "Cart Price Rule" should be disabled. Because it is useless and when exporting, it has the error: 

### Preconditions (*)

1. Magento 2.3-develop

### Steps to reproduce (*)

1. Go to backend
2. Marketing-> Cart Price Rules, Create New Cart Price Rule
3. In " Coupon" choose Specific Coupon
4. Check "Use Auto Generation"
5. Scroll to Manage Coupon Codes
6. Export

### Expected result (*)

1. I think Should be disable the Grid, because in the New Cart Price Rule, there is No Coupon Code what is generated

### Actual result (*)

1. Redirect to dashboard
2.
image

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Coupon Grid in create new "Cart Price Rule" should be disabled. Because it is useless and when exporting, it has the error

Solution: Hide the grid when create new 

1. Resolve magento/magento2#24468: Export Coupon Code Grid redirect to DashBoard when create New Cart Price Rule

### Fixed Issues (if relevant)

1. magento/magento2#24468: Export Coupon Code Grid redirect to DashBoard when create New Cart Price Rule

### Manual testing scenarios (*)

1. Go to backend
2. Marketing-> Cart Price Rules, Create New Cart Price Rule
3. In " Coupon" choose Specific Coupon
4. Check "Use Auto Generation"
5. Scroll to Manage Coupon Codes
6. Export

#### Expected result (*)

1. Should export empty file

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
No introduce the Public function, because it already in the Parent Class

File: app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons/Grid.php [hunk 1]
```diff
@@ -151,4 +152,16 @@ public function getGridUrl()
     {
         return $this->getUrl('sales_rule/*/couponsGrid', ['_current' => true]);
     }
+
+    /**
+     * @inheritdoc
+     */
+    public function toHtml()
```
Comment (dmytro-ch) [inline app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons/Grid.php]: @edenduong, could you please verify if it's possible to solve the mentioned issue by overriding the `_toHtml` method instead of `toHtml`?
If not, then let's leave it as it is.

Thank you!

**Review by dmytro-ch — CHANGES_REQUESTED** [review]

File: app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons/Grid.php (hunk 1 above)
Comment (edenduong) [reply app/code/Magento/SalesRule/Block/Adminhtml/Promo/Quote/Edit/Tab/Coupons/Grid.php]: Hello @dmytro-ch ,

I have changed the source code to _toHtml(). Please check it again.

Thanks

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5822](https://jira.corp.magento.com/browse/ENGCOM-5822) has been created to process this Pull Request
:eight_spoked_asterisk: @dmytro-ch, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
Hi @edenduong ,

During testing we faced with the issue.

_**Problem:**_  JS error message occurs when we click on "Generate" button

**Steps to reproduce:**
1. Login to Admin;
2. Go to Marketing->Cart Price Rules->Add New Rule;
3. Fill all required fields;
4. Select "Specific Coupon" from  "Coupon" drop-down menu;
5. Mark :heavy_check_mark: "Use Auto Generation" checkbox;
6. Go to "Manage Coupon Codes " tab;
7. Fill "Coupon Qty" field and click on "Generate" button;

**Actual Result:** JS error message occurs
after

@edenduong Could you take a look, please?

Thanks!

**Comment by edenduong** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [new Magento instance](https://pr-24471.instances.magento-community.engineering).
Admin access: [https://pr-24471.instances.magento-community.engineering/admin](https://pr-24471.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by edenduong** [comment]
Hi @engcom-Alfa, @dmytro-ch : I fixed it. Please check it again.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5822](https://jira.corp.magento.com/browse/ENGCOM-5822) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Review by sidolov — CHANGES_REQUESTED** [review]
@edenduong after a closer look, we found that it would be better disable Manage Coupon Codes grid controls or fix Export button functionality to handle cases when the grid is empty.

**Comment by VladimirZaets** [comment]
@edenduong can you take a look at it?

**Comment by edenduong** [comment]
Hi @VladimirZaets : I have changed the source code. I fixed Export button functionality to handle cases when the grid is empty instead of hide the grid.

**Comment by slavvka** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @slavvka. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @slavvka, here is your [new Magento instance](https://pr-24471.instances.magento-community.engineering).
Admin access: [https://pr-24471.instances.magento-community.engineering/admin](https://pr-24471.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5822](https://jira.corp.magento.com/browse/ENGCOM-5822) has been created to process this Pull Request

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-5822](https://jira.corp.magento.com/browse/ENGCOM-5822) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed
