### PR TITLE
Fix for queue numeric argument conversion

### LINKED ISSUE #29615: [Issue] Fix for queue numeric argument conversion
This issue is automatically created based on existing pull request: magento/magento2#26967: Fix for queue numeric argument conversion

---------

### Description (*)

Magento 2.4-develop

If we want to declare queue (I bet this also occurs the same way for exchanges) with arguments and we use numeric type argument in `queue_topology.xml` it is casted to string and in corrected file it gets wrapped in incorrect type for rabbit. Example of configuration:

```
 <exchange name="test.dead_letter" type="topic" connection="amqp">
        <binding id="test" topic="#" destinationType="queue"
                 destination="test_dead_letter">
            <arguments>
                <argument name="x-dead-letter-exchange" xsi:type="string">test.retry</argument>
                <argument name="x-message-ttl" xsi:type="number">36000</argument>
            </arguments>
        </binding>
    </exchange>
```

Of course using string type doesn't help as we get also string. While creating such a queue we get error similar to:
`PRECONDITION_FAILED - inequivalent arg 'x-message-ttl'for queue 'test_dead_letter' in vhost '\': received the value '36000' of type 'longstr' but current is none`.

If PR will be accepted, please port to 2.3 as well.

### Related Pull Requests

This one has to be fixed first, as for now we are not able to declare queue with ANY parameters
https://github.com/magento/magento2/pull/26966

### Manual testing scenarios (*)

1. Declare queue with numeric argument, for example x-message-ttl
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by bartoszkubicki**
### Description (*)

If we want to declare queue (I bet this also occurs the same way for exchanges) with arguments and we use numeric type argument in `queue_topology.xml` it is casted to string and in corrected file it gets wrapped in incorrect type for rabbit. Example of configuration:

```
 <exchange name="test.dead_letter" type="topic" connection="amqp">
        <binding id="test" topic="#" destinationType="queue"
                 destination="test_dead_letter">
            <arguments>
                <argument name="x-dead-letter-exchange" xsi:type="string">test.retry</argument>
                <argument name="x-message-ttl" xsi:type="number">36000</argument>
            </arguments>
        </binding>
    </exchange>
```

Of course using string type doesn't help as we get also string. While creating such a queue we get error similar to:
`PRECONDITION_FAILED - inequivalent arg 'x-message-ttl'for queue 'test_dead_letter' in vhost '\': received the value '36000' of type 'longstr' but current is none`.

If PR will be accepted, please port to 2.3 as well.

### Related Pull Requests

This one has to be fixed first, as for now we are not able to declare queue with ANY parameters
https://github.com/magento/magento2/pull/26966

### Manual testing scenarios (*)

1. Declare queue with numeric argument, for example x-message-ttl
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29615: Fix for queue numeric argument conversion

### CODE REVIEW

File: lib/internal/Magento/Framework/Amqp/Topology/ArgumentProcessor.php [hunk 1]
```diff
@@ -17,22 +22,25 @@ trait ArgumentProcessor
...
      * @return array
      */
-    public function processArguments($arguments)
+    public function processArguments($arguments): array
     {
         $output = [];
         foreach ($arguments as $key => $value) {
             if (is_array($value)) {
                 $output[$key] = ['A', $value];
             } elseif (is_int($value)) {
```
Comment (naydav) [inline lib/internal/Magento/Framework/Amqp/Topology/ArgumentProcessor.php]: In this case, using only `is_numeric` will be enough.
Thanks

Comment (bartoszkubicki) [reply lib/internal/Magento/Framework/Amqp/Topology/ArgumentProcessor.php]: you mean in scope of this PR is_int check should be removed, while keeping is_numeric check?

Comment (bartoszkubicki) [reply lib/internal/Magento/Framework/Amqp/Topology/ArgumentProcessor.php]: up

**Comment by sidolov** [comment]
@magento create issue

File: lib/internal/Magento/Framework/Amqp/Topology/ArgumentProcessor.php (hunk 1 above)
Comment (sidolov) [reply lib/internal/Magento/Framework/Amqp/Topology/ArgumentProcessor.php]: @bartoszkubicki Yes, you are right, is_int check can be removed.

**Review by sidolov — CHANGES_REQUESTED** [review]

**Comment by bartoszkubicki** [comment]
@naydav @sidolov corrected

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@bartoszkubicki could you please cover changes with automated tests?

**Comment by bartoszkubicki** [comment]
@sidolov I have added unit test

**Comment by bartoszkubicki** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
The risk was set to`medium` due to: the suggested changes are made on the framework and may affect other areas/modules.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8155](https://jira.corp.magento.com/browse/ENGCOM-8155) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8155](https://jira.corp.magento.com/browse/ENGCOM-8155) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
Dependent on 
#https://github.com/magento/magento2/pull/26966

**Comment by engcom-Bravo** [comment]
Dev experience is required for testing of this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Bravo** [comment]
Dev experience is required for testing of this PR. Please note that Manual testing has not been performed.

**Comment by engcom-Foxtrot** [comment]
On hold until https://github.com/magento/magento2/pull/26966 is merged.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by bartoszkubicki** [comment]
@engcom-Foxtrot I have possible fix for failing integration test. As it seems from the report, order of key-values differes between result and expected. I replaced assertSame with checking array differences by array_diff_assoc, but let's see if merging branch helps here.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Moving state.

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8155](https://jira.corp.magento.com/browse/ENGCOM-8155) has been created to process this Pull Request

**Comment by bartoszkubicki** [comment]
Ok, I have pushed possible fix for integration test. I could not test it quickly right now, because my local copy is broken somehow after last merging 2.4-develop into it. Fix seemed to be simple, so I decided to give it a shot. I will reinstall it anyway and if it wouldn't work I will fix it.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by bartoszkubicki** [comment]
@magento run integration tests

File: dev/tests/integration/testsuite/Magento/Framework/MessageQueue/TopologyTest.php [hunk 2]
```diff
@@ -121,7 +132,7 @@ public function exchangeDataProvider()
                         'arguments' => [
                             'argument1' => 'value',
                             'argument2' => true,
-                            'argument3' => 150,
+                            'argument3' => '150',
```
Comment (engcom-Foxtrot) [inline dev/tests/integration/testsuite/Magento/Framework/MessageQueue/TopologyTest.php]: The idea is to assert argument3 is a number.

**Review by engcom-Foxtrot — CHANGES_REQUESTED** [review]

**Comment by bartoszkubicki** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by engcom-Foxtrot — APPROVED** [review]

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Comment by bartoszkubicki** [comment]
Please port it to Magento 2.3
