### PR TITLE
magento/magento2#39481: Completely removing a gallery-image from be k…

### LINKED ISSUE #39481: Completely removing a gallery-image from be keeps scope roles/types set (base/small/thumbnail) and after re-adding "old" roles/types appear
### Preconditions and environment

PRECONDITIONS:
- magento version: 2.4.7
- magento installation with at least 2 store views

### Steps to reproduce

- add a simple product
- add an image in the default scope and select "base" type/role
- make sure the type/role has been inherited by the store-scopes
- remove or change types/roles in a store_view scope (i.e. remove the "base" type/role)
- completely remove the gallery image (from scopes and from default)
- re-add a new image in the default scope and flag the type/role "base"

### Expected result

- in the store scopes the images inherit the roles/types of the new added image as per the default scope

### Actual result

- if we previously removed the "base" type/role in a specific store-view, even if the image was completely removed from the gallery, after re-adding the image now in the specific store-scope the type/roles are the ones of the old (removed) image instead the ones of the default image (we expected inheritance)

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pavel77718**
### Description (*)

- fixed inheritance of the role of a deleted image after adding a new one

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39481

### Manual testing scenarios (*)

1. add a simple product
2. add an image in the default scope and select "base" type/role
3. make sure the type/role has been inherited by the store-scopes
4. remove or change types/roles in a store_view scope (i.e. remove the "base" type/role)
5. completely remove the gallery image (from scopes and from default)
6. re-add a new image in the default scope and flag the type/role "base"

### Expected result

After adding a new image, the roles will be set by default.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Unit Tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Functional Tests EE

**Comment by pavel77718** [comment]
@magento run Functional Tests EE

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Functional Tests EE

**Comment by pavel77718** [comment]
@mahento run Functional Tests EE

**Comment by pavel77718** [comment]
@magento run Functional Tests EE

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Database Compare, Functional Tests B2B, Functional EE

**Comment by pavel77718** [comment]
@magento run Functional Tests EE

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by pavel77718** [comment]
@magento run all tests

**Comment by pavel77718** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js]: This could be 2013, as the file has been created in this year only

File: app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js [hunk 2]
```diff
@@ -355,6 +355,11 @@ define([
             imageData.isRemoved = true;
             $imageContainer.addClass('removed').hide().find('.is-removed').val(1);
 
+            $.each(this.options.types, $.proxy(function (index, type) {
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js:361]: Suggesting to add an comment for this newly added code block, so that in future developer can relate with it.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @pavel77718,

Thanks for the contribution!

The code changes seems good to us, but please check my review comments below and add some automated test to verify the PR changes.

Thanks

File: app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js (hunk 2 above)
Comment (pavel77718) [reply app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js:361]: I added a comment for the new code block.

File: app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js (hunk 1 above)
Comment (pavel77718) [reply app/code/Magento/Catalog/view/adminhtml/web/js/product-gallery.js]: I changed it.

**Comment by pavel77718** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by pavel77718** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Bravo** [comment]
Hi @pavel77718,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- add a simple product
- add an image in the default scope and select "base" type/role
- make sure the type/role has been inherited by the store-scopes
- remove or change types/roles in a store_view scope (i.e. remove the "base" type/role)
- completely remove the gallery image (from scopes and from default)
- re-add a new image in the default scope and flag the type/role "base"



**Before:** :heavy_multiplication_x: 

Simple-Products-Inventory-Catalog-Magento-Admin-04-01-2025_01_22_PM




**After:** :heavy_check_mark: 


COnfigureeee-Products-Inventory-Catalog-Magento-Admin-04-01-2025_01_57_PM



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Two of the tests in Functional B2B failures are not consistent. Neither failing because of the PR changes nor part of PR. They seem to be flaky. One of the consistent test is a known issue and has a JIRA for the same. Hence moving this PR to Merge in Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39680/eac7c210ad926437da04b1f956347988/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/7b345b9f066fe118/

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39680/6e93581c6813f37e768cd8d38e65c401/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/f2def3f54579f7ae/

image


**Known Issue:**
[ACQE-7751](https://jira.corp.adobe.com/browse/ACQE-7751) : CatalogPriceRuleAndCustomerGroupMembershipArePersistedUnderLongTermCookieTest
