### PR TITLE
Newrelic api change

### LINKED ISSUE #32649: [Issue] Newrelic api change
This issue is automatically created based on existing pull request: magento/magento2#32648: Newrelic api change

---------
### Description (*)

New Relic has an possibility to setup deployment markers. 
But this feature is not working anymore, cause NewRelic changed API some time ago and current implementation is useless.

I changed Modue to work with a new API.

More info:
https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/

### Fixed Issues (if relevant)
Fixed Deployment functionality for NewRelic module

### Manual testing scenarios (*)

1. Deployment marker can be sent manually from CMD: bin/magento newrelic:create:deploy-marker "Name" "Description" "Email", "Release"
2. Every time Cache flushed, marker is set

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by nuzil**
### Description (*)

New Relic has an possibility to setup deployment markers. 
But this feature is not working anymore, cause NewRelic changed API some time ago and current implementation is useless.

I changed Modue to work with a new API.

More info:
https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/

### Fixed Issues (if relevant)
Fixed Deployment functionality for NewRelic module

### Manual testing scenarios (*)

1. Deployment marker can be sent manually from CMD: bin/magento newrelic:create:deploy-marker "Name" "Description" "Email", "Release"
2. Every time Cache flushed, marker is set

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32649: Newrelic api change

### CODE REVIEW

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento create issue

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests

File: app/code/Magento/NewRelicReporting/Model/Apm/Deployments.php [hunk 1]
```diff
@@ -15,7 +15,7 @@ class Deployments
     /**
      * API URL for New Relic deployments
      */
-    const API_URL = 'https://api.newrelic.com/deployments.xml';
+    const API_URL = 'https://api.newrelic.com/v2/applications/%s/deployments.json';
```
Comment (swnsma) [inline app/code/Magento/NewRelicReporting/Model/Apm/Deployments.php:18]: Should we take value from config (app/code/Magento/NewRelicReporting/etc/config.xml) ?

**Review by swnsma — CHANGES_REQUESTED** [review]

File: app/code/Magento/NewRelicReporting/Model/Apm/Deployments.php (hunk 1 above)
Comment (nuzil) [reply app/code/Magento/NewRelicReporting/Model/Apm/Deployments.php:18]: Hey @swnsma 
We do, 

```
$apiUrl = $this->config->getNewRelicApiUrl();
        if (empty($apiUrl)) {
            $this->logger->notice('New Relic API URL is blank, using fallback URL');
            $apiUrl = self::API_URL;
        }
```

I see that config.xml is exists in module and cannot be empty in this case, but also may happen that somebody already extended module and for some reason using constant. So I would leave it there

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8998](https://jira.corp.magento.com/browse/ENGCOM-8998) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
Hi @nuzil
Thanks for your contribution and collaboration.

I am flushed after I hit the command  php bin/magento newrelic:create:deploy-marker "manju1_deply1" "System.log".
The log file is not having the information about marker being set. can you please how you are validating the marker being set/no.

**Comment by engcom-Alfa** [comment]
> Hi @nuzil
> Thanks for your contribution and collaboration.
> 
> I am flushed after I hit the command php bin/magento newrelic:create:deploy-marker "manju1_deply1" "System.log".
> The log file is not having the information about marker being set. can you please how you are validating the marker being
> Thanks in advance

Ok, Seems I have to do some missing configurations, will come back soon! thanks!

**Comment by engcom-Alfa** [comment]
Hi @nuzil 
Thanks for your contribution and collaboration on this, I am able to proceed ahead after slack discussion with you. Thanks for all the help :)
