### PR TITLE
magento/magento2#28579:DependencyTest does not analyze GraphQL schema…

### LINKED ISSUE #28579: DependencyTest does not analyze GraphQL schema files
Steps to reproduce:
* Add new GraphQl module which will extend existing schema
* Add dependencies to the module.xml
* Only schema refers to dependencies

(/) Test is green
(-) Test fails with `Redundant dependencies found!`

### PR DESCRIPTION
**Pull request by sasha19957099**
… files - added tests and missing dependency for SwatchesGraphQl module

### Related Pull Requests
https://github.com/magento/partners-magento2-infrastructure/pull/8

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run Magento Health Index
@magento run Static Tests

**Comment by sasha19957099** [comment]
@magento run Static Tests

**Comment by sasha19957099** [comment]
Here is a problem. Running static tests on the Magento build we don't have Magento app instance. It is a cause of failing static tests https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/28747/3fbd463f86fe3e705dc9d439abe63716/Statics/allure-report-ee/index.html#categories/f8421ffb12c0de5091bdf17e30c0fef2/1774e386c6824151/
So interface Magento\Framework\GraphQlSchemaStitching\GraphQlReader\TypeMetaReaderInterface can't be instantiated. How we can solve it?

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php [hunk 1]
```diff
@@ -705,54 +579,8 @@ private function getModuleName(string $packageName): ?string
      * @param $mapType
      * @return array
      */
-    private function getDeclaredDependencies(string $module, string $type, string $mapType)
+    protected function getDeclaredDependencies(string $module, string $type, string $mapType)
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php]: do we really need this? we try to stay away from "protected"

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php [hunk 2]
```diff
@@ -0,0 +1,207 @@
...
+
+    /**
+     * Retrieve array of dependency items.
+     *
+     * @param $module
+     * @param $type
+     * @param $mapType
+     * @return array
+     */
+    abstract protected function getDeclaredDependencies(string $module, string $type, string $mapType);
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: this is the template pattern, but we try to stay away from abstract and protected
Use composition instead

File: lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader.php [hunk 3]
```diff
@@ -285,4 +294,58 @@ private function removePlaceholderFromResults(array $partialResults) : array
...
+     *
+     * @param array $source
+     * @param string $filePath
+     * @return array
+     */
+    private function addModuleNameToTypes(array $source, string $filePath): array
+    {
+        foreach ($source as $typeName => $type) {
+            if (!isset($type['module']) && (
+                ($type['type'] == 'graphql_interface' && isset($type['typeResolver']))
```
Comment (cpartica) [inline lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader.php]: can these strings like "graphql_interface" be referenced by some constant?

File: lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader.php [hunk 4]
```diff
@@ -285,4 +294,58 @@ private function removePlaceholderFromResults(array $partialResults) : array
...
+     */
+    private static function getModuleNameForRelevantFile($file)
+    {
+        if (!isset(self::$componentRegistrar)) {
+            self::$componentRegistrar = new ComponentRegistrar();
+        }
+        // Validates file when it belongs to default themes
+        foreach (self::$componentRegistrar->getPaths(ComponentRegistrar::THEME) as $themeDir) {
+            if (strpos($file, $themeDir . '/') !== false) {
+                return '';
```
Comment (cpartica) [inline lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader.php]: it's hard to follow a method with multiple returns, 
try to limit to one return

File: dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php [hunk 5]
```diff
@@ -783,14 +784,16 @@ function (&$moduleName) {
     public function collectRedundant()
     {
         $schemaDependencyProvider = new DeclarativeSchemaDependencyProvider();
+        $graphQlSchemaDependencyProvider = new GraphQlSchemaDependencyProvider();
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php]: is it necessary to use "new" here? don't know if you have access to object manager here..

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+     * Provide undeclared dependencies between modules based on the declarative schema configuration.
+     *
+     * [
+     *     $dependencyId => [$module1, $module2, $module3 ...],
+     *     ...
+     * ]
+     *
+     * @param string $moduleName
+     * @return array
+     * @throws \Exception
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php]: should not throw simple exceptions
https://devdocs.magento.com/guides/v2.2/coding-standards/technical-guidelines.html#5-exceptions

**Review by cpartica — CHANGES_REQUESTED** [review]

File: dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php (hunk 5 above)
Comment (sasha19957099) [reply dev/tests/static/testsuite/Magento/Test/Integrity/DependencyTest.php:787]: I think yes, all objects in this file are created by "new".

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php [hunk 7]
```diff
@@ -83,15 +68,20 @@ class DeclarativeSchemaDependencyProvider
      */
     public function getDeclaredExistingModuleDependencies(string $moduleName): array
     {
-        $this->initDeclaredDependencies();
+        $this->dependencyProvider->initDeclaredDependencies();
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php]: why can't you init dependencies the first time that we get something?
this makes this class mutable. What happends if somebody that uses this class forget to call init?
It basically uses temporal coupling, which we discourage

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by sasha19957099** [comment]
@magento run all tests

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php (hunk 7 above)
Comment (sasha19957099) [reply dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php]: fixed

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php [hunk 8]
```diff
@@ -0,0 +1,212 @@
...
+    private $packageModuleMapping = [];
+
+    /**
+     * DependencyProvider constructor.
+     * @throws \Magento\Framework\Exception\LocalizedException
+     * @throws \Magento\TestFramework\Inspection\Exception
+     */
+    public function __construct()
+    {
+        $this->initDeclaredDependencies();
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: this would make this class instantiate very slowly unless you use a Proxy class.
the other solution would be to call init before calling addDependencies or getDeclaredDependencies. basically any public method of this class

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php (hunk 8 above)
Comment (sasha19957099) [reply dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: yes, you're right, changed to the proxy.

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php [hunk 9]
```diff
@@ -0,0 +1,212 @@
...
+
+use Magento\Framework\App\Utility\Files;
+use Magento\Framework\Component\ComponentRegistrar;
+
+class DependencyProvider
+{
+    /**
+     * Types of dependency between modules.
+     */
+    const TYPE_HARD = 'hard';
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: looks like we have a new requirement to add "public" to const @see https://github.com/magento/magento2/pull/28713/files#diff-16beb87a670284151b84072a3fc8cc4dR17

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php [hunk 10]
```diff
@@ -0,0 +1,212 @@
...
+
+    /**
+     * @var array
+     */
+    private $packageModuleMapping = [];
+
+    /**
+     * DependencyProvider constructor.
+     * @throws \Magento\Framework\Exception\LocalizedException
+     * @throws \Magento\TestFramework\Inspection\Exception
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: try to add all namespaces and move the to a "use" statement

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php [hunk 11]
```diff
@@ -57,22 +42,26 @@ class DeclarativeSchemaDependencyProvider
...
     /**
-     * @var array
+     * @var DependencyProvider
      */
-    private $packageModuleMapping = [];
+    private $dependencyProvider;
 
     /**
-     * @var array
+     * DeclarativeSchemaDependencyProvider constructor.
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DeclarativeSchemaDependencyProvider.php]: you don't need a comment description in constructors

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php [hunk 12]
```diff
@@ -0,0 +1,157 @@
...
+    private $dependencyProvider;
+
+    /**
+     * GraphQlSchemaDependencyProvider constructor.
+     * @param \Magento\Test\Integrity\Dependency\DependencyProvider\Proxy $dependencyProvider
+     */
+    public function __construct(\Magento\Test\Integrity\Dependency\DependencyProvider\Proxy $dependencyProvider)
+    {
+        $this->dependencyProvider = $dependencyProvider;
+        $this->getGraphQlSchemaDeclaration();
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php]: this will again do constructor processing delaying instantiation of the class

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php (hunk 8 above)
Comment (cpartica) [reply dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: what I meant that instead of using a proxy ..better call that initDeclaredDependencies within addDependencies and getDeclaredDependencies and remove it from constructor.
It's even better than a proxy.

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php [hunk 13]
```diff
@@ -0,0 +1,157 @@
...
+        $schema = $this->parsedSchema;
+
+        $dependencies = [];
+
+        foreach ($schema as $type) {
+            if (isset($type['module']) && $type['module'] == $moduleName && isset($type['implements'])) {
+                $interfaces = array_keys($type['implements']);
+                foreach ($interfaces as $interface) {
+                    $dependOnModule = $schema[$interface]['module'];
+                    if ($dependOnModule != $moduleName) {
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php]: !==

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php [hunk 14]
```diff
@@ -0,0 +1,157 @@
...
+     * @return array
+     */
+    private function getDependenciesFromSchema(string $moduleName): array
+    {
+        $schema = $this->parsedSchema;
+
+        $dependencies = [];
+
+        foreach ($schema as $type) {
+            if (isset($type['module']) && $type['module'] == $moduleName && isset($type['implements'])) {
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/GraphQlSchemaDependencyProvider.php]: ===

File: lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader.php [hunk 15]
```diff
@@ -285,4 +296,51 @@ private function removePlaceholderFromResults(array $partialResults) : array
...
+            self::$componentRegistrar = new ComponentRegistrar();
+        }
+        $foundModuleName = '';
+        foreach (self::$componentRegistrar->getPaths(ComponentRegistrar::MODULE) as $moduleName => $moduleDir) {
+            if (strpos($file, $moduleDir . '/') !== false) {
+                $foundModuleName = str_replace('_', '\\', $moduleName);
+                break;
+            }
+        }
+        if (empty($foundModuleName)) {
```
Comment (cpartica) [inline lib/internal/Magento/Framework/GraphQlSchemaStitching/GraphQlReader.php]: isn't $foundModuleName = ''; already empty if not set by foreach?

**Review by cpartica — CHANGES_REQUESTED** [review]

File: dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php (hunk 8 above)
Comment (danielrenaud) [reply dev/tests/static/testsuite/Magento/Test/Integrity/Dependency/DependencyProvider.php]: to avoid using an init in the constructor you can move it into the method where it is needed.
e.g.
```
function getDependencies(){
    if(empty($dependencies)){
        doInit();
    }
    return $this->dependencies;
}
```

**Comment by sasha19957099** [comment]
@magento run Static Tests

**Comment by sasha19957099** [comment]
@magento run Static Tests

**Comment by sasha19957099** [comment]
@magento run Static Tests

**Comment by sasha19957099** [comment]
@magento run Static Tests

**Comment by sasha19957099** [comment]
@magento run all tests

File: dev/tests/static/testsuite/Magento/Test/Integrity/DeclarativeDependencyTest.php [hunk 16]
```diff
@@ -131,14 +138,13 @@ private function getErrorMessage(string $id): string
...
-     * @throws \Exception
+     * @throws InspectionException
      */
     private function readJsonFile(string $file, bool $asArray = false)
     {
         $decodedJson = json_decode(file_get_contents($file), $asArray);
         if (null == $decodedJson) {
-            //phpcs:ignore Magento2.Exceptions.DirectThrow
-            throw new \Exception("Invalid Json: $file");
+            throw new InspectionException("Invalid Json: $file");
```
Comment (cpartica) [inline dev/tests/static/testsuite/Magento/Test/Integrity/DeclarativeDependencyTest.php:147]: missed this, we usually do a localized exception that's translatable and any parameters like file go into a "%1" or "%s" if using sprintf. 
This is probably fine because it's a test.  But "Invalid Json: $file" would still be a risky practice and sprintf would be preferred.

**Review by cpartica — APPROVED** [review]
