### PR TITLE
Bundle products options input validation

### LINKED ISSUE #26110: Bundle product with option type radio and dropdown can be added to the cart with multiple choices
### Preconditions (*)

1. Sample Data

### Steps to reproduce (*)

1. Add product to the cart
```graphql
mutation addBundle(
  $cart_id: String!
) {
  addBundleProductsToCart(
    input: {
      cart_id: $cart_id
      cart_items: {
        data: {
          quantity: 1
          sku: "24-WG080"
        }
        bundle_options: [
          {
            id: 1
            quantity: 1
            value: [
              "1"
              "2"
              "3"
            ]
          }
          {
            id: 2
            quantity: 1
            value: [
              "4"
            ]
          }
                    {
            id: 3
            quantity: 1
            value: [
              "5"
            ]
          }
                    {
            id: 4
            quantity: 1
            value: [
              "8"
            ]
          }
        ]
      }
    }
  ) {
    cart {
      items {
        id
        quantity
        product {
          sku
        }
        ... on BundleCartItem {
          bundle_options {
            id
            label
            type
            values {
              id
              label
              quantity
              __typename
            }
          }
        }
      }
    }
  }
}
```

### Expected result (*)

1. Some message that complains about invalid input for BundleItem.type: radio/dropdown

### Actual result (*)

1. Successfully added to cart

### Additional information 
The issue was confirmed again on the lates `2.4-develop` code. May 28, 2020
In general it is possible to add to Shopping Cart and place order with option type radio and dropdown with multiple choices. This flow is not possible using UI on Storefront.
More details: https://github.com/magento/magento2/issues/26110#issuecomment-635308289

### PR DESCRIPTION
**Pull request by michalderlatka**
### Description (*)
Validates input for radio and select type options. 

### Fixed Issues (if relevant)
1. Fixes magento/magento2#26110

### Manual testing scenarios (*)
Follow instructions from related issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by michalderlatka** [comment]
@magento run all tests

**Comment by michalderlatka** [comment]
@magento run all tests

File: app/code/Magento/Bundle/Model/Product/Type.php [hunk 1]
```diff
@@ -1272,6 +1277,40 @@ protected function checkIsAllRequiredOptions($product, $isStrictProcessMode, $op
...
 
+    /**
+     * Validate Options for Radio and Select input types
+     *
+     * @param \Magento\Bundle\Model\ResourceModel\Option\Collection $optionsCollection
+     * @param int[] $options
+     * @return void
+     * @throws \Magento\Framework\Exception\LocalizedException
+     */
+    protected function validateRadioAndSelectOptions($optionsCollection, $options): void
```
Comment (cpartica) [inline app/code/Magento/Bundle/Model/Product/Type.php]: don't add protected, use private

File: app/code/Magento/Bundle/Model/Product/Type.php [hunk 2]
```diff
@@ -1272,6 +1277,40 @@ protected function checkIsAllRequiredOptions($product, $isStrictProcessMode, $op
...
+    {
+        $errorTypes = [];
+
+        if (is_array($optionsCollection->getItems())) {
+            foreach ($optionsCollection->getItems() as $option) {
+                if (($option->getType() == 'radio' || $option->getType() == 'select') &&
```
Comment (cpartica) [inline app/code/Magento/Bundle/Model/Product/Type.php]: that is a big condition, can you move that to a method with a meaningful name?

File: app/code/Magento/Bundle/Model/Product/Type.php [hunk 3]
```diff
@@ -1272,6 +1277,40 @@ protected function checkIsAllRequiredOptions($product, $isStrictProcessMode, $op
         }
     }
 
+    /**
+     * Validate Options for Radio and Select input types
+     *
+     * @param \Magento\Bundle\Model\ResourceModel\Option\Collection $optionsCollection
```
Comment (cpartica) [inline app/code/Magento/Bundle/Model/Product/Type.php]: do "use Magento\Bundle\Model\ResourceModel\Option\Collection" and only use "Collection"

File: app/code/Magento/Bundle/Model/Product/Type.php [hunk 4]
```diff
@@ -1272,6 +1277,40 @@ protected function checkIsAllRequiredOptions($product, $isStrictProcessMode, $op
         }
     }
 
+    /**
+     * Validate Options for Radio and Select input types
```
Comment (cpartica) [inline app/code/Magento/Bundle/Model/Product/Type.php:1283]: add some kind of a test for this, either unit or integration, or webapi

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by lbajsarowicz** [comment]
Hi @michalderlatka . Nice to see another contributor from Poland.
Please review the Maintainer comments and feel free to share your thoughts.

**Comment by michalderlatka** [comment]
@magento run all tests

**Comment by michalderlatka** [comment]
@magento run static tests

**Review by cpartica — APPROVED** [review]

**Comment by cpartica** [comment]
@magento run all tests

**Review by cpartica — CHANGES_REQUESTED** [review]
Some static fails, but also some possible performance problems:

PHP Code Sniffer detected 2 violation(s): 

FILE: /var/www/html/app/code/Magento/Bundle/Model/Product/Type.php
----------------------------------------------------------------------
FOUND 1 ERROR AND 4 WARNINGS AFFECTING 5 LINES
----------------------------------------------------------------------
  398 | WARNING | [ ] Function's nesting level (6) exceeds 5;
      |         |     consider refactoring the function
  535 | ERROR   | [x] Tags visual alignment must be consistent
 1194 | WARNING | [ ] Empty FUNCTION statement detected
 1212 | WARNING | [ ] array_merge(...) is used in a loop and is a
      |         |     resources greedy construction.
 1393 | WARNING | [ ] array_merge(...) is used in a loop and is a
      |         |     resources greedy construction.
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

The following files incorrectly reuse fixtures:
/var/www/html/dev/tests/integration/testsuite/Magento/Bundle/_files/product_with_multiple_options_radio_select.php
/var/www/html/dev/tests/integration/testsuite/Magento/Bundle/_files/product_with_multiple_options_radio_select_rollback.php
Please use Magento\TestFramework\Workaround\Override\Fixture\Resolver::requireDataFixture
Failed asserting that 2 matches expected 0.

File: app/code/Magento/Bundle/Model/Product/Type.php [hunk 5]
```diff
@@ -459,12 +461,12 @@ public function getOptionsIds($product)
      * Retrieve bundle option collection
      *
      * @param \Magento\Catalog\Model\Product $product
-     * @return \Magento\Bundle\Model\ResourceModel\Option\Collection
```
Comment (cpartica) [inline app/code/Magento/Bundle/Model/Product/Type.php]: SVC is failing because of this, but I will approve it, it's a false positive

File: app/code/Magento/Bundle/Model/Product/Type.php [hunk 6]
```diff
@@ -887,7 +894,7 @@ public function getSelectionsByIds($selectionIds, $product)
      *
      * @param array $optionIds
      * @param \Magento\Catalog\Model\Product $product
-     * @return \Magento\Bundle\Model\ResourceModel\Option\Collection
```
Comment (cpartica) [inline app/code/Magento/Bundle/Model/Product/Type.php]: SVC is failing because of this, but I will approve it, it's a false positive

**Comment by michalderlatka** [comment]
@magento run all tests

**Comment by michalderlatka** [comment]
@magento run Functional Tests B2B

**Review by cpartica — APPROVED** [review]

**Comment by cpartica** [comment]
@magento run Functional Tests B2B

**Comment by cpartica** [comment]
@magento run Functional Tests EE
