### PR TITLE
Resolve "Clear Shopping Cart" button not working in Internet Explorer issue24491

### LINKED ISSUE #24491: "Clear Shopping Cart" button not working in Internet Explorer
### Preconditions (*)

1. Magento Commerce 2.3.2
2. PHP 7.2.21

### Steps to reproduce (*)

1. Open Magento 2 site in Internet Explorer
2. Add item to the cart
3. Click `Clear Shopping Cart` button

### Expected result (*)

1. All items are deleted from the shopping cart
2. The cart page is refreshed showing no items

### Actual result (*)

1. The page refreshes and all cart items are still in the cart

The issue is caused by line 18 of `app/code/Magento/Checkout/view/frontend/web/js/shopping-cart.js`. The on click handler for the `Clear Shopping Cart` button checks if `event.detail` is 0 before proceeding. There is a bug in Internet Explorer 11 that causes the `event.detail` attribute to always be 0. As a result, you cannot clear the cart in IE.

Here is the IE bug report explaining that `event.detail` will not be fixed: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16710370/

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Resolve magento/magento2#24491: "Clear Shopping Cart" button not working in Internet Explorer 

The problem:

in this PR: https://github.com/magento/magento2/issues/21499 "Cart is emptied when enter is pressed after changing product quantity". This code is added to `app/code/Magento/Checkout/view/frontend/web/js/shopping-cart.js`

```
                if (event.detail === 0) {
                    return;
                }

```

However, IE 11 can not support `event.detail`. It always return 0

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/16710370/

I believe when enter is pressed after changing product quantity we Shouldn't trigger click **"emptyCartButton"** and check the condition. I will be wrong. We should change the button empty cart to "button", not "submit". So button isn't clicked when press enter.

In my PR, I have changed it to normal button and process the empty cart only the user click to the "Clear shopping cart" button.

### Fixed Issues (if relevant)

1. magento/magento2#24491: "Clear Shopping Cart" button not working in Internet Explorer 

### Manual testing scenarios (*)

Change Magento Theme to **BLANK**

1. Open Magento 2 site in Internet Explorer
2. Add item to the cart
3. Click `Clear Shopping Cart` button

### Expected result (*)

1. All items are deleted from the shopping cart
2. The cart page is refreshed showing no items

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-5807](https://jira.corp.magento.com/browse/ENGCOM-5807) has been created to process this Pull Request

**Comment by dmytro-ch** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, here is your [Magento instance](https://i-24499-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24499-2-3-develop.instances.magento-community.engineering/admin](https://i-24499-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5807](https://jira.corp.magento.com/browse/ENGCOM-5807) has been created to process this Pull Request

File: app/code/Magento/Checkout/view/frontend/web/js/shopping-cart.js [hunk 1]
```diff
@@ -14,14 +14,14 @@ define([
...
-                if (event.detail === 0) {
-                    return;
-                }
-
+            $(this.options.emptyCartButton).on('click', $.proxy(function () {
                 $(this.options.emptyCartButton).attr('name', 'update_cart_action_temp');
                 $(this.options.updateCartActionContainer)
                     .attr('name', 'update_cart_action').attr('value', 'empty_cart');
+
+                if ($(this.options.emptyCartButton).parents('form').length > 0) {
```
Comment (DrewML) [inline app/code/Magento/Checkout/view/frontend/web/js/shopping-cart.js:22]: Can you describe why this fixes the reported bug?

Comment (edenduong) [reply app/code/Magento/Checkout/view/frontend/web/js/shopping-cart.js:22]: @DrewML: I remove `event.detail == 0 ` because it isn't supported by IE.11.

`event.detail` code is added to fix the bug https://github.com/magento/magento2/issues/21499. 

I removed it and changed to other solution to fix issue 21499. When the cart is updated, it should't call the emptyCartButton. So I change it to "button" element. So the emptyCartButton isn't trigger click when the qty is update.

**Comment by engcom-Alfa** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [new Magento instance](https://pr-24499.instances.magento-community.engineering).
Admin access: [https://pr-24499.instances.magento-community.engineering/admin](https://pr-24499.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by engcom-Alfa** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @engcom-Alfa, here is your [Magento instance](https://i-24499-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-24499-2-3-develop.instances.magento-community.engineering/admin](https://i-24499-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed
