### PR TITLE
Set correct parent transaction ID for Payflow delayed capture

### LINKED ISSUE #30870: PayPal Payflow Pro performs delayed capture with incorrect parent transaction ID
Shortly after updating to Magento 2.3.6, our client had a large volume of customers report they had been "charged twice." After investigating this, we found these customers had a lingering authorization (pending transaction) on their cards, in addition to a charge for the full amount of the order. The authorization remains until it expires, typically 30 days.

We found that [changes to the Magento_Paypal module introduced in Magento 2.3.6](https://github.com/magento/magento2/commit/24481e96c171a51ca326f107ca76662bdec8732d#diff-7198862901baba9a4936f420cf43203f92e1e221c341489f966eb69467f163ebR206) caused the incorrect parent transaction ID to be used when performing a delayed capture. Instead of using the order's authorization as the parent transaction ID (behavior prior to Magento 2.3.6), the $0.00 vault token authorization for the payment is used as the parent transaction ID.

This causes the authorization to remain open until it expires, and the transaction sent to Payflow is not associated to the original order authorization. Additionally, the transaction displays in Payflow as "Capture" instead of "Delayed Capture". 

Merchants with "Payment Action" set to "Sale" are likely not impacted, but we have not tested this.

### Preconditions (*)

1. Magento Open Source >= 2.3.6
3. magento/module-paypal >= 100.3.6

### Steps to reproduce (*)

1. Set up PayPal Payflow Pro gateway with "Payment Action" set to "Authorization"
2. Place an order with a credit card
3. Capture the order's payment by creating an invoice and choosing to Capture Online

### Expected result (*)

payflow-transaction-correct-delayed-capture
1. Magento Transaction is created with parent transaction ID of the authorization created at checkout
2. A "Delayed Capture" transaction is sent to Payflow with a parent transaction ID of the authorization created at checkout
3. Customer observes a new charge on their credit card for the amount of the invoice
4. Customer observes pending transaction disappear from their card immediately, or within several days

### Actual result (*)

payflow-transaction-incorrect-capture
1. Magento Transaction is created with parent transaction ID of the authorization created at checkout
2. A **"Sale"** transaction is sent to Payflow with a parent transaction ID of the **vault token created at checkout**
3. Customer observes a new charge on their credit card for the amount of the invoice
4. **Customer observes pending transaction remain on their card for over a week, and until it expires, typically in 30 days**
5. Customer contacts merchant and reports they have been "charged twice"

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by aaronsilber**
### Description (*)

Correct the parent transaction ID used in PayPal Payflow capture and authorization, partially reverting [modified behavior introduced in Magento 2.3.6](https://github.com/magento/magento2/commit/24481e96c171a51ca326f107ca76662bdec8732d).

### Related Pull Requests

n/a

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30870

### Manual testing scenarios (*)

1. Set up PayPal Payflow Pro gateway with "Payment Action" set to "Authorization"
2. Place an order with a credit card
3. Capture the order's payment by creating an invoice and choosing to Capture Online

#### Expected result before merging
1. Magento Transaction is created with parent transaction ID of the authorization created at checkout
2. A **"Sale"** transaction is sent to Payflow with a parent transaction ID of the **vault token created at checkout**
3. Customer observes a new charge on their credit card for the amount of the invoice
4. **Customer observes pending transaction remain on their card for over a week, and until it expires, typically in 30 days**
5. Customer contacts merchant and reports they have been "charged twice"

#### Expected result after merge
1. Magento Transaction is created with parent transaction ID of the authorization created at checkout
2. A "Delayed Capture" transaction is sent to Payflow with a parent transaction ID of the authorization created at checkout
3. Customer observes a new charge on their credit card for the amount of the invoice
4. Customer observes pending transaction disappear from their card immediately, or within several days

### Questions or comments

It would be great to have someone that worked [MC-32494](https://github.com/magento/magento2/commit/24481e96c171a51ca326f107ca76662bdec8732d) review this PR to ensure it doesn't trigger the original issue resolved by that commit.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by aaronsilber** [comment]
@magento run all tests

**Comment by aleron75** [comment]
>It would be great to have someone that worked MC-32494 review this PR to ensure it doesn't trigger the original issue resolved by that commit.

cc @yelahin-serhiy

**Comment by gabrieldagama** [comment]
@magento run all tests

File: app/code/Magento/Paypal/Model/Payflow/Transparent.php [hunk 1]
```diff
@@ -328,19 +324,11 @@ public function capture(InfoInterface $payment, $amount)
         }
 
         /** @var Payment $payment */
-        $zeroAmountAuthorizationId = $this->getZeroAmountAuthorizationId($payment);
-        /** @var PaymentTokenInterface $vaultPaymentToken */
-        $vaultPaymentToken = $payment->getExtensionAttributes()->getVaultPaymentToken();
-        if ($vaultPaymentToken && empty($zeroAmountAuthorizationId)) {
```
Comment (viktym) [inline app/code/Magento/Paypal/Model/Payflow/Transparent.php:334]: @aaronsilber  Actually, to fix the issue it's enough to replace lines 334-339 with

```
 if ($vaultPaymentToken && empty($zeroAmountAuthorizationId) && empty($payment->getParentTransactionId())) {
            $payment->setAdditionalInformation(self::PNREF, $vaultPaymentToken->getGatewayToken());
            $payment->setParentTransactionId($vaultPaymentToken->getGatewayToken());
 }
```
It will cover a case when we don't have $payment->getAdditionalInformation(self::PNREF) while accepting payment marked as Suspected Fraud. 
When you have a successful authorization transaction $payment->getParentTransactionId() won't be empty.

Please try this solution and revert all other changes in case of success.

File: app/code/Magento/Paypal/Model/Payflow/Transparent.php [hunk 2]
```diff
@@ -203,9 +203,9 @@ public function authorize(InfoInterface $payment, $amount)
         $payPalCart = $this->payPalCartFactory->create(['salesModel' => $order]);
         $payPalCart->getAmounts();
 
-        $parentTransactionId = $vaultPaymentToken ? $vaultPaymentToken->getGatewayToken() : $zeroAmountAuthorizationId;
+        $token = $payment->getAdditionalInformation(self::PNREF);
```
Comment (viktym) [inline app/code/Magento/Paypal/Model/Payflow/Transparent.php]: This change will break a case when the order is in Suspected Fraud status and Admin user accepts payment.
\Magento\Paypal\Model\Payflow\Transparent::acceptPayment method calls \Magento\Paypal\Model\Payflow\Transparent::capture and there is no $payment->getAdditionalInformation(self::PNREF) value on this stage. So we need to take reference transaction id from stored token.

**Review by viktym — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
Hello @aaronsilber, I've noticed that you are not actively working on this pull request anymore, would you like to continue with it? Please let us know otherwise we will continue with it.
Thanks!

**Comment by aaronsilber** [comment]
Hey @engcom-Charlie - thanks for the ping, some things came up over the last week, but I'll be able to test @viktym's suggested changes by Monday. Let me know if you'd prefer I commit a partial revert, or rebase my commit and force push it up to this branch to make those changes.

File: app/code/Magento/Paypal/Model/Payflow/Transparent.php (hunk 1 above)
Comment (aaronsilber) [reply app/code/Magento/Paypal/Model/Payflow/Transparent.php:334]: @viktym Very good points, thanks for reviewing. I tested your proposed change on its own, and it resolves this perfectly on the site we encountered this originally on. Updating the PR to reflect this.

File: app/code/Magento/Paypal/Model/Payflow/Transparent.php (hunk 2 above)
Comment (aaronsilber) [reply app/code/Magento/Paypal/Model/Payflow/Transparent.php]: @viktym Makes sense. Updating PR to remove this change.

**Comment by aaronsilber** [comment]
@magento run all tests

**Comment by aaronsilber** [comment]
@magento give me test instance

**Comment by aaronsilber** [comment]
Tested these changes on a fresh Magento instance and confirmed the updates to the PR still resolve #30870. Thanks to @viktym for the review and recommended changes.

It's not clear why any of the automated tests are failing, I reviewed the Allure reports and didn't see any failure items.

@engcom-Charlie This should be all set from my end - let me know if you need anything else to keep the ball rolling.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi, @aaronsilber thanks for updating the PR. @engcom-Foxtrot can we cover these changes with automated tests?

Thanks!

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by viktym — APPROVED** [review]

**Comment by sdzhepa** [comment]
The changes were tested by the Magento team in the scope of `MC-42279`
