### PR TITLE
Passing arguments for queues as expected

### LINKED ISSUE #30216: [Issue] Passing arguments for queues as expected
This issue is automatically created based on existing pull request: magento/magento2#26966: Passing arguments for queues as expected

---------

### Description (*)

According to [docs](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/config-mq.html#queuetopologyxml) it should be possible to declare queue with arguments (like dead-letter-exchange or message-ttl). Unfortunately during process of setting up rabbite schema, arguments are lost and queues are declared without any arguments.

It is because [here](https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php#L115) arguements are always empty array. PR fixes this and also adds return type and some minor formatting fixes. If there are any tests for these class I will fix them as soon as bug will be reproduced, confirmed and my solution will be accepted.
If PR will be accepted, please port to 2.3 as well.

### Preconditions (*)
Magento 2.4-develop

### Steps to reproduce (*)

1. Create some schema for rabbit using magento xml `queue_topology.xml`, like in dev docs.
2. Check if queue is declared in rabbit with arguments (for testing use real arguments like message ttl)

### Expected result (*)
Que is declared 

### Actual result (*)
Que is not declared

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by bartoszkubicki**
### Description (*)

According to [docs](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/config-mq.html#queuetopologyxml) it should be possible to declare queue with arguments (like dead-letter-exchange or message-ttl). Unfortunately during process of setting up rabbite schema, arguments are lost and queues are declared without any arguments.

It is because [here](https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php#L115) arguements are always empty array. PR fixes this and also adds return type and some minor formatting fixes. If there are any tests for these class I will fix them as soon as bug will be reproduced, confirmed and my solution will be accepted.
If PR will be accepted, please port to 2.3 as well.

### Manual testing scenarios (*)

1. Create some schema for rabbit using magento xml `queue_topology.xml`, like in dev docs.
2. Check if queue is declared in rabbit with arguments (for testing use real arguments like message ttl)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30216: Passing arguments for queues as expected

### CODE REVIEW

**Comment by bartoszkubicki** [comment]
Static tests seems to fail because of some copy-paste in EE. I have encountered this failure in multiple PR opened.

File: lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php [hunk 1]
```diff
@@ -59,21 +62,28 @@ public function __construct(
...
                     if ($binding['destinationType'] === 'queue') {
-                        $queueItems = $this->createQueueItems($binding['destination'], $binding['topic'], $connection);
-                        $this->mappedData = array_merge($this->mappedData, $queueItems);
+                        $queueItems = $this->createQueueItems(
+                            (string) $binding['destination'],
+                            (string) $binding['topic'],
+                            (array) $binding['arguments'],
+                            (string) $connection
+                        );
+                        $this->mappedData += $queueItems;
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php]: Unfortunately it might be not an equal to the array_merge. Could you fix it as described here https://github.com/magento/magento-coding-standard/blob/develop/Magento2/Sniffs/Performance/ForeachArrayMergeSniff.md?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Hi @bartoszkubicki,
We're really sorry for long waiting for processing this PR. I'm taking this PR and will try to push it forward.

From first looks changes looks good, but need to see the test results and analyze a bit deeper.

**Comment by ihor-sviziev** [comment]
@magento create issue

File: lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php [hunk 2]
```diff
@@ -17,17 +21,17 @@
 class DataMapperTest extends TestCase
 {
     /**
-     * @var MockObject
+     * @var Data|MockObject
      */
     private $configData;
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php]: Could you add "Mock" suffix to all property names that contains mock object?

File: lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php [hunk 3]
```diff
@@ -59,21 +62,28 @@ public function __construct(
...
         if (null === $this->mappedData) {
             $this->mappedData = [];
             foreach ($this->configData->get() as $exchange) {
                 $connection = $exchange['connection'];
                 foreach ($exchange['bindings'] as $binding) {
                     if ($binding['destinationType'] === 'queue') {
-                        $queueItems = $this->createQueueItems($binding['destination'], $binding['topic'], $connection);
-                        $this->mappedData = array_merge($this->mappedData, $queueItems);
+                        $queueItems = $this->createQueueItems(
+                            (string) $binding['destination'],
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php]: 1. Could you remove the space between type casting and variable in all places in order to have similar code formatting as in other places in Magento, like this?
```suggestion
                            (string)$binding['destination'],
```

2. Do we really need this casting? Do we have any case where we'll have another type?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @bartoszkubicki,
Thank you for your contribution!
Your changes looks good, but small adjustments are needed here. Could you review my comments and update your PR accordingly?

**Comment by bartoszkubicki** [comment]
@ihor-sviziev corrected in separate commit

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php [hunk 4]
```diff
@@ -59,21 +62,28 @@ public function __construct(
...
+                        $queueItems = $this->createQueueItems(
+                            (string)$binding['destination'],
+                            (string)$binding['topic'],
+                            (array)$binding['arguments'],
+                            (string)$connection
+                        );
                         $this->mappedData = array_merge($this->mappedData, $queueItems);
                     }
                 }
             }
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php:85]:
```suggestion
            }
            $this->mappedData = array_merge([], ...$mappedData);
```

File: lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php [hunk 5]
```diff
@@ -59,21 +62,28 @@ public function __construct(
...
                 foreach ($exchange['bindings'] as $binding) {
                     if ($binding['destinationType'] === 'queue') {
-                        $queueItems = $this->createQueueItems($binding['destination'], $binding['topic'], $connection);
+                        $queueItems = $this->createQueueItems(
+                            (string)$binding['destination'],
+                            (string)$binding['topic'],
+                            (array)$binding['arguments'],
+                            (string)$connection
+                        );
                         $this->mappedData = array_merge($this->mappedData, $queueItems);
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php]:
```suggestion
                        $mappedData[] = $queueItems;
```

File: lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php [hunk 6]
```diff
@@ -59,21 +62,28 @@ public function __construct(
      * Get mapped config data.
      *
      * @return array
+     * @throws LocalizedException
      */
-    public function getMappedData()
+    public function getMappedData(): array
     {
         if (null === $this->mappedData) {
             $this->mappedData = [];
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php]:
```suggestion
            $mappedData = [];
```

File: lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php [hunk 7]
```diff
@@ -141,22 +153,24 @@ private function isSynchronousTopic($topicName)
...
      * @return array
      */
-    private function matchSynchronousTopics($wildcard)
+    private function matchSynchronousTopics(string $wildcard): array
     {
         $topicDefinitions = array_filter(
             $this->communicationConfig->getTopics(),
             function ($item) {
-                return (bool)$item[CommunicationConfig::TOPIC_IS_SYNCHRONOUS];
+                return (bool) $item[CommunicationConfig::TOPIC_IS_SYNCHRONOUS];
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Topology/Config/QueueConfigItem/DataMapper.php]:
```suggestion
                return (bool)$item[CommunicationConfig::TOPIC_IS_SYNCHRONOUS];
```

File: lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php [hunk 8]
```diff
@@ -1,13 +1,16 @@
 <?php
+
+declare(strict_types=1);
+
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php]: Please move it back to prev. position

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @bartoszkubicki,
Static tests are still failing. Could you apply my suggestions?

File: lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php (hunk 8 above)
Comment (bartoszkubicki) [reply lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php]: I have corrected rest of comments, but I don't understand this one

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php]: Strict type declaration usually goes after copyright notice

Comment (bartoszkubicki) [reply lib/internal/Magento/Framework/MessageQueue/Test/Unit/Topology/Config/QueueConfigItem/DataMapperTest.php]: ok, corrected

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Review by ihor-sviziev — DISMISSED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8317](https://jira.corp.magento.com/browse/ENGCOM-8317) has been created to process this Pull Request

**Comment by bartoszkubicki** [comment]
@magento-engcom-team Please port it to magento 2.3

**Comment by engcom-Alfa** [comment]
Dev experience is required for testing this PR. Please note that Manual testing has not been performed.

**Review by engcom-Foxtrot — CHANGES_REQUESTED** [review]
Hello, @bartoszkubicki. Thank you for your contribution.
I've tried to reproduce the issue you've described on default Magento 2 2.4-develop branch without your fix. I've modified app/code/Magento/WebapiAsync/etc/queue_topology.xml to look like:
```
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework-message-queue:etc/topology.xsd">
    <exchange name="magento" type="topic" connection="amqp">
        <binding id="async.operations.all" topic="async.#" destinationType="queue" destination="async.operations.all">
            <arguments>
                <argument name="x-message-ttl" xsi:type="number">36000</argument>
            </arguments>
        </binding>
    </exchange>
</config>
```
After that, I've checked the modified binding through RabbitMQ UI and found that argument has been applied:
Screenshot from 2020-10-09 15-09-13
Could you please confirm that issue is already fixed or provide some more detailed steps to reproduce?

**Comment by bartoszkubicki** [comment]
@engcom-Foxtrot I will check it. I don't remeber why this branch is set to be merged to 2.4-develop. It was problem for sure in magento 2.3

**Comment by bartoszkubicki** [comment]
@engcom-Foxtrot Ok, I have checked it against 2.3 and 2.4. I can still reproduce an issue. The thing is, I was expecting to set these arguments on queue level, no I see it may work with this codebase on binding level (I am not sure if it has the same effect, I think arguments are limited to the binding). Most of tutorials that I found sets these arguments on queue level.

async all
We can see that aguments are set on binding level, but not as a 'feature' of whole queue

queue w arguments
Here we have different effect achieved by this script:
`
<?php

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use PhpAmqpLib\Connection\AMQPStreamConnection;
use PhpAmqpLib\Wire\AMQPTable;

$connection = new AMQPStreamConnection('rabbitmq', 5672, 'user', 'pass', 'vhost');
$channel = $connection->channel();

$taskExchange = 'task';
$taskQueue = 'task';
$deadLetterExchange = 'retry';
$deadLetterQueue = 'retry_task';

// Normal queue
$channel->exchange_declare($taskExchange, 'direct', false, true);
$channel->queue_declare($taskQueue, false, true, false, false, false, new AMQPTable([
    'x-dead-letter-exchange' => $deadLetterExchange
]));
$channel->queue_bind($taskQueue, $taskExchange);

// Retry queue with TTL
$channel->exchange_declare($deadLetterExchange, 'direct', false, true);
$channel->queue_declare($deadLetterQueue, false, true, false, false, false, new AMQPTable([
    'x-dead-letter-exchange' => $taskExchange,
    'x-message-ttl' => 10000
]));
$channel->queue_bind($deadLetterQueue, $deadLetterExchange);
$channel->basic_qos(null, 1, null);
`

queue w arguments
Here difference is also visible

**Comment by engcom-Foxtrot** [comment]
@bartekszymanski thank you for clarification, but it seems code still works incorrectly.
I'm using config from [this PR](https://github.com/magento/magento2/pull/26966) with some customization:
```
    <exchange name="test.dead_letter" type="topic" connection="amqp">
        <arguments>
            <argument name="x-dead-letter-exchange" xsi:type="string">test.retry</argument>
        </arguments>
        <binding id="test" topic="#" destinationType="queue"
                 destination="test_dead_letter">
            <arguments>
                <argument name="x-message-ttl" xsi:type="string">36000</argument>
            </arguments>
        </binding>
    </exchange>
```
As I understand, you assume we should get 'x-dead-letter-exchange' argument set for both topic and queue.
On 2.4-develop branch, I'm getting  'x-dead-letter-exchange' argument set only for the topic.
Screenshot from 2020-10-13 12-23-20

On bartoszkubicki:message-queue-arguments-passing-from-config, the exchange is not created at all:
Screenshot from 2020-10-13 12-11-28

**Comment by bartoszkubicki** [comment]
@engcom-Foxtrot I can't locate from which place you have taken this config, but it is not about setting arguments for exchanges (it seems to be working), but for queues - so it is not relevant (as official rabbit mq docs says, in order to create working DLX fallback you have to add dlx to queue, not to another exchange, because message is sent to DLX after its expired, rejected and so on).

From my tests on 2.4 you can set arguments for exchanges and bindings only. Arguments for queues are missing. I would like to have possibility to set arguments separately for queues and bindings. Basing on magento queues xmls construction, with this PR, I achieved setting queues arguments (with bindings arguments set, as a side effect). Normally (using php amq lib) you can set arguments for each component separately - exchange, queue, binding.

**Comment by engcom-Foxtrot** [comment]
@bartoszkubicki could you please provide some xml what would obviously confirm your PR is fixing the issue you described?

**Comment by bartoszkubicki** [comment]
@engcom-Foxtrot Me and my agency has created [sample module](https://github.com/lizardmedia/rabbitmq-playground) that needs this fix - you can install it and test it or take configuration files. Without fix DLX exchanges are not configured properly.

**Comment by ihor-sviziev** [comment]
@engcom-Foxtrot could you review https://github.com/magento/magento2/pull/26966#issuecomment-716726494 ?

**Comment by engcom-Foxtrot** [comment]
@bartoszkubicki thank you for clarification.

**Review by engcom-Foxtrot — APPROVED** [review]
