### PR TITLE
magento/magento2#35670: Meta tags auto generation: variables cannot be used multiple times

### LINKED ISSUE #35670: Meta tags auto generation: variables cannot be used multiple times
### Preconditions and environment

- Magento 2.3.3 / Magento 2.4.2

### Steps to reproduce

1. Execute `bin/magento config:set catalog/fields_masks/meta_keyword '{{name}}, order {{name}}'` or set manually
2. Login to Magento2 Backend
3. Create a new product
4. Set product name to "NEW PRODUCT"
5. Check meta keywords

### Expected result

The meta keywords should be set to `NEW PRODUCT, order NEW PRODUCT`

### Actual result

The meta keywords are set to `NEW PRODUCT, order {{name}}` .
So the second occurrence is not replaced as expected.

### Additional information

I think the substitution is done here?
https://github.com/magento/magento2/blob/1a7f152da7dca587e01e69012847e12cd86b75e3/app/code/Magento/Catalog/view/adminhtml/templates/catalog/product/edit.phtml#L198

So the solution would be to use `replaceAll` instead of `replace`:

```
var value = self._masks[this].replaceAll(self.varsRegexp, function(maskfieldName) {
    return $('#' + maskfieldName.slice(2, -2)).val();
});
```

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by MaximLogic**
### Description (*)

According to issue [#35670](https://github.com/magento/magento2/issues/35670#event-21850962100), when a field mask contains the same placeholder multiple times (e.g., `{{name}}, order {{name}}`), only the first occurrence was being replaced. This happened because `string.replace()` only replaces the first match by default.

  Changed the replacement logic in `import-handler.js` to use `split().join()` pattern instead, which replaces all occurrences of the placeholder. This ensures that masks like `{{name}}, order {{name}}` correctly produce "Product Name, order Product Name" instead of "Product Name, order {{name}}".

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35670

### Manual testing scenarios (*)

1. Set the meta keyword mask via CLI: `bin/magento config:set catalog/fields_masks/meta_keyword '{{name}}, order {{name}}'`
2. Log in to Magento Admin
3. Navigate to Catalog > Products and create a new product
4. Set the product name to "Test Product"
5. Check the meta keywords field - it should now display "Test Product, order Test Product"
6. Verify that both occurrences of `{{name}}` are replaced correctly

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by MaximLogic** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Catalog/view/adminhtml/web/js/components/import-handler.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /**
- * Copyright 2016 Adobe
+ * Copyright 2026 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/view/adminhtml/web/js/components/import-handler.js]: Keep this year as 2016 only.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @MaximLogic,

Thank you for the contribution!

The changes looks good to us. But a small minor change requested below.

File: app/code/Magento/Catalog/view/adminhtml/web/js/components/import-handler.js (hunk 1 above)
Comment (MaximLogic) [reply app/code/Magento/Catalog/view/adminhtml/web/js/components/import-handler.js]: Done

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Few test failure from Functional B2B, and EE are not consistent in recent 2 builds. They neither part of PR nor failing because of the PR changes. Seems to be flaky. The consistent failures are known issues and have the open JIRAs for them. Hence moving the PR to Merge in Progres..

**Functional B2B Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40412/df121305181529a90a4d4eef27b50ecd/Functional/allure-report-b2b/index.html#categories

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40412/205f29cecfbf722421d8a866971a7b94/Functional/allure-report-b2b/index.html#categories/dad3b5a7b0574462665553fcc880a350/3f1356d5d00edbd7/

image


**Functional CE Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40412/b0dc899669b62c044568ac8694b1e7fb/Functional/allure-report-ce/index.html#categories/dad3b5a7b0574462665553fcc880a350/98656a473bc5454d/

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40412/0d7dbcd400525e091af62d2523921c04/Functional/allure-report-ce/index.html#categories/dad3b5a7b0574462665553fcc880a350/b19d2e97cbda35e/

image


**Functional EE Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40412/e4d7622778899937b66c88a7bb5b601f/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741

image


Run 2:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40412/002d0df89ad3fe2b350746162d754859/Functional/allure-report-ee/index.html#categories/dad3b5a7b0574462665553fcc880a350/728d2f1de6ff2f22/

image



**Known Issues:**
[ACQE-9358](https://jira.corp.adobe.com/browse/ACQE-9358): AdminDisplayingCartAndCatalogPriceRulesGridsTest
[ACQE-9359](https://jira.corp.adobe.com/browse/ACQE-9359): AssertSuccessMessageAppearsAfterAddingProductToCartThatContainsOutOfStockProductTest
[ACQE-9362](https://jira.corp.adobe.com/browse/ACQE-9362): PurchaseOrderEnableDisableE2ETest
