### PR TITLE
Fixes #18357 - SQL error when table prefix used.

### LINKED ISSUE #18357: checkout_agreement_store doesn't exist
### Preconditions

1. Starting from Magento CE 2.2.5
2. upgrade from 2.2.5 to 2.2.6

### Steps to reproduce

1. Starting from Magento CE 2.2.5
2. created a terms and conditions (Store-->Terms and conditions)
3. upgrade from 2.2.5 to 2.2.6
3. The Terms and conditions created are not visible in admin (Store-->Terms and conditions)

### Expected result

1. I can edit the old terms and conditions
2. I can insert a new terms and conditions

### Actual result

1. old terms and conditions are not visible
2. In production mode I can add a new terms and conditions but is not visible in admin
3. In developer mode there is an exception: 

2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXXX.checkout_agreement_store' doesn't exist, query was: SELECT `agreement_store`.* FROM `checkout_agreement_store` AS `agreement_store` WHERE (agreement_store.agreement_id IN ('1'))
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXXX.checkout_agreement_store' doesn't exist

The table exist in DB; note that in sql there isn't the prefix to table.

### PR DESCRIPTION
**Pull request by pocallaghan**
### Description
Hard-coded table names cause errors if a table prefix, passing the table name to getTable resolves this.

### Fixed Issues (if relevant)
1. magento/magento2#18357

### Manual testing scenarios
1. Create a store using table prefixes
2. Navigate to Store > Terms and Conditions in the admin backend
3. Without the patch, errors are generated

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18412) <br/>All committers have signed the CLA.

**Comment by okorshenko** [comment]
Hi @pocallaghan 
Thank you for your contribution. Could you please sign Contributor License Agreement so that we can proceed with pull request processing. Just follow the URL: https://cla.dev.magento.com/magento/magento2?pullRequest=18412 to sign the CLA

Thank you

File: app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ private function getStoresForAgreements()
 
         if (!empty($agreementId)) {
             $select = $this->getConnection()->select()->from(
-                ['agreement_store' => 'checkout_agreement_store']
+                ['agreement_store' => $this->getResource()->getTable('checkout_agreement_store')]
```
Comment (okorshenko) [inline app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php:67]: thank you for your fix. The solution looks reasonable. The reason why this issue appeared is that there is not an integration test for this case. We are running integration tests with and w/o table prefixes to make sure that such issues won't appear. 

Please cover this case with the integration test (and earn additional contribution points :) ) to avoid a regression issue for your solution.

Also, could you please fix broken static tests.
Thank you

**Review by okorshenko — CHANGES_REQUESTED** [review]

**Comment by magento-engcom-team** [comment]
Hi @pocallaghan. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

File: app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php (hunk 1 above)
Comment (sreichel) [reply app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php:67]: @okobchenko is `getResource()` really neccessary?
