### PR TITLE
Fixed #26345 Reorder in Admin panel leads to report page in case of changed product custom option max characters

### LINKED ISSUE #26345: Reorder in Admin panel leads to report page in case of changed product custom option max characters
### Preconditions (*)

1. Magento ver. 2.3.2-p2.

### Steps to reproduce (*)

1. Configure a product with text (area) custom option, that has "Max Characters" value = 15.
2. Place an order with the configured product.
2.1. The text custom option value should be at least 11 symbols length.
3. Change the value of the product text custom option "Max Characters" to 10 (or less).
4. Go to the placed order in Admin panel.
5. Click on "Reorder" button.

### Expected result (*)

The Admin user see a clear error message, that explains, why the order couldn't reordered.
Probably it's enough to implement it in the same way as on frontend for registered customer:
registered customer - reorder after changing max characters - error message

### Actual result (*)

The Admin user see a report page.

### PR DESCRIPTION
**Pull request by cedmudit**
Fixed #26345 Reorder in Admin panel leads to report page in case of changed product custom option max characters

Preconditions (*)

    Magento ver. 2.3.2-p2.

Steps to reproduce (*)

    Configure a product with text (area) custom option, that has "Max Characters" value = 15.
    Place an order with the configured product.
    2.1. The text custom option value should be at least 11 symbols length.
    Change the value of the product text custom option "Max Characters" to 10 (or less).
    Go to the placed order in Admin panel.
    Click on "Reorder" button.

Expected result (*)

The Admin user see a clear error message, that explains, why the order couldn't reordered.
Probably it's enough to implement it in the same way as on frontend for registered customer:
registered customer - reorder after changing max characters - error message
Actual result (*)

The Admin user see a report page

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @cedmudit. Thank you for your contribution. Could I kindly ask you to cover your change using an automated test? I would recommend a unit test or MFTF test in this particular case. 

Also, consider checking the failing static tests as well. 

Thank you!

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by rogyar** [comment]
@magento run functional tests

**Comment by engcom-Echo** [comment]
@magento all run tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by rogyar — CHANGES_REQUESTED** [review]
It looks like the reorder functionality for MSI has been affected by this change. Please, take a look at the failing functional tests.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Looks like they were just fluky tests

File: app/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder.php [hunk 1]
```diff
@@ -90,10 +104,18 @@ public function execute()
...
-            $order->setReordered(true);
-            $this->_getSession()->setUseOldShippingMethod(true);
-            $this->_getOrderCreateModel()->initFromOrder($order);
-            $resultRedirect->setPath('sales/*');
+            try {
+                $order->setReordered(true);
+                $this->_getSession()->setUseOldShippingMethod(true);
+                $this->_getOrderCreateModel()->initFromOrder($order);
+                $resultRedirect->setPath('sales/*');
+            } catch (\Magento\Framework\Exception\LocalizedException $e) {
```
Comment (rogyar) [inline app/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder.php:121]: Hi @cedmudit. I've noticed that we don't log the exception. It's not that critical in case of `LocalizedException` since we show the message using the `messageManager`. However, it's still recommended to log the exception.

In the case of catching `\Exception` it's very important to have the details in the error log. Otherwise, we just catch the exception and hide important error details. 

Please, add error logging for both cases. Thank you!

**Review by rogyar — DISMISSED** [review]

File: app/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder.php (hunk 1 above)
Comment (engcom-Echo) [reply app/code/Magento/Sales/Controller/Adminhtml/Order/Create/Reorder.php:121]: Hi, @rogyar. I will add an error logging.

**Comment by rogyar** [comment]
The failing tests are not related to the current PR since we have the same tests failing for other PRs

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7090](https://jira.corp.magento.com/browse/ENGCOM-7090) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR
