### PR TITLE
33040 add is subscription enabled checking to new action controller

### LINKED ISSUE #33040: Newsletter Subscription does not check for newsletter/general/active (no effective check for disabled newsletter implemented)
We found on our Magento2 Shops (Version 2.4.0 - 2.4.2) various successful attempts to subscribe to newsletter by posting to /newsletter/subscriber/new/. The newsletter functionality however is disabled, but still accepting new emails and sending confirmation mails out.

### Preconditions (*)
1. Magento installation version 2.4.0 to 2.4.2 is vulnerable 

### Steps to reproduce (*)
1. In the admin backend, disable newsletter functionality.
2. Create or forge html form that posts to /newsletter/subscriber/new/

### Expected result (*)
1. New subscribers should not be accepted

### Actual result (*)
1. In the backend, you will find a new newsletter subscriber. Furthermore, a newsletter confirmation email is sent out.

Since the Magento_Newsletter module can't be disabled due to dependencies from Magento_Customer, the only way to prevent new subscribers is to edit code in vendor/magento/module-newsletter/Controller/Subscriber/NewAction.php.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by SilinMykola**
### Description (*)
I added config settings check to NewAction subscriber controller to prevent subscription customer if in config subscription is disabled

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33040

### Manual testing scenarios (*)
1. Open frontend page with subscription form.
2. Disabled subscription in configuration and clear cache.
3. Back to frontend page (not reload) and subscribe.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SilinMykola** [comment]
@magento run all tests

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 1]
```diff
@@ -125,6 +129,17 @@ protected function validateGuestSubscription()
...
     }
 
+    /**
+     * Check subscription is enabled in configuration
+     *
+     * @return bool
+     */
+    protected function validateIsSubscriptionEnabled()
+    {
+        return (bool)$this->_objectManager->get(ScopeConfigInterface::class)
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: We should avoid using objectManager. Please inject and use \Magento\Newsletter\Model\Config::isActive instead.

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 2]
```diff
@@ -32,6 +32,10 @@
  */
 class NewAction extends SubscriberController implements HttpPostActionInterface
 {
+    /**
+     * Config path is subscription enabled
+     */
+    public const XML_PATH_IS_SUBSCRIPTION_ENABLED = 'newsletter/general/active';
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: This won't be needed after implementing the suggested change.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @SilinMykola thank you for your contribution. Could you please review the below suggestion? Also, please consider covering the fix by some automated tests (integration tests would be suitable for such cases).

Thank you.

**Comment by eduard13** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by SilinMykola** [comment]
@magento run Integration Tests

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 3]
```diff
@@ -51,16 +59,18 @@ class NewAction extends SubscriberController implements HttpPostActionInterface
      * Initialize dependencies.
      *
      * @param Context $context
+     * @param NewsletterConfig $newsletterConfig
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: Please add the new dependency at the end and exactly how it is added the `EmailValidator`.

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 4]
```diff
@@ -85,10 +96,11 @@ public function __construct(
      * Validates that the email address isn't being used by a different account.
      *
      * @param string $email
-     * @throws LocalizedException
+     *
      * @return void
+     * @throws LocalizedException
      */
-    protected function validateEmailAvailable($email)
+    protected function validateEmailAvailable(string $email)
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: Please revert it, since it's BIC
```suggestion
    protected function validateEmailAvailable($email)
```

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 5]
```diff
@@ -125,14 +137,25 @@ protected function validateGuestSubscription()
         }
     }
 
+    /**
+     * Check subscription is enabled in configuration
+     *
+     * @return bool
+     */
+    protected function validateIsSubscriptionEnabled(): bool
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: I'm not sure that it worth declaring a new method for this purpose, I'd add `isActive` check straight into that condition.

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 6]
```diff
@@ -125,14 +137,25 @@ protected function validateGuestSubscription()
...
      * Validates the format of the email address
      *
      * @param string $email
-     * @throws LocalizedException
+     *
      * @return void
+     * @throws LocalizedException
      */
-    protected function validateEmailFormat($email)
+    protected function validateEmailFormat(string $email)
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: Revert this change
```suggestion
    protected function validateEmailFormat($email)
```

File: app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php [hunk 7]
```diff
@@ -146,7 +169,8 @@ protected function validateEmailFormat($email)
      */
     public function execute()
     {
-        if ($this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
+        if ($this->validateIsSubscriptionEnabled() &&
+            $this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
```
Comment (eduard13) [inline app/code/Magento/Newsletter/Controller/Subscriber/NewAction.php]: Please move `validateIsSubscriptionEnabled` at the end and correctly format the multiline if condition. Check [this article](https://pear.php.net/manual/en/rfc.cs-enhancements.splitlongstatements.php) for more info.
```suggestion
        if ($this->validateIsSubscriptionEnabled() &&
            $this->getRequest()->isPost() && $this->getRequest()->getPost('email')) {
```

**Review by eduard13 — CHANGES_REQUESTED** [review]
Please check my suggestions below

**Comment by SilinMykola** [comment]
@magento run all tests

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9238](https://jira.corp.magento.com/browse/ENGCOM-9238) has been created to process this Pull Request

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by SilinMykola** [comment]
@magento run Functional Tests B2B

**Comment by SilinMykola** [comment]
@magento run Functional Tests B2B

**Comment by SilinMykola** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
@SilinMykola , Please clear the conflicts in the Pr to move ahead

**Comment by SilinMykola** [comment]
@magento run all tests

**Comment by SilinMykola** [comment]
@engcom-Delta hi! Thank you for your response! I fixed the conflicts and ran the tests.

**Comment by SilinMykola** [comment]
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B

**Comment by SilinMykola** [comment]
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B

**Comment by SilinMykola** [comment]
@magento run Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B
