### PR TITLE
Delete existing URL rewrite IDs in After Replace

### LINKED ISSUE #34210: [Issue] Ensure that previously existing records in catalog_url_rewrite_produc…
This issue is automatically created based on existing pull request: magento/magento2#34209: Ensure that previously existing records in catalog_url_rewrite_produc…

---------
Ensure that previously existing records in catalog_url_rewrite_product_category are deleted before trying to insert them again.

#### Changes
Delete existing records in the catalog_url_rewrite_product_category table before inserting the same ones.

#### Why
This change will avoid the following exception during multi store product import :

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '74583' for key 'PRIMARY', query was: INSERT  INTO `catalog_url_rewrite_product_category` (`url_rewrite_id`,`category_id`,`product_id`) VALUES (?, ?, ?), ...

The problem is that catalog_url_rewrite_product_category records are not created storewise for a given request_path. On the other side, url_rewrite records are created storewise.
If, during the same import, a product and its url_rewrite records are created for stores A and B in the first batch and then for store C in a second batch and if product url keys and category name are the same for all those stores, an insert try for duplicated catalog_url_rewrite_product_category records will cause the mentioned issue.

### Related Pull Requests

None

### Fixed Issues (if relevant)

Not relevant

### Manual testing scenarios (*)

1. Install a fresh Magento instance
2. Create `che` website with `de_ch`, `en_ch`, `es_ch`, `fr_ch`, `zh_ch` store views
3. Create `exp` website with `de_ex`, `en_ex`, `es_ex`, `fr_ex`, `zh_ex` store views
4. Create the `Products` category
5. Go on the admin panel under System > Import
6. Choose Products entity type with Add/Update behaviour and let default settings for the rest
7. Upload [this file](https://github.com/magento/magento2/files/7260916/contribute.csv) and launch the import
8. General system exception happened
9. Make the PR changes
10. Repeat steps 5 to 7
11. Import works fine

### Questions or comments

I am not sure if an additional test is needed for that. Please, tell me if it is the case.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by amenk**
It is possible that the entries in the `catalog_url_rewrite_product_category` table already exist. So as we are in a replace interceptor, we have to take care of this and not just insert additional entries.

### Description (*)

We saw errors like 

	SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '51541850' for key 'PRIMARY', query was:
	INSERT  INTO `catalog_url_rewrite_product_category` 
	(`url_rewrite_id`,`category_id`,`product_id`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)

after saving categories. This pull request fixes the issue.

I do not have a single clue if this reproducible in a stock Magento installation.

### Manual testing scenarios (*)
* not sure if reproducible

### Fixed issues
- Fixes https://github.com/magento/magento2/issues/34210

Please tell me if that makes sense

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by amenk** [comment]
@magento run all tests

**Comment by amenk** [comment]
@magento give me 2.4.3 instance

**Comment by amenk** [comment]
related: https://github.com/magento/magento2/issues/33770

**Comment by amenk** [comment]
The functional tests seem to fail because of other reasons, I cannot imagine those errors are related to my PR. @ihor-sviziev can you review this as you were involved in the releated issue?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

Hi @amenk,
Could you provide the steps to reproduce this issue?

**Comment by amenk** [comment]
@ihor-sviziev 

Thank you for your feedback.

I was not able to reproduce this on a clean Magento installation, it seems a complex case. 
But as you see in https://github.com/magento/magento2/issues/33770, many are facing this issue.

From a logical point of view it makes sense to me - when hooking in the afterReplace - to actually replace items and not just insert them. That's why I inserted the delete before the insert.

**Comment by ihor-sviziev** [comment]
@amenk, I wonder how we can check that this change will fix the issue if we can't reproduce it.

**Comment by amenk** [comment]
@ihor-sviziev Yes, very good point.
Anyways, on my local customer's instance I can reproduce it - but I was not able to create a minimal example. Would it make sense to share the database dump of the product catalog privately?

**Comment by ihor-sviziev** [comment]
@amenk, sorry, I don't have enough time to test it now. Maybe you could share with someone who will be checking this PR?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Functional Tests CE

File: app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php [hunk 1]
```diff
@@ -59,6 +59,7 @@ public function afterReplace(StorageInterface $object, array $result, array $url
             ];
         }
         if (count($toSave) > 0) {
+            $this->productResource->removeMultiple(array_column($toSave, 'url_rewrite_id'));
             $this->productResource->saveMultiple($toSave);
```
Comment (ihor-sviziev) [inline app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php]: I don't like the idea of removing items from the URL rewrites table and then inserting them due to potentially stopped process (server restart / php-fpm reload / hardware failure). Don't really want to add case, when URL rewrites won't be saved.

I just looked at the implementation of the saveMultiple method uses 
https://github.com/magento/magento2/blob/ef9425dd5154fa64f8d0de570e5644992b905213/app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php#L56

What if we'll replace it with the `insertOnDuplicate` method, which should handle duplicates correctly?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php (hunk 1 above)
Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php]: Yes, that would be essentially the same as saveMultiple is only called from the place that I changed.
But as it is a public method, it might eventually be called from other places and it would change behavior slightly, but I guess that is not actually a problem

Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php]: Shall I change it ?

Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php]: Other option would be to change the signature to

    public function saveMultiple(array $insertData, $ignoreDuplicates = false)

Comment (ihor-sviziev) [reply app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php]: I think no need to add an optional parameter as the exception here isn't something expected, so better to fix the implementation. In most cases, it works fine, but in some edge cases, it works incorrectly.

PS: it's not used anywhere else according to https://github.com/magento/magento2/search?q=saveMultiple

**Comment by ihor-sviziev** [comment]
@amenk, FYI, I found the following PR that does the exact change https://github.com/magento/magento2/pull/34209, and it has steps to reproduce. Maybe, you can write some automated tests on top of it?

**Comment by amenk** [comment]
>

**Comment by amenk** [comment]
> @amenk, FYI, I found the following PR that does the exact change #34209, and it has steps to reproduce. Maybe, you can write some automated tests on top of it?
> 
> PS: I marked that this PR fixes #34210, as the issue seems the same

Ah, thanks - acutally on our database the issue happens when changing categories via the backend, but the import case is also interesting.

Not sure if I will find the time to write a test based on that. It's unfortunately very time consuming in Magento 2 :-( Are you talking about an integration test or MFTF?

**Comment by ihor-sviziev** [comment]
@amenk, any suitable type. As to me - I think integration might be easier to implement.
If you're having the same issue during the category save - I think the pre-requisites are the same. :)

**Comment by amenk** [comment]
I tried to write a (failing) integration test, but actually without the import, because I think it's not so good to have a 2000 line CSV fixture. I sometimes go key constraint violations when I had TEST_CLEANUP set to `disabled`, but with it `enabled` I never was able to reproduce such errors...

**Comment by amenk** [comment]
Maybe I could try to call \Magento\UrlRewrite\Model\Storage\DbStorage::replace() directly with approriate values

**Comment by ihor-sviziev** [comment]
@amenk, could you ping me in EngCom Slack for more straightforward discussions? :)

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

**Comment by amenk** [comment]
In normal cases, \Magento\UrlRewrite\Model\Storage\DbStorage::deleteOldUrls seems to clean the url_rewrites and so, because of the "on delete cascade" also the entry in `catalog_url_rewrite_product_category` get cleaned .. in some cases (probably because of data inconsistency from old Magento versions or imports) this does not work reliably.

**Comment by amenk** [comment]
... but I have no clue how to reproduce this in a test ...

**Comment by amenk** [comment]
Maybe it's really related to the chunking and we need to insert very much entries at the same time. In our customers shop the array hat around 8000 entries I believe

**Comment by amenk** [comment]
I am creating an integration tset based on the file in https://github.com/magento/magento2/issues/34210 now

**Comment by amenk** [comment]
@magento run Integration Tests

**Comment by amenk** [comment]
@ihor-sviziev  Failing test added, integration tests triggered

Locally I get this result:

```
Magento\Framework\DB\Adapter\DuplicateException : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '176' for key 'PRIMARY', query was: INSERT  INTO `catalog_url_rewrite_product_category` (`url_rewrite_id`,`category_id`,`product_id`) VALUES (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?), (?, ?, ?)
```
which is what we need

**Comment by amenk** [comment]
If I apply the fix, I get the following error during the import in the test

```
Zend_Db_Statement_Exception : SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction, query was: SELECT `catalog_category_product_index_store2`.`category_id`, `catalog_category_product_index_store2`.`product_id`, `catalog_category_product_index_store2`.`position`, `catalog_category_product_index_store2`.`store_id` FROM `catalog_category_product_index_store2` WHERE (store_id = '2') AND (product_id IN (4, 9))

```

**Comment by amenk** [comment]
@magento run Integration Tests

**Comment by amenk** [comment]
@ihor-sviziev The test fails as expected 

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/34791/a71fba8adf1824fb3f42046e9e295ee5/Integration/allure-report-ce/index.html#suites/b5f17e08f9c70bc6738c19e2bf1a5a7d/53a02193c2a76898/

image

I will now next push the fix and make it green

**Comment by amenk** [comment]
@magento run Integration Tests

File: app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php (hunk 1 above)
Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Model/Category/Plugin/Storage.php]: Change was made, tests are green now

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/_files/issue34210_structure.php [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+        ->setIsActive(1);
+    $storeResource->save($store);
+}
+
+/* Refresh CatalogSearch index */
+/** @var IndexerRegistry $indexerRegistry */
+$storeManager->reinitStores();
+$indexerRegistry = $objectManager->get(IndexerRegistry::class);
+$indexerRegistry->get(Fulltext::INDEXER_ID)->reindexAll();
+//$indexerRegistry->get('catalog_category_product')->reindexAll();
```
Comment (ihor-sviziev) [inline dev/tests/integration/testsuite/Magento/CatalogUrlRewrite/_files/issue34210_structure.php]: Please remove this line if it's not needed

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Great job! 👏 
Please fix the static test failure and I'll approve your PR

**Comment by amenk** [comment]
@magento run static tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B,Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9380](https://jira.corp.magento.com/browse/ENGCOM-9380) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. We should have fresh installation of Magento 2.4 Develop. 



**Manual testing scenario:**

1. Create che website with de_ch, en_ch, es_ch, fr_ch, zh_ch store views
2. Create exp website with de_ex, en_ex, es_ex, fr_ex, zh_ex store views
3. Create the Products category inside default catagory
4. Go on the admin panel under System > Import
5. Choose Products entity type with Add/Update behaviour and let default settings for the rest
6. Upload [provided csv](https://github.com/magento/magento2/files/7260916/contribute.csv) file and launch the import
7. Validate file import successful


**Before:** :heavy_multiplication_x: We had been getting exception while importing.

Screenshot 2022-01-10 at 10 54 27 PM


**After:** :heavy_check_mark:  flies getting imported successfully.

Screenshot 2022-01-11 at 12 52 45 AM

File: app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php [hunk 3]
```diff
@@ -19,12 +19,12 @@ class Product extends AbstractDb
...
      * Product/Category relation table name
      */
-    const TABLE_NAME = 'catalog_url_rewrite_product_category';
+    public const TABLE_NAME = 'catalog_url_rewrite_product_category';
 
     /**
      * Chunk for mass insert
      */
-    const CHUNK_SIZE = 100;
+    private const CHUNK_SIZE = 100;
```
Comment (hostep) [inline app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php]: @amenk, @ihor-sviziev: isn't this a backwards incompatible change? The constant used to be public but is now private, this change will break for people who are relying on this constant, right?

Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php]: kind of true, shall we change it back?

Comment (ihor-sviziev) [reply app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php]: I think we should make it public back
```suggestion
    public const CHUNK_SIZE = 100;
```

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php (hunk 3 above)
Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Model/ResourceModel/Category/Product.php]: thanks :-)

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9380](https://jira.corp.magento.com/browse/ENGCOM-9380) has been created to process this Pull Request

**Comment by charlescurrier** [comment]
Any movement on this? This issue is affecting every developer on our team, and the PR appears to have been sitting stagnant for over a month.

**Comment by burgh8wp** [comment]
@amenk the patch created doesn't seem to address the lack of auto increment on this catalog_url_rewrite_product_category table?

So for example in our setup for this client, it should be auto incrementing from around 118669 as the next new ID to go in, starting off from previous of 118668, but the Magento system is trying to add various that start 117xxx when a product is saved in a new category, which suggests it has wrong stamp on where to start the ID? As far as I can see, the patch doesn't address any of this?

**Comment by amenk** [comment]
@burgh8wp nothing was changed with the auto increments, yes. Probably a different issue?
