### PR TITLE
[2.3.x][REST] required configurable attributes should not be required value in configurable product.

### LINKED ISSUE #13234: [2.3.x][REST] required configurable attributes should not be required value in configurable product
### Preconditions
1. Magento 2.3.x CE & EE 
1. API Integration in place

### Steps to reproduce
1. Create a custom required, global product attribute that can be used for configurations (e.g. select)
1. Create one or more simple products with different values for the attribute
1. Create a configurable product over the rest api and leave the required attribute empty
(I think the API point is only important for reproducing since creating the product in the backend would most likely lead to have the default value / first value in select for the attribute submitted)

### Expected result
1. The created attribute should not be required for the configurable product when it is used for configurations

### Actual result
1. We get "message": "The \"test\" attribute value is empty. Set the attribute and try again."
With empty value for attribute:
!https://user-images.githubusercontent.com/51680850/65122539-e7c45a80-d9f9-11e9-90ad-5045f9b9b177.png!
Without attribute(same response):
!https://user-images.githubusercontent.com/51680850/65122708-4f7aa580-d9fa-11e9-8dca-03c21ec9d8f0.png!

Current Workaround is to set the attribute to not required

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/13234

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/13234

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php [hunk 1]
```diff
@@ -29,27 +33,41 @@ public function __construct(
...
     }
+
+    /**
+     * Verify if attribute is a part of configurable product and should not be validated.
+     *
+     * @param DataObject $entity
+     * @param AbstractAttribute $attribute
+     * @return bool
+     */
+    private function isAttributeShouldBeValidated(DataObject $entity, AbstractAttribute $attribute): bool
```
Comment (zakdma) [inline app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php]: I suppose name should be **isAttributeShouldNotBeValidated**
since we're skipping validation if it return true

File: app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php [hunk 2]
```diff
@@ -29,27 +33,41 @@ public function __construct(
...
+    {
+        if (!($entity instanceof ProductInterface && $entity->getTypeId() == Configurable::TYPE_CODE)) {
```
Comment (zakdma) [inline app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php]: Its better use strict comparison is possible

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php (hunk 2 above)
Comment (engcom-Kilo) [reply app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php]: Fixed

File: app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php (hunk 1 above)
Comment (engcom-Kilo) [reply app/code/Magento/ConfigurableProduct/Plugin/Model/Attribute/Backend/AttributeValidation.php]: Renamed

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by zakdma — APPROVED** [review]

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32716`.
