### PR TITLE
Rewrote Magento\Framework\DB\Adapter\Pdo\Mysql->isTableExists

### LINKED ISSUE #29662: [Issue] Rewrote Magento\Framework\DB\Adapter\Pdo\Mysql->isTableExists
This issue is automatically created based on existing pull request: magento/magento2#28516: Rewrote Magento\Framework\DB\Adapter\Pdo\Mysql->isTableExists

---------
### Preconditions

Magento 2.4-develop

### Description
During heavier load on newer productive Magento2 installations (2.3 with MSI or 2.3.4+), we noticed increased execution time was spent in `SHOW TABLE STATUS` queries to MySQL. Analyzing this further, we found that these queries seemed to occur in higher frequency than in earlier Magento versions. This can be problematic, since the MySQL server uses an exclusive file system lock and a call to readdir() to answer them. Because of this, these calls can be slow. We also found that one web request can result in multiple calls of `SHOW TABLE STATUS` for the same tables, which seems very wasteful and inefficient.

In more detailed analysis of some of our customers, we found instances where `SHOW TABLE STATUS` queries were executed nearly 100 times when requesting a single category page with 48 products.

Looking at the code of the MySQL adapter, we identified several places that use the function `showTablesStatus()`, among them `isTableExists()`.
With this patch, we eliminate the calls of `SHOW TABLE STATUS` for the common case of checking table existence.

#### Implementation details
In our implementation of `isTableExists()`, we use information from the INFORMATION_SCHEMA.TABLES table, which is provided without expensive file system operations and proved to be significantly faster in our tests (see below for details). Additionally, we use the already existing DDL cache to store a positive table existence, resulting in even fewer database calls.

According to the official MySQL documentation[[link]](https://dev.mysql.com/doc/refman/5.7/en/information-schema-introduction.html), using the views from INFORMATION_SCHEMA is actually recommended over using SHOW queries, since this has some advantages. INFORMATION_SCHEMA views are read-only and respect the access rights of the database user, so it should be readily available on supported MySQL platforms.

The raw performance advantages of using INFORMATION_SCHEMA over `SHOW TABLES STATUS` can easily be measured with MySQL itself. We’ve used MySQL 5.7.30 on Ubuntu 18.04, with `datadir` running on a high performance NVME SSD (Samsung PM1725b).
We’ve run 10 concurrent clients each executing 1,000,000 statements in a Magento database with demo data, once with the query `SHOW TABLES STATUS LIKE ‘catalog_product_entity’;` and once with our statement `SELECT COUNT(1) AS tbl_exists FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = ‘catalog_product_entity’ AND TABLE_SCHEMA = DATABASE();`.

Between these queries, we measured a difference of *slightly over factor 10* in the execution time, favoring our solution with INFORMATION_SCHEMA. See below for details.
We assume the difference is even bigger when having more concurrent clients or slower hardware. As MySQL’s “SHOW TABLE STATUS” implementation is reading the whole directory, file system locking can have a stronger effect as well as which file system is used.

Our performance measurements:
- create the files test1.sql and test2.sql with 1.000.000 rows of the statements to test.
- run these commands
  - `time seq 1 10 | parallel -j 10 bash -c 'mysql < test1.sql > /dev/null’`
  - `time seq 1 10 | parallel -j 10 bash -c 'mysql < test2.sql > /dev/null’`

Results:
For `SHOW TABLE STATUS`:
```
# time seq 1 10 |  parallel  -j 10 bash -c ' mysql   < test1.sql  > /dev/null’ 

real	85m21.374s
user	3m5.500s
sys	1m40.317s
```
For `INFORMATION_SCHEMA`:
```
time seq 1 10 |  parallel  -j 10 bash -c ' mysql   < test2.sql > /dev/null 


real	8m5.184s
user	1m54.587s
sys	1m11.687s
```

### Steps to reproduce:
To see the impact our patch has, load the same set of pages on the frontend with and without the patch on any Magento instance (with real or demo data). The difference can be seen when analyzing the amount of SQL queries sent to the database and the time spent processing them. Here’s an easy way to do this:

Using [Slow Query Log](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html), you can make MySQL actually log all queries by setting the threshold to 0 seconds:

```
SET @@GLOBAL.long_query_time = 0; SET @@GLOBAL.slow_query_log = 1;
```
After you’ve opened the selected set of frontend pages, deactivate it again:
```
SET @@GLOBAL.slow_query_log = 0;
```
Now, using `pt-query-digest` from the Percona Toolkit on the slow query log file, you get an analysis of the logged queries, with queries grouped by type, their average and cumulative run time, and other information. Make sure to use two different log files so that they can easily be compared between M2 with and without our patch.

In the analysis, you will usually see `SHOW TABLE STATUS` queries appearing in the top queries (this depends a bit on the module configuration and of course on which and how many pages you accessed for this test), meaning they're taking quite a good percentage of total execution time.

Please see these extracts from the `pt-query-digest` output for an example, which we created when simply opening the single category page “Men > Tops” from the demo data (`https://$BASEURL/men/tops-men.html?product_list_limit=36`).

### Actual Result:

Analysis of SQL queries run, *unpatched* Magento:
```
# Profile
# Rank Query ID                         Response time Calls R/Call V/M   I
# ==== ================================ ============= ===== ====== ===== =
#    1 0xAADD55611E492BA965AF2F067A0...  0.0099 34.3%    22 0.0004  0.00 SELECT catalog_product_index_eav search_tmp_?ed?d?dcc?b?_? cataloginventory_stock_status
#    2 0x7009A071F49236A84A57562D461...  0.0050 17.2%     1 0.0050  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price review_entity_summary review_entity cataloginventory_stock_status search_tmp_?ed?d?dccc?_?
#    3 0x8085D806F3631D0D30FE5C20326...  0.0036 12.5%     3 0.0012  0.00 SHOW TABLE STATUS
#    4 0x13262D434B03958CB4F62EC706B...  0.0011  3.9%     1 0.0011  0.00 INSERT SELECT search_tmp_?ed?d?dcc?b?_? catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#    5 0x2F9EDAB00084ED0A7EE1463DBA4...  0.0009  3.1%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
[...]
```
You can see that queries of the type `SHOW TABLE STATUS` are the third most expensive queries with 12.5% of the total execution time inside the database and 3 calls in total just for this single page load.

### Expected Result:
*Patched* Magento, opening the same category page:
```
# Profile
# Rank Query ID                         Response time Calls R/Call V/M   I
# ==== ================================ ============= ===== ====== ===== =
#    1 0xAADD55611E492BA965AF2F067A0...  0.0105 29.9%    22 0.0005  0.00 SELECT catalog_product_index_eav search_tmp_?ed?cf?f?c?a?_? cataloginventory_stock_status
#    2 0x8EA4DF263A535F59EAC6ED75B20...  0.0073 20.7%    24 0.0003  0.00 SELECT catalog_product_entity catalog_product_super_link catalog_product_website catalog_product_entity_int cataloginventory_stock_status
#    3 0x7009A071F49236A84A57562D461...  0.0050 14.2%     1 0.0050  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price review_entity_summary review_entity cataloginventory_stock_status search_tmp_?ed?cf?f?e?b?_?
#    4 0x13262D434B03958CB4F62EC706B...  0.0015  4.3%     1 0.0015  0.00 INSERT SELECT search_tmp_?ed?cf?f?c?a?_? catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#    5 0xCB3E7FA2C499AC0B69ACCD06C21...  0.0012  3.4%     2 0.0006  0.00 SELECT catalog_product_index_price search_tmp_?ed?cf?f?c?a?_?
#    6 0x2F9EDAB00084ED0A7EE1463DBA4...  0.0009  2.7%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
#    7 0x593763BE686057BEA87DB0BC232...  0.0008  2.4%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
#    8 0x23B42F57B465E32E1732E4070E9...  0.0008  2.2%    72 0.0000  0.00 SELECT inventory_stock
#    9 0x11C6E1A6D7347EEAF29EBEA1350...  0.0008  2.2%     1 0.0008  0.00 SELECT catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#   10 0xA788DCC6FE9679C3FDABA74662A...  0.0007  1.9%     1 0.0007  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price cataloginventory_stock_status search_tmp_?ed?cf?f?e?b?_?
#   11 0x961084F55005407CD1C1E76C0BE...  0.0006  1.7%     2 0.0003  0.00 SELECT eav_attribute_option_swatch
#   12 0xE29FDCAD0B27AFD15D17697A415...  0.0005  1.5%     1 0.0005  0.00 SELECT catalog_product_index_price search_tmp_?ed?cf?f?c?a?_?
#   13 0x233B56CFFF59C63BF02E08D9654...  0.0005  1.4%     2 0.0002  0.00 CREATE TABLE search_tmp_?ed?cf?f?e?b?_? `search_tmp_5ed8cf6f89e2b9_26325963`
#   14 0x2F0A3214F96ED5CD4E962B1E990...  0.0005  1.3%    24 0.0000  0.00 SELECT catalog_product_super_attribute catalog_product_entity catalog_product_super_link eav_attribute catalog_product_entity catalog_product_entity_int catalog_product_super_attribute_label eav_attribute_option
#   15 0xDD45A442CF95F62A11D72D7D0F8...  0.0004  1.2%     1 0.0004  0.00 SELECT catalog_category_product_index_store? search_tmp_?ed?cf?f?c?a?_? catalog_category_entity
#   16 0x616C07D9410BE0BBA2EBCD6D77C...  0.0003  0.8%    21 0.0000  0.00 SELECT eav_attribute
#   17 0xB3E930152F4418A1C656779CE44...  0.0003  0.7%    12 0.0000  0.00 SELECT catalog_product_super_attribute
#   18 0xDFE08A11F72783E309DFA58BA8F...  0.0003  0.7%    12 0.0000  0.00 SELECT catalog_category_product
#   19 0x58EA3033F7E981C7FACDF0DE8D3...  0.0002  0.7%    20 0.0000  0.00 SELECT catalog_eav_attribute
#   20 0x13867189A41845FE8E8C4366F7B...  0.0002  0.5%    12 0.0000  0.00 SELECT catalog_product_super_attribute_label
# MISC 0xMISC                            0.0020  5.6%    74 0.0000   0.0 <38 ITEMS>
```
We’ve had to include the full summary in this case to show that our implementation not only eliminates the common cause for `SHOW TABLE STATUS` queries, but also that the new queries to INFORMATION_SCHEMA.TABLES do not occur in the top 20 queries.
This already illustrates that we’ve found a good solution to improve the performance of table existence checks. The complete impact can be estimated from observing production stores with many concurrent page views, where we see thousands of `SHOW TABLE STATUS` queries in 2–3 minutes.

### Questions or comments
- The commit in this pull request is a combined work of @jonashrem and @leeps.
- We haven’t created an issue for this improvement, but can do that if it’s needed/wanted.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by jonashrem**
### Description
During heavier load on newer productive Magento2 installations (2.3 with MSI or 2.3.4+), we noticed increased execution time was spent in `SHOW TABLE STATUS` queries to MySQL. Analyzing this further, we found that these queries seemed to occur in higher frequency than in earlier Magento versions. This can be problematic, since the MySQL server uses an exclusive file system lock and a call to readdir() to answer them. Because of this, these calls can be slow. We also found that one web request can result in multiple calls of `SHOW TABLE STATUS` for the same tables, which seems very wasteful and inefficient.

In more detailed analysis of some of our customers, we found instances where `SHOW TABLE STATUS` queries were executed nearly 100 times when requesting a single category page with 48 products.

Looking at the code of the MySQL adapter, we identified several places that use the function `showTablesStatus()`, among them `isTableExists()`.
With this patch, we eliminate the calls of `SHOW TABLE STATUS` for the common case of checking table existence.

#### Implementation details
In our implementation of `isTableExists()`, we use information from the INFORMATION_SCHEMA.TABLES table, which is provided without expensive file system operations and proved to be significantly faster in our tests (see below for details). Additionally, we use the already existing DDL cache to store a positive table existence, resulting in even fewer database calls.

According to the official MySQL documentation[[link]](https://dev.mysql.com/doc/refman/5.7/en/information-schema-introduction.html), using the views from INFORMATION_SCHEMA is actually recommended over using SHOW queries, since this has some advantages. INFORMATION_SCHEMA views are read-only and respect the access rights of the database user, so it should be readily available on supported MySQL platforms.

The raw performance advantages of using INFORMATION_SCHEMA over `SHOW TABLES STATUS` can easily be measured with MySQL itself. We’ve used MySQL 5.7.30 on Ubuntu 18.04, with `datadir` running on a high performance NVME SSD (Samsung PM1725b).
We’ve run 10 concurrent clients each executing 1,000,000 statements in a Magento database with demo data, once with the query `SHOW TABLES STATUS LIKE ‘catalog_product_entity’;` and once with our statement `SELECT COUNT(1) AS tbl_exists FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = ‘catalog_product_entity’ AND TABLE_SCHEMA = DATABASE();`.

Between these queries, we measured a difference of *slightly over factor 10* in the execution time, favoring our solution with INFORMATION_SCHEMA. See below for details.
We assume the difference is even bigger when having more concurrent clients or slower hardware. As MySQL’s “SHOW TABLE STATUS” implementation is reading the whole directory, file system locking can have a stronger effect as well as which file system is used.

Our performance measurements:
- create the files test1.sql and test2.sql with 1.000.000 rows of the statements to test.
- run these commands
  - `time seq 1 10 | parallel -j 10 bash -c 'mysql < test1.sql > /dev/null’`
  - `time seq 1 10 | parallel -j 10 bash -c 'mysql < test2.sql > /dev/null’`

Results:
For `SHOW TABLE STATUS`:
```
# time seq 1 10 |  parallel  -j 10 bash -c ' mysql   < test1.sql  > /dev/null’ 

real	85m21.374s
user	3m5.500s
sys	1m40.317s
```
For `INFORMATION_SCHEMA`:
```
time seq 1 10 |  parallel  -j 10 bash -c ' mysql   < test2.sql > /dev/null 


real	8m5.184s
user	1m54.587s
sys	1m11.687s
```

### Manual testing scenarios
To see the impact our patch has, load the same set of pages on the frontend with and without the patch on any Magento instance (with real or demo data). The difference can be seen when analyzing the amount of SQL queries sent to the database and the time spent processing them. Here’s an easy way to do this:

Using [Slow Query Log](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html), you can make MySQL actually log all queries by setting the threshold to 0 seconds:

```
SET @@GLOBAL.long_query_time = 0; SET @@GLOBAL.slow_query_log = 1;
```
After you’ve opened the selected set of frontend pages, deactivate it again:
```
SET @@GLOBAL.slow_query_log = 0;
```
Now, using `pt-query-digest` from the Percona Toolkit on the slow query log file, you get an analysis of the logged queries, with queries grouped by type, their average and cumulative run time, and other information. Make sure to use two different log files so that they can easily be compared between M2 with and without our patch.

In the analysis, you will usually see `SHOW TABLE STATUS` queries appearing in the top queries (this depends a bit on the module configuration and of course on which and how many pages you accessed for this test), meaning they're taking quite a good percentage of total execution time.

Please see these extracts from the `pt-query-digest` output for an example, which we created when simply opening the single category page “Men > Tops” from the demo data (`https://$BASEURL/men/tops-men.html?product_list_limit=36`).

Analysis of SQL queries run, *unpatched* Magento:
```
# Profile
# Rank Query ID                         Response time Calls R/Call V/M   I
# ==== ================================ ============= ===== ====== ===== =
#    1 0xAADD55611E492BA965AF2F067A0...  0.0099 34.3%    22 0.0004  0.00 SELECT catalog_product_index_eav search_tmp_?ed?d?dcc?b?_? cataloginventory_stock_status
#    2 0x7009A071F49236A84A57562D461...  0.0050 17.2%     1 0.0050  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price review_entity_summary review_entity cataloginventory_stock_status search_tmp_?ed?d?dccc?_?
#    3 0x8085D806F3631D0D30FE5C20326...  0.0036 12.5%     3 0.0012  0.00 SHOW TABLE STATUS
#    4 0x13262D434B03958CB4F62EC706B...  0.0011  3.9%     1 0.0011  0.00 INSERT SELECT search_tmp_?ed?d?dcc?b?_? catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#    5 0x2F9EDAB00084ED0A7EE1463DBA4...  0.0009  3.1%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
[...]
```
You can see that queries of the type `SHOW TABLE STATUS` are the third most expensive queries with 12.5% of the total execution time inside the database and 3 calls in total just for this single page load.

*Patched* Magento, opening the same category page:
```
# Profile
# Rank Query ID                         Response time Calls R/Call V/M   I
# ==== ================================ ============= ===== ====== ===== =
#    1 0xAADD55611E492BA965AF2F067A0...  0.0105 29.9%    22 0.0005  0.00 SELECT catalog_product_index_eav search_tmp_?ed?cf?f?c?a?_? cataloginventory_stock_status
#    2 0x8EA4DF263A535F59EAC6ED75B20...  0.0073 20.7%    24 0.0003  0.00 SELECT catalog_product_entity catalog_product_super_link catalog_product_website catalog_product_entity_int cataloginventory_stock_status
#    3 0x7009A071F49236A84A57562D461...  0.0050 14.2%     1 0.0050  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price review_entity_summary review_entity cataloginventory_stock_status search_tmp_?ed?cf?f?e?b?_?
#    4 0x13262D434B03958CB4F62EC706B...  0.0015  4.3%     1 0.0015  0.00 INSERT SELECT search_tmp_?ed?cf?f?c?a?_? catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#    5 0xCB3E7FA2C499AC0B69ACCD06C21...  0.0012  3.4%     2 0.0006  0.00 SELECT catalog_product_index_price search_tmp_?ed?cf?f?c?a?_?
#    6 0x2F9EDAB00084ED0A7EE1463DBA4...  0.0009  2.7%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
#    7 0x593763BE686057BEA87DB0BC232...  0.0008  2.4%    72 0.0000  0.00 SELECT inventory_stock_sales_channel
#    8 0x23B42F57B465E32E1732E4070E9...  0.0008  2.2%    72 0.0000  0.00 SELECT inventory_stock
#    9 0x11C6E1A6D7347EEAF29EBEA1350...  0.0008  2.2%     1 0.0008  0.00 SELECT catalog_product_index_eav cataloginventory_stock_status catalog_category_product_index_store?
#   10 0xA788DCC6FE9679C3FDABA74662A...  0.0007  1.9%     1 0.0007  0.00 SELECT catalog_product_entity catalog_category_product_index_store? catalog_product_index_price cataloginventory_stock_status search_tmp_?ed?cf?f?e?b?_?
#   11 0x961084F55005407CD1C1E76C0BE...  0.0006  1.7%     2 0.0003  0.00 SELECT eav_attribute_option_swatch
#   12 0xE29FDCAD0B27AFD15D17697A415...  0.0005  1.5%     1 0.0005  0.00 SELECT catalog_product_index_price search_tmp_?ed?cf?f?c?a?_?
#   13 0x233B56CFFF59C63BF02E08D9654...  0.0005  1.4%     2 0.0002  0.00 CREATE TABLE search_tmp_?ed?cf?f?e?b?_? `search_tmp_5ed8cf6f89e2b9_26325963`
#   14 0x2F0A3214F96ED5CD4E962B1E990...  0.0005  1.3%    24 0.0000  0.00 SELECT catalog_product_super_attribute catalog_product_entity catalog_product_super_link eav_attribute catalog_product_entity catalog_product_entity_int catalog_product_super_attribute_label eav_attribute_option
#   15 0xDD45A442CF95F62A11D72D7D0F8...  0.0004  1.2%     1 0.0004  0.00 SELECT catalog_category_product_index_store? search_tmp_?ed?cf?f?c?a?_? catalog_category_entity
#   16 0x616C07D9410BE0BBA2EBCD6D77C...  0.0003  0.8%    21 0.0000  0.00 SELECT eav_attribute
#   17 0xB3E930152F4418A1C656779CE44...  0.0003  0.7%    12 0.0000  0.00 SELECT catalog_product_super_attribute
#   18 0xDFE08A11F72783E309DFA58BA8F...  0.0003  0.7%    12 0.0000  0.00 SELECT catalog_category_product
#   19 0x58EA3033F7E981C7FACDF0DE8D3...  0.0002  0.7%    20 0.0000  0.00 SELECT catalog_eav_attribute
#   20 0x13867189A41845FE8E8C4366F7B...  0.0002  0.5%    12 0.0000  0.00 SELECT catalog_product_super_attribute_label
# MISC 0xMISC                            0.0020  5.6%    74 0.0000   0.0 <38 ITEMS>
```
We’ve had to include the full summary in this case to show that our implementation not only eliminates the common cause for `SHOW TABLE STATUS` queries, but also that the new queries to INFORMATION_SCHEMA.TABLES do not occur in the top 20 queries.
This already illustrates that we’ve found a good solution to improve the performance of table existence checks. The complete impact can be estimated from observing production stores with many concurrent page views, where we see thousands of `SHOW TABLE STATUS` queries in 2–3 minutes.

### Questions or comments
- The commit in this pull request is a combined work of @jonashrem and @leeps.
- We haven’t created an issue for this improvement, but can do that if it’s needed/wanted.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29662: Rewrote Magento\Framework\DB\Adapter\Pdo\Mysql->isTableExists

### CODE REVIEW

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
@magento run Static Tests

**Comment by jonashrem** [comment]
@magento run Functional Tests CE
@magento run Functional Tests EE

**Comment by jonashrem** [comment]
@magento run Functional Tests EE

**Comment by jonashrem** [comment]
@magento run Functional Tests B2B

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
@magento run Functional Tests B2B

**Comment by jonashrem** [comment]
@magento run Functional Tests CE

**Comment by jonashrem** [comment]
@magento run Static Tests

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Review by aleron75 — DISMISSED** [review]

**Comment by aleron75** [comment]
The failing integration test doesn't seem related to this PR.
The affected method is used in a lot of tests so to me this satisfies test coverage.
Thus I approved this PR.

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-7622](https://jira.corp.magento.com/browse/ENGCOM-7622) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
We tested the failing Integration test on 2.3.5-p1 and it didn't fail there, so I agree that this isn't related to our change.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Integration test fails, even after restarting few times. Looks like your change caused regression in some specific case - image resize command fails in case if DB storage used.

@jonashrem could you try to run following test locally? https://github.com/magento/magento2/blob/40a787632f36ca67f8fff8c451e1e8d1bdbaf9f6/dev/tests/integration/testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php#L120-L124

**Comment by jonashrem** [comment]
@magento give me 2.4-develop instance

**Comment by magento-engcom-team** [comment]
Hi @jonashrem. Thank you for your request. I'm working on Magento 2.4-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @jonashrem, here is your [Magento instance](https://i-28516-2-4-develop.instances.magento-community.engineering).
Admin access: [https://i-28516-2-4-develop.instances.magento-community.engineering/admin_6f30](https://i-28516-2-4-develop.instances.magento-community.engineering/admin_6f30)
Login: `0f11a9f8` Password: `4e5687cd5838`
Instance will be terminated in up to 3 hours.

**Comment by jonashrem** [comment]
@ihor-sviziev thanks for the review.

We tested this integrationtest locally on 2.3.5-p1 before.

We now did another local test on our PR directly, but also couldn't reproduce this error.

Can you check we run the test correctly or do we need to do some special Magento settings here (for preparing DB Storage for example)?

We cloned our instance, did `composer install` and run the test.

```
dev/tests/integration # ../../../vendor/bin/phpunit --testdox testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php
PHPUnit 9.1.5 by Sebastian Bergmann and contributors.

Warning:       Using a custom test suite loader is deprecated

Image Resize Command (Magento\MediaStorage\Console\Command\ImageResizeCommand)
 ✔ Run resize with missing file
 ✔ Execute with zero byte image
 ✔ Database storage missing file

Time: 00:19.762, Memory: 111.00 MB

OK (3 tests, 3 assertions)

=== Memory Usage System Stats ===
Memory usage (OS):      141.02M (129.38% of 109.00M reported by PHP)
Estimated memory leak:  32.02M (22.71% of used memory)
```

```
dev/tests/integration # git remote -v                                                                                                          
origin  https://github.com/jonashrem/magento2.git (fetch)
origin  https://github.com/jonashrem/magento2.git (push)
```

```
dev/tests/integration # git branch
  2.4-develop
* faster-isTableExists
```

```
dev/tests/integration # cat etc/install-config-mysql.php
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

return [
    'db-host' => 'localhost',
    'db-user' => 'db-user-4',
    'db-password' => '*',
    'db-name' => 'db-4',
    'db-prefix' => '',
    'backend-frontname' => 'backend',
    'admin-user' => \Magento\TestFramework\Bootstrap::ADMIN_NAME,
    'admin-password' => \Magento\TestFramework\Bootstrap::ADMIN_PASSWORD,
    'admin-email' => \Magento\TestFramework\Bootstrap::ADMIN_EMAIL,
    'admin-firstname' => \Magento\TestFramework\Bootstrap::ADMIN_FIRSTNAME,
    'admin-lastname' => \Magento\TestFramework\Bootstrap::ADMIN_LASTNAME,
//    'amqp-host' => 'localhost',
//    'amqp-port' => '5672',
//    'amqp-user' => 'guest',
//    'amqp-password' => 'guest',
];

```

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@engcom-Golf @engcom-Charlie could you help to understand why integration tests fails on CI, while successfully executes locally?

**Comment by jonashrem** [comment]
@engcom-Golf @engcom-Charlie @ihor-sviziev how is the status here? Is there anything, we can do to help in regard of this integration tests or the PR?

As I understand, the cloud instances provided by the m2-assistant bot don't come with ssh access to manually run the rests.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
@engcom-Charlie did you find out anything?

**Comment by engcom-Charlie** [comment]
Unfortunately, I don't have an idea at the moment.

**Comment by ihor-sviziev** [comment]
@slavvka @lenaorobei @naydav could you help to understand why integration test fails on CI, while on local machine it passes?

**Comment by lenaorobei** [comment]
I found following error in logs
```
Magento\MediaStorage\Console\Command\ImageResizeCommandTest::testDatabaseStorageMissingFile
PHPUnit\Framework\Exception: Error in fixture: "\/var\/www\/html\/dev\/tests\/integration\/testsuite\/Magento\/MediaStorage\/_files\/product_with_missed_image.php".
 SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction, query was: SELECT `e`.* FROM `media_storage_directory_storage` AS `e` WHERE (name = 'a') AND (path = 'tmp/catalog/product/m')
```

**Comment by leeps** [comment]
Thank you, @lenaorobei, that helped!
We will look into this issue and get back to you all within a few days.

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
Hmm, quite confusing.

Changing the order of tests doesn't help, fallback to old behavior on non hit doesn't help (#29153) and removing the new cache doesn't help as well (#29152).

**Comment by jonashrem** [comment]
We are still working on this through. So do not close this, please.

**Comment by ihor-sviziev** [comment]
Sure, no problem

**Comment by jonashrem** [comment]
Btw. is it possible, to get PHP Settings (like phpinfo or php --i and MySQL Settings "show variables \G" to compare with our environment?

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@jonashrem @engcom-Charlie maybe there should be some isolation enabled / disabled for failing test?

**Comment by jonashrem** [comment]
@jonashrem @engcom-Charlie  thanks for the Hint. Do you have details how to enable this?

**Comment by engcom-Charlie** [comment]
@jonashrem you can see details here https://devdocs.magento.com/guides/v2.4/test/integration/annotations.html

**Comment by Vinai** [comment]
@ihor-sviziev Hi Ihor, good idea.
`@magentoDbIsolation` is automatically enabled when a test uses a `@magentoDataFixture` annotation so it would only be possible to explicitly disable DB isolation it for the test.

The `@magentoAppIsolation enabled` annotation on the other hand will cause the test framework to re-initialize the Magento app after the test, so it won't have an effect on the test itself, only on following tests.

I think you likely are right, but it is some other test that is missing one of these annotations. The tricky thing is figuring out which test is breaking test isolation and causing the failure of `Magento\MediaStorage\Console\Command\ImageResizeCommandTest::testDatabaseStorageMissingFile`

FYI, @jonashrem asked me to spend some time and try to find the cause, so I'm trying to bisect the testsuite to isolate the failure combination.
However, this requires a test environment where the error can be reproduced, which in turn requires fixing some other errors that happen when the whole suite is run in a local environment. It's a slow process, but maybe it will turn up something.

**Comment by ihor-sviziev** [comment]
@Vinai FYI https://warden.dev/ works pretty good for many people ;)

**Comment by Vinai** [comment]
@ihor-sviziev I love warden and use it a lot, but the last time I checked the integration test suite didn't complete there either.

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
@magento run Integration Tests

**Comment by jonashrem** [comment]
ok. Disabled the Isolation actually helps, but now another test (/MediaStorage/Helper/File/Storage/DatabaseTest) is failing only for B2B edition (just running the test again to make sure it's realy related to the change).

Very confusing. Is there anything special with B2B? @ihor-sviziev ?

The exact same test runs fine on CE and EE.

**Comment by jonashrem** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
Ok. Never mind. With changing both tests, the test run through.

@ihor-sviziev 

Is this fine for merging or do you need us, to make changes to Magento until the test pass with Isolation enabled ( As I see, there are already multiple tests with disabled isolation)

File: dev/tests/integration/testsuite/Magento/MediaStorage/Helper/File/Storage/DatabaseTest.php [hunk 1]
```diff
@@ -52,7 +52,7 @@ protected function setUp(): void
     /**
      * test for \Magento\MediaStorage\Model\File\Storage\Database::deleteFolder()
      *
-     * @magentoDbIsolation enabled
+     * @magentoDbIsolation disabled
```
Comment (ihor-sviziev) [inline dev/tests/integration/testsuite/Magento/MediaStorage/Helper/File/Storage/DatabaseTest.php:55]: Note for QA: Need to make sure this test is not leaving any data in DB after test run.

File: dev/tests/integration/testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php [hunk 2]
```diff
@@ -116,6 +116,7 @@ public function testExecuteWithZeroByteImage()
      *
      * @magentoDataFixture Magento/MediaStorage/_files/database_mode.php
      * @magentoDataFixture Magento/MediaStorage/_files/product_with_missed_image.php
+     * @magentoDbIsolation disabled
```
Comment (ihor-sviziev) [inline dev/tests/integration/testsuite/Magento/MediaStorage/Console/Command/ImageResizeCommandTest.php:119]: Note for QA: Need to make sure this test is not leaving any data in DB after test run.

**Review by ihor-sviziev — APPROVED** [review]
Good job! Approved! ✔

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7622](https://jira.corp.magento.com/browse/ENGCOM-7622) has been created to process this Pull Request

**Comment by sidolov** [comment]
@magento create issue

**Comment by jonashrem** [comment]
@ihor-sviziev @sidolov 

As I can't see the internal ticket. Is there anything left, we can do, to help the processing of this PR?

**Comment by ihor-sviziev** [comment]
The PR is waiting for QA process, it’s public info. No actions required
from your side

**Comment by jonashrem** [comment]
Ok. Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by jonashrem** [comment]
@magento  run Functional Tests CE

**Comment by jonashrem** [comment]
@magento run Functional Tests B2B

**Comment by magento-engcom-team** [comment]
Pull request successfully imported to branch `imported-magento-magento2-28516` in the `magento-engcom/magento2ce` repository.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7622](https://jira.corp.magento.com/browse/ENGCOM-7622) has been created to process this Pull Request

**Comment by sidolov** [comment]
Note for QA: the solution should be verified with cases when tables have been changed in DB.

Example: 
1. Check table exists for the first time (cache is generated)
2. Remove or rename a table
3. Check table presence once again. 

I suspect that we will get an error since the result is cached but the actual table was removed.

**Comment by jonashrem** [comment]
> Note for QA: the solution should be verified with cases when tables have been changed in DB.
> 
> Example:
> 
>     1. Check table exists for the first time (cache is generated)
> 
>     2. Remove or rename a table
> 
>     3. Check table presence once again.
> 
> 
> I suspect that we will get an error since the result is cached but the actual table was removed.

One renaming and dropping tables, the cache will be cleared ( https://github.com/magento/magento2/blob/b597c7a0a80072a73a4914b1d80644a57445cb46/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2721 and https://github.com/magento/magento2/blob/b597c7a0a80072a73a4914b1d80644a57445cb46/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php#L2616 ), so both should be fine.

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x:
image

**After:** :heavy_check_mark: 
image
