### PR TITLE
Fixed 24990: link doesn't redirect to dashboard

### LINKED ISSUE #24990: Admin Panel logo link is not directing to admin dashboard page
### Preconditions (*)

1. Magento 2.3

### Steps to reproduce (*)

1. Go to magento admin  -> System -> Web Setup Wizard page.
2. Click on magento admin logo

### Expected result (*)

1. On click magento admin panel logo, It should redirect to admin dashboard page

### Actual result (*)

1. 
admin_panel_logo

2. Logo link is not redirecting to magento admin dashboard page upon click

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixed #24990 issue 

### Fixed Issues (if relevant)

1. magento/magento2#24990: Admin Panel logo link is not directing to admin dashboard page

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26100.instances.magento-community.engineering).
Admin access: [https://pr-26100.instances.magento-community.engineering/admin](https://pr-26100.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

File: setup/src/Magento/Setup/Controller/Navigation.php [hunk 1]
```diff
@@ -32,14 +33,20 @@ class Navigation extends AbstractActionController
...
+     * @var ObjectManagerProvider $objectManagerProvider
+     */
+    protected $objectManagerProvider;
+
     /**
      * @param NavModel $navigation
      * @param Status $status
      */
-    public function __construct(NavModel $navigation, Status $status)
+    public function __construct(NavModel $navigation, Status $status, ObjectManagerProvider $objectManagerProvider)
```
Comment (lbajsarowicz) [inline setup/src/Magento/Setup/Controller/Navigation.php:47]: Why do you use `ObjectManagerProvider` instead of injecting just `UrlInterface`?

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]

File: setup/src/Magento/Setup/Controller/Navigation.php (hunk 1 above)
Comment (Usik2203) [reply setup/src/Magento/Setup/Controller/Navigation.php:47]: I am getting such error "An error occurred during execution; please try again later" and status 500 while injecting `UrlInterface` directly in constructor of controller

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26100.instances.magento-community.engineering).
Admin access: [https://pr-26100.instances.magento-community.engineering/admin_fbea](https://pr-26100.instances.magento-community.engineering/admin_fbea)
Login: `a8bacc76` Password: `98beb8e12485`
Instance will be terminated in up to 3 hours.

File: setup/src/Magento/Setup/Controller/Navigation.php [hunk 2]
```diff
@@ -57,7 +59,7 @@ public function __construct(NavModel $navigation, Status $status, ObjectManagerP
      */
     public function indexAction()
     {
-        $json = new JsonModel;
+        $json = new JsonModel();
```
Comment (lbajsarowicz) [inline setup/src/Magento/Setup/Controller/Navigation.php]: Why are you instantiating classes with `new` instead of using `Factory` or just Dependency Injection?

File: setup/src/Magento/Setup/Controller/Navigation.php [hunk 3]
```diff
@@ -79,11 +81,12 @@ public function menuAction()
...
     /**
      * @return array|ViewModel
+     * @throws Exception
      */
     public function sideMenuAction()
     {
-        /** @var \Magento\Backend\Model\UrlInterface $backendUrl */
-        $backendUrl = $this->objectManagerProvider->get()->get(\Magento\Backend\Model\UrlInterface::class);
+        /** @var UrlInterface $backendUrl */
+        $backendUrl = $this->objectManagerProvider->get()->get(UrlInterface::class);
```
Comment (lbajsarowicz) [inline setup/src/Magento/Setup/Controller/Navigation.php]: You should inject that class to the constructor.

File: setup/src/Magento/Setup/Controller/Navigation.php [hunk 4]
```diff
@@ -47,7 +49,7 @@ public function __construct(NavModel $navigation, Status $status, ObjectManagerP
         $this->navigation = $navigation;
         $this->status = $status;
         $this->objectManagerProvider = $objectManagerProvider;
-        $this->view = new ViewModel;
+        $this->view = new ViewModel();
```
Comment (lbajsarowicz) [inline setup/src/Magento/Setup/Controller/Navigation.php:52]: Why are you instantiating classes with `new` instead of using `Factory` or just Dependency Injection?

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
1. Instantiation of the classes with `new` keyword
2. Use of Object Manager.

File: setup/src/Magento/Setup/Controller/Navigation.php (hunk 2 above)
Comment (Usik2203) [reply setup/src/Magento/Setup/Controller/Navigation.php]: Fixed

File: setup/src/Magento/Setup/Controller/Navigation.php (hunk 4 above)
Comment (Usik2203) [reply setup/src/Magento/Setup/Controller/Navigation.php:52]: I cannot create through Factory  or Dependency Injection as usual I am getting such error 
Screenshot 2020-02-18 at 10 28 44
Also I see a lot of cases in `setup/src/Magento/Setup/Controller` were these object was created with `new`

File: setup/src/Magento/Setup/Controller/Navigation.php (hunk 3 above)
Comment (Usik2203) [reply setup/src/Magento/Setup/Controller/Navigation.php]: Hi @lbajsarowicz ,
Unfortunately I can't inject `\Magento\Backend\Model\UrlInterface`directly to constructor. I get such error.
Screenshot 2020-02-03 at 18 24 27

Also I want to notice that construction  like this  `$this->objectManagerProvider->get()` is used in a lot of cases. 

If such approach is wrong, maybe You could advise me something ?

Thanks a lot!

**Comment by Usik2203** [comment]
Hi @lbajsarowicz . 
Do You have any news about this PR?
Thanks

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Usik2203, could you please fix the conflicting file?
Thank you.

**Comment by Usik2203** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @Usik2203. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @Usik2203, here is your [new Magento instance](https://pr-26100.instances.magento-community.engineering).
Admin access: [https://pr-26100.instances.magento-community.engineering/admin_d008](https://pr-26100.instances.magento-community.engineering/admin_d008)
Login: `98980e15` Password: `96989c682533`
Instance will be terminated in up to 3 hours.

**Review by eduard13 — APPROVED** [review]
The failing Unit Test isn't related with these changes.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7237](https://jira.corp.magento.com/browse/ENGCOM-7237) has been created to process this Pull Request
:eight_spoked_asterisk: @eduard13, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Usik2203, sorry, forgot about the test coverage, could you please cover this fix by a simple MFTF test? You can add it in scope of Magento_Backend module.
Thank you.

File: app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+       xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminLogoLinkSetupWizardPageTest">
+        <annotations>
+            <features value="Backend"/>
+            <stories value="Logo link on Setup Wizard Page"/>
+            <title value="Check active Logo link on Setup Wizard Page"/>
+            <description value="Check active Logo link on Setup Wizard Page"/>
+        </annotations>
+        <before>
+            <actionGroup ref="LoginAsAdmin" stepKey="loginToAdminPanel"/>
```
Comment (eduard13) [inline app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml]: Please use `AdminLoginActionGroup` as `LoginAsAdmin` is deprecated.

File: app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml [hunk 6]
```diff
@@ -0,0 +1,29 @@
...
+-->
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+       xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminLogoLinkSetupWizardPageTest">
+        <annotations>
+            <features value="Backend"/>
+            <stories value="Logo link on Setup Wizard Page"/>
+            <title value="Check active Logo link on Setup Wizard Page"/>
+            <description value="Check active Logo link on Setup Wizard Page"/>
```
Comment (eduard13) [inline app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml]: Please provide a better explanation of what this test does, as we make sure that the logo link redirects to Admin Panel.

File: app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+<!--
+ /**
+  * Copyright © Magento, Inc. All rights reserved.
+  * See COPYING.txt for license details.
+  */
+-->
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+       xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminLogoLinkSetupWizardPageTest">
```
Comment (eduard13) [inline app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml]: I'd rather use the following name for the test.
```suggestion
    <test name="AdminRedirectToAdminPanelOnLogoFromWizardPageClickTest">
```
Don't forget to adjust the test file as well.

File: app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+        </annotations>
+        <before>
+            <actionGroup ref="LoginAsAdmin" stepKey="loginToAdminPanel"/>
+        </before>
+        <after>
+            <actionGroup ref="AdminLogoutActionGroup" stepKey="logoutFromAdmin"/>
+        </after>
+
+        <amOnPage url="{{AdminSetupWizardPage.url}}" stepKey="navigateToSetupWizardPage"/>
+        <waitForPageLoad stepKey="waitForSetupWizardPageLoaded"/>
```
Comment (eduard13) [inline app/code/Magento/Backend/Test/Mftf/Test/AdminLogoLinkSetupWizardPageTest.xml]: Move this into a separate ActionGroup.

File: app/code/Magento/Backend/Test/Mftf/ActionGroup/AdminClickLogoActionGroup.xml [hunk 9]
```diff
@@ -0,0 +1,15 @@
...
+  * Copyright © Magento, Inc. All rights reserved.
+  * See COPYING.txt for license details.
+  */
+-->
+
+<actionGroups xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+              xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
+    <actionGroup name="AdminClickLogoActionGroup">
+        <click selector="{{AdminMenuSection.logo}}" stepKey="clickLogoInAdmin"/>
+        <seeInCurrentUrl url="{{AdminDashboardPage.url}}" stepKey="seeAdminDashboardUrl"/>
```
Comment (eduard13) [inline app/code/Magento/Backend/Test/Mftf/ActionGroup/AdminClickLogoActionGroup.xml]: Please remove this assertion. This Action Group is supposed only to click on the element.
```suggestion
        <waitForPageLoad stepKey="waitForAdminDashboardPageLoaded"/>
```

To check the Admin Dashboard, use the following Action Group `AssertAdminDashboardPageIsVisibleActionGroup`.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Please check the below comments

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-7237](https://jira.corp.magento.com/browse/ENGCOM-7237) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**
1. Go to Admin -> System -> Web Setup Wizard page;
2. Click on Magento admin logo;

**Actual Result:**
:heavy_check_mark: redirected to the admin dashboard page
wizard

**Comment by lbajsarowicz** [comment]
Sorry, I've tried to unassign me from the PR.

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7237](https://jira.corp.magento.com/browse/ENGCOM-7237) has been created to process this Pull Request
