### PR TITLE
magento/magento2#39861: Shipment email not sent when submitted from Admin Order view despite being enabled in store configuration

### LINKED ISSUE #39861: Shipment email not sent when submitted from Admin Order view despite being enabled in store configuration
### Preconditions and environment

- Magento version
　2.4.7-p5
- Multi-store setup with different configurations for shipment emails
- Default store has shipment emails disabled
- Secondary store has shipment emails enabled

### Steps to reproduce

1. Set up a multi-store configuration where the default store has shipment emails disabled
2. Create an order in a secondary store that has shipment emails enabled
3. Go to Admin > Sales > Orders
4. Open the order from the secondary store
5. Click on "Ship" button
6. Fill in shipment details and check "Email Copy of Shipment"
7. Submit the shipment

### Expected result

The system should send a shipment confirmation email as it is enabled in the store configuration where the order was placed.

### Actual result

No shipment confirmation email is sent because the system checks the default store configuration instead of the store configuration where the order was placed.

## Root cause analysis
In Save.php at line 170, the shipment email sending condition is checked using:

```php
if (!empty($data['send_email']) && $this->salesData->canSendNewShipmentEmail())
```

The `canSendNewShipmentEmail()` method is called without passing the store ID parameter. This causes the system to check the configuration of the default store instead of the store where the order was placed.

The correct implementation should pass the order's store ID to this method:

```php
if (!empty($data['send_email']) && $this->salesData->canSendNewShipmentEmail($shipment->getOrder()->getStoreId()))
```

This issue affects multi-store setups where different stores have different email configuration settings.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by KrasnoshchokBohdan**
### Description (*)

\Magento\Shipping\Controller\Adminhtml\Order\Shipment\Save::execute
```
if (!empty($data['send_email']) && $this->salesData->canSendNewShipmentEmail()) {
                $this->shipmentSender->send($shipment);
 }
```
without the right 'store id' checks only default config value  

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/39861

### Manual testing scenarios (*)

1. Set up a multi-website configuration where the default has shipment emails disabled
2. Create an order in a secondary website that has shipment emails enabled
3. Go to Admin > Sales > Orders
4. Open the order from the secondary store
5. Click on "Ship" button
6. Fill in shipment details and check "Email Copy of Shipment"
7. Submit the shipment

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @KrasnoshchokBohdan,

Thanks for the contribution!

The changes looks good to us, but please add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
The build is green now, hence moving this to Merge In Progress.
image

File: app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save.php [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (Den4ik) [inline app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save.php]: @engcom-Hotel 
If I'm correct, the file creation date should be used here — it's 2014, not 2015.

File: app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/SaveTest.php [hunk 2]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (Den4ik) [inline app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/SaveTest.php]: Same here, file creation date is 2014, not 2015.

File: app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save.php (hunk 1 above)
Comment (engcom-Hotel) [reply app/code/Magento/Shipping/Controller/Adminhtml/Order/Shipment/Save.php]: Corrected thanks @Den4ik

File: app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/SaveTest.php (hunk 2 above)
Comment (engcom-Hotel) [reply app/code/Magento/Shipping/Test/Unit/Controller/Adminhtml/Order/Shipment/SaveTest.php]: Corrected, thanks @Den4ik

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
Looks good

**Comment by engcom-Hotel** [comment]
Moving it to Merge in progress
