### PR TITLE
magento/magento2#26107: Exception message on cart with no shipment items

### LINKED ISSUE #26107: Customer got an error about Virtual Product after setting the shipping address on Cart that contains Downloadable Product only
### Preconditions (*)

1. No preconditions

### Steps to reproduce (*)

1.  Create a cart with a downloadable product and try to set the shipping address

### Expected result (*)

1. A proper message

### Actual result (*)

1. Message about Virtual Product
```graphql
{
  "errors": [
    {
      "message": "The Cart includes virtual product(s) only, so a shipping address is not used.",
      "category": "graphql-no-such-entity",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "setShippingAddressesOnCart"
      ]
    }
  ],
  "data": {
    "setShippingAddressesOnCart": null
  }
}
```

### PR DESCRIPTION
**Pull request by michalderlatka**
### Description (*)
Changes exception message when cart has only products with no shipment

### Fixed Issues (if relevant)
1. Fixes magento/magento2#26107

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by michalderlatka** [comment]
@magento run all tests

File: app/code/Magento/Quote/Model/ShippingAddressManagement.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ public function assign($cartId, \Magento\Quote\Api\Data\AddressInterface $addres
         $quote = $this->quoteRepository->getActive($cartId);
         if ($quote->isVirtual()) {
             throw new NoSuchEntityException(
-                __('The Cart includes virtual product(s) only, so a shipping address is not used.')
+                __('Shipping address is not allowed on cart: cart contains no items for shipment.')
```
Comment (cpartica) [inline app/code/Magento/Quote/Model/ShippingAddressManagement.php]: usually a patch release "2.4.1" we can't change phrases.
Since this happens in core,  I would rather introduce a new phrase in graphql only by catching NoSuchEntityException + $quote->isVirtual()

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by michalderlatka** [comment]
@magento run all tests

**Comment by michalderlatka** [comment]
@magento run all tests

**Review by cpartica — APPROVED** [review]
