### PR TITLE
Fixes customer edit issue when there is a newsletter queue associated with it.

### LINKED ISSUE #30645: Customer Edit Issue when there is a newsletter queue associated with it.
### Preconditions (*)

Installed a fresh copy of Magento 2.3.5-P2 with no sample data. Upgrade using composer to 2.4 (where we see the issue) and then upgrade to 2.4.1 (where issue is still present). 

1. I tried on 2.4.0 and 2.4.1 and they both have the same issue. 
1. Reproducible on 2.4-develop

### Steps to reproduce (*)

1. Add a new customer which is also subscribed to newsletter.
1. Create a a newsletter in Marketing>Newsletter Templates
1. Queue the newsletter
1. Go to customer and try to edit their information - This is what we get (https://prnt.sc/v642qm)
1. Go create a new customer and subscribe to newsletter (however this new customer is not and has not been in any newsletter queue yet) - When we go and edit this customer, everything is ok  (https://prnt.sc/v64460).

### Expected result (*)

1. See Screenshot (https://prnt.sc/v64460)

### Actual result (*)

1. See Screenshot (https://prnt.sc/v642qm)

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30645  Customer Edit Issue when there is a newsletter queue associated with it.

### Manual testing scenarios (*)

1.  magento/magento2#30645 Customer Edit Issue when there is a newsletter queue associated with it.
2. Please check newsletter tab queue grid functionality on the customer edit page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by aleron75** [comment]
@magento give me 2.4-develop instance

**Comment by aleron75** [comment]
@magento give me test instance

File: dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php [hunk 1]
```diff
@@ -74,6 +76,9 @@ public function testRenderingNewsletterBlock()
         );
         $this->assertStringNotContainsString('checked="checked"', $body);
         $this->assertStringContainsString('\u003Cspan\u003ESubscribed to Newsletter\u003C\/span\u003E', $body);
-        $this->assertStringContainsString('\u003ENo Newsletter Found\u003C', $body);
+        $this->assertMatchesRegularExpression(
```
Comment (aleron75) [inline dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php:91]: Hello @engcom-Golf,
thanks for your PR. 

Please help me understand something that is unclear to me.

According to the following assertion: 

`$this->assertStringNotContainsString('checked="checked"', $body);` 

we expect that the customer is not subscribed; 

but according to the newly added assertion:

`$this->assertMatchesRegularExpression('~.+\/newsletter\\\/template\\\/preview\\\/id\\\/\d+\\\/subscriber\\\/\d+\\\/.+~', $body);`

it seems we expect that the customer was considered a subscriber because we expect to see the preview link in the grid of queued emails.

Furthermore, looking at the fixtures, I don't see any subscription created for the test customer so I don't get how the tests can pass.

Thanks

Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php:91]: As an example, the customer can unsubscribe from newsletters but have already received ones. They have to be shown in the grid with sent status. The logic of drawing the subscription checkbox is not connected with the newsletters queue.

File: dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php [hunk 2]
```diff
@@ -59,6 +59,8 @@ protected function tearDown(): void
 
     /**
      * @magentoDataFixture Magento/Customer/_files/customer_sample.php
+     * @magentoDataFixture Magento/Newsletter/_files/newsletter_sample.php
```
Comment (zakdma) [inline dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php]: I would recommend make new test case for that and leave old as is

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/Newsletter/Model/ResourceModel/Queue/Collection.php [hunk 3]
```diff
@@ -225,7 +225,10 @@ public function addCustomerFilter(int $customerId): Collection
             )->join(
                 ['subscriber' => $this->getTable('newsletter_subscriber')],
                 'link.subscriber_id=subscriber.subscriber_id',
-                ['subscriber_store_id' => 'subscriber.store_id']
+                [
```
Comment (zakdma) [inline app/code/Magento/Newsletter/Model/ResourceModel/Queue/Collection.php:228]: Please cover this code changes with integration test

File: dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php (hunk 1 above)
Comment (aleron75) [reply dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php:91]: I get the point on the checkbox, but I don't understand where in the fixtures we set a received newsletter for the customer.

To clarify, I verified the PR and it seems ok, it solves the issue, I want just to check whether we have a false positive test or it's just me :)

File: dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php (hunk 2 above)
Comment (engcom-Golf) [reply dev/tests/integration/testsuite/Magento/Customer/Block/Adminhtml/Edit/Tab/NewsletterTest.php]: done

File: app/code/Magento/Newsletter/Model/ResourceModel/Queue/Collection.php (hunk 3 above)
Comment (engcom-Golf) [reply app/code/Magento/Newsletter/Model/ResourceModel/Queue/Collection.php:228]: covered in dev/tests/integration/testsuite/Magento/Newsletter/Model/ResourceModel/Queue/CollectionTest.php

**Comment by engcom-Golf** [comment]
@magento run all tests

**Review by zakdma — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Add a new customer which is also subscribed to newsletter.
Sub news

2. Create a newsletter in Marketing>Newsletter Templates
New template

3. Queue the newsletter
queue news

4. Go to the customer edit page and try to edit their information

**Before** applying changes provided in this PR

97159123-0e1f0280-1783-11eb-8f7d-74322d645e42

**After** switching to the PR
Customer

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: 
Correct `template_id` and `subscriber_id` is set in the **View** newsletter template link _admin/newsletter/template/preview/id/**3**/subscriber/**3**/key/5e2ce99354cdf81dbd3a3e2989d4c0706b3f75d43f0a77cd0462e7f98345686a/_
Correct subscriber_id and customer_id in `newsletter_subscriber` database table
db_template

**Review by aleron75 — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

Retested with the latest commit

**Comment by zakdma** [comment]
@magento import pull request to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the pull request successfully imported.
