### PR TITLE
magento/magento2#39111: Product Collection - addMediaGalleryData call…

### LINKED ISSUE #39111: Product Collection - addMediaGalleryData calls getSize when the collection maybe or will be loaded (Can use count to avoid an extra DB query)
### Preconditions and environment

- Present on 2.4-develop
    - Likely present on most previous M2 versions

The call to getSize is clearly un-needed for the GQL code path for products.
- [ProductGql's CollectionPostProcessor](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/Product/CollectionPostProcessor.php#L33) calls isLoaded and if not loaded calls load. Then it calls addMediaGalleryData. (If needed).
- [Product Collection's addMediaGalleryData](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ResourceModel/Product/Collection.php#L2365) calls  `if (!$this->getSize()) {` on a collection that is loaded already. At this point we can call count. (Or just check the empty on the getItems).

It should be safe to add a `if($this->isLoaded())` prior to calling getSize, and if loaded, call count instead of getSize.
(It should also be safe to just use the count/empty of getItems, (As getItems calls load), but calling isLoaded and using count should be safe and would mitigate this specific issue).

### Steps to reproduce

1. Enable dev query log
1. This should be reproducible by calling the products GQL call with the media*gallery/media_gallery*entries field selected.
1. The count call should be in the query log, traced to addMediaGalleryData

### Expected result

getSize is not called on a loaded product collection. (When the non-paginated count is not needed).

### Actual result

getSize is called on a loaded paginated collection to check if it has data.

### Additional information

*No response*

### Release note

*No response*

### Triage and priority

- < ] Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
- [ ] Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
- [ ] Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
- [X] Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
- [ > Severity: **S4** *- Affects aesthetics, professional look and feel, "quality" or "usability".*

### PR DESCRIPTION
**Pull request by Himsoft**
### Description (*)

\Magento\Catalog\Model\ResourceModel\Product\Collection::addMediaGalleryData calls getSize if the collection is loaded.

- Fixed call count instead of getSize if collection is loaded.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39111

### Manual testing scenarios (*)

1. Enable dev query log
2. Call the products GQL with the media_gallery/media_gallery_entries field selected.
3. The method (getSize or count) call should be in the query log, traced to addMediaGalleryData

Before fix:
getSize is called on a loaded product collection

After fix:
count is called on a loaded product collection

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
The failed tests are not related to fixes, they look like false positives, please pay attention to this during the review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/CollectionTest.php [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2025 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/Test/Unit/Model/ResourceModel/Product/CollectionTest.php]: This must be 2015, as the file created in this year only.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Himsoft,

Thanks for the contribution!

The changes looks good to me, just one change as suggested below.

**Comment by Himsoft** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@Himsoft  Thank you for contribution & collaboration!

✔️   **QA Passed**

Preconditions:
Install Fresh Magento 2.4-develop

Steps to reproduce:

1. Enable dev query log using command:  "bin/magento dev:query-log:enable"
2. Call the products Graphql with the media_gallery field selected.

Screenshot 2025-04-04 at 3 55 58 PM

**Before:** 

As per PR description **getSize()** was getting called on already loaded collection which was increasing the call trace with one more query.

image


**After:**

Count() function is called if the collection is already loaded. only one trace found for addMediaGalleryData.

image

Added Loggers in the code to check is count getting called or not as the call was not there in the db.log

image

image

Functional Tests are failing hence moving this PR to Extended Testing.

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Dash** [comment]
All checks have been completed and the build is green. Hence moving this PR in Merge In Progress.

image
