### PR TITLE
Fix #10583: Checkout place order exception when using a new address

### LINKED ISSUE #10583: Checkout place order exception when using a new address
### Preconditions
1. Magento 2.1.8 CE
2. PHP 7.0
3. Have a plugin on `\Magento\Customer\Api\Data\CustomerInterface` (any function, the plugin doesn't have to do anything)

### Steps to reproduce
1. Register as new customer
2. Add a product to your cart
3. Go to the checkout page
4. Fill in your address details and go through the checkout steps
5. Place an order

### Expected result
1. Order is placed and the address is added to your address book

### Actual result
1. The checkout displays the error message "An error occurred on the server. Please try to place the order again."

The actual error message is this: InvalidArgumentException: Getter return type must be specified using @return annotation. See Magento\Customer\Model\Data\Customer\Interceptor::getDefaultBilling() in vendor/magento/framework/Reflection/TypeProcessor.php on line 305

This error is caused in: `\Magento\Quote\Model\Quote::updateCustomerData()` by 
`$this->dataObjectHelper->mergeDataObjects(get_class($quoteCustomer), $quoteCustomer, $customer);`

The `$quoteCustomer` is the interceptor, and the `TypeProcessor` can't retrieve the required docblock information from it.

### PR DESCRIPTION
**Pull request by YevSent**
### Fixed Issues
1. magento/magento2#10583: Checkout place order exception when using a new address

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

File: lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php [hunk 1]
```diff
@@ -25,6 +27,12 @@ class TypeProcessorTest extends \PHPUnit\Framework\TestCase
     protected function setUp()
     {
         $this->_typeProcessor = new \Magento\Framework\Reflection\TypeProcessor();
+        $loader = new ClassLoader();
+        $loader->addPsr4(
```
Comment (orlangur) [inline lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php]: Why do we need to hack autoloader instead of placing fixtures accordingly?

File: lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+namespace Magento\Framework\Reflection\Test\Unit;
+
+class TSample implements TSampleInterface
+{
+    /**
+     * {@inheritdoc}
```
Comment (orlangur) [inline lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php]: Such syntax only inherits method description, not type hints for parameters and return value.

See https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#61-making-inheritance-explicit-using-the-inheritdoc-tag

Please change implementation in such a way that we do not allow misuse of syntax with curly braces and only inherit return/param in case of `@inheritdoc`.

File: dev/tests/integration/testsuite/Magento/Quote/Model/QuoteTest.php [hunk 3]
```diff
@@ -393,7 +393,7 @@ protected function _getCustomerDataArray()
             \Magento\Customer\Model\Data\Customer::DOB => '2014-02-03 00:00:00',
             \Magento\Customer\Model\Data\Customer::EMAIL => 'qa@example.com',
             \Magento\Customer\Model\Data\Customer::FIRSTNAME => 'Joe',
-            \Magento\Customer\Model\Data\Customer::GENDER => 'Male',
+            \Magento\Customer\Model\Data\Customer::GENDER => 0,
```
Comment (orlangur) [inline dev/tests/integration/testsuite/Magento/Quote/Model/QuoteTest.php:396]: Why need this change?

**Review by orlangur — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php (hunk 1 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php]: To do not use `_files` word in the class namespace.

File: dev/tests/integration/testsuite/Magento/Quote/Model/QuoteTest.php (hunk 3 above)
Comment (YevSent) [reply dev/tests/integration/testsuite/Magento/Quote/Model/QuoteTest.php:396]: Fixed fixture implementation according to interface doc block annotation https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Customer/Api/Data/CustomerInterface.php#L269. After replacing `get_class` by namespace this fixture breaks test.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php (hunk 1 above)
Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php]: You don't need to use `_files` and do manual include. Just place fixtures in something like `lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest/Fixture/TSample.php`.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php (hunk 2 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php]: According to Magento internal guidelines, this annotation should look like `{@inheritdoc}`.

Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php]: Where do you see it? http://devdocs.magento.com/guides/v2.2/coding-standards/docblock-standard-general.html#inheritdoc is compliant with what I'm saying.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php (hunk 1 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php]: If you open integration or unit tests you will see all fixtures located in `_files` directory. I don't want to change such "standard".

Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/TypeProcessorTest.php]: There is no such standard. I remember such cases in integration tests just because there is no class usually.

When we can make our code `PSR-4` compliant we should do so. Please remove unnecessary `ClassLoader` complication, other `_files` occurrences containing PHP classes should be considered as technical debt.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php (hunk 2 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php]: From internal Magento wiki but I agree with `@inheritdoc` usage, even I think it's better to use it.
screenshot from 2017-10-19 15-38-51

Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/_files/TSample.php]: Great 👍 Yeah, seems to be some outdated documentation, please change/remove it or delegate this to whoever is in charge of it.

**Comment by YevSent** [comment]
The class complexity is 103 but Codacy configured complexity threshold is 50.

**Comment by orlangur** [comment]
@joni-jones I don't think we should any suppressions when `testCodeMess` is passed but Codacy complains.

**Comment by YevSent** [comment]
@orlangur, this class has 7 deprecated methods, which increase complexity, I can't them remove because it will be BIC. Magento class complexity configured as 100 (https://github.com/magento/magento2/blob/2.2-develop/dev/tests/static/testsuite/Magento/Test/Php/_files/phpmd/ruleset.xml#L24) but codacy complexity is 50. So without full refactoring, the codacy test for this class will never be green.

**Comment by orlangur** [comment]
@joni-jones do you mean green in Travis or green in Codacy? The latter is pretty odd, like forbidding  `else` usage, contains TooLongVariable rule which was intentionally removed from Magento PHPMD ruleset.

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php [hunk 4]
```diff
@@ -708,4 +695,58 @@ private function getNormalizedType($type)
...
+            /** @var ClassReflection $parentClassReflection */
+            foreach ($implemented as $parentClassReflection) {
+                if (!$parentClassReflection->hasMethod($methodName)) {
+                    continue;
+                }
+                $returnAnnotations = $this->getReturnFromDocBlock(
+                    $parentClassReflection->getMethod($methodName)
+                );
+
+                break;
```
Comment (orlangur) [inline lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Currently logic of this cycle is not so easy to understand. I suggest something like

```
foreach (...) {
    if ($parent...->hasMethod()) {
        $returnAnnotations = ...;
        break;
    }
}
```

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php [hunk 5]
```diff
@@ -708,4 +695,58 @@ private function getNormalizedType($type)
...
+     *
+     * @param MethodReflection $methodReflection
+     * @return ReturnTag
+     */
+    private function getReturnFromDocBlock(MethodReflection $methodReflection)
+    {
+        $methodDocBlock = $methodReflection->getDocBlock();
+        if (!$methodDocBlock) {
+            throw new \InvalidArgumentException(
+                "Each getter must have dock block. "
```
Comment (orlangur) [inline lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Typo dock -> doc. "have **a** doc block"?

**Comment by YevSent** [comment]
I mean green Codacy. Removing deprecated methods will decrease complexity, but the class also requires refactoring like the composition usage, unit tests. I think it should be done in some release but not in a patch release and not during this bug fix.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+    /**
+     * @inheritdoc
+     */
+    public function getPropertyName()
+    {
+        return '';
+    }
+
+    /**
+     * @inheritdoc
```
Comment (orlangur) [inline lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php:19]: Would be really nice to add test case with `{@inheritdoc}` to make it explicit such syntax is not supposed to work. I do not insist though, this PR is already excellent.

**Review by orlangur — CHANGES_REQUESTED** [review]

**Comment by orlangur** [comment]
@joni-jones ok, thanks. According to my understanding we should ignore invalid Codacy complaints but I'm not sure if we have a requirement to make it green (especially when "making green" is just adding suppression).

Please remove this suppression if it is not mandatory to make Codacy green.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php (hunk 6 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php:19]: I thought about it, but a lot of Magento code has such annotation. The current unit test covers such case for parsing return tag because the behavior just checks if a method has `@return` annotation.

**Comment by YevSent** [comment]
This suppress needed for Travis and Bamboo builds because the class has complexity 103, after small refactoring, without changing functionality I've got - 101. To reduce it need to remove deprecated methods and do deep refactoring.

**Comment by orlangur** [comment]
Aaah, ok. So green Bamboo actually, thanks. I'll raise a topic regarding Codacy in Slack, we should do something to it.

File: lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php (hunk 6 above)
Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php:19]: > a lot of Magento code has such annotation

We should fix it anyway. Not saying it must be a scope of this PR, but it could be.

Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/Test/Unit/Fixture/TSample.php:19]: Absolutely agree, even more, I think there should be a static test which won't allow adding this annotation.

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php (hunk 4 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Done

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php (hunk 5 above)
Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Done

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php (hunk 4 above)
Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Don't see it :(

Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Please, see a list of changed files, I amended commit.

Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Hm, I was answering to next thread actually O.o

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php (hunk 5 above)
Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: > +                "Each getter must have a dock block. "

I meant don't see this changed.

Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: https://github.com/magento/magento2/pull/11556/files#diff-292261de777138aa6bb4342b9757a3a5R744

Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: "dock" is correct spelling? I was not certain regarding "a" but "dock" seems to be not correct.

Comment (YevSent) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php]: Yes, sure. Fixed.

**Review by orlangur — APPROVED** [review]

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php [hunk 7]
```diff
@@ -708,4 +695,56 @@ private function getNormalizedType($type)
...
+     * @return ReturnTag
+     * @throws \InvalidArgumentException if doc block is empty or `@return` annotation doesn't exist
+     */
+    private function getMethodReturnAnnotation(MethodReflection $methodReflection)
+    {
+        $methodName = $methodReflection->getName();
+        $returnAnnotations = $this->getReturnFromDocBlock($methodReflection);
+        if (empty($returnAnnotations)) {
+            // method can inherit doc block from implemented interface, like for interceptors
+            $implemented = $methodReflection->getDeclaringClass()->getInterfaces();
```
Comment (VoidWalker) [inline lib/internal/Magento/Framework/Reflection/TypeProcessor.php:712]: Sir, you're missing docs from extended class here. $methodReflection->getDeclaringClass()->getParentClass() should be included in this array

**Review by VoidWalker — COMMENTED** [review]
Missing inheridocs from extended classes

File: lib/internal/Magento/Framework/Reflection/TypeProcessor.php (hunk 7 above)
Comment (orlangur) [reply lib/internal/Magento/Framework/Reflection/TypeProcessor.php:712]: Hi @VoidWalker, please report an issue using a template consisting of full steps to reproduce.
