### PR TITLE
Fix - Newrelic GraphQl transaction names not working

### LINKED ISSUE #36874: [Issue] Fix - Newrelic GraphQl transaction names not working
This issue is automatically created based on existing pull request: magento/magento2#36436: Fix - Newrelic GraphQl transaction names not working

---------
### Description (*)
Add transaction names to all new relic graphql transactions.

So many other transactions are properly named without having the `newrelicreporting/general/enable=1` flag set. 
- cron jobs             ( handled by [magento php level](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/NewRelicReporting/Plugin/StatPlugin.php#L62-L73), so long as the php extension is enabled )
- CLI commands   ( handled by [magento php level](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/NewRelicReporting/Plugin/CommandPlugin.php#L58-L60), so long as the php extension is enabled )
- controllers          ( [handled by new relic agent](https://docs.newrelic.com/docs/apm/agents/php-agent/frameworks-libraries/magento-specific-functionality/) )
- rest API               ( [handled by new relic agent](https://docs.newrelic.com/docs/apm/agents/php-agent/frameworks-libraries/magento-specific-functionality/))

Currently graphql works like this
- graphql   ( handled by magento php level, so long as the php extension is enabled, and the  magento extension is enabled with `newrelicreporting/general/enable=1` )

Having to enable this new relic reporting module to get GraphQL transaction names seems like a bit of an oversight. It is perfectly viable to have this setup

1.  install new relic in the `php.ini` level, new relic will auto detect that it is magento2
```ini
; Setting: newrelic.framework
; Type   : string
; Scope  : per-directory
; Default: empty (auto-detect framework)
; Info   : Disables automatic framework detection, telling the agent to
;          attempt to name transactions according to the specified framework.
;          Specifying "no_framework" will disable framework-related transaction
;          naming entirely. Please let us know at support.newrelic.com if you
;          encounter a failure with framework autodetection.
;
;          Must be one of the following values:
;          cakephp, codeigniter, drupal, drupal8, joomla, kohana, laravel,
;          magento, magento2, mediawiki, silex, slim, symfony1, symfony2,
;          wordpress, yii, zend, zend2, no_framework
;
;          Note that "drupal" covers only Drupal 6 and 7.
;
;newrelic.framework = ""
```

2. Do not enable the magento extension, set `newrelicreporting/general/enable=0`
4. Expect to see transaction names for graphql

What we actually see is 

```
/FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor
```

### Related Pull Requests
- https://github.com/magento/magento2/issues/36112
- https://github.com/magento/magento2/issues/30915

### Manual testing scenarios (*)
1. Configure new relic in your php.ini
2. Make a graphql request like `https://example.com/graphql?luker=3&query=%257Bproducts(filter%253A%257Bsku%253A%257%5B%25E2%2580%25A6%5DA%2522nonsuchsku%2522%257D%257D)%257Bitems%257Bname%2520sku%257D%257D%257D`
6. See `Graphql-products` in your new relic transactions list

Screenshot 2022-11-08 at 15 24 31

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by convenient**
### Description (*)
Add transaction names to all new relic graphql transactions.

So many other transactions are properly named without having the `newrelicreporting/general/enable=1` flag set. 
- cron jobs             ( handled by [magento php level](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/NewRelicReporting/Plugin/StatPlugin.php#L62-L73), so long as the php extension is enabled )
- CLI commands   ( handled by [magento php level](https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/NewRelicReporting/Plugin/CommandPlugin.php#L58-L60), so long as the php extension is enabled )
- controllers          ( [handled by new relic agent](https://docs.newrelic.com/docs/apm/agents/php-agent/frameworks-libraries/magento-specific-functionality/) )
- rest API               ( [handled by new relic agent](https://docs.newrelic.com/docs/apm/agents/php-agent/frameworks-libraries/magento-specific-functionality/))

Currently graphql works like this
- graphql   ( handled by magento php level, so long as the php extension is enabled, and the  magento extension is enabled with `newrelicreporting/general/enable=1` )

Having to enable this new relic reporting module to get GraphQL transaction names seems like a bit of an oversight. It is perfectly viable to have this setup

1.  install new relic in the `php.ini` level, new relic will auto detect that it is magento2
```ini
; Setting: newrelic.framework
; Type   : string
; Scope  : per-directory
; Default: empty (auto-detect framework)
; Info   : Disables automatic framework detection, telling the agent to
;          attempt to name transactions according to the specified framework.
;          Specifying "no_framework" will disable framework-related transaction
;          naming entirely. Please let us know at support.newrelic.com if you
;          encounter a failure with framework autodetection.
;
;          Must be one of the following values:
;          cakephp, codeigniter, drupal, drupal8, joomla, kohana, laravel,
;          magento, magento2, mediawiki, silex, slim, symfony1, symfony2,
;          wordpress, yii, zend, zend2, no_framework
;
;          Note that "drupal" covers only Drupal 6 and 7.
;
;newrelic.framework = ""
```

2. Do not enable the magento extension, set `newrelicreporting/general/enable=0`
4. Expect to see transaction names for graphql

What we actually see is 

```
/FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor
```

### Related Pull Requests
- https://github.com/magento/magento2/issues/36112
- https://github.com/magento/magento2/issues/30915

### Manual testing scenarios (*)
1. Configure new relic in your php.ini
2. Make a graphql request like `https://example.com/graphql?luker=3&query=%257Bproducts(filter%253A%257Bsku%253A%257%5B%25E2%2580%25A6%5DA%2522nonsuchsku%2522%257D%257D)%257Bitems%257Bname%2520sku%257D%257D%257D`
6. See `Graphql-products` in your new relic transactions list

Screenshot 2022-11-08 at 15 24 31

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#36874: Fix - Newrelic GraphQl transaction names not working

### CODE REVIEW

File: app/code/Magento/GraphQl/Model/Query/Logger/NewRelic.php [hunk 1]
```diff
@@ -41,10 +41,6 @@ public function __construct(
      */
     public function execute(array $queryDetails)
     {
-        if (!$this->config->isNewRelicEnabled()) {
```
Comment (audio-engineer) [inline app/code/Magento/GraphQl/Model/Query/Logger/NewRelic.php:44]: @convenient Now you are basically allowing GraphQL logs to be written to New Relic, EVEN if New Relic is disabled in the admin panel. How does that make sense? In a regular scenario, if someone wants to use New Relic, they will enable it in the admin panel as well.

And even if you want to remove code, make sure to remove it properly, i.e. remove the injected dependency as well [here](https://github.com/magento/magento2/blob/381f5d111c8680f3ab22635e05c1a6bc792dbdff/app/code/Magento/GraphQl/Model/Query/Logger/NewRelic.php#L32).

Comment (convenient) [reply app/code/Magento/GraphQl/Model/Query/Logger/NewRelic.php:44]: Many hosts and systems plug new relic in as a standard PHP app and never configure it within the admin panel.

On those systems you get transaction naming, some from new relic framework detection, some from magento.

Here is an example of where Magento sets the transaction name without checking if the admin panel flag is set
https://github.com/magento/magento2/blob/28c7f79f4d74564ba880e35e59ea45b896437ca7/app/code/Magento/NewRelicReporting/Plugin/CommandPlugin.php#L56-L60

this is because the inner of that function checks if the extension is enabled, which is all that is necessary to set a transaction name

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
And the tests themselves seem flaky so it's hard to see what is really an issue.

> FWIW i'm seeing the same failed unit tests/functional tests on https://github.com/magento/magento2/pull/36436
>
> My pr - https://github.com/magento/magento2/runs/9367143258
> Your pr - https://github.com/magento/magento2/runs/9367569793
> 
> ```
> DEPRECATION: Test StorefrontInvoiceFilterTest is missing required annotations.> {"testName":"StorefrontInvoiceFilterTest","missingAnnotations":"stories, title, description, severity"}
> ```
> 
> It's hard to tell whats actually real when the actual tests seem to be flaking 🤔 

Also seeing similar unit test failures and functional b2b test failures

Rather than chasing a green build at this point I really have to wait for the magento tests baseline to be verified working.

**Comment by convenient** [comment]
@audio-engineer anyone magento side aware that the tests are failing for unrelated things? see above comment.

**Comment by convenient** [comment]
@magento run WebAPI Tests

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run Integration Tests, Functional Tests EE

**Comment by convenient** [comment]
@magento run all tests

**Comment by convenient** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by convenient** [comment]
https://github.com/magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by convenient** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by convenient** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by convenient** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by convenient** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by convenient** [comment]
@magento run Functional Tests CE

**Comment by convenient** [comment]
@magento run Functional Tests CE

**Comment by convenient** [comment]
@magento run Functional Tests CE

**Comment by convenient** [comment]
@magento run Functional Tests CE

**Comment by convenient** [comment]
@magento run Functional Tests CE

**Comment by convenient** [comment]
The flaky tests have finally gone green.

@audio-engineer you have self assigned yourself as reviewer, do you need to review further? the description has been updated to be more clear how the current functionality does not match the rest of the transaction naming.

**Comment by audio-engineer** [comment]
@convenient I will take a look tomorrow

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-November** [comment]
Verified the issue on Magento 2.4-develop instance with and without PR changes applied and the issue is still reproducible after applying PR changes.
Observation before applying PR changes:
Graphql Transaction name is displayed as : /FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor
image
Observation after applying PR changes,
No Graphql transaction names are displayed even after performing multiple graphql operations. Transaction name displayed as Unknown:
image

**Review by engcom-November — CHANGES_REQUESTED** [review]
Verified the issue on Magento 2.4-develop instance with and without PR changes applied and the issue is still reproducible after applying PR changes.
Observation before applying PR changes:
Graphql Transaction name is displayed as : /FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor
Observation after applying PR changes:
No Graphql transaction names are displayed even after performing multiple graphql operations. Transaction name displayed as Unknown.
Please refer the [comment](https://github.com/magento/magento2/pull/36436#issuecomment-1434573559)

**Comment by engcom-November** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **2.4-develop** and **PHP 8.1**

**Manual testing scenario:**
1. Installed New Relic Agent server
2. Disabled New Relic from Magento - Stores - Configuration - General - New Relic Reporting.
3. Performed Graphql operations.

**Before:** :heavy_multiplication_x: 
GraphQL Transaction names are displayed as /FrontController/Magento\GraphQl\Controller\GraphQl\Interceptor before PR changes
image


**After:** :heavy_check_mark:
After applying PR changes and changing the transaction type drop down to "All", GraphQL transaction names are getting displayed as expected.
image

**Additionally tested:**
Enabled New Relic from Magento - Stores - Configuration - General - New Relic reporting and verified Graphql transaction names in New Relic account. Graphql Transaction names are getting displayed as expected.

**Comment by convenient** [comment]
Thanks @engcom-November thats perfect looking, i see `GraphQL-customerCart` etc in your screenshot

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR from Merge in Progress to Changes Requested on assignment, hence moving it back.

Thank you!
