### PR TITLE
Fix issue  #30270 Product Reviews can not be sorted by Admin on the Product edit page

### LINKED ISSUE #30270: “Product Reviews” can not be sorted by Admin on the Product page
**Preconditions**:
* Magento EE 2.3.5-p2, EE 2.4.0, EE 2.4.1, EE 2.4.2-alpha1 is installed, should be actual for CE
* A Simple Product is created

**Steps to Reproduce:**
* Go to the Storefront as a guest
* Go to the created Product page
* Add at least 2 reviews
* Go to Magento Admin > Marketing > Pending Reviews
* Approve the added reviews
* Go to Magento Admin > Ctalog > Products
* Select the created Product
* Click the “Edit” link
* Open the “Product Reviews” section
* Sort “Product Reviews” for example, by ID, clicking the “ID” cell

**(/) Expected results:**

All records of “Product Reviews” grid should be sorted by selected parameter

**(x) Actual results:**

Records of “Product Reviews” grid are not sorted

### PR DESCRIPTION
**Pull request by Chandresh22**
### Description (*)

Product Reviews can not be sorted by Admin on the Product edit page so that resolve this  issue.
after changes code Records of "Product Reviews" grid are sorted.

### Fixed Issues (if relevant)

1. Create a few reviews for the product
2. Create an object of ReviewDataProvider with request param with some sorting order and current_product_id
3. Assert that sorting order will be applied for review items by calling
   Review/Ui/DataProvider/Product/ReviewDataProvider::getData()

   Fixes magento/magento2#30270  Product Reviews can not be sorted by Admin on the Product Edit page

### Manual testing scenarios (*)

1. "Steps to reproduce" from the #30270  Product Reviews can not be sorted by Admin on the Product Edit page

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @Chandresh22, thank you for your contribution. However, due to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html#automated-tests) the changes should be covered by tests. Could you please cover your fix by a [MFTF](https://devdocs.magento.com/mftf/docs/introduction.html) test, that will pass through all the steps and then assert that the grid sorting works?

Thank you.

**Comment by Chandresh22** [comment]
@eduard13 can you help me what is mean Auto Test not covered? and how to resolve this thanks.

**Comment by eduard13** [comment]
@Chandresh22 as mentioned in my previous comment, in order to deliver this fix, it should be covered by automated tests. I suggest adding a simple MFTF test, that will make sure that the grid sorting works as expected. 
Also could you additionally check and fix the failing Static Tests, they aren’t related to your changes, however would be great to have all the checks green ✅

**Comment by Chandresh22** [comment]
@magento run Static Tests

**Comment by Chandresh22** [comment]
@magento run all tests

**Comment by Chandresh22** [comment]
@magento run all tests

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php [hunk 1]
```diff
@@ -58,14 +58,22 @@ public function __construct(
...
      * @since 100.1.0
      */
     public function getData()
     {
         $this->getCollection()->addEntityFilter($this->request->getParam('current_product_id', 0))
             ->addStoreData();
 
+        $params = $this->request->getParams();
+        if (isset($params['sorting'])) {
+            $sorting = $this->request->getParam('sorting');
```
Comment (eduard13) [inline app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]: Please check a more simplified version that should also work.

```suggestion
        if ($sorting = $this->request->getParam('sorting', null)) {
```

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php [hunk 2]
```diff
@@ -79,7 +87,8 @@ public function getData()
     }
 
     /**
-     * {@inheritdoc}
+     * @inheritdoc
+     * @return mixed
```
Comment (eduard13) [inline app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]: As far as I can see it doesn't return anything. Am I missing something? This change should fix the Static Tests and Semantic Version Checker.

```suggestion
     * @return void
```

**Review by eduard13 — CHANGES_REQUESTED** [review]
Please check my comments below. Additionally, as far there is already a [Unit Test](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Review/Test/Unit/Ui/DataProvider/Product/ReviewDataProviderTest.php) that covers this class, please update accordingly your test cases.

Thanks.

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php (hunk 2 above)
Comment (Chandresh22) [reply app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]: @eduard13  thanks for suggestion

**Comment by Chandresh22** [comment]
@magento run all tests

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php (hunk 2 above)
Comment (Chandresh22) [reply app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]: @eduard13  check the screenshot it shows error  http://prntscr.com/uz4ukj
but i don't change in it. this function has as it is.

**Comment by eduard13** [comment]
@magento run Static Tests, Semantic Version Checker

**Comment by eduard13** [comment]
@Chandresh22 please fix the rest of static fails, and adjust the Unit Test that is currently failing.
Then could you please squash your commits into one and force push it? Looks like something went wrong with the build, it doesn't see the latest updates.

**Comment by Chandresh22** [comment]
okay @eduard13  i will check

**Comment by Chandresh22** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Static Tests, Unit Tests, Semantic Version Checker.

@Chandresh22 any reasons of why have you reverted the changes I suggested? Also have you had any problems with [squashing](https://www.internalpointers.com/post/squash-commits-into-one-git) the commits into one commit, in order to have a clean history? 
Moreover, there is a failing [Unit Test](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Review/Test/Unit/Ui/DataProvider/Product/ReviewDataProviderTest.php) that you have to adjust including your changes.

Let me know if you have any questions on my feedback.
Thanks.

**Comment by Chandresh22** [comment]
@magento run Static Tests, Unit Tests

**Comment by Chandresh22** [comment]
@magento run Database Compare, Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, Magento Health Index, Sample Data Tests CE, Sample Data Tests EE, Sample Data, Tests B2B, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Chandresh22** [comment]
@magento run all tests

**Comment by Chandresh22** [comment]
> @magento run Static Tests, Unit Tests, Semantic Version Checker.
> 
> @Chandresh22 any reasons of why have you reverted the changes I suggested? Also have you had any problems with [squashing](https://www.internalpointers.com/post/squash-commits-into-one-git) the commits into one commit, in order to have a clean history?
> Moreover, there is a failing [Unit Test](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Review/Test/Unit/Ui/DataProvider/Product/ReviewDataProviderTest.php) that you have to adjust including your changes.
> 
> Let me know if you have any questions on my feedback.
> Thanks.

@eduard13  sorry but i have no idea about squashing the commits
can i have create new branch for this so you can also change the code?

**Comment by engcom-Charlie** [comment]
@Chandresh22 I made squash. Hope I helped you.

**Comment by eduard13** [comment]
@magento run Static Tests, Unit Tests

**Comment by Chandresh22** [comment]
> @Chandresh22 I made squash. Hope I helped you.

okay thank you @engcom-Charlie

**Comment by engcom-Charlie** [comment]
@Chandresh22 could you please fix `Static Tests` failures?
Thank you.

**Comment by engcom-Charlie** [comment]
@Chandresh22 I will take care of test coverage.

**Comment by Chandresh22** [comment]
> @Chandresh22 could you please fix `Static Tests` failures and cover your changes by some kind of autotetest?
> Thank you.

@engcom-Charlie  i will try to fix Static Tests but it give error in function addFilter() which i never touch or edited this function
   it give error like  

PHPStan detected violation(s):
 ------ ------------------------------------------------------------------------ 
  Line   app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php  
 ------ ------------------------------------------------------------------------ 
  109    Method                                                                  
         Magento\Review\Ui\DataProvider\Product\ReviewDataProvider::addFilter(   
         ) should return mixed but return statement is missing.                  
 ------ ------------------------------------------------------------------------ 

 [ERROR] Found 1 error                                                          

Failed asserting that 1 matches expected 0. 

when i declare or add return type to this function than Static Tests fix but Functional Tests CE or Semantic Version Checker error for  change return type. any suggestion?

**Comment by engcom-Charlie** [comment]
@Chandresh22 if you change something in the file then the file will be checked fully by **Static Tests** and **SVC**.
About your question, need to fix **Static Tests** failures, **SVC** error will be reviewed further.
Will you cover changes by automated tests?
Thank you.

**Comment by Chandresh22** [comment]
> @Chandresh22 if you change something in the file then the file will be checked fully by **Static Tests** and **SVC**.
> About your question, need to fix **Static Tests** failures, **SVC** error will be reviewed further.
> Will you cover changes by automated tests?
> Thank you.

@engcom-Charlie  no i haven't cover automated tests.
will you please let me know how to do automated tests?

**Comment by engcom-Charlie** [comment]
@Chandresh22 I believe you can cover the scenario by integration test.

1. Create a few reviews for the product
2. Create an object of ReviewDataProvider with `request` param with some sorting order and `current_product_id`
3. Assert that sorting order will be applied for review items by calling 

> Review/Ui/DataProvider/Product/ReviewDataProvider::getData()

Please let me know if you have an additional questions.

**Comment by engcom-Charlie** [comment]
@Chandresh22 do you have any updates about test coverage?
Thank you.

**Comment by Chandresh22** [comment]
> @Chandresh22 I believe you can cover the scenario by integration test.
> 
> 1. Create a few reviews for the product
> 2. Create an object of ReviewDataProvider with `request` param with some sorting order and `current_product_id`
> 3. Assert that sorting order will be applied for review items by calling
> 
> > Review/Ui/DataProvider/Product/ReviewDataProvider::getData()
> 
> Please let me know if you have an additional questions.

i had created few review for the product and apply sorting order with current_product_id and sorting had
works fine.

**Comment by Chandresh22** [comment]
> @Chandresh22 do you have any updates about test coverage?
> Thank you.

@engcom-Charlie
no update i haven't idea how to fix the static test. are you have any idea? how to fix addFilter(..) return type issue.

**Comment by engcom-Charlie** [comment]
@Chandresh22 I'll take care of the Static Test issue. Could you please provide test coverage?
Thank you.

**Comment by Chandresh22** [comment]
> @Chandresh22 I'll take care of the Static Test issue. Could you please provide test coverage?
> Thank you.

@engcom-Charlie  what does it mean test coverage ?? i had already provided manually testing scenarios

**Comment by engcom-Charlie** [comment]
@Chandresh22 due to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html) the changes should be covered by tests. Could you please cover your fix by an automated test as I wrote https://github.com/magento/magento2/pull/30477#issuecomment-718744960? 
Thank you.

**Comment by Chandresh22** [comment]
@magento run Static Tests

**Comment by Chandresh22** [comment]
> @Chandresh22 due to [Magento Definition of Done](https://devdocs.magento.com/contributor-guide/contributing_dod.html) the changes should be covered by tests. Could you please cover your fix by an automated test as I wrote [#30477 (comment)](https://github.com/magento/magento2/pull/30477#issuecomment-718744960)?
> Thank you.

@engcom-Charlie thank you for helping i had added your comment in Fixed Issues sections is it right?

**Comment by engcom-Charlie** [comment]
@Chandresh22 please cover your changes by integration test by this scenario https://github.com/magento/magento2/pull/30477#issuecomment-718744960 to prevent this issue in future.
Thank you.

**Comment by Chandresh22** [comment]
@magento run Static Tests

**Comment by Chandresh22** [comment]
hello @engcom-Charlie  Static Test failed in Static tests for B2B so it pass with CE & EE right, so can i submit the code only for the CE & EE version because i haven't B2B version of magento and also it magento default/core function related issue so i think it magento related issue.

**Comment by engcom-Charlie** [comment]
@Chandresh22 please cover your changes by integration test and add return type to `Magento\Review\Ui\DataProvider\Product\ReviewDataProvider::addFilter`. No worries about SVC failures.
Thank you.

**Comment by Chandresh22** [comment]
@magento run Unit Tests, Static Tests

**Comment by Chandresh22** [comment]
@magento run Integration Tests

**Comment by Chandresh22** [comment]
@magento run Integration Tests

**Comment by Chandresh22** [comment]
@magento run WebAPI Tests, Sample Data Tests CE, Sample Data Tests EE, Magento Health Index

**Comment by Chandresh22** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by Chandresh22** [comment]
hello @engcom-Charlie  it pass with integration test but in Functional Tests EE it gives error like MC-14686: Storefront Delete Simple Product From Mini Shopping Cart Test

http://prntscr.com/vd5bcx

**Comment by Chandresh22** [comment]
@magento run Functional Tests B2B, Sample Data Tests B2B

**Comment by eduard13** [comment]
H i@Chandresh22, looks like you didn't get it right. You have to write a simple Integration Test (or any other) that covers the fix that you provided. The main purpose of the test coverage, is that we'll avoid breaking the sorting for this grid in the future.

Hope that makes sense. 
Here you can find some useful info on how to run any kind of tests:
https://devdocs.magento.com/guides/v2.4/test/testing.html

Thank you.

**Comment by engcom-Charlie** [comment]
@Chandresh22 please update your PR accordingly to https://github.com/magento/magento2/pull/30477#issuecomment-721607253. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@Chandresh22 I'll continue with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php [hunk 3]
```diff
@@ -79,10 +81,25 @@ public function getData()
...
+     * Apply sorting if it set
+     *
+     * @return void
+     */
+    private function applySorting(): void
+    {
+        $sorting = $this->request->getParam('sorting');
+        if (is_array($sorting)) {
+            $select = $this->getCollection()->getSelect();
+            $select->order($sorting['field'] . ' ' . $sorting['direction']);
```
Comment (gabrieldagama) [inline app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]:
```suggestion
            $this->getCollection()->setOrder($sorting['field'], $sorting['direction']);
```
Apparently, there are some edge cases, it seems better to use the collection provided method than adding it directly to the select.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie,

Can you have a look at my small comment below? Thanks!

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php [hunk 4]
```diff
@@ -79,24 +79,43 @@ public function getData()
...
+    {
+        $this->getCollection()->setOrder($this->getPreparedField($field), $direction);
+    }
+
+    /**
+     * @inheritdoc
+     * @since 100.1.0
+     * @return void
+     */
+    public function addFilter(Filter $filter): void
```
Comment (gabrieldagama) [inline app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]: Since this is an `@api`, and it is extending a class that implements `DataProviderInterface`, for keeping backward compatibility, I believe we should leave the function signature as it is on the interface.

File: app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php [hunk 5]
```diff
@@ -79,24 +79,43 @@ public function getData()
...
+        return $preparedName ?: $name;
+    }
 
-        if ($field === 'review_created_at') {
-            $filter->setField('rt.created_at');
-        }
+    /**
+     * @inheritDoc
+     */
+    public function addOrder($field, $direction): void
```
Comment (gabrieldagama) [inline app/code/Magento/Review/Ui/DataProvider/Product/ReviewDataProvider.php]: Since this is an `@api`, and it is extending a class that implements `DataProviderInterface`, for keeping backward compatibility, I believe we should leave the function signature as it is on the interface.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, thanks for updating this PR.

Can you have a look at my comments below?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by Chandresh22** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by Chandresh22** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by Chandresh22** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8501](https://jira.corp.magento.com/browse/ENGCOM-8501) has been created to process this Pull Request

**Review by eduard13 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8501](https://jira.corp.magento.com/browse/ENGCOM-8501) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to the Storefront as a guest
2. Go to the created Product page
3. Add at least 2 reviews
4. Go to Magento Admin > Marketing > Pending Reviews
5. Approve the added reviews
6. Go to Magento Admin > Ctalog > Products
7. Select the created Product
8. Click on the “Edit” link
9. Open the “Product Reviews” section
10. Sort “Product Reviews” for example, by ID, click the “ID” cell

**Before:** :heavy_multiplication_x: Records of “Product Reviews” grid are not sorted

Peek 2020-12-01 15-50

**After:** :heavy_check_mark: All records of “Product Reviews” were sorted by selected parameter

Peek 2020-12-01 16-11

 :heavy_check_mark: Also was checked Filters functionality and everything works as expected.
Peek 2020-12-01 16-31
