### PR TITLE
Fixed Unable to apply data patch issue after upgrade in 2.4 #29365

### LINKED ISSUE #29365: Magento 2.4 Upgrade issue Unable to apply data patch Magento\CatalogUrlRewrite\Setup\Patch\Data\UpdateUrlKeyForProducts
<!---
Please review our guidelines before adding a new issue: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fields marked with (*) are required. Please don't remove the template.
-->

### Preconditions (*)
<!---
Provide the exact Magento version (example: 2.4.0) and any important information on the environment where bug is reproducible.
-->
1. Magento 2.4.0
2. Magento 2.4-develop

### Steps to reproduce (*)
<!---
Important: Provide a set of clear steps to reproduce this bug. We can not provide support without clear instructions on how to reproduce.
-->
1. Composer upgrade from 2.3.4 to 2.4.0
2. php bin/magento setup:upgrade

### Expected result (*)
<!--- Tell us what do you expect to happen. -->
1. Successful upgrade 

### Actual result (*)
<!--- Tell us what happened instead. Include error messages and issues. -->
```shell
Module 'Magento_EavGraphQl':                                                                                                                                                                                                                  
Module 'Magento_Cms':                                                                                                                                                                                                                         
Module 'Magento_CatalogImportExport':                                                                                                                                                                                                         
Module 'Magento_Catalog':                                                                                                                                                                                                                     
Module 'Magento_CatalogInventory':                                                                                                                                                                                                            
Module 'Magento_Rule':                                                                                                                                                                                                                        
Module 'Magento_Payment':                                                                                                                                                                                                                     
Module 'Magento_CatalogRuleGraphQl':                                                                                                                                                                                                          
Module 'Magento_CatalogRule':                                                                                                                                                                                                                 
Module 'Magento_CatalogUrlRewrite':                                                                                                                                                                                                           
Unable to apply data patch Magento\CatalogUrlRewrite\Setup\Patch\Data\UpdateUrlKeyForProducts for module Magento_CatalogUrlRewrite. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a c
hild row: a foreign key constraint fails (`m24`.`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE CA), q
uery was: INSERT  INTO `catalog_product_entity_varchar` (`value_id`,`value`) VALUES (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?
, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), 
(?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)
, (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, 
?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?
, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), 
(?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)
, (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, 
?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?
, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), 
(?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)
, (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, 
?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?
, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), 
(?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?)
, (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, 
?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?
, ?), (?, ?), (?, ?), (?, ?), (?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)                                                                                                                                                        
```
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #29805: Magento 2.4 upgrade fails if there is data under catalog_product_entity_varchar
### Preconditions (*)

1. Upgrading from version 2.3.5 into Version 2.4.0
2. The bug is in the upgrade script (php bin/magento setup:upgrade) throwing the error (see below)

### Steps to reproduce (*)

1. Install Magento 2.3.5 v2.3.5 first. 
2. Have items already in your catalog_product_entity_varchar table (i.e. add some product attributes TEXT)
3. Upgrade into Magento 2.4.0
4. The upgrade would fail.

### Expected result (*)

1. Upgrade should work/finish successfully. 
2. Values in the database should be UPDATED not re-INSERTED with the insertOnDuplicate function, that is causing the error. 

### Actual result (*)

1. Upgrade Fail with the following error:

Module 'Magento_CatalogUrlRewrite':
Unable to apply data patch Magento\CatalogUrlRewrite\Setup\Patch\Data\UpdateUrlKeyForProducts for module Magento_CatalogUrlRewrite. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`gotravelv2`.`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE), query was: INSERT  INTO `catalog_product_entity_varchar` (`value_id`,`value`) VALUES (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?), (?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ X ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

This upgrade will always fail on a product that has data in it already, 

I will post another update now to show the solution,.

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

Fixed Unable to apply data patch issue #29365
### Fixed Issues (if relevant)

1. Fixes magento/magento2#29365
2. Fixes https://github.com/magento/magento2/issues/29805

### Manual testing scenarios (*)

1. Composer upgrade from 2.3.5-p1 to 2.4.0
2. php bin/magento setup:upgrade

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Setup/Patch/Data/UpdateUrlKeyForProducts.php [hunk 1]
```diff
@@ -58,7 +58,7 @@ public function apply()
         $table = $this->moduleDataSetup->getTable('catalog_product_entity_varchar');
         $select = $this->moduleDataSetup->getConnection()->select()->from(
             $table,
-            ['value_id', 'value']
+            ['entity_id', 'attribute_id', 'store_id', 'value_id', 'value']
```
Comment (ihor-sviziev) [inline app/code/Magento/CatalogUrlRewrite/Setup/Patch/Data/UpdateUrlKeyForProducts.php]: Hi @ravi-chandra3197,
From the https://github.com/magento/magento2/issues/29365#issuecomment-674852010 - this will not work with Magento Commerce.
I just looked to the sample - here is good example how to detect link field for products:

https://github.com/magento/magento2/blob/f70fef1df9c04e77466977747e7ec62264f2a2f2/setup/src/Magento/Setup/Fixtures/ImagesFixture.php#L310-L315

https://github.com/magento/magento2/blob/f70fef1df9c04e77466977747e7ec62264f2a2f2/setup/src/Magento/Setup/Fixtures/ImagesFixture.php#L532-L543

Could you update your PR accordingly?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8145](https://jira.corp.magento.com/browse/ENGCOM-8145) has been created to process this Pull Request

**Comment by DiegoSana** [comment]
May be just removing the line "['value if', 'value']" is enough. The default value for that param is "*". So it's the same result that including all the fields. And it works for community and commerce edition.

**Comment by ihor-sviziev** [comment]
@ravi-chandra3197 @DiegoSana could you provide more details how to reproduce the issue on the empty magento installation? We tried multiple options, but the issue isn’t reproducing. Maybe you could point what are pre requisites should be?

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197 .

Unfortunately, we are not able to reproduce these issues #29365, #29805.

**Manual testing scenario:**

1. Install Magento 2.3.4 version with Sample Data;
2. Upgrade to 2.4.0 version;

**Actual Result:** :heavy_check_mark: The patch was applied and the upgrade was successful

It has also been tested on different types of products, with the same url key values, with the addition of additional attributes, and many other options and everything works as expected.

@ravi-chandra3197 Could you provide more details that would help reproduce this problem?
Thanks!

**Comment by ravi-chandra3197** [comment]
Hello @engcom-Alfa @ihor-sviziev 
we are getting below error during the upgrade from Magento 2.3.5-p1 to Magento 2.4.0

Unable to apply data patch Magento\CatalogUrlRewrite\Setup\Patch\Data\UpdateUrlKeyForProducts for module Magento_CatalogUrlRewrite. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`enti), query was: INSERT  INTO `catalog_product_entity_varchar` (`value_id`,`value`) VALUES (?, ?),

**Comment by ihor-sviziev** [comment]
@ravi-chandra3197 the error is clear, but not clear how we can reproduce this issue on clean magento installation

**Comment by DiegoSana** [comment]
@ihor-sviziev finaly, in my case, i needed two steps to by pass this problem. Im upgrading form Magento 2.2.5 to Magento 2.4 commerce edition.

The steps are:

1 - remove the line "['value_id', 'value']" on Magento\CatalogUrlRewrite\Setup\Patch\Data\UpdateUrlKeyForProducts
2 - Clean the table. I noted that i have items that no exists on the catalog_product_entity table referenced by row_id. I dont jnow how.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Seems like some extension broke foreign keys, that's why this issue appeared.
> i have items that no exists on the catalog_product_entity table referenced by row_id

@ravi-chandra3197 In this case I'm not really sure changes from this PR will fix the issue, seems like we need to add inner join to catalog_product_entity table in order to resolve it.

Could you update your solution accordingly?

**Comment by DiegoSana** [comment]
> Seems like some extension broke foreign keys, that's why this issue appeared.
> 
> > i have items that no exists on the catalog_product_entity table referenced by row_id
> 
> In this case I'm not really sure changes from this PR will fix the issue, seems like we need to add inner join to catalog_product_entity table in order to resolve it.
> 
> Could you update your solution accordingly?

I've solved it doing this: 

Step 1: remove non asociated rows from catalog_product_entity_varchar table 
Step 2: Remove the line 61 from vendor/magento/module-catalog-url-rewrite/Setup/Patch/Data/UpdateUrlKeyForProducts.php (its the line with this code > "['value_id', 'value']")

**Review by ihor-sviziev — APPROVED** [review]
@engcom-Alfa,
according to comments https://github.com/magento/magento2/issues/29365#issuecomment-694178643 and https://github.com/magento/magento2/issues/29365#issuecomment-694197868 - seems like before migration to 2.4.0 in tables `catalog_product_entity_varchar` were records to product that not exists in `catalog_product_entity`. 
That was potentially caused by some issue in the data-migration-tool during migration from M1 or some custom extension.

Could you double check this case?

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8145](https://jira.corp.magento.com/browse/ENGCOM-8145) has been created to process this Pull Request

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @ravi-chandra3197,
Seems like this issue was already fixed in https://github.com/magento/magento2/commit/dd151d11f4d709abb91b82a5d4360aae651c20e3.

Could you confirm that?

**Comment by ihor-sviziev** [comment]
Hi @ravi-chandra3197,
Will you be able to confirm / not confirm that issue was already solved?

**Comment by ihor-sviziev** [comment]
Hi @ravi-chandra3197,
Unfortunately we weren't able to reproduce this issue on 2.4-develop branch original issue was also closed due to that reason - I'm closing this PR as not relevant.

If the issue still reproducing for you - please add additional information here or in the issue.

**Comment by ihor-sviziev** [comment]
Re-opening this PR as the issue was also re-opened.

**Comment by ravi-chandra3197** [comment]
Hello @ihor-sviziev 
I am still able to reproduce the same issue I have checked with the below case
upgrade from Magento 2.3.3 to Magento 2.4.0 - same error
upgrade from Magento 2.3.5-p1 to Magento 2.4.0 (tested in multi-web, multi-store) - same error
upgrade from Magento 2.3.1 to Magento 2.4.1 - same error
using my PR solution it's working fine

could you please review it and provide you input for the same

Thank you

**Comment by ihor-sviziev** [comment]
@ravi-chandra3197 Unfortunately we still weren't able to reproduce this issue.
Were you able to reproduce this issue on clean magento installation?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
We had few confirmations that this PR fixes the original issue, so I'm approving this PR again.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8403](https://jira.corp.magento.com/browse/ENGCOM-8403) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@engcom-Alfa any news on testing this PR? Were you able to reproduce the issue?

**Comment by webhive** [comment]
I can confirm this patch work well.
I had the same issues what was fixed in this patch, upgrading 2.3.6 to 2.4.0 or 2.4.1.
After this patch has been applied migration completed without any issues

**Comment by ihor-sviziev** [comment]
@engcom-Alfa @engcom-Bravo @engcom-Charlie, do you have any updates about the testing of this PR?

**Comment by ihor-sviziev** [comment]
From Slack with @engcom-Alfa - he was able to reproduce this issue locally, but unfortunately, he didn't find exact steps to reproduce it.
@engcom-Alfa do you have any updates about that?

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create several store views - en & de & fr;
2. Enable showing store code in the URL
3. Configure different URL keys for categories and for products for the DE & EN & FR versions;
4. Also were added different product attributes and other different combinations
As result, we had several records by request:
```
mysql> SELECT COUNT(*)
    -> FROM catalog_product_entity_varchar cpev
    -> LEFT JOIN catalog_product_entity cpe on cpev.entity_id = cpe.entity_id
    -> WHERE cpe.entity_id IS NULL;
```
image

5. Try to upgrade;

**Before:** :x: Upgrade Fail with the following error:

`
Unable to apply data patch Magento\CatalogUrlRewrite\Setup\Patch\Data\UpdateUrlKeyForProducts for module Magento_CatalogUrlRewrite. Original exception message: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento24`.`catalog_product_entity_varchar`, CONSTRAINT `CAT_PRD_ENTT_VCHR_ENTT_ID_CAT_PRD_ENTT_ENTT_ID` FOREIGN KEY (`entity_id`) REFERENCES `catalog_product_entity` (`entity_id`) ON DELETE), query was: INSERT  INTO `catalog_product_entity_varchar` (`value_id`,`value`) VALUES (?, ?), (?, ?),....(?, ?) ON DUPLICATE KEY UPDATE `value` = VALUES(`value`)
`

**After:** :heavy_check_mark: Upgrade finished successfully.

Also was tested general functionality and everything works as previously (expected)
