### PR TITLE
Get existing page data only on edit page

### LINKED ISSUE #39743: "The CMS page with the "0" ID doesn't exist" log flood
### Preconditions and environment

- Magento version: 2.4.5-p11, 2.4.6-p9

### Steps to reproduce

1. Create admin user
2. Open BO->Content->Pages->Add New Page

### Expected result

- `system.log` is empty

### Actual result

- `system.log` contains `main.ERROR: The CMS page with the "0" ID doesn't exist. [] []`

### Additional information

see `\Magento\Cms\Model\Page\DataProvider::getMeta`

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Mohamed-Asar**
### Description (*)

Get Page data only on the edit page

### Fixed Issues (if relevant)

1. Fixes #39743 

### Manual testing scenarios (*)

1. Log into admin
2. Navigate to Content->Pages->Add New Page
3. Verify System.log don't have any error log related to cms page

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Mohamed-Asar,

Thanks for the contribution!

The changes seems good to us, but please fixed the failed static test.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @Mohamed-Asar,

To proceed further with the PR, we need a green build, and for this you need to fix the static test failure. Please let us know if you have any query regarding that.

Thanks

**Comment by Mohamed-Asar** [comment]
Sure @engcom-Hotel, Looks like we need to refactor the class, i will fix and let you know

**Comment by engcom-Hotel** [comment]
Hello @Mohamed-Asar,

Have you got a chance to look into this?

Thanks

**Comment by Mohamed-Asar** [comment]
@engcom-Hotel  i have started working on it, will let you know once done

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Page/Service/PageService.php [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+{
+    /**
+     * @param PageRepositoryInterface $pageRepository
+     * @param PageFactory $pageFactory
+     * @param CustomLayoutManagerInterface $customLayoutManager
+     */
+    public function __construct(
+        private PageRepositoryInterface $pageRepository,
+        private PageFactory $pageFactory,
+        private CustomLayoutManagerInterface $customLayoutManager,
```
Comment (engcom-Hotel) [inline app/code/Magento/Cms/Model/Page/Service/PageService.php]: I guess all properties can be readonly.

File: app/code/Magento/Cms/Model/Page/Service/PageService.php [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+use Magento\Cms\Api\Data\PageInterface;
+use Magento\Cms\Api\PageRepositoryInterface;
+use Magento\Cms\Model\Page\CustomLayoutManagerInterface;
+use Magento\Cms\Model\PageFactory;
+use Magento\Framework\Exception\LocalizedException;
+
+/**
+ * Cms Page Service Class
+ */
+class PageService
```
Comment (engcom-Hotel) [inline app/code/Magento/Cms/Model/Page/Service/PageService.php:18]: - PageService can be unit tested for the logic of getPageById, createPageFactory, and fetchAvailableCustomLayouts. 
- Integration tests could ensure data provider works as expected in edit page scenarios.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Mohamed-Asar,

Thanks for the updates!

The changes looks good to us, but some minor changes required as below. Please look into the review comments.

Thanks

File: app/code/Magento/Cms/Model/Page/Service/PageService.php (hunk 1 above)
Comment (Mohamed-Asar) [reply app/code/Magento/Cms/Model/Page/Service/PageService.php]: @engcom-Hotel added readonly

File: app/code/Magento/Cms/Model/Page/Service/PageService.php (hunk 2 above)
Comment (Mohamed-Asar) [reply app/code/Magento/Cms/Model/Page/Service/PageService.php:18]: @engcom-Hotel i have added unit test case, please review

**Comment by Mohamed-Asar** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE
