### PR TITLE
FIX Perfomance Issue for Backend EDIT of CMS #30936

### LINKED ISSUE #30936: Perfomance:Cms/Model/Page/DataProvider.php#L103 loads full collection without any filter
###### (i) This ticket is created automatically based on a verified GitHub issue.        
{panel}
***If you are starting to work on this Jira ticket, please notify issue reporter and authors of related community pull requests (if any) that you are going to work on this issue:***
  1.  *Assign [#30936](https://github.com/magento/magento2/issues/30936) issue to yourself on Magento GitHub*
  2.  *Add comment "Internal Magento team is working on this issue right now."*
{panel}
######Preconditions (*)
1. Magento 2.4

######Steps to reproduce (*)
1. Set break ponit at https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/Page/DataProvider.php#L103
2. Open https://your*backend.com/admin/cms/page/edit/page*id/17

######Expected result (*)
1. Only curent page should be loaded

######Actual result (*)
1. All exiting pages are loaded in my case 1200

### PR DESCRIPTION
**Pull request by larsroettig**
### Description (*)
Edit pages in Backend was loading all CMS Pages to use only one for render the form. 

Here it creates new collection without filter the foreach loads the collection.
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cms/Model/Page/DataProvider.php#L103

### Related Pull Requests
- None

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30936

### Manual testing scenarios (*)
1. Open Edit CMS EDIT Page in Backend 
2. Save CMS Page in Backend

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by larsroettig** [comment]
@magento give me test instance

**Comment by larsroettig** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 1]
```diff
@@ -18,21 +20,16 @@
...
-    /**
-     * @var \Magento\Cms\Model\ResourceModel\Page\Collection
-     */
-    protected $collection;
-
     /**
      * @var DataPersistorInterface
      */
     protected $dataPersistor;
-
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]: I would keep this line for consistency and code style.

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 2]
```diff
@@ -18,21 +20,16 @@
...
     /**
      * @var array
      */
     protected $loadedData;
-
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php:35]: I would keep this line for consistency and code style.

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 3]
```diff
@@ -47,11 +44,10 @@ class DataProvider extends \Magento\Ui\DataProvider\ModifierPoolDataProvider
      * @var CustomLayoutManagerInterface
      */
     private $customLayoutManager;
-
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php:50]: I would keep this line for consistency and code style.

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 4]
```diff
@@ -78,33 +75,20 @@ public function __construct(
         PoolInterface $pool = null,
         ?AuthorizationInterface $auth = null,
         ?RequestInterface $request = null,
-        ?CustomLayoutManagerInterface $customLayoutManager = null
+        ?CustomLayoutManagerInterface $customLayoutManager = null,
+        ?PageRepositoryInterface $pageRepository = null
     ) {
+
+        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data, $pool);
+
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]:
```suggestion
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data, $pool);
```

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 5]
```diff
@@ -123,40 +107,71 @@ public function prepareMeta(array $meta)
...
+     */
+    public function getCurrentPage(): ?Page
+    {
+        if (!$this->getRequestFieldName()) {
+            return null;
+        }
+
+        $pageId = (int)$this->request->getParam($this->getRequestFieldName());
+        if ($pageId === 0) {
+            return null;
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]: Can we throw an exception here instead of returning null? It may help us with error handling.

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 6]
```diff
@@ -123,40 +107,71 @@ public function prepareMeta(array $meta)
...
+        if (isset($this->loadedPages[$pageId])) {
+            return $this->loadedPages[$pageId];
+        }
+
+        try {
+            $this->loadedPages[$pageId] = $this->pageRepository->getById($pageId);
+            return $this->loadedPages[$pageId];
+        } catch (LocalizedException $exception) {
+            return null;
+        }
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]: Maybe we don't need to wrap this on a try-catch and leave the exception handling for where we are calling this function.

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 7]
```diff
@@ -123,40 +107,71 @@ public function prepareMeta(array $meta)
...
+        $this->dataPersistor->clear('cms_page');
+
         return $this->loadedData;
     }
 
+    /**
+     * Loads the current page by current request params.
+     * @return Page|null
+     */
+    public function getCurrentPage(): ?Page
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]:
```suggestion
    private function getCurrentPage(): ?Page
```

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 8]
```diff
@@ -123,40 +107,71 @@ public function prepareMeta(array $meta)
...
-            $this->loadedData[$page->getId()] = $page->getData();
-            if ($page->getCustomLayoutUpdateXml() || $page->getLayoutUpdateXml()) {
-                //Deprecated layout update exists.
-                $this->loadedData[$page->getId()]['layout_update_selected'] = '_existing_';
-            }
+
+        $page = $this->getCurrentPage();
+        if ($page === null) {
+            return [];
+        }
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]: By adding exceptions to `getCurrentPage` we can wrap this on try-catch and handle the errors appropriately, what do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @larsroettig, thanks for your contribution! Well, good catch on that one. Please follow some comments below.

Also, I believe some of the failed tests may be related to these PR changes, can you have a look at them?

Thanks!

**Comment by engcom-Charlie** [comment]
Hi @larsroettig, could you please update your PR accordingly to https://github.com/magento/magento2/pull/30943#pullrequestreview-540839687?
Thank you.

**Comment by larsroettig** [comment]
@engcom-Charlie surre will update today sorry i missed this notfication

**Comment by engcom-Charlie** [comment]
Hi @larsroettig, please update your PR accordingly to https://github.com/magento/magento2/pull/30943#pullrequestreview-540839687. Otherwise, we can't proceed with your PR.
Thank you.

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 9]
```diff
@@ -186,16 +203,19 @@ public function getMeta()
...
+        try {
+            $page = $this->getCurrentPage();
             if ($page->getCustomLayoutUpdateXml() || $page->getLayoutUpdateXml()) {
                 $options[] = ['label' => 'Use existing layout update XML', 'value' => '_existing_'];
             }
             foreach ($this->customLayoutManager->fetchAvailableFiles($page) as $layoutFile) {
                 $options[] = ['label' => $layoutFile, 'value' => $layoutFile];
             }
+        } catch (LocalizedException $exception) {
+
```
Comment (larsroettig) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]: @gabrieldagama schould add logger there because empty catch will lead to static error ?

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 10]
```diff
@@ -123,40 +111,69 @@ public function prepareMeta(array $meta)
...
 
+    /**
+     * Loads the current page by current request params.
+     * @return Page
+     * @throws LocalizedException
+     */
+    private function getCurrentPage(): Page
+    {
+        if (!$this->getRequestFieldName()) {
+            throw new LocalizedException(__('RequestFieldName is not spefied'));
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]:
```suggestion
            throw new LocalizedException(__('RequestFieldName is not specified'));
```

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 11]
```diff
@@ -123,40 +111,69 @@ public function prepareMeta(array $meta)
...
+        }
+
+        $pageId = (int)$this->request->getParam($this->getRequestFieldName());
+        if ($pageId === 0) {
+            throw new LocalizedException(__('Page size must be given'));
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]:
```suggestion
            throw new LocalizedException(__('Page ID must be given'));
```

File: app/code/Magento/Cms/Model/Page/DataProvider.php (hunk 9 above)
Comment (gabrieldagama) [reply app/code/Magento/Cms/Model/Page/DataProvider.php]: Yes, I believe we should add a log in such a case.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @larsroettig, thanks for updating the PR! Please follow some small suggestions on exception msgs!

**Comment by engcom-Charlie** [comment]
Hi @larsroettig, please update your PR accordingly to https://github.com/magento/magento2/pull/30943#discussion_r537478967.
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @larsroettig, I'll continue with your PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8576](https://jira.corp.magento.com/browse/ENGCOM-8576) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Set a breakpoint at `return $this->loadedData;` line in file _/app/code/Magento/Cms/Model/Page/DataProvider.php_
2. From Admin Panel, go to _Content - Pages_ and open any page for **Edit**
3. Observe the output of debug session. **Evaluate** `$this->loadedData;`

**BEFORE** applying changes provided in the PR, all existing pages appeared in the Result. (4 pages in my case)
pr_before

**AFTER** switching to the PR,
set breakpoint an line `if (empty($data)) {
            return $this->loadedData;` (different line after switching to teh PR) Only the Edited page apears in the Result
pr_after

**Comment by engcom-Bravo** [comment]
Closed the PR by accident. Immediately reopened it.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @engcom-Charlie, can you have a look at the failed test for EE/B2B? It seems to be failing constantly.

Thanks!

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 12]
```diff
@@ -128,29 +122,54 @@ public function getData()
...
+    }
+
+    /**
+     * Return current page
+     *
+     * @return PageInterface
+     */
+    private function getCurrentPage(): PageInterface
+    {
+        $newPage = $this->collection->getNewEmptyItem();
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]: Let's use factory to create a new object instead, the `getNewEmptyItem` returns `DataObject` and this method must return `PageInterface`.

Also, I would avoid assigning a variable if it is not gonna be used, I rather call directly the create method on the factory whenever it is necessary.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, thanks for working on this, can you have a look at my comment below?

Thanks!

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 13]
```diff
@@ -186,16 +213,23 @@ public function getMeta()
...
+            $this->logger->error($e->getMessage());
+        }
+
+        if ($page) {
             if ($page->getCustomLayoutUpdateXml() || $page->getLayoutUpdateXml()) {
                 $options[] = ['label' => 'Use existing layout update XML', 'value' => '_existing_'];
             }
             foreach ($this->customLayoutManager->fetchAvailableFiles($page) as $layoutFile) {
                 $options[] = ['label' => $layoutFile, 'value' => $layoutFile];
             }
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php:224]: If we add this within the try-catch we can remove this `if ($page) {`, right?

File: app/code/Magento/Cms/Model/Page/DataProvider.php [hunk 14]
```diff
@@ -128,29 +130,54 @@ public function getData()
...
-            if ($page->getCustomLayoutUpdateXml() || $page->getLayoutUpdateXml()) {
-                $this->loadedData[$page->getId()]['layout_update_selected'] = '_existing_';
-            }
-            $this->dataPersistor->clear('cms_page');
+        if (empty($data)) {
+            return $this->pageFactory->create();
         }
+        $this->dataPersistor->clear('cms_page');
+        $page = $this->pageFactory->create()
+            ->setData($data);
```
Comment (gabrieldagama) [inline app/code/Magento/Cms/Model/Page/DataProvider.php]:
```suggestion
        return $this->pageFactory->create()
            ->setData($data);
```

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, thanks for updating this PR, I've got just a couple more comments, but it is looking very good!

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8576](https://jira.corp.magento.com/browse/ENGCOM-8576) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The result is the same as in the report above https://github.com/magento/magento2/pull/30943#issuecomment-750849455
