### PR TITLE
[Backport] Fixes #18357 - SQL error when table prefix used.

### LINKED ISSUE #18357: checkout_agreement_store doesn't exist
### Preconditions

1. Starting from Magento CE 2.2.5
2. upgrade from 2.2.5 to 2.2.6

### Steps to reproduce

1. Starting from Magento CE 2.2.5
2. created a terms and conditions (Store-->Terms and conditions)
3. upgrade from 2.2.5 to 2.2.6
3. The Terms and conditions created are not visible in admin (Store-->Terms and conditions)

### Expected result

1. I can edit the old terms and conditions
2. I can insert a new terms and conditions

### Actual result

1. old terms and conditions are not visible
2. In production mode I can add a new terms and conditions but is not visible in admin
3. In developer mode there is an exception: 

2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXXX.checkout_agreement_store' doesn't exist, query was: SELECT `agreement_store`.* FROM `checkout_agreement_store` AS `agreement_store` WHERE (agreement_store.agreement_id IN ('1'))
Exception #1 (PDOException): SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXXX.checkout_agreement_store' doesn't exist

The table exist in DB; note that in sql there isn't the prefix to table.

### PR DESCRIPTION
**Pull request by gelanivishal**
### Original PR
#18412 

### Description
Hard-coded table names cause errors if a table prefix, passing the table name to getTable resolves this.

### Fixed Issues (if relevant)
1. magento/magento2#18357
https://github.com/magento/magento2/issues/18954

### Manual testing scenarios
1. Create a store using table prefixes
2. Navigate to Store > Terms and Conditions in the admin backend
3. Without the patch, errors are generated

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @gelanivishal. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me $VERSION instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

File: app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php [hunk 1]
```diff
@@ -63,7 +63,7 @@ private function getStoresForAgreements()
 
         if (!empty($agreementId)) {
             $select = $this->getConnection()->select()->from(
-                ['agreement_store' => 'checkout_agreement_store']
+                ['agreement_store' => $this->getResource()->getTable('checkout_agreement_store')]
```
Comment (sreichel) [inline app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php:66]: Is `getResource()` really necessary?

Comment (gelanivishal) [reply app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php:66]: Yes. It is. How do you get if the prefix of the table?

Comment (sreichel) [reply app/code/Magento/CheckoutAgreements/Model/ResourceModel/Agreement/Grid/Collection.php:66]: @gelanivishal Just `$this->getTable(...)` should be enough to get prefix table name.

**Comment by gelanivishal** [comment]
@VladimirZaets I can't find any **Codacy/PR Quality Review** error. Can you processed this PR?

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-3989](https://jira.corp.magento.com/browse/ENGCOM-3989) has been created to process this Pull Request

**Comment by Ctucker9233** [comment]
@magento-engcom-team Why was this moved from the 2.2.8 release to 2.2.9? It seems like a simple fix that should be released asap as it has caused many including myself significant problems.
