### PR TITLE
Fix #11175 - i18n:collect-phrases -m can't find many important Magento phrases - added parsing of the attr translations via `$t('Text')`

### LINKED ISSUE #11175: i18n:collect-phrases -m can't find many important magento phrases
**Summary**
This is continuation of thread https://github.com/magento/magento2/issues/2630
Magento 2.2 clear installation using script http://apps.scholtz.sk/magento.install.script.txt
### Preconditions

1. Magento 2.4-develop
2. PHP 7.1, Nginx, Mysql 5.7

### Steps to reproduce
1. Install Magento and download SK language pack
2. do collect phrases php bin/magento i18n:collect-phrases -o "$VER.csv" -m
3. translate phrases
4. Check translations in admin

(I have full translation of magento to slovak language, so i skip step 2 i install it through the script listed above)

### Expected result
I expect all texts to be localised

### Actual result
Some phrases are not translated.. Btw, i can see some progress in the 2 years work now, but still some are missing..

obrazok
obrazok
obrazok
obrazok
obrazok
obrazok

### LINKED ISSUE #31873: [Issue] Fix #11175 - i18n:collect-phrases -m can't find many important Magento phrases - added parsing of the attr translations via `$t('Text')`
This issue is automatically created based on existing pull request: magento/magento2#31804: Fix #11175 - i18n:collect-phrases -m can't find many important Magento phrases - added parsing of the attr translations via `$t('Text')`

---------
### Description (*)

According to the official Magento 2 documentations, there is a way to translate HTML attributes, but this is not covered as well. Here is a text from the documentation:

> When a string is added as an attribute of an HTML element:

```html
<input type="text" data-bind="attr: {placeholder: $t('First Name')}" />
```

[Documentation -  Strings added in UI component templates](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/translate_theory.html)

This was of translating attributes does not seem to be used in the Magento 2 itself (if my search is correct). Though,
it is officially documented, is used by some vendors and it can be found in some Q&A on the Internet
(like here - [magento.stackexchange.com](https://magento.stackexchange.com/questions/181070/magento-2-translate-input-placeholder-attribute-string-in-knockout-html-templat))

### Related Pull Requests
https://github.com/magento/magento2/commit/48216f3e13d04b8755b70f8b9b1399d87a33ab91

### Fixed Issues (if relevant)
1. Fixes magento/magento2#11175 - i18n:collect-phrases -m can't find many important magento phrases

### Manual testing scenarios (*)
1. Add the following code to any Magento `.html` file, for example `app/code/Magento/Catalog/view/frontend/web/template/product/addtocart-button.html`

```html
<a data-bind="attr: { title: $t('This is \' test \' data for attribute translation with single quotes'), href: '#'} "></a>
<a data-bind="attr: { title: $t('This is test data for attribute translation with a quote after\'\''), href: '#'} "></a>
<a data-bind="attr: { title: $t('This is test data for attribute translation with a quote after\' \' '), href: '#'} "></a>
<input type="text" data-bind="attr: { placeholder: $t('Attribute translation - Placeholder'), title: $t('Attribute translation - Title') }" />
```

2. Run the command `php bin/magento i18n:collect-phrases app/code/Magento/Catalog/view/frontend/web/template/product/`

Expected result: Command output contains phrases in the `$t('Text')` translations that cat be then used in the i18n files.
i18n output example:
```text
"This is ' test ' data for attribute translation with single quotes","This is ' test ' data for attribute translation with single quotes"
"This is test data for attribute translation with a quote after''","This is test data for attribute translation with a quote after''"
"This is test data for attribute translation with a quote after' ' ","This is test data for attribute translation with a quote after' ' "
"This is "" test "" data with 'href' after translate","This is "" test "" data with 'href' after translate"
```

Actual result: The above phrases are not present in the output.

### Contribution checklist (*)
- [ ] Pull request has a meaningful description of its purpose
- [ ] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by maksymz**
### Description (*)

According to the official Magento 2 documentations, there is a way to translate HTML attributes, but this is not covered as well. Here is a text from the documentation:

> When a string is added as an attribute of an HTML element:

```html
<input type="text" data-bind="attr: {placeholder: $t('First Name')}" />
```

[Documentation -  Strings added in UI component templates](https://devdocs.magento.com/guides/v2.4/frontend-dev-guide/translations/translate_theory.html)

This was of translating attributes does not seem to be used in the Magento 2 itself (if my search is correct). Though,
it is officially documented, is used by some vendors and it can be found in some Q&A on the Internet
(like here - [magento.stackexchange.com](https://magento.stackexchange.com/questions/181070/magento-2-translate-input-placeholder-attribute-string-in-knockout-html-templat))

### Related Pull Requests
https://github.com/magento/magento2/commit/48216f3e13d04b8755b70f8b9b1399d87a33ab91

### Fixed Issues (if relevant)
1. Fixes magento/magento2#11175 - i18n:collect-phrases -m can't find many important magento phrases

### Manual testing scenarios (*)
1. Add the following code to any Magento `.html` file, for example `app/code/Magento/Catalog/view/frontend/web/template/product/addtocart-button.html`

```html
<a data-bind="attr: { title: $t('This is \' test \' data for attribute translation with single quotes'), href: '#'} "></a>
<a data-bind="attr: { title: $t('This is test data for attribute translation with a quote after\'\''), href: '#'} "></a>
<a data-bind="attr: { title: $t('This is test data for attribute translation with a quote after\' \' '), href: '#'} "></a>
<input type="text" data-bind="attr: { placeholder: $t('Attribute translation - Placeholder'), title: $t('Attribute translation - Title') }" />
```

2. Run the command `php bin/magento i18n:collect-phrases app/code/Magento/Catalog/view/frontend/web/template/product/`

Expected result: Command output contains phrases in the `$t('Text')` translations that cat be then used in the i18n files.
i18n output example:
```text
"This is ' test ' data for attribute translation with single quotes","This is ' test ' data for attribute translation with single quotes"
"This is test data for attribute translation with a quote after''","This is test data for attribute translation with a quote after''"
"This is test data for attribute translation with a quote after' ' ","This is test data for attribute translation with a quote after' ' "
"This is "" test "" data with 'href' after translate","This is "" test "" data with 'href' after translate"
```

Actual result: The above phrases are not present in the output.

### Contribution checklist (*)
- [ ] Pull request has a meaningful description of its purpose
- [ ] All commits are accompanied by meaningful commit messages
- [ ] All new or changed code is covered with unit/integration tests (if applicable)
- [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#31873: Fix #11175 - i18n:collect-phrases -m can't find many important Magento phrases - added parsing of the attr translations via `$t('Text')`

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

@maksymz, could you sign Adobe CLA in the meanwhile?

**Comment by maksymz** [comment]
@ihor-sviziev Have just signed the Adobe CLA. Should I reopen the Pull Request? Don't know how to re-run the checks

**Comment by ihor-sviziev** [comment]
@maksymz just closed and re-opened the PR, now it passes. Thank you!
I'll review your PR once the test results are ready

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8694](https://jira.corp.magento.com/browse/ENGCOM-8694) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@maksymz thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, WebAPI Tests

File: setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php [hunk 1]
```diff
@@ -30,7 +30,11 @@ class Html extends AbstractAdapter
         "/i18n:\s?'(?<value>[^'\\\\]*(?:\\\\.[^'\\\\]*)*)'/i",
         // <translate args="'System Messages'"/>
         // <span translate="'Examples'"></span>
-        "/translate( args|)=\"'(?<value>[^\"\\\\]*(?:\\\\.[^\"\\\\]*)*)'\"/i"
+        "/translate( args|)=\"'(?<value>[^\"\\\\]*(?:\\\\.[^\"\\\\]*)*)'\"/i",
+        // <a data-bind="attr: { title: $t('This is \' test \' data'), href: '#'} "></a>
+        // <input type="text" data-bind="attr: { placeholder: $t('Placeholder'), title: $t('Title') }" />
+        // Double quotes are not handled correctly in the `attr` binding. Move phrase to the UI component property if needed
+        '/\\$t\(\s*([\'"])(?<value>.*?[^\\\])\1.*?[),]/i'
```
Comment (gabrieldagama) [inline setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php]: Shouldn't we use the same pattern at the one `setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Js.php` instead?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @maksymz, thanks for contributing!

Can you have a look at my comment below?

Thanks!

File: setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php (hunk 1 above)
Comment (ihor-sviziev) [reply setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php]: @gabrieldagama I believe for js files it's already covered in https://github.com/magento/magento2/blob/754ea5fcb1ed51281019235b7095d8152a6ffdc6/setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Js.php#L32
But this issue/PR about knockout js inside html

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

File: setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php (hunk 1 above)
Comment (gabrieldagama) [reply setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php]: Hi @ihor-sviziev, you are right, for JS is already covered. We were discussing it at the public triage meeting, and @sivaschenko highlighted that the regex between JS and HTML should be the same. 

As far as I can see the difference between them is the `?<value>` that is added, and the `/i` that would make the behavior between them different, one would be case sensitive, the other not.

Comment (ihor-sviziev) [reply setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php]: @maksymz, could you unify the regex between this line and the similar one in the JS file?
https://github.com/magento/magento2/blob/754ea5fcb1ed51281019235b7095d8152a6ffdc6/setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Js.php#L32

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php (hunk 1 above)
Comment (maksymz) [reply setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php]: @gabrieldagama @ihor-sviziev 
The whole thing is about the `.html` templates for Knockout components.

The patterns is the same as in the JS file. I've added this part due to the difference in the parser code: `?<value>`.

Though, seems that `\i` modifier is a problem here. `$T()` will not work as function names in JS are case-sensitive. Besides, I've just checked both the previous fix to this file (https://github.com/magento/magento2/issues/11175) and the original pattern. It seems both must be case-sensitive, because:

a) Knockout binding names are case-sensitive. 
The following will not work:
```html
<span data-bind="I18N: 'Foo Bar Baz'"></span>
```

The following works fine:
```html
<span data-bind="i18n: 'Foo Bar Baz'"></span>
```

b) translation via the `translate` attribute works only when the attribute name is lowercase.
The following will not work:
```html
<span TRANSLATE="'Foo Bar Baz'"></span>
```

The following works fine:
```html
<span translate="'Foo Bar Baz'"></span>
```

Current state: translations work only with the lowercase attribute/binding/function call.

Solution 1: remove the `i` modifier from all three patterns, update unit tests to cover uppercase spelling. We get better translations coverage and the rules will be defined better. No changes to how translations work.

Solution 2: search where `translate` attribute is processed and make it possible to work with uppercase attributes. Though, uppercase tag attributes are probably controversial with the HTML code style.

Think solution 1 is better. I'll change the code and update unit tests if agreed.

Regards,
Max

Comment (maksymz) [reply setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php]: Just checked one more way of translating the text. Right now the following does not work as well, the text is shown without translation:
```html
<TRANSLATE args="'Foo Bar Baz'"/>
```

The following works fine:
```html
<translate args="'Foo Bar Baz'"/>
```

**Comment by maksymz** [comment]
@ihor-sviziev Sorry for disturbing you regarding this issue again.

The test  in file `setup/src/Magento/Setup/Module/I18n/Parser/Adapter/Html.php` uses the following fixtures file: `setup/src/Magento/Setup/Test/Unit/Module/I18n/Parser/Adapter/_files/email.html`.

It looks incorrect that the file with email-related directives also contain Knockout-related things. Though, there is totally other set of email-related test, and they have their own template file. Besides. translations via directives (like `{{trans 'Foo Bar Baz'}}`) will not work in the Knockout component templates. It is probably better to rename this file from `email.html` to `file.html` (like `file.js` in the same folder) and remove the email-related things from this file and from the test itself. Does this make sense?

Regards,
Max

**Comment by ihor-sviziev** [comment]
@magento run all test

@maksymz could you explain more what's the different in parsers, why can't we add or remove `?<value>` in both cases?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by maksymz** [comment]
@ihor-sviziev 

> could you explain more what's the different in parsers, why can't we add or remove ?<value> in both cases?

There are several patterns, and the `?value` allows to ignore the position of the catch group which contains the actual value. I mean this part:
```php
if (!empty($results[$i]['value'])) {
    $this->_addPhrase($results[$i]['value']);
}
```

From the other hand, it is possible to:
- move the pattern in JS parser into the constant;
- substitute the loop in HTML parser with a closure or protected method call, which accepts the index of the value in the catch group.
In this case the same constant with pattern will be used in both places.

Will make this change and push the code for review.

**Comment by maksymz** [comment]
@magento run all tests

**Comment by maksymz** [comment]
@ihor-sviziev JS and HTML parser now use constants for regex patterns. Also, JS parser was changed a little to remove code duplication and a few simple test were added for it. I've also removed the `deprecated` annotation from the `HTML_FILTER` constant because it is now used again. This should be fine because the previous fix has not been released yet.

Regards,
Max

**Review by ihor-sviziev — APPROVED** [review]
Great job! 👍
 ✔ Approved!

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Add the following code to any Magento `.html` file, for example `app/code/Magento/Catalog/view/frontend/web/template/product/addtocart-button.html`

```html
<a data-bind="attr: { title: $t('This is \' test \' data for attribute translation with single quotes'), href: '#'} "></a>
<a data-bind="attr: { title: $t('This is test data for attribute translation with a quote after\'\''), href: '#'} "></a>
<a data-bind="attr: { title: $t('This is test data for attribute translation with a quote after\' \' '), href: '#'} "></a>
<input type="text" data-bind="attr: { placeholder: $t('Attribute translation - Placeholder'), title: $t('Attribute translation - Title') }" />
```

2. Run the command `php bin/magento i18n:collect-phrases app/code/Magento/Catalog/view/frontend/web/template/product/`

**Before:** :heavy_multiplication_x:  The above phrases are not present in the output.

Screenshot from 2021-01-28 10-55-16

**After:** :heavy_check_mark:  Command output contains phrases in the `$t('Text')` translations that cat be then used in the i18n files.

Screenshot from 2021-01-28 11-12-35

Also added a few phrases that were not collected on the mainline.

_Run:_ `php bin/magento i18n:collect-phrases --output=mainline.csv app/code/Magento/`

The results can be seen in the comparison of the mainline and with changes from PR - [diff](https://www.diffchecker.com/0KMjATlK/)

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by vertic4l** [comment]
Could this relate to my issue? https://github.com/magento/magento2/issues/33772
