### PR TITLE
Fix #30073 - Store specific text swatch attribute option label with v…

### LINKED ISSUE #30073: Store specific text swatch attribute option label with value 0 (zero) can't be saved and automatically replaced with Admin Label value of option
Store-specific text swatch attribute option label with value 0 (zero) can't be saved and automatically replaced with Admin Label value of the option

### Preconditions
* Magento 2.3.5-p2, 2.4-develop

### Steps to reproduce
1. Create multistore Magento instance
2. Create text swatch attribute
3. Insert in non-default store label input field **0** (like at the screenshot)
image
4. Save attribute

### Expected result
1. Store-specific option label saved as inserted

### Actual result
1. Instead of **0** option store specific label is replaced with Admin label value
image

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
…alue 0 (zero) can't be saved and automatically replaced with Admin Label value of option

### Description (*)

The issue is fixed specifically by https://github.com/magento/magento2/pull/30114/files#diff-e82f73165c79d2422b9b50632a4ff4feL355 - rest of modifications in the class are just cleanup

### Fixed Issues (if relevant)

1. Fixes magento/magento2#30073

### Manual testing scenarios (*)

Please check fixed issue for testing scenario

### Questions or comments

I believe unit test should be enough for such type of change

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento run Integration Tests

**Comment by Bartlomiejsz** [comment]
@magento run Integration Tests

**Comment by rogyar** [comment]
Hi @Bartlomiejsz. Great work, thank you! 
I don't see the failing integration tests, only the skipped ones. So, I believe we don't have an issue there.

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8234](https://jira.corp.magento.com/browse/ENGCOM-8234) has been created to process this Pull Request

File: app/code/Magento/Swatches/Model/Plugin/EavAttribute.php [hunk 1]
```diff
@@ -209,15 +218,14 @@ protected function processSwatchOptions(Attribute $attribute)
...
      * @return array
      */
     protected function prepareOptionIds(array $optionsArray)
     {
         if (isset($optionsArray['value']) && is_array($optionsArray['value'])) {
             foreach (array_keys($optionsArray['value']) as $optionId) {
-                if (isset($optionsArray['delete']) && isset($optionsArray['delete'][$optionId])
-                    && $optionsArray['delete'][$optionId] == 1
-                ) {
+                if (isset($optionsArray['delete'][$optionId]) && $optionsArray['delete'][$optionId] == 1) {
```
Comment (Stepa4man) [inline app/code/Magento/Swatches/Model/Plugin/EavAttribute.php]: Could you please simplify this nested ifs, handling the negative case first and use a strict comparison operator?

File: app/code/Magento/Swatches/Model/Plugin/EavAttribute.php [hunk 2]
```diff
@@ -374,13 +388,16 @@ protected function processTextualSwatch(Attribute $attribute)
...
      * @param integer $optionId
+     *
      * @return int
      */
     protected function getAttributeOptionId($optionId)
     {
-        if (substr($optionId, 0, 6) == self::BASE_OPTION_TITLE || substr($optionId, 0, 3) == self::API_OPTION_PREFIX) {
-            $optionId = isset($this->dependencyArray[$optionId]) ? $this->dependencyArray[$optionId] : null;
+        if (strpos((string)$optionId, self::BASE_OPTION_TITLE) === 0 ||
+            strpos((string)$optionId, self::API_OPTION_PREFIX) === 0) {
```
Comment (Stepa4man) [inline app/code/Magento/Swatches/Model/Plugin/EavAttribute.php:382]: Not clear what is checked here from the first glance. Can I ask you to move these conditions to another private method and name it so it displays what exactly it checks.

**Review by Stepa4man — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz 
Thanks for your contribution

Could you please take a look at my comments?

**Comment by Stepa4man** [comment]
@magento give me test instance

File: app/code/Magento/Swatches/Model/Plugin/EavAttribute.php (hunk 2 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Swatches/Model/Plugin/EavAttribute.php:382]: To be honest I'm not sure what is purpose of this check, and I'm not author of this part. I only replaced `substr` with `strpos` since it made more sense in such comparison in my opinion...

File: app/code/Magento/Swatches/Model/Plugin/EavAttribute.php (hunk 1 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Swatches/Model/Plugin/EavAttribute.php]: Hi @Stepa4man, done

File: app/code/Magento/Swatches/Model/Plugin/EavAttribute.php (hunk 2 above)
Comment (Stepa4man) [reply app/code/Magento/Swatches/Model/Plugin/EavAttribute.php:382]: Ok, I think we can live with this=)

**Comment by Stepa4man** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@Stepa4man @rogyar is there any other update needed here?

**Comment by rogyar** [comment]
Not from my end. The failing tests don't seem to be related to the current changeset. 
@Stepa4man could you recheck and confirm, please? 

Thanks

**Comment by engcom-Hotel** [comment]
will check the tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8234](https://jira.corp.magento.com/browse/ENGCOM-8234) has been created to process this Pull Request

**Review by Stepa4man — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Stepa4man, thank you for the review.
[ENGCOM-8234](https://jira.corp.magento.com/browse/ENGCOM-8234) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create multistore Magento instance;
2. Admin -> Stores -> Attribute -> Product and Create text swatch attribute;
3. Insert in non-default store label input field 0;
4. Save Attribute;

**Before:** :heavy_multiplication_x: Instead of **0** option store specific label is replaced with Admin label value



**After:** :heavy_check_mark: Store-specific option label saved as inserted

**Comment by Stepa4man** [comment]
@sidolov which version will contain these commits changes?

**Comment by sidolov** [comment]
@Stepa4man it's included to 2.4.2 reelase.
