### PR TITLE
24070 - Allowed multivalue form elements to submit data to website/gr…

### LINKED ISSUE #24070: Website/Group/Store entity form can't be extended with multiple value form element for extension attributes
### Summary (*)
When extending the Website/Group/Store form (_module-backend/Block/System/Store/Edit/AbstractForm.php_) with the _adminhtml_store_edit_form_prepare_form_ event, multiple value fields (arrays) are being flattened by the javascript store validator (_module-backend/view/adminhtml/web/js/validate-store.js_). Preventing me to extend this form with a multiselect, checkboxes or radios form element.

### Examples (*)
1. Create Observer for adminhtml_store_edit_form_prepare_form
2. Add field with multiselect.
```
    /**
     * @param Observer $observer
     */
    public function execute(Observer $observer): void
    {
        $block = $observer->getEvent()->getBlock();
        $form = $block->getForm();
        $fieldSettings = [
            'name' => 'store[multiple][]',
            'label' => __('Multiselect field'),
            'value' => '',
            'values' => [
            ],
            'required' => false,
            'disabled' => false,
        ];

        $fieldset = $form->addFieldset('group_multiselect', ['legend' => __('Multiselect fieldset')]);
        $fieldset->addField('multiselectElement', 'multiselect', $fieldSettings);
        $observer->setData('block', $block->setForm($form));
    }
```
3. Save form and check headers of postdata.

### Proposed solution
Remove the each callback on serializeArray which sets the name of the formData element to a singular value or only apply the filter on the initial elements.

```
$.each($(form).serializeArray(), function () {
    formData[this.name] = this.value || '';
});
```

EDIT:

The proposed solution does not work, there can only be a single fieldname because it's converted to an object, which in turn, turns into a new form, with input name/value fields and that is being posted. Why you want do such a thing on a perfectly formatted html form, I don't know. But this is how it works :(

There is no way to post multiple values for this form unless it's an direct post instead of this fake form post generation.

Will create a pull request and provide solution for this issue shortly.

### PR DESCRIPTION
**Pull request by ericclaeren**
### Description (*)
Fix for issue: https://github.com/magento/magento2/issues/24070

When submitting a website, group or store entity form (add/edit), submitted multivalue form elements get filtered and only the last selected element will be posted to the controller.

This posted data
```
fieldname[]: value1
fieldname[]: value2
```
Turns into
```
{
   fieldname[]: value2
}
```

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/24070#issue-478488652 : Website/Group/Store entity form can't be extended with multiple value form element for extension attributes

* Transform fieldnames with multiple [] to an indexed one.
** This: 
```
fieldname[]: value1
fieldname[]: value2
```
** Turns into
```
fieldname[]: value1
fieldname[1]: value2
```

Therefore the names are different and both fields can be converted to a new input to be actually posted to the controller.

I chose not to convert the first fieldname[] to fieldname[0] because altering this, I could not reference to the fieldname within the same set of data and this needed more javascript code. This is not necessary for PHP which receives fieldname[] as 0 and fieldname[1] as 1.

Used let/const because they are supported in IE11 and don't interfere with scope of the function.

### Manual testing scenarios (*)
* Extend the Store.php form block with a multivalue field. See: https://github.com/magento/magento2/issues/24070
** <select name="fieldname[]" multiple="multiple">
* The submitted data in validate-store.js will converted a key/value object
* A new html form will be generated with <input name="" value="" /> of the previous object entries.
* This form is posted to the controller.
* Current postdata fields won't be altered, multivalue fields will be submitted, before only the last element gets posted.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=24094) <br/>All committers have signed the CLA.

File: app/code/Magento/Backend/view/adminhtml/web/js/validate-store.js [hunk 1]
```diff
@@ -50,9 +50,17 @@ define([
                 options = $.data(form, 'validator').settings;
 
             if ($(form).validation('isValid')) {
+                const counts = {};
```
Comment (VladimirZaets) [inline app/code/Magento/Backend/view/adminhtml/web/js/validate-store.js]: Hi @ericclaeren, thanks for collaboration. 

Please change all `const` and `let` declaration to `var`. Currently, we support just ES5 and we cant use `const` and `let` that was provided in ES6

**Review by VladimirZaets — CHANGES_REQUESTED** [review]

File: app/code/Magento/Backend/view/adminhtml/web/js/validate-store.js (hunk 1 above)
Comment (ericclaeren) [reply app/code/Magento/Backend/view/adminhtml/web/js/validate-store.js]: Thank you for the feedback @VladimirZaets. Have changed the variable declarations. See: https://github.com/magento/magento2/pull/24094/files

**Comment by ericclaeren** [comment]
Hi @VladimirZaets, have fixed the variable declarations and ran into js linting errors which I have resolved. Would you mind reviewing my code again? Thanks

**Review by VladimirZaets — DISMISSED** [review]
Thanks for fixes.

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-5604](https://jira.corp.magento.com/browse/ENGCOM-5604) has been created to process this Pull Request
:eight_spoked_asterisk: @VladimirZaets, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@ericclaeren thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ericclaeren** [comment]
@VladimirZaets The purpose of this change is untested by auto-test.

Although Magento Core has a jasmin JS test for this validate function, there isn't a test for the _saveHandler() method. See: validate-store.test.js. So the whole core JS functionality isn't being tested right now.

**Comment by ericclaeren** [comment]
@magento-engcom-team The label has been added.

**Comment by engcom-Delta** [comment]
Hi @ericclaeren seems like issue described by PR wasn't fixed.
**Manual testing scenario:**

- Create Observer for adminhtml_store_edit_form_prepare_form
- Add field with multiselect.

```/**
     * @param Observer $observer
     */
    public function execute(Observer $observer): void
    {
        $block = $observer->getEvent()->getBlock();
        $form = $block->getForm();
        $fieldSettings = [
            'name' => 'store[multiple][]',
            'label' => __('Multiselect field'),
            'value' => '',
            'values' => [
                ['value' => 'value1', 'label' => 'testLabel1'],
                ['value' => 'value2', 'label' => 'testLabel2']

            ],
            'required' => false,
            'disabled' => false,
        ];

        $fieldset = $form->addFieldset('group_multiselect', ['legend' => __('Multiselect fieldset')]);
        $fieldset->addField('multiselectElement', 'multiselect', $fieldSettings);
        $observer->setData('block', $block->setForm($form));
```

- Select all values from multiselect

#24094PRMultiselect

- Save form and check headers of postdata.

**Result:**
:x: Only last value from multiselect was sent in POST
#24094PRPost

**Comment by ericclaeren** [comment]
That's really weird, are you sure the correct (patched) validation-store.js code is loaded.

Some screens from my code. The observer is pretty much the same, although my data are store Ids.

**Multiselect**
image

**console.table(formData)** of validate-store.js
Screenshot 2019-09-23 at 09 37 15

**Request recorded in Google Chrome.**
Screenshot 2019-09-23 at 09 45 37

As you may see in the screenshot both values are posted. I have a working / functioning module with this patch.

Could you explain how you evaluated your code?

**Comment by sidolov** [comment]
@engcom-Delta please, take a look a comment from @ericclaeren

**Comment by engcom-Delta** [comment]
@ericclaeren I debug Magento/Backend/Controller/Adminhtml/System/Store/[Save.php](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Backend/Controller/Adminhtml/System/Store/Save.php#L115) and check $_POST variable:
image
Here what I get in console:
#24094PRConsoleJS

And code snippet of my multiselect field:
```
/**
* @param Observer $observer
*/
public function execute(Observer $observer): void
    {
        $block = $observer->getEvent()->getBlock();
        $form = $block->getForm();
        $fieldSettings = [
            'name' => 'store_custom',
            'label' => __('Multiselect field'),

            'values' => [
                ['label' => 'testLabel1', 'value' => 'value1'],
                ['label' => 'testLabel2', 'value' => 'value2']

            ],
            'required' => false,
            'disabled' => false,
        ];

        $fieldset = $form->addFieldset('group_multiselect', ['legend' => __('Multiselect fieldset')]);
        $fieldset->addField('multiselectElement', 'multiselect', $fieldSettings);
        $observer->setData('block', $block->setForm($form));
    }
```

**Comment by ericclaeren** [comment]
That's really interesting, the format also is different [0] vs []. 

Could you validate if your local codebase in /validate-store.js on line 55 contains `counts[this.name] = (counts[this.name] || 0) + 1;`?

Have no clue why this is not working and the output differs.

**Comment by engcom-Delta** [comment]
@ericclaeren I have tested PR branch with appropriate changes in validate-store.js.
Row ```counts[this.name] = (counts[this.name] || 0) + 1;``` is present there.
#24094PR

**Comment by ericclaeren** [comment]
Thanks for the feedback, will look into this.

**Comment by ericclaeren** [comment]
Allright, i'm a bit lost right now. Have tried the exact same steps, copied your code example of the multiple fields in my observer. And have totally different output in chrome debugger as in phpstorm debugger.

Attached you will find my screencast. Any suggestions?
example

**Comment by ericclaeren** [comment]
@engcom-Delta Have you seen my findings. I'm a bit stuck on why we have a completely different output.

**Comment by VladimirZaets** [comment]
Hi @ericclaeren. Thanks for collaboration. I will try to investigate why the results are different.

**Comment by ericclaeren** [comment]
Any news on this issue?

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@ericclaeren please, sign Adobe CLA

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5604](https://jira.corp.magento.com/browse/ENGCOM-5604) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
Selected multivalue fields are submitted
image
image

**Review by engcom-Charlie — CHANGES_REQUESTED** [review]
@ericclaeren please sign CLA. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@ericclaeren please look at https://github.com/magento/magento2/pull/24094#pullrequestreview-510388676
Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
As code review, testing is already completed on this PR. Also the Adobe CLA is signed now. Moving this PR in Extended Testing.

**Comment by engcom-Dash** [comment]
Hello @ericclaeren 

Thank you for your contribution.

We’ve verified that the issue is still reproducible, and we can confirm that the solution proposed in this PR effectively resolves it. We’ll be taking it forward from here and proceeding with the necessary steps to get it merged.

Appreciate your efforts!

Thanks!
