### PR TITLE
Fix #7065 - page.main.title is translating title

### LINKED ISSUE #7065: page.main.title is translating title
The page.main.title block is translating the title. This can lead to unwanted results (like the product name being translated...)
### Preconditions
1. MG2.1 CE
2. PHP7.0
### Steps to reproduce

1. Create a product with the name 'Save'
2. Create a storeview that doesn't use english as locale (I'm using nl_NL as example)
3. Go to the product detail page
### Expected result
1. The page title in page.main.title should be 'Save'
### Actual result
1. The page title in page.main.title is 'Opslaan' (dutch translation for save)

I traced this back to \Magento\Theme\Block\Html\Title.
Both the getPageTitle() and getPageHeading() function are wrapping the output in the magic translation function. Because of this the product name is being translated.

```
public function getPageTitle()
{
    if (!empty($this->pageTitle)) {
        return $this->pageTitle;
    }
    return __($this->pageConfig->getTitle()->getShort());
}

public function getPageHeading()
{
    if (!empty($this->pageTitle)) {
        return __($this->pageTitle);
    }
    return __($this->pageConfig->getTitle()->getShortHeading());
}
```

I'm pretty sure the translation here can be dropped all together because you can control the page titles from either the layout xml's or through the backend on storeview values.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #7065. To resolve the issue additional configuration option was added to store design configuration. As default, current behavior is kept, but this can be changed to not translate title, if needed.

### Fixed Issues (if relevant)

1. magento/magento2#7065: page.main.title is translating title

### Manual testing scenarios (*)

1. Create a product with the name 'Save'
2. Create a storeview that doesn't use english as locale (I'm using nl_NL as example)
3. Change `Translate Title` option in Content -> Design -> Configuration to `No`, flush cache
4. Go to the product detail page
5. Page title should no longer be translated

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/Theme/Block/Html/Title.php [hunk 1]
```diff
@@ -19,13 +22,39 @@
...
+     * @param array $data
+     * @param ScopeConfigInterface|null $scopeConfig
+     */
+    public function __construct(
+        Template\Context $context,
+        array $data = [],
+        ScopeConfigInterface $scopeConfig = null
+    ) {
+        parent::__construct($context, $data);
+        $this->scopeConfig = $scopeConfig ?: ObjectManager::getInstance()->get(ScopeConfigInterface::class);
```
Comment (nuzil) [inline app/code/Magento/Theme/Block/Html/Title.php]: Before we used such constructions to keep backward compatibility.
Currently we are delivering code in Magento 2.4.
So can you please, implement this without using of ObjectManager directly

**Review by nuzil — CHANGES_REQUESTED** [review]

File: app/code/Magento/Theme/Block/Html/Title.php (hunk 1 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Theme/Block/Html/Title.php]: @nuzil done

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-6557](https://jira.corp.magento.com/browse/ENGCOM-6557) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Foxtrot** [comment]
@magento run all tests
