### PR TITLE
[PHPDOC] Fix bad phpdoc Magento\Framework\App\Config\ScopeConfigInterface

### LINKED ISSUE #39492: [Issue] [PHPDOC] Fix bad phpdoc Magento\Framework\App\Config\ScopeConfigInterface
This issue is automatically created based on existing pull request: magento/magento2#39199: [PHPDOC] Fix bad phpdoc Magento\Framework\App\Config\ScopeConfigInterface

---------
### Description (*)

This PR fix bad phpdoc in  `Magento\Framework\App\Config\ScopeConfigInterface` : 

- `getValue` : The `$scopeCode` argument can accept StoreInterface
- `isSetFlag` : The `$scopeCode` argument can accept StoreInterface

Here is an example where the type `StoreInterface` is used :

https://github.com/magento/magento2/blob/7377de59a5458cce1945741303e49a29f98cc329/lib/internal/Magento/Framework/App/Config.php#L66-L75

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :(

Capture d’écran du 2024-09-23 10-28-32

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dimitriBouteille**
### Description (*)

This PR fix bad phpdoc in  `Magento\Framework\App\Config\ScopeConfigInterface` : 

- `getValue` : The `$scopeCode` argument can accept StoreInterface
- `isSetFlag` : The `$scopeCode` argument can accept StoreInterface

Here is an example where the type `StoreInterface` is used :

https://github.com/magento/magento2/blob/7377de59a5458cce1945741303e49a29f98cc329/lib/internal/Magento/Framework/App/Config.php#L66-L75

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :(

Capture d’écran du 2024-09-23 10-28-32

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39492: [PHPDOC] Fix bad phpdoc Magento\Framework\App\Config\ScopeConfigInterface

### CODE REVIEW

**Comment by dimitriBouteille** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @dimitriBouteille,

Thank you for your contribution!

The changes look good to us. However, please check the failed tests, particularly the static test, and address the issues accordingly.

**Comment by dimitriBouteille** [comment]
@magento run all tests

**Comment by dimitriBouteille** [comment]
@magento run Static Tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by dimitriBouteille** [comment]
@engcom-Dash Thanks you :heart:

**Review by engcom-Hotel — APPROVED** [review]

**Comment by dimitriBouteille** [comment]
@engcom-Bravo @engcom-Hotel Why some tests fails ? Same problem here https://github.com/magento/magento2/pull/39153

File: lib/internal/Magento/Framework/App/Config/ScopeConfigInterface.php [hunk 1]
```diff
@@ -17,14 +15,14 @@ interface ScopeConfigInterface
...
-    const SCOPE_TYPE_DEFAULT = 'default';
+    public const SCOPE_TYPE_DEFAULT = 'default';
 
     /**
      * Retrieve config value by path and scope.
      *
      * @param string $path The path through the tree of configuration values, e.g., 'general/store_information/name'
      * @param string $scopeType The scope to use to determine config value, e.g., 'store' or 'default'
-     * @param null|int|string $scopeCode
+     * @param null|int|string|\Magento\Store\Api\Data\StoreInterface $scopeCode
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/App/Config/ScopeConfigInterface.php]: It could be `\Magento\Framework\App\ScopeInterface` instead of `\Magento\Store\Api\Data\StoreInterface`

File: lib/internal/Magento/Framework/App/Config/ScopeConfigInterface.php [hunk 2]
```diff
@@ -34,7 +32,7 @@ public function getValue($path, $scopeType = ScopeConfigInterface::SCOPE_TYPE_DE
...
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/App/Config/ScopeConfigInterface.php]: Same here

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @dimitriBouteille,

Please refer to my below review comment

Thanks @engcom-Dash for highlighting the same.

Thanks

File: lib/internal/Magento/Framework/App/Config/ScopeConfigInterface.php (hunk 1 above)
Comment (dimitriBouteille) [reply lib/internal/Magento/Framework/App/Config/ScopeConfigInterface.php]: Perfect, thanks for your feedback :rocket:

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Manual testing is not required here, as this PR is only updating the doc block. Since the builds are failing, moving it to Extended Testing.

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, Functional Tests CE

**Comment by engcom-Dash** [comment]
@magento create issue

**Comment by engcom-Dash** [comment]
The Functional CE test failures are inconsistent in the last two builds and seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39199/a125ed7085d0b92289c951805b6e9521/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39199/f392145369943d85ff0af0463c0324f9/Functional/allure-report-ce/index.html#categories/ee9a7904470df46f41d453cf2e3cad02/b03e5f18341f5c1f/
image
