### PR TITLE
Invoice for an order that contains only one configurable product is not generated correctly

### LINKED ISSUE #31143: Invoice for an order that contains only one configurable product is not generated correctly
### Preconditions (*)
1. Magento ver. 2.3.5-p1
2. Magento 2.4-develop

### Steps to reproduce (*)
1. create a cart with exactly one configurable product
2. complete the order with any payment method
3. invoice the order from Admin (only if the invoice has not already been created)

### Expected result (*)
The invoice is treated as last invoice (\Magento\Sales\Model\Order\Invoice::isLast returns true)
e.g., invoice with simple product
Peek 2020-12-14 15-43

### Actual result (*)
The invoice is not treated as last invoice (\Magento\Sales\Model\Order\Invoice::isLast returns false)
Peek 2020-12-14 15-46

---
similar issue is https://github.com/magento/magento2/issues/22283
isLast should skip the dummy items to avoid the problem.

extra info: if the order contains extra fees (for example the costs of cash on delivery) taxes on these are not calculated in the total and the total due is greater than 0

### PR DESCRIPTION
**Pull request by namlier**
### Description (*)
When you placing exactly one configurable option two order items appears in order model - one of them is dummy, that just provides useful information about the order. Such kind of dummy items are defined as not the last in invoice model that brings us wrong flow of a total calculation.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31143

### Manual testing scenarios (*)
**Preconditions**
1. CE 2.4-develop version
2. Install extension module with feature which can add extra fee on order, for example - https://github.com/mageprince/magento2-paymentfee
3. Add a tax rule
4. Create configurable product
5. Add extra fee on orders, for example - Price type : fixed price, Payment method fee:
payment method code: "checkmo", fee amount: "30"
Calculate tax: yes
**Steps**
1. Place order with one of options of configurable product, so that the Tax Rule will apply
2. As Admin try create an Invoice

 **Expected result**
Extra payment fee created by the module includes the Tax from the Tax Rule.

 **Actual result**
Extra payment fee created by the module doesn't include the Tax from the Tax Rule

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

File: app/code/Magento/Sales/Model/Order/Invoice.php [hunk 1]
```diff
@@ -679,6 +679,11 @@ public function register()
     public function isLast()
     {
         foreach ($this->getAllItems() as $item) {
+            $orderItem = $item->getOrderItem();
```
Comment (engcom-Kilo) [inline app/code/Magento/Sales/Model/Order/Invoice.php:682]: Should be verified with PAT tests.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31472`.

**Comment by akgola** [comment]
@mastiuhin-olexandr  ,  same issue is coming in Report section where custom tax is not getting added even after fixing this by
app/code/Magento/Sales/Model/Order/Invoice.php .
could you please check it.
