### PR TITLE
Fix Wrong Exception on Cli run when Command Not found

### LINKED ISSUE #40006: Ensure that a single command failure logs the error (file or stderr) without stopping the execution of subsequent CLI commands.
https://github.com/magento/magento2/blob/597e991a9554695785250f11ccc27a0ef8120279/app/code/Magento/Deploy/Console/CommandList.php#L48-L54

### PR DESCRIPTION
**Pull request by Genaker**
Before Fix error on Cli run:

image

After : 

image
 

### Description (*)
If you have ever tried to run bin/magento and been greeted with the maddening: "There is no command found in the namespace"

you already know how opaque Magento (Adobe Commerce) can be when a single CLI command class is broken. One constructor typo, a missing dependency, or a bad module upgrade and—boom—the whole console goes dark. No stack-trace, no filename, no clue. You are left spelunking through logs or disabling modules by trial and error. More than 10 years Adobe is not able to fix this critical issue! I'm tired and submitted the PR. 

What My PR  tiny but vital quality-of-life improvement:

 - Catches the original exception thrown while Magento is assembling its command list.

 - Prints the real message and class name before the fallback “no command found” notice.

  - The change is only a few lines, but the impact is huge: you immediately see which command class failed and why, so you can fix the root cause in minutes instead of hours. 

Why every extension author & integrator should care:

 * Faster CI/CD – Broken modules fail loudly during automated builds; no more silent time-outs.

  * Happier merchants – Support teams pinpoint faulty third-party code instead of asking store owners for full backups.

   * Lean core – The patch touches only CLI bootstrap code; zero risk to storefront performance.

Thanks for backing real-world developer experience improvements—your click today could save countless debugging hundreds hours tomorrow!

Fixes #40006 

### Related Issue
[](https://github.com/magento/magento2/issues/40006#event-18569396117)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Just wonder if we can do a bit different approach - throw different type of exception when the command not found, and handle it differently. What do you think?

File: lib/internal/Magento/Framework/Console/Cli.php [hunk 1]
```diff
@@ -151,6 +178,11 @@ protected function getApplicationCommands()
     {
         $commands = [];
         try {
+            if (class_exists(\Magento\Setup\Console\CommandList::class)) {
+                $setupCommandList = new \Magento\Setup\Console\CommandList($this->serviceManager);
+                $commands = array_merge($commands, $setupCommandList->getCommands());
+            }
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Console/Cli.php]: Could you please explain, why this change is needed?

**Comment by Genaker** [comment]
We don't need these lines; it is probably due to a merge issue. You can
follow the logic. These lines don't change logic, just were touched by the
commit

**Comment by Genaker** [comment]
You can. The main issue is that we need to show which command failed, not
just the command that was not found. The best solution could be to allow
the execution of other commands and skip the command with an error.

File: lib/internal/Magento/Framework/Console/Cli.php (hunk 1 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Console/Cli.php]: From reply in https://github.com/magento/magento2/pull/40063#issuecomment-3083241783:
> We don't need these lines; it is probably due to a merge issue. You can
follow the logic. These lines don't change logic, just were touched by the
commit



These lines were added, so let's remove them if we don't need them

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi,
I've tried to debug a bit, and feels like the issue is coming from the masking original exception - if exception happened during loading list of the commands - we're just skipping it and trying to print the failure message after,  but command is trying to be executed.
Ref:

https://github.com/magento/magento2/blob/16c2c4a95c912b7b6e3f6e4a56bad68e3d752394/lib/internal/Magento/Framework/Console/Cli.php#L150-L169

This code was introduced long time ago in https://github.com/magento/magento2/commit/293ba1e141c95eb17cc18e2c246d12d2ed071cff 

I think this logic has to be changed - we should not hide the exception, but print it directly when it happens - just remove try-catch in the `getApplicationCommands` method.

This will result in having a clear exception at the beginning:
```
$ php bin/magento -vvv

In ClassReader.php line 34:
                                                                  
  [ReflectionException (-1)]                                      
  Class "Test\TEsctCli\Console\Command\TestWrong" does not exist  
                                                                  

Exception trace:
  at /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:34
 ReflectionClass->__construct() at /var/www/html/vendor/magento/framework/Code/Reader/ClassReader.php:34
 Magento\Framework\Code\Reader\ClassReader->getConstructor() at /var/www/html/vendor/magento/framework/ObjectManager/Definition/Runtime.php:50
 Magento\Framework\ObjectManager\Definition\Runtime->getParameters() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:48
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:73
 Magento\Framework\ObjectManager\ObjectManager->get() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:206
 Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:182
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /var/www/html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /var/www/html/vendor/magento/framework/ObjectManager/ObjectManager.php:59
 Magento\Framework\ObjectManager\ObjectManager->create() at /var/www/html/vendor/magento/framework/Console/Cli.php:156
 Magento\Framework\Console\Cli->getApplicationCommands() at /var/www/html/vendor/magento/framework/Console/Cli.php:137
 Magento\Framework\Console\Cli->getDefaultCommands() at /var/www/html/vendor/symfony/console/Application.php:1327
 Symfony\Component\Console\Application->init() at /var/www/html/vendor/symfony/console/Application.php:692
 Symfony\Component\Console\Application->find() at /var/www/html/vendor/symfony/console/Application.php:266
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/magento/framework/Console/Cli.php:118
 Magento\Framework\Console\Cli->doRun() at /var/www/html/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /var/www/html/bin/magento:23

```

What do you think about it?

**Comment by engcom-Dash** [comment]
Hello @jakwinkler 
Following up to check if you had a chance to review or provide any updates on this PR.

@ihor-sviziev @Genaker — since there hasn’t been any feedback for quite some time, could you please advise if we can proceed with closing this PR due to inactivity?

Thank you!

**Comment by Genaker** [comment]
Hi there,

Please do not close this Pull Request. The changes in PR #40063 are
essential for improving the Magento CLI debugging experience by providing
more informative exceptions when command initialization fails.

I understand the discussions around alternative approaches; however, the
current implementation significantly improves the masked error. I am ready
to address any further feedback to advance this PR.

This PR resolves a valid issue and should be merged, not closed due to
inactivity.

Thanks,
Yegor

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Genaker,

Thank you for your contribution!

I have reviewed the PR and your approach to solving the issue is good. However, I also agree with @ihor-sviziev's comment [here](https://github.com/magento/magento2/pull/40063#pullrequestreview-3029069591) about not masking the original exception.

I'd like to suggest a hybrid approach that provides the best of both solutions:

- Developer mode: Throw exceptions immediately (fail-fast for debugging)
- Production mode: Log errors and continue loading other commands (graceful degradation)

**Modify getVendorCommands() to capture individual failures:**
```
protected function getVendorCommands($objectManager)
{
    $commands = [];
    foreach (CommandLocator::getCommands() as $commandListClass) {
        if (!class_exists($commandListClass)) {
            continue;
        }
        
        try {
            $commands[] = $objectManager->create($commandListClass)->getCommands();
        } catch (\Exception $e) {
            // Store failure in class property
            $this->failedCommands[] = [
                'class' => $commandListClass,
                'error' => $e->getMessage(),
                'type' => get_class($e),
                'file' => $e->getFile() . ':' . $e->getLine()
            ];
            
            // Log the error
            $this->logger->error(
                sprintf('Failed to load command class %s: %s', $commandListClass, $e->getMessage()),
                ['exception' => $e, 'trace' => $e->getTraceAsString()]
            );
            
            // Developer mode: fail immediately
            if ($this->isDeveloperMode()) {
                throw $e;
            }
            
            // Production mode: continue
        }
    }
    
    return array_merge([], ...$commands);
}
```
Let me know your views.

Thank you

**Comment by Genaker** [comment]
Hi,

Thank you for reviewing the suggestion and providing your perspective.

I agree that the hybrid approach you outlined—throwing the original
exception immediately in developer mode and gracefully logging the error
while continuing in production mode—represents a significant improvement.
This solution perfectly balances the need for a "fail-fast" debugging
experience with production stability, which is highly desirable for the
Magento CLI.

The goal has always been to stop masking critical exceptions, and your
proposed modification to `getVendorCommands()` achieves this while ensuring
the CLI remains usable in a production environment even if a single command
fails to initialize. I believe this hybrid solution is superior to the
current PR implementation and the previous masked error.

Please go ahead and adopt this logic.
I don't have time now.

Thank you once again for your detailed feedback and assistance in moving
this PR toward a high-quality solution.

Yegor

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Console/Cli.php [hunk 2]
```diff
@@ -123,15 +137,57 @@ public function doRun(Console\Input\InputInterface $input, Console\Output\Output
...
+                        error_log($combinedErrorMessage);
+                    }
+                } else {
+                    // Production mode: command loading errors were already logged
+                    // The specific command user tried to run may not be available
+                    $warningMessage = "\n"
+                        . '<comment>Warning: Some commands failed to load due to errors.</comment>' . "\n"
+                        . '<comment>Check error logs (var/log/system.log) for details.</comment>' . "\n"
+                        . '<comment>The command you tried to run may not be available. '
+                        . 'Try running: bin/magento list</comment>' . "\n";
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Console/Cli.php]: I believe we should also use `PHP_EOL` here instead of `"\n"`, as is done above.

File: lib/internal/Magento/Framework/Console/Cli.php [hunk 3]
```diff
@@ -256,4 +400,125 @@ private function getCommandLoader(): Console\CommandLoader\CommandLoaderInterfac
...
+                    'Check system.log for details.'
+                );
+            } catch (\Exception $logException) {
+                // Logger failed, will show in terminal
+                $loggedToMagento = false;
+            }
+        }
+        
+        // Show actionable error in terminal (production mode)
+        $terminalMessage = "\n" . str_repeat('=', 80) . "\n";
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Console/Cli.php]: I believe we should also use `PHP_EOL` here and below instead of `"\n"`, as is done above.

File: lib/internal/Magento/Framework/Console/Cli.php [hunk 4]
```diff
@@ -150,24 +206,74 @@ protected function getDefaultCommands():array
...
+            'Failed to load %s: %s in %s:%d',
+            $commandType,
+            $e->getMessage(),
+            $e->getFile(),
+            $e->getLine()
+        );
+        
+        // Special handling for core commands failure - this is critical
+        if ($commandType === 'core Magento commands') {
+            $errorMessage .= "\n\nCRITICAL: Core Magento commands "
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Console/Cli.php]: I believe we should also use `PHP_EOL` here and below instead of `"\n"`, as is done above.

File: lib/internal/Magento/Framework/Console/Cli.php [hunk 5]
```diff
@@ -256,4 +400,125 @@ private function getCommandLoader(): Console\CommandLoader\CommandLoaderInterfac
...
+                );
+            } catch (\Exception $logException) {
+                // Logger failed, will show in terminal
+                $loggedToMagento = false;
+            }
+        }
+        
+        // Show actionable error in terminal (production mode)
+        $terminalMessage = "\n" . str_repeat('=', 80) . "\n";
+        $terminalMessage .= "⚠️  MAGENTO CLI ERROR (Production Mode)\n";
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Console/Cli.php]: Using emojis in error_log() messages might not be a best practice, especially if logs are parsed or consumed by external tools.

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @engcom-Hotel,
Please review my comments for this PR.

**Comment by engcom-Hotel** [comment]
Hello @Den4ik,

Thank you for the review!

I have made the asked changes. Requesting you to review.

@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@engcom-Hotel Thanks for update. I'll check it

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Review by Den4ik — APPROVED** [review]
@engcom-Hotel,
Changes looks good for me.

**Comment by Genaker** [comment]
What do you think about not failing all CLI commands on an error, but failing only the specific command that actually encounters the error?

**Comment by engcom-Bravo** [comment]
Hi @Genaker,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to Reproduce**


- Delete any usles 3-d party Cli Class or make fatal PHP error
- Run Cli command
- Run Console cache:flush


**Before:** :heavy_multiplication_x: 


Screenshot 2025-12-29 at 5 27 47 pm



**After:** :heavy_check_mark: 

Screenshot 2025-12-29 at 5 27 57 pm





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Static Tests
