### PR TITLE
Avoid lots of uncessary exceptions during layout XML merge loading

### LINKED ISSUE #39877: [Issue] Avoid lots of uncessary exceptions during layout XML merge loading
This issue is automatically created based on existing pull request: magento/magento2#37570: Avoid lots of uncessary exceptions during layout XML merge loading

---------
### Description

* Introduce a new function (for B/C compat we don't overwrite the protected _loadXmlString) to load and not throw an exception
* Use it in extract handlers -> no need to catch the exception any more

### Related Pull Requests

See also: https://github.com/justbetter/magento2-sentry/issues/113

### Fixed Issues (if relevant)
No magento issue created.

### Manual testing scenarios (*)
1. Install the sentry plugin
2. Have some invalid XML there
3. Exception is reported, even it is not necessary

### Reason

When using tools like Sentry, because of there inner workings, such exceptions still might be reported. While this is not exactly the root cause, it's always cleaner to not throw an exception and immediately catch it, if invalid cases can happen often.

This might even improve performance a bit and improves developer's experience.

### Remarks

There seems some invalid XML at that place in the code happen quite often - it might be also interesting to check if that can be avoided.

This is a simple, trivial change to the code and should not break anything, so hopefully this can get triaged quickly and without to much back-and-forth about the testing procedure :-)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [not applicable] All new or changed code is covered with unit/integration tests (if applicable)
 - [not applicable] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [waiting] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by amenk**
### Description

* Introduce a new function (for B/C compat we don't overwrite the protected _loadXmlString) to load and not throw an exception
* Use it in extract handlers -> no need to catch the exception any more

### Related Pull Requests

See also: https://github.com/justbetter/magento2-sentry/issues/113

### Fixed Issues (if relevant)
No magento issue created.

### Manual testing scenarios (*)
1. Install the sentry plugin
2. Have some invalid XML there
3. Exception is reported, even it is not necessary

### Reason

When using tools like Sentry, because of there inner workings, such exceptions still might be reported. While this is not exactly the root cause, it's always cleaner to not throw an exception and immediately catch it, if invalid cases can happen often.

This might even improve performance a bit and improves developer's experience.

### Remarks

There seems some invalid XML at that place in the code happen quite often - it might be also interesting to check if that can be avoided.

This is a simple, trivial change to the code and should not break anything, so hopefully this can get triaged quickly and without to much back-and-forth about the testing procedure :-)

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [not applicable] All new or changed code is covered with unit/integration tests (if applicable)
 - [not applicable] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [waiting] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39877: Avoid lots of uncessary exceptions during layout XML merge loading

### CODE REVIEW

**Comment by amenk** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @amenk,

Thanks for the contribution!

Please fix the failed static test and also let us know if we can reproduce this original issue without using any 3rd party extensions. 

Also please let us know which kind of exceptions are not generating after this fix.

Thanks

**Comment by amenk** [comment]
Almost two years later I am a bit out of context of this.

The issue was mostly visible with the sentry plugin.

Feel free to take over and fix the static tests ... :-) Thank you!

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento create issue

**Comment by engcom-Dash** [comment]
@engcom-Hotel I have fixed static test cases. Could you please review it?

Thanks

File: lib/internal/Magento/Framework/View/Model/Layout/Merge.php [hunk 1]
```diff
@@ -564,6 +564,21 @@ protected function _loadXmlString($xmlString)
         return simplexml_load_string($xmlString, \Magento\Framework\View\Layout\Element::class);
     }
 
+    /**
+     * Return object representation of XML string, or false, if XML was invalid
+     *
+     * @param string $xmlString
+     * @return \SimpleXMLElement
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/View/Model/Layout/Merge.php]: The @return annotation here does not align with its possible return values. `simplexml_load_string` can return false if the XML is invalid as well

File: lib/internal/Magento/Framework/View/Model/Layout/Merge.php [hunk 2]
```diff
@@ -564,6 +564,21 @@ protected function _loadXmlString($xmlString)
...
+     */
+    protected function _safeLoadXmlString($xmlString)
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/View/Model/Layout/Merge.php]: Add strict type declarations to _safeLoadXmlString

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @engcom-Dash,

Please refer to the below review comments.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/View/Model/Layout/Merge.php (hunk 1 above)
Comment (engcom-Dash) [reply lib/internal/Magento/Framework/View/Model/Layout/Merge.php]: added @return \SimpleXMLElement | false in return type

File: lib/internal/Magento/Framework/View/Model/Layout/Merge.php (hunk 2 above)
Comment (engcom-Dash) [reply lib/internal/Magento/Framework/View/Model/Layout/Merge.php]: added strict type declaration

**Comment by engcom-Dash** [comment]
@engcom-Hotel suggested changes has been made hence moving this back to pending review. could you please reviwe it once ?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by amenk** [comment]
@engcom-Dash Thank you for finalizing this!
