### PR TITLE
Fix accepted types for escaper methods

### LINKED ISSUE #40012: Unclear/invalid return types in Magento\Framework\Escaper
### Summary

When running `phpstan` against `phtml` files on max level, the proper use of the Escaper can cause all sorts of errors due to the poor return types in this class.

First: Almost every method takes a value that can be cast to a string, but all declare that the type is `string`.  This methods should document that it is a type equivalent to `\Stringable|scalar` instead of `string`.

Second: escapeHtml outputs either an array or a string, which causes typesafety concerns when having code as simple as `<?= $escaper->escapeHtml($stringVariable) ?>` since `phpstan` knows `escapeHtml` could return an array.  To fix this, we should instruct `phpstan` under what circumstances an array might be returned.  For example: `@phpstan-return ($data is array ? string[] : string)`

To fix this in my own code, I've ended up having to stub out the Escaper class (see https://github.com/bitExpert/phpstan-magento/issues/343 )

### Examples

(see summary)

### Proposed solution

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)
When performing static analysis using phpstan on level 5 or higher on (custom) phtml files, we often run into false positives that have to do with the kind of data we send to one of the many `escape` methods.
Also the return type of `escapeHtml` was not clear as it can return a `string` or `array` depending on the type you send to the method.

We fix that in this PR.

Many thanks to @navarr who came up this suggested solution in scope of https://github.com/bitExpert/phpstan-magento/pull/346

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/40012

### Manual testing scenarios (*)
See https://github.com/magento/magento2/issues/40012 & https://github.com/bitExpert/phpstan-magento/pull/346
Maybe I'll find more time later to work out a good example, but I don't have the time at the moment.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/History.php [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2013 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Sales/Block/Adminhtml/Order/View/History.php:3]:
```suggestion
 * Copyright 2011 Adobe
```

File: app/code/Magento/Sales/Helper/Admin.php [hunk 2]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2013 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Sales/Helper/Admin.php:3]:
```suggestion
 * Copyright 2011 Adobe
```

File: lib/internal/Magento/Framework/Escaper.php [hunk 3]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2014 Adobe
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Escaper.php:3]:
```suggestion
 * Copyright 2013 Adobe
```

File: lib/internal/Magento/Framework/View/Element/AbstractBlock.php [hunk 4]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2014 Adobe
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/View/Element/AbstractBlock.php:3]:
```suggestion
 * Copyright 2011 Adobe
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @hostep,

Thanks for the contribution!

Please refer to the below review comment. The failed functional test seems flaky to me, hence re-running the test.

For SVC failure we have created a [JIRA](https://jira.corp.adobe.com/browse/AC-15299) for approval. Please fix the review comment, so that we can proceed for the SVC approval.

Thanks

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/History.php (hunk 1 above)
Comment (hostep) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/History.php:3]: @engcom-Hotel: it should be 2013, not 2011. Looking at the git history, github is _guessing_ it got renamed from `app/code/core/Mage/Adminhtml/Model/System/Config/Backend/Price/Scope.php ` to `app/code/core/Mage/Adminhtml/Block/Tax/Rate/ImportExportHeader.php` in 2011 and then to `app/code/Magento/Adminhtml/Block/Sales/Order/View/History.php` in 2013

But going from a PriceScopeBackendConfig to a TaxRateImportExportHeader to a SalesOrderViewHistoryBlock makes no sense to me. So in my opinion it should be 2013.

Can you double check this again?

I didn't check the other files, only this one...

Comment (hostep) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/History.php:3]: If you really believe it should be 2011, go ahead and change it yourself because I'm unavailable for the next 2 weeks, since I'll go on holiday. Thanks!

Comment (engcom-Hotel) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/History.php:3]: Hello @hostep,

Thanks for the update!

I have checked for all the files from this PR, I think we are good to go with the current years. Hence approving the PR.

Thanks again for the clarification.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
JIRA approval is required for SVC failure, hence moving it to pending approval bucket.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Charlie** [comment]
As mentioned [here](https://github.com/magento/magento2/pull/40114#issuecomment-3322555990), we have got all the approvals for the SVC approval [JIRA](https://jira.corp.adobe.com/browse/AC-15299).

The Functional B2B failures in recent 2 builds are not consistent. Few of the test failures for the functional EE failures are not consistent in recent 2 builds, the consistent one is a known issue.

The non consistent seems to be flaky. They are neither failing because of the PR nor part of the PR. Hence moving this PR to Merge In Progress.

**Functional B2B: Run 1**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40114/2890791519a23e99e90cd195e4d71530/Functional/allure-report-b2b/index.html#categories

image


**Run 2**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40114/2890791519a23e99e90cd195e4d71530/Functional/allure-report-b2b/index.html#categories

image


**Functional EE: Run 1**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40114/dda84aa09a25cdc78ce08ebed7d5761d/Functional/allure-report-ee/index.html#categories/3418275ac42b7ca8566f7871b42bcde6/ce5f845fa5c766a6/

image



**Run 2**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/40114/8ecae91656ce427b7d53db67137bd8d7/Functional/allure-report-ee/index.html#categories/bdbf199525818fae7a8651db9eafe741

image

Known Issue:
[ACQE-8655](https://jira.corp.adobe.com/browse/ACQE-8655): AdminRmaSettingsConfigurationTest
