### PR TITLE
magento/magento2#38455: Fixed

### LINKED ISSUE #38455: Wrong Order total, the round is not applied to the price calculation.
### Preconditions and environment

- Magento version: 2.4.6-p3
- Php version: 8.1
- Tax Rate configuration (22%)
taxrate-config
- Tax configuration
tax-config
- Discount configuration (10%)
discount-config
- product 1 (hat)
special price 733.61
- product 2 (jacket)
special price 569.67

### Steps to reproduce

Two ways to reproduce the error:
Method 1:
1- add product 1 * 3 to the cart
2- add product 2 * 2 to the cart
3- go to the checkout 
4- apply the discount and use the country for the tax to be applied
5- create order

Method 2:
1- add product 2 * 2 to the cart
2- add product 1 * 3 to the cart
3- go to the checkout 
4- apply the discount and use the country for the tax to be applied
5- create order

### Expected result

The function round should be applied when calculating the price_after_discount, discount_amount and taxes amount.
the actual total of the order should be 3667,52.

### Actual result

Magento not doing the round function when calculating price_after_discount, discount_amount and taxes amount for the second product added to the cart.
resulting in total 3667,51 when reproducing the error using method 1 and 3667,5 when reproducing the error using method 2.

hat-jacket

jacket-hat

### Additional information

Here is the calculation that magento do, column (B+C) for first order, column (D+E) for the second order.
the cells with background yellow where magento miscalculate the price (possibly by not rounding the price).
the correct total is the result of the column (B+E) which are the correct calculations and matches the manual calculations.
calculations

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by YuriyYavorskiy**
- the mistake was that the amount for non-taxes after the discount came with incorrect rounding

### Description (*)
Hello, as a result of the tests, it turned out that taxes are calculated correctly and the problem is not with them. When the discount was calculated, it came with different roundings in different cases. Rounding was assigned by Magento rules

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38455

### Manual testing scenarios (*)

To test, you need to repeat everything that was in the task, now the result of the order is correct. checked many times with different sequences

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by YuriyYavorskiy** [comment]
> * the mistake was that the amount for non-taxes after the discount came with incorrect rounding
> 
> ### Description (*)
> Hello, as a result of the tests, it turned out that taxes are calculated correctly and the problem is not with them. When the discount was calculated, it came with different roundings in different cases. Rounding was assigned by Magento rules
> 
> ### Related Pull Requests
> ### Fixed Issues (if relevant)
> 1. Fixes [Wrong Order total, the round is not applied to the price calculation. #38455](https://github.com/magento/magento2/issues/38455)
> 
> ### Manual testing scenarios (*)
> To test, you need to repeat everything that was in the task, now the result of the order is correct. checked many times with different sequences
> 
> ### Questions or comments
> ### Contribution checklist (*)
> * [ ]  Pull request has a meaningful description of its purpose
> * [ ]  All commits are accompanied by meaningful commit messages
> * [ ]  All new or changed code is covered with unit/integration tests (if applicable)
> * [ ]  README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
> * [ ]  All automated tests passed successfully (all builds are green)

image

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @YuriyYavorskiy,

Thanks for the contribution!

Please have a look into the failed Integration, Static, Unit tests, it seems they are failing due to the code changes, kindly fix those.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @YuriyYavorskiy,

Thanks for the contribution!

Please fix the failed static, integration and unit test, it seems they are failing due to the code changes, other functional tests failures seems flaky to me. Rerunning the functional tests.

Thanks

**Comment by YuriyYavorskiy** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@YuriyYavorskiy Thank you for contribution!

I wanted to check if you are working on the review comment https://github.com/magento/magento2/pull/39687#pullrequestreview-2789852278 . If not, Can I take care of them? Just let me know what works best for you.

**Comment by YuriyYavorskiy** [comment]
> @YuriyYavorskiy Thank you for contribution!
> 
> I wanted to check if you are working on the review comment [#39687 (review)](https://github.com/magento/magento2/pull/39687#pullrequestreview-2789852278) . If not, Can I take care of them? Just let me know what works best for you.

Hi! Yes

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hi @YuriyYavorskiy & @engcom-Hotel 

I noticed that  round() of Magento\Framework\Pricing\PriceCurrencyInterface is deprecated. I have addressed this by replacing it with number format ensuring that it fixes the issue.

Also, failing unit, static & integration tests has been fixed. In the recent build failing unit & integration tests are not related to the code changes done in this PR and seems flaky to me hence moving this PR in Pending Review. Could you please review the PR ?

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/SalesRule/Model/Rule/Action/Discount/ByPercent.php [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/SalesRule/Model/Rule/Action/Discount/ByPercent.php]:
```suggestion
 * Copyright 2014 Adobe
```

File: app/code/Magento/SalesRule/Model/Rule/Action/Discount/ByPercent.php [hunk 2]
```diff
@@ -60,11 +60,17 @@ protected function _calculate($rule, $item, $qty, $rulePercent)
         $baseItemOriginalPrice = $this->validator->getItemBaseOriginalPrice($item);
 
         $_rulePct = $rulePercent / 100;
-        $discountData->setAmount(($qty * $itemPrice - $item->getDiscountAmount()) * $_rulePct);
-        $discountData->setBaseAmount(($qty * $baseItemPrice - $item->getBaseDiscountAmount()) * $_rulePct);
-        $discountData->setOriginalAmount(($qty * $itemOriginalPrice - $item->getDiscountAmount()) * $_rulePct);
+        $discountData->setAmount(
+            number_format((($qty * $itemPrice - $item->getDiscountAmount()) * $_rulePct), 2, '.', '')
```
Comment (engcom-Hotel) [inline app/code/Magento/SalesRule/Model/Rule/Action/Discount/ByPercent.php]: As discussed I think we can use the `round` method here

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @engcom-Dash & @YuriyYavorskiy,

Please refer to the below review comments.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@engcom-Hotel review comments has been fixed. Could you please review it ?

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Dash** [comment]
One of the consistent Functional B2B test failure is a known issue and JIRA is present for the same. Other test failures are inconsistent and seems to be flaky. They are not related to this PR nor part of PR. 

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39687/29abe8dce3d6efc229b9eaee9fab7b64/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39687/7751779d09061327b88a7522c3048d15/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Known Issue: AdminDeleteCatalogPriceRuleEntityFromConfigurableProductTest [ACQE-7945](https://jira.corp.adobe.com/browse/ACQE-7945)

Hence moving this PR in Merge In Progress.
