### PR TITLE
#26121 - special price & tier price are coming in base currency

### LINKED ISSUE #26121: special price & tier price are coming in base currency
In Graphql fetch data for special price & tier prices in products query. The values come always in base currency.
### Preconditions (*)
1. Magento based on '2.4-develop' branch
2. Have a product created with name "Beginner's Yoga" (or refer to the same named product that becomes available with sample data) and set the following prices
    a. price: 6 
    b. Advanced pricing > special price: 5 
    c. Advanced Pricing > Catalog and Tier Price, for all websites and all groups, fixed type price, 
        - for qty 2 price 4
        - for qty 3 price 3 

3. Add new store view with code "eur_view"
4. Navigate to Store -> Settings -> Configuration -> General -> Currency Setup and allow EURO in **Allowed Currencies** and Save Configuration
5.  Change the Scope to the second Eur View and set **Default Display Currency** to Euro
6. Ensure there are currency rates available (e.g. on frontend catalog if the store view is switched price would change from 6 to 4.24 -> indicating that the USD -> EUR rate is 1.415)

### Steps to reproduce (*)

1. Set header "Store = default" and execute this query
`query{
products(search: "Beginner's Yoga"){
  total_count
	items {    
		name
     price_range {
       minimum_price {
         regular_price {
          currency
          value
        }
        final_price {
          currency
          value
        }
      } 
     }
     special_price
     price_tiers {
     	final_price {
        currency
        value
      }
      quantity
     }
		sku
	}
    }
}`

2. Prices now are expected in Default Store view in USD, response should look like
`        {
          "name": "Beginner's Yoga",
          "price_range": {
            "minimum_price": {
              "regular_price": {
                "currency": "USD",
                "value": 6
              },
              "final_price": {
                "currency": "USD",
                "value": 5
              }
            }
          },
          "special_price": 5,
          "price_tiers": [
            {
              "final_price": {
                "currency": "USD",
                "value": 4
              },
              "quantity": 2
            },
            {
              "final_price": {
                "currency": "USD",
                "value": 3
              },
              "quantity": 3
            }
          ],
          "sku": "240-LV04"
        }`

3.  Set header "Store = eur_view" and execute the query again
4. Prices now are expected in Eur View in EUR currency, response should look like
`        {
          "name": "Beginner's Yoga",
          "price_range": {
            "minimum_price": {
              "regular_price": {
                "currency": "EUR",
                "value": 4.24
              },
              "final_price": {
                "currency": "EUR",
                "value": 3.53
              }
            }
          },
          "special_price": 5,
          "price_tiers": [
            {
              "final_price": {
                "currency": "EUR",
                "value": 4
              },
              "quantity": 2
            },
            {
              "final_price": {
                "currency": "EUR",
                "value": 3
              },
              "quantity": 3
            }
          ],
          "sku": "240-LV04"
        }`

Observe how the `regular_price.minimum_price` and `regular_price.final_price` have changed its value, but not the `special_price` or the values respectively for the `price_tiers`

### Expected result (*)
1. `special_price` should display values corrected by the USD->EUR rate (E.g. something like 3.53)
2. `price_tiers.final_price.value` should display values corrected by the USD->EUR rate

### Actual result (*)
1. `special_price` still displays 5
2. `price_tiers.final_price.value` is still displayed in USD and displays 4 for qty 2, and 3 for qty 3

### PR DESCRIPTION
**Pull request by pmarjan**
Collect store specific value for store specific currecny when querying products special_price and price_tiers

### Description (*)
Solves for https://github.com/magento/magento2/issues/26121

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pmarjan** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+namespace Magento\CatalogGraphQl\Model\Resolver\Product;
+
+use Magento\Framework\GraphQl\Config\Element\Field;
+use Magento\Framework\GraphQl\Query\Resolver\ContextInterface;
+use Magento\Framework\GraphQl\Query\Resolver\Value;
+use Magento\Framework\GraphQl\Query\ResolverInterface;
+use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
+use Magento\Catalog\Pricing\Price\SpecialPrice as PricingSpecialPrice;
+
+class SpecialPrice implements ResolverInterface
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php:19]: Class requires a short description

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+    /**
+     * Fetches the data from persistence models and format it according to the GraphQL schema.
+     *
+     * @param \Magento\Framework\GraphQl\Config\Element\Field $field
+     * @param ContextInterface $context
+     * @param ResolveInfo $info
+     * @param array|null $value
+     * @param array|null $args
+     * @return mixed|Value
+     * @throws \Exception
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php]: This should not throw \Exception. Resolvers should only throw graphql specific exceptions

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+     */public function resolve(Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php]: look like the comment closing tag is on same line as function

**Review by danielrenaud — CHANGES_REQUESTED** [review]
Can you please update or add test automated tests to cover these changes.

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+use Magento\Framework\GraphQl\Query\Resolver\ContextInterface;
+use Magento\Framework\GraphQl\Query\Resolver\Value;
+use Magento\Framework\GraphQl\Query\ResolverInterface;
+use Magento\Framework\GraphQl\Schema\Type\ResolveInfo;
+use Magento\Catalog\Pricing\Price\SpecialPrice as PricingSpecialPrice;
+
+class SpecialPrice implements ResolverInterface
+{
+    /**
+     * Fetches the data from persistence models and format it according to the GraphQL schema.
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php]: Fetch the data (Imperative, Fetches would be descriptive)

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+     *
+     * @param \Magento\Framework\GraphQl\Config\Element\Field $field
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php]: move FQDN to use statement

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php (hunk 3 above)
Comment (cpartica) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php]: static tests fail, some params are not used

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@cpartica all points from above should be addressed now. Also, the resolvers for special price and tier prices are supported now by api-functional tests that specifically query for a second store that has a display currency that comes with some rate compared to the base currency.

File: app/code/Magento/Catalog/Model/Product/Type/Price.php [hunk 6]
```diff
@@ -368,10 +368,33 @@ protected function getAllCustomerGroupsId()
...
+        return $this->buildProductTierPriceInterfaceObjects($tierPricesRaw);
+    }
+
+    /**
+     * Return ProductTierPriceInterface[] given raw tier prices array
+     *
+     * @param array $tierPricesRaw
+     * @return \Magento\Catalog\Api\Data\ProductTierPriceInterface[]
+     */
+    public function transformTierPrices($tierPricesRaw)
```
Comment (danielrenaud) [inline app/code/Magento/Catalog/Model/Product/Type/Price.php]: Adding a public method to an "@api" class is a backwards incompatible change, that is best avoided.

File: app/code/Magento/CatalogCustomerGraphQl/Pricing/Price/TierPrice.php [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+
+namespace Magento\CatalogCustomerGraphQl\Pricing\Price;
+
+use Magento\Catalog\Model\Product;
+use Magento\Customer\Api\GroupManagementInterface;
+use Magento\Framework\Pricing\Adjustment\CalculatorInterface;
+use Magento\Framework\Pricing\PriceCurrencyInterface;
+use Magento\Framework\App\ObjectManager;
+
+class TierPrice extends \Magento\Catalog\Pricing\Price\TierPrice
```
Comment (danielrenaud) [inline app/code/Magento/CatalogCustomerGraphQl/Pricing/Price/TierPrice.php]: We should avoid doing extension in this way.
I necessary it may be better to add customerGroupId as an optional param for methods, and falling back to the old mechanism when not provided

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/Product/Price/Tiers.php [hunk 8]
```diff
@@ -97,7 +115,23 @@ public function getProductTierPrices($productId): ?array
         if (empty($this->products[$productId])) {
             return null;
         }
-        return $this->products[$productId]->getTierPrices();
+
```
Comment (danielrenaud) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/Product/Price/Tiers.php]: Is there a reason that the original Price::getTierPrices method does not for us here?

**Review by danielrenaud — CHANGES_REQUESTED** [review]
I left some comments that should be addressed, but we can discuss if anything is unclear

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/Product/Price/Tiers.php (hunk 8 above)
Comment (pmarjan) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/Product/Price/Tiers.php]: this original Price::getTierPrices actually loads always in base currency not minding the current store selected currency.
Now, trying to see what can be done about it - maybe this method can be improved.

File: app/code/Magento/Catalog/Model/Product/Type/Price.php (hunk 6 above)
Comment (cpartica) [reply app/code/Magento/Catalog/Model/Product/Type/Price.php]: I tink the alternative is to extract \Magento\Catalog\Model\Product\Type\Price::buildProductTierPriceInterfaceObjects and \Magento\Catalog\Model\Product\Type\Price::getWebsiteForPriceScope into another class..
we can deprecate getWebsiteForPriceScope and buildProductTierPriceInterfaceObjects

Later in 2.5.0 we can delete them.
in 2.4.1 in theory we can't even add this new class to the constructor with "= null" Backward compatible way unless we have an approval. we can try.
Anyway either that or code duplication.

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+{
+    /**
+     * @inheritdoc
+     */
+    public function resolve(Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
+    {
+        /** @var \Magento\Catalog\Model\Product $product */
+        $product = $value['model'];
+        /** @var PricingSpecialPrice $specialPrice */
+        $specialPrice = $product->getPriceInfo()->getPrice(PricingSpecialPrice::PRICE_CODE);
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php:29]: you already know how to get here customerGroup, so use it here to get the price you want, pass it by param

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Model/Product/Type/Price.php [hunk 10]
```diff
@@ -368,10 +368,33 @@ protected function getAllCustomerGroupsId()
...
+    {
+        return $this->buildProductTierPriceInterfaceObjects($tierPricesRaw);
+    }
+
+    /**
+     * Return ProductTierPriceInterface[] given raw tier prices array
+     *
+     * @param array $tierPricesRaw
+     * @return \Magento\Catalog\Api\Data\ProductTierPriceInterface[]
```
Comment (cpartica) [inline app/code/Magento/Catalog/Model/Product/Type/Price.php]: can you move this to use?

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+ * Resolver for Special Price
+ */
+class SpecialPrice implements ResolverInterface
+{
+    /**
+     * @inheritdoc
+     */
+    public function resolve(Field $field, $context, ResolveInfo $info, array $value = null, array $args = null)
+    {
+        /** @var \Magento\Catalog\Model\Product $product */
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php]: use product interface

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Pricing/Price/TierPrice.php (hunk 7 above)
Comment (pmarjan) [reply app/code/Magento/CatalogCustomerGraphQl/Pricing/Price/TierPrice.php]: I remember, we cannot use \Magento\Catalog\Pricing\Price\TierPrice directly (even if we would apply proposed chances that would properly set the customer group).

Reason is that the mess detector test will fail with
`The class Magento\Catalog\Pricing\Price\TierPrice uses sessions or cookies while not being a part of HTML Presentation layer`
Unfortunately, this class has the session obsolete and not used at all, but still, cannot be directly called in graphql area.

Anyway, my latest commit bypasses this idea completely, and this should not be an issue anymore.

File: app/code/Magento/Catalog/Model/Product/Type/Price.php (hunk 6 above)
Comment (pmarjan) [reply app/code/Magento/Catalog/Model/Product/Type/Price.php]: For this purpose, created now is Magento\Catalog\Model\Product\Price\TierPriceBuilder.

**Comment by pmarjan** [comment]
@cpartica @danielrenaud 
all remarks are addressed, PR is ready for new re-review

**Comment by pmarjan** [comment]
@magento run all tests

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 12]
```diff
@@ -0,0 +1,230 @@
...
+    {
+        $this->objectManager = Bootstrap::getObjectManager();
+    }
+
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/product_simple.php
+     */
+    public function testAllGroups()
+    {
+        /** @var string $productSku */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]:
```suggestion
```
Remove all unnecessary @var annotations

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 13]
```diff
@@ -0,0 +1,230 @@
...
+        $productSku = 'simple';
+        /** @var string $query */
+        $query = $this->getProductSearchQuery($productSku);
+
+        $response = $this->graphQlQuery($query);
+
+        $itemTiers = $response['products']['items'][0]['price_tiers'];
+        $this->assertEquals(5, sizeof($itemTiers));
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: You can use assertCount()

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 14]
```diff
@@ -0,0 +1,230 @@
...
+}
+QUERY;
+    }
+
+    /**
+     * @param string $username
+     * @param string $password
+     * @return array
+     */
+    private function getHeaderAuthorization(string $username, string $password): array
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: Please use \Magento\GraphQl\GetCustomerAuthenticationHeader instead

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 15]
```diff
@@ -0,0 +1,230 @@
...
+     */
+    public function testLoggedInCustomer()
+    {
+        /** @var string $productSku */
+        $productSku = 'simple';
+        /** @var ProductRepositoryInterface $productRepository */
+        $productRepository = $this->objectManager->get(ProductRepositoryInterface::class);
+        /** @var Product $product */
+        $product = $productRepository->get($productSku, false, null, true);
+        $tierPriceData =[
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: data changes should be done in fixtures

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 16]
```diff
@@ -0,0 +1,230 @@
...
+        $query = $this->getProductSearchQuery($productSku);
+        $response = $this->graphQlQuery(
+            $query,
+            [],
+            '',
+            $this->getHeaderAuthorization('customer@example.com', 'password')
+        );
+
+        $itemTiers = $response['products']['items'][0]['price_tiers'];
+        $this->assertEquals(3, sizeof($itemTiers));
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: use assertCount()

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 17]
```diff
@@ -0,0 +1,230 @@
...
+    }
+
+    /**
+     * @magentoApiDataFixture Magento/Store/_files/second_store_with_second_currency.php
+     * @magentoApiDataFixture Magento/Customer/_files/customer.php
+     * @magentoApiDataFixture Magento/Catalog/_files/product_simple.php
+     */
+    public function testSecondStoreViewWithCurrencyRate()
+    {
+        /** @var string $storeViewCode */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]:
```suggestion
```
Remove all unnecessary @var annotations

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 18]
```diff
@@ -0,0 +1,230 @@
...
+            [
+                'customer_group_id' => 2,
+                'percentage_value'=> null,
+                'qty'=> 3,
+                'value'=> 8
+            ]
+        ];
+
+        $this->saveTierPrices($product, $tierPriceData);
+        /** @var string $query */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]:
```suggestion
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 19]
```diff
@@ -0,0 +1,230 @@
...
+        $storeViewCode = 'fixture_second_store';
+        /** @var StoreRepositoryInterface $storeRepository */
+        $storeRepository = $this->objectManager->get(StoreRepositoryInterface::class);
+        /** @var float $rate */
+        $rate = $storeRepository->get($storeViewCode)->getCurrentCurrencyRate();
+        /** @var string $productSku */
+        $productSku = 'simple';
+        /** @var string $query */
+        $query = $this->getProductSearchQuery($productSku);
+        /** @var array $headers */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]:
```suggestion
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 20]
```diff
@@ -0,0 +1,230 @@
...
+        $this->assertEquals(round(8 * $rate, 2), $this->getValueForQuantity(2, $itemTiers));
+        $this->assertEquals(round(5 * $rate, 2), $this->getValueForQuantity(5, $itemTiers));
+    }
+
+    /**
+     * @param float $quantity
+     * @param array $tiers
+     * @return float
+     */
+    private function getValueForQuantity(float $quantity, array $tiers)
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: Please add short description for utility methods

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 21]
```diff
@@ -0,0 +1,230 @@
...
+
+    /**
+     * @param string $productSku
+     * @return string
+     */
+    private function getProductSearchQuery(string $productSku): string
+    {
+        return <<<QUERY
+{
+  products(search: "{$productSku}") {
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: It might be safer to use "filter sku equals" to make sure you get an exact match

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/SpecialPriceTest.php [hunk 22]
```diff
@@ -0,0 +1,99 @@
...
+    {
+        $this->objectManager = Bootstrap::getObjectManager();
+    }
+
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/product_special_price.php
+     */
+    public function testSpecialPrice()
+    {
+        /** @var string $productSku */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/SpecialPriceTest.php]:
```suggestion
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/SpecialPriceTest.php [hunk 23]
```diff
@@ -0,0 +1,99 @@
...
+        $productSku = 'simple';
+        /** @var string $query */
+        $query = $this->getProductSearchQuery($productSku);
+
+        $response = $this->graphQlQuery($query);
+
+        /** @var float $specialPrice */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/SpecialPriceTest.php]:
```suggestion
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/SpecialPriceTest.php [hunk 24]
```diff
@@ -0,0 +1,99 @@
...
+    }
+
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/product_special_price.php
+     */
+    public function testSpecialPrice()
+    {
+        /** @var string $productSku */
+        $productSku = 'simple';
+        /** @var string $query */
```
Comment (danielrenaud) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/SpecialPriceTest.php]:
```suggestion
```

**Review by danielrenaud — CHANGES_REQUESTED** [review]
Functionality looks good, just some cleanup comments for the tests

**Comment by pmarjan** [comment]
@magento run all tests

**Review by danielrenaud — APPROVED** [review]
Nice work!
