### PR TITLE
MC-38592 Fixed load regions for scope

### LINKED ISSUE #30577: Can't place order on admin: "regionId" is required
### Preconditions

Magento 2.4-develop;
Magento 2.3.6;

2. Two websites;
3. Disable all countries for the default scope (General > Countries > Allow);
4. Enable `United States` on one website (General > Countries > Allow);

### Steps to reproduce

1. Go to Admin > Sales > Orders > Create order;
2. Select the website used on Preconditions step 4;
3. Add a product, fill the addresses using `United States` as country;
    Note that the region field is a text field instead of a dropdown with the states
4. Fill the payment method and shipping method and place the order;

### Expected result

1. Order is placed successfully;

### Actual result

1. Error `Please check the shipping address information. "regionId" is required. Enter and try again.` is shown and the order is not placed.

Screenshot from 2020-10-21 15-11-51

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by bogutskyy**
### Description (*)
Currently, if different scopes have different allowed countries, then can be issue on address forms. One of issue described in #30577: new order can not be created from admin. Another issue, which I found, on customer address edit page, when for US doesn't appear states dropdown.
image
I fixed regions loading depending on current scope. 

### Related Pull Requests
No related PRs

### Fixed Issues (if relevant)
1. Fixes magento/magento2#30577

### Manual testing scenarios (*)
See magento/magento2#30577

### Questions or comments
Looks like directory helper has been broken after fix in ticket MC-33168. Unfortunately I don't know what the problem was in MC-33168, but after code changes investigation I guess it was issue, when scope present in request params. Not sure the fix of MC-33168 was correct, maybe logic of current scope determination should be moved from **app/code/Magento/Directory/Helper/Data.php** to **app/code/Magento/Store/Model/StoreResolver.php**.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by vveb-developer** [comment]
@magento run all tests

**Comment by bogutskyy** [comment]
@magento run all tests

File: app/code/Magento/Directory/Helper/Data.php [hunk 1]
```diff
@@ -190,8 +190,8 @@ public function getRegionJson()
         \Magento\Framework\Profiler::start('TEST: ' . __METHOD__, ['group' => 'TEST', 'method' => __METHOD__]);
         if (!$this->_regionJson) {
             $scope = $this->getCurrentScope();
-            $scopeKey = $scope['value'] ? '_' . implode('_', $scope) : null;
-            $cacheKey = 'DIRECTORY_REGIONS_JSON_STORE' . $scopeKey;
+            $scopeKey = $scope['value'] ? '_' . implode('_', $scope) : '';
+            $cacheKey = 'DIRECTORY_REGIONS_JSON' . $scopeKey;
```
Comment (gabrieldagama) [inline app/code/Magento/Directory/Helper/Data.php]: Can you give more details on why this change here is relevant?

File: app/code/Magento/Directory/Helper/Data.php [hunk 2]
```diff
@@ -406,14 +406,21 @@ public function getWeightUnit()
      * Get current scope from request
      *
      * @return array
+     * @throws \Magento\Framework\Exception\NoSuchEntityException
      */
     private function getCurrentScope(): array
```
Comment (gabrieldagama) [inline app/code/Magento/Directory/Helper/Data.php]: This method has as a goal (as described on the PHP doc block) to get the current scope from the request, I'm not sure that such change makes sense, maybe we should look at the problem from the request perspective?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @bogutskyy, thanks for contributing! Can you have a look at my comments below? Also, can you have a look at the failed tests and fix them?

Thank you!

File: app/code/Magento/Directory/Helper/Data.php (hunk 1 above)
Comment (bogutskyy) [reply app/code/Magento/Directory/Helper/Data.php]: Doesn't make sense to have string **_STORE** in cache key template, because `$scope['type']` already contains scope type. In result currently cache key for store takes value **DIRECTORY_REGIONS_JSON_STORE_STORE_1**.

File: app/code/Magento/Directory/Helper/Data.php (hunk 2 above)
Comment (bogutskyy) [reply app/code/Magento/Directory/Helper/Data.php]: Method getCurrentScope has been added in commit 2b4cfab, ticket MC-33168, and this change produced issue #30577. tbh, my change looks like quick fix. I am not sure that method getCurrentScope should be here. In this class we have store resolver. I think make sense to move logic of current scope determination into store resolver. But I don't know what issue MC-33168 was about, and afraid to broke something, what has been fixed previously. Therefore I decided change default value in method getCurrentScope. If somebody can explain me issue of MC-33168, then I'll be able to move on.

**Comment by bogutskyy** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @bogutskyy, sorry for the delay on this. Please follow some information from MC-33168:

```
Default State dropdown is not filled with correct data

ISSUE:
When configuring 'Default Tax Destination Calculation', the 'Default State' dropdown only fills with data based on allowed countries of the default website.

STEPS TO REPLICATE:
1. Configure a second website, e.g. 'Test Website'.
2. Go to Stores -> Configurations.
3. Change the scope to 'Main Website'.
4. Navigate to General -> General -> Country Options -> Allow Countries and select some countries, e.g. select France and Germany.
5. Clear the cache.
6. Go to Stores -> Configurations again and change the scope to 'Test Website'.
7. Navigate to Sales -> Tax -> Default Tax Destination Calculation.
8. Select Default Country from the dropdown list instead of Use Default.
9. Try to select Default State from the dropdown list instead of Use Default.

ACTUAL RESULTS:
Only when selecting countries that have been selected for the Main Website (Step 4), will the Default State dropdown display a full list. Otherwise, it does not display the full list of states:
```

File: app/code/Magento/Directory/Helper/Data.php (hunk 2 above)
Comment (gabrieldagama) [reply app/code/Magento/Directory/Helper/Data.php]: I agree that `getCurrentScope` probably shouldn't be on this helper, but by adding that condition it makes the function ambiguous. My proposal would be to look at the solution from the Create Order perspective, see from which request this function is being called, and make sure we have the correct scope on the request, it should be also a quick fix, what do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
Hello @bogutskyy, could you please look at https://github.com/magento/magento2/pull/30755#discussion_r551456808?
Thank you.

**Comment by engcom-Charlie** [comment]
Hello @bogutskyy, I'll try to continue with your PR.

**Comment by bogutskyy** [comment]
@engcom-Charlie  sure. Unfortunately, I don't have time to finish PR in the coming weeks Let me know if you need anything from me.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Static Tests

File: app/code/Magento/Directory/Helper/Data.php [hunk 3]
```diff
@@ -419,10 +419,10 @@ private function getCurrentScope(): array
                 'type' => ScopeInterface::SCOPE_WEBSITE,
                 'value' => $request->getParam(ScopeInterface::SCOPE_WEBSITE),
             ];
-        } elseif ($request->getParam(ScopeInterface::SCOPE_STORE)) {
+        } elseif ($request->getParam('store_id')) {
```
Comment (gabrieldagama) [inline app/code/Magento/Directory/Helper/Data.php]: Let's just replace the string with a private constant.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, thanks for working on it. Please follow a small recommendation below.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8797](https://jira.corp.magento.com/browse/ENGCOM-8797) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
Was checked case described in issue https://github.com/magento/magento2/issues/30577
**Before:**
:x: Error `Please check the shipping address information. "regionId" is required. Enter and try again.` is shown and the order is not placed.
Screenshot from 2021-02-22 13-54-20


**After:**
:heavy_check_mark: Order is placed successfully
Screenshot from 2021-02-22 14-06-43

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B are failed

**Comment by hussainbaig34** [comment]
Hi Guys,

I am running Magento 2.4.2.  I Just migrated from 1.9.3. Alot of my orders are declining due to this issue. Is there a way I can fix this on my website quick?

Regards,
Hussain
