### PR TITLE
Internal Server Error in /V1/order/{orderId}/ship API Endpoint

### LINKED ISSUE #35931: Internal Server Error in `/V1/order/{orderId}/ship` API Endpoint
### Preconditions and environment

- Magento version 2.4

### Steps to reproduce

1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Request endpoint: POST : //yourstore/rest/V1/order/{orderId}/ship
Payload:
_{
  "items": "[]"
}_

Other below APi's also got effected and getting similar error in logs:
1. POST request to /V1/inventory/stock-source-links with payload:
_{"links": "[]"}_ 
2. POST request to /rest/V1/inventory/source-items with payload:
_{"sourceItems": "\\[]\\"}_
3. POST request to //V1/inventory/low-quantity-notification with payload:
_{"sourceItemConfigurations": ""}_
4. POST request to /rest/V1/inventory/stock-source-links-delete with payload:
_{"links": "\\[]\\"}_

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code from a null TypeError .

### Additional information

output of var/log/system.log:
```
	[2022-08-01T12:54:49.463557+00:00] main.CRITICAL: TypeError: Magento\Sales\Model\ShipOrder::execute(): Argument #2 ($items) must be of type array, null given in /magento/vendor/magento/module-sales/Model/ShipOrder.php:133
	Stack trace:
	#0 [internal function]: Magento\Sales\Model\ShipOrder->execute()
	#1 /magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
	#2 /magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
	#3 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
	#4 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
	#5 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
	#6 /magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
	#7 /magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
	#8 /magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
	#9 /magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
	#10 /magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
	#11 {main} [] []
```

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35931

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rogerdz,

Thanks for the contribution!

Please look into the failed tests it seems multiple tests are failing due to this change.

Thanks

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php [hunk 1]
```diff
@@ -19,7 +20,7 @@
  */
 class SynchronousRequestProcessor implements RequestProcessorInterface
 {
-    const PROCESSOR_PATH = "/^\\/V\\d+/";
+    private const PROCESSOR_PATH = "/^\\/V\\d+/";
```
Comment (engcom-Hotel) [inline app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php]: The change from `public` to `private` for the PROCESSOR_PATH constant could potentially impact code that directly references this constant.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Integration Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rogerdz @engcom-Dash,

Thanks for making the changes!

The failed tests seems flaky to me, hence re-ran the build to double sure. There is one small review comment below, please have a look into it.

Thanks

**Comment by rogerdz** [comment]
@magento run all tests

File: app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php (hunk 1 above)
Comment (rogerdz) [reply app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php]: I have updated

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Review by engcom-Hotel — APPROVED** [review]
Hello @rogerdz,

Thanks for making the changes. Failed tests seems flaky to me hence approving this PR for further processing.

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Retrieve auth token from the admin endpoint /V1/integration/admin/
- Request endpoint: POST : //yourstore/rest/V1/order/{orderId}/ship

Payload:
{
"items": "[]"
}


**Before:** :heavy_multiplication_x: 

Screenshot 2025-08-14 at 3 46 02 pm






**After:** :heavy_check_mark: 



Screenshot 2025-08-14 at 3 51 24 pm



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.
