### PR TITLE
Set self closing tags for void elements

### LINKED ISSUE #32822: SecureHtmlRenderer renderTag method renders incorrectly when provided 'null' content
### Preconditions (*)

1. 2.4.* (2.4.1 and 2.4.2 verified)

### Steps to reproduce (*)

1. Attempt to use the `\Magento\Framework\View\Helper\SecureHtmlRenderer::renderTag` method in a template to render an empty script tag with an external script src:
```
eg.
<script type="text/javascript" src="https://some-domain.com/external-lib.js"></script>
```

According to the documentation of that method, the 3rd argument ($content) should be nullable, so you should be able to do the following:

```
<?= /* @noEscape */ $secureRenderer->renderTag('script', ['src' => 'https://some-domain.com/external-lib.js'], null); ?>
```

**Use Case:** To conditionally render a script tag based on some criteria determined in PHP, such as the value of a system config, or the presence of some flag set in layout xml.

### Expected result (*)
1. Tag should render correctly with an empty body and be immediately followed by a closing tag:

```
eg.
<script type="text/javascript" src="https://some-domain.com/external-lib.js"></script>
```

### Actual result (*)
1. Tag does not close, which places all proceeding content _within_ the script tag, until the next closing script tag is encountered:
Screenshot from 2021-04-22 15-40-44

---
- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by basvanpoppel**
### Description (*)

This PR adds a fix to prevent html tags to be rendered in a wrong way. If a tag doesn't have content it's always self-closing, adding a script tag without content will therefor not work. 

Tags like hr, br, input, img, etc. are forbidden to be closed - they must be self-closing and are not allowed to have content. 

This change checks if the element type is void to determine if the tag should be self-closing.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32822

### Manual testing scenarios (*)

There's currently no steps you can take inside Magento to test this, as all present script tags have content. Adding a script tag without content (like <script/>, or what happens in many scenarios, <script src="script.js"/>) will trigger the issue.

### Questions or comments

I have written a unit test to verify behaviour, please let me know if anything else is needed.
Related to this issue there might be the question wether it's a good practice to add external scripts this way - but this is not the function to validate this - this function should just take care of rendering the html tag.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
Can you check fail tests related integrations cases

**Comment by mrtuvn** [comment]
@magento run Integration Tests, Unit Tests

**Comment by basvanpoppel** [comment]
@magento run Integration Tests

**Comment by basvanpoppel** [comment]
Integration tests are fine now. I saw a functional test failing earlier but it seems I can't access it. (also it doesn't seem related to this PR)

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Static Tests, Semantic Version Checker, Sample Data Tests EE, Sample Data Tests CE, Sample Data Tests B2B, Magento Health Index, Functional Tests EE, Functional Tests CE, Functional Tests B2B, Database Compare

**Comment by mrtuvn** [comment]
Thanks you for your contribution
Seem everything look good for me! Fail tests seem not related with this pull request changes

**Review by Den4ik — APPROVED** [review]
✅ Approved

Changes looks correct for me. @basvanpoppel Thanks for work on this PR

**Comment by Den4ik** [comment]
Just for completely green tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9119](https://jira.corp.magento.com/browse/ENGCOM-9119) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@basvanpoppel thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by Den4ik** [comment]
@magento run Functional Tests CE

**Comment by mrtuvn** [comment]
cc @sivaschenko this one may have higher priority for merge soon

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php [hunk 1]
```diff
@@ -49,10 +74,10 @@ public function renderTag(TagData $tagData): string
         }
 
         $html = '<' .$tagData->getTag() .$attributesHtml;
-        if ($content) {
-            $html .= '>' .$content .'</' .$tagData->getTag() .'>';
-        } else {
+        if (in_array($tagData->getTag(), self::VOID_ELEMENTS)) {
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]: Hi,

Could you replace the `in_array` statement with `isset` due to performance issues?
https://gist.github.com/alcaeus/536156663fac96744eba77b3e133e50a

/CC @Den4ik @mrtuvn , please pay attention to this one as well.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php (hunk 1 above)
Comment (mrtuvn) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]: Better re-check this case carefully!

Comment (Den4ik) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]: @ihor-sviziev Good point. I agree that searching by value is slower but in this case insignificant gain. Also php 7.* give slower result that's really interested

PHP 8.0
Function call in_array took 0.00493 seconds
Function call isset took 0.00360 seconds
Function call array_key_exists took 0.00388 seconds

PHP 7.4
Function call in_array took **0.00485** seconds
Function call isset took **0.00541** seconds
Function call array_key_exists took 0.00674 seconds

PHP 7.3
Function call in_array took **0.00530** seconds
Function call isset took **0.00563** seconds
Function call array_key_exists took 0.00464 seconds

Comment (Den4ik) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]: https://gist.github.com/Den4ik/ddfae8384bf8e26bd42af8c6e1662b9e

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]: @Den4ik tested your code locally and on the https://sandbox.onlinephpfunctions.com/
PHP 7.3 - isset is faster ✔
image
PHP 7.4 - isset is faster ✔
image
PHP 8.0 - isset is faster ✔
image

**Comment by sivaschenko** [comment]
The base branch was changed to platform-health to deliver in the scope of the Platform health project.

@ihor-sviziev @Den4ik do you think the proposed optimization is important? Did you include `array_flip` execution time in the benchmark for `isset` (or exclude it for `in_arrray`)?

**Comment by ihor-sviziev** [comment]
We don’t need to run array_flip in case if we’ll prepare correct map

**Comment by Den4ik** [comment]
> The base branch was changed to platform-health to deliver in the scope of the Platform health project.
> 
> @ihor-sviziev @Den4ik do you think the proposed optimization is important? Did you include `array_flip` execution time in the benchmark for `isset` (or exclude it for `in_array`)?

In my opinion it's not super important because array is not so long. But I  agree with @ihor-sviziev that we can prepare array with keys and use `isset` for check

**Comment by sivaschenko** [comment]
@basvanpoppel would you be able to apply the proposed improvements?

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php [hunk 2]
```diff
@@ -13,6 +13,31 @@
...
+        'img',
+        'input',
+        'keygen',
+        'link',
+        'meta',
+        'param',
+        'source',
+        'track',
+        'wbr'
+    ];
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]:
```suggestion
    private const VOID_ELEMENTS_MAP = [
        'area' => true,
        'base' => true,
        'br' => true,
        'col' => true,
        'command' => true,
        'embed' => true,
        'hr' => true,
        'img' => true,
        'input' => true,
        'keygen' => true,
        'link' => true,
        'meta' => true,
        'param' => true,
        'source' => true,
        'track' => true,
        'wbr' => true,
    ];
```

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php (hunk 1 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRender/HtmlRenderer.php]:
```suggestion
        if (isset(self::VOID_ELEMENTS_MAP[$tagData->getTag()])) {
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by basvanpoppel** [comment]
> @basvanpoppel would you be able to apply the proposed improvements?

They have been applied. I've learned something, thanks. :)

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]
