### PR TITLE
Fix issue #27355 with too many cookies in admin

### LINKED ISSUE #27355: Adminhtml - Too many mage-translation-file-version cookies
### Preconditions (*)
1. Magento 2.3.4 or 2.4-develop
2. Enable "Add Secret Key to URLs" in Stores > Configuration > Advanced > Admin > Security (enabling this option recommended for production env, it increases issue reproducing)

### Steps to reproduce (*)
1. Login into the admin
2. Go to few different pages
3. Open Chrome developer console, Network
4. Refresh the page
5. Select "document" request, see "Cookies" tab on the right side
6. check "show filtered out request cookies"
7. See list of cookies 

### Expected result (*)
1. Maximum one cookie `mage-translation-file-version` and `mage-translation-storage` should be created

### Actual result (*)
1. Almost for all admin URLs were created separate cookie `mage-translation-file-version` and `mage-translation-storage` because each of them has own path:
image

### Additional info
After some time of navigation on the admin and frontend - browser reaches limit per domain (in chrome 180 cookies per domain) and drops older cookies. In my case it started dropping 2fa auth cookie, and I have to put 2fa code all the time when I log in into the admin

### PR DESCRIPTION
**Pull request by ihor-sviziev**
Port MC-19247 for adminhtml in order to not use jQuery.localStorage plugin

### Description (*)
As part of https://github.com/magento/magento2/commit/71c781df5536a2ec79c9cf42ade0c262396767a3 there were significantly changed translation module for frontend, but for backend was left old implementation that caused https://github.com/magento/magento2/issues/27355

Before my changes js translation file was loaded via 
https://github.com/magento/magento2/blob/71c781df5536a2ec79c9cf42ade0c262396767a3/app/code/Magento/Translation/view/base/templates/translate.phtml

After - via https://github.com/magento/magento2/blob/71c781df5536a2ec79c9cf42ade0c262396767a3/app/code/Magento/Translation/view/base/web/js/mage-translation-dictionary.js
so it not creating any cookies anymore.

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/27355 : Adminhtml - Too many mage-translation-file-version cookies
2. Reduces time of reproducing https://github.com/magento/magento2/issues/17195

### Manual testing scenarios (*)
1. See https://github.com/magento/magento2/issues/27355

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lbajsarowicz — DISMISSED** [review]
Verified that locally with different scenarios.
Change works as expected, translations (Polish) still work.
I'd love to provide Functional Tests as a separate PR.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7156](https://jira.corp.magento.com/browse/ENGCOM-7156) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by ihor-sviziev** [comment]
@lbajsarowicz in functional tests I believe we can’t handle specifically this case because AFAIK there is no way to find all cookies with the same domain and name, but different path.
What we can check here is just that cookie isn’t added, but not really sure it would be ok as if functionality will be adjusted in future by adding these cookies back - it will not mean that became works incorrect.
I still think it’s better not to cover this case at all

**Comment by lbajsarowicz** [comment]
Ok. Its fine for me.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:**
before

**After:**
after

Tested with Germany language and everything work as expected

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by ihor-sviziev** [comment]
I would mark this PR as P2 and S1 because when you're working hard on changes in the admin - every 10-15 mins it forces you to fill up two factor auth, so it makes admin not useful at all.

Also this issue were causing cookie loosing on frontend after work in the admin.

**Comment by VladimirZaets** [comment]
Discuss with the author of the original PR

**Comment by hostep** [comment]
Hi folks, what's the status here?

We're also noticing random cookie/sessions problems, most likely caused by the bug this PR is trying to fix. A lot of duplicated `mage-translation-storage` and `mage-translation-file-version` cookies can be seen here for various domain names of shops we work on.
Problems seen by this:
- accepted cookie notices re-appearing on the frontend after a couple of minutes surfing around
- clicking around in backend, being redirected to the dashboard all out of the sudden

Seen happening on various Magento versions ranging from 2.3.2 to 2.3.5 at least (which is weird since [the commit](https://github.com/magento/magento2/commit/71c781df5536a2ec79c9cf42ade0c262396767a3) @ihor-sviziev mentions was only added in 2.3.4, but I have the feeling these total amount of cookies limit is a global setting we surpass and isn't solely from one shop)

**Comment by ihor-sviziev** [comment]
@hostep,
I think you can use changes from this PR in order to fix the issue on your project. I'm using this in production since this PR was created - no issues so far.

**Comment by hostep** [comment]
Thanks @ihor-sviziev: I can confirm this fixes our issue. Good work!

But I have problems understanding on what Magento versions this issue can occur, from what I understand it can happen on all Magento 2 versions ever released, is that correct?

This patch itself can only be applied to 2.3.4 and 2.3.5 shops I believe, so - if applicable - is there an (easy) way to fix this as well on older versions of Magento?

**Comment by ihor-sviziev** [comment]
@hostep I've tested on 2.3.4, but i think you could try to port it to older version and see if it helps.

**Review by inkloop — APPROVED** [review]
never mind

File: app/code/Magento/Translation/view/adminhtml/requirejs-config.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+
+var config = {
+    map: {
+        '*': {
+            mageTranslationDictionary: 'Magento_Translation/js/mage-translation-dictionary'
```
Comment (ihor-sviziev) [inline app/code/Magento/Translation/view/adminhtml/requirejs-config.js]: Just found that we have similar line in the frontend, maybe we need to move it to base, so it will be available both for frontend & admin?
https://github.com/magento/magento2/blob/71c781df5536a2ec79c9cf42ade0c262396767a3/app/code/Magento/Translation/view/frontend/requirejs-config.js#L12

Comment (lbajsarowicz) [reply app/code/Magento/Translation/view/adminhtml/requirejs-config.js]: I find it a great idea!

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Translation/view/adminhtml/requirejs-config.js (hunk 1 above)
Comment (ihor-sviziev) [reply app/code/Magento/Translation/view/adminhtml/requirejs-config.js]: Done

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @ihor-sviziev. I discussed this PR inside the team and currently, it's very tricky to approve the changes with BIC. Can we instead of removing block use it like stub. Leave empty block that doesn't do anything, just in case if someone writes some plugins on it. That will be backward compatible and we will have the ability to proceed with this PR

**Comment by ihor-sviziev** [comment]
Ok, no problem, will update PR soon

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by lbajsarowicz — DISMISSED** [review]
✔️ Changes look fine. Let's wait for the Tests to finish.

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev . It seems that the changes do not solve the problem described in the problem #27355 

**Actual Result:** :heavy_multiplication_x: were created a lot of separate cookies `mage-translation-file-version` and `mage-translation-storage`



@ihor-sviziev Could you take a look?

Thanks!

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, here is your [new Magento instance](https://pr-27364.instances.magento-community.engineering).
Admin access: [https://pr-27364.instances.magento-community.engineering/admin_36e6](https://pr-27364.instances.magento-community.engineering/admin_36e6)
Login: `49fdcfb1` Password: `41e9d8d4a8fc`
Instance will be terminated in up to 3 hours.

**Comment by ihor-sviziev** [comment]
@engcom-Alfa I can't reproduce this issue on test instance.
image

Also I see the file mage-translation-directory is loaded, so we shouldn't have any cookies:
image

**Comment by engcom-Alfa** [comment]
Hi @ihor-sviziev . I rechecked it and everything works well.
@lbajsarowicz Could you approve it again?

Thanks!

**Comment by engcom-Alfa** [comment]
Hi @lbajsarowicz . Could you approve it again?

**Review by lbajsarowicz — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7156](https://jira.corp.magento.com/browse/ENGCOM-7156) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: 




**After:** :heavy_check_mark: 

Screenshot from 2020-08-04 16-17-51
