### PR TITLE
Fix concurrency issue in static content deploy

### LINKED ISSUE #39990: [Issue] Fix concurrency issue in static content deploy
This issue is automatically created based on existing pull request: magento/magento2#39954: Fix concurrency issue in static content deploy

---------
# Summary

This fixes a bug in which multiple concurrent processes spin up to handle the same theme package, depending on how the themes are defined with their parents.

We saw a lot of issues like

```
DEBUG: STDERR:Compilation from source /path/to/some.js failed
Magento\Framework\Exception\FileSystemException: The file or directory "/app/var/view_preprocessed/pub/static/frontend/path/to/some.js" cannot be copied to "/app/pub/static/frontend/path/to/some.js"
```

We also saw less compilation intermittently failing to generate complete `styles-m.css` and `styles-l.css` files, as multiple processes were fighting and doing work on the same file at the same time. This cause the frontend to be deployed in a broken manner which needed a redeploy to solve.

For affected setups this may also improve the performance of this process, by the idea that we have a process no longer doing duplicated work.

#  To reproduce

## Reproduce

Clone https://github.com/convenient/magento-bug-reproduction-static-content-concurrency then run `composer install`, you can now generate static content.

Without the bugfix we can see multiple executions of the same package, see that `frontend/Custom/ztheme/default` is executed multiple times
```bash
$ rm -rf pub/static var/view_preprocessed/ var/cache ; php bin/magento > /dev/null ;  php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB en_IE -vvv | grep -E 'Execute: frontend/Custom/ztheme|Prevent'
Execute: frontend/Custom/ztheme/default
Execute: frontend/Custom/ztheme/default
Execute: frontend/Custom/ztheme/en_US
Execute: frontend/Custom/ztheme/en_GB
Execute: frontend/Custom/ztheme/en_IE
```

With the bugfix we can see each is only executed once
```bash
$ rm -rf pub/static var/view_preprocessed/ var/cache ; php bin/magento > /dev/null ;  php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB en_IE -vvv | grep -E 'Execute: frontend/Custom/ztheme|Prevent'
Execute: frontend/Custom/ztheme/default
Preventing duplicate execution of package as it is in progress: frontend/Custom/ztheme/default (pid: 67830)
Execute: frontend/Custom/ztheme/en_US
Execute: frontend/Custom/ztheme/en_GB
Execute: frontend/Custom/ztheme/en_IE
```

## Verification

I have used this fix on production for over a year without any issues. But we can also double check on the example reproduction repository provided above.

Get a baseline
```bash
rm -rf pub/static/
php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB
find ./pub/static -type f -exec md5sum {} + | awk '{print $1, $2}' > before.txt
```

Apply the bugfix then do the following

```bash
rm -rf pub/static/
php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB
find ./pub/static -type f -exec md5sum {} + | awk '{print $1, $2}' > after.txt
```

See that all files (that matter) were generated the same 
```bash
$ diff  before.txt after.txt
1c1
< 04d5dfe8b06b35834eeb526128ef11ba ./pub/static/deployed_version.txt
---
> b5e5f1122730b93197d32286a8dc65ab ./pub/static/deployed_version.txt
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by convenient**
# Summary

This fixes a bug in which multiple concurrent processes spin up to handle the same theme package, depending on how the themes are defined with their parents.

We saw a lot of issues like

```
DEBUG: STDERR:Compilation from source /path/to/some.js failed
Magento\Framework\Exception\FileSystemException: The file or directory "/app/var/view_preprocessed/pub/static/frontend/path/to/some.js" cannot be copied to "/app/pub/static/frontend/path/to/some.js"
```

We also saw less compilation intermittently failing to generate complete `styles-m.css` and `styles-l.css` files, as multiple processes were fighting and doing work on the same file at the same time. This cause the frontend to be deployed in a broken manner which needed a redeploy to solve.

For affected setups this may also improve the performance of this process, by the idea that we have a process no longer doing duplicated work.

#  To reproduce

## Reproduce

Clone https://github.com/convenient/magento-bug-reproduction-static-content-concurrency then run `composer install`, you can now generate static content.

Without the bugfix we can see multiple executions of the same package, see that `frontend/Custom/ztheme/default` is executed multiple times
```bash
$ rm -rf pub/static var/view_preprocessed/ var/cache ; php bin/magento > /dev/null ;  php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB en_IE -vvv | grep -E 'Execute: frontend/Custom/ztheme|Prevent'
Execute: frontend/Custom/ztheme/default
Execute: frontend/Custom/ztheme/default
Execute: frontend/Custom/ztheme/en_US
Execute: frontend/Custom/ztheme/en_GB
Execute: frontend/Custom/ztheme/en_IE
```

With the bugfix we can see each is only executed once
```bash
$ rm -rf pub/static var/view_preprocessed/ var/cache ; php bin/magento > /dev/null ;  php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB en_IE -vvv | grep -E 'Execute: frontend/Custom/ztheme|Prevent'
Execute: frontend/Custom/ztheme/default
Preventing duplicate execution of package as it is in progress: frontend/Custom/ztheme/default (pid: 67830)
Execute: frontend/Custom/ztheme/en_US
Execute: frontend/Custom/ztheme/en_GB
Execute: frontend/Custom/ztheme/en_IE
```

## Verification

I have used this fix on production for over a year without any issues. But we can also double check on the example reproduction repository provided above.

Get a baseline
```bash
rm -rf pub/static/
php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB
find ./pub/static -type f -exec md5sum {} + | awk '{print $1, $2}' > before.txt
```

Apply the bugfix then do the following

```bash
rm -rf pub/static/
php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB
find ./pub/static -type f -exec md5sum {} + | awk '{print $1, $2}' > after.txt
```

See that all files (that matter) were generated the same 
```bash
$ diff  before.txt after.txt
1c1
< 04d5dfe8b06b35834eeb526128ef11ba ./pub/static/deployed_version.txt
---
> b5e5f1122730b93197d32286a8dc65ab ./pub/static/deployed_version.txt
```

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39990: Fix concurrency issue in static content deploy

### CODE REVIEW

File: app/code/Magento/Deploy/Process/Queue.php [hunk 1]
```diff
@@ -263,6 +263,14 @@ private function executePackage(Package $package, string $name, array &$packages
             && !$this->isDeployed($package)
             && ($this->maxProcesses < 2 || (count($this->inProgress) < $this->maxProcesses))
         ) {
+            if (!isset($packages[$name])) {
```
Comment (ihor-sviziev) [inline app/code/Magento/Deploy/Process/Queue.php:267]: From Copilot's review:
> Add a brief comment explaining that the absence of the package in the $packages array indicates it is already in progress, to aid future maintainers in understanding why duplicate execution is being prevented.


Could you please do this?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @convenient,
Thank you so much for the contribution! Looks good

Could you please fix static test failures as described in https://github.com/magento/magento2/pull/39954#issuecomment-2940205496

File: app/code/Magento/Deploy/Process/Queue.php (hunk 1 above)
Comment (convenient) [reply app/code/Magento/Deploy/Process/Queue.php:267]: I have some billable work to complete, and then the MMUK conference next week 

This will go into my TODO pile, or anyone with privileges to my branch is welcome to push

Comment (engcom-Dash) [reply app/code/Magento/Deploy/Process/Queue.php:267]: Hi @convenient, I am taking care of the static test failures.

Comment (convenient) [reply app/code/Magento/Deploy/Process/Queue.php:267]: Thank you!

**Comment by engcom-Dash** [comment]
@convenient & @ihor-sviziev  I have fixed the static test cases also added the comment above the if statement. The other failing test cases seems flaky to me. Could you please review the changes ?

Moving it back to pending review. Thanks!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento create issue

**Comment by engcom-Dash** [comment]
@convenient Thank you for the contribution & collaboration!

<h3>✔️ QA Passed </h3>

Preconditions:
1. Install fresh Magento 2.4-develop

Steps to reproduce:
1. Add themes configuration in config.php.
2. Run below command  to check the execution of theme package:
rm -rf pub/static var/view_preprocessed/ var/cache ; php bin/magento > /dev/null ;  php ./bin/magento setup:static-content:deploy --no-ansi --no-interaction -f -s compact -vvv --jobs 4 --no-html-minify en_US en_GB en_IE -vvv | grep -E 'Execute: frontend/Magento/blank|Prevent'

Before: ❌ 

Duplicate execution of the theme package found.
Screenshot 2025-06-12 at 4 52 39 PM

After: ✔️ 

Screenshot 2025-06-12 at 5 26 06 PM

Builds are failing hence moving this PR in Extended Testing.

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, Semantic Version Checker, Unit Tests, WebAPI Tests
