### PR TITLE
MC-33893: 2.3.4 Invoice always sent (if exist) when order placed

### LINKED ISSUE #27656: 2.3.4 Invoice always sent (if exist) when order placed.
### Preconditions (*)
related to attempt to fix 
https://github.com/magento/magento2/issues/13466

commit 
https://github.com/magento/magento2/commit/5ccd367ebc628b588a77cb2032faeabd6005b039
1. # h3. Steps to reproduce (*)
1. Place order with a payment method that instantly generates an invoice
1. The module/code that generated an invoice now is responsible for checking it's state and send to customer
1. but here https://github.com/magento/magento2/commit/896ae3bce3615ba59ba0e43757d6712de023dc20#diff-5e96777dde905631ad1729751f5cc83fR72 magento checks if invoice exist and send it to customer
1. If so, pleas give the possibility to disable this in `sales*model_service_quote_submit*success` without code modifying or changing `\Magento\Quote\Observer\SubmitObserver::execute` or its dependencies

### Expected result (*)
1. Invoice Sending is managed by modules that created this invoice and should be configurable
1. Invoice is not sent the same time the order placed
1. or this feature is disabled and can be configured

### Actual result (*)
1. Invoice is always sent if exists https://github.com/magento/magento2/commit/896ae3bce3615ba59ba0e43757d6712de023dc20#diff-5e96777dde905631ad1729751f5cc83fR7
1. The original intention to fix https://github.com/magento/magento2/issues/13466 if so **the PayPal module is responsible for sending its invoice NOT MAGENTO QUOTE MODULE**

### PR DESCRIPTION
**Pull request by zakdma**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/27656

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

File: app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+         * a flag to set that there will be redirect to third party after confirmation
+         */
+        $redirectUrl = $quote->getPayment()->getOrderPlaceRedirectUrl();
+        if (!$redirectUrl && $order->getCanSendNewEmailFlag()) {
+            try {
+                $invoice = current($order->getInvoiceCollection()->getItems());
+                if ($invoice) {
+                    $this->invoiceSender->send($invoice);
+                }
+            } catch (\Exception $e) {
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php]: Just to make sure if some TypeError or any other exception will happen - it shouldn't break placing order
```suggestion
            } catch (\Throwable $e) {
```

or you feel that catching Exception  will be enough?

File: app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php [hunk 2]
```diff
@@ -0,0 +1,94 @@
+<?php
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
```
Comment (engcom-Kilo) [inline app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php:5]: Please add declare(strict_types=1);

File: app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php [hunk 3]
```diff
@@ -0,0 +1,94 @@
...
+    }
+
+    /**
+     * Send invoice email if allowed.
+     *
+     * @param Observer $observer
+     *
+     * @return void
+     */
+    public function execute(Observer $observer)
```
Comment (engcom-Kilo) [inline app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php:60]: Please specify return type to method.
```suggestion
    public function execute(Observer $observer): void
```

**Review by engcom-Kilo — CHANGES_REQUESTED** [review]

**Comment by zakdma** [comment]
@magento run all tests

File: app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php (hunk 1 above)
Comment (zakdma) [reply app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php]: Thank you! Fixed

File: app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php (hunk 2 above)
Comment (zakdma) [reply app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php:5]: Fixed

File: app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php (hunk 3 above)
Comment (zakdma) [reply app/code/Magento/Quote/Observer/SendInvoiceEmailObserver.php:60]: Not allowed to do that because declared interface method  ObserverInterface::execute() have no such return type hinting.

**Comment by zakdma** [comment]
@magento run all tests

**Review by engcom-Kilo — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8965](https://jira.corp.magento.com/browse/ENGCOM-8965) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@zakdma thank you so much for making this as a public PR!

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed
**Manual testing scenario:**
- Configure payment method  with Payment Action=Sale (e.g., Payflow Pro)
- Create simple product
- Login as registered customer
- Place order using Credit Card (Payflow Pro)

**Before:**

- Email with order information send.
- Email with invoice information send(no possibility to disable/customize behavior)

**After:**
- Email with order information send.
- Email with invoice information send - could be disabled or customize via observer `sendInvoiceEmail`

- - Email with invoice information is not sent if observer is disabled:

```
<event name="sales_model_service_quote_submit_success">
        <observer name="sendInvoiceEmail" disabled="true"/>
</event>
```

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32580`.
