### PR TITLE
#29174 Add save_rewrites_history to categories via API

### LINKED ISSUE #29174: Category API should support save_rewrites_history for consistency reasons
# Description

When updating category URL keys via REST API there is no possibility to automatically create 301 redirects for the old URL key to the new one.

For products this is possible

### Expected behavior (*)

contents of category-rename.json

     {"category":{"name":"new name","is_active":1,"parentId":2366,"custom_attributes":[{"attribute_code":"url_key","value":"new name"},{"attribute_code":"save_rewrites_history","value":1}]}}

When making a API call like

     curl -k -X PUT $BASEURL/rest/V1/categories/1295  -H 'Content-Type: application/json' -H "Authorization: Bearer $BEARER" -d @category-rename.json

I expect that a new entry is created a the end of `url_rewrite` database table with the old url_key redirecting to the new category.
Instead, after the API call, I cannot find the URL key anywhere in the `url_rewrite` table.

### Benefits

There are shops which are managed by PIM systems via API. Here it is important for SEO reasons, to allow renaming the URL key without loosing old links.

### Additional information 

There was already a pull request implementing something similar, but without the option to *not* create rewrites.
https://github.com/magento/magento2/pull/18408

The `save_rewrites_history` *is* supported for products. So for consistency this should also be possible for categories.

Maybe I can be implemented similarly to `\Magento\CatalogUrlRewrite\Plugin\Webapi\Controller\Rest\InputParamsResolver::afterResolve`

### LINKED ISSUE #30240: [Issue] #29174 Add save_rewrites_history to categories via API
This issue is automatically created based on existing pull request: magento/magento2#29205: #29174 Add save_rewrites_history to categories via API

---------
Support save_rewrites_history to categories API
### Preconditions (*)
1. Magento 2.4-develop

### Description (*)

See #29174 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29174

### Steps to reproduce (*)
1. Go to **Catalog - Categories** and create a new **Subcategory**
2. Open Swagger (http://magentositewname.domain/swagger)
3. Generate Admin token via _**integrationAdminTokenServiceV1** **POST** /V1/integration/admin/token_ request
4. Copy the generated token into _api_key_ field and click **apply
api_key_field
5. Perform the _**catalogCategoryRepositoryV1** **PUT** /V1/categories/{id}_ request with the following Parameters:
- _id_ 2 (id of the previously created category)
- _body_
```
{
    "category": {
    "id": 5,
    "parent_id": 2,
    "name": "new name",
    "is_active": true,
    "position": 0,
    "level": 0,
    "created_at": "string",
    "updated_at": "string",
    "path": "string",
    "include_in_menu": true,
    "extension_attributes": {},
    "custom_attributes": [
      {
        "attribute_code": "url_key",
        "value": "new name1"
      },{
        "attribute_code":"save_rewrites_history",
        "value":1
        }
      ]
     }
    }
```
6. Verify if the _Response body_ is correct. 
**Example**:
resp_body
7. Open database table _url_rewrite_

### Actual result (*) 
The old url_rewriew record has been removed, and only the new record existed
db_before11

db_before2

### Expected result (*) 
The previous record is not removed
db_after1

See example in #29174

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by amenk**
Support save_rewrites_history to categories API

### Description (*)

See #29174 

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29174, magento/magento2#30240

### Manual testing scenarios (*)

See example in #29174

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30240: #29174 Add save_rewrites_history to categories via API

### CODE REVIEW

File: app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php [hunk 1]
```diff
@@ -18,6 +19,8 @@
  */
 class InputParamsResolver
 {
+    const SAVE_REWRITES_HISTORY = 'save_rewrites_history';
```
Comment (swnsma) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php]: Please make 'private'

File: app/code/Magento/Catalog/Model/CategoryRepository.php [hunk 2]
```diff
@@ -82,6 +82,10 @@ public function save(\Magento\Catalog\Api\Data\CategoryInterface $category)
         $existingData = array_diff_key($existingData, array_flip(['path', 'level', 'parent_id']));
         $existingData['store_id'] = $storeId;
 
+        if ($category->getData('save_rewrites_history', null) !== null) {
```
Comment (swnsma) [inline app/code/Magento/Catalog/Model/CategoryRepository.php]: It should be placed in Magento_CatalogUrlRewrite, not in Magento_Catalog.

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @amenk!

Thank you for your contribution!
Could you please check my comments?

Could you, also, please add coverage with webapi-functional tests?
Thank you!

File: app/code/Magento/Catalog/Model/CategoryRepository.php (hunk 2 above)
Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: Do you have a clue how we could do that?

**Comment by amenk** [comment]
I resolved the comment about private const by accident. Will fix it

File: app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php (hunk 1 above)
Comment (amenk) [reply app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php]: done

**Comment by amenk** [comment]
> Could you, also, please add coverage with webapi-functional tests?

I thought about doing that, yes :) Do you have some suggestion which test would be a good starting point.

File: app/code/Magento/Catalog/Model/CategoryRepository.php (hunk 2 above)
Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: @swnsma 

In the first place my code is very similar to the solution products, just the categories are persisted differently and I am wondering which is the better way :)
I.e. if we change it for categories, we might need to adapt products as well.

I see several options:

1. Mess with \Magento\Catalog\Model\CategoryRepository::getExtensibleDataObjectConverter (which is already deprecated)
2. Intercept a different method, in the before save event, and somehow get the info that rewrites should be created from the request
3. .... ?

Help is very much appreciated :)

**Comment by amenk** [comment]
I think I will use \Magento\Catalog\Api\CategoryRepositoryTest::testUpdate as a base test

**Comment by amenk** [comment]
@swnsma functional test added, no we just have to solve the architectural problem in
https://github.com/magento/magento2/pull/29205/files/00176f5a3a0c6671556ff28b66f437ffb1970060#diff-7493dc1498457624ac9529eacf844ff7

Feel free to adapt the pull request, if you have an idea how to fix it and now that a proper test is in place.

File: app/code/Magento/Catalog/Model/CategoryRepository.php (hunk 2 above)
Comment (swnsma) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: The problem that approach is lead to violation of modularity.
I see that for save from Adminhtml area, it uses observer to set a value and ResourceModel to save:
```observer name="category_save_rewrites_history_setter"```

Could you play somehow with `\Magento\Catalog\Model\CategoryRepository::getExtensibleDataObjectConverter` ? (the method is deprecated because class should be injected into the constructor parameters).

I see that it can handle custom attributes: \Magento\Framework\Api\ExtensibleDataObjectConverter::processCustomAttributes
Could we check why it does not help to solve our issue?

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: > The problem that approach is lead to violation of modularity.
absolutely

> I see that for save from Adminhtml area, it uses observer to set a value and ResourceModel to save:
> observer name="category_save_rewrites_history_setter"

yes, but no access to what was sent via the API, here

> Could you play somehow with \Magento\Catalog\Model\CategoryRepository::getExtensibleDataObjectConverter ? (the
> method is deprecated because class should be injected into the constructor parameters).
> I see that it can handle custom attributes:
> \Magento\Framework\Api\ExtensibleDataObjectConverter::processCustomAttributes
> Could we check why it does not help to solve our issue?

Maybe ... I am still wondering if that flag should be a custom attribute at all

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: After thinking a bit about it, I think it should be a custom attribute ... will check the converter

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: Just adding save_rewrites_history to \Magento\Catalog\Model\Category::getCustomAttributesCodes seems to do the trick -- not even messing with InputParamsResolver needed :)

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: but of course 

	    protected function getCustomAttributesCodes()
	    {
		if ($this->customAttributesCodes === null) {
		    $this->customAttributesCodes = $this->getEavAttributesCodes($this->metadataService);
		    $this->customAttributesCodes = array_diff($this->customAttributesCodes, CategoryInterface::ATTRIBUTES);
		}

		$this->customAttributesCodes[] = 'save_rewrites_history';

		return $this->customAttributesCodes;
	    }

would also destroy the purpose of modularity

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: @swnsma  I am tempted to add a public method getControlAttributesCodes() to 
app/code/Magento/Catalog/Model/Category.php:302 which I then could plug-in overwrite in the UrlRewriteModule

But this would be a B/C break, right? But seems like the cleanest solution

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: Or like it's done for addresses by injecting an attributeList Interface ... \Magento\Quote\Model\Quote\Address\CustomAttributeListInterface
EDIT: does not make sense, this customAttributeList is only meant for Quotes

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: I of course could plug into all find of functions like \Magento\Framework\Model\AbstractExtensibleModel::getCustomAttributes and \Magento\Framework\Model\AbstractExtensibleModel::getCustomAttribute which implicitly call \Magento\Framework\Model\AbstractExtensibleModel::getCustomAttributesCodes and call getCustomAttributeCodes by myself and add the save_rewrites_history attribute, that would work without any other subsential changes, but is a would be a huge mess architecture-wise

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: Or before adding a new public function, could we just make \Magento\Catalog\Model\Category::getCustomAttributesCodes public, so that a plugin could be used?

**Comment by amenk** [comment]
Actually there are tons of modularity problems save_rewrites_history is used in Magento_Catalog and url_key of course as well ...

The simples possible fix for the full issue would be 

	Index: app/code/Magento/Catalog/Model/Category.php
	===================================================================
	--- app/code/Magento/Catalog/Model/Category.php	(revision b8c848b22083b369702bebc19af7ad74bfe83c27)
	+++ app/code/Magento/Catalog/Model/Category.php	(date 1595352024085)
	@@ -309,7 +309,9 @@
		 if ($this->customAttributesCodes === null) {
		     $this->customAttributesCodes = $this->getEavAttributesCodes($this->metadataService);
		     $this->customAttributesCodes = array_diff($this->customAttributesCodes, CategoryInterface::ATTRIBUTES);
	+            $this->customAttributesCodes[] = 'save_rewrites_history';
		 }
		 return $this->customAttributesCodes;
	     }
	 

We could do something similar for products and get rid of the full file

app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php

File: app/code/Magento/Catalog/Model/CategoryRepository.php (hunk 2 above)
Comment (swnsma) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: Oh, I really would like to avoid such complications.
In such a case, it will be nice to have a mechanism for extension of Custom Attributes with not only EAV attributes but also with some configuration (more XML!).
But we already have Extension Attributes, which, could be used for this.

I prefer to look into two possible ways:
1) A short one - look into how we are saving category. 
Probably, we need to just copy 'all other' fields from category data as it works for the product: 
https://github.com/magento/magento2/blob/3008324fc7e90b01fd2b25be789aacaf950f6cde/app/code/Magento/Catalog/Model/ProductRepository.php#L538
2) A long one but more solid - look if we can replace usage of a custom attribute for extension attributes.
 But it still is required to think about possible BC breaks (at least for products, where it works previously).

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: Thanks for your feedback @swnsma  - I choose the blue pill (1.) for now. Let's see what the full test suite say.
I might still be BC breaking in a way, that some module does not expect all data to be copied in the repository's save, but it is very unlikely.

Actually I am not sure how repositories are supposed to work: Whether they should the attributes to the ones clearly specified (like EAV attributes) or not.

Option 2. would be great to implement, because it also saves us from all the hassle in InputParamsResolver, but I just don't have the resources to do that now -- at least we would have a integration test now if this get's merged :)

In the end of the day, I am not even sure if this setData() approach is nice to trigger the URL key regeneration - maybe somebody has even some better idea here.

**Comment by amenk** [comment]
@magento run all tests

**Comment by amenk** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Model/CategoryRepository.php (hunk 2 above)
Comment (swnsma) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: I also do not really like the idea to pass all data with `setData()`. It also a hack but, at least, it does not provide modularity issue :sweat_smile:

**_But, in general, it will be nice to ask someone else for additional ideas._**

**Comment by amenk** [comment]
> But, in general, it will be nice to ask someone else for additional ideas.

@swnsma whom?

File: app/code/Magento/Catalog/Model/CategoryRepository.php (hunk 2 above)
Comment (novikor) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: I would prefer option 1 if it is enough to solve the issue.
Looks like the safest and the easiest way.

Comment (amenk) [reply app/code/Magento/Catalog/Model/CategoryRepository.php]: That is like it is currently implemented in the PR... Can you take over and fix the tests? Thanks in advance

**Comment by gabrieldagama** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Model/CategoryRepository.php [hunk 3]
```diff
@@ -82,6 +82,10 @@ public function save(\Magento\Catalog\Api\Data\CategoryInterface $category)
         $existingData = array_diff_key($existingData, array_flip(['path', 'level', 'parent_id']));
         $existingData['store_id'] = $storeId;
 
+        if (is_array($category->getData())) {
+            $existingData = array_replace($existingData, $category->getData());
```
Comment (gabrieldagama) [inline app/code/Magento/Catalog/Model/CategoryRepository.php]: At first glance I don't see a problem with such approach, we just need to check the failed tests to see the impact of such change.

File: app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php [hunk 4]
```diff
@@ -41,48 +45,98 @@ public function __construct(RestRequest $request)
      */
     public function afterResolve(\Magento\Webapi\Controller\Rest\InputParamsResolver $subject, array $result): array
     {
-        $route = $subject->getRoute();
-        $serviceMethodName = $route->getServiceMethod();
-        $serviceClassName = $route->getServiceClass();
-        $requestBodyParams = $this->request->getBodyParams();
+        $this->processProductCall($subject, $result);
+        $this->processCategoryCall($subject, $result);
```
Comment (gabrieldagama) [inline app/code/Magento/CatalogUrlRewrite/Plugin/Webapi/Controller/Rest/InputParamsResolver.php]: This class now has more than one reason to change, breaking the SRP. Also looking at the plugin name it references it to product `product_save_rewrites_history_rest_plugin`. Also, the code between product and category seems to be duplication, can we create it in a general way and maybe handle things with DI?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @amenk,  thanks for your contribution! Please have a look at my comments below, please let me know your thoughts, happy to help you to proceed with this PR.

**Comment by amenk** [comment]
@gabrieldagama thanks for you comments
Do you have time to work on this PR? I probably will not follow-up this PR anymore, at least not in the near future.

It grow out of my reach: To create a clean and nice solution, needs too much refactoring, which might break BC and I don't know which BC breaking changes are allowed

But I am open to answer questions :)

**Comment by engcom-Echo** [comment]
Hi @amenk. Please check the option 
image
There is no way to continue.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

File: app/code/Magento/Catalog/Model/CategoryRepository.php [hunk 5]
```diff
@@ -239,4 +236,25 @@ private function getMetadataPool()
...
+    private function getExistingData(CategoryInterface $category, int $storeId)
+    {
+        $existingData = $this->getExtensibleDataObjectConverter()
+            ->toNestedArray($category, [], \Magento\Catalog\Api\Data\CategoryInterface::class);
+        $existingData = array_diff_key($existingData, array_flip(['path', 'level', 'parent_id']));
+        $existingData['store_id'] = $storeId;
+
+        if ($category->getData('save_rewrites_history') !== null) {
+            $existingData['save_rewrites_history'] = $category->getData('save_rewrites_history');
+        }
```
Comment (gabrieldagama) [inline app/code/Magento/Catalog/Model/CategoryRepository.php]: This isn't ideal, as mentioned by @swnsma it leads to violation of modularity, where `Catalog` module knows about an attribute introduced by `CatalogUrlRewrite` which isn't ideal. 

Instead of changing the repository itself, can we create a plugin (just on rest webapi context, similar to `CategoryInputParamsResolver`) that runs before `CategoryUrlRewriteGenerator::generate` and check the RestRequest for the `save_rewrites_history` property and sets it on the `Category` object?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Echo, thanks for updating the PR, please have a look on my comment below.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Review by swnsma — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-8286](https://jira.corp.magento.com/browse/ENGCOM-8286) has been created to process this Pull Request
:eight_spoked_asterisk: @swnsma, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by swnsma** [comment]
@magento run Functional Tests EE Functional Tests B2B

**Comment by swnsma** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Go to **Catalog - Categories** and create a new **Subcategory**
2. Open Swagger (http://magentositewname.domain/swagger)
3. Generate Admin token via _**integrationAdminTokenServiceV1** **POST** /V1/integration/admin/token_ request
4. Copy the generated token into _api_key_ field and click **apply
api_key_field
5. Perform the _**catalogCategoryRepositoryV1** **PUT** /V1/categories/{id}_ request with the following Parameters:
- _id_ 2 (id of the previously created category)
- _body_
```
{
    "category": {
    "id": 5,
    "parent_id": 2,
    "name": "new name",
    "is_active": true,
    "position": 0,
    "level": 0,
    "created_at": "string",
    "updated_at": "string",
    "path": "string",
    "include_in_menu": true,
    "extension_attributes": {},
    "custom_attributes": [
      {
        "attribute_code": "url_key",
        "value": "new name1"
      },{
        "attribute_code":"save_rewrites_history",
        "value":1
        }
      ]
     }
    }
```
6. Verify if the _Response body_ is correct. 
**Example**:
resp_body
7. Open database table _url_rewrite_

**BEFORE** applying changes provided in this PR, the old url_rewriew record has been removed, and only the new record existed
db_before11

db_before2

**AFTER** switching to the PR, the previous record is not removed
db_after1

**Comment by engcom-Bravo** [comment]
@magento create issue
