### PR TITLE
GraphQl Product visibility for search results

### LINKED ISSUE #36591: GraphQL product visibility isn't handled correctly for search results
### Preconditions and environment

- Magento 2.4.5

### Steps to reproduce

We've got a product API testproduct 1 (sku: `API-TEST-1`) which has set Visbility: Catalog and isn't assigned to any category. This effectively means that the product isn't visible anywhere by navigating, but the product page still works.

[Run query online](https://test.kommagento.nl/api/graphql?query=%23+We%27ve+got+a+product+API+testproduct+1+%28sku%3A+API-TEST-1%29+which+has+set+Visbility+to+Catalog%0A%23+and+isn%27t+assign+to+any+category.%0A%23%0A%23+This+means+that+the+product+page+can+be+accessed+but+it+doesn%27t+show+up+anywhere.%0A%0A%23+It+shows+the+the+product%2C+while+it+shouldn%27t%0Aquery+IncorrectlyReturnsAPITEST1+%7B%0A++one%3A+products%28search%3A+%22%22%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku%0A++++%7D%0A++%7D%0A%7D%0A%0A%23+For+the+above+query+this+is+a+workaround+by+using+a+space+for+the+search+field%0Aquery+CorrectlyDoesNotReturnAPITEST1++%7B%0A++two%3A+products%28search%3A+%22+%22%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku+%0A++++%7D%0A++%7D%0A%7D%0A%0A%23+Because+there+is+a+search+term+given%2C+it+correctly+uses+visibility+search+and+thus%0A%23+does+not+return+the+product%0Aquery+CorrectlyDoesNotReturnAPITEST2++%7B%0A++three%3A+products%28search%3A+%22API+testproduct+1%22%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku+%0A++++%7D%0A++%7D%0A%7D%0A%0A%23+Because+there+is+a+search+term+given%2C+it+should+always+use+Visbility%3A+Search%0A%23+but+it+seems+to+be+filtering+on+Visbility%3A+Product%0Aquery+IncorrectlyReturnsAPITEST2+%7B%0A++four%3A+products%28search%3A+%22API+testproduct+1%22%2C+filter%3A+%7Bprice%3A+%7Bfrom%3A+%221%22%7D%7D%29+%7B%0A++++items+%7B%0A++++++name%0A++++++sku%0A++++%7D%0A++%7D%0A%7D)

```graphql
# It shows the the product, while it shouldn't
query IncorrectlyReturnsAPITEST1 {
  one: products(search: "") {
    items {
      name
      sku
    }
  }
}

# For the above query this is a workaround by using a space for the search field
query CorrectlyDoesNotReturnAPITEST1  {
  two: products(search: " ") {
    items {
      name
      sku 
    }
  }
}

# Because there is a search term given, it correctly uses visibility search and thus
# does not return the product
query CorrectlyDoesNotReturnAPITEST2  {
  three: products(search: "API") {
    items {
      name
      sku 
    }
  }
}

# Because there is a search term given, it should always use Visbility: Search
# but it seems to be filtering on Visbility: Product
query IncorrectlyReturnsAPITEST2 {
  four: products(search: "API", filter: {price: {from: "1"}}) {
    items {
      name
      sku
    }
  }
}
```

### Expected result

```JSON
  "data": {
    "one": {
      "items": [
        {
          "name": "DrayTek Vigor 2927F",
          "sku": "V2927F"
        },
        {
          "name": "DrayTek Web Content Filter B",
          "sku": "DrayTek Web Content Filter B"
        },
        {
          "name": "ZyXEL ZyWALL VPN100 Firewall",
          "sku": "VPN100-EU0101F"
        }
      ]
    }
  },
```

```JSON
  "data": {
    "four": {
      "items": []
    }
  },
```

### Actual result

```JSON
  "data": {
    "one": {
      "items": [
        {
          "name": "DrayTek Vigor 2927F",
          "sku": "V2927F"
        },
        {
          "name": "DrayTek Web Content Filter B",
          "sku": "DrayTek Web Content Filter B"
        },
        {
          "name": "ZyXEL ZyWALL VPN100 Firewall",
          "sku": "VPN100-EU0101F"
        },
        {
          "name": "API testproduct 1",
          "sku": "API-TEST-1"
        }
      ]
    }
  },
```

```JSON
  "data": {
    "four": {
      "items": [
        {
          "name": "API testproduct 1",
          "sku": "API-TEST-1"
        }
      ]
    }
  },
```

### Additional information

So it seems that it can use the Visbility: Search, but when any filter is provided it switches to the Visibility: Catalog

### Release note

Correctly set the visibility filer when providing a search parameter

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

Product Visibility handling for search feature ,

### Related Pull Requests

Fixes for https://github.com/magento/magento2/issues/36591

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36591

### Manual testing scenarios (*)

1. SKU `API-TEST-1`, has assigned a visibility as Catalog, so it will visible only with checking category condition.
Admin
2. Result won't be appear if we search this sku.
Search_without_filter
3. Result will appear by checking the combination of assigned category and search key word
Search_with_filter

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by Vasudev-22** [comment]
@magento run all unit tests

**Comment by Vasudev-22** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php [hunk 1]
```diff
@@ -122,7 +122,7 @@ public function build(array $args, bool $includeAggregation): SearchCriteriaInte
         }
 
         $this->addEntityIdSort($searchCriteria);
-        $this->addVisibilityFilter($searchCriteria, $isSearch, !empty($args['filter']));
```
Comment (paales) [inline app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php]: I think this logic doesn't make sense: https://github.com/magento/magento2/blob/688a0b4172ffea536628b0d22fbdb833cb86e33f/app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php#L142

If a search query is present it should always use `getVisibleInSearchIds` and if it doesn't contain a search query it should use `getVisibleInCatalogIds`. I don't think it makes sense to not filter anything. We are either in 'search mode' or in 'catalog mode' not in both?

Comment (Vasudev-22) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php]: @paales , Which you mentioned this logic `if ($isFilter && $isSearch) { ` , is not related to this PR changes, it was available from core standards.
This PR is related to filter category conditions for catalog visibility combination  `$this->addVisibilityFilter($searchCriteria, $isSearch, !empty($args['filter']['category_id']));`

Comment (paales) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php]: I don't think selecting by category_id is a valid condition:
- When searching for a keyword but _filtering_ on a category_id it should still have visibility search? Or you could argue that each item should be in Search AND Catalog, but not neither? 
- You only check on `category_id` but we've also got `category_uid` so, that should probably be changed.

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php (hunk 1 above)
Comment (engcom-Hotel) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/SearchCriteriaBuilder.php]: @paales I have checked in the codebase this `build` method has been called from the below file

https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Search.php#L185

And if from the query, someone is passing `category_uid` then it is converted in `category_id` through the below function call:

https://github.com/magento/magento2/blob/cfaeeaef415c2a77009db57995e5eee627350878/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/Query/Search.php#L190

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @Vasudev-22,

Thank you for your contribution!

I have given fixes for few Web API test failures. Working on the remaining once. May I know are you working on this PR? Are you going to take care of the rest of the failures. Please confirm.

Thank you!

**Comment by Vasudev-22** [comment]
@engcom-Charlie, Thanks for supporting, You can take over from here.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests, Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Fixed static as well as web API test failures.

The functional test failures are not part of this PR or failing because of this PR. Hence moving this PR in Merge in Progress

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
This PR is already merged in [d4a9791](https://github.com/magento/magento2/commit/d4a9791d0f589ee1006beba25c240a39a59d50e9). Hence moving it to Recently merged.
