### PR TITLE
Fixes #7723 - saving multi select field in UI component form

### LINKED ISSUE #7723: Catalog rule contains-condition not saving multiple selection in 2.1.2
### Preconditions
1. Magento version 2.1.2 
2. Installed default sample data

### Steps to reproduce
1. Add new catalog price rule
2. General information doesn't seem to matter
3. Add contains-condition with multiple options
4. Example: Climate contains Spring, Warm
5. Save the rule

### Expected result
1. POST should contain both values for example:
`rule[conditions][1--1][type]:Magento\CatalogRule\Model\Rule\Condition\Product
rule[conditions][1--1][attribute]:climate
rule[conditions][1--1][operator]:{}
rule[conditions][1--1][value][]:208
rule[conditions][1--1][value][]:209`
2. Rule should be saved and condition should state: Climate contains Spring, Warm
schermafbeelding 2016-12-08 om 11 26 27

### Actual result
1. POST contains only first selected value
`rule[conditions][1--1][type]:Magento\CatalogRule\Model\Rule\Condition\Product
rule[conditions][1--1][attribute]:climate
rule[conditions][1--1][operator]:{}
rule[conditions][1--1][value][]:208`
2. Rule is saved and condition is: Climate contains Spring
schermafbeelding 2016-12-08 om 11 27 09

### PR DESCRIPTION
**Pull request by Zefiryn**
This fix resolves issue #7723 and allows to send all selected values of multi-select field in form handled by UI compontent

### CODE REVIEW

File: app/code/Magento/Ui/view/base/web/js/form/form.js [hunk 1]
```diff
@@ -54,6 +54,11 @@ define([
                     }
                     break;
 
+                case 'select-multiple':
+                    var name = item.name.substring(0,(item.name.length - 2)); //remove [] from the name ending
+                    result[name] = Array.prototype.slice.call(item.selectedOptions).map(function(o) {return o.value;});
```
Comment (zetlen) [inline app/code/Magento/Ui/view/base/web/js/form/form.js]: Since you are not mutating `item.selectedOptions` in place, there should be no need to clone it with `Array.prototype.slice`. Also, It might be clearer to use Underscore here, because this pattern is very common:

```js
result[name] = _.pluck(item.selectedOptions, 'value');
```

**Comment by vrann** [comment]
@Zefiryn thank you for contribution! Please see comments from @zetlen

**Comment by hatimeria-artur-jewula** [comment]
@vrann Thanks for the hint. I changed the code and double checked on my end.

**Review by zetlen — APPROVED** [review]
Thank you! It looks great.

**Comment by okorshenko** [comment]
@Zefiryn Thank you for your contribution to Magento 2 project! Your pull request has been successfully merged!

**Comment by jmtakahashi** [comment]
@okorshenko @Zefiryn does this also fix #8215 when using the condition "SKU is" used and adding mulitple sku's in the UI only results in the first 2 sku's being affected?
