### PR TITLE
Fixed issue create order page in admin - move items from shopping cart

### LINKED ISSUE #37538: Magento 2.4.6 - create order page in admin - move items from shopping cart issue
### Preconditions and environment

- Magento version: Magento 2.4.6
magento_move_items_from_cart_issue

### Steps to reproduce

When creating an order in admin and you move an item from the shopping cart to the list of items to order, that item is not getting deleted from the cart.

**Steps to reproduce**

- Create an order from admin.
- Add products and move the products to SHOPPING CART
- Again move products to Order.
- Put the items back into the cart.

### Expected result

The item moved from shopping cart to the list of items to order should get deleted from the shopping cart.

### Actual result

The item is not getting deleted from the shopping cart.

### Additional information

https://github.com/magento/magento2/assets/51680745/15766270-0701-4067-9c0d-54508c6a2169

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rostilos**
### Description (*)

The reason is that moving an item from the cart or wishlist to the order items section in the current implementation does not remove items from the cart or wishlist, but moves them within the session to the $transferredItems object to hide during order creation. Moved items are only deleted after the order has been created (which is obviously intended to avoid removing items from the wish list and cart in case no order has been created ). There is currently no functionality to restore moved items, and the item is re-added when you try to move it from the ordered section back to the cart/wishlist (regardless of whether the item is in them). I tried to add this functionality in this MR
### Fixed Issues (if relevant)

1. Fixes magento/magento2#37538

### Manual testing scenarios (*)

1. Create an order from admin.
2. Add products and move the products to SHOPPING CART or WISHLIST
3. Again move products to Order.
4. Put the items back into the cart/wishlist.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rostilos** [comment]
@magento run Static Tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by rostilos** [comment]
@magento run Functional Tests EE

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Sales/Model/AdminOrder/Create.php [hunk 1]
```diff
@@ -2094,6 +2103,47 @@ private function removeTransferredItems(): void
...
+     * @return bool
+     */
+    private function restoreTransferredItem($area, $items, $product = null): bool
+    {
+        $transferredItems = $this->_session->getTransferredItems() ?? [];
+        if (!isset($transferredItems[$area])) {
+            return false;
+        }
+        $itemToRestoreId = null;
+        switch ($area) {
```
Comment (engcom-Hotel) [inline app/code/Magento/Sales/Model/AdminOrder/Create.php]: Instead of a switch case, I would like to suggest using a composite approach like below:

https://github.com/magento-commerce/magento2ce/blob/b98deb3fea25cb823c25b005d3ea22ab18c45176/app/code/Magento/Ui/etc/di.xml#L405

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rostilos,

Thanks for the contribution!

Please review my suggestion below and cover the changes with some automated tests.

Thanks

File: app/code/Magento/Sales/Model/AdminOrder/Create.php (hunk 1 above)
Comment (DannyDaemonic) [reply app/code/Magento/Sales/Model/AdminOrder/Create.php]: I'm getting a 404 on your link.

Comment (engcom-Hotel) [reply app/code/Magento/Sales/Model/AdminOrder/Create.php]: The above link was from the private repo, you can use the below one for reference:

https://github.com/magento/magento2/blob/b98deb3fea25cb823c25b005d3ea22ab18c45176/app/code/Magento/Ui/etc/di.xml#L405

**Comment by engcom-Hotel** [comment]
Hello @rostilos,

Have you got a chance to check this [comment](https://github.com/magento/magento2/pull/37553#pullrequestreview-1699112369)?

Thanks

**Comment by rostilos** [comment]
@engcom-Hotel Yes, I have looked at it, and will try to fix it as soon as possible, can't spare the time right now, but will give an update soon. Thanks

**Comment by engcom-Hotel** [comment]
@rostilos did you get a chance to have a look on https://github.com/magento/magento2/pull/37553#pullrequestreview-1699112369?

**Comment by rostilos** [comment]
@engcom-Hotel 
Slightly reworked the functionality ( removed the stitch-case statement ), covered the functionality with mftf tests

**Comment by rostilos** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rostilos,

Thanks for making the changes!

Please resolve the build failures, they are due to the changes in this PR.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE

**Comment by engcom-Echo** [comment]
Functional failure are not related to PR changes.
Hence moving it to `Pending Review`

File: app/code/Magento/Sales/Model/AdminOrder/Create.php [hunk 2]
```diff
@@ -301,39 +301,39 @@ class Create extends \Magento\Framework\DataObject implements \Magento\Checkout\
...
+        \Magento\Quote\Api\CartManagementInterface           $quoteManagement,
+        \Magento\Framework\Api\DataObjectHelper              $dataObjectHelper,
+        \Magento\Sales\Api\OrderManagementInterface          $orderManagement,
+        \Magento\Quote\Model\QuoteFactory                    $quoteFactory,
+        array                                                $data = [],
+        \Magento\Framework\Serialize\Serializer\Json         $serializer = null,
+        ExtensibleDataObjectConverter                        $dataObjectConverter = null,
+        StoreManagerInterface                                $storeManager = null,
+        CustomAttributeListInterface                         $customAttributeList = null,
+        OrderRepositoryInterface                             $orderRepositoryInterface = null
```
Comment (andrewbess) [inline app/code/Magento/Sales/Model/AdminOrder/Create.php]: Could you please revert this changes in the constructor.
We must have the same code style for constructors in whole codebase.

File: app/code/Magento/Sales/Model/AdminOrder/Create.php [hunk 3]
```diff
@@ -886,11 +888,20 @@ public function moveQuoteItem($item, $moveTo, $qty)
...
                         }
 
-                        $cartItem = $cart->addProduct($product, $info);
-                        if (is_string($cartItem)) {
-                            throw new \Magento\Framework\Exception\LocalizedException(__($cartItem));
+                        $cartItems = $cart->getAllVisibleItems();
+                        $cartItemsToRestore = [];
+                        foreach ($cartItems as $value) {
+                            $cartItemsToRestore[$value->getData('item_id')] = $value->getData('item_id');
+                        }
```
Comment (andrewbess) [inline app/code/Magento/Sales/Model/AdminOrder/Create.php]:
```suggestion
                        foreach ($cartItems as $cartItem) {
                            $cartItemsToRestore[$cartItem->getItemId()] = $cartItem->getItemId();
                        }
```

Could you please check this suggestion?

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @rostilos 
Thank you for your contribution
Could you please check my suggestions
Thank you in advance

**Comment by andrewbess** [comment]
> @andrewbess Made the requested edits

Thank you
Looks good for me
Waiting for tests

**Comment by andrewbess** [comment]
@magento run all tests

**Review by andrewbess — APPROVED** [review]
Approved

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1. Create an order from admin.
2. Add products and move the products to SHOPPING CART
3. Again move products to Order.
4. Put the items back into the cart.

**Before:** :heavy_multiplication_x: 

9af5434a-2c47-4400-a842-e3496cc13a92.mp4

**After:** :heavy_check_mark:  

f3ee9f6a-0fcb-4732-8667-8de47bc87236.mp4

Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR to ready for testing hence pulling it back to Extended Testing.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
The functional B2B and Web API test failures are not same in recent 2 builds, it seems to be flakey hence moving it to Merge in Progress.
 
**Functional B2B**
Run 1: 
image

Run 2: 
image

**Web API test**
Run 1: 
image

Run 2:
image
