### PR TITLE
30350:Unable to update the items of a bundle-product in a wishlist-Ch…

### LINKED ISSUE #30350: [GraphQL] UpdateBundleProductsFromWishlist Web-API test fails with MariaDB
Pre- condition:

I'm using the Luma storefront.

Side note: I can't find a way to return the uids of the entered options. I can retrieve the options, as shown in step 2. This might be due to lack of knowledge on my part.

1. Use the following mutation to add the configurable product to cart.

```json
mutation {
  addProductsToWishlist(
  wishlistId: 1
  wishlistItems: <
    {
      sku: "24-WG080"
      quantity: 1
      selected_options: [
        "YnVuZGxlLzEvMS8x"
        "YnVuZGxlLzIvNC8x"
        "YnVuZGxlLzMvNy8x"
        "YnVuZGxlLzQvOC8x"
      ]
    }
  ]){
    wishlist {
      id
      items_count
      items {
        id
        qty
        product {
          name
          sku
          id
          price_range {
            minimum_price {
              regular_price {
                currency
                value
              }
            }
            maximum_price {
              regular_price {
                currency
                value
              }
            }
          }
        }
      }
    }
    user_errors {
      code
      message
    }
  }
}
 {code}

2. Update the selected items. I'm changing the first entry from YnVuZGxlLzEvMS8x to YnVuZGxlLzEvMi8x and the third entry from YnVuZGxlLzMvNy8x to YnVuZGxlLzMvNi8x

{code:json}
mutation {
  updateProductsInWishlist(
  wishlistId: 1
  wishlistItems: [
    {
      wishlist*item*id: 20
      selected_options: [
        "YnVuZGxlLzEvMi8x"
        "YnVuZGxlLzIvNC8x"
        "YnVuZGxlLzMvNi8x"
        "YnVuZGxlLzQvOC8x"
      ]
    }

  ]){
    wishlist {
      id
      items_count
      items {
        id
        qty
        product {
          name
          sku
          id
          ... on BundleProduct {
            items {
              sku
              options {
                id
                uid
              }
            }
          }
          price_range {
            minimum_price {
              regular_price {
                currency
                value
              }
            }
            maximum_price {
              regular_price {
                currency
                value
              }
            }
          }
        }
        
      }
    }
    user_errors {
      code
      message
    }
  }
}

{code}

#### Expected Result: 
A single bundle product

#### Actual

Two bundle products.
{code:php}
{
  "data": {
    "updateProductsInWishlist": {
      "wishlist": {
        "id": "1",
        "items_count": 2,
        "items": [
          {
            "id": 20,
            "qty": 1,
            "product": {
              "name": "Sprite Yoga Companion Kit",
              "sku": "24-WG080",
              "id": 46,
              "items": [
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 1,
                      "uid": "YnVuZGxlLzEvMS8x"
                    },
                    {
                      "id": 2,
                      "uid": "YnVuZGxlLzEvMi8x"
                    },
                    {
                      "id": 3,
                      "uid": "YnVuZGxlLzEvMy8x"
                    }
                  ]
                },
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 4,
                      "uid": "YnVuZGxlLzIvNC8x"
                    }
                  ]
                },
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 5,
                      "uid": "YnVuZGxlLzMvNS8x"
                    },
                    {
                      "id": 6,
                      "uid": "YnVuZGxlLzMvNi8x"
                    },
                    {
                      "id": 7,
                      "uid": "YnVuZGxlLzMvNy8x"
                    }
                  ]
                },
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 8,
                      "uid": "YnVuZGxlLzQvOC8x"
                    }
                  ]
                }
              ],
              "price_range": {
                "minimum_price": {
                  "regular_price": {
                    "currency": "USD",
                    "value": 61
                  }
                },
                "maximum_price": {
                  "regular_price": {
                    "currency": "USD",
                    "value": 77
                  }
                }
              }
            }
          },
          {
            "id": 21,
            "qty": 1,
            "product": {
              "name": "Sprite Yoga Companion Kit",
              "sku": "24-WG080",
              "id": 46,
              "items": [
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 1,
                      "uid": "YnVuZGxlLzEvMS8x"
                    },
                    {
                      "id": 2,
                      "uid": "YnVuZGxlLzEvMi8x"
                    },
                    {
                      "id": 3,
                      "uid": "YnVuZGxlLzEvMy8x"
                    }
                  ]
                },
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 4,
                      "uid": "YnVuZGxlLzIvNC8x"
                    }
                  ]
                },
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 5,
                      "uid": "YnVuZGxlLzMvNS8x"
                    },
                    {
                      "id": 6,
                      "uid": "YnVuZGxlLzMvNi8x"
                    },
                    {
                      "id": 7,
                      "uid": "YnVuZGxlLzMvNy8x"
                    }
                  ]
                },
                {
                  "sku": "24-WG080",
                  "options": [
                    {
                      "id": 8,
                      "uid": "YnVuZGxlLzQvOC8x"
                    }
                  ]
                }
              ],
              "price_range": {
                "minimum_price": {
                  "regular_price": {
                    "currency": "USD",
                    "value": 61
                  }
                },
                "maximum_price": {
                  "regular_price": {
                    "currency": "USD",
                    "value": 77
                  }
                }
              }
            }
          }
        ]
      },
      "user_errors": [>
    }
  }
}
```

### PR DESCRIPTION
**Pull request by ranaprathapm-kensium**
Unable to update the items of a bundle-product in a wishlist

### Description (*)

Changed the condition for wishlist item comparison and added product options while item update in wishist
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30350

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogyar** [comment]
Hi @ranaprathapm-kensium. Thank you for your fix. Please, sign CLA, so we may proceed with processing your PR. 

Thank you!

File: app/code/Magento/Wishlist/Model/Wishlist.php [hunk 1]
```diff
@@ -334,7 +334,7 @@ protected function _addCatalogProduct(Product $product, $qty = 1, $forciblySetQt
     {
         $item = null;
         foreach ($this->getItemCollection() as $_item) {
-            if ($_item->representProduct($product)) {
+            if ($_item->getProduct()->getId() === $product->getId()) {
```
Comment (rogyar) [inline app/code/Magento/Wishlist/Model/Wishlist.php]: I would not recommend going this way since this fix excludes an important comparison of item options. See the following implementation for details 

https://github.com/magento/magento2/blob/795b2c6152e0fdf27bfb720d18e1bcd29723b154/app/code/Magento/Wishlist/Model/Item.php#L585

By bypassing this check we introduce a new problem when items with different options might be the same product.

Also, if the issue appears only in GraphQL are, I would recommend checking and fixing the issue on the resolvers or GraphQL services level without modifying the domain logic.

Hope it makes sense.

**Review by rogyar — CHANGES_REQUESTED** [review]

File: app/code/Magento/Wishlist/Model/Wishlist.php (hunk 1 above)
Comment (prabhuram93) [reply app/code/Magento/Wishlist/Model/Wishlist.php]: @ranaprathapm-kensium the above comment makes sense. This issue should be fixed in the graphql area. Also please cover this case using web api test. Thanks!

**Comment by ranaprathapm-kensium** [comment]
@prabhuram93  I have removed the changes in the core module and fixed the issue in GraphQL resolver only, Please check once. Also, I am working on API functional tests and update this PR once done.

**Comment by rogyar** [comment]
@magento run Static Tests

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 2]
```diff
@@ -51,25 +54,49 @@ class UpdateProductsInWishlist implements ResolverInterface
      */
     private $wishlistFactory;
 
+    /**
+     * Catalog product
+     *
+     * @var \Magento\Catalog\Helper\Product
+     */
+    protected $catalogProduct;
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, use the `private` scope for class properties

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 3]
```diff
@@ -51,25 +54,49 @@ class UpdateProductsInWishlist implements ResolverInterface
      */
     private $wishlistFactory;
 
+    /**
+     * Catalog product
+     *
+     * @var \Magento\Catalog\Helper\Product
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, use imports instead of fully qualified names

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 4]
```diff
@@ -95,22 +122,22 @@ public function resolve(
...
+            $wishlistOutput = $this->updateItem($wishlistItem->getId(), $options, $wishlist);
+        }
         if (count($wishlistOutput->getErrors()) !== count($wishlistItems)) {
             $this->wishlistResource->save($wishlist);
         }
 
         return [
-            'wishlist' => $this->wishlistDataMapper->map($wishlistOutput->getWishlist()),
-            'user_errors' => \array_map(
+            'wishlist' => $this->wishlistDataMapper->map($wishlistOutput->getWishlist()),            'user_errors' => \array_map(
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, check the code indentation

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 5]
```diff
@@ -160,4 +185,110 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+     * Update wishlist Item and set data from request
+     *
+     * @param int|Item $itemId
+     * @param DataObject $buyRequest
+     * @param wishlistFactory $wishlist
+     * @param null|array|DataObject $params
+     *
+     * @return $this
+     */
+    public function updateItem($itemId, $buyRequest,$wishlist,$params = null)
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, use `private` scope for class methods that are not entry points of the class. Also, please, use type hinting (including return type) and correct indentation.

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 6]
```diff
@@ -160,4 +185,110 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+    {
+        $item = null;
+        if ($itemId instanceof Item) {
+            $item = $itemId;
+            $itemId = $item->getId();
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: There's no usages of `$itemId` below. I would omit this line of code

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 7]
```diff
@@ -160,4 +185,110 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+                    if ($candidate->getParentProductId()) {
+                        continue;
+                    }
+                    $candidate->setWishlistStoreId($item->getStoreId());
+
+                    $qty = $buyRequest->getData('qty') ? $buyRequest->getData('qty') : 1;
+                    $item->setOptions($candidate->getCustomOptions());
+                    $item->setQty($qty)->save();
+                }
+                $wishlist->save();
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, do not use entity model for saving (deprecated approach). Use repo or resource model instead.

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 8]
```diff
@@ -160,4 +185,110 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+            } else {
+                throw new GraphQlInputException(__('The product does not exist.'));
+            }
+
+            if (is_string($item)) {
+                $this->addError($item);
+            }
+        } catch (GraphQlInputException $exception) {
+            $this->addError($exception->getMessage());
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, do not use try->catch for this single case. You may reduce the code complexity by adding error directly (line 252) without unnecessary try->catch

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php (hunk 5 above)
Comment (rogyar) [reply app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Moreover, to reduce complexity of the resolver, I would suggest moving this logic to a separate class, i.e. "UpdateWishlistItem" with one public `execute()` method.

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @ranaprathapm-kensium. Thank you for the adjustments. Please, check my comments below. Also, please, sign [Adobe CLA](http://opensource.adobe.com/cla.html), so we may proceed with processing the PR. 

Thanks

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php (hunk 5 above)
Comment (ranaprathapm-kensium) [reply app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: @rogyar Thanks for the suggestion, We can add a separate class but some common objects are shared between resolve & updateItem functions so added in resolver class only.

**Comment by ranaprathapm-kensium** [comment]
@rogyar  Thanks for the comments and I did changes in the latest commit, Please check once. Also, About CLA I am working with my internal team to get it done ASAP.

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 9]
```diff
@@ -160,4 +186,107 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+     * @param null $params
+     *
+     * @return WishlistOutput
+     * @throws GraphQlInputException
+     * @throws \Magento\Framework\Exception\AlreadyExistsException
+     */
+    private function updateItem($itemId, $buyRequest, $wishlist, $params = null)
+    {
+        $item = null;
+        if ($itemId instanceof Item) {
```
Comment (prabhuram93) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: @ranaprathapm-kensium itemId is always int, do we need this validation?

Comment (prabhuram93) [reply app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: $params is always null

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 10]
```diff
@@ -160,4 +186,107 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+            $params->setCurrentConfig($item->getBuyRequest());
+            $buyRequest = $this->catalogProduct->addParamsToBuyRequest($buyRequest, $params);
+            $buyRequest->setData('action', 'updateItem');
+            $product->setWishlistStoreId($item->getStoreId());
+            $cartCandidates = $product->getTypeInstance()->processConfiguration($buyRequest, clone $product);
+            /**
+             * Error message
+             */
+            if (is_string($cartCandidates)) {
+                return $cartCandidates;
```
Comment (prabhuram93) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Handle when $cartCandidates is a string

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 11]
```diff
@@ -160,4 +186,107 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+     * @param string $message
+     * @param string $code
+     *
+     * @return void
+     */
+    private function addError(string $message, string $code = null): void
+    {
+        $this->errors[] = new Data\Error(
+            $message,
+            $code ?? self::ERROR_UNDEFINED
```
Comment (prabhuram93) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: 2 issues here. 
self::ERROR_UNDEFINED is not found
Undefined class 'Error'

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 12]
```diff
@@ -160,4 +186,107 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
         return $wishlist;
     }
+
+    /**
+     * Update wishlist Item and set data from request
+     *
+     * @param int $itemId
+     * @param DataObject $buyRequest
+     * @param wishlistFactory $wishlist
+     * @param null $params
```
Comment (prabhuram93) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: null is not a valid type, you will get a phpcs error. Also I dont see params being used. Please handle it  accordingly.

**Review by prabhuram93 — CHANGES_REQUESTED** [review]
Hey @ranaprathapm-kensium, left some review comments. Mostly cosmetic issues. Please address them so we can start Qaing this one. Thanks!

**Comment by prabhuram93** [comment]
@magento rull all tests

**Comment by nrkapoor** [comment]
@magento rull all tests

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 13]
```diff
@@ -160,4 +186,76 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+     *
+     * @param int $itemId
+     * @param DataObject $buyRequest
+     * @param wishlistFactory $wishlist
+     *
+     * @return WishlistOutput
+     * @throws GraphQlInputException
+     * @throws \Magento\Framework\Exception\AlreadyExistsException
+     */
+    private function updateItem($itemId, $buyRequest, $wishlist)
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, use type hinting for method parameters and return types.

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 14]
```diff
@@ -160,4 +186,76 @@ private function getWishlist(?int $wishlistId, ?int $customerId): Wishlist
...
+            }
+
+            foreach ($cartCandidates as $candidate) {
+                if ($candidate->getParentProductId()) {
+                    continue;
+                }
+                $candidate->setWishlistStoreId($item->getStoreId());
+                $qty = $buyRequest->getData('qty') ? $buyRequest->getData('qty') : 1;
+                $item->setOptions($candidate->getCustomOptions());
+                $item->setQty($qty)->save();
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: Please, do not use deprecated methods in your code. The `::save` method of `AbstractModel` is deprecated since 2.1

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 15]
```diff
@@ -51,25 +55,49 @@ class UpdateProductsInWishlist implements ResolverInterface
...
+        WishlistDataMapper $wishlistDataMapper,
+        Product $catalogProduct,
+        BuyRequestBuilder $buyRequestBuilder
     ) {
         $this->wishlistResource = $wishlistResource;
         $this->wishlistFactory = $wishlistFactory;
         $this->wishlistConfig = $wishlistConfig;
         $this->updateProductsInWishlist = $updateProductsInWishlist;
         $this->wishlistDataMapper = $wishlistDataMapper;
+        $this->catalogProduct = $catalogProduct;
```
Comment (rogyar) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php]: If we use hepler, it makes sense to rename this property to `productHelper` or similar. `catalogProduct` suits more for a product model.

**Review by rogyar — CHANGES_REQUESTED** [review]
Please, check my suggestions below

**Comment by rogyar** [comment]
@magento run Static Tests

**Comment by ranaprathapm-kensium** [comment]
@rogyar I made changes to what you suggested so please check once.

**Comment by ranaprathapm-kensium** [comment]
@magento run all tests

**Comment by ranaprathapm-kensium** [comment]
@magento run Static Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run all tests

**Comment by ranaprathapm-kensium** [comment]
@magento run all tests

**Comment by ranaprathapm-kensium** [comment]
@magento run Static Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run Static Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run all tests

**Comment by ranaprathapm-kensium** [comment]
@magento run WebAPI Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run WebAPI Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run WebAPI Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run WebAPI Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run WebAPI Tests

**Comment by ranaprathapm-kensium** [comment]
@magento run WebAPI Tests

**Comment by rogyar** [comment]
@magento run Static Tests

**Comment by rogyar** [comment]
Hi @ranaprathapm-kensium. Please, check the failing tests.

Thank you

File: app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php [hunk 16]
```diff
@@ -0,0 +1,148 @@
...
+    private $wishlistResource;
+
+    /**
+     * @var array
+     */
+    private $errors = [];
+
+    /**
+     * BuyRequestBuilder
+     * @var BuyRequestBuilder $buyRequestBuilder
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php:34]: Update annotation to 
```
/**
* @var BuyRequestBuilder
*/
```

File: app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php [hunk 17]
```diff
@@ -0,0 +1,148 @@
...
+     * Update wishlist Item and set data from request
+     *
+     * @param object $options
+     * @param Wishlist $wishlist
+     *
+     * @return WishlistOutput
+     * @throws GraphQlInputException
+     * @throws \Magento\Framework\Exception\LocalizedException
+     */
+    public function execute(object $options, Wishlist $wishlist)
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php:62]: The first parameter represents more than just the item options. Can we rename `$options` to `$wishlistItemData` for added clarity?

File: app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php [hunk 18]
```diff
@@ -0,0 +1,148 @@
...
+            $productId = $product->getId();
+
+            if ($productId) {
+                $buyRequest->setData('action', 'updateItem');
+                $product->setWishlistStoreId($item->getStoreId());
+                $cartCandidates = $product->getTypeInstance()->processConfiguration($buyRequest, clone $product);
+
+                /**
+                 * If the product with options existed or not
+                 */
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php:85]: Change to single-line comment

File: app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php [hunk 19]
```diff
@@ -0,0 +1,148 @@
...
+                if (is_string($cartCandidates)) {
+                    throw new GraphQlInputException(__('The product with options does not exist.'));
+                }
+
+                /**
+                 * If prepare process return one object
+                 */
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php:92]: Change to single-line comment

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 20]
```diff
@@ -95,22 +95,24 @@ public function resolve(
...
+        }
 
         if (count($wishlistOutput->getErrors()) !== count($wishlistItems)) {
             $this->wishlistResource->save($wishlist);
         }
 
         return [
-            'wishlist' => $this->wishlistDataMapper->map($wishlistOutput->getWishlist()),
-            'user_errors' => \array_map(
+            'wishlist' => $this->wishlistDataMapper->map($wishlistOutput->getWishlist()),'user_errors' => \array_map(
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php:115]: Move `user_errors` to back to newline for better readability

File: app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php [hunk 21]
```diff
@@ -0,0 +1,148 @@
...
+                    $qty = $buyRequest->getData('qty') ? $buyRequest->getData('qty') : 1;
+                    $item->setOptions($candidate->getCustomOptions());
+                    $item->setQty($qty);
+                    if($options->getDescription()) {
+                        $item->setDescription($options->getDescription());
+                    }
+                }
+                $this->wishlistResource->save($wishlist);
+            } else {
+                throw new GraphQlInputException(__('The product does not exist.'));
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php:111]: This exception is not the result of direct input from the user. Thoughts on converting this to a `LocalizedException`?

Suggested message: `Could not find product for wishlist item with ID "%1"`

File: app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php [hunk 22]
```diff
@@ -0,0 +1,148 @@
...
+            if ($productId) {
+                $buyRequest->setData('action', 'updateItem');
+                $product->setWishlistStoreId($item->getStoreId());
+                $cartCandidates = $product->getTypeInstance()->processConfiguration($buyRequest, clone $product);
+
+                /**
+                 * If the product with options existed or not
+                 */
+                if (is_string($cartCandidates)) {
+                    throw new GraphQlInputException(__('The product with options does not exist.'));
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/UpdateWishlistItem.php:87]: This exception is not the result of direct input from the user. Thoughts on converting this to a `LocalizedException`?

Suggested message: `Could not prepare product for wishlist item with ID %1`

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 23]
```diff
@@ -95,22 +95,24 @@ public function resolve(
...
+        $wishlistItems  = $args['wishlistItems'];
+        $wishlistItems  = $this->getWishlistItems($wishlistItems, $wishlist);
+        $wishlistOutput = "";
+
+        foreach ($wishlistItems as $wishlistItem) {
+            $wishlistOutput = $this->updateWishlistItem->execute($wishlistItem, $wishlist);
+        }
 
         if (count($wishlistOutput->getErrors()) !== count($wishlistItems)) {
             $this->wishlistResource->save($wishlist);
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php:111]: It looks like the function call above is saving the wishlist for us when an error is not encountered.
```$this->updateWishlistItem->execute($wishlistItem, $wishlist)```

Is this additional save still necessary?

File: app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php [hunk 24]
```diff
@@ -95,22 +95,24 @@ public function resolve(
...
 
-        $wishlistItems = $args['wishlistItems'];
-        $wishlistItems = $this->getWishlistItems($wishlistItems, $wishlist);
-        $wishlistOutput = $this->updateProductsInWishlist->execute($wishlist, $wishlistItems);
+        $wishlistItems  = $args['wishlistItems'];
+        $wishlistItems  = $this->getWishlistItems($wishlistItems, $wishlist);
+        $wishlistOutput = "";
+
+        foreach ($wishlistItems as $wishlistItem) {
+            $wishlistOutput = $this->updateWishlistItem->execute($wishlistItem, $wishlist);
```
Comment (amolina-adobe) [inline app/code/Magento/WishlistGraphQl/Model/Resolver/UpdateProductsInWishlist.php:107]: The `$wishlistOutput` is going to be overridden with the function call for each successive wishlist item. The wishlist is properly updated, but only errors for the last wishlist item will be reported.

**Comment by amolina-magento** [comment]
@magento import pr to magento-honey-badgers/magento2ce

**Comment by magento-engcom-team** [comment]
@amolina-magento the pull request successfully imported.
