### PR TITLE
MC-26683: Removed get errors of cart allowing to add product to cart

### LINKED ISSUE #26683: Unable to execute addSimpleProduct mutation while other items out of stock
### Summary (*)

We are using Magento as a headless backend for our front-facing application, we are using the GraphQL API to build the frontend.

We noticed if we added a product to cart, and that product later became **out of stock**, any further attempts to add items to cart will fail with `Some cart items are out of stock` effectively locking up the cart from adding other items or changing other items quantities.

This is the returned GraphQL error:

```
"message": "Some of the products are out of stock.",
```

This is a breaking issue for us, as the alternative would result in a very poor experience for our users.

Currently, we have things set up that the frontend is able to detect whenever this exception is thrown and tries to amend it by removing the offending items and attempting to re-play whatever mutations are done to the cart since then.

Needless to say, this is a very flaky solution and it doesn't make sense to have this restriction in the first place since the REST API seems to be fine with this scenario.

### Examples (*)

To Reproduce:

1. Using the GraphQL API: **Add an item to cart.**
2. **Mark it as out-of-stock from the admin dashboard.**
3. Using the GraphQL API: **Try to add other products to cart.**

**I have successfully reproduced this on a fresh magento environment**

### Proposed solution

Ideally, the GraphQL API should allow mutating the cart as long as the out-of-stock item is not being the target of the mutation (updating its quantity for example).

A slightly less robust solution is to allow the mutation to go through, but return `errors` alongside the `data` prompting the GQL client to update their UI and also be aware of possible problems.

### GraphQL requests for reproducing
Create an empty cart
```graphql
mutation {
  createEmptyCart
}
```
Add product to cart 
```graphql
mutation {
  addSimpleProductsToCart(
    input: {
      cart_id: "{ CART_ID }"   # <--- cart id from the previous request goes here
      cart_items: [
        {
          data: {
            quantity: 1
            sku: "simple-product"   # <--- product sku goes here
          }
        }
      ]
    }
  ) {
    cart {
      items {
        id
        product {
          sku
          stock_status
        }
        quantity
      }
    }
  }
```

### PR DESCRIPTION
**Pull request by AleksLi**
### Description (*)

I removed completely the part of throwing any kind of error in the cart in case one of the product is out of stock. 
I tried to change/add _out of stock_ product that is in the cart and I've got an error with my current implementation (removed the getErrors -> throw $e). 
Removing_errors_get_errors_in_cart_graphql

Please help me figure out what might go wrong in this case.

### Fixed Issues (if relevant)

1. magento/magento2#26683: Unable to execute addSimpleProduct mutation while other items out of stock

### Manual testing scenarios (*)

1. Fully described in #26683 

### Questions or comments

Why did we need that part of code to throw any kind of error in the cart for GraphQL cart management?

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Hi @AleksLi,
Thank you for the contribution, however I don't think that removing error messages is the right way to fix this issue. This fix leads to the wrong flow when user will see cart errors only on place order step. My understanding here is that errors should be returned under `error` node like it is right now, but cart data should be present under `data` node. Could you please investigate the possibility to adjust this PR to display both - errors and data?
Thank you.

**Comment by AleksLi** [comment]
@lenaorobei Let me investigate that and come back with the commit or descriptive solution.

**Comment by AleksLi** [comment]
@lenaorobei I investigated the possible solutions for that.
Throwing an $e - will lead to building response with null data and errors.

1. So I would say we may find a way to add data in that case (in case of throwing error).
2. We could update the cart model or add one more key in response array like this:
`return [
            'cart' => [
                'model' => $cart,
            ],
            'errors' => [
                 'model' => $cart->getErrors()
            ]
        ];`
getErrors() method will return array of errors.

What do you think we should do? 

P.S. I would prefer the first option I guess. (my opinion). But I have no idea right now how to do that)) I will investigate it more in case we will choose 1st one.

**Comment by lenaorobei** [comment]
@AleksLi, I agree, option 1 looks better and complies with GraphQL standard. Appreciate your involvement!

**Comment by AleksLi** [comment]
@lenaorobei Ok then. I will investigate and maybe make a commit today. Sorry, I don't have much time in the evening to make a big input into the process. It would be slow but in the right way))

**Comment by AleksLi** [comment]
@lenaorobei  What I have found is:
vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php:250 says that
> // Errors from sub-fields of a NonNull type may propagate to the top level,
> // at which point we still log the error and null the parent field, 
> // in this case is the entire response.
Could you help me find out how to actually do that? At least a right way to dig. I'm debugging the whole process of logging error but cannot find anything useful to solve the issue, but I really want to. 
I think somewhere here or in resolve method /vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php:255 $result should be with cart data.

My other thought create some sort of `\Magento\Framework\GraphQl\Exception\GraphQlInputException` but with cart data. I haven't tried that, but it might work if I will understand what should be the response and with a little help

**Comment by lenaorobei** [comment]
I would start debugging from `\Magento\Framework\GraphQl\Query\QueryProcessor` and try to understand why only `errors` are present if exception was thrown. It looks like `\GraphQL\Executor\ExecutionResult::toArray` can process both `data` and `errors`.

**Comment by AleksLi** [comment]
@lenaorobei Yes, thanks that's the place I'm digging now and around it. 
The thing is \GraphQL\Executor\ReferenceExecutor::buildResponse is building response with almost empty data. Almost because data looks like an array with `addSimpleProductToCart = null`. So, I dug dipper to see why it's empty. I found out that \GraphQL\Executor\ReferenceExecutor::executeOperation returns null because it throws error and in that case $result will be null \GraphQL\Executor\ReferenceExecutor::doExecute here.

And I'm stuck on this. 
Any help would be great.

**Comment by lenaorobei** [comment]
Looks like it will require framework change, see `\Magento\GraphQl\Controller\GraphQl::dispatch`. I found related https://github.com/webonyx/graphql-php/issues/432 bug but I don't believe that global state is a good solution here. This task turns into much more complex one.

**Comment by AleksLi** [comment]
@lenaorobei totally agree with you. That require more time definitely and magento architecturer's help to resolve it right. 

So what should we do? Should I unassign the issue, because I'm interested to resolve it or keep helping in future progress? Please tell me

**Comment by lenaorobei** [comment]
It would be nice if you can propose some proof of concept of how to solve this issue on the framework level.

**Comment by AleksLi** [comment]
@lenaorobei  I think I found something interesting.
We have no rights to change any webonyx/graphql-php package, so...

I would say that the BEST solution I see of this issue is adding data to `\Magento\GraphQl\Controller\GraphQl::dispatch` Line:162 when we actually throwing an error int $result['data'] for example. But in this case I can see 2 improvements or parts that should be changed: 

1.  `\Magento\Framework\GraphQl\Exception\GraphQlInputException` with add Data method.
2. Actually go to `catch` (catch error when it's error) on line 160 of `\Magento\GraphQl\Controller\GraphQl::dispatch`. Now that part is no working as I wish it would.

That's I guess a possible solution to the issue. But I guess I mislead a couple of things here( How to actually jump to dispatch catch in case it is error.

**Comment by lenaorobei** [comment]
It would be easier to understand the proposed solution if you can commit POC to this branch. Thanks.

**Comment by AleksLi** [comment]
@lenaorobei could you explain what is POC and how to commit POC? 

Do you mean something that might work but requires improvement from the Magento developer?

**Comment by lenaorobei** [comment]
POC - proof of concept. This is a prototype for the proposed solution. If it will solve the issue and meet all requirements, the further solution can be based on it.

**Comment by AleksLi** [comment]
@lenaorobei Alright then. That's the same what I googled about POC) Ok. Let me do the commit. But I described a couple things I see as a problem. In case that would be easy I would do that myself))

File: app/code/Magento/QuoteGraphQl/Model/Cart/AddProductsToCart.php [hunk 1]
```diff
@@ -44,23 +44,26 @@ public function __construct(
...
 
         if ($cart->getData('has_error')) {
-            $e = new GraphQlInputException(__('Shopping cart errors'));
+            $e = new \Magento\Framework\GraphQl\Exception\GraphQlCartInputException(__('Shopping cart errors'));
             $errors = $cart->getErrors();
             foreach ($errors as $error) {
                 /** @var MessageInterface $error */
                 $e->addError(new GraphQlInputException(__($error->getText())));
             }
+            $e->addData($cartItems);
```
Comment (lenaorobei) [inline app/code/Magento/QuoteGraphQl/Model/Cart/AddProductsToCart.php]: This solution looks like a hack to me. We cannot add regular cart data to the exception.

Unfortunately, I don't have answer off the top of my head how to fix this right away, but this is not the right way to do this. Framework should allow returning both - `data` and `errors` and have predictable and behaviour, since other developer might use this code as well.

Comment (AleksLi) [reply app/code/Magento/QuoteGraphQl/Model/Cart/AddProductsToCart.php]: Totally agree. I didn't mean to push the exact solution. I don't know how to represent the solution in the right way. It is should be easily extendable and not obligatory I guess.

Comment (AleksLi) [reply app/code/Magento/QuoteGraphQl/Model/Cart/AddProductsToCart.php]: I might help someone more involved on GraphQl with more extended knowledge to resolve the issue or at least figure out the solution somehow. I actually have no idea how to push cartData into $result. After all the RESULT should be here \Magento\Framework\GraphQl\Query\QueryProcessor::process() this is the method that returns completed error and data with empty array.

Comment (AleksLi) [reply app/code/Magento/QuoteGraphQl/Model/Cart/AddProductsToCart.php]: Could push something in one of this variables that would be available in the queryProcessor where the result will be handled? 

`\Magento\Framework\GraphQl\Query\QueryProcessor::process`
```
$result  = \GraphQL\GraphQL::executeQuery(
            $schema,
            $source,
            $rootValue,
            $contextValue,
            $variableValues,
            $operationName
        );
```

**Comment by lenaorobei** [comment]
I believe I have an idea how to handle both - `errors` and `data`.
You need to add following code to the `\Magento\QuoteGraphQl\Model\Resolver\CartItems::resolve`:
```
        if ($cart->getData('has_error')) {
            $errors = $cart->getErrors();
            foreach ($errors as $error) {
                $itemsData[] = new GraphQlInputException(__($error->getText()));
            }
        }
```
after line 32. And remove errors from the `\Magento\QuoteGraphQl\Model\Cart\AddProductsToCart::execute`. 


Are you interested in trying this solution?

**Comment by lenaorobei** [comment]
Hi @AleksLi! Are you still up to finishing this PR?

**Comment by AleksLi** [comment]
@lenaorobei yes, I am. Sorry, I was away for a couple of days.

**Comment by AleksLi** [comment]
@lenaorobei thank you for an enormous help in this. I stuck there somewhere. That's really the solution and I've got the data and errors as a result. Awesome

**Comment by lenaorobei** [comment]
Happy to hear that! Pleas make sure it is covered with api-functional tests.

**Examples:**
\Magento\GraphQl\Quote\Guest\AddSimpleProductToCartTest
\Magento\GraphQl\Quote\Customer\AddSimpleProductToCartTest

**Docs:**
https://devdocs.magento.com/guides/v2.3/graphql/functional-testing.html

**Comment by AleksLi** [comment]
@lenaorobei  I will start covering it in the evening. thanks.

**Comment by AleksLi** [comment]
@lenaorobei hm. I just checked what failed and nothing even close to this PR. Let me try to rerun the tests.

**Comment by lenaorobei** [comment]
For this particular PR we actually need to check WebAPI Tests only.

**Comment by AleksLi** [comment]
@lenaorobei I've checked files for any reasonable changes regarding the api-functional testing and the files were changed here. I think everything is covered and needless to add/replace/edit any of them. 
 
Both changed files here were not covered before and won't affect the whole logic.
I haven't found anything that would use `Magento\QuoteGraphQl\Model\Cart\AddProductsToCart` for testing cases.

**Comment by lenaorobei** [comment]
I will ask somebody from our team to help you with tests. We dont have this case covered when both are present - `data` and `errors`.

**Comment by AleksLi** [comment]
@lenaorobei  ok good. I thought why Functional tests might fail. I guess I simply have not the latest 2.4-develop branch here. Could it be the reason?

**Comment by engcom-Charlie** [comment]
Due to framework limitation covered only the following scenarios:
1. Adding in-stock product to cart and verifying returned data.
2. Adding out-of-stock product to cart and check that response contains an exception message.

File: dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php [hunk 2]
```diff
@@ -79,6 +80,30 @@ public function testAddSimpleProductToCart()
         self::assertEquals('USD', $rowTotalIncludingTax['currency']);
     }
 
+    /**
+     * Add out of stock product to cart
```
Comment (lenaorobei) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php]:
```suggestion
     * Add disabled product to cart
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php [hunk 3]
```diff
@@ -79,6 +80,30 @@ public function testAddSimpleProductToCart()
...
+     *
+     * @@magentoApiDataFixture Magento/Catalog/_files/multiple_products.php
+     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/guest/create_empty_cart.php
+     * @return void
+     */
+    public function testAddProductToCartWithError(): void
```
Comment (lenaorobei) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php]:
```suggestion
    public function testAddDisabledProductToCart(): void
```

File: dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php [hunk 4]
```diff
@@ -79,6 +80,30 @@ public function testAddSimpleProductToCart()
         self::assertEquals('USD', $rowTotalIncludingTax['currency']);
     }
 
+    /**
+     * Add out of stock product to cart
+     *
+     * @@magentoApiDataFixture Magento/Catalog/_files/multiple_products.php
```
Comment (lenaorobei) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php]:
```suggestion
     * @magentoApiDataFixture Magento/Catalog/_files/multiple_products.php
```

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Please see review comments.

File: dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php [hunk 5]
```diff
@@ -79,6 +80,54 @@ public function testAddSimpleProductToCart()
...
+    }
+
+    /**
+     * Add out of stock product to cart
+     *
+     * @magentoApiDataFixture Magento/Catalog/_files/product_virtual_out_of_stock.php
+     * @magentoApiDataFixture Magento/GraphQl/Quote/_files/guest/create_empty_cart.php
+     * @return void
+     */
+    public function testAddOutOfStockProductToCart(): void
```
Comment (lenaorobei) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php:119]: For virtual product we have separate mutation https://devdocs.magento.com/guides/v2.3/graphql/mutations/add-virtual-products.html

Please change the test to make following:
1. Add `simple` (should be in stock) - using fixture
2. Add another one `simple` - using fixture
3. Mark one of them out of stock - using fixture - `Magento/GraphQl/Catalog/_files/set_simple_product_out_of_stock.php`
4. Perform mutation

See good example here: `Magento\GraphQl\Quote\Guest\PlaceOrderTest::testPlaceOrderWithOutOfStockProduct`

**Comment by AleksLi** [comment]
@lenaorobei I've seen your commits. thanks.

File: dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php (hunk 5 above)
Comment (AleksLi) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/Quote/Guest/AddSimpleProductToCartTest.php:119]: Yes, I've covered this case. Please check that

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-7105](https://jira.corp.magento.com/browse/ENGCOM-7105) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The second product, which is _IN-STOCK_, could be added to Cart while the first product in Cart is _OUT-OF-STOCK_  
pr27015


The cart query returns an error, displaying that _"Some of the products are out of stock."_, but also displays that the second, IN-STOCK product, was added 
```graphql
{
  "errors": [
    {
      "message": "Some of the products are out of stock.",
      "extensions": {
        "category": "graphql-input"
      },
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "cart",
        "items",
        0
      ]
    }
  ],
  "data": {
    "cart": {
      "total_quantity": 2,
      "items": [
        null,
        {
          "product": {
            "id": 2047,
            "name": "Sprod",
            "sku": "Sprod",
            "stock_status": "OUT_OF_STOCK"
          }
        },
        {
          "product": {
            "id": 2048,
            "name": "Sprod2",
            "sku": "Sprod2",
            "stock_status": "IN_STOCK"
          }
        }
      ]
    }
  }
}
```

**Comment by engcom-Charlie** [comment]
Failed functional tests not related to the changes in this PR.
