### PR TITLE
#30473 fixed image url for category if url rewrite are disabled

### LINKED ISSUE #30473: [Atwix]Category images are broken with SEO disabled
Cloning this ticket as its the same fix but it needs to also enable for when a customer has URL rewrites turned **off** (right now it only works if they have it turned on)

Seems like we introduced a bug change to 2.3.4 when we updated the category image source. It was changed from file name to the actual url but doesn't seem to work as the path returned is not the actual path for existing images. Only new images created after the migration work correctly. 

Test instance - <https://adobe-starter.dummycachetest.com/graphql/> 

Query 
 {
 category(id: 21)

{ id name url*path image product_count children*count }

}

Expected output 
```java
{
  "data": {
    "category": {
      "id": 31,
      "name": "Tops",
      "url_path": "venia-tops",
      "image": "https://adobe-starter.dummycachetest.com/media/catalog/category/outside.jpg",
      "product_count": 0,
      "children_count": "2"
    }
  }
} {code}
Actual output
{code:java}
 { "data": { "category": { "id": 31, "name": "Tops", "url*path": "venia-tops", "image": "https://adobe-starter.dummycachetest.com/media/outside.jpg", "product_count": 0, "children*count": "2" } } } ```

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30473

### Manual testing scenarios (*)

1. Turn off url rewrite
2. Set image for category
3. Execute query:
```
{
  category(id: 38){
    name
    image
  }
}
```

### Coments

If url rewrites on the site was disabled we have next result for query: 
Screenshot 2020-10-28 at 16 11 50

As we can see `image` response contains `index.php`, when we try open image by current url we get 404 error:

Screenshot 2020-10-28 at 16 13 51

I fixed it in my PR. Now we get correct response: 

Screenshot 2020-10-28 at 16 14 44

And can open image by url:

Screenshot 2020-10-28 at 16 15 35

Even if url rewrite turned off we will get correct image url. 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run Functional Tests EE

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php [hunk 1]
```diff
@@ -52,15 +54,15 @@ public function resolve(
...
+        /** @var Category $category */
         $category = $value['model'];
         $imagePath = $category->getData('image');
         if (empty($imagePath)) {
             return null;
         }
         /** @var StoreInterface $store */
         $store = $context->getExtensionAttributes()->getStore();
-        $baseUrl = $store->getBaseUrl();
+        $baseUrl = $store->getBaseUrl(UrlInterface::URL_TYPE_WEB);
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Category/Image.php:65]: I think we just need some tests for this

**Review by cpartica — CHANGES_REQUESTED** [review]
