### PR TITLE
Fixed creating shipping labels in part-shipment

### LINKED ISSUE #29552: [Issue] Fixed creating shipping labels in part-shipment
This issue is automatically created based on existing pull request: magento/magento2#27672: Fixed creating shipping labels in part-shipment

Fixed creating package when we ship not all items

### Description (*)
When we use sources, we can create shipment for only one item from order. In this case when we try to create shipping label with shipment ("Create Shipping Label" Checkbox), the system requires to add all products to package (including products, which wasn't added to shipment) and validation fails.

### Precondition(*)
Magento 2.4-develop
Inventory modules installed 

### Steps to reproduce (*)

1. Have configured shipping method with ability to create Shipping Labels
1. Have 2 products with available in 2 or more sources
1. Add to cart and order both products with shipping method from point 0.
1. Create shipment from admin panel: select source and enter qty only for one product (qty for second product should be 0)
1. Click Proceed to Shipment.
1. Check that only one product in Items to Ship
1. Check checkbox "Create Shipping Label" and press "Submit Shipment..."
1. Click "Add Products to Package". In the list there are both products.
1. When we add to package only one product - the next button is disabled.

### Expected result (*)
1. In the list there is only one product
1. The "Save" button is enabled

### Actual result (*)
Two products available in the list
The "Save" button is disabled after adding one product

### PR DESCRIPTION
**Pull request by NikolasSumrak**
Fixed creating package when we ship not all items

### Description (*)
When we use sources, we can create shipment for only one item from order. In this case when we try to create shipping label with shipment ("Create Shipping Label" Checkbox), the system requires to add all products to package (including products, which wasn't added to shipment) and validation fails.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

0. Have configured shipping method with ability to create Shipping Labels
1. Have 2 products with available in 2 or more sources
2. Add to cart and order both products with shipping method from point 0.
3. Create shipment from admin panel: select source and enter qty only for one product (qty for second product should be 0)
4. Click Proceed to Shipment.
5. Check that only one product in Items to Ship
6. Check checkbox "Create Shipping Label" and press "Submit Shipment..."
7. Click "Add Products to Package". In the list there are both products.
8. When we add to package only one product - the next button is disabled.

Expected result:
7. In the list there is only one product
8. The "Next" button is enabled

### Contribution checklist (*)
 - [*] Pull request has a meaningful description of its purpose
 - [*] All commits are accompanied by meaningful commit messages
 - [*] All new or changed code is covered with unit/integration tests (if applicable)
 - [*] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29552: Fixed creating shipping labels in part-shipment

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Review by sidolov — CHANGES_REQUESTED** [review]
@NikolasSumrak could you please cover changes with automated test?

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
It is complicated to create MFTF for this change, because of the security issue with storing shipment account credentials. Integration test checks that JS code rendered.

File: dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        $this->objectManager = Bootstrap::getObjectManager();
+        $this->registry = $this->objectManager->get(Registry::class);
+        $this->orderFactory = $this->objectManager->get(OrderInterfaceFactory::class);
+    }
+
+    /**
+     * Test that Packaging popup renders
+     *
+     * @magentoDataFixture Magento/GraphQl/Sales/_files/customer_order_with_ups_shipping.php
```
Comment (gabrieldagama) [inline dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php]: Can we use a fixture from the Sales module instead? It sounds more appropriate. Like this one `dev/tests/integration/testsuite/Magento/Sales/_files/order_with_shipping_and_invoice.php`

File: dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+     */
+    public function testGetCommentsHtml()
+    {
+        /** @var Template $block */
+        $block = $this->objectManager->get(Packaging::class);
+
+        $order = $this->orderFactory->create()->loadByIncrementId('100000001');
```
Comment (gabrieldagama) [inline dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php]: Instead of using the `orderFactory` here, it would be more appropriate to depend on `OrderRepositoryInterface` instead.

File: dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php (hunk 1 above)
Comment (gabrieldagama) [reply dev/tests/integration/testsuite/Magento/Shipping/Block/Adminhtml/Order/AddToPackageTest.php]: We may even use the fixture from the `Shipping` module `dev/tests/integration/testsuite/Magento/Shipping/_files/track.php` it also creates an order with shipment.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Hotel, thanks for adding test coverage, please have a look at my comments below.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by gabrieldagama — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8253](https://jira.corp.magento.com/browse/ENGCOM-8253) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
Hello @NikolasSumrak 

Looks like the changes provided in this PR do not fix the original issue
The **Save** button is still disabled when only one product is added to package
save_button

**Comment by engcom-Hotel** [comment]
Hello @NikolasSumrak, could you please check the previous comment and provide additional information for reproducing process or check provided solution.
Thank you.

**Comment by engcom-Hotel** [comment]
Will check it

**Comment by engcom-Bravo** [comment]
@gabrieldagama Can you please review the latest changes? Thank you

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8253](https://jira.corp.magento.com/browse/ENGCOM-8253) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Install Inventory 
2. Configure a Shipping method with the ability to **Create Shipping Label**, UPS for example
3. Create two **Sources** and **Assign** them to one **Stock**
1_source_stock
4. Create two Products, and **Assign** two previously created **Sources** to each of them
2_products
5. **Submit** an order containing previously created Products and selecting UPS _Shipping Method_
3_submit_order
6. Go to **Ship**. Select **Source**, set **Qty To Deduct** _1_ for one Product and _0_ for the other Product. Click **Proceed to Shipment**
4_process
7. Assert that only 1 Product is listed in _Items to Ship_
8. Check **Create Shiping Label** checkbox and click **Submit Shipment**
cre_ship_label
9. Click **Add Products to Package**. Assert that only one product appeared in the list of Products
фыыуке_щту
10 Check the product and click **Add selected Product(s) to Package**
11. Assert that the **Save** button is active and available

**BEFORE APPLYING CHANGES PROVIDED IN THIS PR**
Two products were available in _Create Packages_ window, despite that _0_ quantity has been set
two products
And before Adding both Products to Package, **Save** button was not available
Peek 2020-10-16 10-47

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests
