### PR TITLE
Fix Warning: Undefined array key "filters"

### LINKED ISSUE #39013: [Issue] Fix Warning: Undefined array key "filters"
This issue is automatically created based on existing pull request: magento/magento2#38996: Fix Warning: Undefined array key "filters"

---------
### Description (*)
Fresh Install, when a new user does not have played with bookmarks yet, this silenced error is logged.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by thomas-kl1**
### Description (*)
Fresh Install, when a new user does not have played with bookmarks yet, this silenced error is logged.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39013: Fix Warning: Undefined array key "filters"

### CODE REVIEW

**Comment by thomas-kl1** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento create issue

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php [hunk 1]
```diff
@@ -246,17 +246,28 @@ private function updateCurrentBookmarkConfig(array $data): void
...
+                    $this->bookmarkRepository->save($bookmark);
                 }
                 break;
             }
         }
     }
+
+    /**
+     * Check if the positions for identical filters has changed
+     */
```
Comment (engcom-Hotel) [inline app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php:267]:
```suggestion
     */*
 * @param array $existingConfig The existing configuration
 * @param array $currentConfig The current configuration
 * @return bool True if positions have changed, false otherwise
 */
```

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @thomas-kl1,
Thanks for the contribution!

Please add the doc block as suggested below.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that review changes has been covered so moved it back to review

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @thomas-kl1,


Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

A lot of "Fix Warning: Undefined array key "filters" errors pop in the logs when using the Admin views (ui grids).


**Before:** :heavy_multiplication_x: 


` main.CRITICAL: Exception: Warning: Undefined array key "filters" in /usr/local/var/www/magentok/magento2/app/code/Magento/Ui/Controller/Adminhtml/Bookmark/Save.php on line 250 in /usr/local/var/www/magentok/magento2/lib/internal/Magento/Framework/App/ErrorHandler.php:62`


**After:** :heavy_check_mark: 


There will be No Error in the Logs.

Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker, Functional Tests B2B, Functional Tests CE

**Comment by engcom-Charlie** [comment]
Functional B2B and CE failures in recent 2 builds are not consistent. They are not related to PR or not failing because of PR changes, seems to be flaky. Hence moving this PR to Merge in Progress.

**Functional B2B: Run1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/43f32231cb1a5e50d3ad4a58a1e1e303/Functional/allure-report-b2b/index.html#categories

image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/a464976bc37b6cb5b82b31a51a9949bf/Functional/allure-report-b2b/index.html#categories

image


**Functional CE: Run1:**

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/88db4508464058e6323f57d14f892641/Functional/allure-report-ce/index.html#categories

image



**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38996/c5ea7735164fde9706863e259a29c0fa/Functional/allure-report-ce/index.html#categories

image

**Comment by thomas-kl1** [comment]
Hello @engcom-Charlie , any idea if there's a chance this PR pass with next release?

**Comment by engcom-Charlie** [comment]
> Hello @engcom-Charlie , any idea if there's a chance this PR pass with next release?

Hi @thomas-kl1, 

We are trying to get it merge soon. We will notify you here once it will get merge.

**Comment by Calvin495** [comment]
@engcom-Charlie 
This fix is not in Magento 2.4.7-p1. Is there an official patch available for this fix?

**Comment by thomas-kl1** [comment]
Hello @Calvin495 you can use the diff and apply it as a patch.

**Comment by Calvin495** [comment]
@thomas-kl1 

Thanks. That was the last resort :)

Is this fix included in 2.4.7-p2?

**Comment by thomas-kl1** [comment]
This fix has been merged on November 1st, the 2.4.7-p2 has been released on August 9th. 😄 

For now the fix is only in the develop branch and is not part of any release yet.

**Comment by Calvin495** [comment]
@thomas-kl1 

Thanks
