### PR TITLE
Search should be disabled from products query when general configuration chooses to disabled it

### LINKED ISSUE #29927: Search should be disabled from products query when general configuration chooses to disabled it
Consider configuration "Disallow Catalog Search By" in the general Category Permissions.

If the relevant customer group is denied search then this kind of query
`products(search: "product"){...}`
should return no results

The Luma equivalent is that the search controller `catalogsearch/result/?q=product` redirects to 404 - no page found.

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pmarjan**
### Description (*)
Fixes https://github.com/magento/magento2/issues/29927

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/337

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pmarjan** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php [hunk 1]
```diff
@@ -94,4 +81,29 @@ public function resolve(
...
+     * Validate input arguments
+     *
+     * @param array $args
+     * @throws GraphQlAuthorizationException
+     * @throws GraphQlInputException
+     */
+    private function validateInput(array $args)
+    {
+        if (isset($args['searchAllowed']) && $args['searchAllowed'] === false) {
+            throw new GraphQlAuthorizationException(__('Product search has been disabled.'));
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php:95]: did we decide that this was preferable against no results?
shouldn't we have a storeConfig for it?

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php (hunk 1 above)
Comment (pmarjan) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Products.php:95]: When the customer group is denied searching the catalog, luma behaves in such a way that it would redirect to 404 page if the search results controller is hit (and that is if one knows or has Url to the search results previously saved or bookmarked).
So, luma does NOT land on a search results page saying that we do not have any results.

I thought this is the closest to that behavior, although, it gives information that luma does not: that the product search has been disabled.

I assume adding a store config about it, whether to throw an exception, or, display empty set of results, should be elegant approach.

**Review by cpartica — APPROVED** [review]
