### PR TITLE
#40216-Replacing nested foreach with array union (+) to reduce time complexity

### LINKED ISSUE #40216: Time complexity of _loadAttributes in Eav\Model\Entity\Collection\AbstractCollection increases with number of products in cart and attributes
### Preconditions and environment

Magento 2.4.x

### Steps to reproduce

1. Review https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/AbstractModel.php#L180 and there is a nested for in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php#L1236 and it calls `_setItemAttributeValue` once per attribute and `_setItemAttributeValue` iterates all products and set the value which is **O(n*m) [50 products in cart & 50 attributes leads to 2500 iterations]**

```
n = number of attributes
m= numbers of products
```
Profiler Output

Image

2. In addition `setData` function in https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/AbstractModel.php#L180 does the same validation for all products instead it should be done once per attribute per collection given it doesn't change per product or per entityValue

### Expected result

Iterates the number of rows from select query and then set once per product 

### Actual result

Iterates per attribute per product which increases the time complexity to multifold

### Additional information
Proposal is to avoid the nested loop with the below 

In `Magento\Eav\Model\Entity\Collection\AbstractCollection::_loadAttributes`

Replace
```
foreach ($values as $value) {
    $this->_setItemAttributeValue($value);
}
```
With

```
$attributeCode = $data = [];
$entityIdField = $this->getEntity()->getEntityIdField();

foreach ($values as $value) {
   $entityId = $value[$entityIdField];
    $attributeId = $value['attribute_id'];
    if(!isset($attributeCode[$attributeId])) {
        $attributeCode[$attributeId] = array_search($attributeId, $this->_selectAttributes);
        if (!$attributeCode[$attributeId]) {
            $attribute = $this->_eavConfig->getAttribute(
                $this->getEntity()->getType(),
                $attributeId
            );
            $attributeCode[$attributeId] = $attribute->getAttributeCode();
        }
        $data[$entityId][$attributeCode[$attributeId]] = $value['value'];
    }
}
if($data)
    $this->_setItemAttributeValue($data);
```
Replace `Magento\Eav\Model\Entity\Collection\AbstractCollection::_setItemAttributeValue` with the below

```
protected function _setItemAttributeValue($valueInfo)
    {
       foreach ($valueInfo as $entityId => $value) {
            if (!isset($this->_itemsById[$entityId])) {
                throw new LocalizedException(
                    __('A header row is missing for an attribute. Verify the header row and try again.')
                );
            }
           $object =$this->_itemsById[$entityId][0];
           $value = array_replace($object->getData(), $value);
           $object->setData($value);
        }
        return $this;
    }
```
Thus avoid calling _setItemAttributeValue equivalent to the number of attributes and internally it calls all products per attribute

### Additional Questions

Since array_replace is memory intensive for large array would it benefit over all or not ?

### Triage and priority

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by senthilengg**
### Description (*)

1. Moving $this->getEntity()->getEntityIdField(); lookup outside of the foreach
2. Processing the result of select query and preparing `[product_id => [attribute_code => value, attribute_code1 => value1]]` 
3. Calling `_setItemAttributeValue` only once per `$selectGroups` instead of per `$selectGroups`, per attribute and per product
4. Return same response as the original function

### Fixed Issues (if relevant)

1. Fixes magento/magento2 #40216 

### Manual testing scenarios (*)
1. Check all areas thats hitting the EAV

### Result

*Without this PR - Too many calls to _setItemAttributeValue function*
image

*With PR - Only one call to _setItemAttributeValue function*
image

### Additional Questions

Since array_replace is memory intensive for large array would it benefit over all or not ? 
array union (+) seems to be memory optimised and used here

### CODE REVIEW

**Comment by senthilengg** [comment]
@magento run unit Tests

**Comment by senthilengg** [comment]
@magento run Database Compare,Functional Tests CE,Functional Tests EE,Functional Tests B2B,Integration Tests,Magento Health Index,Sample Data Tests CE,Sample Data Tests EE,Sample Data Tests B2B,Static Tests,WebAPI Tests,Semantic Version Checker

**Comment by senthilengg** [comment]
https://github.com/magento run Functional Tests CE

**Comment by senthilengg** [comment]
@magento run Functional Tests CE

**Comment by senthilengg** [comment]
@magento run WebAPI Tests

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php [hunk 1]
```diff
@@ -1303,32 +1322,24 @@ protected function _addLoadAttributesSelectValues($select, $table, $type)
...
      * Initialize entity object property value
      *
-     * Parameter $valueInfo is _getLoadAttributesSelect fetch result row
+     * Parameter $valueInfo is [product_id => [attribute_code => value]]
      *
      * @param array $valueInfo
      * @return $this
      * @throws LocalizedException
      */
     protected function _setItemAttributeValue($valueInfo)
```
Comment (engcom-Hotel) [inline app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php:1334]: The method signature behavior has changed. Any plugin/extension overriding `_setItemAttributeValue()` will break. 

**Recommendations:**

- Create a new method `_setItemAttributeValues()` (plural) for batch processing
- Keep _setItemAttributeValue() (singular) unchanged for BC
- Add an automated test for the new method.

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php [hunk 2]
```diff
@@ -1303,32 +1322,24 @@ protected function _addLoadAttributesSelectValues($select, $table, $type)
...
-
-        foreach ($this->_itemsById[$entityId] as $object) {
-            $object->setData($attributeCode, $valueInfo['value']);
+        foreach ($valueInfo as $entityId => $value) {
+            if (!isset($this->_itemsById[$entityId])) {
+                throw new LocalizedException(
+                    __('A header row is missing for an attribute. Verify the header row and try again.')
+                );
+            }
+            // Run only once
```
Comment (engcom-Hotel) [inline app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php]: **Question**: If it "runs only once" why is there a foreach loop? This suggests `_itemsById[$entityId]` contains multiple objects, contradicting the comment.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @senthilengg,

Thank you for your contribution!

Please have a look into the below review comments.

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php (hunk 2 above)
Comment (senthilengg) [reply app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php]: @engcom-Hotel Without this loop during my manual functional testing and unit testing is working well and passed, I have tested with configurable, bundle and simple products. However without the loop its failing WebAPI Graphql MTF test so there could be a scenario the test script except this to run in a loop but I couldn't reproduce myself. Tried with Xdebug profile as well during the manual test.

 To give you another perspective I couldn't think of a scenario where this `_itemsById` contains more than one product object under the same Id. 

`_itemsById` was set here https://github.com/magento/magento2/blob/f6aa682fcff1562a804ecbf3995309123c7509a3/app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php#L1168  and if you notice it was fetched from DB. `$object->getId()` here being the entity ID from the DB can't be a duplicated. So to me it looks like a legacy code sitting there and push the object to the `_itemsById`  array if the same id exists. And this is the reason why MTF Web API test also expecting something, similar however in real world, I couldn't think of a scenario happens like this and thats the reason for my comment that it will run only once.

In any case if you feel its better to remove the please do so. Because if the object contains multiple it should have affected the stores much more since it would have run O(  a*b*c) c being the number of  objects inside `_itemsById`

And Thank you so much for the review. Appreciate it.

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php (hunk 1 above)
Comment (senthilengg) [reply app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php:1334]: @engcom-Hotel  I think you didn't notice its a protected function in an abstract class. Let me know if you still think we need to introduce new function for other reasons. I couldn't think of a scenario someone wants to override the under the hood Eav Object processing.

Comment (engcom-Hotel) [reply app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php:1334]: Hello @senthilengg,

Thanks for your reply!

but I am still thinks that this is the BiC change. Please go through with the below link:

https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/#modifying-the-default-values-of-optional-arguments-in-public-and-protected-methods

and let me know If I missed anything here.

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php (hunk 2 above)
Comment (engcom-Hotel) [reply app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php]: Thank you for your analysis @senthilengg. I agrees with your point. But I have suggestion below to change the comment as below:

// _itemsById[$entityId] is always an array (typically with one element)
// Foreach handles edge cases where multiple objects share the same entity ID

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php (hunk 1 above)
Comment (senthilengg) [reply app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php:1334]: @engcom-Hotel  Thank you for sharing the link. Its done!

File: app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php (hunk 2 above)
Comment (senthilengg) [reply app/code/Magento/Eav/Model/Entity/Collection/AbstractCollection.php]: @engcom-Hotel  Its done!

**Review by engcom-Hotel — APPROVED** [review]
Thank you @senthilengg for making the changes.

Failed tests seems flaky to me, hence approving this PR.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests
