### PR TITLE
Fix error visiting compare page without items

### LINKED ISSUE #40205: [Issue] Fix error visiting compare page without items
This issue is automatically created based on existing pull request: magento/magento2#40203: Fix error visiting compare page without items

---------
### Description (*)
Going incognito and visiting `/catalog/product_compare/index/` will cause an
```
Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "xxx" already exists.
```

Error on many live webshops. This is because the database table looks somewhat like this 
| catalog_compare_item_id | visitor_id | customer_id | product_id | store_id | list_id |
|-------------------------|------------|-------------|------------|----------|---------|
|                   23159 |    4690502 |             |      19028 |        1 |         |
|                   22917 |          0 |             |      18906 |        1 |     711 |
|                   23034 |          0 |             |      18868 |        1 |     732 |
|                   22916 |          0 |             |      18851 |        1 |     711 |
|                   21991 |          0 |             |      18783 |        1 |     537 |
|                   21573 |          0 |             |      18747 |        1 |     451 |
|                   22196 |          0 |             |      18740 |        1 |     585 |
|                   22485 |          0 |             |      18706 |        1 |     644 |
|                   22111 |          0 |             |      18705 |        1 |     568 |
|                   22259 |          0 |             |      18689 |        1 |     596 |
|                   22133 |          0 |             |      18689 |        1 |     573 |
|                   21802 |          0 |             |      18689 |        1 |     492 |

Thus if we only get items with visitor_id 0 and customer_id NULL we will get duplicate products (and compare product from other customers...)

### Manual testing scenarios (*)

1. Ensure your `catalog_compare_items` somewhat matches the example above (duplicate product id's on different lists)
2. Visit the `/catalog/product_compare/index/` route in incognito, so no visitor id, customer id, or list id is assigned to you
3. See the error that occurs.

### Additional Steps
It'd be quite simple to trigger this behavior using graphql:
```
curl 'https://magento.test/graphql' \
  -H 'accept: application/json' \
  -H 'content-type: application/json' \
  --data-raw '{"query":"mutation createCompareList($input: CreateCompareListInput) {\n  createCompareList(input: $input) {\n    item_count\n    uid\n  }\n}","variables":{"input":{"products":[23]}},"operationName":"createCompareList"}'
```

Call this query a couple of times (to emulate multiple users adding this product to their compare list), navigate to the `/catalog/product_compare/index/` page and you should get this error.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by indykoning**
### Description (*)
Going incognito and visiting `/catalog/product_compare/index/` will cause an
```
Item (Magento\Catalog\Model\Product\Interceptor) with the same ID "xxx" already exists.
```

Error on many live webshops. This is because the database table looks somewhat like this 
| catalog_compare_item_id | visitor_id | customer_id | product_id | store_id | list_id |
|-------------------------|------------|-------------|------------|----------|---------|
|                   23159 |    4690502 |             |      19028 |        1 |         |
|                   22917 |          0 |             |      18906 |        1 |     711 |
|                   23034 |          0 |             |      18868 |        1 |     732 |
|                   22916 |          0 |             |      18851 |        1 |     711 |
|                   21991 |          0 |             |      18783 |        1 |     537 |
|                   21573 |          0 |             |      18747 |        1 |     451 |
|                   22196 |          0 |             |      18740 |        1 |     585 |
|                   22485 |          0 |             |      18706 |        1 |     644 |
|                   22111 |          0 |             |      18705 |        1 |     568 |
|                   22259 |          0 |             |      18689 |        1 |     596 |
|                   22133 |          0 |             |      18689 |        1 |     573 |
|                   21802 |          0 |             |      18689 |        1 |     492 |

Thus if we only get items with visitor_id 0 and customer_id NULL we will get duplicate products (and compare product from other customers...)

### Manual testing scenarios (*)

1. Ensure your `catalog_compare_items` somewhat matches the example above (duplicate product id's on different lists)
2. Visit the `/catalog/product_compare/index/` route in incognito, so no visitor id, customer id, or list id is assigned to you
3. See the error that occurs.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#40205: Fix error visiting compare page without items

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @indykoning,

Thank you for the contribution!

The fix is technically correct and solves the reported issue, but lacks proper test coverage which is a requirement for Adobe Commerce contributions. So please add some automated tests.

**Comment by indykoning** [comment]
I've added a test based on https://github.com/magento/magento2/blob/913bf1a646580230130bf49de9bf069bd8d7aaf0/dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/Product/CollectionTest.php#L302 to see if the expected join query appears if a value of 0 is passed as customer id

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @indykoning,

Thank you for adding the integration test. We are having some static tests failing, please fix those.

File: dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/CollectionTest.php [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+     */
+    public function testJoinTable()
+    {
+        $this->collection->setVisitorId(0);
+        $sql = (string) $this->collection->getSelect();
+        $productTable = $this->collection->getTable('catalog_product_entity');
+        $compareTable = $this->collection->getTable('catalog_compare_item');
+
+        // phpcs:ignore Magento2.SQL.RawQuery
+        $expected = 'SELECT `e`.*, `t_compare`.`product_id`, `t_compare`.`customer_id`, `t_compare`.`visitor_id`, '
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/CollectionTest.php]: ## Test Improvement Suggestion

Great fix! However, the test could be more robust. Instead of asserting the entire SQL string (which can break with query formatting changes), Magento's own tests use `getPart()` to inspect specific query sections.

### Suggested approach (following Magento patterns):
```

    $this->collection->setVisitorId(0);
    $fromParts = $this->collection->getSelect()->getPart(\Magento\Framework\DB\Select::FROM);
    
    $this->assertArrayHasKey('t_compare', $fromParts);
    $joinCondition = $fromParts['t_compare']['joinCondition'];
    
    $this->assertStringContainsString('t_compare.list_id IS NULL', $joinCondition);
    $this->assertStringContainsString('t_compare.customer_id IS NULL', $joinCondition);
    $this->assertStringContainsString("t_compare.visitor_id = '0'", $joinCondition);
```

You can update as per your requirement.

File: app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php [hunk 2]
```diff
@@ -261,7 +261,7 @@ public function getConditionForJoin()
             return ['list_id' => $this->getListId()];
         }
 
-        return ['customer_id' => ['null' => true], 'visitor_id' => '0'];
+        return ['customer_id' => ['null' => true], 'visitor_id' => '0', 'list_id' => ['null' => true]];
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php:266]: Please add a comment explaining the fix

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php (hunk 2 above)
Comment (indykoning) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php:266]: To the code?
```suggestion
        // If no customer id, visitor id or list id is passed ensure we add all these fields as 0 or null to the query
        // To prevent data leaks.
        return ['customer_id' => ['null' => true], 'visitor_id' => '0', 'list_id' => ['null' => true]]; 
```

**Comment by indykoning** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php (hunk 2 above)
Comment (engcom-Hotel) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php:266]: Yes @indykoning

Comment (indykoning) [reply app/code/Magento/Catalog/Model/ResourceModel/Product/Compare/Item/Collection.php:266]: I've added the comment 👍

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
