### PR TITLE
[Bugfix] #7333 Unable to set negative custom option fixed price in admin view.

### LINKED ISSUE #7333: Unable to set negative custom option fixed price in admin view.
In versions 2.1.1 and 2.1.2, setting custom options for a product with fix price settings will not allow a negative value. I'm not sure if this is a simple ui problem or if there is a validator issue. Either way, this was always an option in Magento 1.x in which you can set discounts on an item via custom option. Uploading values via CSV works correctly, however making admin view changes for given product will fail validation via negative values.

### Preconditions

1. Magento 2.1.2
2. PHP 7

### Steps to reproduce

1. Freshly install Magento.
2. Create product with a custom option.
3. Attempt to place a negative value in the custom option price input.

### Expected result

1. Item validates and clients using the custom option allows a price reduction.

### Actual result

1. Cannot save item. Validator fails.

capture

### PR DESCRIPTION
**Pull request by dverkade**
Fixes the ability to set a negative custom option price in the backend. 

### Description
In Magento 1 it was possible to set a negative price change to a custom option. This PR fixes issue #7333 and makes it possible to set a negative price in the backend of Magento. This PR fixes the backend so that the negative price change can actually be entered in the Magento admin. There is a separate PR for the frontend changes which is PR #14975 

There also seem to be two other PR's for this issue which are stale and are not moving along: 
#13393
#14342

### Fixed Issues
1. magento/magento2#7333: Unable to set negative custom option fixed price in admin view.

### Manual testing scenarios
1. Create a new simple product in the backend and try to create new custom options where the price change has a negative value (for instance, "-10").

### CODE REVIEW

**Comment by miguelbalparda** [comment]
Tests are failing, any chance you can review them?

**Comment by dverkade** [comment]
Will work on this at the MM18NL contribution day.

**Comment by dverkade** [comment]
All tests are now green. Please proceed with processing this PR.

File: app/code/Magento/Catalog/Model/Product/Option/Validator/DefaultValidator.php [hunk 1]
```diff
@@ -159,13 +169,24 @@ protected function isInRange($value, array $range)
...
+        return $this->localeFormat->getNumber($value) < 0;
+    }
+
+    /**
+     * Check whether the value is a number
+     *
+     * @param string $value
+     * @return bool
+     */
+    protected function isNumber($value)
```
Comment (dmanners) [inline app/code/Magento/Catalog/Model/Product/Option/Validator/DefaultValidator.php]: So @dverkade looking over this pr again I think we should be making this method public. We are trying to stay away from protected and since these classes are built with inheritance in mind I would suggest that having this method public would allow for a user to create a new validator and change the `isNumber` functionality.

**Review by dmanners — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Model/Product/Option/Validator/DefaultValidator.php (hunk 1 above)
Comment (dverkade) [reply app/code/Magento/Catalog/Model/Product/Option/Validator/DefaultValidator.php]: Hi @dmanners, thanks for reviewing this. I have changed the function to public.

**Comment by dverkade** [comment]
Changes have been made, this PR can be processed / reviewed again.

**Comment by dmanners** [comment]
Thanks for those changes @dverkade there are two failures with the api tests but I will investigate these for you and then process this pr.

**Comment by ihor-sviziev** [comment]
Hi @dmanners,
Could you also look into https://github.com/magento/magento2/pull/14342?  Looks like these PRs fixing one issue

**Comment by dmanners** [comment]
Will do @ihor-sviziev thanks for the note.

**Comment by dmanners** [comment]
Hi @dverkade just to keep you updated I am checking with the core team to understand the reasoning for making negative prices not allowed a bit better, just to make sure that we do not miss something important out. After I have more information I will update you via this PR. Thanks for your patience.

**Comment by dmanners** [comment]
Hi @dverkade sorry for the delay. Would you be able to look into the test `Magento\Catalog\Api\ProductCustomOptionRepositoryTest::testAddNegative` It is used to validate that there are no negative prices added for options. In this case I would suggest that we test the addition of negative prices and validate that you can add them. This way if someone happens in the future to this feature we are able to see it.

**Comment by ihor-sviziev** [comment]
Hi @dverkade @dmanners ,
Looks like this issue was fixed by Magento core team https://github.com/magento/magento2/commit/8d4124cc4125e81d4a41ae71aca12c8e12f297a6

**Comment by dmanners** [comment]
Hi @ihor-sviziev thanks for this. @dverkade noticed this yesterday but this fix does not cover all the issues we noticed. The plan is to progress with this fix including the locale options.

**Comment by dmanners** [comment]
Hey @dverkade any update here on the test fixes I would love if we could progress here?

**Comment by dverkade** [comment]
Hi @dmanners,

I didn't have the time to look into this yet. I'll have some free time next weekend to check it out.

**Comment by dmanners** [comment]
Thanks @dverkade just drop a message here and tag me when it is done so I dont miss it.

**Comment by dmanners** [comment]
Hi @dverkade any update here?

**Comment by dverkade** [comment]
Hi @dmanners,

Thanks for your patience. This has been resolved by merging the 2.3 develop branch into this PR. Merge conflicts have been resolved. You can proceed with checking this PR.

**Comment by dmanners** [comment]
Thanks @dverkade got one more failure coming through.

```
Magento\Catalog\Api\ProductCustomOptionRepositoryTest::testGetList
Failed asserting that 10 matches expected 11.
```

Could you take a look at this for me.

**Comment by dverkade** [comment]
Hi @dmanners,

I have taken a look at this test and fixed the issue. The API functional test should now pass as well.

**Comment by sidolov** [comment]
Hi @dverkade , please, resolve merge conflict. 
Thanks!

**Comment by dverkade** [comment]
@dmanners @sidolov merge conflict is resolved.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-1862](https://jira.corp.magento.com/browse/ENGCOM-1862) has been created to process this Pull Request

**Comment by dverkade** [comment]
@dmanners @sidolov when will this PR be processed? Had been in this state since the 4th of October.

**Comment by magento-engcom-team** [comment]
Hi @dverkade. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.
