### PR TITLE
Fixed Magento reorder order id issue

### LINKED ISSUE #39089: v2.4.7-p1 Magento reorder -1 order numbers
### Preconditions and environment

- Magento version - 2.4.7

### Steps to reproduce

1) Open any order
2) Click reorder
3) Submit the order

### Expected result

The order number is unique 8 digits.

### Actual result

The order number is the same 8 digits as the previous order with “-1” added to the end.

### Additional information

Early before version 2.4.7, when we recreated an order, you would get a new unique number. In version 2.4.7, you get a number with the postfix '-1' added to the end. This appeared after the bug fix. [[Sales] Missing relation data when reorder](https://github.com/magento/magento2/issues/37028).

To fix this behavior, I suggest the following:

```
Index: vendor/magento/module-sales/Model/AdminOrder/Create.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/vendor/magento/module-sales/Model/AdminOrder/Create.php b/vendor/magento/module-sales/Model/AdminOrder/Create.php
--- a/vendor/magento/module-sales/Model/AdminOrder/Create.php	
+++ b/vendor/magento/module-sales/Model/AdminOrder/Create.php	(date 1724315876294)
@@ -2056,10 +2056,13 @@
                 'original_increment_id' => $originalId,
                 'relation_parent_id' => $oldOrder->getId(),
                 'relation_parent_real_id' => $oldOrder->getIncrementId(),
-                'edit_increment' => $oldOrder->getEditIncrement() + 1,
-                'increment_id' => $originalId . '-' . ($oldOrder->getEditIncrement() + 1)
+                'edit_increment' => $oldOrder->getEditIncrement() + 1
             ];
-            $quote->setReservedOrderId($orderData['increment_id']);
+
+            if($this->getSession()->getOrder()->getId()) {
+                $orderData['increment_id'] = $originalId . '-' . ($oldOrder->getEditIncrement() + 1);
+                $quote->setReservedOrderId($orderData['increment_id']);
+            }
         }
 
         return $orderData;

```

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by magentoabu**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#39089

### Manual testing scenarios (*)

1. Open any order, click reorder
2. Submit the order.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magentoabu** [comment]
@magento run all tests

**Comment by magentoabu** [comment]
@magento run Static Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @magentoabu,

Thanks for the contribution!

Please sign the CLA as it is required to process the PR further. Till the time we are moving this PR `On Hold`.

Thanks

**Comment by magentoabu** [comment]
> Hello @magentoabu,
> 
> Thanks for the contribution!
> 
> Please sign the CLA as it is required to process the PR further. Till the time we are moving this PR `On Hold`.
> 
> Thanks

CLA signed, please proceed further

**Comment by magentoabu** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
Hello @magentoabu,

It is still showing as unsigned. Please have a look at the cross mark in front of the `Adobe CLA Signed?` test.

Thanks

File: app/code/Magento/Sales/Model/AdminOrder/Create.php [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <?php
 /**
- * Copyright 2011 Adobe
+ * Copyright 2015 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Sales/Model/AdminOrder/Create.php]: It should be `2011` only as the file has been created in 2011 only

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @magentoabu,

Thanks for the contribution!

Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1).

And also look into the below review comment.

Thanks

File: app/code/Magento/Sales/Model/AdminOrder/Create.php (hunk 1 above)
Comment (magentoabu) [reply app/code/Magento/Sales/Model/AdminOrder/Create.php]: fixed

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @magentoabu, 

As mentioned [here](https://github.com/magento/magento2/pull/39399#pullrequestreview-2585913258), please also add automated test.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @magentoabu,

Just a friendly reminder to add an automated test for this PR.

Thanks

**Comment by magentoabu** [comment]
@engcom-Hotel I'm working on it

**Comment by engcom-Charlie** [comment]
It seems that review changes has been taken care hence moving it for Pending Review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @magentoabu,

Thanks for making the changes. I guess the integration test is failing due to the PR Changes. Please look into this.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved
Changes looks good for me.
All logical changes made in https://github.com/magento/magento2/pull/37298/ reverted.

Failed Functional Tests are not related to changes in R

**Comment by engcom-Charlie** [comment]
Fixed the integration test failure.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hi @magentoabu,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Open any order, click reorder
- Submit the order.



**Before:** :heavy_multiplication_x: 

Screenshot 2025-03-26 at 1 50 51 pm







**After:** :heavy_check_mark: 

**order number with unique 8 digits.**

Screenshot 2025-03-26 at 2 01 40 pm






Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Charlie** [comment]
The consistent test failure of Functional B2B is a known issue. Hence moving this PR to Merge in Progress.

**Build 1:**  
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39399/889b809ab8d69e88f7938b9020e26bdb/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/ff428befbea0a9b0/
image

**Build 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39399/5735671a4ab8fbf0b570fd1e2059b9a8/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/fa4e07a5eed0251d/

image


**Known Issue:**
[ACQE-7751](https://jira.corp.adobe.com/browse/ACQE-7751) : CatalogPriceRuleAndCustomerGroupMembershipArePersistedUnderLongTermCookieTest

**Comment by engcom-Charlie** [comment]
> Hi @engcom-Charlie, What is planned release version that will contain this fix?

Hi @Den4ik, this PR got merged and delivered in https://github.com/magento/magento2/commit/0db88bc4c5e6fffdd8174d45be5f61ac0ebce0cc in 2.4.9-alpha2 version
