### PR TITLE
Fix Issues 29213

### LINKED ISSUE #29213: Price Filter Into Grid not working for specific data
### Preconditions (*)
1. Magento versions: 2.3.4, 2.3.5, 2.4-develop

### Steps to reproduce (*)
1. Create Grid Block with deprecated functionality extended class Magento\Backend\Block\Widget\Grid\Extended
2. add column type price `
$this->addColumn(
            'total_price',
            [
                'header' => __('Total Price'),
                'index' => 'total_price',
                'type' => 'price',
                'currency_code' => (string)$this->_scopeConfig
                    ->getValue(Currency::XML_PATH_CURRENCY_BASE),
            ]
        );
`
3. apply a filter on this field. Example: '123a'

### Expected result (*)
1. apply filter price to 123 cost

### Actual result (*)
1. Throw exception `Notice: A non well formed numeric value encountered in vendor/magento/module-backend/Block/Widget/Grid/Column/Filter/Price.php on line 197` and redirect on some page

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by sarron93**
### Description (*)
If use Magento\Backend\Block\Widget\Grid\Column\Filter\Price::getCondition method and Magento\Backend\Block\Widget\Grid\Column\Filter\Price::getValue() return array with indexes 'from' or 'to' string data, then PHP throw notice exception and Magento break apply filter, redirect to some page

### Fixed Issues (if relevant)
1. Fixes magento/magento2#29213

### Manual testing scenarios (*)
1. Create Grid Block with deprecated functionality extended class Magento\Backend\Block\Widget\Grid\Extended
2. Add column type price `$this->addColumn( 'total_price', [ 'header' => __('Total Price'), 'index' => 'total_price', 'type' => 'price', 'currency_code' => (string)$this->_scopeConfig ->getValue(Currency::XML_PATH_CURRENCY_BASE), ] );`
3. Apply a filter on this field. Example: '123a'
4. Apply filter price to 123 cost

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sarron93** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @sarron93. Thank you for your collaboration, makes sense to me. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I kindly ask you to create a simple unit test that will test the case with passing values like "123a"?

Thank you!

**Comment by sarron93** [comment]
Hello @rogyar, class `Magento\Backend\Block\Widget\Grid\Column\Filter\Price` for some reason it is not covered by any tests, should I completely cover it with tests?

**Comment by rogyar** [comment]
Hi @sarron93. That's a good question. I would say, you may if you wish to 😎
But it's not necessary to cover all the cases, only the change provided by you. So you may create a new test and cover only the corresponding method.

Thank you.

**Comment by sarron93** [comment]
Hello @rogyar, i'm created unit test for getCondition method

**Comment by sarron93** [comment]
@magento run all tests

File: app/code/Magento/Backend/Test/Unit/Block/Widget/Grid/Column/Filter/PriceTest.php [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+use Magento\Directory\Model\Currency;
+use Magento\Directory\Model\Currency\DefaultLocator;
+use Magento\Framework\TestFramework\Unit\Helper\ObjectManager;
+use PHPUnit\Framework\MockObject\MockObject;
+use PHPUnit\Framework\TestCase;
+
+class PriceTest extends TestCase
+{
+    /** @var RequestInterface|MockObject  */
+    private $_requestMock;
```
Comment (rogyar) [inline app/code/Magento/Backend/Test/Unit/Block/Widget/Grid/Column/Filter/PriceTest.php]: Please, do not use underscores for properties name

**Comment by rogyar** [comment]
Good job! Please, check my minor recommendations. Also, please, check the failing static tests.
I will re-run the integration tests to double-check they are not related to the current change.

**Comment by rogyar** [comment]
@magento run Integration Tests

**Comment by sarron93** [comment]
@magento run Static Tests

**Comment by sarron93** [comment]
@magento run Integration Tests

**Comment by sarron93** [comment]
Hello @rogyar, integration and static tests complete after my changes

**Comment by rogyar** [comment]
@magento run all tests

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7962](https://jira.corp.magento.com/browse/ENGCOM-7962) has been created to process this Pull Request

**Comment by engcom-Kilo** [comment]
**Test passed.**
Tested with custom column (Sale Price) on Category, Products in Category.

**Before:**
If set value like 10a - will redirect to /admin_nkc1ww/catalog/ and in log added Exception.
before

**After:**
All variations of values for filter works correctly and returned result.
after
