### PR TITLE
Fix unable to remove parameter override for a webapi route

### LINKED ISSUE #33843: Unable to remove parameter override for a webapi route
I stumbled upon the necessity to remove a parameter override which is defined in a `webapi.xml`

```xml
<route url="/V1/customers" method="POST">
    <data>
        <parameter name="customer.extension_attributes.company_attributes.company_id" force="true">%company_id%</parameter>
    </data>
</route>
```

My initial though was setting `force="false"` should remove the paramter being overwritten by the `\Magento\Framework\Webapi\Rest\Request\ParamOverriderInterface`, however that was not the case.

Upon closer look into the schema converter `\Magento\Webapi\Model\Config\Converter` that's responsible to read the xml files I found out the line that's responsible to parse the attribute is incorrect.

```php
$force = $forceNode ? (bool)$forceNode->nodeValue : false;
```

Strings always evaluate to boolean true unless they have a value that's considered "empty" by PHP. [PHP empty documentation](https://www.php.net/manual/en/function.empty.php)
1. `""`
2. `"0"`

Current work around is setting a falsy value so that works
```xml
<route url="/V1/customers" method="POST">
    <data>
        <parameter name="customer.extension_attributes.company_attributes.company_id" force="0">%company_id%</parameter>
    </data>
</route>
```

### Preconditions (*)
1. vanilla Magento 2.4.3

### Steps to reproduce (*)
1. Define an existing or new webapi route paramter override with `force="false"`

### Expected result (*)
1. The parameter override should have the value set to `false` 

Using n98 to inspect (`Magento\Webapi\Model\ConfigInterface::getServices()['routes']['V1/customers']`)

```php
[
    "POST" => [
        "secure" => false,
        "service" => [
            "class" => "Magento\Customer\Api\AccountManagementInterface",
            "method" => "createAccount",
        ],
        "resources" => [
            "anonymous" => true,
        ],
        "parameters" => [
            "customer.extension_attributes.company_attributes.company_id" => [
                "force" => false,
                "value" => "%company_id%",
            ],
        ],
    ],
]

```

### Actual result (*)
1. The paramter override still has the value `true`

Using n98 to inspect
```php
[
    "POST" => [
        "secure" => false,
        "service" => [
            "class" => "Magento\Customer\Api\AccountManagementInterface",
            "method" => "createAccount",
        ],
        "resources" => [
            "anonymous" => true,
        ],
        "parameters" => [
            "customer.extension_attributes.company_attributes.company_id" => [
                "force" => true, # this is still true
                "value" => "%company_id%",
            ],
        ],
    ],
]
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by gowrizrh**
### Description (*)
This PR contains the changes to fix #33843 - the `force` attribute in a `webapi.xml` is ignored in certain cases.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#33843

### Manual testing scenarios (*)
1. Redefine a route parameter override in a new `webapi.xml`
2. Verify the webapi config with something like the `n98 dev:console` 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by gowrizrh** [comment]
@magento run all tests

**Comment by gowrizrh** [comment]
@magento run Unit Tests

**Comment by gowrizrh** [comment]
@magento run all tests

File: app/code/Magento/Webapi/Model/Config/Converter.php [hunk 1]
```diff
@@ -138,7 +138,7 @@ protected function convertMethodParameters($parameters)
             }
             $name = $parameter->attributes->getNamedItem('name')->nodeValue;
             $forceNode = $parameter->attributes->getNamedItem('force');
-            $force = $forceNode ? (bool)$forceNode->nodeValue : false;
+            $force = filter_var($forceNode ? $forceNode->nodeValue : false, FILTER_VALIDATE_BOOLEAN);
```
Comment (Den4ik) [inline app/code/Magento/Webapi/Model/Config/Converter.php]:
```suggestion
            $force = $forceNode ? filter_var($forceNode->nodeValue, FILTER_VALIDATE_BOOLEAN) : false;
```

**Review by Den4ik — CHANGES_REQUESTED** [review]
@gowrizrh Thanks for contribution.
Please look at suggested changes

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved.

Looks good for me

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9186](https://jira.corp.magento.com/browse/ENGCOM-9186) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Static Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @gowrizrh,

Thanks for the contribution!

Some of the tests are failing, please look into this. And Also I am unable to reproduce the issue. Can you please help us with the exact commands or steps in order to reproduce the issue?

Thanks

**Comment by Den4ik** [comment]
@engcom-Hotel In fact failed static test is not related to this PR because it's failed on different function. I believe that we should not mix fixes of issues with not related fixes.
But as fast solution @gowrizrh could you please add phpcs ignore?

**Comment by gowrizrh** [comment]
Sure, I'll post ways to reproduce and also add phpcs ignore and update it shortly.

**Comment by engcom-Charlie** [comment]
Hi @gowrizrh,

Thank you for your contribution!

Can you provide any information on this [comment](https://github.com/magento/magento2/pull/33844#issuecomment-920847490)

Thank you!

**Comment by gowrizrh** [comment]
We can reproduce this using [n98-magerun2](https://github.com/netz98/n98-magerun2) which is a cli tool for Magento.

1. Install vanilla Magento 2.4.3
2. Create an example module and define a `webapi.xml`
3. Attempt to override the `/V1/customers` core webapi route using the following code

```
<!-- Vendor/Module/etc/webapi.xml -->

    <route url="/V1/customers" method="POST">
        <data>
            <parameter name="customer.extension_attributes.company_attributes.company_id" force="false">%company_id%</parameter>
        </data>
    </route>
```

**Note that our intention is to make the force attribute false. `force="false"`**

Run `bin/magento setup:upgrade`

Now using `n98-magerun2` fire up the dev console using `bin/n98-magerun2 dev:console`

Once it's available, we can inspect what's stored in the merged xml file. You should be able to run the following piece of code in the shell / REPL

```
$config = $di->create(\Magento\Webapi\Model\ConfigInterface::class);

$customer_route_config = $config->getServices()['routes']['/V1/customers']
```

The `$customer_route_config` should contain an array of configs that is created for the route `/V1/customers`, the route config should contain `parameters` which is another array of just configurations. Basically, the `force` field will never be `false` even though we define it as `false` in our example earlier.


```
 [
     "POST" => [
       "secure" => false,
       "service" => [
         "class" => "Magento\Customer\Api\AccountManagementInterface",
         "method" => "createAccount",
       ],
       "resources" => [
         "anonymous" => true,
       ],
       "parameters" => [
         "customer.extension_attributes.company_attributes.company_id" => [
           "force" => true, <------ THIS SHOULD BE FALSE
           "value" => "%company_id%",
         ],
       ],
     ],
   ]
```

**Comment by gowrizrh** [comment]
@magento run all tests

**Comment by gowrizrh** [comment]
@Den4ik @engcom-Charlie i'm not sure why these tests would report failure in github, i can see that no tests have failed in any of the test suites.

image

**Comment by engcom-Charlie** [comment]
Hi @gowrizrh,

I have checked the Allure report from the Details link and few tests are failing from Functional Tests EE and Static Test.

Functional EE
image

Static Test
image

Can you please recheck it.

Thank you!

**Comment by gowrizrh** [comment]
it looks like the phpcs change wasn't pushed to GH in my last comment. however i have no idea what the Functional EE test failure is.

i'll be just rerunning all tests.

**Comment by gowrizrh** [comment]
@magento run all tests

**Comment by gowrizrh** [comment]
@engcom-Charlie 

this time it says it has failed `Functional Tests EE` however i cannot see any errors in the build report. these automated builds are not very stable at all.

image

**Comment by engcom-Charlie** [comment]
Hi @gowrizrh,

Yeah, Perhaps there is some issue for now. 

Functional Tests EE are showing failed but when I am checking the detail report, there is no single test failure. All the Functional EE tests are successfully passed so moving this issue further.

image


Thank you!

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE
