### PR TITLE
Fix: CustomerAddressId missing for backend orders

### LINKED ISSUE #28793: Magento 2 CustomerAddressId missing for backend orders
### Preconditions (*)

In Magento 2 ,for backend orders created the customer_address_id is missing/NULL for sale order addresses
1.2.2.8
2.2.3.3

### Steps to reproduce (*)

1.Go to Magento 2 backend login. Create a new order for a new customer from Sales->Orders->Create New Order After the creation of Order you can see the customer_address_id in sales_order_address table as NULL for both shipping and billing address.
2.Again create a new order with the customer created last time and choose the address created in last order with the shipping address same as billing.

After the order creation when you check the sales_order_address table,we can see the customer_address_id is available for billing address but not for shipping address .

### Expected result (*)

1.The customer_address_id should be updated in sales_order_address table for botth billing and shipping address
2.The customer_address_id should be updated in sales_order_address table for shipping address

### Actual result (*)

1. NULL value for customer_address_id in both 
2.NULL value for customer_address_id in shipping address 

### Additional information
- issue has been confirmed on the latest `2.4-develop` code, detailed steps https://github.com/magento/magento2/issues/28793#issuecomment-647474485
- main precondition: when creating new address select checkbox use same for shipping address
- example of real business scenario https://github.com/magento/magento2/issues/28793#issuecomment-646537298

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by engcom-Echo**
### Description (*)
Added validate 'CustomerAddressId' in the quote for a newly created customer.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28793

### Manual testing scenarios (*)

See magento/magento2#28793

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Echo** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Quote/Model/CustomerManagementTest.php [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+        return $quote;
+    }
+
+    /**
+     * Get search criteria
+     *
+     * @param string $filterValue
+     * @return SearchCriteria
+     */
+    private function getSearchCriteria($filterValue)
```
Comment (ihor-sviziev) [inline dev/tests/integration/testsuite/Magento/Quote/Model/CustomerManagementTest.php]:
```suggestion
    private function getSearchCriteria(string $filterValue): SearchCriteria
```

File: dev/tests/integration/testsuite/Magento/Quote/Model/CustomerManagementTest.php [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+        self::assertEquals(0, $quote->getShippingAddress()->getCustomerAddressId());
+    }
+
+    /**
+     * Returns quote by reserved order id.
+     *
+     * @param string $reservedOrderId
+     * @return CartInterface
+     */
+    private function getQuote(string $reservedOrderId)
```
Comment (ihor-sviziev) [inline dev/tests/integration/testsuite/Magento/Quote/Model/CustomerManagementTest.php]:
```suggestion
    private function getQuote(string $reservedOrderId): CartInterface
```

File: dev/tests/integration/testsuite/Magento/Quote/Model/CustomerManagementTest.php [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+        $this->quoteRepository = $this->objectManager->create(QuoteRepository::class);
+        $this->customerManagemet = $this->objectManager->create(CustomerManagement::class);
+        $this->searchCriteriaBuilder = $this->objectManager->create(SearchCriteriaBuilder::class);
+        $this->filterBuilder = $this->objectManager->create(FilterBuilder::class);
+    }
+
+    /**
+     * @magentoDataFixture Magento/Sales/_files/quote_with_new_customer.php
+     */
+    public function testCustomerAddressIdQuote()
```
Comment (ihor-sviziev) [inline dev/tests/integration/testsuite/Magento/Quote/Model/CustomerManagementTest.php]:
```suggestion
    public function testCustomerAddressIdQuote(): void
```

File: app/code/Magento/Quote/Model/CustomerManagement.php [hunk 4]
```diff
@@ -100,11 +105,47 @@ public function populateCustomerInfo(QuoteEntity $quote)
         }
     }
 
+    /**
+     * Validate 'CustomerAddressId' in quote for a newly created customer.
+     *
+     * @param QuoteEntity $quote
+     * @return void
+     */
+    public function validateCustomerAddressId($quote): void
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/CustomerManagement.php]: Can we make this method private and define argument types?
```suggestion
    private function validateCustomerAddressId(QuoteEntity $quote): void
```

Also it'snot validating, it's populating customer address

File: app/code/Magento/Quote/Model/CustomerManagement.php [hunk 5]
```diff
@@ -3,14 +3,18 @@
...
 namespace Magento\Quote\Model;
 
-use Magento\Customer\Api\CustomerRepositoryInterface as CustomerRepository;
 use Magento\Customer\Api\AccountManagementInterface as AccountManagement;
 use Magento\Customer\Api\AddressRepositoryInterface as CustomerAddressRepository;
-use Magento\Quote\Model\Quote as QuoteEntity;
+use Magento\Customer\Api\CustomerRepositoryInterface as CustomerRepository;
+use Magento\Customer\Model\AddressFactory;
 use Magento\Framework\App\ObjectManager;
+use Magento\Framework\Validator\Exception;
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/CustomerManagement.php]: Could you import it as ValidatorException? It will not be clear that `throw new Exception` is not the same as `throw new \Exception`

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

File: app/code/Magento/Quote/Model/CustomerManagement.php [hunk 6]
```diff
@@ -100,11 +105,47 @@ public function populateCustomerInfo(QuoteEntity $quote)
         }
     }
 
+    /**
+     * Validate 'CustomerAddressId' in quote for a newly created customer.
+     *
+     * @param QuoteEntity $quote
+     * @return void
+     */
+    private function validateCustomerAddressId(QuoteEntity $quote): void
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/CustomerManagement.php]: I wrote it above - but probably you missed it - this method isn't doing any validation, it's just filling it

File: app/code/Magento/Quote/Model/CustomerManagement.php [hunk 7]
```diff
@@ -100,11 +105,47 @@ public function populateCustomerInfo(QuoteEntity $quote)
...
+        }
+
+        if (!$quote->getShippingAddress()->getSameAsBilling() && $customer->getDefaultShipping()) {
+            $quote->getShippingAddress()->importCustomerAddressData(
+                $this->customerAddressRepository->getById($customer->getDefaultShipping())
+            );
+            $quote->getShippingAddress()->setCustomerAddressId($customer->getDefaultShipping());
+        } else {
+            $quote->getShippingAddress()->setCustomerAddressId(0);
+        }
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/CustomerManagement.php]: I see quite similar code in https://github.com/magento/magento2/pull/29139/files#diff-9d928aadb5e8377f0a87b2ca364c48b7R91-R105
Is there any way to not copy paste, but unify it for all needed cases instead? I don't believe we need to run it twice.

File: app/code/Magento/Quote/Test/Unit/Model/CustomerManagementTest.php [hunk 8]
```diff
@@ -147,7 +147,7 @@ protected function setUp(): void
 
     public function testPopulateCustomerInfo()
     {
-        $this->quoteMock->expects($this->once())
+        $this->quoteMock->expects($this->exactly(2))
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Test/Unit/Model/CustomerManagementTest.php]: Is there any reasons to check how exactly times it was ran? AFAIK method getCustomer caches result, but it will not cause performance issues in case if it will be ran more than 1 or 2 times, but in future this test will fail if amount of running this method will change. 
Maybe we can replace it to `$this->atLeastOnce()`?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7885](https://jira.corp.magento.com/browse/ENGCOM-7885) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**
NULL value for customer_address_id in shipping address
#29139MainDb


**After:**
The customer_address_id has value in sales_order_address table for botth billing and shipping address
#29139PRDb
