### PR TITLE
magento/magento2#39236: Magento 2.4.7 update (mini)cart no decimal qty allowed

### LINKED ISSUE #39236: Magento 2.4.7 update (mini)cart no decimal qty allowed
### Preconditions and environment

- Magento 2.4.7-p2
- Webshop sells fabrics per 10 cm with minimum of 0.5 meter

### Steps to reproduce

1. Add product with qty 0.5 to cart
2. Click on change (pencil) in minicart
3. Change qty to 0.7 and click update

### Expected result

Expected that 0.7 is in cart

### Actual result

In cart is 1

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by quterorta**
### Description (*)
The issue was related to the wrong parsing float/double values from the string, depending on the used decimal separator

### Related Pull Requests
Fixes magento/magento2#39236

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Create an additional store view (or use an existing one) with the NL locale zone
2. Choose some product and set "Qty Uses Decimals" to Yes for it
3. On the front add a product to the cart
4. In the mini-cart try to change qty to the decimal value

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rostilos** [comment]
@magento run all tests

**Comment by quterorta** [comment]
@magento run all tests

**Comment by quterorta** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @quterorta,

Thanks for the contribution!

The changes seems fine to us, but please add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/) and please fix the static test failures.

Other failures seems flaky to us.

Thanks

**Comment by engcom-Dash** [comment]
@quterorta Thank you for the contribution!  I am taking care of the fixes for the static and automated tests.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Static Tests, Unit Tests, Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Fixed failing static test cases. Also, added new Unit Test Case.

File: lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+ * Copyright 2025 Adobe
+ * All Rights Reserved.
+ */
+declare(strict_types=1);
+
+namespace Magento\Framework\Filter\Test\Unit;
+
+use Magento\Framework\Filter\LocalizedToNormalized;
+use PHPUnit\Framework\TestCase;
+use NumberFormatter;
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php:12]: This import is not in used, I guess we can remove it.

File: lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php [hunk 2]
```diff
@@ -0,0 +1,81 @@
...
+{
+
+    /**
+     * @param string $value
+     * @param array $options
+     * @param string|array $expectedValues
+     *
+     * @dataProvider localizedToNormalizedDataProvider
+     */
+    public function testLocalizedToNormalized($value, $options, $expectedValue)
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php]: Please add parameter type declarations

for e.g.
```suggestion
    public function testLocalizedToNormalized(string $value, $options, $expectedValue)
```

File: lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    {
+        $filter = new LocalizedToNormalized($options);
+        $this->assertEquals($expectedValue, $filter->filter($value));
+    }
+
+    /**
+     * @return array
+     */
+    public static function localizedToNormalizedDataProvider()
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php]: Add a return type for this method.

File: app/code/Magento/Checkout/Test/Unit/Model/SidebarTest.php [hunk 4]
```diff
@@ -140,19 +140,25 @@ public function testRemoveQuoteItem()
...
-    public function testUpdateQuoteItem()
+    /**
+     * @param string $locale
+     * @param int|string $itemId
+     * @param int|string|float $expectedItemQty
+     * @param int|string|float $itemQty
+     *
+     * @dataProvider dataProviderUpdateQuoteItem
+     */
+    public function testUpdateQuoteItem($locale, $itemId, $expectedItemQty, $itemQty)
```
Comment (engcom-Hotel) [inline app/code/Magento/Checkout/Test/Unit/Model/SidebarTest.php]: Please add parameter type declarations.

File: app/code/Magento/Checkout/Test/Unit/Model/SidebarTest.php [hunk 5]
```diff
@@ -178,4 +184,18 @@ public function testUpdateQuoteItemWithZeroQty()
 
         $this->assertEquals($this->sidebar, $this->sidebar->updateQuoteItem($itemId, $itemQty));
     }
+
+    /**
+     * @return array
+     */
+    public static function dataProviderUpdateQuoteItem()
```
Comment (engcom-Hotel) [inline app/code/Magento/Checkout/Test/Unit/Model/SidebarTest.php]: Add method return type declaration

File: lib/internal/Magento/Framework/Filter/LocalizedToNormalized.php [hunk 6]
```diff
@@ -60,14 +61,16 @@ public function setOptions(?array $options = null)
...
-     * @param  string $value Value to normalized
+     * @param string $value Value to normalized
      * @return string|array The normalized value
      */
     public function filter($value)
     {
         if (is_numeric($value)) {
-            $numberParse = new NumberParse($this->_options['locale'], NumberFormatter::PATTERN_DECIMAL);
-            return (string) $numberParse->filter($value);
+            $numberParse = new NumberParse(
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Filter/LocalizedToNormalized.php:77]: Removing `NumberFormatter::PATTERN_DECIMAL` as a second parameter from here might introduce backward compatibility issues. Please consider using an alternative approach to handle this.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @engcom-Dash,

Thanks for making the changes!

Please refer to the below review comments.

Thanks

File: lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php (hunk 1 above)
Comment (engcom-Dash) [reply lib/internal/Magento/Framework/Filter/Test/Unit/LocalizedToNormalizedTest.php:12]: We are using the NumberFormatter now hence keeping it in the file

**Comment by engcom-Dash** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE
