### PR TITLE
Fix #12802 - allow to override preference over CartInterface and return correct object from QuoteRepository

### LINKED ISSUE #12802: QuoteRepository get methods won't return CartInterface but Quote model
### Preconditions
1. Magento 2.2.0 CE
2. PHP 7.024

### Steps to reproduce
1. Create custom module with following etc/di.xml` file:
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <preference for="Magento\Quote\Api\Data\CartInterface" type="Vendor\Module\Model\Quote" />
</config>
```
2. Create `\Vendor\Module\Model\Quote` object which extends `\Magento\Quote\Model\Quote`.
3. Now execute following code:
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$cartRepository = $objectManager->create(\Magento\Quote\Api\CartRepositoryInterface::class);
$cartRepository->get(70); // use existing quote ID
```
### Expected result
1. The result will be an object of instance `Vendor\Module\Model\Quote`

### Actual result
1. Actual result is an object of instance `Magento\Quote\Model\Quote`

It's caused by invalid vendor/magento/module-quote/Model/QuoteRepository.php::loadQuote method which uses `Magento\Quote\Model\QuoteFactory` in the very first line instead of `Magento\Quote\Api\Data\CartInterfaceFactory`.

The solution is to override QuoteRepository's loadQuote method and use CartInterfaceFactory.

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #12802 

### Fixed Issues (if relevant)

1. magento/magento2#12802: QuoteRepository get methods won't return CartInterface but Quote model

### Manual testing scenarios (*)

Steps are described in #12802 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

File: app/code/Magento/Quote/Model/QuoteRepository.php [hunk 1]
```diff
@@ -203,13 +214,13 @@ public function delete(\Magento\Quote\Api\Data\CartInterface $quote)
...
+     * @return CartInterface
      */
     protected function loadQuote($loadMethod, $loadField, $identifier, array $sharedStoreIds = [])
     {
-        /** @var Quote $quote */
-        $quote = $this->quoteFactory->create();
-        if ($sharedStoreIds) {
+        /** @var CartInterface $quote */
+        $quote = $this->cartFactory->create();
+        if ($sharedStoreIds && $quote instanceof Quote) {
```
Comment (orlangur) [inline app/code/Magento/Quote/Model/QuoteRepository.php]: Maybe just check `method_exists('setSharedStoreIds')` ?

**Review by orlangur — CHANGES_REQUESTED** [review]
Really nice @Bartlomiejsz!

According to my understanding such change is backward compatible, asking @sivaschenko to double check.

Please mark `quoteFactory` property as deprecated.

After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

File: app/code/Magento/Quote/Model/QuoteRepository.php (hunk 1 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @orlangur actually this method does not exist I believe, it is declared only in `Quote` class docblock. Maybe we should change this to `$quote instanceof \Magento\Framework\DataObject || method_exists($quote, 'setSharedStoreIds')`? Because in both situations method should probably be called.

Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @orlangur please check current solution 😉

Comment (orlangur) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: Please grep for `share.*store` to find whether we get it somewhere.

It works and is placed in DocBlock due to `DataObject` providing magic method `__call`. I would use it for a legacy `Quote` only or would check with `method_exists` so it won't break any implementation just covering `CartInterface` but not extending `AbstractModel`.

Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: I haven't found any usage that could be broken using grep. Please check now, I changed DataModel to Quote @orlangur

File: app/code/Magento/Quote/Model/QuoteRepository.php [hunk 2]
```diff
@@ -77,39 +81,47 @@ class QuoteRepository implements \Magento\Quote\Api\CartRepositoryInterface
...
+     * @param QuoteCollectionFactory|null $collectionFactory
+     * @param CartInterfaceFactory|null $cartFactory
      * @SuppressWarnings(PHPMD.UnusedFormalParameter)
      */
     public function __construct(
         QuoteFactory $quoteFactory,
         StoreManagerInterface $storeManager,
-        \Magento\Quote\Model\ResourceModel\Quote\Collection $quoteCollection,
-        \Magento\Quote\Api\Data\CartSearchResultsInterfaceFactory $searchResultsDataFactory,
-        JoinProcessorInterface $extensionAttributesJoinProcessor,
```
Comment (sivaschenko) [inline app/code/Magento/Quote/Model/QuoteRepository.php]: I don't think it's a good idea to change names of the parameters, as they could be referenced i.e. in arguments DI configuration.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @Bartlomiejsz thanks for the pull request, please see my review comment

File: app/code/Magento/Quote/Model/QuoteRepository.php (hunk 2 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @sivaschenko previously Codacy result was failed due to length of those, should I ignore this then and change them back to length not accepted by Codacy?

Comment (orlangur) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @Bartlomiejsz yep, feel free to ignore any of those, as we removed such check for PHPMD intentionally. I heard Codacy is going to be eliminated soon.

File: app/code/Magento/Quote/Model/QuoteRepository.php (hunk 1 above)
Comment (orlangur) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: I meant remove this condition if no getter called but this is not true: https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Quote/Model/ResourceModel/Quote.php#L63

Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @orlangur what should I do with this condition then?

File: app/code/Magento/Quote/Model/QuoteRepository.php (hunk 2 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @sivaschenko @orlangur done

File: app/code/Magento/Quote/Model/QuoteRepository.php [hunk 3]
```diff
@@ -203,13 +215,15 @@ public function delete(\Magento\Quote\Api\Data\CartInterface $quote)
...
      */
     protected function loadQuote($loadMethod, $loadField, $identifier, array $sharedStoreIds = [])
     {
-        /** @var Quote $quote */
-        $quote = $this->quoteFactory->create();
-        if ($sharedStoreIds) {
+        /** @var CartInterface $quote */
+        $quote = $this->cartFactory->create();
+        if ($sharedStoreIds &&
+            ($quote instanceof Quote || method_exists($quote, 'setSharedStoreIds'))
```
Comment (orlangur) [inline app/code/Magento/Quote/Model/QuoteRepository.php]: Remove first part of condition. `method_exists` is sufficient.

**Review by orlangur — CHANGES_REQUESTED** [review]
After changes are applied and all builds are green, please squash them into a single commit so that we have perfectly clean history 😉

File: app/code/Magento/Quote/Model/QuoteRepository.php (hunk 3 above)
Comment (Bartlomiejsz) [reply app/code/Magento/Quote/Model/QuoteRepository.php]: @orlangur done

**Comment by Bartlomiejsz** [comment]
@orlangur commits are squashed now

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-4679](https://jira.corp.magento.com/browse/ENGCOM-4679) has been created to process this Pull Request
