### PR TITLE
Fix for scope bug in Catalog URL resource

### LINKED ISSUE #38393: Scope bug in Catalog URL resource (_getCategories)
**Bug**
The following condition is obviously invalid:
<https://github.com/magento/magento2/blob/03621bbcd75cbac4ffa8266a51aa2606980f4830/app/code/Magento/Catalog/Model/ResourceModel/Url.php#L415>

**Explanation**
The resulting query is:
```
SELECT
`main*table\`.`entity*id`,
`main*table\`.`parent*id`,
`main_table\`.`level`,
IF(c.value*id > 0, c.value, c.value) AS `is*active`,
`main_table\`.`path`
FROM
`catalog*category_entity\` AS `main*table`
LEFT JOIN `catalog*category_entity_int\` AS `d` ON d.attribute_id = 46 AND d.store_id = 0 AND d.entity_id = main_table.entity*id
LEFT JOIN `catalog*category_entity_int\` AS `c` ON c.attribute_id = 46 AND c.store_id = 3 AND c.entity_id = main_table.entity*id
WHERE (main*table.entity*id IN(...))
```

Attribute `is_active\` is joined twice on both the store (`c\`) and default scope (`d\`). If there is no value available on the store scope (`c.value\`) the default scope (`d.value`) should be used instead.

**Solution**
The condition from line 415:
```
$isActiveExpr = $connection->getCheckSql('c.value_id > 0', 'c.value', 'c.value');
```

Should be changed to:
```
$isActiveExpr = $connection->getCheckSql('c.value_id IS NOT NULL', 'c.value', 'd.value');
```
##  

*Note: This bug might not be affecting any Magento code (depends if the `is_active` flag is actually being used somewhere).*

### PR DESCRIPTION
**Pull request by pmzandbergen**
### Description (*)
Fallback to default scope for the `is_active` category attribute is not working as expected on Url Resource Model. This commit adds a fallback to default scope if there is no value defined on the store scope.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#38393

### Manual testing scenarios (*)
1. Create 3 categories
2. Disable one category on the default scope
3. Disable another category on the store scope
4. Execute `\Magento\Catalog\ResourceModel\Url::getCategories(..)`
5. Validate the values of `is_active` on the returned data objects

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
Hello @pmzandbergen 
Thank you for your contribution
But we need to check this changes history

**Comment by pmzandbergen** [comment]
Any update? :)

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by engcom-Hotel** [comment]
We have created a Guild issue for this PR here:

https://github.com/magento-commerce/quality-guild/issues/82

Hence moving this PR `On Hold` for now. We will proceed with this as per the discussion in the guild.

Thanks

**Comment by pmzandbergen** [comment]
> We have created a Guild issue for this PR here:
> 
> https://github.com/magento-commerce/quality-guild/issues/82
> 
> Hence moving this PR `On Hold` for now. We will proceed with this as per the discussion in the guild.
> 
> Thanks

Unfortunately I don't have access to the Magento Commerce repository. I'll wait patiently.

**Comment by engcom-Hotel** [comment]
We have received go-ahead on this PR from the internal team, hence we are moving it to appropriate bucket.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @pmzandbergen,

Thanks for the collaboration!

The changes seems good to us, but I guess we can add an automated test for this fix in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

So please do the needful.

Thanks

**Comment by pmzandbergen** [comment]
> Hello @pmzandbergen,
> 
> 
> 
> Thanks for the collaboration!
> 
> 
> 
> The changes seems good to us, but I guess we can add an automated test for this fix in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).
> 
> 
> 
> So please do the needful.
> 
> 
> 
> Thanks

Will do after holiday 🏝️

**Comment by engcom-Hotel** [comment]
Hello @pmzandbergen,

Have you got a chance to look into this PR for further progress?

Thanks

**Comment by pmzandbergen** [comment]
> Hello @pmzandbergen,
> 
> 
> 
> Have you got a chance to look into this PR for further progress?
> 
> 
> 
> Thanks

Yes, tests will be committed tomorrow.

**Comment by pmzandbergen** [comment]
@engcom-Hotel my apologies, busy with after-holiday tasks. I'll finish the tests and commit them tomorrow (23th, CEST).

**Comment by engcom-Hotel** [comment]
Sure, @pmzandbergen. I understand. Thank you for the update.

**Comment by pmzandbergen** [comment]
@engcom-Hotel an integration test has been added.

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+    /**
+     * Test that scope is respected for the is_active flag.
+     *
+     * @return void
+     * @magentoDataFixture Magento/Catalog/_files/categories_disabled_different_scopes.php
+     */
+    public function testIsActiveScope(): void
+    {
+        $categories = $this->urlResource->getCategories([3, 4, 5], 1);
+        $this->assertTrue((bool) $categories[3]->getIsActive());
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php]: The test uses `assertTrue` and `assertFalse` with a cast to (bool). While this works, using `assertSame` ensures stricter type checking and avoids potential issues with unexpected data types.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @pmzandbergen,

Thanks for making the changes as per the review comment. but please use parameterized fixture format, as the format used for creating fixtures is deprecated. Also  please fix the static test failures and review comment below.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+        ], 'c4'),
+    ]
+    public function testIsActiveScope(): void
+    {
+        // Get Store ID
+        $storeId = (int) $this->storeManager->getStore('default')->getId();
+
+        // Get Category IDs
+        $fixtureNames = ['c1', 'c2', 'c3', 'c4'];
+        $categoryIds = array_combine($fixtureNames, array_map(function (string $fixtureName): int {
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php]: Here error `Illegal array key type array` might arises because the `array_combine` function is used with `$fixtureNames` as keys and the result of `array_map` as values. However, the `array_map` callback returns an array, which is not valid as array keys.

Replacing the `array_combine` function with a foreach loop to ensure that `$categoryIds` is constructed with valid scalar keys.

```
$categoryIds = [];
foreach ($fixtureNames as $fixtureName) {
    $categoryIds[$fixtureName] = (int) $this->fixtures->get($fixtureName)->getId();
}
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @pmzandbergen,

Please have a look into the below review comment and also fix the failed static tests.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php [hunk 3]
```diff
@@ -0,0 +1,109 @@
+<?php
+/**
+ * Copyright © Magento, Inc. All rights reserved.
+ * See COPYING.txt for license details.
+ */
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Catalog/Model/ResourceModel/UrlTest.php]:
```suggestion
/**
 * Copyright 2025 Adobe
 * All Rights Reserved.
 */
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @pmzandbergen,

We are still having a static test failure related to copyright. Please use copyright as below.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE
