### PR TITLE
Exception are not translated to store scope

### LINKED ISSUE #31351: [GraphQl] Exception are not translated to store scope.
### Preconditions (*)

Reproduced on
1. Magento 2.3.5-p2
2. Magento 2.4.1

### Steps to reproduce (*)

1. Set the locale of a store to anything but en_US.
2. Create a translation file/database entry with one of the translatable exception strings (eg: 'currentPage value must be greater than 0.' to 'This text is translated')
3. Make a GraphQl request that will cause the exception to trigger with the Store header for the store set in 1.
````
query productList{
    products( currentPage: 0) {
        items {
            id
            name
        }
    }
}
````

### Expected result (*)

````
{
    "errors": [
        {
            "message": "This text is translated.",
            "extensions": {
                "category": "graphql-input"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "products"
            ]
        }
    ],
    "data": {
        "products": null
    }
}
````

### Actual result (*)

````
{
    "errors": [
        {
            "message": "currentPage value must be greater than 0.",
            "extensions": {
                "category": "graphql-input"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "products"
            ]
        }
    ],
    "data": {
        "products": null
    }
}
````

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rikwillems**
#31351

### Related Pull Requests
https://github.com/magento/inventory/pull/3318

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Functional Tests B2b, WebAPI Tests

**Comment by slavvka** [comment]
@magento run Semantic Version Checker

File: app/code/Magento/GraphQl/Controller/GraphQl.php [hunk 1]
```diff
@@ -114,7 +121,8 @@ public function __construct(
         QueryFields $queryFields,
         JsonFactory $jsonFactory = null,
         HttpResponse $httpResponse = null,
-        ContextFactoryInterface $contextFactory = null
+        ContextFactoryInterface $contextFactory = null,
+        AreaList $areaList
```
Comment (Den4ik) [inline app/code/Magento/GraphQl/Controller/GraphQl.php]:
```suggestion
        AreaList $areaList = null
```

File: app/code/Magento/GraphQl/Controller/GraphQl.php [hunk 2]
```diff
@@ -127,6 +135,7 @@ public function __construct(
         $this->jsonFactory = $jsonFactory ?: ObjectManager::getInstance()->get(JsonFactory::class);
         $this->httpResponse = $httpResponse ?: ObjectManager::getInstance()->get(HttpResponse::class);
         $this->contextFactory = $contextFactory ?: ObjectManager::getInstance()->get(ContextFactoryInterface::class);
+        $this->areaList = $areaList;
```
Comment (Den4ik) [inline app/code/Magento/GraphQl/Controller/GraphQl.php]:
```suggestion
        $this->areaList = $areaList ?: ObjectManager::getInstance()->get(AreaList::class);
```

**Review by Den4ik — CHANGES_REQUESTED** [review]
@rikwillems Thanks for your contribution.
Please look at my comments and update adding of new constructor params based on [Backward Compatibility Policy](https://devdocs.magento.com/contributor-guide/backward-compatible-development/#php)

File: app/code/Magento/GraphQl/Controller/GraphQl.php (hunk 2 above)
Comment (rikwillems) [reply app/code/Magento/GraphQl/Controller/GraphQl.php]: Please see the updated PR.

**Comment by Den4ik** [comment]
@magento run all tests

File: app/code/Magento/GraphQl/Controller/GraphQl.php [hunk 3]
```diff
@@ -127,6 +135,7 @@ public function __construct(
         $this->jsonFactory = $jsonFactory ?: ObjectManager::getInstance()->get(JsonFactory::class);
         $this->httpResponse = $httpResponse ?: ObjectManager::getInstance()->get(HttpResponse::class);
         $this->contextFactory = $contextFactory ?: ObjectManager::getInstance()->get(ContextFactoryInterface::class);
+        $this->areaList = $areaList ?: ObjectManager::getInstance()->get(AreaList::class);;
```
Comment (Den4ik) [inline app/code/Magento/GraphQl/Controller/GraphQl.php]: Please remove double semicolon at the end.

**Review by Den4ik — CHANGES_REQUESTED** [review]
@rikwillems Thanks for the update. Please see another small request below

File: app/code/Magento/GraphQl/Controller/GraphQl.php (hunk 3 above)
Comment (rikwillems) [reply app/code/Magento/GraphQl/Controller/GraphQl.php]: Oeps... this is removed now.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests EE

**Comment by Den4ik** [comment]
@magento run WebAPI Tests. Functional Tests EE

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests EE

File: app/code/Magento/GraphQl/Controller/GraphQl.php [hunk 4]
```diff
@@ -88,6 +90,11 @@ class GraphQl implements FrontControllerInterface
      * @var ContextFactoryInterface
      */
     private $contextFactory;
+    
+    /** 
+     * @var AreaList $areaList
+     */
+    private $appState;
```
Comment (szymonnosal) [inline app/code/Magento/GraphQl/Controller/GraphQl.php]: I think `private $appState;` should be change into `private $areaList;`

**Review by szymonnosal — COMMENTED** [review]
Hi,

Looks like you have the wrong property declared in the class. 
You are using `$this->areaList` and `$areaList` is not declared at all.

File: app/code/Magento/GraphQl/Controller/GraphQl.php (hunk 4 above)
Comment (rikwillems) [reply app/code/Magento/GraphQl/Controller/GraphQl.php]: Fixed. Stupid me. I had an error here before but only half fixed it.

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@rikwillems Could you verify WebAPI tests. Looks like PR changes break the tests

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
In the case of `WebAPI Tests`, all failing tests belong to a single scenario i.e 
Test with Non Existent store. 

The cause of the error is an exception is thrown from the `StoreRepository` class when it tries to get the object of a non-existent store
https://github.com/magento/magento2/blob/2c94da6391b61d6e336b3aa3b5739f6df874e7dc/app/code/Magento/Store/Model/StoreRepository.php#L74

The scenario is basically originated from [StoreProcessor](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php)
when the current store is set from header. `$this->storeManager->setCurrentStore($storeCode);`

We can avoid this if we add a check for a valid store before setting it to the context 
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php#L62toL63

@cpartica

**Comment by cpartica** [comment]
> In the case of `WebAPI Tests`, all failing tests belong to a single scenario i.e
> Test with Non Existent store.
> 
> The cause of the error is an exception is thrown from the `StoreRepository` class when it tries to get the object of a non-existent store
> https://github.com/magento/magento2/blob/2c94da6391b61d6e336b3aa3b5739f6df874e7dc/app/code/Magento/Store/Model/StoreRepository.php#L74
> 
> The scenario is basically originated from [StoreProcessor](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php)
> when the current store is set from header. `$this->storeManager->setCurrentStore($storeCode);`
> 
> We can avoid this if we add a check for a valid store before setting it to the context
> https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php#L62toL63
> 
> @cpartica

that seems ok. There's also a fallback mechanism that we could do, but I'd rather be specific about codes and errors validity. Makes a better dev. experience

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run WebAPI Tests, Integration Tests, Functional Tests B2B

**Comment by shikhamis11** [comment]
now all tests are passing can you please review @cpartica @Den4ik

**Review by Den4ik — APPROVED** [review]
✅ Approved.

I like to use `StoreRepository` for get store by code, but it's additional dependency that is not very good. In this case usage of `StoreManager` looks ok.

@rikwillems Thanks for contribution.

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9187](https://jira.corp.magento.com/browse/ENGCOM-9187) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
Hi @shikhamis11 , @rikwillems , @Den4ik and @szymonnosal 
Thanks for your contribution and collaboration!

I tried to identify the manual scenario to test the fix, but couldn't get anything better. Can anybody please provide me the end-to-end manual execution scenarios to test it completely.

Thanks in advance!

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests EE

**Comment by shikhamis11** [comment]
Hi @engcom-Alfa, you can try reproducing the error with actual issue description here
https://github.com/magento/magento2/issues/31351#issue-770964163

**Comment by engcom-Alfa** [comment]
> Hi @engcom-Alfa, you can try reproducing the error with actual issue description here
> [#31351 (comment)](https://github.com/magento/magento2/issues/31351#issue-770964163)

Thanks for your info @shikhamis11 , I have the setup of language translation now! I just want to write the exception statement in the code in order to reproduce the error message, correct? So Where should I place the exception line statement? I mean, in which class file and in which method exactly ?

Thanks in advance

**Comment by shikhamis11** [comment]
> Thanks for your info @shikhamis11, I have the setup of language translation now! I just want to write the exception statement in the code in order to reproduce the error message, correct? So Where should I place the exception line statement? I mean, in which class file and in which method exactly ?
> 
> Thanks in advance

Hi @engcom-Alfa 
you can add your translation in your custom module or in the Magento catalog module inside 

`<NameSpace>/<Module>/i18n/fr_FR.csv 
`
add below line 

`"currentPage value must be greater than 0.","La valeur currentPage doit être supérieure à 0."
`

**Comment by shikhamis11** [comment]
@magento run all tests

File: app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php [hunk 5]
```diff
@@ -95,4 +110,19 @@ private function isAlreadySet(): bool
...
+     */
+    private function isStoreValid(string $storeCode): bool
+    {
+        $stores = $this->storeManager->getStores(true, true);
+        if (isset($stores[$storeCode])) {
+            return true;
+        }
+        return false;
+    }
+}
```
Comment (Den4ik) [inline app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: Please add empty line at the end of file

**Review by Den4ik — CHANGES_REQUESTED** [review]

File: app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php (hunk 5 above)
Comment (shikhamis11) [reply app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: hi @Den4ik, sorry I didn’t get you. Where do you want me to add an empty line?

Comment (Den4ik) [reply app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: 2021-09-20-15-34-38@2x

Comment (shikhamis11) [reply app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: oh ok @Den4ik, I think that is not required. Can’t we ignore it?

Comment (Den4ik) [reply app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: It will not pass static tests without empty line

Comment (shikhamis11) [reply app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: @Den4ik static test is fixed now, failing mftf test seems not related to this PR and I am not sure about Semantic Version Check

**Comment by cpartica** [comment]
Added this issue on hold, as this fix added some performance issues in terms of loaded classes and Redis calls that are over the usual accepted threshold which affect all queries in GraphQL
```
tideways-redis-get-requests-count
Get List of Products by category_id (GraphQL Get List of Products by category_id): 7.1% (mainline = 28 | team = 30) -> DEGRADATION
Get Url Info by url_key (GraphQL Get Url Info by url_key): 7.7% (mainline = 13 | team = 14) -> DEGRADATION
Get Cms Block by identifier (GraphQL Get Cms Block by identifier): 5.6% (mainline = 18 | team = 19) -> DEGRADATION
Get Cms Page by id (GraphQL Get Cms Page by id): 6.7% (mainline = 15 | team = 16) -> DEGRADATION
Get Empty Cart (GraphQL Get Empty Cart): 5.3% (mainline = 19 | team = 20) -> DEGRADATION
Get Empty Cart (GraphQL Set Shipping Address On Cart): 5.3% (mainline = 19 | team = 20) -> DEGRADATION
Get Empty Cart (GraphQL Set Billing Address On Cart): 5.3% (mainline = 19 | team = 20) -> DEGRADATION
Get Url Info by url_key (GraphQL Catalog Browsing By Guest): 7.7% (mainline = 13 | team = 14) -> DEGRADATION
Get Cms Page by id (GraphQL Catalog Browsing By Guest): 6.7% (mainline = 15 | team = 16) -> DEGRADATION
Get Cms Block by identifier (GraphQL Catalog Browsing By Guest): 5.6% (mainline = 18 | team = 19) -> DEGRADATION
Get Empty Cart (GraphQL Checkout By Guest): 5.3% (mainline = 19 | team = 20) -> DEGRADATION
Query Category (Catalog GraphQL): 5.9% (mainline = 17 | team = 18) -> DEGRADATION
Query CategoryList (Catalog GraphQL): 5.9% (mainline = 17 | team = 18) -> DEGRADATION
```


```
loaded-classes
Get Url Info by url_key (GraphQL Get Url Info by url_key): 5.3% (mainline = 1426 | team = 1502) -> DEGRADATION
Get Url Info by url_key (GraphQL Catalog Browsing By Guest): 5.3% (mainline = 1426 | team = 1502) -> DEGRADATION
Query customer with token (Catalog GraphQL): 5.1% (mainline = 1495 | team = 1571) -> DEGRADATION
```


We don't seem to have any time complexity implications
```
Get Navigation Menu by category_id                                                             91.00ms    -1.1%      (-1ms)     ok
Get Product Search by text and category_id                                                     168.00ms   +0.6%      (+1ms)     ok
Get Url Info by url_key                                                                        34.00ms    +3.0%      (+1ms)     ok
Get List of Products by category_id                                                            110.00ms   +0.9%      (+1ms)     ok
Get Configurable Product Details by name                                                       70.00ms    +1.4%      (+1ms)     ok
Get Configurable Product Details by product_url_key                                            75.00ms    +0.0%      (+0ms)     ok
Get Simple Product Details by name                                                             63.00ms    +1.6%      (+1ms)     ok
Get Simple Product Details by product_url_key                                                  62.00ms    +0.0%      (+0ms)     ok
Get Cms Page by id                                                                             37.00ms    +0.0%      (+0ms)     ok
Get Cms Block by identifier                                                                    40.00ms    +2.6%      (+1ms)     ok
```

File: app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php [hunk 6]
```diff
@@ -55,12 +67,15 @@ public function __construct(
...
      * @return void
      */
-    public function processHeaderValue(string $headerValue) : void
+    public function processHeaderValue(string $headerValue): void
     {
         if (!empty($headerValue)) {
             $storeCode = ltrim(rtrim($headerValue));
-            $this->storeManager->setCurrentStore($storeCode);
-            $this->updateContext($storeCode);
+            if ($this->isStoreValid($storeCode)) {
```
Comment (cpartica) [inline app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: \Magento\GraphQl\Controller\HttpHeaderProcessorInterface is not where you would validate the store
but in \Magento\GraphQl\Controller\HttpRequestValidatorInterface
as we already have a store validator there
\Magento\StoreGraphQl\Controller\HttpRequestValidator\StoreValidator

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php (hunk 6 above)
Comment (shikhamis11) [reply app/code/Magento/StoreGraphQl/Controller/HttpHeaderProcessor/StoreProcessor.php]: yes, seems this is the culprit behind additional Redis calls.
Since `HttpRequestValidatorInterface` is called after `HttpHeaderProcessorInterface` and wrong store codes are causing the fatal errors, so to avoid that I had added that check. 
please see this comment https://github.com/magento/magento2/pull/32953#issuecomment-891058911

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run Unit Tests, WebAPI Tests, Functional Tests B2B, Functional Tests EE, Semantic Version Checker

**Comment by shikhamis11** [comment]
@magento run Unit Tests, Semantic Version Checker, Static Tests

**Comment by shikhamis11** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, WebAPI Tests

**Review by Den4ik — APPROVED** [review]

**Review by cpartica — APPROVED** [review]

File: app/code/Magento/GraphQl/Controller/GraphQl.php [hunk 7]
```diff
@@ -115,6 +124,7 @@ class GraphQl implements FrontControllerInterface
      * @param ContextFactoryInterface $contextFactory
      * @param LogData $logDataHelper
      * @param LoggerPool $loggerPool
+     * @param AreaList $areaList
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/GraphQl.php]: @shikhamis11 can you add really quick the " | null" here to be consistent with the constructor?

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Review by cpartica — APPROVED** [review]

**Comment by Den4ik** [comment]
@magneto run Functional Tests B2B

**Comment by Den4ik** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have a Magento latest installed with sample data.
2. Make sure to setup the other language like French and working successfully.

**Manual testing scenario:**

1. Login to admin and navigate to Store>configuration>Locale options> Set the language to French(France)

2. Clear the cache and check in the front end that french language is successfully applied.
 
3. Get a customer token from GraphQL query and create a new cart of the customer.

4. GraphQL request to add new product to the cart (Utilise the wrong SKU to query the request, so that we should see the exception message in the response).


**Before:** :heavy_multiplication_x: The GraphQL response was returning the error message with the English language.

Screenshot 2021-12-17 at 5 34 50 PM


**After:** :heavy_check_mark: The GraphQL response is returning the error message with the set French language exactly.

Screenshot 2021-12-17 at 5 49 30 PM


Since it is a GraphQL fix and had the auto-test covered, no additional regression is required on this!

**Comment by engcom-Alfa** [comment]
There is a [internal PR ticket](https://github.com/magento-gl/magento2ce/pull/98) raised on this same issue and that is being processed.
So, since this Pr ticket will become duplicate, closing this PR. In case of any changes, we will come back to this same ticket!
Thanks for everybody's collaboration and contribution on this!

**Comment by hostep** [comment]
Hi @engcom-Alfa or @cpartica: is there any news around this?

It's kind of annoying that this public issue got closed and replaced by a private issue that the community can not see into, it would be nice if you stopped doing this in the future, thanks!

**Comment by cpartica** [comment]
The issue is the process we have.
I can keep the PR opened and it will automatically be merged when 2.4.4 is released and merged back into 2.4-develop
We kept your contribution part of the actual fix. The only thing private about it is that there is an integration of our Jira with Github which updates statuses.
If it works for you I can keep this open until the 2.4.4 event happens and you get in merged status with no action
