### PR TITLE
Fix for wildcard section reload being broken by section-config refacor

### LINKED ISSUE #28154: [Backward compatibility] Customer section load with one section causes an error
### Preconditions (*)
1. Magento 2.4-develop
2. It cannot be reproduced on clean Magento. An issue occurred only with incompatible code.

### Steps to reproduce (*)
Open any page and take any action which force Magento to clean **one section** (In my case it was adding product to shopping cart from PDP)
Source code should contain sth like 
`customerData.reload('cart'); `
instead of 
`customerData.reload(['cart']);
`
### Expected result (*)

The console log must be clear.

### Actual result (*)

We faced with an issue in console:
_customer-data.js:87 Uncaught Error: [object Object]
    at Object.<anonymous> (customer-data.js:87)
    at fire (jquery.js:3238)
    at Object.fireWith [as rejectWith] (jquery.js:3368)
    at done (jquery.js:9848)
    at XMLHttpRequest.callback (jquery.js:10317)_

Screenshot from 2020-09-16 14-42-31

### What actually happens:
www/magento/vendor/magento/module-customer/view/frontend/web/js/section-config.js:61
Previous code:
```
        /**
         * @param {*} allSections
         * @return {*}
         */
        filterClientSideSections: function (allSections) {
            if (Array.isArray(allSections)) {
                return _.difference(allSections, clientSideSections);
            }

            return allSections;
        },
```
Magento 2.3.5-p1 code:
```
        /**
         * Filters the list of given sections to the ones defined as client side.
         * @param {Array} allSections - List of sections to check.
         * @return {Array} - List of filtered sections.
         */
        filterClientSideSections: function (allSections) {
            return _.difference(_.toArray(allSections), clientSideSections);
        },
```

When we pass into this function one element (string) JS parses as an array:
```
_.toArray(allSections)
(9) ["a", "u", "t", "h", "_", "d", "a", "t", "a"]
```
And of course cannot find such sections.

**Upd 1.**
Initially, your method accepted anything and we passed a string with a section name. Now your are accepting arrays only, but there no such verification in the method.
I suppose for backward compatibility you should return back isArray verification.

### LINKED ISSUE #28428: Customer data not retrieved after executing a custom login controller
### Description
I customized the routes for login flow because I have a SAML SSO extension, 

I'm experiencing issues the first time I try to log the user in using the SSO flow. Customer data is not loaded.

### Preconditions
 - Magento 2.3.4 or 2.3.5
 - Custom Login controller

My login controller is similar than the [PostLogin](https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/app/code/Magento/Customer/Controller/Account/LoginPost.php#L187) code 

```
$customerSession->setCustomerDataAsLoggedIn($customer);
if ($this->getCookieManager()->getCookie('mage-cache-sessid')) {
    $metadata = $this->getCookieMetadataFactory()->createCookieMetadata();
    $metadata->setPath('/');
    $this->getCookieManager()->deleteCookie('mage-cache-sessid', $metadata);
}

$resultRedirect = $this->resultRedirectFactory->create();
return $resultRedirect->setUrl($targetURL);
```

The extension also forces sections to be invalidated after my custom login, by adding a etc/frontend/sections.xml as documented on [page-caching](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/cache/page-caching/private-content.html)
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Customer:etc/sections.xsd">
    <action name="sso/saml2/acs">
        <section name="*"/>
    </action>
</config>
```

### Steps to reproduce
I implemented this simple custom login controller that will allow reproduce the issue:
https://github.com/pitbulk/magento-custom-login

If in a private browser I log in, the call to retrieve sections info does not contain the customer section.
```
http://example.com/customer/section/load/?sections=recently_viewed_product%2Crecently_compared_product
%2Cpersistent&force_new_section_timestamp=false&_=1590761846169
```

If I later log in using the normal login process and then logout and try to log again using the SSO module, the customer data is properly retrieved.
If I analyze the call done to retrieve the customer-data, it contains the customer section:
```
http://example.com/customer/section/load/?sections=recently_viewed_product%2Crecently_compared_product
%2Cpersistent%2Ccustomer%2Ccompare-products%2Clast-ordered-items
%2Ccart%2Cdirectory-data%2Ccaptcha%2Cinstant-purchase%2Creview%2Cwishlist%2Cproduct_data_storage
%2Cpaypal-billing-agreement&force_new_section_timestamp=false&_=1590761971410
```
It seems that the normal login flow set something the first time the user tries to log that is not set by my extension.

The issue I experience is similar than the one described at:
https://github.com/magento/magento2/issues/21548

The issue exists on Magento 2.3.4, 2.3.4-p2 and 2.3.5-p1

### Expected result

customer section listed on section_data_ids.
Customer data available. 

### Actual result

After enabling a private browser, login and logout using the SAML SSO flow, my sessions looks like:
```
- Cookies:
  mage-cache-sessid                                        true
  mage-cache-storage                                      %7B%7D
  mage-cache-storage-section-invalidation      %7B%7D
  private_content_version                                 b1051bef9438849ebe3f156423360282
  store                                                               default
  section_data_ids                                            %7B%22recently_viewed_product%22%3A1590766823%2C%22recently_compared_product%22%3A1590766823%2C%22persistent%22%3A1590766823%7D

- Session Storage:
 mage-cache-storage                                  {}
 mage-cache-storage-section-invalidation  {}

- Local Storage:
  mage-cache-timeout                                  "2020-05-29T16:37:08.438Z"
  mage-cache-storage-section-invalidation  {}
  mage-cache-storage                                  {"recently_viewed_product":{"count":0,"items":[],
                                                                     "data_id":1590766823},"recently_compared_product":
                                                                     {"count":0,"items":[],"data_id":1590766823},
                                                                    "persistent":{"data_id":1590766823}}
```
After enabling a private browser, login and logout using the normal flow, that allows me later to login with no issue via SAML, the sessions look like:
```
- Cookies:
  mage-cache-sessid                                        true
  mage-cache-storage                                      %7B%7D
  mage-cache-storage-section-invalidation      %7B%7D
  private_content_version                                 4366e273973e6fe629402ced87a74171
  store                                                               default
  section_data_ids                                            %7B%22customer%22%3A1590767746%2C%22compare-products%22%3A1590767746%2C%22last-ordered-items%22%3A1590767746%2C%22cart%22%3A1590767746%2C%22directory-data%22%3A1590767746%2C%22captcha%22%3A1590767746%2C%22instant-purchase%22%3A1590767746%2C%22persistent%22%3A1590767746%2C%22review%22%3A1590767746%2C%22wishlist%22%3A1590767746%2C%22recently_viewed_product%22%3A1590767746%2C%22recently_compared_product%22%3A1590767746%2C%22product_data_storage%22%3A1590767746%2C%22paypal-billing-agreement%22%3A1590767746%7D

- Session Storage:
 mage-cache-storage                                  {}
 mage-cache-storage-section-invalidation  {}

- Local Storage:
  mage-cache-timeout                                  "2020-05-29T16:54:53.287Z"
  mage-cache-storage-section-invalidation  {}
  mage-cache-storage                                  {"customer":{"data_id":1590767746},"compare-products":{"count":0,"countCaption":"0 items", ............ "persistent":{"data_id":1590767746},"review":{"nickname":"","title":"","detail":"","data_id":1590767746},"wishlist":{"counter":null,"items":[],"data_id":1590767746},"recently_viewed_product":{"count":0,"items":[],"data_id":1590767746},"recently_compared_product":{"count":0,"items":[],"data_id":1590767746},"product_data_storage":{"data_id":1590767746},"paypal-billing-agreement":{"data_id":1590767746}}
```

I removed the mage-cache-storage   and tried to login with SAML, and it worked, so it seems that
all that is required is to include the so it seems that once customer section customer on section_data_ids. I executed again the SAML SSO process and added the customer string manually inside the section_data_ids, so logged in, logged out, edited the Cookie and the process worked.

What may I do to include "customer" inside the section_data_ids?

### PR DESCRIPTION
**Pull request by complexthings**
### Description (*)
Since the refactor of section-config.js in Magento_Customer (https://github.com/magento/magento2/commit/976302de9187d12d9ed0b54e06de3ca8a6f37b24) reloading of all customer-data sections via wildcard `*` has caused requests to `customer/section/load` to respond `400`. 

image

This causes issues when you call reload directly from `customer-data` or you request wildcard section reloading via an action in sections.xml

You can validate this yourself by executing the following code from your devtools console:

```js
require('Magento_Customer/js/customer-data').reload('*');
``` 

I've added an additional condition to the `getFromServer` method's parameters variable that checks to see if the wildcard section request is present, if it is, it makes sure parameters gets set to `[]` instead of `['*']` which fails.

image

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/28428
2. Fixes https://github.com/magento/magento2/issues/28154

### Manual testing scenarios (*)

1. In your Browser's devtools, execute the following code:
```js
require('Magento_Customer/js/customer-data').reload('*');
```
This should return all customer-data sections.
2. Hitting any route with a request where the action expects to reload '*'.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by complexthings** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@complexthings interesting... I see case with `*` (all) is covered with auto test, so it suppose to work... https://github.com/magento/magento2/blob/5be754b7d3de102cb9ec6ef2f43dbdbcb797540a/dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/section-config.test.js#L99-L130

@krzksz could you review this PR?

**Comment by complexthings** [comment]
@ihor-sviziev section-config does what it's supposed to, the refactor works, it just happened to break customer-data.js

File: app/code/Magento/Customer/view/frontend/web/js/customer-data.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ define([
             var parameters;
 
             sectionNames = sectionConfig.filterClientSideSections(sectionNames);
-            parameters = _.isArray(sectionNames) ? {
+            parameters = _.isArray(sectionNames) && sectionNames.indexOf('*').length < 0 ? {
```
Comment (ihor-sviziev) [inline app/code/Magento/Customer/view/frontend/web/js/customer-data.js]: Seems like it will not work:
image
```suggestion
            parameters = _.isArray(sectionNames) && sectionNames.indexOf('*') < 0 ? {
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @complexthings,
Could you cover your change with js unit test? Example you can find here:
https://github.com/magento/magento2/blob/5be754b7d3de102cb9ec6ef2f43dbdbcb797540a/dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/section-config.test.js

**Review by krzksz — CHANGES_REQUESTED** [review]
@ihor-sviziev suggestions look good to me. It would be great to have this module covered with unit tests.

File: app/code/Magento/Customer/view/frontend/web/js/customer-data.js (hunk 1 above)
Comment (complexthings) [reply app/code/Magento/Customer/view/frontend/web/js/customer-data.js]: Typo fixed. Force of habit.

**Comment by complexthings** [comment]
@ihor-sviziev @krzksz I am working on jasmine tests for customer-data.js but it will take some time.

**Comment by ihor-sviziev** [comment]
Ok, np

**Comment by complexthings** [comment]
@ihor-sviziev @krzksz I added js unit test for customer-data.js

**Comment by complexthings** [comment]
@magento run all tests

**Comment by complexthings** [comment]
@magento run Database Compare, Functional Tests B2B, Static Tests, Unit Tests

**Comment by complexthings** [comment]
@magento run all tests

**Comment by complexthings** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@magento run Functional Tests CE, Functional Tests B2B

The failures seem to be unrelated.
We need to finally resolve the issue with tests isolation...

**Comment by complexthings** [comment]
@magento run Functional Tests B2B

File: lib/web/jquery/jquery.storageapi.min.js [hunk 2]
```diff
@@ -1,2 +1,2 @@
...
...ain&&(this._domain=e.domain),e.expires&&(this._expires=e.expires),this},setDefaultConf:function(){this._path=this._domain=this._expires=null}};g||(window.localCookieStorage=e.extend({},l,{_prefix:c,_expires:3650}),window.sessionCookieStorage=e.extend({},l,{_prefix:m+window.name+"_"})),window.cookieStorage=e.extend({},l),e.cookieStorage=e.extend({},h,{_type:"cookieStorage",setExpires:function(e){return window.cookieStorage.setExpires(e),this},setPath:function(e){return window.cookieStorage.setPath(e),this},setDomain:function(e){return window.cookieStorage.setDomain(e),this},setConf:function(e){return window.cookieStorage.setConf(e),this},setDefaultConf:function(){return window.cookieStorage.setDefaultConf(),this}})}e.initNamespaceStorage=function(e){return u(e)},g?(e.localStorage=e.extend({},h,{_type:"localStorage"}),e.sessionStorage=e.extend({},h,{_type:"sessionStorage"})):(e.localStorage=e.extend({},h,{_type:"localCookieStorage"}),e.sessionStorage=e.extend({},h,{_type:"sessionCookieStorage"})),e.namespaceStorages={},e.removeAllStorages=function(t){e.localStorage.removeAll(t),e.sessionStorage.removeAll(t),e.cookieStorage&&e.cookieStorage.removeAll(t),t||(e.namespaceStorages={})}});
```
Comment (ihor-sviziev) [inline lib/web/jquery/jquery.storageapi.min.js]: Please revert changes in this file, it’s not related to this PR

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: lib/web/jquery/jquery.storageapi.min.js (hunk 2 above)
Comment (complexthings) [reply lib/web/jquery/jquery.storageapi.min.js]: It is though, this library is extremely out of date and had a fix issued in version 1.7.5 (Magento has 1.7.3) that fixes an issue that prevents unit tests from being executable and has a rare chance to throw in error in general.

It was fixed in 2015, I placed it in the file as a means of correcting the issue: https://github.com/julien-maurel/jQuery-Storage-API/commit/abef0586cf92e29297a283ee6299bac741ae125e#diff-50c51a23ea1ca042039829fb4ddeeb7c

This library had it's final release in May of 2016 (1.9.1) I think it's kind of ridiculous that this library is on a 2014 version, I'm also fine upgrading this library to 1.7.5 or even 1.9.1 (not sure how much divergence there is between 1.7.5 & 1.9.1)

Please advise how you want me to proceed.

Comment (ihor-sviziev) [reply lib/web/jquery/jquery.storageapi.min.js]: @complexthings 
> issue that prevents unit tests from being executable and has a rare chance to throw in error in general.

I think fixing or even updating some library just to fix the test is not good thing. Could you explain what the issue you had in the test? Maybe we'll find some workaround for that?

**Comment by complexthings** [comment]
@magento run Unit Tests

File: lib/web/jquery/jquery.storageapi.min.js (hunk 2 above)
Comment (complexthings) [reply lib/web/jquery/jquery.storageapi.min.js]: I removed it in a commit, you'll be able to see below the results of Magento's Unit Tests running.  But essentially here's what happens:

image

Comment (ihor-sviziev) [reply lib/web/jquery/jquery.storageapi.min.js]: I just tried to investigate.
In original code we have
https://github.com/dariusz-goc/jQuery-Storage-API/blob/abef0586cf92e29297a283ee6299bac741ae125e/jquery.storageapi.js#L428 that runs `_createNamespace` method.

This method sets https://github.com/dariusz-goc/jQuery-Storage-API/blob/abef0586cf92e29297a283ee6299bac741ae125e/jquery.storageapi.js#L278

something like this should work:
```
    var ns={
      localStorage: {cookie: false},
      sessionStorage: {cookie: false}
    };
    $.namespaceStorages[name]=ns;
```

Looks like we need to put some mock `$.namespaceStorages[name]` and issue should be solved. What do you thing?

Comment (ihor-sviziev) [reply lib/web/jquery/jquery.storageapi.min.js]: In general this plugin is buggy for instance it causes issues like https://github.com/magento/magento2/issues/27355  https://github.com/magento/magento2/issues/17195 and https://github.com/magento/magento2/pull/17033#issuecomment-411026073, would be good to get rid of it at some point, but not in scope of this task.

Comment (ihor-sviziev) [reply lib/web/jquery/jquery.storageapi.min.js]: @complexthings please check my comments above, hope it will fix the issue you had

**Comment by ihor-sviziev** [comment]
@complexthings will you be able to update your PR?

**Comment by complexthings** [comment]
@ihor-sviziev I keep trying to mock that library and it never takes, I'm just beating my head against the wall at this point.  Any help would be appreciated if anyone has successfully mocked it or has a lot more experience with Jasmine than myself.

**Comment by ihor-sviziev** [comment]
@complexthings will try to help

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
Looks like my change fixed failing unit tests
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@lenaorobei @slavvka @naydav could you explain why static test fails with no errors?

**Comment by lenaorobei** [comment]
It failed because of JS issue.
```
Error Message
Parsing error: The keyword 'let' is reserved
Stacktrace
line 78, col 21, Error - Parsing error: The keyword &apos;let&apos; is reserved
```

We will investigate why it is not reflected in reports.

**Comment by ihor-sviziev** [comment]
@magento run Static Tests, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests, Unit Tests

@complexthings seems like mock of `$.initNamespaceStorage` wasn't working at all, I replaced to calling initNamespaceStorage similar to what we have in the top of `customer-data.js` file.

**Comment by complexthings** [comment]
@ihor-sviziev yeah I was trying to mock similar to what you were doing before, but I hadn't tried just initializing like so, thank you for the help.

**Comment by ihor-sviziev** [comment]
Unfortunately it still doesn’t work, while it worked fine on local machine.
@engcom-Charlie could you help with failing unit tests?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Unfortunately it still doesn’t work, while it worked fine on local machine and I don’t have ideas anymore.
@engcom-Charlie @engcom-Kilo could you help with failing js unit tests?

**Comment by engcom-Kilo** [comment]
@magento run Static Tests, Unit Tests

**Comment by complexthings** [comment]
@magento run Static Tests, Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8093](https://jira.corp.magento.com/browse/ENGCOM-8093) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@complexthings thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by ihor-sviziev** [comment]
@complexthings good job!

**Comment by complexthings** [comment]
Thanks for your help @ihor-sviziev

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @complexthings 

Could you resolve merge conflicts?

Also, we faced the problems during testing issue #28428.

**Manual testing scenario:**

1. We implemented this simple custom login controller:
https://github.com/pitbulk/magento-custom-login
2. Go to Storefront -> Sign In -> Custom Login

**Actual Result:** :heavy_multiplication_x: Uncaught Error... and customer data was not uploaded

Peek 2020-09-04 15-13

@complexthings Could you take a look? 

Thanks!

**Comment by complexthings** [comment]
@engcom-Alfa I resolved the merge conflicts and removed some unused code from the test, I'll begin looking at the issue you linked.

**Comment by complexthings** [comment]
@magento run Static Tests, Unit Tests

**Comment by complexthings** [comment]
@engcom-Alfa I installed the custom module on this branch and was unable to reproduce the issue in your screenshot/gif

**Comment by complexthings** [comment]
@magento run all tests

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js [hunk 3]
```diff
@@ -95,84 +97,100 @@ define([
...
     describe('Magento_Customer/js/customer-data', function () {
+
         beforeAll(function () {
             clearLocalStorage();
         });
 
-        beforeEach(function () {
-            jQueryGetJSON = $.getJSON;
+        beforeEach(function (done) {
+            originalGetJSON = jQuery.getJSON;
```
Comment (ihor-sviziev) [inline dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: Seems like we have `$` in the top, so probably we should use it instead
```suggestion
            originalGetJSON = $.getJSON;
```

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js [hunk 4]
```diff
@@ -95,84 +97,100 @@ define([
...
+                obj = Constr;
+                done();
+            });
         });
 
         afterEach(function () {
-            $.getJSON = jQueryGetJSON;
-            clearLocalStorage();
+            try {
+                jQuery.getJSON = originalGetJSON;
```
Comment (ihor-sviziev) [inline dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]:
```suggestion
                $.getJSON = originalGetJSON;
```

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js [hunk 5]
```diff
@@ -95,84 +97,100 @@ define([
...
+        beforeEach(function (done) {
+            originalGetJSON = jQuery.getJSON;
             sectionConfig['Magento_Customer/js/section-config'](sectionConfigSettings);
+
+            injector.require([
+                'Magento_Customer/js/customer-data'
+            ], function (Constr) {
+                obj = Constr;
+                done();
+            });
```
Comment (ihor-sviziev) [inline dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: Seems like we don't really need to mock any dependencies, so looks like we can just use customerData object that already imported above. What do you thing?

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js [hunk 6]
```diff
@@ -95,84 +97,100 @@ define([
...
         afterEach(function () {
-            $.getJSON = jQueryGetJSON;
-            clearLocalStorage();
+            try {
+                jQuery.getJSON = originalGetJSON;
+                clearLocalStorage();
+                injector.clean();
+                injector.remove();
+            } catch (e) {
+            }
```
Comment (ihor-sviziev) [inline dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:129]: Are we expecring to have any exceptions here? I don't think it's good to have empty catch, it will just mask any issues inside

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js [hunk 7]
```diff
@@ -3,30 +3,34 @@
...
-/*eslint-disable max-nested-callbacks*/
-/*jscs:disable jsDoc*/
+/* global _ */
+/* eslint max-nested-callbacks: 0 */
+/* jscs:disable jsDoc*/
 
 define([
+    'squire',
     'jquery',
-    'underscore',
```
Comment (ihor-sviziev) [inline dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:11]: Seems like we should add it back as it's used in the code below

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by engcom-Alfa** [comment]
Hi @complexthings, @ihor-sviziev  . 

We double-checked the changes and found out what the problem was. The custom module https://github.com/pitbulk/magento-custom-login mentioned in issue #28428 was written for the Enterprise Edition version of Magento. (`<section name="multiplewishlist"/>` and because of what we received errors in the console. After minor changes in the module itself, everything works properly.

Peek 2020-09-09 13-05

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 6 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:129]: Squire throws errors itself, this happens with anything that's using Squire same as in section-config.test.js

`TypeError: undefined is not an object (evaluating 'getContext(this.id).defined')`

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 5 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: Removing the mocking breaks the following:

`Check it requests sections from the server if there are expired sections` with error:
```
Expected spy $.getJSON to have been called with [ 'http://localhost/customer/section/load/', <jasmine.objectContaining(Object({ sections: 'cart,customer' }))> ] but it was never called. (1)
```

`"getExpiredSectionNames method` -> `Does not throw before component is initialized` with error:
```
Expected function not to throw, but it threw TypeError: null is not an object (evaluating 'i[a[f]]'). (1)
```

`"set" method` -> `Does not throw before component is initialized...`
```
>> Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
>> Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
```

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 3 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: Breaks the following tests:

`"getExpiredSectionNames method` -> `Check that result does not contain unexpired section names...` with error:
```
log: JQMIGRATE: jQuery.parseJSON requires a valid JSON string

log:
>> Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
```

`"getExpiredSectionNames method` -> `Check that result does not contain unsupported section names...` with error:
```
>> Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
```

`"reload" method` -> `Check it returns proper sections object when passed array with a single section name...` with error:
```
>> Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
```

`"reload" method` -> `Check it returns proper sections object when passed array with a single section name...` with error:
```
Expected Object({ readyState: 1, getResponseHeader: Function, getAllResponseHeaders: Function, setRequestHeader: Function, overrideMimeType: Function, statusCode: Function, abort: Function, state: Function, always: Function, then: Function, promise: Function, pipe: Function, done: Function, fail: Function, progress: Function, complete: Function, success: Function, error: Function }) to equal <jasmine.objectContaining(Object({ responseJSON: Object({ section: Object({  }) }) }))>. (1)
```

`"reload" method` -> `Check it returns proper sections object when passed array with multiple section names...`
```
Expected Object({ readyState: 1, getResponseHeader: Function, getAllResponseHeaders: Function, setRequestHeader: Function, overrideMimeType: Function, statusCode: Function, abort: Function, state: Function, always: Function, then: Function, promise: Function, pipe: Function, done: Function, fail: Function, progress: Function, complete: Function, success: Function, error: Function }) to equal <jasmine.objectContaining(Object({ responseJSON: Object({ cart: Object({  }), customer: Object({  }), messages: Object({  }) }) }))>. (1)
```

`"reload" method` -> `Check it returns all sections when passed wildcard string...`
```
Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
```

`"reload" method` -> `Check it returns all sections when passed wildcard string`
```
Expected spy unknown to have been called. (1)
       Expected Object({ readyState: 1, getResponseHeader: Function, getAllResponseHeaders: Function, setRequestHeader: Function, overrideMimeType: Function, statusCode: Function, abort: Function, state: Function, always: Function, then: Function, promise: Function, pipe: Function, done: Function, fail: Function, progress: Function, complete: Function, success: Function, error: Function }) to equal <jasmine.objectContaining(Object({ responseJSON: Object({ cart: Object({  }), customer: Object({  }), messages: Object({  }) }) }))>. (2)
```

`"invalidate" method` -> `Should be defined`
```
Error: [object Object] at
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/Magento_Customer/js/customer-data.js:87
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3238 fire
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:3368 fireWith
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:9848 done
>> http:/localhost:8000/pub/static/frontend/Magento/luma/en_US/jquery.js:10317 callback
```

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 4 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: See above comment.

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 7 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:11]: Breaks following tests:

`"init" method` -> `Calls "reload" method when expired sections do not exist`
```
Expected spy reload to have been called. (1)
```

`"set" method` -> `Does not throw before component is initialized`
```
Expected function not to throw, but it threw TypeError: undefined is not an object (evaluating 'sectionData['data_id']'). (1)
```

**Comment by complexthings** [comment]
@magento run all tests

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 3 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: Figured out a way around this, and updated below.

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 5 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js]: Nope it was needed, using just customerData didn't end up working, I also ended up needing to inject underscore here to resolve another one of your suggestions below.

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 6 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:129]: At most I can remove the try catch, thoughts?

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 7 above)
Comment (complexthings) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:11]: Was able to figure out how to load underscore via Squire and that resolves the issues.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@complexthings could you check failing tests?

**Comment by complexthings** [comment]
@magento run Static Tests, Unit Tests

**Comment by complexthings** [comment]
@magento run Static Tests, Unit Tests

**Comment by complexthings** [comment]
@magento run all tests

File: dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js (hunk 6 above)
Comment (ihor-sviziev) [reply dev/tests/js/jasmine/tests/app/code/Magento/Customer/frontend/js/customer-data.test.js:129]: Let's keep it as is for now

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8093](https://jira.corp.magento.com/browse/ENGCOM-8093) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. In Browser's devtools, execute the following code:
```js
require('Magento_Customer/js/customer-data').reload('*');
```
**Before:** :heavy_multiplication_x: Js error:

Screenshot from 2020-09-16 14-42-31

**After:** :heavy_check_mark: It returns all customer-data sections.

Screenshot from 2020-09-16 15-20-39

**Comment by pitbulk** [comment]
After apply the changes, one of my customer reported me 2 different related issues:
- If in the Magento instance exists customers with similar fullname (same lastname for example), the message that appears on the welcome message mismatch the fullname (wrong is loaded). It was verified that the data of the logged user that appears on the profile view is different than the one loaded on the customer data object loaded by js for printing the welcome message 
- After login, if the user proceeds to checkout, the login popup appear even if the user was previously logged.
  Similar than the issue described here:  https://github.com/mageplaza/magento-2-social-login/issues/197

I created a new ticket:
https://github.com/magento/magento2/issues/30498

Hopefully @complexthings can fix this one as well.
