### PR TITLE
#27504 fix joinprocessor behavior with consecutive calls

### LINKED ISSUE #27504: JoinProcessor caching issue
<!---
Please review our guidelines before adding a new issue: https://github.com/magento/magento2/wiki/Issue-reporting-guidelines
Fields marked with (*) are required. Please don't remove the template.
-->

### Preconditions (*)
1. Magento Open Source **2.4-develop**
2. PHP 7.3 - PHP 7.4 

### Steps to reproduce (*)

1. Add a module with [JoinProcessor](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/searching-with-repositories.html#join-processor) for the OrderRepository using the files below:
    <details><summary>app/code/SomeVendor/SomeModule/registration.php</summary>

    ```php
    <?php

    use Magento\Framework\Component\ComponentRegistrar;

    ComponentRegistrar::register(ComponentRegistrar::MODULE, 'SomeVendor_SomeModule', __DIR__);
    ```
    </details>
    <details><summary>app/code/SomeVendor/SomeModule/etc/module.xml</summary>

    ```xml
    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
        <module name="SomeVendor_SomeModule" />
    </config>
    ```
    </details>
    <details><summary>app/code/SomeVendor/SomeModule/etc/di.xml</summary>

    ```xml
    <?xml version="1.0"?>
    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
        <type name="Magento\Framework\Console\CommandListInterface">
            <arguments>
                <argument name="commands" xsi:type="array">
                    <item name="order:update" xsi:type="object">SomeVendor\SomeModule\Console\Command\OrderUpdate</item>
                </argument>
            </arguments>
        </type>
        <type name="SomeVendor\SomeModule\Console\Command\OrderUpdate">
            <arguments>
                <argument name="orderRepository" xsi:type="object">SomeVendor\SomeModule\Model\OrderRepository</argument>
            </arguments>
        </type>
        <virtualType name="SomeVendor\SomeModule\Model\OrderRepository" type="Magento\Sales\Model\OrderRepository">
            <arguments>
                <argument name="collectionProcessor" xsi:type="object">SomeVendor\SomeModule\Model\OrderRepository\CollectionProcessor</argument>
            </arguments>
        </virtualType>
        <virtualType name="SomeVendor\SomeModule\Model\OrderRepository\CollectionProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor">
            <arguments>
                <argument name="processors" xsi:type="array">
                    <item name="joins" xsi:type="object">SomeVendor\SomeModule\Model\Api\SearchCriteria\CollectionProcessor\StoreViewJoinProcessor</item>
                </argument>
            </arguments>
        </virtualType>
        <virtualType name="SomeVendor\SomeModule\Model\Api\SearchCriteria\CollectionProcessor\StoreViewJoinProcessor" type="Magento\Framework\Api\SearchCriteria\CollectionProcessor\JoinProcessor">
            <arguments>
                <argument name="customJoins" xsi:type="array">
                    <item name="store.group_id" xsi:type="object">SomeVendor\SomeModule\Model\Api\SearchCriteria\JoinProcessor\Store</item>
                </argument>
            </arguments>
        </virtualType>
    </config>
    ```
    </details>
    <details><summary>app/code/SomeVendor/SomeModule/Model/Api/SearchCriteria/JoinProcessor/Store.php</summary>

    ```php
    <?php
    /**
     * Store Join Processor
     */
    declare(strict_types = 1);

    namespace SomeVendor\SomeModule\Model\Api\SearchCriteria\JoinProcessor;

    use Magento\Framework\Api\SearchCriteria\CollectionProcessor\JoinProcessor\CustomJoinInterface;
    use Magento\Framework\Data\Collection\AbstractDb;

    /**
     * Store Join Processor
     */
    class Store implements CustomJoinInterface
    {
        /**
         * @inheritDoc
         */
        public function apply(AbstractDb $collection)
        {
            $collection->join(
                ['store' => $collection->getResource()->getTable('store')],
                'store.store_id = main_table.store_id',
                []
            );

            return true;
        }
    }
    ```
    </details>
    <details><summary>app/code/SomeVendor/SomeModule/Console/Command/OrderUpdate.php</summary>

    ```php
    <?php
    /**
     * Order Update CLI
     */

    declare(strict_types = 1);

    namespace SomeVendor\SomeModule\Console\Command;

    use Magento\Framework\Api\SearchCriteriaBuilder;
    use Magento\Sales\Api\Data\OrderInterface;
    use Magento\Sales\Api\OrderRepositoryInterface;
    use Symfony\Component\Console\Command\Command;
    use Symfony\Component\Console\Input\InputInterface;
    use Symfony\Component\Console\Output\OutputInterface;

    /**
     * Order Update CLI
     */
    class OrderUpdate extends Command
    {
        /** @var OrderRepositoryInterface */
        protected $orderRepository;

        /** @var SearchCriteriaBuilder */
        protected $searchCriteriaBuilder;

        /**
         * OrderUpdate constructor.
         *
         * @param OrderRepositoryInterface $orderRepository
         * @param SearchCriteriaBuilder $searchCriteriaBuilder
         */
        public function __construct(
            OrderRepositoryInterface $orderRepository,
            SearchCriteriaBuilder $searchCriteriaBuilder
        ) {
            $this->orderRepository = $orderRepository;
            $this->searchCriteriaBuilder = $searchCriteriaBuilder;
            parent::__construct();
        }

        /**
         * @inheritDoc
         */
        protected function configure()
        {
            $this->setName('order:update');
            $this->setDescription('Order Update');

            parent::configure();
        }

        /**
         * @inheritDoc
         */
        protected function execute(InputInterface $input, OutputInterface $output)
        {
            foreach (['001', '002'] as $orderId) {
                echo 'Searching for order #' . $orderId . ' ... ';
                $order = $this->searchOrder($orderId, 1);
                echo $order ? ' Found' : ' Not Found';
                echo PHP_EOL;
            }
        }

        /**
         * Search Order
         *
         * @param string $incrementId
         * @param int $storeId
         *
         * @return OrderInterface|null
         */
        protected function searchOrder(string $incrementId, int $storeId): ?OrderInterface
        {
            $searchCriteria = $this->searchCriteriaBuilder
                ->addFilter('increment_id', $incrementId)
                ->addFilter('store.group_id', $storeId)
                ->create();
            $orders = $this->orderRepository->getList($searchCriteria)->getItems();

            return current($orders) ?: null;
        }
    }
    ```
    </details>
2. Run the following CLI commands:
    ```bash
    php bin/magento module:enable SomeVendor_SomeModule
    php bin/magento setup:upgrade
    php bin/magento cache:clean
    php bin/magento order:update
    ```

### Expected result (*)
```
Searching for order #001 ... Not Found
Searching for order #002 ... Not Found
```

### Actual result (*)
```
Searching for order #001 ...  Not Found
Searching for order #002 ... 
In Mysql.php line 110:
                                                                                                                                                                            
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store.group_id' in 'where clause', query was: SELECT `main_table`.* FROM `sales_order` AS `main_table` WHERE ((`  
  increment_id` = '002')) AND ((`store`.`group_id` = 1))                                                                                                                    
                                                                                                                                                                            

In Mysql.php line 91:
                                                                                             
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store.group_id' in 'where clause'  
                                                                                             

order:update
```

### More Details

In the second `foreach` iteration the JoinProcessor it not applied because it is marked as already applied in the `$this->appliedFields` property of the [`Magento\Framework\Api\SearchCriteria\CollectionProcessor\JoinProcessor`](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessor.php#L58) class. It looks right, but in the second iteration we have a fresh new instance of the order collection where is no JOIN which was added in the first iteration. You may check it with the 
```php
echo 'Collection ID: ' . spl_object_id($collection) . PHP_EOL;
``` 
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ouzned**
### Description (*)

When a JoinProcessor is called multiple times during a request the join definitions are only applied the first time. Subsequent calls will leave the collections unmodified.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#27504

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fgerodez** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php [hunk 1]
```diff
@@ -0,0 +1,60 @@
+<?php
```
Comment (andrewbess) [inline dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php:1]:
```suggestion
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
```

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @fgerodez
Thank you for your contribution
Could you please check my suggestion and fix copyright?
Thank you in advance.

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run WebAPI Tests, Functional Tests CE, Functional Tests EE

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @fgerodez,

Thanks for the collaboration & contribution!

✔️ QA Passed
Preconditions:

Install fresh Magento 2.4-develop
Steps to reproduce
According to the issue description.
Before: ✖️ 
image

After: ✔️

image

Builds are failed. Hence, moving this PR to Extended Testing.

Thanks

**Comment by engcom-Dash** [comment]
@magnto run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Dash** [comment]
Failing tests seem flaky and these are known issues. Therefore, I am moving the PR to Merge in Progress.

**Build Result**
Functional Tests B2B
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/0fbdcdfa9a31d12cd376388d3b612236/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/0fbdcdfa9a31d12cd376388d3b612236/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/cd4f35f8bf8051b7b4becdc429888efd/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/cd8bdfe4b424a3437cc015897f021949/Functional/allure-report-b2b/index.html

Known issue :
StorefrontCheckoutProcessForQuoteWithoutNegotiatedPricesTestCest: [#AC-6801](https://jira.corp.adobe.com/browse/ACQE-6801)
StorefrontPrintListItemsFromRequisitionListTest: [#AC-12166](https://jira.corp.adobe.com/browse/AC-12166)

**Comment by engcom-Charlie** [comment]
Hi @fgerodez and @andrewbess,

Thank you for the contribution!

As the review is pending, moving it back to Pending review.

Thank you!

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php [hunk 2]
```diff
@@ -0,0 +1,64 @@
...
+
+use Magento\Framework\Api\SearchCriteria\CollectionProcessor\JoinProcessor\CustomJoinInterface;
+use Magento\Framework\Api\SearchCriteriaBuilder;
+use Magento\Framework\Data\Collection\AbstractDb;
+use PHPUnit\Framework\TestCase;
+
+class JoinProcessorTest extends TestCase
+{
+    /**
+     * @var \Magento\Framework\ObjectManagerInterface
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php]: This qualifier can be replaced with an import. Import the ObjectManagerInterface and use it as below:
```suggestion
     * @var ObjectManagerInterface
```

File: dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+     */
+    private $objectManager;
+
+    protected function setUp(): void
+    {
+        $this->objectManager = \Magento\TestFramework\Helper\Bootstrap::getObjectManager();
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php]: Same here
```suggestion
        $this->objectManager = Bootstrap::getObjectManager();
```

File: dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+            ],
+        ]);
+
+        $searchCriteria = $this->objectManager->create(SearchCriteriaBuilder::class)
+            ->addFilter('test_field', 'test')
+            ->create();
+
+        $collection1 = $this->getMockBuilder(AbstractDb::class)
+            ->disableOriginalConstructor()
+            ->getMockForAbstractClass();
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php]: The `getMockForAbstractClass` method has been deprecated, please use alternate method.

File: dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+
+        $collection2 = $this->getMockBuilder(AbstractDb::class)
+            ->disableOriginalConstructor()
+            ->getMockForAbstractClass();
```
Comment (engcom-Hotel) [inline dev/tests/integration/testsuite/Magento/Framework/Api/SearchCriteria/CollectionProcessor/JoinProcessorTest.php]: The `getMockForAbstractClass` method has been deprecated, please use alternate method.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @fgerodez,
Thanks for the contribution!

Please fix the failed automated tests, specifically static test, and look into the review comments below.

Thanks

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
> Hello @fgerodez, Thanks for the contribution!
> 
> Please fix the failed automated tests, specifically static test, and look into the review comments below.
> 
> Thanks

@engcom-Hotel: I have implemented the suggested changes and fixed the integration failures. Moving it back to Pending Review.

NOTE: The failed integration tests are not related to the PR changes and can also be seen in other PRs.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run Integration Tests, Functional Tests EE

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
The Functional B2B, CE and Integration test failures are inconsistent or known issues in the last two builds and seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

**Integration Tests**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/b8d3b143ee2d4461466eaecbc06cc161/Integration/console-error-logs.html
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/e55d6635f7dbd475f5ca236ceeb1a535/Integration/console-error-logs.html
image

Known Issue:
[AC-13584](https://jira.corp.adobe.com/browse/AC-13584)

**Functional Tests B2B**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/96b61a594a1ae1c7207fe8403c36d94a/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/36fcf222bef58cb7/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/d07cd9fc1b64f9dd7ff8631e39bb5c04/Functional/allure-report-b2b/index.html#categories/bfde7a9fcff9e79ffbe443fe2e9ee992/fa198996fe557e5/
image

Known Issue:
EndToEndB2CLoggedInUserTest: [ACQE-7387](https://jira.corp.adobe.com/browse/ACQE-7387)

**Functional Tests CE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/3cae302f7a40c3a2881c4787e7dd82c5/Functional/allure-report-ce/index.html#categories/75b40a63f79830217aae704c6d6af940/110526e17ad16bfb/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37550/feee1c963f5bf6397afbd7fba47476db/Functional/allure-report-ce/index.html#categories/e93c564a2dcd5e30ee0e0e811a828c2b/811cd8516b0a14be/
image

Known Issue:
StoreFrontAddOutOfStockProductToShoppingCartTest: [ACQE-6818](https://jira.corp.adobe.com/browse/ACQE-6818)
