### PR TITLE
Categories permissions for "categories" and "categoryList"

### LINKED ISSUE #29880: GraphQL "categories" and  "categoryList" do not consider Category Permissions configuration
Sample queries may look like

`{
  categoryList(filters: {name: {match: "category"}}){
    id
    name
    product_count
  }
}  `

`{
  categories(filters: {name: {match: "category"}}){
    items {
      id
      name
      product_count
    }
  }
} `

If any catalog permissions are present these two queries should account for the categories availability.
Dominant factor that determines availability is the customer group.

### Connected issues
This ticket will help to achieve [B2B shared catalog feature set ](https://github.com/magento/magento2/issues/28550)

### Related Pull Requests
https://github.com/magento/magento2/pull/29883
https://github.com/magento/partners-magento2ee/pull/319

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pmarjan**
### Description (*)
Fixes https://github.com/magento/magento2/issues/29880

Collection Processors (via Composite processor) are added. Context is passed as optional parameter.

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/319

### Fixed Issues (if relevant)

1. [GraphQL "categories" and "categoryList" do not consider Category Permissions configuration](https://github.com/magento/magento2/issues/29880)

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pmarjan** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+ * Apply pre-defined catalog filtering
+ *
+ * {@inheritdoc}
+ */
+class CatalogProcessor implements CollectionProcessorInterface
+{
+    /** @var SearchCriteriaCollectionProcessor */
+    private $collectionProcessor;
+
+    public function __construct(
```
Comment (BarnyShergold) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php:29]: No DocBlock

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+     * @param SearchCriteriaInterface $searchCriteria
+     * @param ContextInterface|null $context
+     * @return Collection
+     */
+    public function process(
+        Collection $collection,
+        SearchCriteriaInterface $searchCriteria,
+        ContextInterface $context = null
+    ): Collection
+    {
```
Comment (BarnyShergold) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php]: This { should be on previous line

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
There seems to be quite a lot of new code files here and some substantial changes to core methods - is there a reason why there is no test coverage?

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php (hunk 2 above)
Comment (pmarjan) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php]: hey @BarnyShergold 

the changes to core methods are with the purpose to expose modular collection processing, so other layers in the application can have a say what the collection consists of.
Check maybe implementation of "products" query for an example - it is the same idea.

On a closer look, please notice, there is no bug to be solved, or new requirement to be satisfied, just a refactor, thus, should be sufficient that already present api-functinal tests do not break (and they don't :) ), no need for new ones.

In more details, I would bring your attention to GraphQl/Catalog tests, and there all the Category*.Test.php and all tests from CategoriesQuery folder are the top relevant to verify the refactor.

Anyway, bigger picture is here: https://github.com/magento/magento2/issues/28550, if it helps to gain depth on the idea that is running in this PR. If any questions, just contact me... I can give you even more details.

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php (hunk 2 above)
Comment (BarnyShergold) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php]: @pmarjan - Your reasoning is sound - just wanted to check!
You just need to fix the minor format issues and the failing tests and all will be good.

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by pmarjan** [comment]
@magento run all tests

**Comment by BarnyShergold** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessorInterface.php [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+     *
+     * @param Collection $collection
+     * @param SearchCriteriaInterface $searchCriteria
+     * @param ContextInterface|null $context
+     * @return Collection
+     */
+    public function process(
+        Collection $collection,
+        SearchCriteriaInterface $searchCriteria,
+        ContextInterface $context = null
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessorInterface.php:32]: just a minor observation in comparison to the product processor
Noticed that there we passed attributes as well. I guess here we did not need it here. Not sure because this is meant as an extension point if we need to add it and just not use it ourselves..maybe other extensions will..

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php (hunk 1 above)
Comment (pmarjan) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessor/CatalogProcessor.php:29]: Done

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessorInterface.php (hunk 3 above)
Comment (pmarjan) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Categories/DataProvider/Category/CollectionProcessorInterface.php:32]: Good point. Now, I have edited to pass attributesNames as well. Currently are not used, but someday maybe someone extends this.

**Review by cpartica — APPROVED** [review]

**Review by cpartica — APPROVED** [review]
