### PR TITLE
Issue 35923: Internal Server Error in /V1/products/{sku}/links API En…

### LINKED ISSUE #35923: Internal Server Error in /V1/products/{sku}/links API Endpoints
### Preconditions and environment

- Magento version 2.4

### Steps to reproduce

1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Request PUT endpoint: /rest/default/V1/products/{sku}/links with payload:
_{
  "entity": {
  }
}_

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code as an error is thrown as $sku is a null argument in Magento\Catalog\Model\ProductRepository::getProductFromLocalCache()

### Additional information

output of var/log/system.log:

```
[2022-08-01T11:14:05.418205+00:00] main.CRITICAL: TypeError: Magento\Catalog\Model\ProductRepository::getProductFromLocalCache(): Argument #1 ($sku) must be of type string, null given, called in /magento/vendor/magento/module-catalog/Model/ProductRepository.php on line 284 and defined in /magento/vendor/magento/module-catalog/Model/ProductRepository.php:813
	Stack trace:
	#0 /magento/vendor/magento/module-catalog/Model/ProductRepository.php(284): Magento\Catalog\Model\ProductRepository->getProductFromLocalCache()
	#1 /magento/generated/code/Magento/Catalog/Model/ProductRepository/Interceptor.php(23): Magento\Catalog\Model\ProductRepository->get()
	#2 /magento/vendor/magento/module-catalog/Model/ProductLink/Repository.php(137): Magento\Catalog\Model\ProductRepository\Interceptor->get()
	#3 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ProductLink\Repository->save()
	#4 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ProductLink\Repository\Interceptor->___callParent()
	#5 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ProductLink\Repository\Interceptor->Magento\Framework\Interception\{closure}()
	#6 /magento/generated/code/Magento/Catalog/Model/ProductLink/Repository/Interceptor.php(23): Magento\Catalog\Model\ProductLink\Repository\Interceptor->___callPlugins()
	#7 [internal function]: Magento\Catalog\Model\ProductLink\Repository\Interceptor->save()
	#8 /magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
	#9 /magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
	#10 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
	#11 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
	#12 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
	#13 /magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
	#14 /magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
	#15 /magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
	#16 /magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
	#17 /magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
	#18 {main} [] []
```

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35923

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Model/ProductLink/Repository.php [hunk 1]
```diff
@@ -134,6 +132,9 @@ public function __construct(
      */
     public function save(\Magento\Catalog\Api\Data\ProductLinkInterface $entity)
     {
+        if (!$entity->getLinkedProductSku()) {
+            throw new NoSuchEntityException(__('The linked products sku is invalid. Verify the data and try again.'));
```
Comment (bgorski) [inline app/code/Magento/Catalog/Model/ProductLink/Repository.php]: The wording of this exception doesn't seem right since the SKU returned by the function is singular. Also, SKU should be all caps because it's an acronym. Please fix.

**Review by bgorski — CHANGES_REQUESTED** [review]
There's one message that needs to be adjusted. Apart from that, please check all the failing tests and determine if they're failing because of your code. I took a quick look and looks like only this static test is failing because of your changes:

```
FILE: /var/www/html/app/code/Magento/Catalog/Model/ProductLink/Repository.php
------------------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------------------
 64 | WARNING | Motivation behind the added @deprecated tag MUST be explained. @see tag MUST be used with reference to
    |         | new implementation when code is deprecated and there is a new alternative.
------------------------------------------------------------------------------------------------------------------------
```

Because you touched the repository class, fixing the test would be your job. If you don't know what to put in the `@see` tag, you can put something like `@see \Magento\Catalog\Model\ResourceModel\Product\Link::saveProductLinks()` because the deprecation (that happened years ago with the switch from 2.0.* to 2.1.0) was about the fact that previously in order to persist product links it was required to initialize all links on a product before the save on that product could occur. So let's point to that. Although the sniff is about providing an alternative, in this case no alternative is required. The way it's all working now for years is the alternative.

File: app/code/Magento/Catalog/Model/ProductLink/Repository.php (hunk 1 above)
Comment (rogerdz) [reply app/code/Magento/Catalog/Model/ProductLink/Repository.php]: thank @bgorski , I added new commit

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by bgorski** [comment]
@magento run Integration Tests

**Comment by bgorski** [comment]
@magento run Integration Tests

**Review by bgorski — COMMENTED** [review]
Approved - thank you for the contribution!

**Review by bgorski — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Retrieve auth token from the admin endpoint `/V1/integration/admin/`
2. Request PUT endpoint: `/rest/default/V1/products/{sku}/links` with payload:

```
{
    "entity": {}
}
```
**Before:** :heavy_multiplication_x:  Getting 500 internal server error in response and error as show in screenshot:

**Response:**
Screenshot 2022-09-30 at 3 37 43 PM

**Logs:**
Screenshot 2022-09-30 at 3 33 53 PM


**After:** :heavy_check_mark:  Getting 400 error as expected.
Screenshot 2022-09-30 at 3 35 59 PM

No additional manual test case is required as PR is related to error in response of rest api and also, automation is covered.
