### PR TITLE
 Resolve product price rounding issue when tax applied

### LINKED ISSUE #18025: Rounding problem on prices when adding tax to display prices
### Preconditions

1. Magento 2.2.x, 2.3.x & 2.4-develop
2. PHP 7.1.9 & 7.2
3. MySql 5.6.37

### Steps to reproduce
1.  Set _Configuration > Tax > Calculation Settings_ to following:
tax_calculation_settings
2. Set  _Configuration > Tax > Price Display Settings_ to _Including Tax_

### Expected result

1. Tax should be added to price set in product data when getting amount from classes extending Magento\Framework\Pricing\Price\AbstractPrice. Example Affirm Water Bottle with price of 7.00 with tax of 25 percent should result final value of 8.75

### Actual result

1. Magento\Framework\Pricing\Price\AbstractPrice returns value of 8.750001. This is visible example data-price-amount se to price wrapper element. See screenshot.
image

### Own findings

Problem seems to stem from Magento\Tax\Model\Calculation\AbstractCalculator. Calculator is adding delta of 0.000001 in deltaRound to prices, even if the $round is set to false and no rounding is happening. 

```php
    /**
     * Round price based on previous rounding operation delta
     *
     * @param float $price
     * @param string $rate
     * @param bool $direction
     * @param string $type
     * @param bool $round
     * @return float
     */
    protected function deltaRound($price, $rate, $direction, $type = self::KEY_REGULAR_DELTA_ROUNDING, $round = true)
    {
        if ($price) {
            $rate = (string)$rate;
            $type = $type . $direction;
            // initialize the delta to a small number to avoid non-deterministic behavior with rounding of 0.5
            $delta = isset($this->roundingDeltas[$type][$rate]) ?
                $this->roundingDeltas[$type][$rate] :
                0.000001;
            $price += $delta;
            $roundPrice = $price;
            if ($round) {
                $roundPrice = $this->calculationTool->round($roundPrice);
            }
            $this->roundingDeltas[$type][$rate] = $price - $roundPrice;
            $price = $roundPrice;
        }
        return $price;
    }
```

### PR DESCRIPTION
**Pull request by ravi-chandra3197**
### Description (*)

 Resolve product price rounding issue when tax applied #18025
### Fixed Issues (if relevant)

1. Fixes magento/magento2#18025: 

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ravi-chandra3197** [comment]
@magento run all tests

File: app/code/Magento/Tax/Model/Calculation/AbstractCalculator.php [hunk 1]
```diff
@@ -408,13 +408,14 @@ protected function deltaRound($price, $rate, $direction, $type = self::KEY_REGUL
...
+            $roundPrice = $price;
+            if ($round) {
+                // initialize the delta to a small number to avoid non-deterministic behavior with rounding of 0.5
             $delta = isset($this->roundingDeltas[$type][$rate]) ?
                 $this->roundingDeltas[$type][$rate] :
                 0.000001;
             $price += $delta;
-            $roundPrice = $price;
-            if ($round) {
+
```
Comment (engcom-Hotel) [inline app/code/Magento/Tax/Model/Calculation/AbstractCalculator.php:411]: In the updated logic we assigning  `$roundPrice = $price;` in line number 411 and calling `$this->calculationTool->round($roundPrice);` on `$roundPrice` without having `$delta` into it. 

This might be happen that delta is never included in the rounding calculation.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @ravi-chandra3197,

Thank you for the contribution!

Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1). Also fix the indentation of the code.

Also look into the below review comment.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
> Hello @ravi-chandra3197,
> 
> Thank you for the contribution!
> 
> Please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1). Also fix the indentation of the code.
> 
> Also look into the below review comment.

@engcom-Hotel, I have implemented the review comments also unit test is present for the tax calculation,  I have fixed the failed one also fixed all the static test failure. Moving it to Review.

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @ravi-chandra3197,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to Reproduce**

1.  Set _Configuration > Tax > Calculation Settings_ to following:
tax_calculation_settings
2. Set  _Configuration > Tax > Price Display Settings_ to _Including Tax_



**Before:** :heavy_multiplication_x: 


Screenshot 2025-12-23 at 3 12 36 pm



**After:** :heavy_check_mark: 



Screenshot 2025-12-23 at 3 16 07 pm





Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run all tests
