### PR TITLE
Fixed Critical Errors in MFTF tests

### LINKED ISSUE #34270: [PHP8] Failed MFTF tests for downloadable product
There are failed MFTF tests for MFTF tests. 

Please see magento log for corresponding test:
```java
<2021-10-06T13:11:57.592836+00:00> report.CRITICAL: Error: fsockopen(): Argument #3 ($error_code) cannot be passed by reference in /var/www/html/lib/internal/Magento/Framework/Filesystem/Driver/Http.php:253
{code}
Steps to reproduce:
* Run  following test with PHP8
  * AdminImportDownloadableProductsWithUrlLinksTest

Actual result:

Test failed with 
{code:java}
An error has happened during application run. See exception log for details.
```
Expected result:

Test should pass

### PR DESCRIPTION
**Pull request by anzin**
### Description (*)

Fixed failed MFTF tests for downloadable product.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34270

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php [hunk 1]
```diff
@@ -128,7 +129,8 @@ public function getChildProductIds(int $bundleId, ?int $websiteId = null): array
     private function getProducts(array $selectionProductIds, int $websiteId): array
     {
         $productIds = [];
-        $defaultStoreId = $this->storeManager->getWebsite($websiteId)->getDefaultStore()->getId();
+        $defaultStore = $this->storeManager->getWebsite($websiteId)->getDefaultStore();
+        $defaultStoreId = $defaultStore ? $defaultStore->getId() : Store::DEFAULT_STORE_ID;
         foreach ($selectionProductIds as $optionProductIds) {
             $productIds = array_merge($productIds, $optionProductIds);
         }
```
Comment (ihor-sviziev) [inline app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php]: Please fix array_merge in a loop:
```suggestion
        foreach ($selectionProductIds as $optionProductIds) {
            $productIds[] = $optionProductIds;
        }
        $productIds = array_merge([], ...$productIds); 
```

File: app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php [hunk 2]
```diff
@@ -128,7 +129,8 @@ public function getChildProductIds(int $bundleId, ?int $websiteId = null): array
     private function getProducts(array $selectionProductIds, int $websiteId): array
     {
         $productIds = [];
-        $defaultStoreId = $this->storeManager->getWebsite($websiteId)->getDefaultStore()->getId();
+        $defaultStore = $this->storeManager->getWebsite($websiteId)->getDefaultStore();
+        $defaultStoreId = $defaultStore ? $defaultStore->getId() : Store::DEFAULT_STORE_ID;
```
Comment (ihor-sviziev) [inline app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php]: Could you explain how this might not work correctly on PHP8, but works fine on PHP 7.4?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php (hunk 1 above)
Comment (anzin) [reply app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php]: Hello @ihor-sviziev, thanks for your review, I fixed code by you recommendation.

Thank you

File: app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php (hunk 2 above)
Comment (anzin) [reply app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php]: The problem here is that we have an exception :
`/group288/system.log:[2021-10-06T12:57:09.162852+00:00] report.CRITICAL: Error: Call to a member function getId() on null in /var/www/html/app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php:131`
 I investigation of it and was found that getDefaultStore method can return NULL, so I added an additional check.

Thank you.

Comment (ihor-sviziev) [reply app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php]: @anzin, but you should have the null value both on PHP 7.4 and on 8.x. Right?

Comment (anzin) [reply app/code/Magento/Bundle/Model/Product/SelectionProductsDisabledRequired.php]: @ihor-sviziev  Yes, you are right, but the getDefaultStore() method can return NULL in both PHP 7.4 and 8.x, so this check is necessary.

**Comment by anzin** [comment]
@magento run WebAPI Tests with env PHP 8.0

**Comment by xmav** [comment]
@magento run Unit Tests with env PHP 8.0

**Review by andrewbess — APPROVED** [review]

**Review by eduard13 — APPROVED** [review]
