### PR TITLE
Product import: Only the first additional image is validated.

### LINKED ISSUE #28236: Product import: Only the first additional image is validated
### Preconditions (*)
1. Magento 2.3.5
1. Magento 2.4-develop

### Steps to reproduce (*)
1. Import a product with multiple additional_images set where the second image is invalid (has spaces or parentheses)
- file contains broken path of second image `/1/1/1 11*2.jpg` instead of correct `/1/1/111*2.jpg`

[import*break_add_image.csv.txt](https://github.com/magento/magento2/files/5638527/import_break_add*image.csv.txt)

### Expected result (*)

1. All additional images should be validated

### Actual result (*)

1. Only the first image is validated because the loop exists after the first pass
image

This is the cause of problem: https://github.com/magento/magento2/blob/2.3.5/app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php#L118
Only the first additional image gets validated because the loop has a `break;` at the end. It should probably just be removed.

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/28236

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/28236

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by irenelagno** [comment]
@magento run all tests

File: app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php [hunk 1]
```diff
@@ -114,8 +114,8 @@ public function isValid($value)
                         ]
                     );
                     $valid = false;
+                    break;
```
Comment (zakdma) [inline app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php:117]: Maybe it would be better check all images and add messages for all invalid images
Now it just break after first invalid image
Please also change test accordingly.

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php (hunk 1 above)
Comment (engcom-Kilo) [reply app/code/Magento/CatalogImportExport/Model/Import/Product/Validator/Media.php:117]: There is no sense to show all errors as they are not related to every image, but to row in csv in general.

**Review by zakdma — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Navigate to System > Data Transfer > Import
2. Select 'Products' from *Entity Type* drop-down list
3. Select 'Add/Update' from *Import Behavior*
4. Select a file to import and upload csv file with multiple additional_images set where the second image is invalid
Selection_239
use the test file attached to the issue description [import*break_add_image.csv.txt](https://github.com/magento/magento2/files/5638527/import_break_add*image.csv.txt)
5. Click on **Check Data** button

**Before fix**:
The second image is not validated, no warning about the wrong path
before fix

**After fix**
A warning message appears, Wrong URL/path used. Import is interapted
After fix

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-31397`.
