### PR TITLE
Accessibility: WAI-ARIA roles nesting wrong in menu

### LINKED ISSUE #40045: [Issue] Accessibility: WAI-ARIA roles nesting wrong in menu
This issue is automatically created based on existing pull request: magento/magento2#38617: Accessibility: WAI-ARIA roles nesting wrong in menu

---------

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/40045

### Manual testing scenarios (*)

1. Open the Lighthouse and do the Accessibily analysis **without** this PR 

Screenshot from 2024-04-14 11-52-16

2. Open the Lighthouse and do the Accessibily analysis **with** this PR 

Screenshot from 2024-04-14 11-56-37

### PR DESCRIPTION
**Pull request by mirianfalconi**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/40045

### Manual testing scenarios (*)

1. Open the Lighthouse and do the Accessibily analysis **without** this PR 

Screenshot from 2024-04-14 11-52-16

2. Open the Lighthouse and do the Accessibily analysis **with** this PR 

Screenshot from 2024-04-14 11-56-37

### Resolved issues:
1. [x] resolves magento/magento2#40045: Accessibility: WAI-ARIA roles nesting wrong in menu

### CODE REVIEW

**Comment by mirianfalconi** [comment]
@magento run all tests

File: app/code/Magento/Theme/Block/Html/Topmenu.php [hunk 1]
```diff
@@ -246,7 +246,7 @@ protected function _getHtml(
             }
 
             $html .= '<li ' . $this->_getRenderedMenuItemAttributes($child) . '>';
-            $html .= '<a href="' . $child->getUrl() . '" ' . $outermostClassCode . '><span>' . $this->escapeHtml(
+            $html .= '<a href="' . $child->getUrl() . '" ' . $outermostClassCode . ' role="menuitem"><span>' . $this->escapeHtml(
```
Comment (Franciscof-Serfe) [inline app/code/Magento/Theme/Block/Html/Topmenu.php]:
```suggestion
            $html .= '<a href="' . $child->getUrl() . '" '
            . $outermostClassCode
            . ' role="menuitem"><span>'
            . $this->escapeHtml(
```

To fix coding standard:

FILE: /var/www/html/app/code/Magento/Theme/Block/Html/Topmenu.php
-------------------------------------------------- --------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
-------------------------------------------------- --------------------
 249 | WARNING | Line exceeds 120 characters; contains 129 characters

**Comment by mirianfalconi** [comment]
@magento run all tests

**Comment by Franciscof-Serfe** [comment]
@magento give me test instance

**Comment by Franciscof-Serfe** [comment]
image

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @mirianfalconi,

Thanks for the collaboration!

The changes seems good to us. But please fix the failed static tests.

Thanks

**Comment by mirianfalconi** [comment]
@magento I'm working on it

**Comment by mirianfalconi** [comment]
@magento run all tests

**Comment by mirianfalconi** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento create issue

**Comment by engcom-Bravo** [comment]
Hi @mirianfalconi,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Open the Lighthouse and do the Accessibily analysis


**Before:** :heavy_multiplication_x: 


Screenshot 2025-07-07 at 3 00 45 pm











**After:** :heavy_check_mark: 


Screenshot 2025-07-07 at 3 21 05 pm




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B
