### PR TITLE
Fixed 22511

### LINKED ISSUE #22511: Special From Date set to today's date when Use Default Date checked in Store scope
### Preconditions (*)

1. Magento 2.2.8
2. Configured product with Special Price, Special From Date, and Special To Date set at the All Stores Scope.

### Steps to reproduce (*)

1. Edit a product in store view (say Default Store View) that has a Special Price, Special From Date, and Special To Date already set at the All Store Scope.
2. Open the Advanced Pricing popup.
3. Note that the Use Default Value boxes should be checked for Special From Date and Special To Date, if not, check them and close the Advance Price Window.
4. Save the product.
5. After the page reloads, open the Advanced Price window again.
6. Observe Screen.

### Expected result (*)
I expected the Use Default Value boxes to remain checked on both the Special From Date and Special To Date and for them to display the values set at the All Store Scope.

### Actual result (*)
The Special From Date "Use Default Value" is unchecked and the value is set to today's date.

While debugging this I found `Magento\Catalog\Observer\SetSpecialPriceStartDate` which is set to run before product save.  It has the following function

```
    /**
     * Set the current date to Special Price From attribute if it empty
     *
     * @param \Magento\Framework\Event\Observer $observer
     * @return $this
     */
    public function execute(\Magento\Framework\Event\Observer $observer)
    {
        /** @var  $product \Magento\Catalog\Model\Product */
        $product = $observer->getEvent()->getProduct();
        if ($product->getSpecialPrice() && !$product->getSpecialFromDate()) {
            $product->setData('special_from_date', $this->localeDate->date());
        }

        return $this;
    }
```

Which appears to be setting the Special From Date to today if there's no Special From Date set, but a Special Price is set.  Earlier in the execution of the save though, `Magento\Catalog\Controller\Adminhtml\Product\Initialization\Helper` set's the values of attributes that are set to "Use Default Value" to either `null` or `false` depending on the type of attribute.  So when this observer is ran, it get's `null` for the Special From Date, and since we have a Special From Price set, it ignores the "Use Default Value" and sets the Special From Date.

I'm not entirely sure though what to do for a solution to this.  For the moment though I've removed the Observer to prevent the undesired behavior.  But it seems to me like this should not be the behavior when saving products at the store level.

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
Fixed #22511 in this PR.
### Description (*)

I have added check that special from date value is not Boolean and value not set then add today's date
to this field.  

### Fixed Issues (if relevant)

1.#22511
2. ...

### Manual testing scenarios (*)

1. Followed all steps explained in issue.
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

File: app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php [hunk 1]
```diff
@@ -38,7 +38,8 @@ public function execute(\Magento\Framework\Event\Observer $observer)
     {
         /** @var  $product \Magento\Catalog\Model\Product */
         $product = $observer->getEvent()->getProduct();
-        if ($product->getSpecialPrice() && ! $product->getSpecialFromDate()) {
+        $specialFromDate = $product->getSpecialFromDate();
+        if ($product->getSpecialPrice() && !is_bool($specialFromDate) && !$specialFromDate) {
```
Comment (orlangur) [inline app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php]: Looks like it should be check for `=== null` instead. Also, cover corresponding case with unit test.

**Review by orlangur — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php (hunk 1 above)
Comment (mahesh-rajawat) [reply app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php]: @orlangur if i am using condition `if ($product->getSpecialPrice() && $specialFromDate === null)` it can save blank value as well.

Comment (mahesh-rajawat) [reply app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php]: @orlangur , please update if it is correct.

Comment (orlangur) [reply app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php]: `is_bool` is very odd condition here. Should we do `$product->setData('special_from_date'` only when value is `null`?

**Review by orlangur — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php (hunk 1 above)
Comment (mahesh-rajawat) [reply app/code/Magento/Catalog/Observer/SetSpecialPriceStartDate.php]: @orlangur , i will update it. Thanks

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-5129](https://jira.corp.magento.com/browse/ENGCOM-5129) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed

**Review by orlangur — CHANGES_REQUESTED** [review]
Please squash changes into a single commit so that we have perfectly clean history 😉

**Comment by mahesh-rajawat** [comment]
> Please squash changes into a single commit so that we have perfectly clean history

@orlangur , All commits are squashed now.

**Comment by mahesh-rajawat** [comment]
@orlangur , Any update on it?

**Review by orlangur — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @orlangur, thank you for the review.
[ENGCOM-5129](https://jira.corp.magento.com/browse/ENGCOM-5129) has been created to process this Pull Request

**Comment by VasylShvorak** [comment]
:heavy_check_mark: QA passed
