### PR TITLE
34858: Adjust validation for upload ICO files

### LINKED ISSUE #34858: Favicon Icon upload form in Magento does not actually support .ico file types
When attempting to upload a favicon file of .ico extension type in Magento admin, Magento will not deem the file as valid.
Tested on a clean composer install of Magento 2.4.3-p1 with a PHP version of 7.4.13.

Perhaps the usage of PHP's `imagecreatefromstring` causes for an .ico file type to always be deemed invalid by Magento. The exception is thrown: "Warning: imagecreatefromstring(): one parameter to a memory allocation multiplication is negative or zero, failing operation gracefully
 in /var/www/html/vendor/magento/module-media-storage/Model/File/Validator/Image.php on line 64"

### Preconditions (*)
1. Unaltered, clean install of Magento version 2.4.3-p1
2. PHP version 7.4.13
3. DBMS: MySQL (ver. 5.5.5-10.2.40-MariaDB-1:10.2.40+maria~bionic)
Case sensitivity: plain=exact, delimited=exact
Driver: MySQL Connector/J (ver. mysql-connector-java-8.0.25 (Revision: 08be9e9b4cba6aa115f9b27b215887af40b159e0), JDBC4.2)
Effective version: MariaDB (ver. 10.2.40)
4. Chrome browser version Version 96.0.4664.110 (Official Build) (x86_64)
5. MacBook Pro - OS: Catalina 10.15.7

### Steps to reproduce (*)
1. Login to Magento admin
2. Navigate to Content -> Design -> Configuration
3. Click 'Edit' on any of the records shown in the grid
4. Scroll to 'Other Settings'
5. Expand 'HTML Head'
6. Under the 'Favicon Icon' section, click 'Upload'
7. Select a valid .ico file, click 'Open'

### Expected result (*)
1. It should provide a preview of the icon below the upload form and allow for the admin user to save the configuration settings.

### Actual result (*)
1. An error was shown to the admin:
image

### PR DESCRIPTION
**Pull request by mmezhensky**
### Description (*)
This PR adjusted validation for images files in ICO format.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#34858

### Manual testing scenarios (*)

1. Login to Magento admin
2. Navigate to Content -> Design -> Configuration
3. Click 'Edit' on any of the records shown in the grid
4. Scroll to 'Other Settings'
5. Expand 'HTML Head'
6. Under the 'Favicon Icon' section, click 'Upload'
7. Select a valid .ico file, click 'Open'

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mmezhensky** [comment]
@magento run all tests

File: app/code/Magento/MediaStorage/Model/File/Validator/Image.php [hunk 1]
```diff
@@ -60,10 +60,16 @@ public function isValid($filePath): bool
...
             try {
-                //phpcs:ignore Magento2.Functions.DiscouragedFunction
-                $image = imagecreatefromstring($this->file->fileGetContents($filePath));
+                if ($fileMimeType !== 'image/vnd.microsoft.icon') {
+                    //phpcs:ignore Magento2.Functions.DiscouragedFunction
+                    $image = imagecreatefromstring($this->file->fileGetContents($filePath));
+                } else {
+                    $imagick = new \Imagick();
+                    $imagick->setFormat('ICO');
+                    $image = $imagick->readImageBlob($this->file->fileGetContents($filePath));
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: I don't think it's a good option because the Imagick extension is currently optional, and by default, Magento uses lib gd.
Can it handle this case?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/MediaStorage/Model/File/Validator/Image.php (hunk 1 above)
Comment (mmezhensky) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: Hi @ihor-sviziev 
Lib **GD** does not support the `ICO` format and error returns.
After a long search for a solution, I think **Imagick** is the most suitable option, or we will have to install a third-party extension.

Comment (ihor-sviziev) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: @mmezhensky I'm OK with using imagick when it's available. But when it's not?

Comment (mmezhensky) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: @ihor-sviziev `Imagick` is already used in Magento.

Comment (ihor-sviziev) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: Yes, but only as **optional** dependence

Comment (Den4ik) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: @mmezhensky I'm agree with @ihor-sviziev and believe that we could use `Magento\Framework\Image\Factory` here because it will use default adapter selected in configs.
If call of `open` throw exception than image is not valid.

**Review by Den4ik — CHANGES_REQUESTED** [review]

File: app/code/Magento/MediaStorage/Model/File/Validator/Image.php (hunk 1 above)
Comment (mmezhensky) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: Hi @Den4ik 
Thanks for your information, but I tried to do it, and I always get an error for `ICO` files because **`GD2` does not support this format**, and `Magento\Framework\Image\Adapter\ImageMagick` has no function for setting `ICO` format.

To use `Magento\Framework\Image\Factory`, we always need to pass `$adapterName = "IMAGEMAGICK"` and extend `Magento\Framework\Image\Adapter\ImageMagick` class to add the ability to install the form.
But I think it will be a significant change in the Magento Framework that may cause problems in the future, so I suggest using the fix option I suggested earlier.

СС @ihor-sviziev

Comment (Den4ik) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: Hi @mmezhensky. Thanks for your work.

> we always need to pass $adapterName = "IMAGEMAGICK"

It's not quite true. AdapterFactory retrieve current selected adapter from stores configuration. And my mind is that we receive exception if imagick is not selected as adapter at Stores config. It's guarant that user/administrator that select imagick as adapter will be sure that it's installed for php.

Comment (mmezhensky) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: @Den4ik 
Yes, but even if imagick is installed in the configuration and it is installed on the server, we will still get an exception because we need to set ICO format for the imagick object (but we can't do it without changes in `Magento\Framework\Image\Adapter\ImageMagick`).

Comment (Den4ik) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: @mmezhensky I agree that it require some changes for `ImageMagick` class, but I don't see any problems use something like that in `open` method

```
            if (is_callable('exif_imagetype')) {
                $fileType = exif_imagetype($this->_fileName);
                if ($fileType === IMAGETYPE_ICO) {
                    $filename = 'ico:' . $filename;
                }
            }
            $this->_imageHandler = new \Imagick($filename);
```
It provide total support of ico files for image magick adapter
@ihor-sviziev @sidolov What do you think?

**Comment by mmezhensky** [comment]
@magento run all tests

File: app/code/Magento/MediaStorage/Model/File/Validator/Image.php (hunk 1 above)
Comment (mmezhensky) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: I prepared these changes.
Thx!

**Comment by Den4ik** [comment]
@magento run Functional Tests CE, Functional Tests EE

File: app/code/Magento/MediaStorage/Model/File/Validator/Image.php [hunk 2]
```diff
@@ -60,10 +69,8 @@ public function isValid($filePath): bool
 
         if (in_array($fileMimeType, $this->imageMimeTypes)) {
             try {
-                //phpcs:ignore Magento2.Functions.DiscouragedFunction
-                $image = imagecreatefromstring($this->file->fileGetContents($filePath));
-
-                $isValid = $image ? true : false;
+                $imagick = $this->imageFactory->create($filePath);
+                $imagick->open();
```
Comment (Den4ik) [inline app/code/Magento/MediaStorage/Model/File/Validator/Image.php]:
```suggestion
                $image = $this->imageFactory->create($filePath);
                $image->open();
```

Comment (Den4ik) [reply app/code/Magento/MediaStorage/Model/File/Validator/Image.php]: It's not an issue but I believe that use of `$image` as variable name is more correct

**Review by Den4ik — CHANGES_REQUESTED** [review]

**Comment by mmezhensky** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Integration Tests

**Review by Den4ik — APPROVED** [review]
✅ Looks good for me

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9397](https://jira.corp.magento.com/browse/ENGCOM-9397) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
@mmezhensky Could you add unit tests for implemented changes?

**Comment by engcom-Delta** [comment]
:x: QA not Passed

Favicon Icon upload form does not support .ico file types in Magento 2.4 Develop.

**Preconditions:**

1. We should have fresh installation of Magento 2.4 Develop. 
2. We should have .Ico files ready for uploading

**Manual Scenario Steps**

1. Log in to Magento admin
2. Navigate to Content -> Design -> Configuration
3. Click 'Edit' on any of the records shown in the grid
4. Scroll to 'Other Settings'
5. Expand 'HTML Head'
6. Under the 'Favicon Icon' section, click 'Upload'
7. Select a valid “.ico” extension file, click 'Open'
8. Validate the file upload results


**:heavy_check_mark: Expected result After Fix** 
- .Ico files should be uploaded successfully.



**:x: Actual result After Fix** 
- .Ico files are not getting uploaded, throwing the ''File validation Failed " popup


FYI- downloaded the ico files [from link](https://icon-icons.com/pack/Furniture-(Flat)/3325)

**Review by engcom-Delta — CHANGES_REQUESTED** [review]
Thanks for your contribution and collaboration @mmezhensky , @ihor-sviziev  and @Den4ik 
Based on the above comments moving to 'Request Changes' status

**Comment by engcom-Lima** [comment]
Hi @engcom-Delta,
Magento by default uses **GD Library** which does not support **ico** extension.
In order to verify the issue, the **ImageMagick** extension needs to be set in **Stores->Configuration->Advanced->Developer->Image Processing Settings**

**Note:** ImageMagic needs to be installed on server in order to set the **ImagMagic** option in magento.

Request you to kindly verify the issue after installing ImageMagic on server and setting it as the default adapter

Thanks!

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have ImageMagic installed in your system and extension enabled under server php.ini; [REFER HERE](https://stackoverflow.com/questions/921780/how-to-install-imagemagick-on-mamp)
2. Have Magento latest installed.
3. Have some .ico files in the system to upload; here is - [ico files downloadable link](https://icon-icons.com/pack/Furniture-(Flat)/3325)


**Manual testing scenario:**

1. Log in to Magento admin; Navigate to Content -> Design -> Configuration

2. Click 'Edit' on any of the records shown in the grid > Scroll to 'Other Settings' > Expand 'HTML Head'
 
3. Under the 'Favicon Icon' section, click 'Upload'; Select a valid “.ico” extension file, click 'Open'

4. Validate the file upload results


**Before:** :heavy_multiplication_x: We were getting an error message "File Validation Failed".

image


**After:** :heavy_check_mark: File is getting uploaded successfully.

image


Tried to save the uploaded ico file and getting it saved successfully.
