### PR TITLE
FIx text and images are displayed cropped if folder has long name && Filters isn`t applied on the "Category" 

### LINKED ISSUE #1758: Text and images are displayed cropped if folder has long name
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
### Steps to reproduce (*)

1. Go to Content -> Media Gallery
2. Create a folder with long name (for example: `TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTT`)
3. Select it

### Expected result (*)

"We couldn't find any records." text should be displayed without cropping it there is no image. If there is an image, it should also be displayed without cropping.
### Actual result (*)

The "We couldn't find any records." text displays cropped. If there is an image, it is also displayed cropped.
Peek 2020-08-17 12-42

### LINKED ISSUE #1763: Filters aren`t applied on the "Category" grid
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled
4. Add an image to a category

### Steps to reproduce (*)

1. Go to Content -> Media Gallery
2. Select uploaded image
3. Click on three dots -> View Details 
4. Click on the link 'Categories..." in 'Used in' attribute
5. Delete the `?filters[asset_id]=[1]` part of request from address line -> Press `Enter` key
6. Pay attention to the 'Active filters:'
7. Click on the "Clear all" link
8. Wait for a few seconds and reload the page
9. Click on the "Filters" button
10. Enter any word in the "ID" field -> Apply Filters
11. Try to apply any filter

### Expected result (*)

Filter should be applied 

### Actual result (*)

Filters aren`t applied on the "Category" grid 
Peek 2020-08-18 10-53

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1758: Text and images are displayed cropped if folder has long name
2. Fixes magento/adobe-stock-integration#1763: Filters isn`t applied on the "Category" 

### Manual testing scenarios (*)
1. Go to Content -> Media Gallery
2. Create a folder with long name (for example: `TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTT`)
3. Select it

"We couldn't find any records." text should be displayed without cropping it there is no any image. If there is any image, it should also be displayed without cropping.
1. Go to Content -> Media Gallery
2. Select uploaded image
3. Click on three dots -> View Details 
4. Click on the link 'Categories..." in 'Used in' attribute
5. Delete the `?filters[asset_id]=[1]` part of request from address line -> Press `Enter` key
6. Pay attention to the 'Active filters:'
7. Click on the "Clear all" link
8. Waite a few seconds and reload the page
9. Click on the "Filters" button
10. Enter any word in the "ID" field -> Apply Filters
11. Try to apply any filter

Filter should be applied 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php [hunk 1]
```diff
@@ -84,8 +84,9 @@ private function getDirectories(): array
             }
 
             $pathArray = explode('/', $path);
+            $displayName = strlen(end($pathArray)) > 50 ? substr(end($pathArray),0,50)."..." : end($pathArray);
```
Comment (sivaschenko) [inline app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php]: Please create a constant for `50`

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the PR @Nazar65 ! Can you please cover the fixed cases with the MFTF tests:
1. Creating a folder with more than 50 characters name
2. Applying a filter after following the link with url-filter-applier

File: app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php (hunk 1 above)
Comment (Nazar65) [reply app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php [hunk 2]
```diff
@@ -84,8 +86,11 @@ private function getDirectories(): array
             }
 
             $pathArray = explode('/', $path);
+            $displayName = strlen(end($pathArray)) > self::NAME_LENGTH ?
+                         substr(end($pathArray), 0, self::NAME_LENGTH) . "..." :
+                         end($pathArray);
             $directories[] = [
-                'data' => count($pathArray) > 0 ? end($pathArray) : $path,
+                'data' => count($pathArray) > 0 ? $displayName : $path,
```
Comment (sidolov) [inline app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php]: Not sure it's a right way to trim name on the backend, it would be better adapt frontend application to handle long names. Let's imagine that someone will decide to extend frontend implementation and provide new design (where long names will look good) and with such approach, we are limiting 3d party developers to use trimmed names only.

**Review by sidolov — CHANGES_REQUESTED** [review]

File: app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php (hunk 2 above)
Comment (Nazar65) [reply app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php]: agree but there is some limitation in a frontend so i decided it can be more easier to fix this in a back-end part, but i will try one more time fix this behavior on a frontend.

Comment (Nazar65) [reply app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php:93]: https://github.com/vakata/jstree/commit/3c5bf416d85a32392c3b330ad20e386357fdc367

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php (hunk 2 above)
Comment (Nazar65) [reply app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php]: @sidolov i'v changed implementation, instead of cutting folders as it was done in old media gallery and there is also this issue here ->
Screenshot_2020-08-20 Default Category (ID 2) Categories Inventory Catalog Magento Admin

so when we have a long folders and the block is too small for it i had added ability to scroll, as we can have alot of folders created one in one and soon or later we also have same issue, so i think only adding ability to vertical scrolling when there is a lot folder will be correct

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php (hunk 2 above)
Comment (sidolov) [reply app/code/Magento/MediaGalleryUi/Model/Directories/GetFolderTree.php]: @Nazar65 sounds good to me! Look like it's the only solution in such case.

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8047](https://jira.corp.magento.com/browse/ENGCOM-8047) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by sidolov — APPROVED** [review]
