### PR TITLE
Backend: focus search field when pressing forwardslash - '/'

### LINKED ISSUE #29551: [Issue] Backend: focus search field when pressing forwardslash - '/'
keydown event listener in magento backend to activate global search form if forward slash was pressed.

### Preconditions (*)
1. Magento 2.4

### Steps to reproduce (*)

1. Login to backend
2. Press '/' on the keyboard.
3. Start typing a query.

### Expected result (*)
No need to grab the mouse!

### Actual result (*)
Not working with forward slash

https://user-images.githubusercontent.com/306080/78894531-e03bd000-7a75-11ea-9f27-5378aca18200.gif

### PR DESCRIPTION
**Pull request by vovayatsyuk**
### Description
This PR adds a keydown event listener in magento backend to activate global search form if forward slash was pressed.

**No need to grab the mouse!**

ezgif com-video-to-gif

### Manual testing scenarios (*)
1. Login to backend
2. Press '/' on the keyboard.
3. Start typing a query.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29551: Backend: focus search field when pressing forwardslash - '/'

### CODE REVIEW

**Comment by sidolov** [comment]
@magento create issue

**Comment by ihorvansach** [comment]
@magento run all tests

**Comment by ihorvansach** [comment]
@magento run Functional Tests B2B

**Comment by ihorvansach** [comment]
Hello @vovayatsyuk, thank you for your contribution. Can you please add a few improvements to the pull request?

1. Define key code 191 in the Magento_Ui/js/lib/key-codes (https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/lib/key-codes.js), here is an example of key-codes use https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Ui/view/base/web/js/grid/columns/image-preview.js

2. Better to rename "e" variable into "event"

3. Could you please also add "multiselect" to the inputs array

4. Cover this case with MFTF tests (https://devdocs.magento.com/mftf/docs/introduction.html)

5. Don't forget to sign the Adobe CLA agreement.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@vovayatsyuk could you update your PR with requested changes in https://github.com/magento/magento2/pull/27674#issuecomment-690914959 ?

**Comment by vovayatsyuk** [comment]
> Define key code 191

Done.

> Rename "e" variable into "event"

Done.

> Add "multiselect" to the inputs array

Multiselect is a 'select' with `multiple` attribute, so it's already in the list.

> Cover this case with MFTF tests

I'll try to write the tests in a few days.

> Sign the Adobe CLA agreement.

Should be ok.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@vovayatsyuk can you please cover your changes by mftf test?
Thank you.

**Comment by vovayatsyuk** [comment]
Will do today.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by vovayatsyuk** [comment]
The test is not ready yet. 

I don't know how to check the focus state on the field after '/' was pressed on the body. Looks like `seeElement` and `waitForElementVisible` checking element visibility in dom structure. 

While the tests are passed, they actually will pass even if the field doesn't get the focus.

**Comment by ihor-sviziev** [comment]
@engcom-Charlie could you help with writing MFTF tests?

**Comment by vovayatsyuk** [comment]
Fixed. 🎉

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/design/adminhtml/Magento/backend/web/js/theme.js [hunk 1]
```diff
@@ -345,6 +346,25 @@ define('globalSearch', [
             this.input.on('focus.activateGlobalSearchForm', function () {
                 self.field.addClass(self.options.fieldActiveClass);
             });
+
+            $(document).keydown(function (event) {
```
Comment (ihor-sviziev) [inline app/design/adminhtml/Magento/backend/web/js/theme.js]: Could you switch to using 'on' with a `activateGlobalSearchForm` namespace, like this?
```suggestion
            $(document).on('keydown.activateGlobalSearchForm', function (event) {
```

So in case if we need - we'll be able to use `off` method only for this specific event listener

File: app/design/adminhtml/Magento/backend/web/js/theme.js [hunk 2]
```diff
@@ -312,8 +312,9 @@ define('globalNavigation', [
 
 define('globalSearch', [
     'jquery',
+    'Magento_Ui/js/lib/key-codes',
     'jquery/ui'
```
Comment (ihor-sviziev) [inline app/design/adminhtml/Magento/backend/web/js/theme.js]: Could you replace using `jquery/ui` to what component really needed?
```suggestion
    'jquery-ui-modules/widget'
```

I don't see any other other usages here rather than jquery widget, and we'll fix the following warning for this specific case:
https://github.com/magento/magento2/blob/9544fb243d5848a497d4ea7b88e08609376ac39e/lib/web/jquery/compat.js#L43-L48

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Just have a few minor suggestions. Could you apply them?

**Comment by ihor-sviziev** [comment]
Thank you for your fixes! Let's start the tests

@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE, Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8393](https://jira.corp.magento.com/browse/ENGCOM-8393) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Login to backend
2. Press '/' on the keyboard.
3. Start typing a query.

**After:** :heavy_check_mark: the search box focuses when clicking on the slash - '/'

Peek 2020-11-02 13-00
