### PR TITLE
Duplicate cache fpc for same page with same query

### LINKED ISSUE #38269: Duplicate cache fpc for same page with same query
### Preconditions and environment

- Magento version 2.4-develop + sameple data 
- Use developer mode
- Use build in fpc 

### Steps to reproduce

1. Clear cache: bin/magento cache:clean
2. Run command: curl -I --location-trusted 'https://magento2.test/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug, it will return x-magento-cache-debug: MISS => correct
3. Run command: curl -I --location-trusted 'https://magento2.test/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug, it will return x-magento-cache-debug: HIT => correct 
4. Run command: curl -I --location-trusted 'https://magento2.test/gear/bags.html?style_bags=24&activity=8' | grep -i X-Magento-Cache-Debug => it return x-magento-cache-debug: MISS => wrong
5. Run command: curl -I --location-trusted 'https://magento2.test/gear/bags.html?activity=8&style_bags=24&' | grep -i X-Magento-Cache-Debug => it return x-magento-cache-debug: MISS => wrong

### Expected result

https://magento2.test/gear/bags.html?style_bags=24&activity=8 and https://magento2.test/gear/bags.html?activity=8&style_bags=24 and https://magento2.test/gear/bags.html?activity=8&style_bags=24& use same fpc 

### Actual result

https://magento2.test/gear/bags.html?style_bags=24&activity=8 and https://magento2.test/gear/bags.html?activity=8&style_bags=24 and https://magento2.test/gear/bags.html?activity=8&style_bags=24& use difference fpc identifier  => increase page cache folder size

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#38269

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Integration Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rogerdz,

Thanks for the contribution!

Please check the build failures, it seems they are failing due to code changes.

Thanks

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Static Tests

**Comment by rogerdz** [comment]
@magento run Static Tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Unit Tests, Static Tests, Magento Health Index, Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Magento Health Index

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @rogerdz,

Thank you for working on Unit test failure. In order to move further on this PR, build should be green; can you please have a look into Magento Health Index failure.

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
Hi @engcom-Charlie, 
I fixed all test, Functional Tests fail seem not related my code

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/PageCache/Model/App/Request/Http/IdentifierForSave.php [hunk 1]
```diff
@@ -38,14 +38,38 @@ public function __construct(
...
         return sha1($this->serializer->serialize($data));
     }
+
+    /**
+     * Reconstruct url and sort query
+     *
+     * @param string $url
+     * @return array
+     */
+    private function reconstructUrl($url)
```
Comment (engcom-Hotel) [inline app/code/Magento/PageCache/Model/App/Request/Http/IdentifierForSave.php]:
```suggestion
    private function reconstructUrl(string $url): array
```

File: lib/internal/Magento/Framework/App/PageCache/Identifier.php [hunk 2]
```diff
@@ -50,13 +50,37 @@ public function __construct(
...
         return sha1($this->serializer->serialize($data));
     }
+
+    /**
+     * Reconstruct url and sort query
+     *
+     * @param string $url
+     * @return array
+     */
+    private function reconstructUrl($url)
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/App/PageCache/Identifier.php]:
```suggestion
    private function reconstructUrl(string $url): array
```

File: app/code/Magento/PageCache/Test/Unit/Model/App/Request/Http/IdentifierForSaveTest.php [hunk 3]
```diff
@@ -98,10 +104,79 @@ public function testGetValue(): void
...
+                        '',
+                        self::VARY
+                    ]
+                )
+            ),
+            $this->model->getValue()
+        );
+    }
+
+    public function testGetValueWithQuery(): void
```
Comment (engcom-Hotel) [inline app/code/Magento/PageCache/Test/Unit/Model/App/Request/Http/IdentifierForSaveTest.php:173]:
```suggestion
    /**
 * Test get identifier for save value with query parameters.
 *
 * @return void
 */
    public function testGetValueWithQuery(): void
```

File: lib/internal/Magento/Framework/App/Test/Unit/PageCache/IdentifierTest.php [hunk 4]
```diff
@@ -173,12 +221,74 @@ public function testGetValue(): void
...
+                        'http://example.com/path1/',
+                        '',
+                        self::VARY
+                    ]
+                )
+            ),
+            $this->model->getValue()
+        );
+    }
+
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/App/Test/Unit/PageCache/IdentifierTest.php:251]:
```suggestion
/**
 * Test get identifier for save value with query parameters.
 *
 * @return void
 */
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rogerdz,

The changes seems good to me but please fix the below review comments.

Thanks

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @rogerdz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**


As per the Description.


**Before:** :heavy_multiplication_x: 

Screenshot 2024-09-13 at 14 00 06


**After:** :heavy_check_mark: 


Screenshot 2024-09-13 at 14 16 31



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
The Functional B2B test failures are not consistent in recent 2 builds. They are neither part of PR now failing because of PR changes. Seems to be flaky, hence moving it to Merge in Progress.

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/f751c6d7e59f68f664f9240db0474fcf/Functional/allure-report-b2b/index.html#categories/16b25a50b4a8b68f5548cdba82ebd5f8/65d76e88635b8175/

image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/c84d5d0c039fd077a616edb568dd271b/Functional/allure-report-b2b/index.html#categories

image

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Static Tests, Functional Tests CE, Functional Tests B2B, Functional Tests EE

**Comment by engcom-Dash** [comment]
The Functional B2B and CE test failures seem flaky and some of these failures are known issues. They are neither part of PR now failing because of PR changes. Hence moving it to Merge in Progress.

**Known Issues:**
MultiShippingWithCreationNewCustomerAndAddressesDuringCheckoutTest: [ACQE-7229](https://jira.corp.adobe.com/browse/ACQE-7229)
StorefrontReuseCouponCodeAfterOrderCanceledTest: [ACQE-7230](https://jira.corp.adobe.com/browse/ACQE-7230)
VerifyDefaultWYSIWYGToolbarOnProductTest: [ACQE-7227](https://jira.corp.adobe.com/browse/ACQE-7227)

**Functional Tests B2B** 
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/95b9984bc468ba92a21b2e99d9e1191e/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/439533c23bc0fa30bcd92ba6c99a9194/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d
image


**Functional Tests CE**
Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/4a790f66b688e1fb03a7fe28cdca61a9/Functional/allure-report-ce/index.html#categories/6d7e37752c3cc83cb3d2063131f608bb/190a9b2622ef3f4/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38270/dc0707fb0b4f81610a28b9acfd370cfe/Functional/allure-report-ce/index.html#categories/6d7e37752c3cc83cb3d2063131f608bb/5ba8ed3be74fdf64/
image

**Comment by engcom-Dash** [comment]
Moving back to the changes requested, as there are conflicts in the files

**Comment by engcom-Charlie** [comment]
Hi @rogerdz,

Did you get a chance to look into the conflicts as mentioned [here](https://github.com/magento/magento2/pull/38270#issuecomment-2575021371). Currently, we are closing this PR, once its done please feel free to reopen.

Thank you!

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
Hi @engcom-Charlie

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Hi @rogerdz,

The addressed [issue](https://github.com/magento/magento2/issues/38269) in this PR seems to be not exists anymore. 

The issue is not reproducible after trying below steps as mentioned in description in Magento2 repository.

1. Install fresh Magento **`2.4-develop`**
2. Install Sample data
3. Check FPC is set in magento instance
4. Enable developer mode
5. Clear the cache.
6. Sent below CURL request one after other, all gave the same result in magento 2 repository

- http://magento.local/gear/bags.html?activity=20
- http://magento.local/gear/bags.html?activity=20&style_bags=28
- http://magento.local/gear/bags.html?activity=20&performance_fabric=1&style_bags=28

All above URLs giving HIT. As, the issue is no more exits now, hence closing this PR for now. Please feel free to reopen it for any further updates.

Screenshot 2025-03-10 at 3 19 20 PM

**Comment by rogerdz** [comment]
Hi @engcom-Charlie ,
Issue still reproducible in my local 
image
Your test is not correct, please check https://github.com/magento/magento2/issues/38269#issuecomment-1862568163

**Comment by engcom-Charlie** [comment]
> Hi @rogerdz,
> 
> The addressed [issue](https://github.com/magento/magento2/issues/38269) in this PR seems to be not exists anymore.
> 
> The issue is not reproducible after trying below steps as mentioned in description in Magento2 repository.
> 
> 1. Install fresh Magento **`2.4-develop`**
> 2. Install Sample data
> 3. Check FPC is set in magento instance
> 4. Enable developer mode
> 5. Clear the cache.
> 6. Sent below CURL request one after other, all gave the same result in magento 2 repository
> 
> * http://magento.local/gear/bags.html?activity=20
> * http://magento.local/gear/bags.html?activity=20&style_bags=28
> * http://magento.local/gear/bags.html?activity=20&performance_fabric=1&style_bags=28
> 
> All above URLs giving HIT. As, the issue is no more exits now, hence closing this PR for now. Please feel free to reopen it for any further updates.
> 
> Screenshot 2025-03-10 at 3 19 20 PM

It seems that I have tried to reproduce the issue with PR code itself hence got this result.

The issue is reproducible on Magento2 repository and working fine on PR instance.

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento 2.4-develop
- Install Sample data

**Steps to reproduce**
- Check FPC is set in magento instance
- Enable developer mode
- Clear the cache.


**Before:** :heavy_multiplication_x: 
Result on below CURL requests on magento 2.4-develop
```
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: MISS
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: HIT
curl -I --location-trusted 'http://magento.local/gear/bags.html?style_bags=24&activity=8' | grep -i X-Magento-Cache-Debug: MISS
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24&' | grep -i X-Magento-Cache-Debug: MISS
```


Screenshot 2025-03-11 at 4 25 39 PM




**After:** :heavy_check_mark: 
```
Result on below CURL requests on PR branch
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: MISS
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24' | grep -i X-Magento-Cache-Debug: HIT
curl -I --location-trusted 'http://magento.local/gear/bags.html?style_bags=24&activity=8' | grep -i X-Magento-Cache-Debug: HIT
curl -I --location-trusted 'http://magento.local/gear/bags.html?activity=8&style_bags=24&' | grep -i X-Magento-Cache-Debug: HIT
```


Screenshot 2025-03-11 at 4 50 54 PM

The build is successful. Hence, moving this PR to **Merge in Progress**.

image


Thanks.
