### PR TITLE
magento/magento2#28568:GraphQL query returns admin option value label…

### LINKED ISSUE #28568: GraphQL query returns admin option value label within aggregations
## Issue

Product attribute option labels that are set for the Admin are also returned by the **products** GraphQL query, instead of option labels for the Default Store View.

For example, if you set the label for the "Yoga" option for the "Activity" product attribute to different values for the Admin versus the Default Store View, the store frontend will show the Default Store view label, whereas a GraphQL query will return the Admin label. 
## Steps to Replicate
1. Create a new Magento instance with sample data (the merchant did this in clean 2.3.5 and 2.4-develop, and we confirmed in 2.3-develop)
1. Note how the *Activity_ product attribute has an option called _Yoga*:
 !https://support.magento.com/attachments/token/5iLCI4P036962Ch5jX4CVzIjC/?name=Screen<ins>Shot</ins>2020-05-15<ins>at</ins>2.12.58<ins>PM.png|width=820,height=453!
1. In the admin dashboard, go to **Stores -> Attributes -> Products**.
1. Click the "activity" attribute to edit it
1. Go to **Manage Options** and set a different value for Admin and Default Store View:
 !https://support.magento.com/attachments/token/XIvqqfxSylYtm1CBDourD8VOf/?name=Screen</ins>Shot<ins>2020-05-15</ins>at<ins>2.14.25</ins>PM.png|width=764,height=596!
1. Save changes and clear cache
1. Compare the store view to a GraphQL query that shows the *Activity* label and options:
 !https://support.magento.com/attachments/token/3sBU89qfzjWyDkxkiPC0gs1lD/?name=Screen<ins>Shot</ins>2020-05-15<ins>at</ins>2.16.38<ins>PM.png|width=817,height=450!

## Expected Results

The label for Yoga should be the same in the frontend store view and the GraphQL query
## Actual Results

The store view shows the Default Store View label whereas the GraphQL query shows the Admin label
## Notes

As seen in the above and below screenshots, the merchant observes that when an Admin label is created, the associated entry in the `eav*attribute_option_value` table has a higher `value_id`, and another `store*id` is also created, even when there is just one store. They suspect that this is buggy behavior contributing to the issue.

!https://support.magento.com/attachments/token/BNNQyom0lftsiJRy7L7Zm71bT/?name=Screen</ins>Shot<ins>2020-05-06</ins>at<ins>5.08.40</ins>PM.png!
  

They also shared the following comments:
{quote}The reason is Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\AttributeOptionProvider::getOptions method retrieving all the values for the option without respecting what store it should bring this result. If you stop your debugger in Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\AttributeOptionProvider::formatResult and watch processed data, you will see that Magento processes "English Yoga" first, sets the result as "English Yoga" then iterates to next item and processes "Admin Yoga" and overrides result as "Admin Yoga". As you can see on my screenshot, eav*attribute_option_value table shows a higher value_id for store_id=0, so Admin Yoga gets processed last. If I make store_id=1 value*id 10000, it gets processed last and then I see "English Yoga" on my result. If I would create another store view and assign value for it, then that value could have a different value but this method wouldn't also respect to Store header being sent for multi-store setups, but that's a secondary issue. This even doesn't work with single store setups.
{quote}
## Example GraphQL query
```java
query myProducts ($currentPage: Int = 1 $pageSize: Int!){
  products(pageSize: $pageSize, currentPage: $currentPage, search:"Yoga"){
    aggregations{
      attribute_code
      label
      options{
        label
        value
      }
    }
  }
}

// Query vars
{
  "currentPage": 1,
  "pageSize": 4
}```

### LINKED ISSUE #28572: [GraphQl] Custom attribute aggregations should return store specific option values
#### Steps to reproduce:

1. Create multiple stores with multiple store views ( for example: english and arabic storeviews) and choose either the English or the luma default store as the store view
2. create a custom attribute that is visible in search and layered navigation. ( For test purpose, a drop down custom attribute " brand" with atleast couple options for different storeviews. 
  For example: defaultBrand, englishBrand, arabicBrand etc)
3. Add the custom attribute to attribute set 
4. Create a product and assign it to a category
5. Use the below query to query for the product and aggregrations. 
```php
{
    products(filter: {
      		category_id: {eq: {$categoryId}},
    },
      pageSize:1,
      sort:{name:DESC})
  {
    items{
      id
      sku
      name
    }
    aggregations{
      label
      attribute_code
      count
      options{
        label
        value
        count
      }
    }
  }
}
{code}
Make sure no store code is passed in through the header.
Notice that the option value returned is the "arabicBrand"
Now remove this option from the attrribute form and re-run the query, you will see that the next option value : "englishBrand" now shows up and so on

Expected:
1. Since no store code is specified, the attribute option value for the default store should be returned( if store_code is passed in, appropriate option value should be returned)

Actual:
The last eav*attribute_option_value is always returned, since store*code is not honored.
{code:php}
"aggregations" :<
{...}
{...}
    {
          "label": "brand",
          "attribute_code": "brand",
          "count": 1,
          "options": [
            {
              "label": "arabicBrand2",
              "value": "44",
              "count": 1
            }
          ]
        }
>
```

### PR DESCRIPTION
**Pull request by gallyamov**
### Description (*)

This is for #28568 and #28572 

### Related Pull Requests

N/A

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28568: Query returns admin option value label within aggregations
2. Fixes magento/magento2#28572: Custom attribute aggregations should return store specific option values

### Manual testing scenarios (*)

Check fixed issue for testing steps and expected results.

### Questions or comments

N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php [hunk 1]
```diff
@@ -42,15 +42,17 @@ public function __construct(ResourceConnection $resourceConnection)
...
      * @throws \Zend_Db_Statement_Exception
      */
-    public function getOptions(array $optionIds, array $attributeCodes = []): array
+    public function getOptions(array $optionIds, ?int $storeId, array $attributeCodes = []): array
     {
         if (!$optionIds) {
             return [];
         }
 
+        $storeId = $storeId ?: 0;
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: Let's change "0" to use \Magento\Store\Model\Store::DEFAULT_STORE_ID instead

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php [hunk 2]
```diff
@@ -42,15 +42,17 @@ public function __construct(ResourceConnection $resourceConnection)
      *
      * @param array $optionIds
      * @param array $attributeCodes
+     * @param int|null $storeId
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:45]: Please swap params so the match argument order

**Review by danielrenaud — CHANGES_REQUESTED** [review]
@gallyamov  Can you please add api-functional test cases to cover this change

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php [hunk 3]
```diff
@@ -42,15 +42,17 @@ public function __construct(ResourceConnection $resourceConnection)
...
      * @return array
      * @throws \Zend_Db_Statement_Exception
      */
-    public function getOptions(array $optionIds, array $attributeCodes = []): array
```
Comment (lbajsarowicz) [inline app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: What is the reason of adding parameter (optional) before other optional parameter

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Store ID is optional, so you should add this after already defined parameters

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php (hunk 3 above)
Comment (gallyamov) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: Correct me if I am wrong, but in our case Store ID is not optional but required. Optional is only $attributeCodes. This is why I added Store ID before it.

Comment (lbajsarowicz) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: The question mark before type means that you allow null there

Comment (gallyamov) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: Yes, but as I know it is not optional, we have to pass int or null (correct me if I am wrong).

I am passing it with a question mark because the method I am calling it from also has it in params with a question mark. 

```
/**
     * Get list of attributes with options
     *
     * @param AggregationInterface $aggregation
     * @param int|null $storeId
     * @return array
     * @throws \Zend_Db_Statement_Exception
     */
    private function getAttributeOptions(AggregationInterface $aggregation, ?int $storeId): array
    {
        $attributeOptionIds = [];
        $attributes = [];
        foreach ($this->getAttributeBuckets($aggregation) as $bucket) {
            $attributes[] = \preg_replace('~_bucket$~', '', $bucket->getName());
            $attributeOptionIds[] = \array_map(
                function (AggregationValueInterface $value) {
                    return $value->getValue();
                },
                $bucket->getValues()
            );
        }

        if (!$attributeOptionIds) {
            return [];
        }

        return $this->attributeOptionProvider->getOptions(\array_merge(...$attributeOptionIds), $storeId, $attributes);
    }
```

Comment (lbajsarowicz) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: Now I understand. Thank you for your effort to explain that!

Comment (gallyamov) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: No problem, thanks!

**Comment by gallyamov** [comment]
@magento run all tests

**Comment by gallyamov** [comment]
@magento run Functional Tests B2B

**Comment by gallyamov** [comment]
@magento run Functional Tests B2B

**Review by danielrenaud — APPROVED** [review]

**Comment by danielrenaud** [comment]
Review and QA passed

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php (hunk 3 above)
Comment (gallyamov) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:48]: @lbajsarowicz could you mark this as resolved, please? It is blocking us to merge this fix.

**Review by lbajsarowicz — APPROVED** [review]
:heavy_check_mark:

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7677](https://jira.corp.magento.com/browse/ENGCOM-7677) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@gallyamov thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by gallyamov** [comment]
@magento run all tests

**Comment by gallyamov** [comment]
@magento run all tests

**Comment by gallyamov** [comment]
@magento run Functional Tests B2B

**Comment by gallyamov** [comment]
@magento run Functional Tests EE
