### PR TITLE
magento/magento2#: Remove a redundant getMappedNums from a loop

### LINKED ISSUE #30031: [Issue] magento/magento2#: Remove a redundant getMappedNums from a loop
###### (i) This ticket is created automatically based on a verified GitHub issue.        
{panel}
***If you are starting to work on this Jira ticket, please notify issue reporter and authors of related community pull requests (if any) that you are going to work on this issue:***
  1.  *Assign [#30031](https://github.com/magento/magento2/issues/30031) issue to yourself on Magento GitHub*
  2.  *Add comment "Internal Magento team is working on this issue right now."*
{panel}
This issue is automatically created based on existing pull request: magento/magento2#27939: magento/magento2#: Remove a redundant getMappedNums from a loop ~~-------~~ ######Preconditions (*)
1. 2.4-develop

######Description (*)

Removes a redundant `getMappedNums` from a loop.

Before changes:

 !bef79987364-fc982d80-84b5-11ea-8f6d-d0047b8245fa.png|thumbnail! 

After fix:

 !aft79987388-028e0e80-84b6-11ea-8005-51fb618b8fb1.png|thumbnail! 

######Related Pull Requests

######Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

######Steps to reproduce (*)

1. ...
2. ...

######Expected result (*)
...

######Actual result (*)

######Questions or comments

######Contribution checklist (*)
 - < ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ > All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by atwixfirster**
### Description (*)

Removes a redundant `getMappedNums` from a loop.

Before changes:

After fix:

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30031: magento/magento2#: Remove a redundant getMappedNums from a loop

### CODE REVIEW

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
Hello @atwixfirster, thank you for the suggested improvement :)

Please note, due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html#automated-tests) the changes must be covered by tests. Could you please cover your fix by the appropriate unit test?

Thank you!

**Comment by atwixfirster** [comment]
> Please note, due to Magento Definition of Done the changes must be covered by tests. Could you please cover your fix by the appropriate unit test?

**done**

Thank you, @dmytro-ch

File: lib/internal/Magento/Framework/GraphQl/Test/Unit/Query/EnumLookupTest.php [hunk 1]
```diff
@@ -0,0 +1,172 @@
...
+
+    /**
+     * @var array
+     */
+    private $values = [];
+
+    /**
+     * @inheritDoc
+     */
+    protected function setUp()
```
Comment (dmytro-ch) [inline lib/internal/Magento/Framework/GraphQl/Test/Unit/Query/EnumLookupTest.php]:
```suggestion
    protected function setUp(): void
```

**Review by dmytro-ch — CHANGES_REQUESTED** [review]
@atwixfirster thank you for the updates!
Could you please just apply the following minor change in order to make sure the test is compatible with PHPUnit 8?

Thank you!

File: lib/internal/Magento/Framework/GraphQl/Test/Unit/Query/EnumLookupTest.php (hunk 1 above)
Comment (atwixfirster) [reply lib/internal/Magento/Framework/GraphQl/Test/Unit/Query/EnumLookupTest.php]: **done**

Thanks, @dmytro-ch

**Review by dmytro-ch — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @dmytro-ch, thank you for the review.
[ENGCOM-7528](https://jira.corp.magento.com/browse/ENGCOM-7528) has been created to process this Pull Request

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA passed 

"$ this-> enumDataMapper-> getMappedEnums ($ enumName);" it is possible to take out for "foreach" it will not influence logic but will reduce quantity of uses.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php [hunk 2]
```diff
@@ -43,23 +44,19 @@ public function __construct(ConfigInterface $typeConfig, DataMapperInterface $en
...
-                $mappedValues = $this->enumDataMapper->getMappedEnums($enumName);
-                if (isset($mappedValues[$enumItem->getName()]) && $mappedValues[$enumItem->getName()] == $fieldValue) {
-                    return $enumItem->getValue();
-                }
+        /** @var Enum $enumObject */
+        $enumObject = $this->typeConfig->getConfigElement($enumName);
+        $mappedValues = $this->enumDataMapper->getMappedEnums($enumName);
+
+        foreach ($enumObject->getValues() as $enumItem) {
+            if (isset($mappedValues[$enumItem->getName()]) && $mappedValues[$enumItem->getName()] == $fieldValue) {
```
Comment (sidolov) [inline lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php:63]: Please, use strict comparison.

File: lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php [hunk 3]
```diff
@@ -43,23 +44,19 @@ public function __construct(ConfigInterface $typeConfig, DataMapperInterface $en
...
+                return $enumItem->getValue();
             }
-        } else {
-            throw new \Magento\Framework\Exception\RuntimeException(
```
Comment (sidolov) [inline lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php:59]: What is the reason to remove exception here?

**Review by sidolov — CHANGES_REQUESTED** [review]

**Comment by engcom-Echo** [comment]
Hi @atwixfirster. Please consider suggestions for corrections. Thanks.

File: lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php (hunk 3 above)
Comment (atwixfirster) [reply lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php:59]: Because it will never happen.

See, [\Magento\Framework\GraphQl\ConfigInterface](https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/GraphQl/ConfigInterface.php#L25)

File: lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php (hunk 2 above)
Comment (atwixfirster) [reply lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php:63]: **done**

**Comment by atwixfirster** [comment]
@magento run all tests

**Comment by atwixfirster** [comment]
> Hi @atwixfirster. Please consider suggestions for corrections. Thanks.

@engcom-Echo , **done**

Thank you for the reminder!

**Comment by atwixfirster** [comment]
@magento run all tests

**Comment by atwixfirster** [comment]
@magento run Functional Tests B2B, Unit Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php (hunk 3 above)
Comment (gabrieldagama) [reply lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php:59]: @atwixfirster As far as I understood `Magento\Framework\GraphQl\ConfigInterface::getConfigElement` returns `ConfigElementInterface` and that is not necessary `Enum`, so the exception may happen. 

`Enum` does extends `ConfigElementInterface` but for your point to be valid the `Magento\Framework\GraphQl\ConfigInterface::getConfigElement` should explicit return the `Enum` interface.

Please let me know your thoughts.

Comment (atwixfirster) [reply lib/internal/Magento/Framework/GraphQl/Query/EnumLookup.php:59]: agreed, @gabrieldagama 

**fixed**

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-7528](https://jira.corp.magento.com/browse/ENGCOM-7528) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual Testing scenario
1. Creare a Customer on Storefront, with the checkbox **Subscribed fro Newsletter** checked 
2. Perform a grphql query
```graphql
query{
  customer{
    firstname
    lastname
    email
    is_subscribed
    created_at
    prefix
    wishlists{
      id
    }
  }
}
```
3. See the response data

AR: The response contains all the correct information about the Customer, for example
```graphql
{
  "data": {
    "customer": {
      "firstname": "Alan",
      "lastname": "Smithee",
      "email": "alan.smithee@mail.com",
      "is_subscribed": true,
      "created_at": "2020-09-25 13:34:27",
      "prefix": null,
      "wishlists": [
        {
          "id": "1"
        }
      ]
    }
  }
}
```
