### PR TITLE
Fix performance issue in cache locking mechanism

### LINKED ISSUE #22824: usleep Statments in Cache Loader causing Pathological Page Load Times
### Preconditions (*)
1. Magento 2.3.1

### Steps to reproduce (*)
1. Clear Cache
2. Load Page

### Expected result (*)
Page loads in less than 30 - 45 seconds

### Actual result (*)
Page loads in 30 - 45 seconds under unknown circumstances

If this is possible, I'd like to nominate a bit of code for removal/refactoring.  It looks like it was introduced in Magento 2.3.1

https://github.com/magento/magento2/commit/acdc770ac25c6f9d6c621fd7ba44add38bb89b05#diff-cbe30020f802e5ab5b7cf6399e91e178

And currently lives here: https://github.com/magento/magento2/blob/2.3-develop/lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php#L72

I've had reports from users/customers (who will hopefully be able to comment below) of one of my extensions ([Commerce Bug](https://store.pulsestorm.net/products/commerce-bug-3)) that they're seeing uncached Magento 2 page loads taking between 30 and 45 seconds, with the majority of this being spent [in this call to `usleep`](https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Config/App/Config/Type/System.php#L239).  The delay is inconsistent and seems dependent on resource contention in the host system (i.e. it may only show up when/if file loading is slower/faster than normal, a certain number of simultaneous requests is present, etc)

I'm reasonably certain my extension isn't to blame -- it's just that my extension makes an early call to `Magento\Developer\Helper\Data::isDevLoaded` in an event observer, and is the first thing to trigger this cache being loaded. As mentioned the problem is inconsistent, so I can't be fully certain what is or isn't to blame.  

It also seems like at least one other extension vendor has this problem.

https://twitter.com/jissereitsma/status/1126746140534165504

Beyond this being a specific problem that real users have run into -- I don't think this is the right solution for the problem, (the problem as listed in the commit comment)

> MC-6275: Conflict of simultaneous write in Redis cache

1. The pattern in use here may be OK in a language with asynchronous callbacks, but PHP's execution model is single threaded and synchronous.  This means the call to `usleep` blocks _everything in the request_.  This is what's causing the 30 - 45 seconds uncached load times for users. In most organizations I've worked for and projects I've worked on a sleep statement of any-kind in user facing PHP code would have a high bar to make it into the repo -- while MC-6275 is an important issue to solve, I'm not sure this is the right solution for this problem

2. If this code is meant to solve simultaneous Redis writes -- then it belong _in the redis cache implementation_.  Having this code up here means that every cache implementation (Redis, Filesystem, etc) is effected.  

3. The recent change to move this from a .1 second sleep to a .02 second sleep are a welcome improvement, but this seems like a work around that's destined to cause future problem for users and customers.

### PR DESCRIPTION
**Pull request by IvanChepurnyi**
### Description
This change replaces the locking strategy for resolving race condition in the configuration cache loader. 
The previous implementation was waiting for the release of the lock for all concurrent connections when the cache was flushed. It was redundant to do as the whole website visitors wait for a lock release. 

The new implementation creates a lock only for the write operation and the other connections who try to write it just return data uncached without performing any write operations. This approach removes any possibility of cyclic locking. 

### Fixed Issues 

1. Fixes magento/magento2#22824

### Manual testing scenarios
1. Create a load test that sends 20 concurrent users to your Magento without Varnish cache enabled.
2. Flush Magento cache.
3. Visit Magento backend.
4. Validate that you still can access and operate Magento store.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=22829) <br/>All committers have signed the CLA.

**Comment by IvanChepurnyi** [comment]
Static test failures related to legacy code in AbstractBlock that are unrelated to the current PR.

File: lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php [hunk 1]
```diff
@@ -93,6 +93,44 @@ public function lockedLoadData(
...
+    ) {
+        $cachedData = $dataLoader();
+
+        if ($cachedData !== false) {
+            return $cachedData;
+        }
+
+        $cachedData = $dataCollector();
+
+        if ($this->locker->lock($lockName, $this->lockTimeout / 1000)) {
```
Comment (kandy) [inline lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php]: Hi @IvanChepurnyi 
One of the goals of the previous implementation is to reduce the load on the system due to the fact that only one client generates data. 
One write to cache is atomic for most cache adapters (at least for redis) and does not  make sense to add additional locks on top of it.

Comment (IvanChepurnyi) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php]: @kandy I see, just a moment will adjust the test to make sure to exclude locking if the record is already locked.

Comment (kandy) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php]: I mean lock at all in Magento (in additional to implement in Redis server)

Comment (IvanChepurnyi) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php]: @kandy I fixed the issue with storing locked state before reading uncached data. It resolves an issue for continuous write when under high load. Redis atomic write will not save from it, as a problem is not in cache backend, but in time difference between the generation of the data on Magento side and actual write operation. When one of the processes generates data other processes still access uncached versions and schedule writes too. Good catch on the lock method forgot to add a test case for it to implement a complete solution.

**Comment by kandy** [comment]
Still, don't get why we need locks on write and how it will resolve problem? All client will try to write to cache storage and wait on lock

**Comment by IvanChepurnyi** [comment]
The latest update exactly resolves an issue, test it with the load test and put logging on a number of writes happening during the flush operation. 
Then make a load test without locking, and then compare.

**Comment by kandy** [comment]
Well, now only one customer will write data.
But let's imagine that we need to cache the code that calculates the number of lines in a 100 GB file.
How many times will this operation be performed for your code?

**Comment by IvanChepurnyi** [comment]
@kandy I would say something is wrong if you want to cache a number of lines in the 100GB file. Locking is currently used only in 2 places: config cache and block cache.

**Comment by kandy** [comment]
This is just an example. You can choose any resource-intensive operation.

**Comment by IvanChepurnyi** [comment]
Can you explain how this theoretical problem is affecting this specific pull request? 

The second option with continuous lock is still available for such cases - an original method is not removed. 

PS: Also, as probably you know, I am not a fan of optimization by caching, but for some places caching is inevitable.

For example in resource-intensive operations, if this data can be stored and invalidated by any other means than volatile cache storage, I prefer that method. Usually, resource-intensive operations can be optimized by using indexation, using a better algorithm, building memory based microservice, etc.

**Comment by kandy** [comment]
Well, let's discuss the initial implementation with your suggestion.
They are distinguished by the fact that in the first, parallel processes they sleep (and use no resources) while data is being generated.
In the proposed by you, all parallel processes generate data (makes sql queries, reads from fs, etc.)
I see no reason why the new version is better. Can you explain it for me?

PS: agree that if the cache has overheads comparable to the generation of data, we must delete the cache

**Comment by IvanChepurnyi** [comment]
@kandy The reason is simple, webshop needs to sell goods to make money for the merchant. If it saves CPU cycles to make sure only one non-cached request happen, the merchant won't be happy. 

When all the requests are waiting for a released lock, then nothing can be sold. PHP-FPM pool gets used up and NGINX receives a growing number of incoming connections it cannot resolve to send through to fpm, so it responds with 503 error. All of these just because of a single lock. 

In the second case, requests are processed, yes slower than with a case when we have cached data, but still, nothing is putting a plug on FPM pool and server responds, hoster can scale by adding additional frontend nodes - everyone is happy!

**Comment by kandy** [comment]
your sentence is correct only in case when time on generation is less than time on the check of lock present + sleep timeout.
And pay attention that in your case site will work slower because the client still need to wait until data will be regenerated

**Comment by IvanChepurnyi** [comment]
@kandy I am not talking theoretically, I am talking out of my experience. I've run into similar errors before when was working directly with merchants who received huge traffic where these issues were real. Mutex is not the answer, especially for the cache, especially in PHP.

**Comment by maksek** [comment]
@kandy @IvanChepurnyi - What do you think if we will have community architecture call and discuss the solution, instead of typing a lot of text?

**Comment by kandy** [comment]
@IvanChepurnyi I more deeply analyzed your solution and think it will resolve problems with locks on reading, especially on edge cases where cache disabled or data always return false. 
I believe that it makes sense to accept PR now, and then we will  try to find a better solution for improvement on data generation

**Comment by IvanChepurnyi** [comment]
@kandy Great news, I think it is better to work towards a solution together than argue.

I am actually was already thinking yesterday about how to improve generation time for concurrent connections, and looks like something like grace period would solve an issue. Going to work on it today so you can review it and check.

**Comment by kandy** [comment]
We try to implement "grace period" and we were got the issue with the inconsistency of data. 

For example, the old data was returned from system configuration and in FPC was stored page with prices calculated based on outdated settings. And page like this can live in FPC for days.

Please try to consider this scenario when will work "grace period" implementation

**Comment by IvanChepurnyi** [comment]
@kandy I am planning to serve stale data only during the lock. Also, probably it makes sense to make whole page un-cacheable when there is some stale data served, so FPC will not use it to store it. Do you know what is the best way to do it without putting a hard dependency on the PageCache module?

**Comment by IvanChepurnyi** [comment]
Seems like just adding a plugin for LockGuardedCacheLoader will be more than enough for PageCache module, so it will just disable cache at runtime if any stale cache data is read.

**Comment by kandy** [comment]
I think that the same problem can be with other caches (like block cache) and it's hard to predict dependencies on system configuration data.

I am afraid that this may lead to an additional discussion thread. It seems to me that this topic needs deep architectural research.

I recommend, to save your time and make the process more interactive, we could stop on the current implementation and the additional improvements move to a separate PR/issue/architecture proposal ?

What do you think about it? Will it be comfortable for you?

**Comment by IvanChepurnyi** [comment]
I prefer to finalize guarded lock implementation that allows stale content load and then we will be able to split those up. Also, I want to supply some load tests of the final solution, to add it to put everything on the table when architectural discussion happens. 

As for block_html, behavior right now I don't see any code that prevents it from happening in the current implementation too. If I set product price HTML block cache lifetime, and remove currency key from cache key, it will show me stale data when displayed currency is changed but will not flush block_html. So far it looks like approach to add data from config into your cache key is already an existing solution from stale config cache. I probably can find more examples where the problem of "cache onion" is not resolved. 
Here is btw a screenshot of such a configuration:
configuration cache flushed
result on the category page
changed line of code

**Comment by hmphu** [comment]
This PR seem optimize the site performance so much.
Hi @IvanChepurnyi  are you able to verify the failed checks below. We're really appreciated your help

**Comment by josefbehr** [comment]
@IvanChepurnyi any progress on the failing tests?

**Comment by IvanChepurnyi** [comment]
@josefbehr, I plan to fix static and semantic version tests as soon as load tests are done in reliable way, waiting for hosting party to fix their kubernetes to remove noise from dynamic page calls under high load.

**Comment by vkolesny** [comment]
Hi @IvanChepurnyi 

Could you please provide any ETA on this pull request?
Thanks.

**Comment by okorshenko** [comment]
@magento run Unit Tests build

File: dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php [hunk 2]
```diff
@@ -46,8 +46,14 @@ public function __construct(\Magento\Framework\Shell $shell)
     public function getRealMemoryUsage()
     {
         $pid = getmypid();
-
-        $result = $this->_getUnixProcessMemoryUsage($pid);
+        try {
+            // try to use the Windows command line
+            // some ports of Unix commands on Windows, such as MinGW, have limited capabilities and cannot be used
+            $result = $this->_getWinProcessMemoryUsage($pid);
```
Comment (PiotrSiejczuk) [inline dev/tests/integration/framework/Magento/TestFramework/Helper/Memory.php]: Magento 2.3 technology stack requirements (via https://devdocs.magento.com/guides/v2.3/install-gde/system-requirements-tech.html):
Operating systems (Linux x86-64) - Linux distributions, such as RedHat Enterprise Linux (RHEL), CentOS, Ubuntu, Debian, and similar. Magento is not supported on:

- Windows OS
- Mac OS

So it is kind of funny to see Windows Refs in Application Code itself... 🥇

**Comment by IvanChepurnyi** [comment]
@magento-engcom-team give me test instance with sample data

**Comment by magento-engcom-team** [comment]
Hi @IvanChepurnyi. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @IvanChepurnyi, here is your [new Magento instance](https://pr-22829.instances.magento-community.engineering).
Admin access: [https://pr-22829.instances.magento-community.engineering/admin](https://pr-22829.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`

**Comment by IvanChepurnyi** [comment]
When I replaced lock with proper locking model from configuration block cache for prices stopped working as this error started showing up in the log
image
Had to add shortener to AbstractBlock as getCacheKey can be pluginized and internal shortening won't work for lock name generation. 

Apart from that, waiting for last load test results. All static tests are passing except warnings in AbstractBlock that are unrelated to my changes.

**Comment by IvanChepurnyi** [comment]
But I can't fix semantic version tests as Magento/Config module does not have version defined in composer.json.

**Comment by josefbehr** [comment]
@IvanChepurnyi can you fix the other tests please?

**Comment by IvanChepurnyi** [comment]
After getting caching properly fixed for configuration, dozens of integration tests are failing as they are not taking into account that data in scope config can be cached. All those tests require review and putting them into isolation from a cache storage.

Also, there are some functional tests failing, probably because of lock key name length, but can't confirm without seeing error logs of the functional build, is there any way to obtain it?

**Comment by IvanChepurnyi** [comment]
So I fixed all tests except ones I can't debug. Also, the one related to consumers' run is questionable as it is not taking into account that lock can be released after some time, and putting sleep for 30 seconds is not the best way to test.

I expect functional tests fail because I changed the cache to use the configured locking model from the configuration (app/etc/env.php), and by default it is DB, so the limit of 64 characters on lock size is set. Before it was using the cache as a way to lock, that is not thread-safe. So any help in reading error logs from functional test build error logs would be great.

As for static tests, only AbstractBlock warnings left, but those warnings are impossible to fix by as they are legacy code not related to this pull request.

**Comment by IvanChepurnyi** [comment]
Here are the results of respective load testing to compare both solutions:
2.3-Develop before fix - https://snapshot.raintank.io/dashboard/snapshot/pltG6BfRU1JASG754XFIMDEXE1lsYDwb
2.3-Develop with this pull request - https://snapshot.raintank.io/dashboard/snapshot/cv5ck5Igw26eOdx2CetLB5EP64X39Bxt

And for the sake of experiment - 2.3-Develop with proper locking model for cache (DB lock) -
https://snapshot.raintank.io/dashboard/snapshot/62VG1zNnwD7OvQesNY6qAwetm8gvSZRu

In load tests every 5 minutes a configuration value is changed via command line, so only **SCOPES_CONFIG** cache is cleared. As visible from results both 2.3 Develop and 2.3 Develop with proper locking suffer from around 50% RPS drop and in TTFB distribution you can see that almost 50% from 40 VUs spend on cache generation. The load tests with PR show a very small RPS drop during cache generation and only one request over 1s per cache flush, indicating that only one request is regenerating the cache and performing the write.

**Comment by kandy** [comment]
@IvanChepurnyi It will be nice if you add CPU usage graphics as well. Thanks

**Comment by IvanChepurnyi** [comment]
@kandy Here are your CPU graphs. As you see there is no visible CPU usage difference (only minuscule idle spikes), as `usleep` statements didn't reduce actual CPU usage comparing to the solution in the pull request, but did reduce RPS. 
2.3 Develop

This Pull Request

**Comment by kandy** [comment]
I see, thanks

**Comment by IvanChepurnyi** [comment]
@kandy can you help with issues with functional tests I mentioned earlier in the ticket? And what shall we do with bad integration tests for lock that timeouts before 30s?

**Comment by kandy** [comment]
Sorry, miss your comment. 
To busy with another project now. 
Please ask for help to the community engineering team members if you need help with tests

**Comment by VladimirZaets** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php [hunk 3]
```diff
@@ -93,6 +111,62 @@ public function lockedLoadData(
...
+        callable $dataSaver,
+        callable $dataFormatter = null
+    ) {
+        $cachedData = $dataLoader();
+
+        if ($cachedData !== false) {
+            return $cachedData;
+        }
+
+        $isLocked = $this->isLocked($lockName);
```
Comment (vaimo-wilko) [inline lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php:141]: Is this check necessary or could it simply be skipped? The attempt to lock on line 152 should be enough, or? (especially given that it's non-blocking).

The problem I see is a race-condition between this line check and the line 149, where the $isLocked result is being used. In the time that passes between those two lines, the actual lock state could have changed.

Locks state is usually best derived by actually trying to acquire the lock (on success, you are guaranteed to hold the lock; on failure you have a guarantee that you are not holding the lock). In most cases where an isLocked test is used to determine the state of a lock, there is a race condition between determining the state and being able to evaluate the result of the state-check.

Comment (IvanChepurnyi) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php:141]: This was tested by at least 70 load tests. Is locked is used to check if stale data need to be loaded instead of trying to acquire a lock for writing. If this check is removed then you get more then one process acquiring a lock under high load that can result in cyclic cache writes as was shown in load test results.

Comment (IvanChepurnyi) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php:141]: Basically `isLocked` prevents race condition in this case, as you don't try to acquire the lock if during loading of cache data another process already acquired a lock and on the moment when you reach write phase lock is already released by another process so your process starts to think lock can be acquired again. See test cases for this method, they cover all mentioned use cases uncovered during highly concurrent load tests. If you remove this check - tests will fail.

Comment (vaimo-wilko) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php:141]: The lock manager should guarantee that that only 1 process can acquire a lock at any time, so all except the one that got the lock, should fail acquiring the lock, right? Those that did not get the lock (essentially meaning the same as isLocked being false) can then use that opportunity to load stale data, or?
i.e.
```php
$isLockAcquired = $this->locker->lock($lockName, 0);
if (!$isLockAcquired) {
    if ($cachedData = $dataLoader()) {
        return $cachedData;
    }
}
//... otherwise do the rest as per current code

Comment (vaimo-wilko) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php:141]: Just saw your 2nd comment above after writing my comment. I will dig a bit into the load tests to see what is being tested for.

Comment (IvanChepurnyi) [reply lib/internal/Magento/Framework/Cache/LockGuardedCacheLoader.php:141]: @vaimo-wilko that is only true when you acquire a lock on reading as well (that is a bad idea in this case). Lock manager does its job well for write lock acquiring but it does not mean that at the microseconds between cache write and lock release another process didn't start check for cache existence and without finding data in cache starts to acquire a lock, but because the lock was released it successfully does it.

**Comment by IvanChepurnyi** [comment]
@mslabko @maghamed any news on the review?

**Comment by okorshenko** [comment]
@magento run all tests

**Comment by jonathanribas** [comment]
We are also experimenting this issue in the company I'm working with (Magento Commerce), it's not acceptable as we are losing business every day.
Thanks for your help!

**Comment by ilnytskyi** [comment]
And we noticed similar issue on 2.3.1 That strange @magento did not process this PR or additional review 
https://github.com/magento/magento2/issues/22504#issuecomment-573582674

**Review by lenaorobei — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-6939](https://jira.corp.magento.com/browse/ENGCOM-6939) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@IvanChepurnyi thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by lenaorobei** [comment]
Hi @IvanChepurnyi,

Our internal team is finalizing huge improvement that impacts the root cause of the reported issue. Once it will be delivered we will review this PR once again from the performance perspective.

Assigning this PR to @vzabaznov who leads this initiative and will keep you in loop regarding further steps.

**Comment by vzabaznov** [comment]
Hi @IvanChepurnyi , thank you for contributing.

We are going to introduce changes that will affect related area this week, we believe that this might resolve some related issues and bring performance boost to cache mechanism. We will provide updated documentation very soon (1-2 weeks).

Due to internal review we agreed that trade-off that you offer might satisfy customers in some cases, but since this is huge changes we think that it should be optional and disabled by default. Could you please update you PR regarding to this.

**Comment by IvanChepurnyi** [comment]
@vzabaznov The changes you require for the pull request on which I already spend 300 hours across last 9 month does not make it possible for me to just turn down all my customers and work for another undefined number of hours to make it easily configurable and being able to enable it. I already spend more time on it than I can afford.

More over the current locking mechanism in Magento does not make any sense, Mutex alike implementation is not concurrently safe when you work in multi-server environment as there is no direct single RAM address wich holds the lock, and latency for acquiring and checking for lock is too astronomically high. So making atomic cache updates optional puts any Magento shop with at least 2 FPM nodes at risk of constant write as reproduced and proven by the load test graphs submitted in this pull requests. 

Also would be great to learn about "trade-offs" of the pull request, as I don't see them.  This is the way how majority of atomic data structures work in highly concurrent environment and is a common practice in high performance multi-threaded application development. I even made sure that potential issue of caching stale data is impossible, and you can see it yourself in the pull request that during stale cache data read parent cache gets disabled to prevent dirty cache writes, as well as auto-prefixing of new cache so there is no data override happening. As well approach when you have one cached data relying on another cached data is a bad practice in itself, and as was demonstrated serving data from block cache that relies on old configuration cache is still possible in develop branch, but impossible in current PR if block cache is added to disable cache service on stale data read.

**Comment by kingletas** [comment]
@IvanChepurnyi we are currently using this patch in our production environment. So far I am seeing great improvements when comparing it to the native implementation. We have turned your work into a set of composer patches we apply to all our environments.

**Comment by vzabaznov** [comment]
Hi @IvanChepurnyi ,
Thank you again for your contribution.
We reviewed your PR carefully and taking into account significant changes in our Magento cache mechanism, we decide to run it through public architecture proposal process - https://github.com/magento/architecture/pull/369. We are looking forward for any valuable inputs from your side and community.
The main idea of Architecture proposal is to wrap all things up, determine all A.C., discuss approach with community and deliver solid solution.

Your PR is linked as Proof Of Concept for a stale cache implementation and could be used as a base for a final implementation that will meet A.C. described in proposal.
As this ticket has a long story, lots of unrelated conversations, and PR does not meet all A.C. described in the proposal, we decided to close it. In advance, we have created an internal ticket to deliver solution for stale cache - MC-33275. We highly appreciate alternative approach for cache locking mechanism that you provided. 

I want to highlight that in the process of testing our locking mechanism, we found couple areas to improve. We believe this will resolve current performance issues of this functionality. Internal tickets MC-32426 & MC-32427 were created. Community can expect to have it in the nearest 2.4 release. Also, some fixes to resolve race conditions and lock related fixes were already delivered, community can expect to have them in 2.3.5 and 2.4.

**Comment by kingletas** [comment]
@vzabaznov this makes zero sense to me. This is currently a big issue for everyone running Magento 2.3.x, why are you delaying fixing this like that? This PR is already proven to work, met all of the requirements asked of Ivan and the goal post kept changing.

If this work is going to be the basis for your performance work, why not merge it now and built on top of it rather than just debating semantics?

In case you are wondering why I am pushing for this PR:

image

**Comment by DavidLambauer** [comment]
We have exactly the same issue. See screenshot:

image

This issue is quite hard to track as you have to profile several different request combinations in your application to find out what's going on. I agree with @kingletas that this issue affects a lot of shops.

**Comment by DavidLambauer** [comment]
We just applied the changes from this pull request as a patch to our Magento Open Source 2.3.4. We are not able to reproduce the issue anymore.  This should be at least a patch provided by the official Magento resources.

**Comment by vzabaznov** [comment]
Dear community and contributors,

We want to give more lights of this particular PR progress even it is closed.

This PR is still very important, and work has been done by @IvanChepurnyi is very valuable.

On the other hand, we not able to complete and merge this PR because of important reasons found during the review, stabilization and DoD standards requirements fixes:

- Part of the customers reported outages because of this PR and had to revert these changes. On large customer profiles this PR leads to have an excessive amount of stale cache data in Redis storage and leads to OOM issue.
-  Stale cache is not an option for some customers and this functionality should be optional because of cache freshness of blocks and config data can be critical for merchants.
- Stale cache approach in this PR is not implemented for block cache. In some cases, this PR removes efficiency improvements that were achieved by introducing lock mechanism.

Besides mentioned issues, anyone is able to install this code on their instances with testing on Staging on their own risk.

Moreover, introducing this proposal [PR](https://github.com/magento/architecture/pull/369) we targeting to complete several improvements and include into upcoming 2.4 release.

Also, we going to improve current locking mechanism and have it decomposed in several stories:

- Changing lock timeout mechanism (expecting in future commits MC-32426)
- Locks signing, in order to prevent unlock from the parallel request (expecting in future commits MC-32427)
- Introduce non-locked configuration option for blocks (expecting in future commits MC-33423)
- Timeout for data generation inside LockGuardedCache (expecting in future commits MC-31558)

Feel free to add any valuable input in a suggested proposal.

**Comment by ihor-sviziev** [comment]
@vzabaznov Wow. This PR was finally merged even after it was closed? 🤯

**Comment by slavvka** [comment]
@ihor-sviziev Yes, it was closed because the related issue was closed. Once the code synced it got merged. I was also amazed :)

**Comment by kingletas** [comment]
Thank you @slavvka. I look forward to upgrading to 2.4 now

**Comment by SilvanLaroo** [comment]
We're also facing this issue, is there a patch available for 2.3?

**Comment by IvanChepurnyi** [comment]
@SilvanLaroo you can extract a patch from this pull request but you have to separate patched files into composer patches per package as PR has diff file for a monorepo.

**Comment by riconeitzel** [comment]
did anyone face installation issues with this patch since 2.3.5? 

When we run a setup with an existing codebase and env.php on an empty database (`bin/magento set:up`) we end up with 

```

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'coverinstall.core_config_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config_data` AS `main_table`

In Mysql.php line 110:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'coverinstall.core_config_data' doesn't exist, query was: SELECT `main_table`.* FROM `core_config_data` AS `main_table`


In Mysql.php line 91:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'coverinstall.core_config_data' doesn't exist

```


1. Triggered by `\Magento\Setup\Console\Command\UpgradeCommand::execute()`
2. calling `\Magento\Setup\Model\Installer::updateModulesSequence()`
3. calling `\Magento\Setup\Model\Installer::cleanCaches()`
4. iterating over all cache types and for … `$type = full_page` …
5. calling `\Magento\PageCache\Model\Cache\Type::clean()`
6. calling `$this->eventManager->dispatch('adminhtml_cache_refresh_type');`
7. which triggers
8. `\Magento\CacheInvalidate\Observer\FlushAllCacheObserver::execute()`
9. calling `\Magento\Framework\Cache\LockGuardedCacheLoader::lockedLoadData()`
10. because it needs the config value for `default/system/full_page_cache/caching_application`
11. which results in
12. `\Magento\Framework\App\Config\ConfigSourceAggregated::get()` loading a collection from the database …
13. which does not (yet) exist
14. 💥

**Comment by ihor-sviziev** [comment]
@riconeitzel if you’ll be able to reproduce this issue on 2.4-develop branch - please report it as separate issue. Thank you!

**Comment by riconeitzel** [comment]
if it's broken on 2.3.x not?

**Comment by IvanChepurnyi** [comment]
@riconeitzel are you sure this pull request is a source of your issue? As seen in your stack trace, it is calling `\Magento\Framework\Cache\LockGuardedCacheLoader::lockedLoadData()`, which is is not called in System config class if this pull request is applied:
`\Magento\Framework\Cache\LockGuardedCacheLoader::nonBlockingLockedLoadData()`

**Comment by riconeitzel** [comment]
@IvanChepurnyi this patch isn't compatible with 2.3.5-p2, right? 😢

**Comment by serbaninno** [comment]
We encountered an issue after applying this patch on a Magento 2.3.5-p2 + Varnish 5. When a Varnish request was made to the homepage for the first time, the X-Magento-Tags were missing. We only got the tags on the next requests to the same page. The "fix" was removing this patch

**Comment by ihor-sviziev** [comment]
Hi @serbaninno,
Could you check if the issue reproducing on 2.4-develop? If so - please report separate issue for investigation & fixing that.

File: lib/internal/Magento/Framework/Lock/Backend/Database.php [hunk 4]
```diff
@@ -84,12 +84,7 @@ public function lock(string $name, int $timeout = -1): bool
          * currently we support MySQL 5.6 way only.
          */
         if ($this->currentLock) {
-            throw new AlreadyExistsException(
-                new Phrase(
-                    'Current connection is already holding lock for %1, only single lock allowed',
-                    [$this->currentLock]
-                )
-            );
+            return false;
```
Comment (boldhedgehog) [inline lib/internal/Magento/Framework/Lock/Backend/Database.php:87]: This creates infinite loop if Database is used for AbstractBlock locking. All next `$this->locker->lock()` calls return false.

If a cacheable block has a child cacheable block, the `LockGuardedCacheLoader::lockedLoadData()` call is nested, but since there is already a lock in the Database backend, and it does not depend on the lock name, lock() returns false. See 2 `lockedLoadData()` in this call stack.
```
LockGuardedCacheLoader.php:111, Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
AbstractBlock.php:1125, Amasty\Label\Block\Label->_loadCache()
AbstractBlock.php:674, Amasty\Label\Block\Label->toHtml()
...
Interceptor.php:429, Magento\Catalog\Block\Product\Image\Interceptor->toHtml()
grid.phtml:52, include()
...
Template.php:301, Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->_toHtml()
AbstractBlock.php:1100, Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->Magento\Framework\View\Element\{closure:/var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php:1094-1101}()
LockGuardedCacheLoader.php:103, Magento\Framework\Cache\LockGuardedCacheLoader->lockedLoadData()
AbstractBlock.php:1125, Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->_loadCache()
AbstractBlock.php:674, Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->toHtml()
Interceptor.php:830, Magento\CatalogWidget\Block\Product\ProductsList\Interceptor->toHtml()
Filter.php:121, Magento\Widget\Model\Template\Filter\Interceptor->generateWidget()
Interceptor.php:24, Magento\Widget\Model\Template\Filter\Interceptor->generateWidget()
Filter.php:132, Magento\Widget\Model\Template\Filter\Interceptor->widgetDirective()
Interceptor.php:37, Magento\Widget\Model\Template\Filter\Interceptor->widgetDirective()
LegacyDirective.php:42, ReflectionMethod->invokeArgs()
LegacyDirective.php:42, Magento\Framework\Filter\DirectiveProcessor\LegacyDirective->process()
Template.php:184, Magento\Widget\Model\Template\Filter\Interceptor->filter()
Filter.php:1080, Magento\Widget\Model\Template\Filter\Interceptor->filter()
Interceptor.php:58, Magento\Widget\Model\Template\Filter\Interceptor->___callParent()
Interceptor.php:138, Magento\Widget\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure:/var/www/html/vendor/magento/framework/Interception/Interceptor.php:104-151}()
Interceptor.php:153, Magento\Widget\Model\Template\Filter\Interceptor->___callPlugins()
Interceptor.php:403, Magento\Widget\Model\Template\Filter\Interceptor->filter()
Page.php:170, Magento\VersionsCms\Block\Cms\Page->_toHtml()
AbstractBlock.php:1100, Magento\VersionsCms\Block\Cms\Page->Magento\Framework\View\Element\{closure:/var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php:1094-1101}()
AbstractBlock.php:1104, Magento\VersionsCms\Block\Cms\Page->_loadCache()
AbstractBlock.php:674, Magento\VersionsCms\Block\Cms\Page->toHtml()
...
Http.php:120, Magento\Framework\App\Http\Interceptor->launch()
Interceptor.php:24, Magento\Framework\App\Http\Interceptor->launch()
Bootstrap.php:261, Magento\Framework\App\Bootstrap->run()
index.php:40, {main}()
```

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Lock/Backend/Database.php:87]: Could you please report a separate issue with all details for verifying and  than fixing that?

**Comment by niclashoyer** [comment]
We're having the same issues with very long load times on a 2.3.5-p2 shop, where sometimes page loading takes around 30 seconds and lockLoadData is just busy waiting.

We may upgrade to 2.4.x, but I'm a bit unsure if this really helps. [This merge](https://github.com/magento/magento2/commit/becbf3d4c0852182f2da11694ef02cf200224b94) merges initial parts of this PR and is tagged with 2.4.2, but if I look e.g. at the test file [in the tagged 2.4.2](https://github.com/magento/magento2/blob/2.4/lib/internal/Magento/Framework/View/Test/Unit/Element/AbstractBlockTest.php#L82) version, it does not mention the non blocking variant and even the history does not mention fixes in these files.

Can someone clear this up? @vzabaznov @ihor-sviziev is this really merged in 2.4.x and fixed? Or was the non blocking lock method removed again somehow?

**Comment by IvanChepurnyi** [comment]
> Can someone clear this up? is this really merged in 2.4.x and fixed? Or was the non blocking lock method removed again somehow?

Probably it was merged and then removed, as they implemented something own; I don't think that rewritten solution is efficient and really solves the concurrency issue, but I already gave up on the original pull request. Maybe someday I will make it as an installable module that can implement a non-blocking cache, but that one is far from even the start of development as I am too busy right now.

**Comment by kandy** [comment]
@nicholasscottfish  see https://devdocs.magento.com/guides/v2.4/config-guide/redis/redis-pg-cache.html#parallel-generation

**Comment by dooblem** [comment]
Hello all.
This is still causing issues on the last magento versions (currently 2.4.5 on my customer).

On our project the config cache is huge because we have a lot of websites. Each time the config cache was flushed (config save in backoffice, or during imports or any other reason), I was seing on PHP process generating the configuration. And the other processes waiting for the lock release.
But once the config was generated and the lock released, all the processes where piling up, consuming a lot of memory and eventually causing oomkills.

After enabling l2 stale cache on the config as suggested by @kandy :point_up:  , it worked like magic, and our problems went away !

Important thing : we only enabled the l2 cache for the config cache. Because I heard from colleagues that enabling it for all the caches slows overall response times, and also as it basically duplicates the cache on all local fronts, I did not want to overload my web front memories.

Here is an extract from env.php:
```
    'cache' => [
        'frontend' => [
            'default' => [
                'id_prefix' => '954_',
                'backend' => 'Magento\\Framework\\Cache\\Backend\\Redis',
                'backend_options' => [
                    'server' => 'myredishost',
                    'database' => '0',
                    'port' => '6379',
                    'password' => 'xxxx',
                    'compress_data' => '1'
                ]
            ],
            'l2_stale_cache_enabled' => [
                'id_prefix' => '954_',
                'backend' => '\\Magento\\Framework\\Cache\\Backend\\RemoteSynchronizedCache',
                'backend_options' => [
                    'remote_backend' => '\\Magento\\Framework\\Cache\\Backend\\Redis',
                    'remote_backend_options' => [
                        'persistent' => 0,
                        'server' => 'myredishost',
                        'database' => '0',
                        'port' => '6379',
                        'password' => 'xxxx',
                        'compress_data' => '1'
                    ],
                    'local_backend' => 'Cm_Cache_Backend_File',
                    'local_backend_options' => [
                        'cache_dir' => '/dev/shm/'
                    ],
                    'use_stale_cache' => true
                ],
                'frontend_options' => [
                    'write_control' => false
                ]
            ]
        ],
        'type' => [
            'default' => [
                'frontend' => 'default'
            ],
            'config' => [
                'frontend' => 'l2_stale_cache_enabled'
            ]
        ]
    ],
```

In order to test it. On a single web front on dev or preprod:

watch the php fpm processes piling up in one terminal window:
```
while true; do date; top -bn1 | grep -vF ' 0.0 '  | grep fpm; sleep 0.5; done
```

on another window, run a `bin/magento cache:clean config`

then quickly run 4 curls in background, and observe the response time, the locking and how processes pile up.
```
time curl -is -o/dev/null -H 'Host:www.example.com' -H X-forwarded-proto:https  http://localhost/agen/checkout/cart &
```

before the config fix: 1 process taking 30s, 3 processes taking 15s
after the config fix: 1 process taking 30s, 3 processes taking less than 1s (those using stale cache)
