### PR TITLE
magento/magento2#35706 Remote storage issue #35706

### LINKED ISSUE #35706: Remote storage issue
### Preconditions and environment

- Magento version 2.4.4
- PHP8.1.7 (allow_url_fopen = ON)

### Steps to reproduce

1. Configure remote storage (S3, minio, ...)
2. Upload an image in Stores > Configuration > Sales > Sales > Logo for PDF Print-outs (200x50)
3. Place an order and invoice it
4. Try to print invoice from backend

### Expected result

PDF is generated

### Actual result

```
Cannot create image resource. File not found."
#1 Zend_Pdf_Image::imageWithPath() called at [vendor\/magento\/module-sales\/Model\/Order\/Pdf\/AbstractPdf.php:282]
```

### Additional information

I doubled checked : the file does exists. And the absolute url passed to `Zend_Pdf_Image::imageWithPath` is correct and gives a 200 when launched in browser. However, `php -r "var_dump(is_file('http://s3.domain/path/file.jpg'));"` does return false. (I don't understand why, it should work according to PHP doc)

`Zend_Pdf_Resource_ImageFactory` should be deprecated and replaced by a class which uses `Magento\Framework\Filesystem\DriverInterface::isFile()` instead of prohibited `is_file`. Maybe some other classes needs to be fixed as well.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by monteshot**
### Description (*)

- Created new ImageFactory class that is refactored service class Zend_Pdf_Resource_ImageFactory for using external S3 Storage images in invoice

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35706

### Manual testing scenarios (*)

1. Install any S3 compatible storage (locally)
1.1 
```
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
```
1.2 Start MinIO. For example: 
`MINIO_ROOT_USER=monteshot MINIO_ROOT_PASSWORD=monteshot ./minio server /home/monteshot/minio/magento --console-address ":9901" --address ":9801"`

1.3 Create your bucket
image
1.4 Connect Application to S3 Storage
`bin/magento setup:config:set \
    --remote-storage-driver="aws-s3" \
    --remote-storage-endpoint="http://127.0.0.1:9801" \
    --remote-storage-region="ua-shostka-1" \
    --remote-storage-bucket="magecd" \
    --remote-storage-key="magecd12" \
    --remote-storage-secret="magecd12" \
    --no-interaction`
1.5 Run Sync
`bin/magento remote-storage:sync
`
2. Go to configuration and add image as discribed in Task 
image
https://github.com/magento/magento2/issues/35706#issue-1288848631
3.
Check the PDF invoice w/o exception
image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run all tests

**Comment by monteshot** [comment]
@magento run WebAPI Tests

**Comment by monteshot** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/File/Pdf/Image.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+ * See COPYING.txt for license details.
+ */
+declare(strict_types=1);
+
+namespace Magento\Framework\File\Pdf;
+
+use Magento\Framework\File\Pdf\ImageResource\ImageFactory;
+use Zend_Pdf_Image;
+
+class Image extends Zend_Pdf_Image
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/File/Pdf/Image.php]: Can we use the `Zend_Pdf_Image` class in the constructor instead of extending it and replicating all methods of the `Zend_Pdf_Image` here in this class?

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @monteshot,

Thanks for the contribution!

Please have a look at my review comment.

Thanks

File: lib/internal/Magento/Framework/File/Pdf/Image.php (hunk 1 above)
Comment (monteshot) [reply lib/internal/Magento/Framework/File/Pdf/Image.php]: I think yes. I can completely remove Zend_Pdf_Image from  lib/internal/Magento/Framework/File/Pdf/Image.php

@engcom-Hotel I'll remove that extending

**Comment by monteshot** [comment]
@engcom-Hotel Hello. Do I need to handle smth with this ?
image

**Comment by engcom-Hotel** [comment]
Hello @monteshot,

Yes, we need to take care of all build failures in order to proceed further. Can you please take care of this test failure?

Thanks

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**
- Minio should be installed and configured.

**Manual testing scenario:**

1. Upload an image in `Stores > Configuration > Sales > Sales > Logo for PDF Print-outs`.
2. Place an order and invoice it
3. Try to print invoice from backend
4. Verify the PDF is generated or not.

**Before:** :heavy_multiplication_x: Getting error while clicking on the "Print" button and PDF invoice was not getting generated.
Screenshot 2023-05-26 at 5 26 10 PM
Screenshot 2023-05-26 at 5 28 36 PM


**After:** :heavy_check_mark:  Now PDF is getting generated.
Screenshot 2023-05-26 at 5 31 29 PM
