### PR TITLE
Fix issue when can't remove layout update after add during new widget creation

### LINKED ISSUE #29936: item layout updates can't remove after add when create new widget
### Preconditions (*)

1. Magento 2.4-develop
2.

### Steps to reproduce (*)

1. Go to admin
2. Content > Widgets
3. Add new widget
4. In section "Layout Updates" Add Layout Update
5. Try to click on icon basket to remove item

### Expected result (*)

1. Item should be remove
2.

### Actual result (*)

1. Item cannot remove
2. Only first item could be removed
Screen Shot 2020-09-08 at 12 58 03

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by saphaljha**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#29936

### Manual testing scenarios (*)

1. Manually tested by adding and removing the elements in new widget as well as in old widget

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php [hunk 1]
```diff
@@ -111,16 +111,21 @@ public function renderEventListenerAsTag(
...
             }
-            var {$elementName} = document.querySelector("{$elementSelector}");
-            if ({$elementName}) {
-                {$elementName}.{$eventName} = function (event) {
-                    var targetElement = {$elementName};
-                    if (event && event.target) {
-                        targetElement = event.target;
+            var {$elementName}Array = document.querySelectorAll("{$elementSelector}");
+
+            {$elementName}Array.forEach(function(element){
```
Comment (rogyar) [inline lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php]: We need to make sure that `document.querySelectorAll` will return an empty node list if there's no `{$elementSelector}` on the page. @saphaljha have you tested this scenario?

**Comment by rogyar** [comment]
Hi @saphaljha. Thank you for your collaboration. Please, check my comment above. Also, I would ask you to cover your fix with an MFTF test. The MFTF test should basically emulate all the steps from "steps to reproduce" and check if it is possible to remove items other than the first one. 

Thank you!

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php (hunk 1 above)
Comment (saphaljha) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php]: @rogyar , Thank you for suggestion, I have updated the code for validate empty nodeList. Also, covered MFTF.

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run Integration Tests

File: app/code/Magento/Widget/Test/Mftf/ActionGroup/AdminCreateAndDeleteMultipleLayoutWidgetActionGroup.xml [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+<!--
+ /**
+  * Copyright © Magento, Inc. All rights reserved.
+  * See COPYING.txt for license details.
+  */
+-->
+<actionGroups
+    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+              xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/actionGroupSchema.xsd">
+    <actionGroup name="AdminCreateAndDeleteMultipleLayoutWidgetActionGroup">
```
Comment (rogyar) [inline app/code/Magento/Widget/Test/Mftf/ActionGroup/AdminCreateAndDeleteMultipleLayoutWidgetActionGroup.xml]: Hi @saphaljha. Great work! Thank you for the coverage. 
We may improve this action group by splitting it into more atomic action groups. The main reason of it is the following. The purpose of the current action group is very specific and it might not be reused in many cases. In the meantime, we could split this huge action group into pieces like action group that creates widget, action group that deletes widget, action group that asserts number elements. In this case the smaller action groups will be much more reusable. Also, it's a good idea to double-check if we could reuse the [existing](https://github.com/magento/magento2/blob/16e6fdace4f1e297a43fe396b4d8f45432e82702/app/code/Magento/Widget/Test/Mftf/ActionGroup/AdminCreateWidgetActionGroup.xml#L11) action groups for adding/removing widgets. 

Hope it makes sense. 

Thank you!

**Comment by sivaschenko** [comment]
@saphaljha thanks for the contribution! Would you be able to complete the changes to this PR?

**Comment by sivaschenko** [comment]
Priority increased to P1 as this PR is a dependency for P1 pull request https://github.com/magento/magento2/pull/30008

**Comment by saphaljha** [comment]
Hello @sivaschenko , Yes, I am working on it and I'll push the changes ASAP.

**Comment by sivaschenko** [comment]
Thank you @saphaljha ! 👍 Waiting for the update.

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php [hunk 3]
```diff
@@ -111,16 +111,21 @@ public function renderEventListenerAsTag(
...
             }
-            var {$elementName} = document.querySelector("{$elementSelector}");
-            if ({$elementName}) {
-                {$elementName}.{$eventName} = function (event) {
-                    var targetElement = {$elementName};
-                    if (event && event.target) {
-                        targetElement = event.target;
+            var {$elementName}Array = document.querySelectorAll("{$elementSelector}");
+            if({$elementName}Array.lenght !== 'undefined'){
+                {$elementName}Array.forEach(function(element){
```
Comment (mrtuvn) [inline lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php]: Should change Array.lenght  to Array.length in line 115
@rogyar @saphaljha

**Review by mrtuvn — CHANGES_REQUESTED** [review]

**Comment by mrtuvn** [comment]
@saphaljha  can you update your PR with resolve conflict xml file ?
This PR at my perspective quite important should have priority P0

**Comment by mrtuvn** [comment]
If author not work on this PR anymore i can create new PR for this

**Comment by saphaljha** [comment]
Hello @mrtuvn ,

I'll push updated code soon, Sorry for delay and thank you for your patience :)

File: app/code/Magento/Widget/Test/Mftf/ActionGroup/AdminCreateAndDeleteMultipleLayoutWidgetActionGroup.xml (hunk 2 above)
Comment (saphaljha) [reply app/code/Magento/Widget/Test/Mftf/ActionGroup/AdminCreateAndDeleteMultipleLayoutWidgetActionGroup.xml]: Thank you @rogyar ,
I have updated it MFTF as per your suggestions, Please check and let me know if there is anything.

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php (hunk 3 above)
Comment (saphaljha) [reply lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php]: Hello @mrtuvn ,
Thank you, I have updated it.

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php [hunk 4]
```diff
@@ -111,16 +111,21 @@ public function renderEventListenerAsTag(
...
-            if ({$elementName}) {
-                {$elementName}.{$eventName} = function (event) {
-                    var targetElement = {$elementName};
-                    if (event && event.target) {
-                        targetElement = event.target;
+            var {$elementName}Array = document.querySelectorAll("{$elementSelector}");
+            if({$elementName}Array.length !== 'undefined'){
+                {$elementName}Array.forEach(function(element){
+                    if (element) {
+                        element.{$eventName} = function (event) {
```
Comment (mrtuvn) [inline lib/internal/Magento/Framework/View/Helper/SecureHtmlRenderer.php:118]: should add event.preventDefault(); here

**Review by mrtuvn — CHANGES_REQUESTED** [review]

**Comment by mrtuvn** [comment]
@krzksz @DrewML @omiroshnichenko what do you guys think about this PR change ?

**Comment by mrtuvn** [comment]
@saphaljha can you solve conflicting files ?
Also update info manual test scenarios for QA Team can check and test correctly

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by rogyar** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@saphaljha could you please look through at failed tests?
Thank you.

**Comment by saphaljha** [comment]
Hello @rogyar  ,

Can you please guide me to find out why these test are failing?

Thanks

**Comment by rogyar** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
@saphaljha looks like test falling was caused by changes in this PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@saphaljha looks like test falling was caused by changes in this PR.

**Comment by rogyar** [comment]
Hi @saphaljha. I agree with @engcom-Charlie. It looks like our change to the rendering process breaks other parts of the system. You may figure out why it happens by an attempt to repeat steps from any broken test. Then, you may have a clue why it happens. 

Thank you

**Comment by saphaljha** [comment]
Hello  @rogyar ,

Thank you for response, I'll check and update it.

**Comment by engcom-Charlie** [comment]
Hi @saphaljha, do you have any updates?
Thank you.

**Comment by saphaljha** [comment]
Hello @engcom-Charlie, 
I am still working on to find out the cause of functional test failing.

**Comment by saphaljha** [comment]
@magento run Functional Tests CE

**Comment by saphaljha** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @saphaljha, could you please look at failed test failures?
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @saphaljha, do you have any updates?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests, Unit Tests, Static Tests, Semantic Version Checker, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B,  Magento Health Index, Integration Tests, Database Compare

**Comment by saphaljha** [comment]
thank you @engcom-Charlie for your help!!

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8514](https://jira.corp.magento.com/browse/ENGCOM-8514) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. From Admin, go to _Content - Widget_ click **Add Widget**
2. Select, for example, 
- **Type** - _CMS Page Link_ 
- **Design Theme** - _Magento Luma_
Click **Continue**
3. Using **Add Layout Update** button, Add 3 Layout Updates, for example
4. Try to remove the added Layouts using the **Remove Layout Update** (basket)

**BEFORE** applying changes provided in this PR, only the first Layout Update could be removed
Peek 2020-12-01 15-23

**AFTER** switching to the PR, all the Layout Updates can be removed
Peek 2020-12-01 15-43_after

The Widget can be saved successfully 
widget_save

**Comment by mrtuvn** [comment]
Can you check issue in checkbox config stores ? Go to stores / configuration try to check on checkbox in each field

**Comment by saphaljha** [comment]
@magento Hello
