### PR TITLE
Fix #17933 - Bank Transfer Payment Instructions switch back to default

### LINKED ISSUE #17933: Bank Transer Payment Instuctions switch back to default
### Summary (*)
The default Magento 2 Bank Transfer Payment has an issue when you have multiple stores.
If you create an order and select Bank Transfer Payment as payment method. Then go look at the just created order the title doesn't reflect the one we have setup in the store configuration. (Says: Bank Transfer Payment instead of "Überweisung (per Bank)"

The instructions are fine. But if you click Ship, Invoice the instuction gets reset to the default value that is in the system->configuration.

### Preconditions (*)

1. Magento 2.2.x, 2.3.x, 2.4-develop
2. PHP 7.1, 7.2

### Steps to reproduce (*)

1. Create second store & store view.
2. Enable Bank Transfer Payment.
image

3. Change title & instructions of Bank Transfer Payment for second store.
image

4. Create a new order with Bank Transfer Payment from second store.
5. Go to the Order information in the backend. 

6. Check email

7. Then click invoice or ship.
8. Check order info again in the backend & email

### Expected result (*)

1. Payment information should be collected from the store the orde was placed in.

### Actual result (*)

1. Payment information show the default information from Store configuration. (in backend and in emails for Invoice/Shipment):
**Admin:**

**Email:**

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

This is fix for #17933 
The issue was caused because observer modified here did override `additional_information` column in `sales_order_payment` table with data for incorrect store view.
Also, exactly the same issue occurred for Cash On Delivery and very similar, just for other fields (`payable_to` and `mailing_address`), for Check Money Order - both also are resolved with this fix.

### Fixed Issues (if relevant)

1. magento/magento2#17933: Bank Transer Payment Instuctions switch back to default

### Manual testing scenarios (*)

Please check fixed issue for testing scenario

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/OfflinePayments/Observer/BeforeOrderPaymentSaveObserver.php [hunk 1]
```diff
@@ -33,15 +35,19 @@ public function execute(\Magento\Framework\Event\Observer $observer)
...
+                    'instructions',
+                    $payment->getOrder()->getStoreId()
+                )
             );
         } elseif ($payment->getMethod() === Checkmo::PAYMENT_METHOD_CHECKMO_CODE) {
             $methodInstance = $payment->getMethodInstance();
-            if (!empty($methodInstance->getPayableTo())) {
-                $payment->setAdditionalInformation('payable_to', $methodInstance->getPayableTo());
+            $storeId = $payment->getOrder()->getStoreId();
+            if (!empty($payableTo = $methodInstance->getConfigData('payable_to', $storeId))) {
```
Comment (aleron75) [inline app/code/Magento/OfflinePayments/Observer/BeforeOrderPaymentSaveObserver.php]: I also used to implement assignments within comparisons but one day someone pointed me out that it can be a bit misleading: is the `=` a real assignment or a bug, that is, a missing`==`? Reading the code without too much attention (it happens) it may seem a bug, someone could be tempted to correct it causing indeed a bug :) 

At that point, I stopped using it and switched back to assigning the variable and doing the comparison in two different statements.

Would you consider doing that change, thus joining my group of old, wise, and defensive programmers like me? :-)

Comment (Bartlomiejsz) [reply app/code/Magento/OfflinePayments/Observer/BeforeOrderPaymentSaveObserver.php]: @aleron75 I'm not sure if I will get used to do it, but I can definitely try, changed it :)

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@aleron75 I rebased changes on develop since those files were also modified there, ready for review again 😉

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6953](https://jira.corp.magento.com/browse/ENGCOM-6953) has been created to process this Pull Request

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by engcom-Delta** [comment]
HI @aleron75 could you approve this PR once again to move it into `Ready for Testing` status?

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-6953](https://jira.corp.magento.com/browse/ENGCOM-6953) has been created to process this Pull Request
