### PR TITLE
Load translations for area, fixes #8412

### LINKED ISSUE #8412: Translations do not work when run via cron
### Preconditions

1. Magento 2.1.3 (and earlier)

### Steps to reproduce

1. Install a language pack, for example `composer require imaginaerum/magento2-language-fr-fr`
2. Create a new Store View "French"
3. Select fr_FR locale for this Store View
4. Change Stores > Configuration > Sales > Sales Email > General Settings > Asynchronous sending to Enabled
5. Place a new order from the French store
6. Ensure Magento's cronjob `bin/magento cron:run` is executing and that the order confirmation email has been sent

### Expected result

1. Order Confirmation Email is sent in French

### Actual result

1. 
screen shot 2017-02-04 at 11 30 48

Please note that the locale for email is correctly emulated as can be seen by formatting of the currency amounts.

### PR DESCRIPTION
**Pull request by ghost**
See #8412 for steps to reproduce.

Result
screen shot 2017-02-04 at 12 00 13

### CODE REVIEW

**Comment by fooman** [comment]
Please note I added `@SuppressWarnings(PHPMD.CouplingBetweenObjects)` as the AreaList pushed it across the boundary of 12. Fixing it like removing the ObjectManager would be a backwards incompatible change - just let me know if you would prefer that instead.

**Comment by fooman** [comment]
Travis failure is a timeout on Integration Tests1 on 5.6 - the same suite passes on 7.0

**Comment by reindert-vetter** [comment]
@fooman This is the solution! I tested it and it works for me. I hope this solution is implemented quickly!

File: lib/internal/Magento/Framework/App/Cron.php [hunk 1]
```diff
@@ -77,6 +87,19 @@ public function launch()
...
 
     /**
+     * @deprecated
+     *
+     * @return \Magento\Framework\App\AreaList
+     */
+    private function getAreaList()
+    {
+        if ($this->areaList === null) {
+            $this->areaList = $this->objectManager->get(\Magento\Framework\App\AreaList::class);
```
Comment (ishakhsuvarov) [inline lib/internal/Magento/Framework/App/Cron.php]: Please use injection via optional parameter in constructor instead of deprecated method, for example:
```php
public function __construct(
    \Magento\Framework\App\AreaList $arealist = null
) {
    $this->arealist = $arealist ?: $this->objectManager->get(\Magento\Framework\App\AreaList::class);
}
```

**Review by ishakhsuvarov — CHANGES_REQUESTED** [review]

**Comment by fooman** [comment]
@ishakhsuvarov requested changes are implemented

**Comment by heldchen** [comment]
#6511 could possibly also be fixed by this PR, have not had chance to test tho, sorry.

**Comment by fooman** [comment]
@heldchen indeed looks like my issue report is a double up to the one you linked to, the suggested solutions are also very similar to the one I proposed

**Comment by okorshenko** [comment]
@fooman Thank you for your contribution. Your pull request merged to develop branch

**Comment by lucscu** [comment]
For my custom cronjob it not works, i have to set correct locale store before load Area
`$storeManager = $this->objectManager->get('Magento\Store\Model\StoreManagerInterface');`
`$storeManager->setCurrentStore(1);`
`$this->areaList->getArea(Area::AREA_CRONTAB)->load(Area::PART_TRANSLATE);`
Otherwise i continue to see en_US string.
Please help me to dynamize it with a parameter in cronjob.

**Comment by fooman** [comment]
@LucScu thanks for your feedback. Just to confirm what do you mean by custom cron and have you applied the changes from this pull request?

**Comment by lucscu** [comment]
@fooman
Yes, i applied full patch (except to CronTest.php).
I developed a custom module that executes this crontab 
```
<job name="feed_google_create" instance="Lucasart\Feed\Model\Google" method="execute">
    <schedule>0 1 * * *</schedule>
</job>
```

Even if i set manually italian store in execute() method, translations are yet in en_US

    public function execute() {

        $text = 'Inizio creazione feed';
        $this->logger->debug($text);

        // set italian store
        $this->storeManager->setCurrentStore(1);        

        // $title = __("Login Options");
        // $this->logger->debug($title);
        // $title = __("men's shirt");
        // $this->logger->debug($title);

        // retrieve products for feed
        $items = $this->getProducts();   

        // write feed
        $this->writeToFile($items);

        $text = 'Fine creazione feed';
        $this->logger->debug($text);

    }    

To have translation in it_IT i have to set italian store in `Magento\Framework\App\Cron` before load Area (like explained in previous post).

**Comment by fooman** [comment]
Have you tried wrapping your code into an emulated store similar to how Magento does [when sending email](https://github.com/magento/magento2/blob/develop/app/code/Magento/Email/Model/AbstractTemplate.php#L510)?

**Comment by lucscu** [comment]
i try to investigate how email translations was managed and i found emulation logic, but i wasn't able to understand how apply it to my code.
Where do you think have i to add it?

**Comment by lucscu** [comment]
please follow up

**Comment by fooman** [comment]
@LucScu please understand that this is not a forum to obtain support for custom code. You might have better luck on StackExchange. Generally you need to add
`\Magento\Store\Model\App\Emulation` to the constructor of your class and then run `$this->appEmulation->startEnvironmentEmulation($storeId, 'frontend', true);` with your store id.

Best of luck.

**Comment by lucscu** [comment]
@fooman sure i understand, but my custom code is related to your PR, i think it is helpful for all magento community.
So, i can confirm that it works also with custom crontab code.

**Comment by Cornel99** [comment]
@fooman 
I have followed your solution and works great under developer (with cache disabled). But when I enable the cache in Magento 2.1.9 it turns emails back to English language. All cache cleared again from Magento backend even from Command line but the emails remain the same in English.

Did I missed something?

**Comment by Cornel99** [comment]
After some research I found that only "Translation Cache" if is disabled emails works correctly.
How can I clear this cache in order to work correctly?
