### PR TITLE
Module catalog, Attribute Repository code validation regex

### LINKED ISSUE #29017: Product Attribute Repository do not respect attribute_code max length
### Preconditions (*)
on magento 2.4 a product attribute code with attribute_code of value A_12345678_9123_4567_890a_BCDEF123456 is saved through the admin ui but not from the repository. Here Magento\Eav\Model\Entity\Attribute::ATTRIBUTE_CODE_MAX_LENGTH should be respected.

### Steps to reproduce (*)

Here is a code example:
```
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$ar = $objectManager->create('Magento\Catalog\Api\ProductAttributeRepositoryInterface');
$attf = $objectManager->create('\Magento\Catalog\Api\Data\ProductAttributeInterfaceFactory');
$a = $attf->create();
$a->setData(['attribute_code' => 'A_12345678_9123_4567_890a_BCDEF123456','frontend_label' => 'a test', 'frontend_input' => 'text']);
$ar->save($a);
    Magento/Framework/Exception/InputException with message 'Invalid value of "A_12345678_9123_4567_890a_BCDEF123456" provided for the attribute_code field.'


```
### Expected result (*)

1. attribute is saved

### Actual result (*)

1. validator exception 

### Addiotional information
Issue is reproducible via WebApi
#29017Main

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by drc0**
Regex modified to accept the A-Z range and check for Magento\Eav\Model\Entity\Attribute::ATTRIBUTE_CODE_MAX_LENGTH instead of the old hardcoded value (30)

### Description (*)

In the magento module catalog, in the method validateCode for product attribute attribute_code field, there were a check for the attribute length that do not respect the Magento\Eav\Model\Entity\Attribute::ATTRIBUTE_CODE_MAX_LENGTH constant, also I think it should accept chars of the A-Z range.

fixes https://github.com/magento/magento2/issues/29017

### CODE REVIEW

**Comment by drc0** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Model/Product/Attribute/Repository.php [hunk 1]
```diff
@@ -218,8 +219,8 @@ public function getCustomAttributesMetadata($dataObjectClassName = null)
      */
     protected function generateCode($label)
     {
-        $code = substr(preg_replace('/[^a-z_0-9]/', '_', $this->filterManager->translitUrl($label)), 0, 30);
-        $validatorAttrCode = new \Zend_Validate_Regex(['pattern' => '/^[a-z][a-z_0-9]{0,29}[a-z0-9]$/']);
+        $code = substr(preg_replace('/[^a-zA-Z_0-9]/', '_', $this->filterManager->translitUrl($label)), 0, Attribute::ATTRIBUTE_CODE_MAX_LENGTH);
+        $validatorAttrCode = new \Zend_Validate_Regex(['pattern' => '/^[a-zA-Z][a-zA-Z_0-9]{0,29}[a-zA-Z0-9]$/']);
```
Comment (gabrieldagama) [inline app/code/Magento/Catalog/Model/Product/Attribute/Repository.php]: I believe we should accept just lower case characters here, as described on the docs:

https://docs.magento.com/user-guide/stores/attributes-product.html
```
Attribute Code | (Required) A unique identifier for internal use. The Attribute Code must begin with a letter, but can include a combination of lowercase letters (a-z) and numbers (0-9). The code must be less than thirty characters in length and cannot include any special characters or spaces, although an underscore (_) can be used to indicate a space.
```

File: app/code/Magento/Catalog/Model/Product/Attribute/Repository.php [hunk 2]
```diff
@@ -235,7 +236,7 @@ protected function generateCode($label)
      */
     protected function validateCode($code)
     {
-        $validatorAttrCode = new \Zend_Validate_Regex(['pattern' => '/^[a-z][a-z_0-9]{0,30}$/']);
+        $validatorAttrCode = new \Zend_Validate_Regex(['pattern' => '/^[a-zA-Z][a-zA-Z_0-9]{0,' . Attribute::ATTRIBUTE_CODE_MAX_LENGTH . '}$/']);
```
Comment (gabrieldagama) [inline app/code/Magento/Catalog/Model/Product/Attribute/Repository.php]: I believe we should accept just lower case characters here, as described on the docs:

https://docs.magento.com/user-guide/stores/attributes-product.html
```
Attribute Code | (Required) A unique identifier for internal use. The Attribute Code must begin with a letter, but can include a combination of lowercase letters (a-z) and numbers (0-9). The code must be less than thirty characters in length and cannot include any special characters or spaces, although an underscore (_) can be used to indicate a space.
```

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @drc0, thanks for the pull request, it looks good!

Please follow below some comments on it, can you fix the static tests failures?

We also need to cover the changes with some tests, we could create some integration tests to validate the changes proposed on this PR, let me know if you are able to create these tests!

Thank you!

File: app/code/Magento/Catalog/Model/Product/Attribute/Repository.php (hunk 1 above)
Comment (drc0) [reply app/code/Magento/Catalog/Model/Product/Attribute/Repository.php]: you are right with this lowercase rule cited in the docs, I missed it previously sorry, is there any technical reason to do so btw?  In my particular case the attribute code is created from a management system that stores attribute references as GUID and those have upper case letters and changing the rule here could avoid some headaches.

Comment (drc0) [reply app/code/Magento/Catalog/Model/Product/Attribute/Repository.php]: done

File: app/code/Magento/Catalog/Model/Product/Attribute/Repository.php (hunk 2 above)
Comment (drc0) [reply app/code/Magento/Catalog/Model/Product/Attribute/Repository.php]: done

File: app/code/Magento/Catalog/Model/Product/Attribute/Repository.php (hunk 1 above)
Comment (gabrieldagama) [reply app/code/Magento/Catalog/Model/Product/Attribute/Repository.php]: To be honest, I'm not 100% sure what is the reason for that, but I guess it is to simplify the field itself since it is used as the key for the attribute. Thanks for reverting it.

**Comment by drc0** [comment]
> Hi @drc0, thanks for the pull request, it looks good!
> 
> Please follow below some comments on it, can you fix the static tests failures?
> 
> We also need to cover the changes with some tests, we could create some integration tests to validate the changes proposed on this PR, let me know if you are able to create these tests!
> 
> Thank you!

For now I'm unable to create a test for the proposed changes. should app/code/Magento/Catalog/Test/Unit/Model/Product/Attribute/RepositoryTest.php be modified to check for this validation on the length of the attribute code adding a new class method for the test case?

**Comment by gabrieldagama** [comment]
Hi @drc0, yeah I guess we can update that unit test to validate the proposed changes. Thanks!

**Comment by engcom-Charlie** [comment]
Hi @drc0 can you please look at https://github.com/magento/magento2/pull/29015#issuecomment-680022873 ?
Thank you.

**Comment by engcom-Charlie** [comment]
Hi @drc0, I'll take care of test coverage.

**Comment by drc0** [comment]
> Hi @drc0, I'll take care of test coverage.

awesome, thank you.

**Comment by engcom-Charlie** [comment]
Hi @drc0, can you please take a look at https://github.com/magento/magento2/issues/29017#issuecomment-685358905?
Thank you.

**Comment by engcom-Charlie** [comment]
I close PR because the issue isn't produced anymore.

**Comment by drc0** [comment]
@engcom-Charlie sorry but the issue had two parts, the admin one (not reproducible) and the check in the validator, the check in the validator bug is still present https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/Product/Attribute/Repository.php#L221 so this PR is still valid.

**Comment by engcom-Charlie** [comment]
@drc0, can you please cover this scenario with some type of test?
Thank you.

**Review by sidolov — CHANGES_REQUESTED** [review]
@drc0 please, cover changes with WebApi test

**Comment by engcom-Charlie** [comment]
@drc0 I'll take care of test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8229](https://jira.corp.magento.com/browse/ENGCOM-8229) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by magento-engcom-team** [comment]
@drc0 thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Result:**
**Before:**
:x: Attribute with code length more than 30 but less than 60 symbols cannot be created
#29017Main


**After:**
:heavy_check_mark: Attribute with code length more than 30 but less than 60 symbols is successfully created
#29017PRapi

**Comment by engcom-Delta** [comment]
**Note:** Functional Tests B2B are failed
