### PR TITLE
magento/magento2#39604: Fixed error with script (404)

### LINKED ISSUE #39604: Error: Script error for "Magento_Catalog/js/validate-product" for admin content pagebuilder with products load
### Preconditions and environment

- Magento version
- 2.4.x
- Anything else that would help a developer reproduce the bug

### Steps to reproduce

Example:
 - Open admin menu -> content -> pages -> edit or create new page -> edit with pagebuilder -> add row/column -> add products from sidebar and choose your conditions
- save
- reopen with pagebuilder
- open console you will observe Error: Script error for "Magento_Catalog/js/validate-product" error 

### Expected result

there should be no errors

### Actual result

Error: Script error for "Magento_Catalog/js/validate-product" error 

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [x] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by BeggiNN**
- Fixed issue for error: Script error for `catalogAddToCart`

### Description (*)

Magento version
2.4.x
Anything else that would help a developer reproduce the bug
### Fixed Issues (if relevant)

1. Fixes magento/magento2#39604

### Manual testing scenarios (*)

1. Open admin menu -> content -> pages -> edit or create new page -> edit with pagebuilder -> add row/column -> add products 2. from sidebar and choose your conditions
2. save
3. reopen with pagebuilder
4.  console does not have errors

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run all tests

**Comment by BeggiNN** [comment]
@magento run Unit Tests, WebAPI Tests, Integration Tests, Functional Tests EE, Functional Tests B2B, Database Compare

**Comment by BeggiNN** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by BeggiNN** [comment]
@magento run Functional Tests B2B

**Comment by BeggiNN** [comment]
@magento run Functional Tests B2B

**Comment by BeggiNN** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Catalog/view/base/requirejs-config.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2025 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/view/base/requirejs-config.js]:
```suggestion
 * Copyright 2019 Adobe
```

File: app/code/Magento/Catalog/view/base/web/js/validate-product.js [hunk 2]
```diff
@@ -1,6 +1,6 @@
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2025 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/view/base/web/js/validate-product.js]:
```suggestion
 * Copyright 2016 Adobe
```

File: app/code/Magento/Catalog/view/frontend/requirejs-config.js [hunk 3]
```diff
@@ -1,6 +1,6 @@
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2025 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Catalog/view/frontend/requirejs-config.js]:
```suggestion
 * Copyright 2011 Adobe
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @BeggiNN,

The changes looks good to me. Below some changes suggested, please do the needful.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @BeggiNN,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Open admin menu -> content -> pages -> edit or create new page -> edit with pagebuilder -> add row/column -> add products 2. from sidebar and choose your conditions
- save
- reopen with pagebuilder
- console does not have errors



**Before:** :heavy_multiplication_x: 

Screenshot 2025-04-04 at 1 38 12 pm




**After:** :heavy_check_mark: 

Screenshot 2025-04-04 at 1 53 17 pm



Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Charlie** [comment]
The Functional B2B and EE failures are not consistent in recent 2 builds on the same code. They are neither part of this PR nor failing because of the PR changes, seems to be flaky. Hence moving the PR into Merge in Progress.

**Functional B2B-  Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39677/8778cd9bad79c26511778a0ea529e9a3/Functional/allure-report-b2b/index.html#categories

image

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39677/75df97a5305df3ed3748756f3539b0c9/Functional/allure-report-b2b/index.html#categories/49d6afa5fbaf9ef33d930e05cf5266ef/8f70c09ac184b3dd/

image


**Functional EE-  Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39677/760da5ea39d05da5806a9e2e62b854fa/Functional/allure-report-ee/index.html#categories

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39677/651b37e79161132890565b8b5d5afb00/Functional/allure-report-ee/index.html#categories/b9d706eb4ea8df3f419d1b4b8a8baa79/5858ce4c238c03d6/

image
