### PR TITLE
Issue 36351: fix bin/magento setup:upgrade error when use composer install --no-dev

### LINKED ISSUE #36351: bin/magento setup:upgrade error when use composer install --no-dev
### Preconditions and environment

- 2.4-develop with sample data.

### Steps to reproduce

1.  Disable Sample data using command : `bin/magento module:disable Magento_SampleData`
2. Run `composer install --no-dev`
3. Run `bin/magento indexer:reindex`
4. Check the debug log.

### Expected result

No error

### Actual result

Error: There is an error in /var/www/html/magento2/lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php at line: 143
Call to undefined function Magento\Framework\Api\SearchCriteria\CollectionProcessor\array_first()

### Additional information

- Function array_first is declared in composer dev package weew/helpers-array.
- In production environment, I think no need install composer dev packages, so the code should not depend on these packages.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#36351

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Functional Tests CE, Integration Tests

**Review by ishakhsuvarov — APPROVED** [review]

File: lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php [hunk 1]
```diff
@@ -140,7 +140,7 @@ private function checkFromTo(&$fields, &$conditions)
         $_fields = array_unique($fields);
         $_conditions = [];
         foreach ($conditions as $condition) {
-            $_conditions[array_key_first($condition)] = array_first($condition);
+            $_conditions[array_key_first($condition)] = empty($condition) ? null : reset($condition);
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php:143]: I don't see any changes, because `array_first` contain same logic.

```
function array_first(array $array, $default = null) {
        if (empty($array)) {
            return $default;
        }

        return reset($array);
    }
```
Please correct me if I'm not right.

Comment (Den4ik) [reply lib/internal/Magento/Framework/Api/SearchCriteria/CollectionProcessor/FilterProcessor.php:143]: Sorry, my fail. I have checked issue and see the problem

**Review by Den4ik — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**
1. Disable Sample data using command : bin/magento module:disable Magento_SampleData
2. Run composer install --no-dev
3. Run bin/magento indexer:reindex
4. Check the debug log.

**Before:** :heavy_multiplication_x: Getting error while running indexer command.
**After running indexer:**
Screenshot 2022-10-28 at 12 23 55 PM

**Logs:**
Screenshot 2022-10-28 at 11 50 46 AM

**After:** :heavy_check_mark:  No error.
Screenshot 2022-10-28 at 12 52 43 PM

**Additionally tested:**
1. Placed an order from the frontend.
2. Invoiced/ship/credit memo from admin.

Since it's not affecting functionality no additional manual test case is required.
