### PR TITLE
Customer Attributes Options with option group fixed

### LINKED ISSUE #30422: [Issue] Customer Attributes Options with option group fixed
This issue is automatically created based on existing pull request: magento/magento2#30421: Customer Attributes Options with option group fixed

---------

\Magento\Customer\Ui\Component\Listing\AttributeRepository::getOptionArray method fails to return correct options for attribute with option groupsi.e store_id (created_in).

### Description (*)
Magento 2.4-develop

\Magento\Customer\Ui\Component\Listing\AttributeRepository::getOptionArray method fails to return correct options for attribute with option groupsi.e store_id (created_in).
It fails for all attributes with option group in "options" index. 
### Fixed Issues (if relevant)

**Preconditions:**

(for example)

**_Main Website:_**
1. _Main Website Store:_
- Default Store View ;
- Second Store View;
- Third Store View;

2. _Second Store:_

- English Store View;
- French Store View;

Screenshot from 2020-11-18 10-24-10

**Manual testing scenario:**

1. Use the \Magento\Customer\Ui\Component\Listing\AttributeRepository in any form or grid and render select options with option groups;
2. $this->attributeRepository->getMetadataByCode($code)

**Actual Result:** :heavy_multiplication_x:  the method doesn't return correct options

```graphql
$test = {array} [12]
 attribute_code = "store_id"
 frontend_input = "select"
 frontend_label = "Create In"
 backend_type = "static"
 options = {array} [3]
  0 = {array} [3]
   label = "Main Website"
   value = null
   __disableTmpl = true
  1 = {array} [3]
   label = "    Main Website Store"
   value = null
   __disableTmpl = true
  2 = {array} [3]
   label = "    Second Store"
   value = null
   __disableTmpl = true
 is_used_in_grid = false
 is_visible_in_grid = false
 is_filterable_in_grid = false
 is_searchable_in_grid = false
 validation_rules = {array} [0]
 required = true
 entity_type_code = "customer"
```

**Expected Result:** :heavy_check_mark:  the method should return correct options

```graphql
$test = {array} [12]
 attribute_code = "store_id"
 frontend_input = "select"
 frontend_label = "Create In"
 backend_type = "static"
 options = {array} [3]
  0 = {array} [3]
   label = "Main Website"
   value = {array} [0]
   __disableTmpl = true
  1 = {array} [3]
   label = "    Main Website Store"
   value = {array} [3]
    0 = {array} [3]
     label = "    Default Store View"
     value = "1"
     __disableTmpl = true
    1 = {array} [3]
     label = "    Second Store View"
     value = "2"
     __disableTmpl = true
    2 = {array} [3]
     label = "    Third Store View"
     value = "3"
     __disableTmpl = true
   __disableTmpl = true
  2 = {array} [3]
   label = "    Second Store"
   value = {array} [2]
    0 = {array} [3]
     label = "    English Store View"
     value = "4"
     __disableTmpl = true
    1 = {array} [3]
     label = "    French Store View"
     value = "5"
     __disableTmpl = true
   __disableTmpl = true
 is_used_in_grid = false
 is_visible_in_grid = false
 is_filterable_in_grid = false
 is_searchable_in_grid = false
 validation_rules = {array} [0]
 required = true
 entity_type_code = "customer"
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by nitishcs6**
\Magento\Customer\Ui\Component\Listing\AttributeRepository::getOptionArray method fails to return correct options for attribute with option groupsi.e store_id (Create In).

### Description (*)

\Magento\Customer\Ui\Component\Listing\AttributeRepository::getOptionArray method fails to return correct options for attribute with option groupsi.e store_id (Create In).
It fails for all attributes with option group in "options" index. 
### Manual testing scenarios (*)

1. Use the \Magento\Customer\Ui\Component\Listing\AttributeRepository in any form or grid and render select options with option groups.
2.
$this->attributeRepository->getMetadataByCode($code)
 **Before**
```json
{
  "attribute_code": "store_id",
  "frontend_input": "select",
  "frontend_label": "Create In",
  "backend_type": "static",
  "options": [
    {
      "label": "MyStore Saudi",
      "value": null,
      "__disableTmpl": true
    },
    {
      "label": "MyStore Saudi Store",
      "value": null,
      "__disableTmpl": true
    },
    {
      "label": "MyStore Kuwait",
      "value": null,
      "__disableTmpl": true
    },
    {
      "label": "MyStore Kuwait Store",
      "value": null,
      "__disableTmpl": true
    }
  ],
  "is_used_in_grid": false,
  "is_visible_in_grid": false,
  "is_filterable_in_grid": false,
  "is_searchable_in_grid": false,
  "validation_rules": [],
  "required": true,
  "entity_type_code": "customer"
}
```

**After**
```json
{
  "attribute_code": "store_id",
  "frontend_input": "select",
  "frontend_label": "Create In",
  "backend_type": "static",
  "options": [
    {
      "label": "MyStore Saudi",
      "value": null,
      "__disableTmpl": true
    },
    {
      "label": "    MyStore Saudi Store",
      "value": [
        {
          "label": "Saudi English",
          "value": "2",
          "__disableTmpl": true
        },
        {
          "label": "Saudi Arabic",
          "value": "3",
          "__disableTmpl": true
        }
      ],
      "__disableTmpl": true
    },
    {
      "label": "MyStore Kuwait",
      "value": null,
      "__disableTmpl": true
    },
    {
      "label": "MyStore Kuwait Store",
      "value": [
        {
          "label": "Kuwait English",
          "value": "4",
          "__disableTmpl": true
        },
        {
          "label": "Kuwait Arabic",
          "value": "5",
          "__disableTmpl": true
        }
      ],
      "__disableTmpl": true
    }
  ],
  "is_used_in_grid": false,
  "is_visible_in_grid": false,
  "is_filterable_in_grid": false,
  "is_searchable_in_grid": false,
  "validation_rules": [],
  "required": true,
  "entity_type_code": "customer"
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#30422: Customer Attributes Options with option group fixed

### CODE REVIEW

**Comment by nitishcs6** [comment]
@magento create issue

**Comment by nitishcs6** [comment]
#dmcdindia2020

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @nitishcs6.Thank you for your contribution. According to the [definition of done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all changes should be covered by autotests. Could I ask you to cover your changes with an integration test, please?

Thank you!

**Comment by rogyar** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi @nitishcs6 could you please cover your changes by integration tests?
Thank you.

**Comment by milindsingh** [comment]
> Hi @nitishcs6 could you please cover your changes by integration tests?
> Thank you.

@engcom-Charlie can you suggest any sample integration test case for this pr?

**Comment by engcom-Charlie** [comment]
@nitishcs6 unfortunately there is no integration test for `\Magento\Customer\Ui\Component\Listing\AttributeRepository` but feel free to create it.
You can assert the output of `\Magento\Customer\Ui\Component\Listing\AttributeRepository::getMetadataByCode('store_id')`. Let me know if you will have any question.

**Comment by engcom-Charlie** [comment]
@nitishcs6 @milindsingh unfortunately there is no integration test for `\Magento\Customer\Ui\Component\Listing\AttributeRepository` but feel free to create it.
You can assert the output of `\Magento\Customer\Ui\Component\Listing\AttributeRepository::getMetadataByCode('store_id')`. 
Let me know if you will have any question.

**Comment by engcom-Charlie** [comment]
Hi, @nitishcs6 please cover your changes by integration tests. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by milindsingh** [comment]
@engcom-Charlie I will add the test cases this weekend.

**Comment by engcom-Charlie** [comment]
@nitishcs6 @milindsingh do you have any updates about test coverage?
Thank you.

**Comment by engcom-Charlie** [comment]
@nitishcs6 @milindsingh please cover your changes by integration test. Otherwise, we can't proceed with your PR.
Thank you.

**Comment by engcom-Charlie** [comment]
@nitishcs6 @milindsingh I will take care of automated tests.
Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Customer/Ui/Component/Listing/AttributeRepository.php [hunk 1]
```diff
@@ -143,9 +143,13 @@ protected function getOptionArray(array $options)
     {
         /** @var \Magento\Customer\Api\Data\OptionInterface $option */
         foreach ($options as &$option) {
+            $value = $option->getValue();
+            if ($option->getOptions()) {
```
Comment (gabrieldagama) [inline app/code/Magento/Customer/Ui/Component/Listing/AttributeRepository.php]: Since the `OptionsInterface` does not have strict return types on its functions, the `getOptions` may not return an array, which may lead to a problem since the `getOptionArray` does require an array.

```suggestion
            if (is_array($option->getOptions())) {
```

What do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @nitishcs6, thanks for contributing! Nice catch.

Can you have a look at my comment below? Thanks.

**Comment by engcom-Charlie** [comment]
Hi @nitishcs6, could you please look at https://github.com/magento/magento2/pull/30421#discussion_r516613756?
Thank you.

**Comment by engcom-Charlie** [comment]
@nitishcs6 I will continue with your PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8465](https://jira.corp.magento.com/browse/ENGCOM-8465) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

(for example)

**_Main Website:_**
1. _Main Website Store:_
- Default Store View ;
- Second Store View;
- Third Store View;

2. _Second Store:_

- English Store View;
- French Store View;

**Manual testing scenario:**

1. Use the \Magento\Customer\Ui\Component\Listing\AttributeRepository in any form or grid and render select options with option groups;
2. $this->attributeRepository->getMetadataByCode($code)

**Before:** :heavy_multiplication_x:  the method doesn't return correct options

```graphql
$test = {array} [12]
 attribute_code = "store_id"
 frontend_input = "select"
 frontend_label = "Create In"
 backend_type = "static"
 options = {array} [3]
  0 = {array} [3]
   label = "Main Website"
   value = null
   __disableTmpl = true
  1 = {array} [3]
   label = "    Main Website Store"
   value = null
   __disableTmpl = true
  2 = {array} [3]
   label = "    Second Store"
   value = null
   __disableTmpl = true
 is_used_in_grid = false
 is_visible_in_grid = false
 is_filterable_in_grid = false
 is_searchable_in_grid = false
 validation_rules = {array} [0]
 required = true
 entity_type_code = "customer"
```

**After:** :heavy_check_mark:  the method returns correct options

```graphql
$test = {array} [12]
 attribute_code = "store_id"
 frontend_input = "select"
 frontend_label = "Create In"
 backend_type = "static"
 options = {array} [3]
  0 = {array} [3]
   label = "Main Website"
   value = {array} [0]
   __disableTmpl = true
  1 = {array} [3]
   label = "    Main Website Store"
   value = {array} [3]
    0 = {array} [3]
     label = "    Default Store View"
     value = "1"
     __disableTmpl = true
    1 = {array} [3]
     label = "    Second Store View"
     value = "2"
     __disableTmpl = true
    2 = {array} [3]
     label = "    Third Store View"
     value = "3"
     __disableTmpl = true
   __disableTmpl = true
  2 = {array} [3]
   label = "    Second Store"
   value = {array} [2]
    0 = {array} [3]
     label = "    English Store View"
     value = "4"
     __disableTmpl = true
    1 = {array} [3]
     label = "    French Store View"
     value = "5"
     __disableTmpl = true
   __disableTmpl = true
 is_used_in_grid = false
 is_visible_in_grid = false
 is_filterable_in_grid = false
 is_searchable_in_grid = false
 validation_rules = {array} [0]
 required = true
 entity_type_code = "customer"
```
