### PR TITLE
Static properties serialization fix.

### LINKED ISSUE #28319: [Issue] Static properties serialization fix.
This issue is automatically created based on existing pull request: magento/magento2#26175: Static properties serialization fix.

---------

### Preconditions(*)

When test cleanup is disabled, Magento\TestFramework\Workaround\Cleanup\StaticProperties is caching static variables before the integration test starts, and restoring them after the test run is finished (if some instance of \Magento\TestFramework\TestCase\AbstractController has run). 
Serialization and unserialization of static properties are provided by  Magento\Framework\Serialize\Serializer\Json class, which wraps json_encode and json_decode functions. 
Some of static properties are objects (e. g. \Magento\Framework\Autoload\AutoloaderRegistry::$autoloader). After encoding and decoding these properties through JSON we are getting arrays instead of objects. So we are facing issues on consecutive runs of integration tests.

### Fixed Issues (if relevant)

1. None

### Steps to reproduce(*)

1. Disable the application cleanup in integration tests phpunit.xml:
`<const name="TESTS_CLEANUP" value="disabled"/>`
2. Run some controller integration test (e. g. \Magento\Newsletter\Controller\ManageTest)
3. Run some another controller integration test (e. g. AdminNotification test bundle)

**Actual Result:**

**Expected Result:**
tests should run successfully
### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### LINKED ISSUE #29313: [Issue] Static properties serialization fix.
This issue is automatically created based on existing pull request: magento/magento2#26175: Static properties serialization fix.

---------

### Description (*)

When test cleanup is disabled, Magento\TestFramework\Workaround\Cleanup\StaticProperties is caching static variables before the integration test starts, and restoring them after the test run is finished (if some instance of \Magento\TestFramework\TestCase\AbstractController has run). 
Serialization and unserialization of static properties are provided by  Magento\Framework\Serialize\Serializer\Json class, which wraps json_encode and json_decode functions. 
Some of static properties are objects (e. g. \Magento\Framework\Autoload\AutoloaderRegistry::$autoloader). After encoding and decoding these properties through JSON we are getting arrays instead of objects. So we are facing issues on consecutive runs of integration tests.

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. Disable the application cleanup in integration tests phpunit.xml:
`<const name="TESTS_CLEANUP" value="disabled"/>`
2. Run some controller integration test (e. g. \Magento\Newsletter\Controller\ManageTest)
3. Run some another controller integration test (e. g. AdminNotification test bundle)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28319: Static properties serialization fix.

### PR DESCRIPTION
**Pull request by p-bystritsky**
### Description (*)

When test cleanup is disabled, Magento\TestFramework\Workaround\Cleanup\StaticProperties is caching static variables before the integration test starts, and restoring them after the test run is finished (if some instance of \Magento\TestFramework\TestCase\AbstractController has run). 
Serialization and unserialization of static properties are provided by  Magento\Framework\Serialize\Serializer\Json class, which wraps json_encode and json_decode functions. 
Some of static properties are objects (e. g. \Magento\Framework\Autoload\AutoloaderRegistry::$autoloader). After encoding and decoding these properties through JSON we are getting arrays instead of objects. So we are facing issues on consecutive runs of integration tests.

### Fixed Issues (if relevant)

1. None

### Manual testing scenarios (*)

1. Disable the application cleanup in integration tests phpunit.xml:
`<const name="TESTS_CLEANUP" value="disabled"/>`
2. Run some controller integration test (e. g. \Magento\Newsletter\Controller\ManageTest)
3. Run some another controller integration test (e. g. AdminNotification test bundle)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#28319: Static properties serialization fix.

### Resolved issues:
1. [x] resolves magento/magento2#29313: Static properties serialization fix.

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @p-bystritsky,
Could you review test failures and fix your solution?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7142](https://jira.corp.magento.com/browse/ENGCOM-7142) has been created to process this Pull Request

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@engcom-Alfa I see this PR in testing more than 1 month. I think you just missed it

**Comment by engcom-Echo** [comment]
:heavy_check_mark: QA Passed

:heavy_multiplication_x: **Before:**
image

:heavy_check_mark:  **After:**

image

**Comment by slavvka** [comment]
@magento create issue

**Review by sdzhepa — APPROVED** [review]

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — CHANGES_REQUESTED** [review]
@p-bystritsky Please fix the solution as WebAPI and Integration tests are failing with fatal error:
```
13:49:50 PHP Fatal error:  Uncaught Exception: Serialization of 'Closure' is not allowed in /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Serialize/Serializer.php:28
13:49:50 Stack trace:
13:49:50 #0 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Serialize/Serializer.php(28): serialize()
13:49:50 #1 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Workaround/Cleanup/StaticProperties.php(223): Magento\TestFramework\Serialize\Serializer->serialize()
13:49:50 #2 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Workaround/Cleanup/StaticProperties.php(231): Magento\TestFramework\Workaround\Cleanup\StaticProperties::backupStaticVariables()
13:49:50 #3 [internal function]: Magento\TestFramework\Workaround\Cleanup\StaticProperties->startTestSuite()
13:49:50 #4 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array()
13:49:50 #5 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(105): Magento\TestFramework\EventManager->fireEvent()
13:49:50 #6 /v in /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Serialize/Serializer.php on line 28
```

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

File: dev/tests/integration/framework/Magento/TestFramework/Workaround/Cleanup/StaticProperties.php [hunk 1]
```diff
@@ -187,7 +187,8 @@ public static function backupStaticVariables()
             function ($classFile) {
                 return StaticProperties::_isClassInCleanableFolders($classFile)
                     // phpcs:ignore Magento2.Functions.DiscouragedFunction
-                    && strpos(file_get_contents($classFile), ' static ')  > 0;
+                    && strpos(file_get_contents($classFile), ' static ')  > 0
+                    && strpos($classFile, 'TestFramework')  === -1;
```
Comment (ihor-sviziev) [inline dev/tests/integration/framework/Magento/TestFramework/Workaround/Cleanup/StaticProperties.php]: It would be better to check strpos before getting file content

Comment (engcom-Foxtrot) [reply dev/tests/integration/framework/Magento/TestFramework/Workaround/Cleanup/StaticProperties.php]: @ihor-sviziev updated

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7142](https://jira.corp.magento.com/browse/ENGCOM-7142) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento run WebAPI tests

**Comment by slavvka** [comment]
@magento run WebAPI Tests

**Comment by slavvka** [comment]
@magento run Integration Tests

**Review by slavvka — CHANGES_REQUESTED** [review]
@p-bystritsky Integration tests are failing again. Could you please fix them?

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@slavvka integration test are not failing on CI. Where we can see that they were failing?

**Review by slavvka — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @slavvka, thank you for the review.
[ENGCOM-7142](https://jira.corp.magento.com/browse/ENGCOM-7142) has been created to process this Pull Request

**Comment by slavvka** [comment]
@magento run all tests
