### PR TITLE
Internal server error on Category graphQl query for redirect code field

### LINKED ISSUE #36675: Internal server error on Category graphql query
### Preconditions and environment

- Magento version : 2.4.4
- PHP version : 8.1

### Steps to reproduce

Run Category List Query 

```
{
	categories(filters: {}, pageSize: 1, currentPage: 2) {
		total_count
		items {
			available_sort_by
			uid
			level
			name
			path
			children_count
			canonical_url
			children_count
			custom_layout_update_file
			default_sort_by
			description
			display_mode
			filter_price_range
			image
			include_in_menu
			is_anchor
			landing_page
			level
			meta_description
			meta_keywords
			meta_title
			name
			path
			path_in_store
			position
			product_count
			redirect_code
			relative_url
			type
			uid
			url_key
			url_path
			url_suffix
			children {
				uid
				level
				name
				path
				children_count
				children {
					uid
					level
					name
					path
				}
			}
		}
		page_info {
			current_page
			page_size
			total_pages
		}
	}
}
```

### Expected result

Query should return Categories data

### Actual result

Internal server error.

 report.ERROR: Cannot return null for non-nullable field "CategoryTree.redirect_code".
 
 
image

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Vasudev-22**
### Description (*)

1. redirect_code filed will not accept as null ,because in graphQl the field was set a mandatory with integer value.
2. If redirect_code is null in category graphQl, then it will return as Zero.
redirect_code Int!
Contains 0 when there is no redirect error. A value of 301 indicates the URL of the requested resource has been changed permanently, while a value of 302 indicates a temporary redirect.

### Related Pull Requests
Fixes for https://github.com/magento/magento2/issues/36675

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36675

### Manual testing scenarios (*)

category_graphql

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php [hunk 1]
```diff
@@ -70,6 +70,10 @@ private function sortTree(array &$tree): array
             } elseif (isset($node['children_count'])) {
                 $node['children_count'] = 0;
             }
+            // redirect_code null will not return , so it will be 0 when there is no redirect error.
+            if (empty($node['redirect_code'])) {
```
Comment (swnsma) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ExtractDataFromCategoryTree.php]:
```suggestion
            if (!isset($node['redirect_code'])) {
```

**Review by swnsma — CHANGES_REQUESTED** [review]
Hi @Vasudev-22,

Thank you for your contribution!
Please check my suggestion.

According to [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/), changes should be covered by auto-tests.
I may suggest changes in \Magento\GraphQl\CatalogUrlRewrite\RouteTest.

**Comment by Vasudev-22** [comment]
@magento run all tests

**Comment by swnsma** [comment]
Hi @Vasudev-22,

Thank you for your changes!

According to [definition of done](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/), changes should be covered by auto-tests.
I may suggest changes in \Magento\GraphQl\CatalogUrlRewrite\RouteTest.

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@Vasudev-22 

Thank you for your contribution!

The functional test failures in B2B and CE are different from the last two run.
B2B : run1
Screenshot 2023-01-25 at 8 54 16 PM
run2
Screenshot 2023-01-25 at 5 47 28 PM

CE : run1
Screenshot 2023-01-25 at 9 20 21 PM

run2
Screenshot 2023-01-25 at 9 14 41 PM

Hence, moving this PR to Ready for Testing

Thanks.

**Review by swnsma — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests CE

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop` with Sample data.

**Manual testing scenario:**
-> _Run below graphQL query and check the response:_
```
{
	categories(filters: {}, pageSize: 1, currentPage: 2) {
		total_count
		items {
			available_sort_by
			uid
			level
			name
			path
			children_count
			canonical_url
			children_count
			custom_layout_update_file
			default_sort_by
			description
			display_mode
			filter_price_range
			image
			include_in_menu
			is_anchor
			landing_page
			level
			meta_description
			meta_keywords
			meta_title
			name
			path
			path_in_store
			position
			product_count
			redirect_code
			relative_url
			type
			uid
			url_key
			url_path
			url_suffix
			children {
				uid
				level
				name
				path
				children_count
				children {
					uid
					level
					name
					path
				}
			}
		}
		page_info {
			current_page
			page_size
			total_pages
		}
	}
}
```
**Before:** :heavy_multiplication_x: Getting internal server error in the response.
Screenshot 2023-01-27 at 12 23 10 PM


**After:** :heavy_check_mark:  Now it is working fine.
Screenshot 2023-01-27 at 12 40 37 PM

**Additionally tested:**

- Tested without sample data.
- Removed products and verified the error coming or not in the response.
- Removed category and verified the error coming or not in the response.

No need of additional test cases is required as part of regression.

As per [above comment ](https://github.com/magento/magento2/pull/36693#issuecomment-1403836193)failed testcases not related to the PR. Hence, moving this PR to Merge in progress.

**Comment by engcom-Charlie** [comment]
It seems bot moved this PR from Merge in Progress to Ready for Testing hence moving it back.
