### PR TITLE
Avoids endless loop of indexers being marked as invalid

### LINKED ISSUE #29297: Refactor Magento_Indexer module so that the "indexer_reindex_all_invalid" cronjob and "bin/magento indexer:reindex" command use the same code
### Summary (*)
This was discovered while working on https://github.com/magento/magento2/pull/29196

The cronjob `indexer_reindex_all_invalid` ([Magento\Indexer\Model\Processor::reindexAllInvalid](https://github.com/magento/magento2/blob/3008324fc7e90b01fd2b25be789aacaf950f6cde/app/code/Magento/Indexer/Model/Processor.php#L61)) and manually executing `bin/magento indexer:reindex {all-invalid-indexers}` ([Magento\Indexer\Console\Command\IndexerReindexCommand::execute](https://github.com/magento/magento2/blob/3008324fc7e90b01fd2b25be789aacaf950f6cde/app/code/Magento/Indexer/Console/Command/IndexerReindexCommand.php#L75)) should execute the exact same thing.
Currently both those entry points have separate codebases for executing their logic which can lead to subtle inconsistencies if only one of both codebases are touched.

We should try to refactor the code into one shared codebase for both entry points.

### Examples

It looks like this (probably) accidentally happened at least once in [MAGETWO-51540](https://github.com/magento/magento2/commit/e8f2b0c385db4036d8953721046af7aabedd6b27)

### Proposed solution
@rogyar [proposed](https://github.com/magento/magento2/pull/29196#issuecomment-663983945) the following solution:
> Additionally, I would create a separate service i.e. `validateSharedIndex` and put the logic of `getIndexerIdsBySharedIndex` and `validateSharedIndex` there. So we can reuse the newly created class for the indexer processor and `IndexerReindexCommand`.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users with no workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #29478: [Issue] Avoids endless loop of indexers being marked as invalid
This issue is automatically created based on existing pull request: magento/magento2#29196: Avoids endless loop of indexers being marked as invalid

Magento 2.4-develop
---------
### Description (*)

This was discovered on a particular project where we noticed that the indexers `catalogrule_rule` and `catalog_category_product` are constantly being marked as `Reindex required`.

The cronjob `indexer_reindex_all_invalid` is running and is supposed to fix this, but that doesn't happen.
If however, I stop the cronjobs, and manually execute `bin/magento indexer:reindex catalogrule_rule catalog_category_product` we see a different behavior and only `catalog_category_product` is then marked as `Reindex required.`. If I then execute either `bin/magento indexer:reindex catalog_category_product` or let the cronjob `indexer_reindex_all_invalid` take over again, everything is getting back to a stable state and all indexers are marked as `Ready`.

So this means that the execution of the `indexer_reindex_all_invalid` cronjob and `bin/magento indexer:reindex {all-invalid-indexers}` are behaving differently which isn't correct in my opinion.

We've seen this happening with Magento OS 2.3.5, and I was able to reproduce it on the `2.4-develop` branch (using commit f39a2e0c5ab)

I currently only have a way to reproduce it by using the database of this particular project and we also need a particular module from Amasty installed as well (the Improved Layered Navigation module version 2.14.3).
But in my opinion it's not a bug in the Amasty module but a problem in core Magento since we see a difference in behavior in how invalid indexers are reindexed if you do it manually or if the cronjob executes it.

After searching around a bit I noticed a particular commit which was only applied to the manual reindexing command: [MAGETWO-51540: Linked indexers catalog_category_product and catalog_product_cateogry do not set valid status after shell run](https://github.com/magento/magento2/commit/e8f2b0c385db4036d8953721046af7aabedd6b27).

So I now introduced these same changes to the code which is used by the `indexer_reindex_all_invalid` cronjob and after testing these changes on both our project (on Magento 2.3.5) as on my test on the `2.4-develop` branch, it looks like it fixes the issue.

In my opinion, this is a pretty important bugfix, because this bug causes the server of this particular project to have a high CPU load because of the constant reindexing which happens with every cron run which is not necessary.

In my opinion, we should also try to refactor the code so both `bin/magento indexer:reindex` as the cronjob `indexer_reindex_all_invalid` should use the same code so we can avoid in the future where one fix is applied to one part and forgotten about in the other part.
I've currently chosen not to refactor this so it's easier to review these changes, and maybe somebody can follow up in a later PR to refactor this?

### Fixed Issues (if relevant)
1. None that I could find

### Manual testing scenarios (*)
1. Have magerun2 available to manually execute cronjobs (https://files.magerun.net/)
2. Setup a clean Magento
3. Install Amasty's Improved Layered Navigation module version 2.14.3
4. Use a specific database from our project (sorry, I can't publicly share this database)
5. Run `bin/magento setup:upgrade`
6. Run `bin/magento indexer:reindex` so all indexers are marked as valid
6. Invalidate the two specific 2 indexers: `bin/magento indexer:reset catalogrule_rule catalog_category_product`
7. Look at the indexers statuses: `bin/magento indexer:status` (the two indexers should be marked as invalid)
8. Run `php n98-magerun2.phar sys:cron:run indexer_reindex_all_invalid`
9. Look at the indexers statuses: `bin/magento indexer:status` (the two indexers are **still** marked as invalid)
10. Run `php n98-magerun2.phar sys:cron:run indexer_reindex_all_invalid` 
11. Look at the indexers statuses: `bin/magento indexer:status` (the two indexers are **still** marked as invalid)
12. Run `bin/magento indexer:reindex catalogrule_rule catalog_category_product`
13. Look at the indexers statuses: `bin/magento indexer:status` (**only** one indexers is marked as invalid: `catalog_category_product`)
14. Run `php n98-magerun2.phar sys:cron:run indexer_reindex_all_invalid` 
15. Look at the indexers statuses: `bin/magento indexer:status` (All indexers are now finally marked as **valid**)

With this PR applied, after step 8, we can jump immediately to step 13. This is probably still not 100% fixing the problem since I would expect all indexers to be marked as **valid** after this, but maybe that Amasty module is intervening here, not exactly sure without more deeper debugging.

If somebody needs the database from this project, I'm willing to provide it to you in private via Slack for example, but it can contain confidential information, so please I'm asking internal Magento devs to not abuse the information in the database.

Thanks!

### Questions or comments
Maybe a reproducible case is written down in internal ticket MAGETWO-51540 which you can try to reproduce using the `indexer_reindex_all_invalid` cronjob?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by hostep**
### Description (*)

Hi

This was discovered on a particular project where we noticed that the indexers `catalogrule_rule` and `catalog_category_product` are constantly being marked as `Reindex required`.

The cronjob `indexer_reindex_all_invalid` is running and is supposed to fix this, but that doesn't happen.
If however, I stop the cronjobs, and manually execute `bin/magento indexer:reindex catalogrule_rule catalog_category_product` we see a different behavior and only `catalog_category_product` is then marked as `Reindex required.`. If I then execute either `bin/magento indexer:reindex catalog_category_product` or let the cronjob `indexer_reindex_all_invalid` take over again, everything is getting back to a stable state and all indexers are marked as `Ready`.

So this means that the execution of the `indexer_reindex_all_invalid` cronjob and `bin/magento indexer:reindex {all-invalid-indexers}` are behaving differently which isn't correct in my opinion.

We've seen this happening with Magento OS 2.3.5, and I was able to reproduce it on the `2.4-develop` branch (using commit f39a2e0c5ab)

I currently only have a way to reproduce it by using the database of this particular project and we also need a particular module from Amasty installed as well (the Improved Layered Navigation module version 2.14.3).
But in my opinion it's not a bug in the Amasty module but a problem in core Magento since we see a difference in behavior in how invalid indexers are reindexed if you do it manually or if the cronjob executes it.

After searching around a bit I noticed a particular commit which was only applied to the manual reindexing command: [MAGETWO-51540: Linked indexers catalog_category_product and catalog_product_cateogry do not set valid status after shell run](https://github.com/magento/magento2/commit/e8f2b0c385db4036d8953721046af7aabedd6b27).

So I now introduced these same changes to the code which is used by the `indexer_reindex_all_invalid` cronjob and after testing these changes on both our project (on Magento 2.3.5) as on my test on the `2.4-develop` branch, it looks like it fixes the issue.

In my opinion, this is a pretty important bugfix, because this bug causes the server of this particular project to have a high CPU load because of the constant reindexing which happens with every cron run which is not necessary.

In my opinion, we should also try to refactor the code so both `bin/magento indexer:reindex` as the cronjob `indexer_reindex_all_invalid` should use the same code so we can avoid in the future where one fix is applied to one part and forgotten about in the other part.
I've currently chosen not to refactor this so it's easier to review these changes, and maybe somebody can follow up in a later PR to refactor this?

### Fixed Issues (if relevant)
1. None that I could find

### Manual testing scenarios (*)
1. Have magerun2 available to manually execute cronjobs (https://files.magerun.net/)
2. Setup a clean Magento
3. Install Amasty's Improved Layered Navigation module version 2.14.3
4. Use a specific database from our project (sorry, I can't publicly share this database)
5. Run `bin/magento setup:upgrade`
6. Run `bin/magento indexer:reindex` so all indexers are marked as valid
6. Invalidate the two specific 2 indexers: `bin/magento indexer:reset catalogrule_rule catalog_category_product`
7. Look at the indexers statuses: `bin/magento indexer:status` (the two indexers should be marked as invalid)
8. Run `php n98-magerun2.phar sys:cron:run indexer_reindex_all_invalid`
9. Look at the indexers statuses: `bin/magento indexer:status` (the two indexers are **still** marked as invalid)
10. Run `php n98-magerun2.phar sys:cron:run indexer_reindex_all_invalid` 
11. Look at the indexers statuses: `bin/magento indexer:status` (the two indexers are **still** marked as invalid)
12. Run `bin/magento indexer:reindex catalogrule_rule catalog_category_product`
13. Look at the indexers statuses: `bin/magento indexer:status` (**only** one indexers is marked as invalid: `catalog_category_product`)
14. Run `php n98-magerun2.phar sys:cron:run indexer_reindex_all_invalid` 
15. Look at the indexers statuses: `bin/magento indexer:status` (All indexers are now finally marked as **valid**)

With this PR applied, after step 8, we can jump immediately to step 13. This is probably still not 100% fixing the problem since I would expect all indexers to be marked as **valid** after this, but maybe that Amasty module is intervening here, not exactly sure without more deeper debugging.

If somebody needs the database from this project, I'm willing to provide it to you in private via Slack for example, but it can contain confidential information, so please I'm asking internal Magento devs to not abuse the information in the database.

Thanks!

### Questions or comments
Maybe a reproducible case is written down in internal ticket MAGETWO-51540 which you can try to reproduce using the `indexer_reindex_all_invalid` cronjob?

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29478: Avoids endless loop of indexers being marked as invalid
2. [x] resolves magento/magento2#29297: Refactor Magento_Indexer module so that the "indexer_reindex_all_invalid" cronjob and "bin/magento indexer:reindex" command use the same code (done by @engcom-Golf, thanks for that!)

### CODE REVIEW

**Comment by hostep** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run Static Tests
@magento run Unit Tests

**Comment by hostep** [comment]
@magento run Unit Tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @hostep. That's a good point, thank you for your collaboration. Additionally, I would create a separate service i.e. `validateSharedIndex` and put the logic of `getIndexerIdsBySharedIndex` and `validateSharedIndex` there. So we can reuse the newly created class for the indexer processor and `IndexerReindexCommand`. 
But you may do it in a separate PR after the current one is merged if you wish.

**Comment by rogyar** [comment]
@magento run WebAPI Tests

**Comment by hostep** [comment]
@rogyar: thanks for the feedback!

I agree we should refactor this, therefore I created https://github.com/magento/magento2/issues/29297 to follow this up.
I'll try to work on that issue when I find some more time (currently pretty busy with other non-Magento stuff)

**Comment by hostep** [comment]
Just some extra information regarding the server impact we noticed due to this change.
We deployed this solution to a production environment on 07/22, the results are quite noticeable in our case.

1. Server load dropped significantly:
Screenshot 2020-07-28 at 14 16 25

2. Write operations (disk i/o) dropped significantly:
Screenshot 2020-07-28 at 14 17 02

3. We see more Varnish hits (presumably because caches get flushed a lot less frequently):
Screenshot 2020-07-28 at 14 16 37

**Comment by hostep** [comment]
And some further info for the people interested.
I took a look at all our projects which run on Magento 2.3.x (a total of 28 shops, ranging from versions 2.3.1 to 2.3.5) and noticed 3 shops which all have this behavior. All 3 shops are running on version 2.3.5. So it looks like some change in 2.3.5 amplified the chance of this problem happening.
If I have to guess it's probably [MC-30569: Shared indexers have invalid status after full reindex](https://github.com/magento/magento2/commit/96fa0acb61b0416adbe56398a63dc22430dd27f8) (on 2.4 a similar change exists as [MC-30568: Shared indexers have invalid status after full reindex](https://github.com/magento/magento2/commit/593edf76a998d794717823371a762efabb8641bf))

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7929](https://jira.corp.magento.com/browse/ENGCOM-7929) has been created to process this Pull Request

**Comment by VladimirZaets** [comment]
@magento create issue

**Comment by hostep** [comment]
@magento run all tests

File: app/code/Magento/Indexer/Model/Processor.php [hunk 1]
```diff
@@ -60,32 +65,83 @@ public function __construct(
...
+        foreach ($indexerIds as $indexerId) {
+            /** @var \Magento\Indexer\Model\Indexer $indexer */
+            $indexer = $this->indexerFactory->create();
+            $indexer->load($indexerId);
+            /** @var \Magento\Indexer\Model\Indexer\State $state */
+            $state = $indexer->getState();
+            $state->setStatus(StateInterface::STATUS_WORKING);
+            $state->save();
+            $state->setStatus(StateInterface::STATUS_VALID);
+            $state->save();
```
Comment (sarjangautam) [inline app/code/Magento/Indexer/Model/Processor.php:137]: Hi, why do we need to set status twice and save? we are currently having issue with indexes in 235 and came to this PR but i did not understand why this is set twice here.

File: app/code/Magento/Indexer/Model/Processor.php [hunk 2]
```diff
@@ -60,32 +65,83 @@ public function __construct(
...
+    /**
+     * Validate indexers by shared index ID
+     *
+     * @param string $sharedIndex
+     * @return $this
+     */
+    private function validateSharedIndex(string $sharedIndex): self
+    {
+        if (empty($sharedIndex)) {
+            throw new \InvalidArgumentException(
```
Comment (gabrieldagama) [inline app/code/Magento/Indexer/Model/Processor.php]: I guess it would be important to handle this exception on the `reindexAllInvalid`, otherwise, the whole command would keep failing on a specific indexer and not move forward. Also, I would recommend logging the exception msg.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @hostep, thanks for your pull request, please follow a small comment regards your changes (I think it may be important). Also, I strongly recommend avoiding the code duplication between this class and `IndexerReindexCommand`, by duplicating the code we are leaving a gap that could result in these 2 classes having different behavior again, what do you think? Thanks.

**Comment by hostep** [comment]
Thanks for the review @gabrieldagama 

I agree that this needs to be refactored, but this falls out of scope of this Pull Request, I've opened a [new issue](29297) for that, which I commented on before: https://github.com/magento/magento2/pull/29196#issuecomment-664599594

File: app/code/Magento/Indexer/Model/Processor.php (hunk 2 above)
Comment (hostep) [reply app/code/Magento/Indexer/Model/Processor.php]: You are probably right, but this falls out of scope of this PR, it might fit better in the refactoring step which should happen when resolving https://github.com/magento/magento2/issues/29297

Sorry for being so strict, but I want to this bug to be fixed as soon as possible and not being held back by "code quality" requirements. That can happen later. The refactoring will probably not take that much time, but rewriting all the automated tests will take a significant amount of time and I don't have a lot of free time at the moment. Sorry!

**Comment by gabrieldagama** [comment]
Hi @hostep, thanks for your answer, as you may know, if we proceed with this PR as is, it would be released as part of the product on the next version that is in development (in this case 2.4.2), this would take few months before it gets released so I believe is time enough for us to make sure this PR is delivered with quality, that is very important for us.

I understand that you may not have availability to work on this, please let me know if so and we will review and take care of this PR.

Thanks for your contribution, please let me know your thoughts.

**Comment by hostep** [comment]
Thanks for the reply @gabrieldagama 

Feel free to pick up the code quality enhancements you need, I'm only concerned with fixing bugs because I think that's a lot more important than cleaner code.

It's sad to hear that the PR didn't make the cut for 2.4.1 / 2.3.6, even though the PR is 1.5 months old, now let's hope it will make it in 2.4.2 / 2.3.7

So you can take it over to improve this PR if you want or follow it up with an extra PR if you so wish to.

Thanks!

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by engcom-Golf** [comment]
Hi @hostep, thank you for your contribution!
I'm going to continue to work on this PR and make the required changes.

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by hostep** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@hostep, there is an issue with test running:
 14:54:32 [Build Functional CE] PHP Fatal error:  Uncaught Error: Cannot instantiate interface Magento\Framework\Indexer\ConfigInterface in /var/www/html/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php:50
Trying to resolve it

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by Adel-Magebinary** [comment]
I can confirm that this is still happening at 2.3.5-p2 where price index stuck so bad with the schedule.

**Review by rogyar — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7929](https://jira.corp.magento.com/browse/ENGCOM-7929) has been created to process this Pull Request

**Comment by engcom-Foxtrot** [comment]
@hostep hello! I cannot reproduce the issue you are fixing in this PR. Can you please provide some additional information?

**Review by engcom-Foxtrot — CHANGES_REQUESTED** [review]
Cannot reproduce by provided test steps.

**Review by engcom-Foxtrot — APPROVED** [review]

**Comment by engcom-Foxtrot** [comment]
QA passed.

**Comment by hostep** [comment]
Thanks for merging and for the extra assistance by @engcom-Golf & @engcom-Foxtrot!

**Comment by collymore** [comment]
This issue was happening for us on a Magento 2.3.5 store, I've pushed the core PR code to a module/composer package for anyone that needs it on earlier versions https://github.com/develodesign/magento-2-indexer-loop-fix
