### PR TITLE
#39382: Fix incorrect image display for directories with identical names but different case

### LINKED ISSUE #39382: Media gallery displays incorrect images from directories with identical names but different case
### Preconditions and environment

1. Magento 2.4.7

### Steps to reproduce

1. Create folder "Testing"
2. Upload file "logo.png" to "Testing" folder
3. Create folder "testing"
4. "logo.png" file will show in "testing" folder

### Expected result

When a file is uploaded to a specific directory, it should only be accessible within that directory. In this case, the "logo.png" file should be exclusively visible within the "Testing" directory.

### Actual result

The "logo.png" file is incorrectly displayed within the "testing" directory as well, despite the difference in case. This behavior is unexpected and inconsistent with standard file system behavior.

### Additional information

The SQL request that displays the files in media gallery is case insensitive.
Modifying collection query at Magento\MediaGalleryUi\Model\SearchCriteria\CollectionProcessor\FilterProcessor\Directory
`$collection->getSelect()->where('path REGEXP ? ', '^' . $value . '/[^\/]*$');`
to
`$collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');`
should fix the issue. 

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by bhushan-cs**
### Description (*)
This pull request addresses an issue where files uploaded to a specific directory in the Media Gallery are also visible in directories with similar names but different case.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#39382

### Manual testing scenarios (*)
1. OS - Ubuntu
2. Navigate to Content > Media Gallery
3. Create a folder under wysiwyg "Testing"
4. Upload an image in the newly created folder.
5. Select wysiwyg folder and try to create another folder named "testing"
6. Image uploaded to "Testing" folder should not show in "testing" folder.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bhushan-cs** [comment]
@magento run all tests

**Comment by bhushan-cs** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @bhushan-cs,

Thanks for the contribution!

The code changes seems good to us, but please refer to the below review comments:

1. Add some automated tests for case-sensitive path filtering.
2. Add code comments explaining the BINARY requirement.

**Comment by bhushan-cs** [comment]
Hello @engcom-Hotel,

Thank you for the feedback!

I have addressed both review comments:
1. Automated Tests Added
I've implemented comprehensive test coverage for case-sensitive path filtering:
Unit Tests: `app/code/Magento/MediaGalleryUi/Test/Unit/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryTest.php`
Integration Tests: `app/code/Magento/MediaGalleryUi/Test/Integration/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryIntegrationTest.php`
2. Code Comments Added
Added inline comments which explains why BINARY comparison prevents incorrect file visibility across case-variant directories.

Please let me know if you need any adjustments to the tests or documentation!

File: app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php [hunk 1]
```diff
@@ -19,7 +19,16 @@ class Directory implements CustomFilterInterface
...
+
+        /**
+         * Use BINARY comparison for case-sensitive path filtering.
+         * Without BINARY, MySQL's default case-insensitive comparison would match
+         * directories like "Testing" and "testing" as the same, leading to incorrect
+         * file visibility across directories with different case variations.
+         * The regex '^{path}/[^\/]*$' ensures we only match files directly in the
+         * specified directory, not in subdirectories.
+         */
+        $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
```
Comment (engcom-Hotel) [inline app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: Suggestion: Consider to add fallback behaviour with error handling:
```suggestion
       try {
    $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
} catch (\Exception $e) {
    // Log error and fallback to non-BINARY comparison
    $this->logger->error('BINARY regex failed, falling back: ' . $e->getMessage());
    $collection->getSelect()->where('path REGEXP ? ', '^' . $value . '/[^\/]*$');
}
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @bhushan-cs,

Please fix the failed static test, other tests seems flaky to me.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

File: app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php (hunk 1 above)
Comment (bhushan-cs) [reply app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: Hello @engcom-Hotel,

The static test is giving warning on Magento copywriter comment. Do we have to change it to B2B copywriter comment?
```php
* Copyright 2019 Adobe
* All Rights Reserved.
 ```
 

> Suggestion: Consider to add fallback behaviour with error handling:

Great suggestion! I agree that adding error handling makes the solution more robust. I've added a few small modifications:
```php
try {
    $collection->getSelect()->where('BINARY path REGEXP ? ', '^' . $value . '/[^\/]*$');
} catch (\Exception $e) {
    // Log the error for debugging but continue with case-insensitive fallback
    // Note: This fallback means directory filtering will not be case-sensitive
    $this->logger->error('MediaGallery Directory Filter: BINARY REGEXP not supported, using case-insensitive fallback: ' . $e->getMessage());
    $collection->getSelect()->where('path REGEXP ? ', '^' . $value . '/[^\/]*$');
}
```
I was not sure how to edit the code suggestion to add my changes.

Comment (engcom-Hotel) [reply app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: > The static test is giving warning on Magento copywriter comment. Do we have to change it to B2B copywriter comment?

You need to refer the files which is mentioned in the failed test, for example, consider the following screenshot:

image

The above screenshot is from the below static test failure:

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39502/fa70983fcf29df8efaba5329f6467951/Statics/report-sanity-ce.html

Comment (engcom-Hotel) [reply app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: > I was not sure how to edit the code suggestion to add my changes.

You can directly edit this file from your local in the same branch, and commit as usual.

**Comment by engcom-Dash** [comment]
Hi @bhushan-cs 

Just checking in to see if you're currently working on the changes. If not, I’m happy to take care of them to help move things forward. Let me know what works best for you.

Thanks!

File: app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php (hunk 1 above)
Comment (bhushan-cs) [reply app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: Thanks for the guidance. Let me commit the changes.

**Comment by bhushan-cs** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @bhushan-cs,

It seems the PR has been ready for review, hence picking it for the same.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

File: app/code/Magento/MediaGalleryUi/Test/Unit/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryTest.php [hunk 2]
```diff
@@ -0,0 +1,175 @@
+<?php
+/**
+ * Copyright 2019 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/MediaGalleryUi/Test/Unit/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryTest.php]:
```suggestion
 * Copyright 2025 Adobe
```

File: app/code/Magento/MediaGalleryUi/Test/Integration/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryIntegrationTest.php [hunk 3]
```diff
@@ -0,0 +1,212 @@
+<?php
+/**
+ * Copyright 2019 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/MediaGalleryUi/Test/Integration/Model/SearchCriteria/CollectionProcessor/FilterProcessor/DirectoryIntegrationTest.php]:
```suggestion
 * Copyright 2025 Adobe
```

File: app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php [hunk 4]
```diff
@@ -10,16 +10,49 @@
...
 {
+    /**
+     * @var LoggerInterface
+     */
+    private $logger;
+
+    /**
+     * @param LoggerInterface $logger
+     */
+    public function __construct(LoggerInterface $logger)
```
Comment (engcom-Hotel) [inline app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: Make logger parameter optional with ObjectManager fallback for backward compatibility

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @bhushan-cs,

Thanks for working on the changes!

The failed tests seems flaky to me, hence re-running the tests. Also please refer to the below review comments.

Thanks

File: app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php (hunk 4 above)
Comment (bhushan-cs) [reply app/code/Magento/MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php]: I've made the suggested change

**Comment by bhushan-cs** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by bhushan-cs** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seems flaky to me, hence approving the PR.

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests
