### PR TITLE
Fixed Issue #14633 Sub-admin role related issue in order view page in magento 2 admin

### LINKED ISSUE #14633: Sub-admin role related issue in order view page in magento 2 admin
I have created one sub admin user from Magento admin. This user can only view orders, add a comment and operate on shipping. I gave some permissions for sub admin user. Please check the below image:
roles - permissions - system - magento admin 4-11-2018 1-35-43 pm

So as you can see I have disabled Invoice and Credit memo role of this sub-admin.
But when I logged in as sub admin and go to order view page. I saw some error messages pop-up. Check below image:
screenshot-2018-4-11 000000013-1

### Preconditions

1. Magento ver. 2.1.8

### Steps to reproduce

1. In M2 admin, create new sub admin user and then create role for that user with order operation and shipping operation.
2. Next Log in as sub admin user and go to view order page
3. You can see some error messages pop-up

### Expected result

1.Must show Order information tab, shipping tab and comment history tab

### Actual result

1. 
screenshot-2018-4-11 000000013-1
2.
screenshot-2018-4-11 000000013-2

### PR DESCRIPTION
**Pull request by hws47a**
This PR is replacing #20903 with some code style fixes and improvements. 

_*All further description is copy-pasted from the previous PR_  

### Description (*)
Fixed Issue #14633 Sub-admin role related issue in order view page in magento 2 admin

### Fixed Issues (if relevant)

1. Fixes magento/magento2#14633: Sub-admin role related issue in order view page in magento 2 admin
2. ...

### Manual testing scenarios (*)

I have created one sub admin user from Magento admin. This user can only view orders, add a comment and operate on shipping. I gave some permissions for sub admin user. Please check the below image:
screenshotacl

So as you can see I have disabled Invoice and Credit memo role of this sub-admin.
But when I logged in as sub admin and go to order view page.Sometime Pop will come with "Something Went Wrong" and sometimes js error comes in console

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magnto run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @hws47a,
In general your changes looks good to me. Could you cover your changes with some type of tests?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by hws47a** [comment]
@ihor-sviziev I have no problems writing unit tests for this. However, it'll have pretty limited value for this case.

MFTF tests will be more appropriate in this case, but not sure if'll have enough energy and time for that 🙂

**Comment by ihor-sviziev** [comment]
@hws47a I think there will be suitable mftf or integration tests. Please try to write tests, if you'll have any issues - we'll try to help you

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php [hunk 1]
```diff
@@ -14,6 +17,27 @@
...
+    /**
+     * Creditmemos constructor.
+     *
+     * @param Context $context
+     * @param AuthorizationInterface $authorization
+     * @param array $data
+     */
+    public function __construct(
+        Context $context,
+        AuthorizationInterface $authorization,
```
Comment (ihor-sviziev) [inline app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php]: This class is marked with `@api` class, so we can't introduce any backward incompatible changes.

Could you make this argument the last one, make it optional with fallback to retrieving this object from the object manager?

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php [hunk 2]
```diff
@@ -14,6 +17,27 @@
...
+    /**
+     * Invoices constructor.
+     *
+     * @param Context $context
+     * @param AuthorizationInterface $authorization
+     * @param array $data
+     */
+    public function __construct(
+        Context $context,
+        AuthorizationInterface $authorization,
```
Comment (ihor-sviziev) [inline app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php]: This class is marked with @api class, so we can't introduce any backward incompatible changes.

Could you make this argument the last one, make it optional with fallback to retrieving this object from the object manager?

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Shipments.php [hunk 3]
```diff
@@ -21,19 +23,27 @@ class Shipments extends \Magento\Framework\View\Element\Text\ListText implements
...
      *
      * @param \Magento\Framework\View\Element\Context $context
      * @param \Magento\Framework\Registry $coreRegistry
+     * @param AuthorizationInterface $authorization
      * @param array $data
      */
     public function __construct(
         \Magento\Framework\View\Element\Context $context,
         \Magento\Framework\Registry $coreRegistry,
+        AuthorizationInterface $authorization,
```
Comment (ihor-sviziev) [inline app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Shipments.php]: This class is marked with @api class, so we can't introduce any backward incompatible changes.

Could you make this argument the last one, make it optional with fallback to retrieving this object from the object manager?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php (hunk 1 above)
Comment (hws47a) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php]: @ihor-sviziev, I see your point.  
Do you have a link to some guide or documentation about why it should be done this way?  
I was not expected dependency injection parameters to be something that cannot be changed.  
And as for me, taking an object from the object manager braking other code style / architecture principles.

Also, I think it's a bit weird to have these classes marked as `@api`, maybe you are aware of a process or a case of removing `@api`from classes where it shouldn't be?

Comment (ihor-sviziev) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php]: You can find “adding constructor argument” section in https://devdocs.magento.com/contributor-guide/backward-compatible-development/
I don’t think some class could be in-marked as api, also it will be too long approval process that might take from few months to more than half a year

Comment (hws47a) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php]: Thanks, @ihor-sviziev   
I'll make backward-compatible

Comment (hws47a) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Creditmemos.php]: Done

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php (hunk 2 above)
Comment (hws47a) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Invoices.php]: Done

File: app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Shipments.php (hunk 3 above)
Comment (hws47a) [reply app/code/Magento/Sales/Block/Adminhtml/Order/View/Tab/Shipments.php]: Done

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @hws47a,
About the test results:
- SVC - ✔seems like false positive, reported an issue for that https://github.com/magento/magento-semver/issues/50
- functional tests - ✔seems like not related to changes from this PR.
- static tests - ❌ could you fix these failures? Unfortunately we need to make changed files to pass static test, even if before 
changing they weren't.

Could you also cover your changes with MFTF test(s)?

**Comment by hws47a** [comment]
@ihor-sviziev thanks for your checks.  
I'll fix code styles today.  
For MFTF I need some time to re-configure the local environment to make tests work, so probably need a few more days.

**Comment by ihor-sviziev** [comment]
@hws47a if you don't have env for running and writing MFTF tests I would recommend you https://warden.dev/, there is quite good and clear docs.

**Comment by hws47a** [comment]
@magento run all tests

**Comment by hws47a** [comment]
@ihor-sviziev static tests have passed.  
Also, I've just configured the warden and run a sample MFTF test. Thanks for a recommendation.

**Comment by engcom-Charlie** [comment]
@hws47a do you have any updates about test coverage?
Thank you.

**Comment by ihor-sviziev** [comment]
@hws47a will you be able to update your PR with requested changes, or maybe you need some help?

**Comment by hws47a** [comment]
Hi @ihor-sviziev,

I've configured env but haven't started writing an actual test. 
I was too busy all these time. 

Let me try to find a time for a one more week and if I won't start, probably I would need help.

Thanks

**Comment by ihor-sviziev** [comment]
@hws47a any updates? Will you be able to finalize your PR with requested changes?

**Comment by hws47a** [comment]
> @hws47a any updates? Will you be able to finalize your PR with requested changes?

Hi @ihor-sviziev,

I was able to start but not finish. I'm on vacation currently and will be back after Oct 26. 

It would be great if you could help with a test.

Regards,
Vladimir

**Comment by ihor-sviziev** [comment]
Will you be able to push all your changes? Or we can start from scratch?

**Comment by hws47a** [comment]
@ihor-sviziev I don't have anything useful, so from scratch.

**Comment by ihor-sviziev** [comment]
@engcom-Charlie could you help with writing MFTF tests?

**Comment by engcom-Charlie** [comment]
@hws47a I'll continue with your PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
In general looks good.
SVC Failures looks like false positive.
Will wait for when all tests will be finished and approve the PR.

**Review by ihor-sviziev — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8351](https://jira.corp.magento.com/browse/ENGCOM-8351) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual Testing scenario
1. Have some orders in **Sales** - **Orders** grid
2. **Add New Role** in **System** - **User Roles**
3. Check the following **Role Resourcess**:
- _Sales_
- _Operations_
- _Actions_
- _View_
- _Send Order Email_
- _Edit_
- _Cancel_
- _Accept or Deny Payment_
- _Capture_
- _Hold_
- _Unhold_
- _Ship_
- _Comment_
- _Send Sales Emails_
- _Shipment_
- _Transaction_
- _Fetch_
screenshotacl
4. **Add New User** under **System** - **All Users**
5. Fill in all the required fields, and assign the previously created **User Role**
6. **Sign In** Magento admin with the previously created User
7. Go to **Sales** - **Orders** grid and **View** any order

**BEFORE** applying changes provided in this PR
us_roles_error

**AFTER** switching on the PR
An order can be Viewed, Shipped, put on Hold, Canceled. Email can be sent

**Comment by engcom-Charlie** [comment]
It needs to approve, **SVC** falls with errors:
- Magento\Sales\Block\Adminhtml\Order\View\Tab\Shipments::getOrder `[public] Method return typing changed.`
- Magento\Sales\Block\Adminhtml\Order\View\Tab\Creditmemos::__construct `[public] Method has been added.`
- Magento\Sales\Block\Adminhtml\Order\View\Tab\Invoices::__construct  `[public] Method has been added.`

**Comment by hws47a** [comment]
@engcom-Charlie @sidolov should it be closed?

**Comment by sivaschenko** [comment]
@magento run Semantic Version Checker

**Comment by sivaschenko** [comment]
Approval Request: https://jira.corp.magento.com/browse/MC-41920
Can be merged after the approval request is completed

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8351](https://jira.corp.magento.com/browse/ENGCOM-8351) has been created to process this Pull Request

**Comment by sivaschenko** [comment]
The SVC failure is approved
