### PR TITLE
Fix issue when Proxy class wasn't generated during di compile

### LINKED ISSUE #35252: Proxy code generation does not generate classes
### Preconditions (*)

1. Magento Commerce 2.4.3-p1
2. PRODUCTION mode (!important)

### Steps to reproduce (*)

1. Create a new module
2. Add the file `etc/adminhtml/di.xml` with content in which the proxy arguments have line breaks at the end
```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Amasty\Oaction\Model\Action\ActionModifierProvider">
        <arguments>
            <argument name="modifiers" xsi:type="array">
                <item name="amasty_oaction_orderattr" xsi:type="object">
                    Amasty\Oaction\Model\Action\Modifier\OrderAttributesModifier\Proxy
                </item>
                <item name="pdfshipments_order" xsi:type="object">
                    Amasty\Oaction\Model\Action\Modifier\PrintPackingSlipsModifier\Proxy
                </item>
            </argument>
        </arguments>
    </type>
    <type name="Amasty\Oaction\Model\Command\Pdf\PdfCollectorResolver">
        <arguments>
            <argument name="collector" xsi:type="object">
                Amasty\Oaction\Model\Command\Pdf\PdfCollector\ZipCollector\Proxy
            </argument>
        </arguments>
    </type>
</config>
```
3. Set production mode
4. run the **`setup:di:compile`** command
5. Check the generated/code folder for `Amasty\Oaction\Model\Action\Modifier\OrderAttributesModifier\Proxy` and `Amasty\Oaction\Model\Action\Modifier\PrintPackingSlipsModifier\Proxy`
6. Check the generated/metadata folder for `generated/metadata/adminhtml.php` content 

### Expected result (*)

1. Proxy files were successfully created after compilation
2. Factory files have been successfully created after compilation

### Actual result (*)

1. Proxy files are missing
2. In my case, there is even an error when trying to open the admin panel

```
Class Amasty\\Oaction\\Model\\Action\\Modifier\\OrderAttributesModifier\\Proxy does not exist

#1 Magento\\Framework\\Code\\Reader\\ClassReader->getConstructor() called at [vendor\/magento\/framework\/ObjectManager\/Definition\/Runtime.php:54],,,
#2 Magento\\Framework\\ObjectManager\\Definition\\Runtime->getParameters() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:100]
#3 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:150]
#4 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:125]
#5 Magento\\Framework\\ObjectManager\\Factory\\Compiled->parseArray() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:86]
#6 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:150]
#7 Magento\\Framework\\ObjectManager\\Factory\\Compiled->get() called at [vendor\/magento\/framework\/ObjectManager\/Factory\/Compiled.php:79]
#8 Magento\\Framework\\ObjectManager\\Factory\\Compiled->create() called at [vendor\/magento\/framework\/ObjectManager\/ObjectManager.php:70]
#9 Magento\\Framework\\ObjectManager\\ObjectManager->get() called at [vendor\/magento\/framework\/Interception\/PluginList\/PluginList.php:174]
#10 Magento\\Framework\\Interception\\PluginList\\PluginList->getPlugin() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:144]
#11 Magento\\Ui\\Config\\Reader\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]
#12 Magento\\Ui\\Config\\Reader\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Ui\/Config\/Reader\/Interceptor.php:23]
#13 Magento\\Ui\\Config\\Reader\\Interceptor->read() called at [vendor\/magento\/module-ui\/Config\/Data.php:102]
#14 Magento\\Ui\\Config\\Data->initData() called at [vendor\/magento\/module-ui\/Config\/Data.php:136]
#15 Magento\\Ui\\Config\\Data->get() called at [vendor\/magento\/framework\/View\/Layout\/Reader\/UiComponent.php:100]
#16 Magento\\Framework\\View\\Layout\\Reader\\UiComponent->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]
#17 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Layout\/Reader\/Container.php:84]
#18 Magento\\Framework\\View\\Layout\\Reader\\Container->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]
#19 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Page\/Config\/Reader\/Body.php:68]
#20 Magento\\Framework\\View\\Page\\Config\\Reader\\Body->interpret() called at [vendor\/magento\/framework\/View\/Layout\/ReaderPool.php:105]
#21 Magento\\Framework\\View\\Layout\\ReaderPool->interpret() called at [vendor\/magento\/framework\/View\/Layout.php:346]
#22 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:32]
#23 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]
#24 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:65]
#25 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]
#26 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Page\/Config.php:224]
#27 Magento\\Framework\\View\\Page\\Config->build() called at [vendor\/magento\/framework\/View\/Page\/Config.php:237]
#28 Magento\\Framework\\View\\Page\\Config->publicBuild() called at [vendor\/magento\/framework\/View\/Result\/Page.php:244]
#29 Magento\\Framework\\View\\Result\\Page->render() called at [vendor\/magento\/framework\/View\/Result\/Layout.php:171]
#30 Magento\\Framework\\View\\Result\\Layout->renderResult() called at [generated\/code\/Magento\/Backend\/Model\/View\/Result\/Page\/Interceptor.php:23]
#31 Magento\\Backend\\Model\\View\\Result\\Page\\Interceptor->renderResult() called at [vendor\/magento\/framework\/App\/Http.php:120]
#32 Magento\\Framework\\App\\Http->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]
#33 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]
```

### Discovery

When production mode is set, code generation is performed only during **`setup:di:compile`**.

After code generation, Proxy and Factory files are missing because [\Magento\Setup\Module\Di\Code\Scanner\XmlScanner::collectEntities()](https://github.com/magento/magento2/blob/2.4.3-p1/setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php#L48) and [\Magento\Setup\Module\Di\Code\Scanner\XmlScanner::scanFactories()](https://github.com/magento/magento2/blob/2.4.3-p1/setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php#L76) use not quite correct regular expressions that want to meet the value without extra whitespace characters after Proxy and Factory

At the same time, these arguments were successfully added to the metadata file `generated/metadata/adminhtml.php`

image

If you use developer mode, then after compiling di, there is also no proxy files, but when accessing the website, these classes are generated on the fly, which avoids errors.

Most likely, this problem can be fixed by changing regexp, which will allow you to use whitespace characters at the end, or by replacing this regulatory expression with a suitable xpath expression.

`$regex = '/^(.*)\\\(.*)Proxy$/';` -> `$regex = '/^(.*)\\\(.*)Proxy(\s*)$/';`
` $regex = '/^(.*)Factory$/';` -> `$regex = '/^(.*)Factory(\s*)$/';`

When I reformat `di.xml` without line breaks, then everything starts working correctly. 

From  image

To image

But the use of line breaks in the arguments is not prohibited in any way

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)

Proxies weren't generated due to the wrong regex, which isn't allowing spaces and newlines before and after the class name.
So I made the following fixes:
- Added optional spaces before and after class names for Proxies and Factories + added trim to have equal results
- Added left trim of backslash for class names - it should reduce duplicates
- Extracted logic of detecting proxies to a separate method, similar to how factories are getting detected
- Fixed array_merge in a loop issue

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/35252

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
https://github.com/magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Functional Tests EE, Integration Tests

File: setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php [hunk 1]
```diff
@@ -42,42 +44,55 @@ public function collectEntities(array $files)
...
 
-            $factoriesOutput = array_merge($factoriesOutput, $this->scanFactories($xpath));
+            $output[] = $this->scanProxies($xpath);
+            $factoriesOutput[] = $this->scanFactories($xpath);
         }
 
-        $output = array_unique($output);
-        $factoriesOutput = array_unique($factoriesOutput);
+        $output = array_unique(array_merge([], ...$output));
+        $factoriesOutput = array_unique(array_merge([], ...$factoriesOutput));
```
Comment (Den4ik) [inline setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php:55]: Why do you extract arrays? `array_merge` expect arrays as parameters. As I see `$output` and `$factoriesOutput` are array of strings and extracting will generate fatal error on php 8.

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev. Thank you for updates.
Could you please check my review comments.

File: setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php (hunk 1 above)
Comment (ihor-sviziev) [reply setup/src/Magento/Setup/Module/Di/Code/Scanner/XmlScanner.php:55]: I updated logic above, now it contains arrays of arrays, this is needed to prevent array merge in a loop

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Database Compare, Integration Tests, WebAPI Tests

**Review by Den4ik — APPROVED** [review]
@ihor-sviziev Thanks for PR.
I checked it locally and failed unit tests is not reproducible.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**
1. Created a custom module named `Magento_CustomModule`
2. In the etc folder of the module created a di.xml with this content

```
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
   <type name="Magento\Catalog\Model\ProductLink\CollectionProvider">
       <arguments>
           <argument name="providers" xsi:type="array">
               <item name="crosssell" xsi:type="object">
                       Magento\Catalog\Model\ProductLink\CollectionProvider\Crosssell\Proxy
               </item>
               <item name="upsell" xsi:type="object">Magento\Catalog\Model\ProductLink\CollectionProvider\Upsell\Proxy</item>
               <item name="related" xsi:type="object">Magento\Catalog\Model\ProductLink\CollectionProvider\Related\Proxy</item>
           </argument>
       </arguments>
   </type>
   <type name="Magento\Catalog\Model\Product">
       <arguments>
           <argument name="catalogProductStatus" xsi:type="object">
           Magento\Catalog\Model\Product\Attribute\Source\Status\Proxy
           </argument>
           <argument name="productLink" xsi:type="object">
           Magento\Catalog\Model\Product\Link\Proxy
           </argument>
       </arguments>
   </type>
</config>
```
3. Set the **_`Production`_** mode on
4. Deleted the generated folder from the root and run the command `bin/magento setup:di:compile`
5. In the generated folder, the Proxy file is only generated for proxy arguments that are given without the line break and not for the arguments that are given with a line break. 

**Before:** :heavy_multiplication_x: 
image

**After:** :heavy_check_mark:  
image

**Comment by engcom-Echo** [comment]
@magento run Static Tests

**Comment by engcom-Echo** [comment]
As there are build failures, Hence moving it to `Extended Testing`.

**Comment by engcom-Echo** [comment]
@ihor-sviziev Can you please have a look at Unit Test Failure seems like related to PR changes?
As there are build failure Hence moving to `Extended Testing`

**Comment by engcom-Echo** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@engcom-Echo, as it was stated in https://github.com/magento/magento2/pull/37434#issuecomment-1523478164, I can't reproduce unit test failure locally.

**Comment by engcom-Echo** [comment]
> @engcom-Echo, as it was stated in [#37434 (comment)](https://github.com/magento/magento2/pull/37434#issuecomment-1523478164), I can't reproduce unit test failure locally.

Thank for a quick response.
I will have a look and work on it.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@engcom-Echo I can confirm that failed unit test is not reproducing locally. I have checked it under review process.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all test

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,WebAPI Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
Functional Tests CE failure are different on last two run on same commit.
Run1
Screenshot 2023-09-14 at 7 24 44 PM

Run2
Screenshot 2023-09-14 at 7 24 52 PM

Hence moving it to `merge in progress`
