### PR TITLE
Admin interface locale breaks  "Expiration date" field

### LINKED ISSUE #32497: Admin interface locale breaks  "Expiration date" field
### Preconditions (*)
1. Magento version 2.4.2

### Steps to reproduce (*)
1. sigh in to admin panel
1. go to System -> All users
1. change locale of current user to Any except 'en_Us'
1. try to create a new user, and set expiration date 
1. save user
1. get an error "Expiration Date is not valid"

### Expected result (*)
1. expect to create user

### Actual result (*)
1. !https://user-images.githubusercontent.com/33631491/111330717-df91bd80-8678-11eb-91c4-824bccdf455c.jpeg!

## 
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*

@magento give me 2.4-develop instance

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/32497

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/32497

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Security/Model/ResourceModel/UserExpiration.php [hunk 1]
```diff
@@ -71,15 +89,16 @@ protected function _beforeSave(\Magento\Framework\Model\AbstractModel $userExpir
...
      * @throws \Exception
      */
-    protected function _afterLoad(\Magento\Framework\Model\AbstractModel $userExpiration)
+    protected function _afterLoad(AbstractModel $userExpiration)
     {
-        /** @var $userExpiration \Magento\Security\Model\UserExpiration */
+        /** @var $userExpiration UserExpirationModel */
         if ($userExpiration->getExpiresAt()) {
-            $storeValue = $this->timezone->date($userExpiration->getExpiresAt());
+            $date = new \DateTime($userExpiration->getExpiresAt(), new \DateTimeZone('UTC'));
```
Comment (zakdma) [inline app/code/Magento/Security/Model/ResourceModel/UserExpiration.php]: UTC timezone is redundant since Magento setup UTC by default
https://github.com/magento-tsg/magento2ce/blob/2.4-develop/app/bootstrap.php#L73

File: lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php [hunk 2]
```diff
@@ -7,12 +7,11 @@
...
 namespace Magento\Framework\Stdlib\DateTime\Timezone;
 
-use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
 use Magento\Framework\Locale\ResolverInterface;
-use Magento\Framework\App\Config\ScopeConfigInterface;
+use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
 
 /**
- * Class LocalizedDateToUtcConverter
+ * @inheritdoc
```
Comment (zakdma) [inline lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php]: @inheritDoc

File: lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php [hunk 3]
```diff
@@ -65,9 +62,7 @@ public function convertLocalizedDateToUtc($date)
         $localTimestamp = $formatter->parse($date);
         $gmtTimestamp = $this->timezone->date($localTimestamp)->getTimestamp();
         $formattedUniversalTime = date($this->defaultFormat, $gmtTimestamp);
-
-        $date = new \DateTime($formattedUniversalTime, new \DateTimeZone($configTimezone));
-        $date->setTimezone(new \DateTimeZone('UTC'));
+        $date = new \DateTime($formattedUniversalTime, new \DateTimeZone('UTC'));
```
Comment (zakdma) [inline lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php]: UTC timezone is redundant since Magento setup UTC by default
https://github.com/magento-tsg/magento2ce/blob/2.4-develop/app/bootstrap.php#L73

**Review by zakdma — CHANGES_REQUESTED** [review]

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Security/Model/ResourceModel/UserExpiration.php (hunk 1 above)
Comment (engcom-Kilo) [reply app/code/Magento/Security/Model/ResourceModel/UserExpiration.php]: Fixed.

File: lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php (hunk 2 above)
Comment (engcom-Kilo) [reply lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php]: Fixed.

File: lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php (hunk 3 above)
Comment (engcom-Kilo) [reply lib/internal/Magento/Framework/Stdlib/DateTime/Timezone/LocalizedDateToUtcConverter.php]: Fixed.

**Review by zakdma — APPROVED** [review]

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Before:**
before

**After:**
after

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9093](https://jira.corp.magento.com/browse/ENGCOM-9093) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-33033`.
