### PR TITLE
Fixed customertoken not generating after configured failure in a row

### LINKED ISSUE #34067: [Issue] Fixed customertoken not generating after configured failure in a row
This issue is automatically created based on existing pull request: magento/magento2#34001: Fixed customertoken not generating after configured failure in a row

---------

### Description (*)
This pull request solves the issue when a customer has tried too many fail attempt (i.e more no of times than in the configuration)for generating the customer token via graphql or rest api. Then the customer is not able to log into the system ever.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Make more number of unsuccessful attempt than the configured number of times (configuration can be found in Services->Oauth) to generate the customer token via generateCustomerToken graphql api. 
2. After that, the customer would not be able to generate the token even with correct credentials.

### Questions or comments

The issue was occuring because in the current system, there was no any check if `lock_expires_at` in  `oauth_token_request_log`  is greater than current date time. So, the system always returns the no of failed attempts. 

For example, let's say, if the configured no of failed attempt is 6. And the customer has tried 7 times to generate the customer token via graphql api. Now, after the expiry time of `lock_expires_at` even when he/she tries with correct credentials, he/she is not able to generate the customer token and get the exception 

'The account sign-in was incorrect or your account is disabled temporarily. '
                    . 'Please wait and try again later.'
image

This is a major issue for the Scandi PWA login as customer is not able to logged into the PWA after trying too many unsuccessful attempt.

To resolve the issue, i have applied the check if `lock_expires_at` is greater than current date time. Then we got zero token in that case and when the customer login with correct credentials, he/she will log into the system.

Please let me know if you need additional test cases (i have to make the test cases, lol) or any other description you want. 
### Contribution checklist (*)
 - [ *] Pull request has a meaningful description of its purpose
 - [ *] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by sagar2009kumar**
### Description (*)
This pull request solves the issue when a customer has tried too many fail attempt (i.e more no of times than in the configuration)for generating the customer token via graphql or rest api. Then the customer is not able to log into the system ever.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Make more number of unsuccessful attempt than the configured number of times (configuration can be found in Services->Oauth) to generate the customer token via generateCustomerToken graphql api. 
2. After that, the customer would not be able to generate the token even with correct credentials.

### Questions or comments

The issue was occuring because in the current system, there was no any check if `lock_expires_at` in  `oauth_token_request_log`  is greater than current date time. So, the system always returns the no of failed attempts. 

For example, let's say, if the configured no of failed attempt is 6. And the customer has tried 7 times to generate the customer token via graphql api. Now, after the expiry time of `lock_expires_at` even when he/she tries with correct credentials, he/she is not able to generate the customer token and get the exception 

'The account sign-in was incorrect or your account is disabled temporarily. '
                    . 'Please wait and try again later.'
image

This is a major issue for the Scandi PWA login as customer is not able to logged into the PWA after trying too many unsuccessful attempt.

To resolve the issue, i have applied the check if `lock_expires_at` is greater than current date time. Then we got zero token in that case and when the customer login with correct credentials, he/she will log into the system.

Please let me know if you need additional test cases (i have to make the test cases, lol) or any other description you want. 
### Contribution checklist (*)
 - [ *] Pull request has a meaningful description of its purpose
 - [ *] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#34067: Fixed customertoken not generating after configured failure in a row

### CODE REVIEW

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
The code here looks fine but you need to properly fill out the PR description to explain the issue being solved, what the fix does and how to test (if appropriate)

A good example of a PR description :  https://github.com/magento/magento2/pull/33998

**Comment by sagar2009kumar** [comment]
@BarnyShergold I have updated the description. Please check and let me know if you need more clarification or anything else needed.

**Review by BarnyShergold — APPROVED** [review]
Nice! Excellent update

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9215](https://jira.corp.magento.com/browse/ENGCOM-9215) has been created to process this Pull Request
:eight_spoked_asterisk: @BarnyShergold, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by sagar2009kumar** [comment]
@magento run all tests again.

**Comment by alansoftsolutions** [comment]
@BarnyShergold , Can you please let me know why this issue is occuring, i think it is more of a code style rather than code ? Can you please suggest ? Thanks in advance. 
image

**Comment by sagar2009kumar** [comment]
@BarnyShergold , Can you please let me know why this issue is occuring, i think it is more of a code style rather than code ? Can you please suggest ? Thanks in advance. 
image

File: app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php [hunk 1]
```diff
@@ -58,11 +58,14 @@ protected function _construct()
...
+        $date = (new \DateTime())->setTimestamp($this->dateTime->gmtTimestamp());
+        $dateTime = $date->format(\Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT);
+        
         $select = $this->getConnection()->select();
         $select->from($this->getMainTable(), 'failures_count')
-            ->where('user_name = :user_name AND user_type = :user_type');
+            ->where('user_name = :user_name AND user_type = :user_type AND lock_expires_at > :expiration_time');
 
-        return (int)$this->getConnection()->fetchOne($select, ['user_name' => $userName, 'user_type' => $userType]);
+        return (int)$this->getConnection()->fetchOne($select, ['user_name' => $userName, 'user_type' => $userType, 'expiration_time' => $dateTime]);
```
Comment (BarnyShergold) [inline app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php]: Would seem this is WAY too long - try this to get rid of the obvious error. Not sure why the inherits are playing up ad they are in existing code.

```suggestion
        return (int)$this->getConnection()->fetchOne(
             $select, 
             [
                 'user_name' => $userName, 
                 'user_type' => $userType, 
                 'expiration_time' => $dateTime,
             ]
        );
```

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Try this update to start

**Comment by sagar2009kumar** [comment]
@magento run all tests

File: app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php [hunk 2]
```diff
@@ -58,11 +58,21 @@ protected function _construct()
...
+        $dateTime = $date->format(\Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT);
+        
         $select = $this->getConnection()->select();
         $select->from($this->getMainTable(), 'failures_count')
-            ->where('user_name = :user_name AND user_type = :user_type');
+            ->where('user_name = :user_name AND user_type = :user_type AND lock_expires_at > :expiration_time');
 
-        return (int)$this->getConnection()->fetchOne($select, ['user_name' => $userName, 'user_type' => $userType]);
+        return (int)$this->getConnection()->fetchOne(
+             $select,
```
Comment (BarnyShergold) [inline app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php]: It looks like the indenting was a bit out. Reduce indenting by one space on lines 69 - 74

Comment (BarnyShergold) [reply app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php]: Also line 69, 70, 71 & 72 have a whitespace at the end of the line. These need to be removed.
I would suggest setting up PHPSniffer locally so you can check BEFORE committing. If you rely on the testing here then it could take a long time.

If you can get these cleaned up and the inherit one still exists we can ask one oft he Magento guys why you are getting a fail on code you didn't touch!

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
You are also getting this fail - Failed asserting that '2021-09-07 13:04:59' contains "2021-09-07 13:05". (testEditCompanyActionLogging) /var/www/html/dev/tests/integration/testsuite/Magento/Company/LoggingTest.php

File: app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php (hunk 2 above)
Comment (sagar2009kumar) [reply app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php]: Thanks @BarnyShergold , I am trying to install PHPsniffer locally and check why those tests are failing. I will let you know what i found out.

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9215](https://jira.corp.magento.com/browse/ENGCOM-9215) has been created to process this Pull Request

**Comment by andrewbess** [comment]
Hello @sagar2009kumar 
Thank you for your contribution here.
I am going to fix static tests.
Could you please give me collaboration for your fork?
Thank you in advance.

**Comment by sagar2009kumar** [comment]
Hi @andrewbess 

I am not sure what you are asking. Can you please confirm if you want the forked repo or only changes ?

**Comment by engcom-Alfa** [comment]
@magento run Static Tests

**Comment by andrewbess** [comment]
> Hi @andrewbess
> 
> I am not sure what you are asking. Can you please confirm if you want the forked repo or only changes ?
> 
> If it is the repo which i have forked, then you can have a look at https://github.com/sagar2009kumar/magento2

Hello @sagar2009kumar 
I can only see it, but cannot add changes to fix static tests.
We cannot deliver changes with failed builds.
Please fix static tests or give collaboration to your fork for me to I have had a possibility to fix static tests by myself.
Thank you in advance.

**Comment by sagar2009kumar** [comment]
> > Hi @andrewbess
> > I am not sure what you are asking. Can you please confirm if you want the forked repo or only changes ?
> > If it is the repo which i have forked, then you can have a look at https://github.com/sagar2009kumar/magento2
> 
> Hello @sagar2009kumar
> I can only see it, but cannot add changes to fix static tests.
> We cannot deliver changes with failed builds.
> Please fix static tests or give collaboration to your fork for me to I have had a possibility to fix static tests by myself.
> Thank you in advance.

Hi @andrewbess

I have given access to my repo as collaborator. Please check if you have access. Let me know if you didn't receive it.

**Comment by engcom-Alfa** [comment]
Hi @sagar2009kumar , @andrewbess and @BarnyShergold 
Thanks for your contribution and collaboration!

Below is the procedure I followed.
1. I set the configuration as shown in the below screenshot firstly.
image

2. Requested for customer token 4-5 times with invalid credentials.
3. Waited for 10 seconds (as I set for 10 seconds only).
4. Later, again requested the same API with valid credentials.
5. Able to get the token successfully (Below is the screenshot of it.)
image

Q1- As per the description API has this issue, I tried to execute it. Let me know if I have to follow any other procedure.
Q2- Also please provide me what is the query you used for GraphQL request.

You can provide me more information on above 2 questions. But since the PR is failing to execute the auto test- Static Tests, I am moving this PR back to _Changes Requested_. Kindly help fix the automation failure case as well!

**Comment by sagar2009kumar** [comment]
image

The "Allowed key by maintainers" is already enabled for this pull request.

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Since the PR is failing to execute the auto test- Static Tests, I am moving this PR back to Request changes

**Comment by sagar2009kumar** [comment]
Let me check it again and provide you the full details of it. Sorry for the delay in the test cases.

**Comment by sagar2009kumar** [comment]
@engcom-Alfa ,

Please hit the query as in the screenshot.

image

This is the first screenshot with the correct credentials.

image

This is the second screenshot with the wrong credentials.

image

This is the data of the lock table.

image

This is the screenshot with correct credentials. You can see that the time is 16:12 which is greater than lock_expires_at time.

image

This is the screenshot of the fix that i have applied, please ignore for the static files and spaces for now. I am trying to get a hold of it.

image

This is the screenshot of the result after the fix has been applied. 

image

Database table `oauth_token_request_log` view. 

I am trying to apply the php sniffer for now. I haven't applied it previously that's why it is taking time. I will try to do it at my earliest.

Let me know if you need any more details. :smirk:

**Comment by sagar2009kumar** [comment]
@magento run tests

**Comment by sagar2009kumar** [comment]
@BarnyShergold , I guess i am not allowed to tell magento to run tests. Could you please ask magento the same ? Thanks in advance.

**Comment by andrewbess** [comment]
@sagar2009kumar 
@magento run all tests

**Comment by andrewbess** [comment]
> @magento run tests

@sagar2009kumar Do you forget the 'all' word between run and tests

**Comment by sagar2009kumar** [comment]
Oops. My mistake 😅😅. Thanks @andrewbess

**Comment by sagar2009kumar** [comment]
@andrewbess , @BarnyShergold , I have fixed the issue in the changed file. But, now the test case is failing from completely unrelated code change. I am not sure how to fix that and also not sure how it failed. Can you please take a look at the failure test cases and suggest me the modification for it ? I would be very thankful to you. :)

**Comment by andrewbess** [comment]
Hello @sagar2009kumar 
Sometime, the MFTF tests fails randomly.
I have rerun failed build.
Thank you for your job.

File: app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php [hunk 3]
```diff
@@ -46,27 +46,41 @@ public function __construct(
...
     /**
-     * {@inheritdoc}
+     * @inheritdoc
+     * @param string $userName
+     * @param int $userType
      */
     public function getFailuresCount($userName, $userType)
     {
+        $date = (new \DateTime())->setTimestamp($this->dateTime->gmtTimestamp());
+        $dateTime = $date->format(\Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT);
```
Comment (Den4ik) [inline app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php:64]: Why you didn't use `\Magento\Framework\Stdlib\DateTime\DateTime::gmtDate`?

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @sagar2009kumar 
Thanks for your work.

Please look at my comment

File: app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php (hunk 3 above)
Comment (sagar2009kumar) [reply app/code/Magento/Integration/Model/ResourceModel/Oauth/Token/RequestLog.php:64]: Since previously in the code of incrementing the count, you can see in the incrementFailuresCount and clearExpiredFailures function, the same has been used. So, I think if it would cause any time differences in the timezone, so better stick to the one which has been used previously.

**Review by Den4ik — APPROVED** [review]
✅ Approved.

Magento has 1000 + 1 solution in different files for one task - get gmt time.
I believe it will be refactored in future and have one solution in all files

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9215](https://jira.corp.magento.com/browse/ENGCOM-9215) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Magento Instance 2.4-develop with one front end active customer login


**Manual testing scenario:**

1. Request a graphql mutation of getCustomerToken with valid customer credentials, check able to get the token successfully.

2. Admin UI > Stores> Configurations> Services> Oauth> Authentication Locks tab> Set _Lockout Time (seconds)_ to 10 seconds (So that we can cross check the issue at the earliest.)
 
3. Request the same graphql mutation of getCustomerToken with invalid customer credentials, check that invalid response received.

4. Do request same for 6 more times one after other, so that user gets locked out! (We can cross check the locked used details in the _oauth_token_request_log_ table)

5. Wait for more than 10 seconds (keep system idle)

6. Request the same mutation again with same valid credentials.

**Before:** :heavy_multiplication_x: Customer token was not getting generating even after wait time

image


**After:** :heavy_check_mark:  Customer token is getting generating after the wait time expiration

image

There is no impact on any other feature since this fix is related to specific query response, no additional regression is required.

**Review by BarnyShergold — APPROVED** [review]
All tests now passing

**Comment by magento-engcom-team** [comment]
Hi @BarnyShergold, thank you for the review.
[ENGCOM-9215](https://jira.corp.magento.com/browse/ENGCOM-9215) has been created to process this Pull Request

**Comment by sagar2009kumar** [comment]
@engcom-Alfa , Please approve the changes or let me know if there is any change needed. :smile:

**Comment by BarnyShergold** [comment]
@magenti run all tests

**Comment by sagar2009kumar** [comment]
@magento run all tests

**Comment by sagar2009kumar** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that all the review comments has been taken care so moving it further.

Thank you!

**Comment by engcom-Alfa** [comment]
Re-tested today completely and the report remains same as mentioned in [above-comment](https://github.com/magento/magento2/pull/34001#issuecomment-918352157). Hence moving it to _Merge In Progress_.
