### PR TITLE
32977 Fixed text area for Customizable Options on the Checkout Cart Page

### LINKED ISSUE #32977: Text Area for Customizable Options shows line break html<br/> on the front end in cart area if a user enters more than 55 characters
Summary of the issue
We have Customizable Options with text areas where people can enter up to 350 characters. If they enter a message that's 50 characters with line breaks it all works OK and displays properly in the cart area. If they enter more than 55 characters the cart area displays the html <br/> line break code

### Preconditions (*)
Information on your environment
Running Magento 2.4.2
Dedicated server
PHP 7.3
MariaDB10.3

### Steps to reproduce (*)
Steps to reproduce
Create a product in admin, create two customizable options both with text area option with 350 characters allowed. Enter less than 55 characters in one text area and more than 55 in the other both with spaces and line breaks. Add the item to your cart and you will see the html line breaks in the text area option with more than 55 characters.

### Expected result (*)
Cart should just show the text entered in each option and not the html line break code

### Actual result (*)
Cart shows html in option
Capture

### PR DESCRIPTION
**Pull request by AZiniukhin**
### Description (*)

I created a solution in the file ( Magento/Checkout/view/frontend/templates/cart/item/default.phtml ). 
For the correct display of the text, need to add one or more AllowedTags ( ['span', 'a'] ) to the function call 
( $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a'] ) by analogy with 
( $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ). 
If this is not done, then the formation of the text will take place without the pregmach function called on line 117 of the file 
( lib/internal/Magento/Framework/Escaper.php ) which leads to incorrect display of text.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#32977

### Manual testing scenarios (*)

1. Create a simple product in the admin panel.
2. Create two customizable options both with text area option with 350 characters allowed.
3. On the product page enter less than 55 characters in one text area and more than 55 in the other both with spaces and line breaks.
Screenshot 2021-06-16 at 12 14 57
4. Add the item to your cart and go to the cart page. You will see the correct text display.
Screenshot 2021-06-16 at 12 19 21

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by AZiniukhin** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you cover your fix with some kind of automated test?

**Comment by AZiniukhin** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Unit Tests, Functional Tests EE

**Comment by AZiniukhin** [comment]
The test added, please check @ihor-sviziev

File: dev/tests/integration/testsuite/Magento/Checkout/_files/cart_with_simple_product_and_custom_option_text_area.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+$options = [];
+/** @var $option Option */
+foreach ($product->getOptions() as $option) {
+    switch ($option->getGroupByType()) {
+        case ProductCustomOptionInterface::OPTION_GROUP_SELECT:
+            $value = key($option->getValues());
+            break;
+        default:
+            $value = 'Test product simple with
```
Comment (Den4ik) [inline dev/tests/integration/testsuite/Magento/Checkout/_files/cart_with_simple_product_and_custom_option_text_area.php]: I believe that heredoc syntax looks more clear

File: dev/tests/integration/testsuite/Magento/Checkout/Block/Cart/Item/RendererTest.php [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+        $template = 'Magento_Checkout::cart/item/default.phtml';
+        $this->renderer->setTemplate($template);
+        $this->renderer->setItem($quoteItem);
+
+        $priceBlock = $this->objectManager->create(\Magento\Checkout\Block\Item\Price\Renderer::class);
+        $this->renderer->getLayout()->setBlock('checkout.item.price.unit', $priceBlock);
+        $this->renderer->getLayout()->setBlock('checkout.item.price.row', $priceBlock);
+        $html = $this->renderer->toHtml();
+
+        $this->assertMatchesRegularExpression('/Test product simple with
```
Comment (Den4ik) [inline dev/tests/integration/testsuite/Magento/Checkout/Block/Cart/Item/RendererTest.php]: I believe that heredoc syntax looks more clear

**Review by Den4ik — CHANGES_REQUESTED** [review]
@AZiniukhin Thanks for contribution.
Please look at my comment. What do you think?

**Comment by AZiniukhin** [comment]
@Den4ik 
I added heredoc syntax. Please check.

**Comment by Den4ik** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]
✅ Approved
Changes looks good for me. @AZiniukhin Thanks for contribution.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed


**Preconditions:**

> 1. Create a product created with 2 customizable options. The options should be with text areas that accepts minimum 350 characters.


**Manual testing scenario:**
> 
> 1. Front end - Checkout the same product with both the text area customizable options filled. (Note: Text area options should be filled with new line as well; Ex is in below screenshot)
>     image
> 
> 2. Proceed to Checkout page and validate the product content.


**Before:** :heavy_multiplication_x: <br /> text was getting appeared in the page

> image


**After:** :heavy_check_mark:  One line description about the is the outcome after fix

> image
