### PR TITLE
ISSUE-27397 - Fix phrase handling in widget validation

### LINKED ISSUE #27397: Creating custom widget instance validation is weird due to controller type mismatch
### Summary (*)
See this line of code:

https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Widget/Controller/Adminhtml/Widget/Instance/Validate.php#L22

The function `\Magento\Widget\Model\Widget\Instance::validate()` is type hinted to return either a `\Magento\Framework\Phrase` or a `bool`
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Widget/Model/Widget/Instance.php#L294

This means the `is_string` check is going to fail. This further means that, unless you type cast the phrase to a string, you will **not** ever get a constructive error message out of the widget validation controller.
This isn't a huge issue for the most part with Magento core because of the frontend validation but for those creating custom widget validation rules it will break.

### Examples (*)

```php
$firstResult = __('Test message');
if ($firstResult !== true && is_string($firstResult)) {
    echo 'We have an error!';
}
```
Does not output anything.

### Proposed solution

I think the easiest solution is just to change the validation controller line to the following:
```php
if ($result !== true && (is_string($result) || ($result instanceof \Magento\Framework\Phrase)) {
// ...
```

On Magento sites with custom validation rules we've gotten around this by adding an `afterValidate` plugin to `\Magento\Widget\Model\Widget\Instance` which type casts the result to string (and returns a string for subsequent errors, rather than a phrase).

### PR DESCRIPTION
**Pull request by zaximus84**
### Description (*)
The doc block in \Magento\Widget\Model\Widget\Instance::validate indicates that it can return a boolean or phrase object, but \Magento\Widget\Controller\Adminhtml\Widget\Instance\Validate doesn't handle the phrase object properly. This PR updates the controller to recognize a phrase result value as an error message and output it to the user.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#27397

### Manual testing scenarios (*)
1. Create a custom widget type (in code).
2. Ensure that the widget class implements the validate() method and returns an instance of \Magento\Framework\Phrase.
3. In admin, go to Content > Widgets.
4. Click Add Widget.
5. Select the custom widget type and save.
6. Instead of saving, an error message should appear with the text from the widget's validate method.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zaximus84** [comment]
@magento run all tests

File: app/code/Magento/Widget/Controller/Adminhtml/Widget/Instance/Validate.php [hunk 1]
```diff
@@ -19,6 +19,9 @@ public function execute()
         $response->setError(false);
         $widgetInstance = $this->_initWidgetInstance();
         $result = $widgetInstance->validate();
+        if ($result instanceof \Magento\Framework\Phrase) {
+            $result = (string) $result;
+        }
         if ($result !== true && is_string($result)) {
```
Comment (aleron75) [inline app/code/Magento/Widget/Controller/Adminhtml/Widget/Instance/Validate.php]: I suggest changing this into:

```
if ($result !== true && $result instanceof \Magento\Framework\Phrase) {
    $this->messageManager->addError((string)$result);
    // ...
}
```

This way we can avoid the first `if...` and the result would be cleaner.

Let me know, thank you!

Comment (zaximus84) [reply app/code/Magento/Widget/Controller/Adminhtml/Widget/Instance/Validate.php]: It still needs to check if $result is a string, so I was trying to avoid putting an AND and an OR on the same line by isolating the Phrase evaluation. However, I've reformatted it as you suggested.

**Comment by zaximus84** [comment]
@magento run all tests

**Review by sidolov — CHANGES_REQUESTED** [review]
@zaximus84 please, cover changes with automated test

**Comment by gabrieldagama** [comment]
Risk set to low since the functionality may not affect other areas.

**Comment by engcom-Charlie** [comment]
@zaximus84 I'll take care of the test coverage.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8250](https://jira.corp.magento.com/browse/ENGCOM-8250) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Create a custom widget type (in code).
2. Ensure that the widget class implements the validate() method and returns an instance of \Magento\Framework\Phrase.
3. In admin, go to Content > Widgets.
4. Click Add Widget.
5. Select the custom widget type and save.

**After** :heavy_check_mark: The error message appears with the text from the widget's validate method

Screenshot from 2020-09-24 12-30-22
