### PR TITLE
phpcs fixes for php8

### LINKED ISSUE #33563: Fix issues reported by PHPCompatibility tests
### What should be done
1. Fix issues reported by dev-develop PHPCompatibility check:
 ```java
 composer config repositories.phpcompatibility vcs "https://github.com/PHPCompatibility/PHPCompatibility"
 composer config minimum-stability dev
 composer require phpcompatibility/php-compatibility:dev-develop
 ./vendor/bin/phpcs -p . --standard=PHPCompatibility
 ```
1. Check the areas not yet covered by PHPCompatibility on develop branch:

<https://github.com/PHPCompatibility/PHPCompatibility/issues/809>
1. The checks should be done for all Magento repositories:

 - < > <https://github.com/magento/magento2>
 - < > <https://github.com/magento/partners-magento2ee>
 - < > <https://github.com/magento/partners-magento2b2b>
 - < > <https://github.com/magento/partners-magento2-infrastructure>
 - < > <https://github.com/magento/inventory>
 - < > <https://github.com/magento/magento2-page-builder>
 - < > <https://github.com/magento/magento2-page-builder-ee>
 - < > <https://github.com/magento/security-package>
 - < > <https://github.com/magento/adobe-stock-integration>
 - < > <https://github.com/magento/adobe-ims>

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
In the scope of this ticket https://github.com/magento/magento2/issues/33563, areas not yet covered by PHPCompatibility was checked. Issues reported by phpcs tool were checked.

This PR fixes relevant issues found by phpcs tool, and non-covered areas (note: some areas cannot be checked manually, e.g. "Saner string to number comparison").

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/597

### Related Issues (if relevant)
1. magento/magento2#33563

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by ihor-sviziev — APPROVED** [review]

File: dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php [hunk 1]
```diff
@@ -1024,11 +1024,23 @@ private function createEcKeys(): array
...
+     * @param mixed $resource
+     *
+     * @return void
+     */
+    private function freeResource($resource): void
+    {
+        if (\is_resource($resource) && (version_compare(PHP_VERSION, '8.0') < 0)) {
+            openssl_free_key($resource);
+        }
+    }
```
Comment (Den4ik) [inline dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php:1045]: I believe that we can move this method into `trait` and use in both files
`lib/internal/Magento/Framework/Jwt/JwkFactory.php` and `dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php`

**Review by Den4ik — CHANGES_REQUESTED** [review]
@karyna-tsymbal-atwix Please look at my comment

File: dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php (hunk 1 above)
Comment (andrewbess) [reply dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php:1045]: Hello @Den4ik 
Thank you for your notice.
I think creating a new class, a new trait to cover only two places in the Magento is overkill.
We checked all possible repositories of Magento.
There are only 2 places when function openssl_free_key() is called.
The both places you can see in this PR.

Comment (Den4ik) [reply dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php:1045]: Ok

Comment (Den4ik) [reply dev/tests/integration/testsuite/Magento/Framework/Jwt/JwtManagerTest.php:1045]: I do not consider using the trait as overkill.

But your opinion is also important and may be differ from mine.

**Comment by andrewbess** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please fix failing tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Functional Tests EE

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@karyna-tsymbal-atwix @andrewbess Could you pay attention to static test? Failed test is not directly related to this PR, but looks like failed due to latest updates in platform-health.

**Comment by andrewbess** [comment]
@magento run Magento Health Index, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B, Static Tests, Unit Tests, WebAPI Tests, Semantic Version Checker

File: dev/tests/static/testsuite/Magento/Test/Legacy/ObsoleteCodeTest.php [hunk 2]
```diff
@@ -210,7 +210,7 @@ protected function _testObsoleteClasses($content)
         foreach (self::$_classes as $row) {
             list($class, , $replacement) = $row;
             $this->_assertNotRegExp(
-                '/[^a-z\d_]' . preg_quote($class, '/') . '[^a-z\d_\\\\]/iS',
+                '/[^a-z\d_\$]' . preg_quote($class, '/') . '[^a-z\d_\\\\]/iS',
```
Comment (ihor-sviziev) [inline dev/tests/static/testsuite/Magento/Test/Legacy/ObsoleteCodeTest.php:213]: could you explain this change?

**Comment by andrewbess** [comment]
@magento run Database Compare, Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, WebAPI Tests

File: dev/tests/static/testsuite/Magento/Test/Legacy/ObsoleteCodeTest.php (hunk 2 above)
Comment (andrewbess) [reply dev/tests/static/testsuite/Magento/Test/Legacy/ObsoleteCodeTest.php:213]: Hello @ihor-sviziev 
Thank you for your question.
This part of the `legacy` test was incorrect.
We had a problem in class `Magento\Framework\Webapi\Rest\Request\Deserializer\Xml` with param in constructor `$xmlParser` because `XMLParser` class is obsolete.
So, the regular expression was not fully correct.
We fixed it. 

cc @Den4ik

**Review by eduard13 — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]
