### PR TITLE
Resolve Incorrect base currency in order grid for historical orders issue 23805

### LINKED ISSUE #23805: Incorrect base currency in order grid for historical orders
### Preconditions
1. Magento 2.3.1

### Steps to reproduce 
1. Create an order
2. Change store base currency
3. Go to order grid screen. New base currency is shown instead of base currency in which the order was placed in. 

### Expected result 
1. Old base currency should be shown

### Actual result (*)
1. Newly configured base currency is shown instead of base currency in which the order was placed in.

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

Resolve magento/magento2#23805: Incorrect base currency in order grid for historical orders

Problem: The Order Grid display the **current currency** in the Order Grid Not **the currency which the order was placed.**

Function **$this->priceFormatter->format** check if the currency code **doesn't have rate**, it will automatically switch to the base currency. **The rate is not necessary because the order was created.** So we can not use this function. Because the **Order was placed**, we can not change the currency code of the **OLD OLDER**

Solution: Use the **format** function of class "**Magento\Directory\Model\Currency**" . It is also the same class which **Magento\Sales\Model\Order** used.

### Fixed Issues (if relevant)

1. magento/magento2#23805: Incorrect base currency in order grid for historical orders

### Manual testing scenarios (*)

1. Create an order with the base currency (USD)
2. Change store base currency (to EUR)
3. Go to order grid screen. 
**Result: Old base currency should be shown** (USD) 

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by edenduong** [comment]
@magento give me 2.3-develop instance

**Comment by magento-engcom-team** [comment]
Hi @edenduong. Thank you for your request. I'm working on Magento 2.3-develop instance for you

**Comment by magento-engcom-team** [comment]
Hi @edenduong, here is your [Magento instance](https://i-23817-2-3-develop.instances.magento-community.engineering).
Admin access: [https://i-23817-2-3-develop.instances.magento-community.engineering/admin](https://i-23817-2-3-develop.instances.magento-community.engineering/admin)
Login: `admin` Password: `123123q`
Instance will be terminated in up to 3 hours.

File: app/code/Magento/Sales/Ui/Component/Listing/Column/Price.php [hunk 1]
```diff
@@ -51,13 +53,9 @@ public function prepareDataSource(array $dataSource)
...
             foreach ($dataSource['data']['items'] as & $item) {
                 $currencyCode = isset($item['base_currency_code']) ? $item['base_currency_code'] : null;
-                $item[$this->getData('name')] = $this->priceFormatter->format(
-                    $item[$this->getData('name')],
-                    false,
-                    null,
-                    null,
-                    $currencyCode
-                );
+                $basePurchaseCurrency = $this->currencyFactory->create()->load($currencyCode);
```
Comment (aleron75) [inline app/code/Magento/Sales/Ui/Component/Listing/Column/Price.php]: Since the `load()` method is deprecated, what do you think about using the following code to initialize the `$basePurchaseCurrency` variable?

```
$basePurchaseCurrency = $this->currencyFactory->->create(['data' => ['currency_code' => $currencyCode]]);
```

File: app/code/Magento/Sales/Ui/Component/Listing/Column/PurchasedPrice.php [hunk 2]
```diff
@@ -51,14 +53,9 @@ public function prepareDataSource(array $dataSource)
...
                 $currencyCode = isset($item['order_currency_code']) ? $item['order_currency_code'] : null;
-                $item[$this->getData('name')] =
-                    $this->priceFormatter->format(
-                        $item[$this->getData('name')],
-                        false,
-                        null,
-                        null,
-                        $currencyCode
-                    );
+                $purchaseCurrency = $this->currencyFactory->create()->load($currencyCode);
```
Comment (aleron75) [inline app/code/Magento/Sales/Ui/Component/Listing/Column/PurchasedPrice.php]: Refer to my comment above related to the `load()` method.

File: app/code/Magento/Sales/Ui/Component/Listing/Column/Price.php (hunk 1 above)
Comment (edenduong) [reply app/code/Magento/Sales/Ui/Component/Listing/Column/Price.php]: image

It is not deprecated. Please check it.

File: app/code/Magento/Sales/Ui/Component/Listing/Column/PurchasedPrice.php (hunk 2 above)
Comment (edenduong) [reply app/code/Magento/Sales/Ui/Component/Listing/Column/PurchasedPrice.php]: image

It is not deprecated. Please check it.

**Comment by edenduong** [comment]
Hello @aleron75,

Thank you for your reviewing. But as I see, the Load() function in Currency Model is different from other model, and it is not deprecated.

Please check it.

Thanks.

File: app/code/Magento/Sales/Ui/Component/Listing/Column/Price.php (hunk 1 above)
Comment (aleron75) [reply app/code/Magento/Sales/Ui/Component/Listing/Column/Price.php]: Sorry, my fault, I didn't explain it well.

It's deprecated in the `\Magento\Framework\Model\AbstractModel` parent and my IDE also indicated it as deprecated.

> @deprecated 100.1.0 because entities must not be responsible for their own loading.             
Service contracts should persist entities. Use resource model "load" or collections to implement service contract model loading operations.                                                      

Actually, the `\Magento\Directory\Model\Currency`'s `load()` method doesn't really load from a Resource Model.

It was just a suggestion, for me it's ok to keep going as you did.

**Review by aleron75 — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @aleron75, thank you for the review.
[ENGCOM-5529](https://jira.corp.magento.com/browse/ENGCOM-5529) has been created to process this Pull Request
:eight_spoked_asterisk: @aleron75, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed

**Comment by edenduong** [comment]
@magento-engcom-team: Could I receive the "Award: bug fix" ? Thank you :)
