### PR TITLE
Drop indexer changelog tables on mview unsubscribe

### LINKED ISSUE #729: [Investigation] Indexers stuck after redeploy
### Preconditions
Looks like after killing processes before deploy phase some indexers can be stuck.

There is more information from community slack: https://magentocommeng.slack.com/archives/C8CBB6K9V/p1589463049184700

### Steps to reproduce

1. Try to redeploy when some indexer works

### Expected result

1. Indexers can be run

### Actual result

1. Some indexers can be stuck

Internal ticket: MCLOUD-5992

### LINKED ISSUE #29789: [Issue] Drop indexer changelog tables on mview unsubscribe
###### (i) This ticket is created automatically based on a verified GitHub issue.        
{panel}
***If you are starting to work on this Jira ticket, please notify issue reporter and authors of related community pull requests (if any) that you are going to work on this issue:***
  1.  *Assign [#29789](https://github.com/magento/magento2/issues/29789) issue to yourself on Magento GitHub*
  2.  *Add comment "Internal Magento team is working on this issue right now."*
{panel}
This issue is automatically created based on existing pull request: magento/magento2#25859: Drop indexer changelog tables on mview unsubscribe ~~-------~~ ######Description (*)
This pull request will remove the unused changelog tables when changing an index from 'update on schedule' to 'update on save'.

From what I can tell, this was the case before 6ae3c48d4df28a20590f7fe5d5deca472fd06084 was merged. I have tried to avoid any regressions here by marking the index as invalid when dropping the table, to catch any entries which might have otherwise been missed. It seems that 6ae3c48d4df28a20590f7fe5d5deca472fd06084 only protects missed changelog entries if the index is switched back to 'update on schedule'. The change introduced here solves that problem by always performing a full index (via normal minutely cron).

######Preconditions (*)
1. Magento 2.4-develop

######Fixed Issues (if relevant)
I am not aware of any open issues regarding this fix.

######Steps to reproduce (*)
1. Set indexes to 'update on schedule'
2. Make a change which will trigger an entry in the changelog table (eg, update product name in admin)
3. Wait for normal minutely cron to run index
4. Observe data in `version*id` column in `mview*state` table.
5. Change indexes to 'update on save'
6. Observe data in `version*id` column in `mview*state` table.
7. Note that all changed indexes are now 'invalid' and will be fully indexed via normal minutely cron.

######Expected result (*)
all changed indexes are now 'invalid'

######Actual result (*)
all changed indexes are now 'valid'

######Questions or comments
I am not confident that I have fully covered all changes here in unit tests. Please may I have some advise as to how I might need to adjust the unit tests to ensure no regressions.

######Contribution checklist (*)
 - <x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ > All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description (*)
This pull request will remove the unused changelog tables when changing an index from 'update on schedule' to 'update on save'.

From what I can tell, this was the case before 6ae3c48d4df28a20590f7fe5d5deca472fd06084 was merged. I have tried to avoid any regressions here by marking the index as invalid when dropping the table, to catch any entries which might have otherwise been missed. It seems that 6ae3c48d4df28a20590f7fe5d5deca472fd06084 only protects missed changelog entries if the index is switched back to 'update on schedule'. The change introduced here solves that problem by always performing a full index (via normal minutely cron).

### Fixed Issues
- Fixes https://github.com/magento/ece-tools/issues/729
-  resolves magento/magento2#29789: Drop indexer changelog tables on mview unsubscribe

### Manual testing scenarios (*)
1. Set indexes to 'update on schedule'
1. Make a change which will trigger an entry in the changelog table (eg, update product name in admin)
1. Wait for normal minutely cron to run index
1. Observe data in `version_id` column in `mview_state` table.
1. Change indexes to 'update on save'
1. Observe data in `version_id` column in `mview_state` table.
1. Note that all changed indexes are now 'invalid' and will be fully indexed via normal minutely cron.

### Questions or comments
I am not confident that I have fully covered all changes here in unit tests. Please may I have some advice as to how I might need to adjust the unit tests to ensure no regressions.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29789: Drop indexer changelog tables on mview unsubscribe

### CODE REVIEW

File: app/code/Magento/Indexer/Setup/RecurringData.php [hunk 1]
```diff
@@ -49,7 +49,8 @@ public function install(ModuleDataSetupInterface $setup, ModuleContextInterface
         foreach (array_keys($this->configInterface->getIndexers()) as $indexerId) {
             $indexer = $this->indexerFactory->create()->load($indexerId);
             if ($indexer->isScheduled()) {
-                $indexer->getView()->unsubscribe()->subscribe();
+                $indexer->setScheduled(false);
```
Comment (kandy) [inline app/code/Magento/Indexer/Setup/RecurringData.php]: Please test that this not cause change log cleanup

Comment (fredden) [reply app/code/Magento/Indexer/Setup/RecurringData.php]: Yes, this will cause the changelog tables to be removed as it will call `$indexer->getView()->unsubscribe()` internally. Please can you help me understand the purpose of this recurring setup task if that behaviour is not desired?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @fredden,
Could you review and fix failing tests?

**Comment by ihor-sviziev** [comment]
@magento create issue

**Comment by fredden** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Risk: high since the changes may affect the caching mechanism.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8165](https://jira.corp.magento.com/browse/ENGCOM-8165) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenario
1. Go to **System - Index Management** 
2. **Select All** indexers from _Mass Actions_and select **Update by Schedule** from _Actions_ 
3. Click **Submit**
the indexers Status is updated, run `php bin/magento indexer:status`
status1
4. Go to **Catalog - Products** and **Edit** an existing _Product Name_. **Save** product
5. Run `php bin/magento indexer:status`
status2
6. Wait for normal minutely cron to run index or run `php  bin/magento cron:run`
7. Check the indexer status `php bin/magento indexer:status`
status3
8. Go to **System - Index Management** 
9. **Select All** indexers from _Mass Actions_and select **Update by Schedule** from _Actions_. Click **Submit**
10. Check the indexers Status, run `php bin/magento indexer:status`

**BEFORE** switching to the PR the indexer _Status_ was **Ready**
rei_not_required

**AFTER** switching to the PR the indexer _Status_ was **Reindex required**
rei_required

**Comment by gabrieldagama** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@gabrieldagama is there any reasons why this PR isn't getting merged?

**Comment by gabrieldagama** [comment]
@ihor-sviziev Yes, we are having an internal problem when trying to deliver this PR, there is an internal ticket to solve that, once that is resolved we can proceed with the merge.

**Comment by fredden** [comment]
@gabrieldagama do I need to resolve the conflicts that are now showing on this pull request? Please can you provide an update on when this will be merged.

**Comment by ihor-sviziev** [comment]
@fredden, yeah, could you resolve the conflict?

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi @fredden, the problem mentioned before was fixed, but as this PR is low priority we will be processing and delivering high priority pull request first. This will be processed as soon as possible considering the priorities.

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

File: app/code/Magento/Indexer/Setup/RecurringData.php (hunk 1 above)
Comment (fredden) [reply app/code/Magento/Indexer/Setup/RecurringData.php]: Further to this, I have discovered (and documented in a code comment) the purpose of this line. I've preserved the behaviour here - no changelog tables will be cleaned up when running this recurring setup script.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8165](https://jira.corp.magento.com/browse/ENGCOM-8165) has been created to process this Pull Request

**Review by torhoehn — APPROVED** [review]

File: lib/internal/Magento/Framework/Mview/View.php [hunk 2]
```diff
@@ -219,21 +219,32 @@ public function subscribe()
...
 
     /**
-     * Remove subscriptions
-     *
-     * @return ViewInterface
-     * @throws Exception
+     * @inheritDoc
      */
-    public function unsubscribe()
+    public function unsubscribe(bool $dropTable = true): ViewInterface
```
Comment (kandy) [inline lib/internal/Magento/Framework/Mview/View.php:224]: Make sense to have `false` as default value to preserve BC

Comment (fredden) [reply lib/internal/Magento/Framework/Mview/View.php:224]: Hi @kandy. I'm assuming that by 'BC' you mean "backwards compatibility."

If the parameter was required (ie, had no default value), it would break backwards compatibility. As the parameter has a default value, anything that calls this method without any arguments will continue to work. I therefore see this as being compatible with previous code, and not breaking backwards compatibility at a code level.

I think you're trying to ask for this method to behave the same as it does currently when called without any arguments. This parameter only exists so that it can be used in the recurring setup script where the intention is to recreate all triggers. If it weren't for that requirement, the parameter would not exist at all.

Can you provide a use-case where it would be useful to keep the changelog table after calling `mview->unsubscribe()`?

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B , Functional Tests EE , Semantic Version Checker

**Comment by engcom-Lima** [comment]
This PR is already QA passed  referring [QA pass comment above](https://github.com/magento/magento2/pull/25859#issuecomment-700686833). Builds are failed hence, moving this PR to extended testing.

**Comment by engcom-Lima** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
@engcom-Lima as the above mentioned QA [testing](https://github.com/magento/magento2/pull/25859#issuecomment-700686833) has been done long back, requesting you to go through the QA process again. Hence moving it back to Ready For Testing.

Thank you!

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Go to System - Index Management
2. Select All indexers from _Mass Actions_ and select **`Update by Schedule`** from Actions
3. Click Submit
4. The indexers Status is updated, run `php bin/magento indexer:status`
5. Go to Catalog - Products and Edit an existing Product Name. Save product
6. Run `php bin/magento indexer:status`
7. Wait for normal minutely cron to run index or run `php  bin/magento cron:run`
8. Check the indexer status `php bin/magento indexer:status`
9. Go to System - Index Management
10. Select All indexers from _Mass Actions_ and select **`Update on save`** from Actions. Click Submit
11. Check the indexers Status, run `php bin/magento indexer:status`

**Before:** :heavy_multiplication_x:  Switching to the PR the indexer Status was **Ready**
Screenshot 2023-01-17 at 6 16 25 PM


**After:** :heavy_check_mark:  Switching to the PR the indexer Status was **Reindex required**

Screenshot 2023-01-19 at 2 57 55 PM

Builds are failed. Hence, moving this PR to extended testing.

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
Hi @fredden,

Thank you for your contribution!

The functional test failures in B2B and EE are different from the last two runs.
Functional tests B2B: run1
Screenshot 2023-01-24 at 12 23 42 PM
run2
Screenshot 2023-01-24 at 12 31 14 PM

Functional tests EE: run1
Screenshot 2023-01-24 at 12 34 05 PM

run2
Screenshot 2023-01-24 at 12 35 38 PM


Raised internal approval request JIRA [ticket](https://jira.corp.adobe.com/browse/AC-7798) for SVC test failure. Waiting for the approvals.

Thank you!

**Comment by engcom-Delta** [comment]
Hi @fredden,
We will let you know as soon as we receive jira approval.
Thanks

**Comment by fredden** [comment]
@engcom-Delta please can you provide an update on this pull request?

**Comment by engcom-Charlie** [comment]
Hi @fredden, we are still waiting for the approvals. Once we got all the required approvals from the internal team, we will proceed further on this PR.

Thank you!

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR to review hence moving it back to Pending Approval.

**Comment by fredden** [comment]
@engcom-Charlie, please can you provide an update on this pull request.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`**

**Manual testing scenario:**

1.Login to magento admin
2.Go to System - Index Management
3.Select All indexers from Mass Actions and select Update by Schedule from Actions, click submit.
4.The indexers Status is updated, run php bin/magento indexer:status
5.Go to Catalog - Products and Edit an existing Product Name. Save product
6.Run php bin/magento indexer:status
7.Wait for normal minutely cron to run index or run php  bin/magento cron:run
8.Check the indexer status php bin/magento indexer:status
9.Go to System - Index Management
10.Select All indexers from Mass Actions and select Update on save from Actions, click Submit
11.Check the indexers Status, run php bin/magento indexer:status

**Before:** :heavy_multiplication_x: 

Screenshot 2024-03-27 at 5 20 46 PM

Screenshot 2024-03-27 at 5 20 54 PM

Screenshot 2024-03-27 at 5 21 18 PM

Screenshot 2024-03-27 at 5 21 28 PM

Screenshot 2024-03-27 at 5 22 09 PM

Screenshot 2024-03-27 at 5 23 05 PM

Screenshot 2024-03-27 at 5 23 14 PM

Screenshot 2024-03-27 at 5 24 37 PM

Screenshot 2024-03-27 at 5 25 19 PM

Screenshot 2024-03-27 at 5 25 28 PM

Screenshot 2024-03-27 at 5 25 44 PM



**After:** :heavy_check_mark:  

Screenshot 2024-03-27 at 6 38 28 PM

Screenshot 2024-03-27 at 6 38 44 PM

Screenshot 2024-03-27 at 6 38 53 PM

Screenshot 2024-03-27 at 6 39 12 PM

Screenshot 2024-03-27 at 6 40 01 PM

Screenshot 2024-03-27 at 6 40 11 PM

Screenshot 2024-03-27 at 6 41 38 PM

Screenshot 2024-03-27 at 6 41 49 PM

Screenshot 2024-03-27 at 6 42 12 PM


Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests EE ,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests CE,Functional Tests EE,Functional Tests B2B failure are different on last two run on same commit.

Functional Tests CE
Run1
ce-25859

Run2
Screenshot 2024-03-28 at 1 00 16 PM

Functional Tests EE
Run1
ee-25859

Run2
Screenshot 2024-03-28 at 1 00 25 PM

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests ,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B
