### PR TITLE
Fix #29194 Update tier price div visibility

### LINKED ISSUE #29194: CSS for tier prices block still visible when there are no tier prices
#26081 
# Preconditions (*)
Magento 2.4

### Steps to reproduce (*)
1. Create a configurable product and associate 1 simple product with no tier pricing and 1 simple product with tier pricing
2. Style the tier prices block with a background or border (for example `border: aqua; background: #99cfff;`)
3. Toggle between the 2 simple products. For the product with no tier pricing, the content disappears but the CSS styling remains (e.g. in Magento Blank theme, there is an empty box with a gray background).

Screenshot_46
Screenshot_47

### Expected result (*)
1. The tier price block, including associated CSS, should disappear from the frontend when choosing a simple product that doesn't have tier prices.

### Actual result (*)
1. The tier price block, including CSS styling such as background or border, is visible even when there are no tier prices to display.
Screenshot_47

**Additional information**
Even when there are no tier prices, any CSS applied to tier prices block are visible on the frontend.

A simple edit to _displayTierPriceBlock function in configurable.js can fix this problem.
**Solution:**

in _displayTierPriceBlock function of configurable.js, change the following if statement:

```
            if (typeof optionId != 'undefined' &&
                this.options.spConfig.optionPrices[optionId].tierPrices != [] // eslint-disable-line eqeqeq
            ) 
```

to the following, which includes a check for tier prices array with 0 length:

```
            if (typeof optionId != 'undefined' &&
                this.options.spConfig.optionPrices[optionId].tierPrices != [] && // eslint-disable-line eqeqeq
                this.options.spConfig.optionPrices[optionId].tierPrices.length > 0
            ) 
```

---

- [S4 ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by srsathish92**
### Description (*)
This PR to hide tier price div on configurable products when the drop down option (simple product) has no tier prices.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29194

### Manual testing scenarios (*)
Please see the steps to reproduce on #29194 

### Questions or comments
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento run Functional Tests B2B

File: app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js [hunk 1]
```diff
@@ -740,10 +740,11 @@ define([
          * @private
          */
         _displayTierPriceBlock: function (optionId) {
-            var options, tierPriceHtml;
+            var options, tierPriceHtml, tierPrices = this.options.spConfig.optionPrices[optionId].tierPrices;
 
             if (typeof optionId != 'undefined' &&
-                this.options.spConfig.optionPrices[optionId].tierPrices != [] // eslint-disable-line eqeqeq
+                tierPrices != [] && // eslint-disable-line eqeqeq
```
Comment (krzksz) [inline app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js]: Thank you for your contribution!

Could you please change this check while we're at it? Right now it doesn't make any sense. I believe that we are trying to check here if `tierPrices` is an array so `_.isArray` could be used instead. This will also allow us to disable this ESLint comment.

**Review by krzksz — CHANGES_REQUESTED** [review]

File: app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js (hunk 1 above)
Comment (srsathish92) [reply app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js]: sure, will update

Comment (srsathish92) [reply app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js]: I have updated. Can you please review now?

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento run Functional Tests B2B, Unit Tests

**Review by krzksz — DISMISSED** [review]

**Comment by krzksz** [comment]
Hey @srsathish92, thanks for contribution!

Would you be able to cover your change with automatic tests so we are sure this error doesn't pop up in the future?

**Comment by magento-engcom-team** [comment]
Hi @krzksz, thank you for the review.
[ENGCOM-7948](https://jira.corp.magento.com/browse/ENGCOM-7948) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @srsathish92  .
     Due to [Magento Definition of Done](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html) all code must be covered by tests. Please cover your fix by automated test.
Thanks!

**Comment by srsathish92** [comment]
@engcom-Alfa @krzksz Sure, I will update test case

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by srsathish92** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
Hi @krzksz . Could you review the latest changes? 
Thanks!

**Review by lbajsarowicz — APPROVED** [review]
✔️ When it comes to MFTF tests - these are fine.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7948](https://jira.corp.magento.com/browse/ENGCOM-7948) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x: The tier price block, including CSS stylings such as background or border, is visible even when there are no tier prices to display.

Peek 2020-07-23 15-51

**After:** :heavy_check_mark:  The tier price block, including associated CSS,  disappeared from the frontend when choosing a simple product that doesn't have tier prices.

Peek 2020-08-17 13-17
