### PR TITLE
Fix a PHP error being thrown on a Magento error being thrown

### LINKED ISSUE #32819: [Issue] Fix a PHP error being thrown on a Magento error being thrown
This issue is automatically created based on existing pull request: magento/magento2#32814: Fix a PHP error being thrown on a Magento error being thrown

---------

### Description (*)

I ran into a small problem with the product media (because my pub/media wasn't writable). But I did not get the actual error that is thrown, I got a PHP error because 'directory' was not set (as you can see by my fix).
I thought, why not have my first contribution be a simple fix

### Related Pull Requests

-

### Fixed Issues (if relevant)

-

### Manual testing scenarios (*)

1. Have a simple magento shop with X (might as well be 1) product *including* images
2. Change the pub/media to incorrect permissions/owners
3. Try to visit the product detail page in the backend

### Questions or comments

-

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by mariusjp**
### Description (*)

I ran into a small problem with the product media (because my pub/media wasn't writable). But I did not get the actual error that is thrown, I got a PHP error because 'directory' was not set (as you can see by my fix).
I thought, why not have my first contribution be a simple fix.

PHP: 7.4.15
Magento: 2.4.2

### Related Pull Requests

-

### Fixed Issues (if relevant)

-

### Manual testing scenarios (*)

1. Have a simple magento shop with X (might as well be 1) product *including* images
2. Change the pub/media to incorrect permissions/owners
3. Try to visit the product detail page in the backend

Screenshot of the PHP Notice in stead of the actual error being thrown (also in the exception.log)
image

### Questions or comments

-

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#32819: Fix a PHP error being thrown on a Magento error being thrown

### CODE REVIEW

**Comment by MJTheOne** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Not sure why we need change the pub/media to incorrect permissions/owners for reproduce
What if we set correct permissions at first
Just curiosity

**Comment by MJTheOne** [comment]
> Not sure why we need change the pub/media to incorrect permissions/owners for reproduce
> What if we set correct permissions at first
> Just curiosity

After a deployment I somehow ended up with incorrect permissions, and got the error "Undefined index 'directory'" in stead of the actual error "Unable to save.."

To be fair, this is probably not a situation that will happen often. Doesn't take away the fact the code is incorrect in assuming 'directory' is set as index on $file.

**Comment by mrtuvn** [comment]
Can you add image screen show issue errors ? Or video records if possible
That will make issue clear for QA can reproduce

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by mrtuvn** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by MJTheOne** [comment]
image

PHP: 7.4.15
Magento: 2.4.2

**Comment by mrtuvn** [comment]
Can you update infor in ticket description

**Comment by MJTheOne** [comment]
> Can you update infor in ticket description

Done!

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@mrtuvn I believe that covering this case with a test would be quite easy, so it's better to cover it.

@MJTheOne, will you be able to cover your change with a simple unit test?

**Comment by mrtuvn** [comment]
Agreed! Let's cover its with automated test

**Comment by MJTheOne** [comment]
I'll get on it asap!

**Comment by MJTheOne** [comment]
I'm sorry it's taking me a while. Having some trouble with how this is set up. The tests want to run "setup:install", which I find weird. Also been a bit busy. Will try to update this week!

**Comment by MJTheOne** [comment]
Unit test added! Took me a while to figure out how this is set up. It's not like I have no UnitTest experience, just overlooked a few things so it was quit confusing at the start.

**Comment by MJTheOne** [comment]
@magento run Unit Tests

**Comment by MJTheOne** [comment]
@magento run all

**Comment by MJTheOne** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, WebAPI Tests
@mrtuvn pls review it again

**Comment by mrtuvn** [comment]
Changes look good to me but steps for reproduce problem seem not easy to reproduce! Can you able to reproduce issue in latest code ? @MJTheOne May you can reproduce in latest code (2.4-develop)

**Comment by MJTheOne** [comment]
> Changes look good to me but steps for reproduce problem seem not easy to reproduce! Can you able to reproduce issue in latest code (2.4-develop) ? @MJTheOne

Sorry for the late reply, have been quite busy. Yes I can reproduce it because it's not fixed yet.. This PR handles the fix.
I realise this isn't your run of the mill problem, but it occurred when I had incorrect permissions/owners set to the public/media folder after a deploy (which was fully my own mistake, not something Magento (core) did incorrect).
It's not something many people will encounter, but when they do, they have no clue what was wrong because the error being thrown is an actual PHP error because of the assumption in the variable $file and it having the key 'directory'

**Comment by mrtuvn** [comment]
@magento run Functional Tests CE

**Comment by mrtuvn** [comment]
Failed test seem not related with these changes
Current code change seem ok with me. But i can't clear reproduce issue from my end with latest code (used warden.dev for local enviroment). Only issue reported by author

**Review by mrtuvn — APPROVED** [review]
Thanks you for contribution

**Comment by magento-engcom-team** [comment]
Hi @mrtuvn, thank you for the review.
[ENGCOM-9144](https://jira.corp.magento.com/browse/ENGCOM-9144) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@MJTheOne thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by MJTheOne** [comment]
I'll give it a try hopefully today! And give you the exact steps I did!

**Comment by MJTheOne** [comment]
Ok, I'm starting to think it has to do with the combination of the assumption in the Exception AND a module I'm using for S3 storage of the images. I can't seem to reproduce it locally just like @mrtuvn.

But on my server I can very easily reproduce it (just set incorrect user/group/permissions on the pub/media dir) it actually makes no sense because the images aren't on the server (well they are, but they are not being served from the server), but those steps are exactly what reproduced the problem..

Such a shame my first contribution turns out to be "meh" 😓

**Review by Den4ik — APPROVED** [review]
I remember that I saw similar PR but currently could not find it.
✅ Approving this PR

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9144](https://jira.corp.magento.com/browse/ENGCOM-9144) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+        $this->_storageHelperMock = $this->createMock(Database::class);
+        $this->_mediaHelperMock = $this->createMock(Media::class);
+        $this->_fileUtilityMock = $this->createMock(\Magento\MediaStorage\Model\ResourceModel\File\Storage\File::class);
+
+        $this->_file = new File(
+            $this->_loggerMock,
+            $this->_storageHelperMock,
+            $this->_mediaHelperMock,
+            $this->_fileUtilityMock
+        );
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        $this->loggerMock = $this->getMockForAbstractClass(LoggerInterface::class);
        $this->storageHelperMock = $this->createMock(Database::class);
        $this->mediaHelperMock = $this->createMock(Media::class);
        $this->fileUtilityMock = $this->createMock(\Magento\MediaStorage\Model\ResourceModel\File\Storage\File::class);

        $this->file = new File(
            $this->loggerMock,
            $this->storageHelperMock,
            $this->mediaHelperMock,
            $this->fileUtilityMock
        );
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+
+    /**
+     * @var DateTime
+     */
+    protected $_mediaHelperMock;
+
+    /**
+     * @var \Magento\MediaStorage\Model\ResourceModel\File\Storage\File
+     */
+    protected $_fileUtilityMock;
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
    /**
     * @var File
     */
    private $file;

    /**
     * @var Media
     */
    private $loggerMock;

    /**
     * @var Database
     */
    private $storageHelperMock;

    /**
     * @var DateTime
     */
    private $mediaHelperMock;

    /**
     * @var \Magento\MediaStorage\Model\ResourceModel\File\Storage\File
     */
    private $fileUtilityMock;
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+            $this->_loggerMock,
+            $this->_storageHelperMock,
+            $this->_mediaHelperMock,
+            $this->_fileUtilityMock
+        );
+    }
+
+    protected function tearDown(): void
+    {
+        unset($this->_file);
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        unset($this->file);
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    public function testSaveFileWithWrongFileFormat(): void
+    {
+        $this->expectException(LocalizedException::class);
+        $this->expectExceptionMessage('Wrong file info format');
+        $this->_file->saveFile([]);
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        $this->file->saveFile([]);
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    public function testSaveFileUnsuccessfullyWithMissingDirectory()
+    {
+        $this->_fileUtilityMock
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        $this->fileUtilityMock
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 6]
```diff
@@ -0,0 +1,104 @@
...
+            ->expects($this->once())
+            ->method('saveFile')
+            ->willThrowException(new Exception());
+
+        $this->expectException(LocalizedException::class);
+        $this->expectExceptionMessage('Unable to save file "filename.ext" at "filename.ext"');
+        $this->_file->saveFile([
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        $this->file->saveFile([
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 7]
```diff
@@ -0,0 +1,104 @@
...
+            'filename' => 'filename.ext',
+            'content' => 'content',
+        ]);
+    }
+
+    public function testSaveFileUnsuccessfullyWithoutMissingDirectory()
+    {
+        $this->_fileUtilityMock
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        $this->fileUtilityMock
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 8]
```diff
@@ -0,0 +1,104 @@
...
+            ->expects($this->once())
+            ->method('saveFile')
+            ->willThrowException(new Exception());
+
+        $this->expectException(LocalizedException::class);
+        $this->expectExceptionMessage('Unable to save file "filename.ext" at "directory/filename.ext"');
+        $this->_file->saveFile([
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
        $this->file->saveFile([
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+
+        $this->expectException(LocalizedException::class);
+        $this->expectExceptionMessage('Unable to save file "filename.ext" at "filename.ext"');
+        $this->_file->saveFile([
+            'filename' => 'filename.ext',
+            'content' => 'content',
+        ]);
+    }
+
+    public function testSaveFileUnsuccessfullyWithoutMissingDirectory()
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
    public function testSaveFileUnsuccessfullyWithoutMissingDirectory(): void
```

File: app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php [hunk 10]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    public function testSaveFileWithWrongFileFormat(): void
+    {
+        $this->expectException(LocalizedException::class);
+        $this->expectExceptionMessage('Wrong file info format');
+        $this->_file->saveFile([]);
+    }
+
+    public function testSaveFileUnsuccessfullyWithMissingDirectory()
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Test/Unit/Model/File/Storage/FileTest.php]:
```suggestion
    public function testSaveFileUnsuccessfullyWithMissingDirectory(): void
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you make all the properties private, w/o underscore prefix and add return types to all methods?

File: app/code/Magento/MediaStorage/Model/File/Storage/File.php [hunk 11]
```diff
@@ -291,16 +291,16 @@ public function saveFile($file, $overwrite = true)
             && isset($file['content'])
             && !empty($file['content'])
         ) {
-            try {
-                $filename = isset(
-                    $file['directory']
-                ) && !empty($file['directory']) ? $file['directory'] . '/' . $file['filename'] : $file['filename'];
+            $filename = isset(
+                $file['directory']
+            ) && !empty($file['directory']) ? $file['directory'] . '/' . $file['filename'] : $file['filename'];
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Model/File/Storage/File.php]: I think this one is a bit more readable. What do you think?
```suggestion
            $directory = !empty($file['directory'] ?? '') : $file['directory'] . '/' : '';
            $filename = $directory . $file['filename'];
```


Or like this:
```suggestion
            $filename = !empty($file['directory'] ?? '') ? $file['directory'] . '/' . $file['filename'] : $file['filename'];
```

Or even 
```suggestion
            $filename = (!empty($file['directory'] ?? '') ? $file['directory'] . '/' : '') . $file['filename'];
```

**Comment by MJTheOne** [comment]
On it!

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/MediaStorage/Model/File/Storage/File.php [hunk 12]
```diff
@@ -291,16 +291,15 @@ public function saveFile($file, $overwrite = true)
...
+            $directory = !empty($file['directory'] ?? '') ? $file['directory'] . '/' : '';
+            $filename = $directory . $file['filename'];
 
+            try {
                 return $this->_fileUtility->saveFile($filename, $file['content'], $overwrite);
             } catch (\Exception $e) {
                 $this->_logger->critical($e);
                 throw new \Magento\Framework\Exception\LocalizedException(
-                    __('Unable to save file "%1" at "%2"', $file['filename'], $file['directory'])
+                    __('Unable to save file "%1" at "%2"', $file['filename'], $filename)
```
Comment (ihor-sviziev) [inline app/code/Magento/MediaStorage/Model/File/Storage/File.php]: Maybe, now we should pass $directory here?
```suggestion
                    __('Unable to save file "%1" at "%2"', $file['filename'], $directory)
```

Comment (mariusjp) [reply app/code/Magento/MediaStorage/Model/File/Storage/File.php]: Ah yes. I didn't want to change too much of the original workings, but it actually makes more sense to make it clear no directory is present for example? Otherwise the message would be "Unable to save file filename.ext at " that would look weird in my opinion.

Comment (ihor-sviziev) [reply app/code/Magento/MediaStorage/Model/File/Storage/File.php]: ok, let's keep it as is.

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests, Integration Tests, Functional Tests EE, Functional Tests B2B

**Comment by Den4ik** [comment]
Failed Unit test "ui/js/grid/columns/multiselect.Default state - Select no rows" is not related to changes

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9144](https://jira.corp.magento.com/browse/ENGCOM-9144) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by engcom-Hotel** [comment]
Hello @MJTheOne,
Thanks for the contribution!

I have tried to reproduce the issue in Magento version 2.4-develop with the following steps. But unable to reproduce the issue:
1. Setup Magento vanilla instance on local.
2. Create a product from the admin panel with a dummy image. 
3. Change the permission of the pub/media folder recursively using `chmod -R 111 pub/media` command. I have tried other commands as well.
4. Try to access the product detail page from the admin panel. I have also tried to upload an image after changing the permission but the appropriate error message has appeared in that case.

The product edit page is open without any error. 

I have also applied some logs in `app/code/Magento/MediaStorage/Model/File/Storage/File.php` to check if the `saveFile` function is called or not. But the logs are not printed in the debug.log file. Please have a look at the below screenshot:

Screenshot 2021-08-17 at 10 57 26 PM

Please let us know if we missed any steps in order to reproduce the issue.

Thanks

**Comment by MJTheOne** [comment]
Hey @engcom-Hotel

As discussed before. I *think* it has to do with an S3 module I have installed, because I could very easily reproduce it on my server but not on a fresh install. And as we all (kinda silently) agreed upon, the assumption the code makes in the Exception, even though it's extensively checked before the Exception, is incorrect, hence why the PR wasn't closed.
But as you can see by my own screenshot the situation does occur, but in a very unique situation apparently.

**Comment by engcom-Hotel** [comment]
✔️ QA Passed

Hello @MJTheOne,

Thanks for the contribution!

I am now able to reproduce the issue. But in order to reproduce, I need to make some changes in code level. Please have a look at my description below:

1. Change the `Media Storage` as `Database`:
image

2. Go to the product edit page, and open the content tab, click on the `Insert/Edit Image` icon, this will popups the below window:
image


3. Now click on the `Select Images` icon, this will popups a new window as follows:
image

4. Check above screenshot having some error message, that is because of some code changes in order to reproduce the issue, below screenshot can refer for code changes:
Screenshot 2021-08-30 at 5 17 11 PM

5. Please find below the logs where the error is visible:

**Before** ✖️ 
Screenshot 2021-08-30 at 5 19 56 PM

But after deploying this branch and make the same changes in code, the PHP error is not visible in logs:
**After** ✔️ 

Screenshot 2021-08-30 at 5 25 25 PM

**Tested all the manual scenarios, no impact on regression testing.** 

Thanks

**Comment by MJTheOne** [comment]
@magento run all tests
