### PR TITLE
30349: Product filter with category_id does not work as expected - fi…

### LINKED ISSUE #29720: GraphQl products query returns missing items on using `category_id` filter with `in` array
### Preconditions (*)

1. creating 2 categories as subcategories of the root one (test1 and test2)
2. creating 2 products 1 for each created category (product1 for test1 and product2 for test2)

### Steps to reproduce (*)

1. using graphql client running this query
```
{
  products(filter: {category_id: {in: ["3","4"]}}) {
    total_count
    items {
      name
      categories {
        id
        name
      }
    }
  }
} 
```

### Expected result (*)

1. getting the `total_count` = 2
2. getting 2 products into `items` property

### Actual result (*)

1. getting correct `total_count` = 2
2. getting **_only 1 product_** of last value in `in` filter array (in this case `category_id` = 4)
Screen Shot 2020-08-23 at 12 29 30 PM

without applying any filters
Screen Shot 2020-08-23 at 12 39 39 PM

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [x] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #30349: [PAP] Product filter with "category_id: {in: [...]}" does not work as expected
Steps to reproduce:
- Create 2 categories with 1 product each
- run query to fetch products in those categories
```
{
  products(filter: {category_id: {in: <"<cat1>", "<cat2>">}}) {
    items {
      sku
      name
    }
    total_count
  }
}
```

Expected:
total_count should be 2, and items should contain 2 products

Actual:
total_count is 2, but items only contains 1 products

Some investigation:
Changes to \Magento\CatalogGraphQl\Model\Resolver\Products\SearchCriteria\CollectionProcessor\FilterProcessor\CategoryFilter::apply() cause the product collection to be filtered by only the last category id in the array used for "in".
see $collection->addCategoryFilter($category); on line 64

Tests failed to catch this because they check total_count but not actual count of items
need to fix test: \Magento\GraphQl\Catalog\ProductSearchTest::testFilteringForProductsFromMultipleCategories()

### PR DESCRIPTION
**Pull request by sudheers-kensium**
Product filter with category_id does not work as expected

### Description (*)

1. Create 2 categories with 1 product each
2. run query to fetch products in those categories
`{
  products(filter: {category_id: {in: ["<cat1>", "<cat2>"]}}) {
    items {
      sku
      name
    }
    total_count
  }
}`
3. Should display total_count should be 2, and items should contain 2 products
### Fixed Issues (if relevant)

1. Fixes magento/magento2#30349

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/SearchCriteria/CollectionProcessor/FilterProcessor/CategoryFilter.php [hunk 1]
```diff
@@ -61,7 +61,6 @@ public function apply(Filter $filter, AbstractDb $collection)
             $category = $this->categoryFactory->create();
             $this->categoryResourceModel->load($category, $categoryId);
             $categoryProducts[$categoryId] = $category->getProductCollection()->getAllIds();
-            $collection->addCategoryFilter($category);
```
Comment (rogyar) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products/SearchCriteria/CollectionProcessor/FilterProcessor/CategoryFilter.php]: Hi @sudheers-kensium. Thank you for your contribution. I'm not sure that by removing this filter we won't introduce an additional issue. This filter has been recently added for solving the sorting issue. Details are below

https://github.com/magento/magento2/commit/dfcf474d83c05620e6fa3010ae25632cb820174e#diff-8a27c9476b188f4e8830e9872984bdfbR64

@cpartica could you provide more information on the consequences, please? Unfortunately, I have a lack of details about MC-32278. 

Thank you!

**Review by rogyar — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
Hi @sudheers-kensium, can you please look at https://github.com/magento/magento2/pull/30375#discussion_r502443239? Otherwise, we can't proceed with your PR.
Thank you.

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/SearchCriteria/CollectionProcessor/FilterProcessor/CategoryFilter.php (hunk 1 above)
Comment (sudheers-kensium) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Products/SearchCriteria/CollectionProcessor/FilterProcessor/CategoryFilter.php]: @rogyar I have changed the code. Please check once.

**Comment by nrkapoor** [comment]
@magento run all tests

**Comment by rogyar** [comment]
Hi @sudheers-kensium. Thanks for the adjustments. Now it looks much better. 
Could you, please, cover this case with an API-functional test? 

Thank you!

**Comment by sudheers-kensium** [comment]
Hi @rogyar. I have added API-functional test. Please check once.

**Comment by sudheers-kensium** [comment]
@magento run all tests

**Comment by sudheers-kensium** [comment]
@magento run all tests

**Comment by prabhuram93** [comment]
@sudheers-kensium changes looks good. I see some static failures which needs to be fixed. Please pull the latest mainline and run the builds again. We can move this to QA once the builds are green. Thanks!

**Comment by sudheers-kensium** [comment]
@magento run all tests

**Comment by sudheers-kensium** [comment]
@magento run Integration Tests

**Comment by prabhuram93** [comment]
@magento run integration tests

**Comment by sudheers-kensium** [comment]
@magento run Integration Tests

**Review by prabhuram93 — APPROVED** [review]

**Comment by dthampy** [comment]
@magento import PR to magento-honey-badgers/magento2ce

**Comment by magento-engcom-team** [comment]
@dthampy the branch with code successfully imported into`magento-honey-badgers/magento2ce` repository. Branch name: `imported-magento-magento2-30375`.

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8392](https://jira.corp.magento.com/browse/ENGCOM-8392) has been created to process this Pull Request

**Comment by cpartica** [comment]
@magento import PR to magento-honey-badgers/magento2ce

**Review by cpartica — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
@cpartica the branch with code successfully imported into`magento-honey-badgers/magento2ce` repository. Branch name: `imported-magento-magento2-30375`.

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php [hunk 2]
```diff
@@ -113,7 +113,7 @@ public function getList(
         $searchResults = $this->searchResultsFactory->create();
         $searchResults->setSearchCriteria($searchCriteriaForCollection);
         $searchResults->setItems($collection->getItems());
-        $searchResults->setTotalCount($searchResult->getTotalCount());
+        $searchResults->setTotalCount($collection->getSize());
```
Comment (rani-priya) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php:116]: Hi @sudheers-kensium ,

Here why we have changed $searchResult->getTotalCount() to $collection->getSize() ?

Actually my concern is when we call getSize() on collection then it will execute one sql query to the database and it will take some time but in $searchResult is itself an object and all the data is present in that object. so, to execute $searchResult->getTotalCount() system will take negligible time where as $collection->getSize() will take some time.

I checked the performance of both code by adding below code in /vendor/magento/module-catalog-graph-ql/Model/Resolver/Products/DataProvider/ProductSearch.php file of "getList" method after "$this->collectionPostProcessor->process($collection, $attributes);" code and checked the response time of both getSize and getTotalCount method.
$time1 = microtime(true);
echo "Total Count: ".$collection->getSize()."<br/>";
$time2 = microtime(true);
echo "time taken in getSize is: ".($time2- $time1)."<br/>"; 

$time3 = microtime(true);
echo "Total Count: ".$searchResult->getTotalCount()."<br/>";
$time4 = microtime(true);
echo "time taken in getTotalCount is: ".($time4 - $time3); 
Response on my local :
Total Count: 32310
time taken in getSize is: 3.1487860679626
Total Count: 32310
time taken in getTotalCount is: 3.4093856811523E-5

**Review by rani-priya — COMMENTED** [review]
@rogyar @cpartica and @prabhuram93 could you please review my observation

**Comment by rani-webkul** [comment]
@magento give me 2.4-develop instance

**Comment by drpayyne** [comment]
> @rogyar @cpartica and @prabhuram93 could you please review my observation

Hi @rogyar, could you please check the above observation by @rani-webkul? Looks like it might cause performance issues when scaling up.
