### PR TITLE
Mark Framework interfaces as API part 2

### LINKED ISSUE #32025: Mark Framework interfaces as API part 2
The following interfaces should be marked as API in 2.4-develop branch

1. lib/internal/Magento/Framework/App/CsrfAwareActionInterface.php
1. lib/internal/Magento/Framework/App/DefaultPathInterface.php
1. lib/internal/Magento/Framework/App/DeploymentConfig/ImporterInterface.php
1. lib/internal/Magento/Framework/App/DeploymentConfig/ValidatorInterface.php
1. lib/internal/Magento/Framework/App/DeploymentConfig/Writer/FormatterInterface.php
1. lib/internal/Magento/Framework/App/DesignInterface.php
1. lib/internal/Magento/Framework/App/EnvironmentInterface.php
1. lib/internal/Magento/Framework/App/ExceptionHandlerInterface.php
1. lib/internal/Magento/Framework/App/FeedFactoryInterface.php
1. lib/internal/Magento/Framework/App/FeedInterface.php
1. lib/internal/Magento/Framework/App/HttpRequestInterface.php
1. lib/internal/Magento/Framework/App/ObjectManager/ConfigWriterInterface.php
1. lib/internal/Magento/Framework/App/PageCache/NotCacheableInterface.php
1. lib/internal/Magento/Framework/App/Request/ValidatorInterface.php
1. lib/internal/Magento/Framework/App/ResourceConnection/ConfigInterface.php
1. lib/internal/Magento/Framework/App/ResourceConnection/ConnectionAdapterInterface.php
1. lib/internal/Magento/Framework/App/Response/FileInterface.php
1. lib/internal/Magento/Framework/App/Response/HeaderProvider/HeaderProviderInterface.php
1. lib/internal/Magento/Framework/App/Response/RedirectInterface.php
1. lib/internal/Magento/Framework/App/Router/NoRouteHandlerInterface.php
1. lib/internal/Magento/Framework/App/Router/PathConfigInterface.php
1. lib/internal/Magento/Framework/App/RouterInterface.php
1. lib/internal/Magento/Framework/App/RouterListInterface.php
1. lib/internal/Magento/Framework/App/Rss/RssManagerInterface.php
1. lib/internal/Magento/Framework/App/Rss/UrlBuilderInterface.php
1. lib/internal/Magento/Framework/App/Scope/ValidatorInterface.php
1. lib/internal/Magento/Framework/App/ScopeFallbackResolverInterface.php
1. lib/internal/Magento/Framework/App/ScopeResolverInterface.php
1. lib/internal/Magento/Framework/App/ScopeTreeProviderInterface.php
1. lib/internal/Magento/Framework/App/ScopeValidatorInterface.php
1. lib/internal/Magento/Framework/App/View/Asset/MaterializationStrategy/StrategyInterface.php
1. lib/internal/Magento/Framework/App/View/Deployment/Version/StorageInterface.php

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

Mark following interfaces as API + Added strict_types

lib/internal/Magento/Framework/App/CsrfAwareActionInterface.php
lib/internal/Magento/Framework/App/DefaultPathInterface.php
lib/internal/Magento/Framework/App/DeploymentConfig/ImporterInterface.php
lib/internal/Magento/Framework/App/DeploymentConfig/ValidatorInterface.php
lib/internal/Magento/Framework/App/DeploymentConfig/Writer/FormatterInterface.php
lib/internal/Magento/Framework/App/DesignInterface.php
lib/internal/Magento/Framework/App/EnvironmentInterface.php
lib/internal/Magento/Framework/App/ExceptionHandlerInterface.php
lib/internal/Magento/Framework/App/FeedFactoryInterface.php
lib/internal/Magento/Framework/App/FeedInterface.php
lib/internal/Magento/Framework/App/HttpRequestInterface.php
lib/internal/Magento/Framework/App/ObjectManager/ConfigWriterInterface.php
lib/internal/Magento/Framework/App/PageCache/NotCacheableInterface.php
lib/internal/Magento/Framework/App/Request/ValidatorInterface.php
lib/internal/Magento/Framework/App/ResourceConnection/ConfigInterface.php
lib/internal/Magento/Framework/App/ResourceConnection/ConnectionAdapterInterface.php
lib/internal/Magento/Framework/App/Response/FileInterface.php
lib/internal/Magento/Framework/App/Response/HeaderProvider/HeaderProviderInterface.php
lib/internal/Magento/Framework/App/Response/RedirectInterface.php
lib/internal/Magento/Framework/App/Router/NoRouteHandlerInterface.php
lib/internal/Magento/Framework/App/Router/PathConfigInterface.php
lib/internal/Magento/Framework/App/RouterInterface.php
lib/internal/Magento/Framework/App/RouterListInterface.php
lib/internal/Magento/Framework/App/Rss/RssManagerInterface.php
lib/internal/Magento/Framework/App/Rss/UrlBuilderInterface.php
lib/internal/Magento/Framework/App/Scope/ValidatorInterface.php
lib/internal/Magento/Framework/App/ScopeFallbackResolverInterface.php
lib/internal/Magento/Framework/App/ScopeResolverInterface.php
lib/internal/Magento/Framework/App/ScopeTreeProviderInterface.php
lib/internal/Magento/Framework/App/ScopeValidatorInterface.php
lib/internal/Magento/Framework/App/View/Asset/MaterializationStrategy/StrategyInterface.php
lib/internal/Magento/Framework/App/View/Deployment/Version/StorageInterface.php

Also marked api for references class/interfaces

lib/internal/Magento/Framework/\App/Request/InvalidRequestException
lib/internal/Magento/Framework/Interception/ObjectManager/ConfigInterface
lib/internal/Magento/Framework/App/Response/Http
lib/internal/Magento/Framework/App/Request/Http

lib/internal/Magento/Framework/ObjectManager/RelationsInterface.php
lib/internal/Magento/Framework/ObjectManager/ConfigInterface.php
lib/internal/Magento/Framework/ObjectManager/ConfigCacheInterface.php
lib/internal/Magento/Framework/Interception/ConfigInterface.php

lib/internal/Magento/Framework/DB/LoggerInterface (by lib/internal/Magento/Framework/App/ResourceConnection/ConnectionAdapterInterface.php)

lib/internal/Magento/Framework/View/DesignInterface (by
lib/internal/Magento/Framework/App/DesignInterface.php)

### Related Pull Requests

https://github.com/magento/magento2/pull/32142
https://github.com/magento/magento2/pull/32156
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32025

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Rebased 2.5-develop

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
Public type 'Magento\Framework\App\CsrfAwareActionInterface' references following non-public types:
Magento\Framework\App\Request\InvalidRequestException

Public type 'Magento\Framework\App\DesignInterface' references following non-public types:
Magento\Framework\View\DesignInterface

Public type 'Magento\Framework\App\EnvironmentInterface' references following non-public types:
Magento\Framework\Interception\ObjectManager\ConfigInterface

Public type 'Magento\Framework\App\ExceptionHandlerInterface' references following non-public types:
Magento\Framework\App\Response\Http
Magento\Framework\App\Request\Http

Public type 'Magento\Framework\App\ResourceConnection\ConnectionAdapterInterface' references following non-public types:
Magento\Framework\DB\LoggerInterface

**Comment by mrtuvn** [comment]
Fix static tests
@magento run all tests

**Comment by mrtuvn** [comment]
Fix static tests
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Static Tests, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@mrtuvn instead of marking the `api` classes that are failing on Static Tests, it's better to take a quick look, maybe they were already mentioned in scope of another PRs. For example, here you are marking as api:

- lib/internal/Magento/Framework/DB/LoggerInterface - but this was already marked in another your PR #32156

This will cause a lot of conflicts while merging them.

Please add all the PRs that you find useful for your PR, as related.

Please let me know if any questions arise.

**Comment by mrtuvn** [comment]
Fixed issue related as your suggestion

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Static Tests, Unit Tests

**Comment by mrtuvn** [comment]
@magento run Static Tests, Unit Tests

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, WebAPI Tests

**Comment by eduard13** [comment]
@magento run Unit Tests, Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests EE, Functional Tests CE, Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests EE, WebAPI Tests

File: lib/internal/Magento/Framework/App/Response/Http.php [hunk 1]
```diff
@@ -131,7 +133,7 @@ public function sendVary()
      */
     public function setPublicHeaders($ttl)
     {
-        if ($ttl < 0 || !preg_match('/^[0-9]+$/', $ttl)) {
+        if ($ttl < 0 || !$ttl) {
```
Comment (eduard13) [inline lib/internal/Magento/Framework/App/Response/Http.php]: Hi @mrtuvn, any info of why the following logic has been changed?

Comment (mrtuvn) [reply lib/internal/Magento/Framework/App/Response/Http.php]: After add strict type i have found error here when second argument of preg_match required type string. But we passed TTL with int value. So i think we don't have to check with preg_match

Comment (eduard13) [reply lib/internal/Magento/Framework/App/Response/Http.php]: I think the main reason of why it was failing, is the following test that passes a `null` value here https://github.com/magento/magento2/blob/45f27d64cbb475a4af4d27e14d312653823083e1/lib/internal/Magento/Framework/App/Test/Unit/Response/HttpTest.php#L231

But preg_match's 2nd argument should be a string value.

But now, we allow passing string values as parameter, as we still don't have any restrictions, which shouldn't happen:
- asd
- test123
- =1
- etc

We should avoid that, and should only have int values.

**Review by eduard13 — CHANGES_REQUESTED** [review]
Requesting changes

**Comment by mrtuvn** [comment]
What should i need to change ?

File: lib/internal/Magento/Framework/App/Response/Http.php [hunk 2]
```diff
@@ -131,7 +133,7 @@ public function sendVary()
      */
     public function setPublicHeaders($ttl)
     {
-        if ($ttl < 0 || !preg_match('/^[0-9]+$/', $ttl)) {
+        if ($ttl < 0 || !preg_match('/^[0-9]+$/', (string) $ttl)) {
             throw new \InvalidArgumentException('Time to live is a mandatory parameter for set public headers');
         }
         $this->setHeader('pragma', 'cache', true);
```
Comment (mrtuvn) [inline lib/internal/Magento/Framework/App/Response/Http.php]: Added compulsive type here for input `$ttl` . we have explicit type pass to preg_match
CC: @eduard13

Comment (eduard13) [reply lib/internal/Magento/Framework/App/Response/Http.php]: But, have you tried to update the Unit Test that I mentioned, to see if that's the reason of why the test was previously failing (referencing the comment above)?

Comment (mrtuvn) [reply lib/internal/Magento/Framework/App/Response/Http.php]: Test file still remain i don't change the null test case! Only change in origin file. Re-run unit test passed in my local

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by eduard13** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

File: lib/internal/Magento/Framework/App/Response/Http.php [hunk 3]
```diff
@@ -131,7 +133,7 @@ public function sendVary()
      */
     public function setPublicHeaders($ttl)
     {
-        if ($ttl < 0 || !preg_match('/^[0-9]+$/', $ttl)) {
+        if ($ttl < 0 || !preg_match('/^[0-9]+$/', (string) $ttl)) {
```
Comment (eduard13) [inline lib/internal/Magento/Framework/App/Response/Http.php]: @mrtuvn after discussing this change internally, decided that it makes sense to get rid of this `preg_match`. This way, we won't need the `string` casting.
```suggestion
        if ($ttl < 0 || !is_numeric($ttl)) {
```

Comment (mrtuvn) [reply lib/internal/Magento/Framework/App/Response/Http.php]: Thanks you just corrected it again as suggestion

**Comment by mrtuvn** [comment]
@mgento run all tests

**Comment by eduard13** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Database Compare

**Comment by eduard13** [comment]
@magento run Database Compare

**Comment by eduard13** [comment]
@magento run Database Compare

**Review by eduard13 — APPROVED** [review]
Don't think that Database Compare failed builds are somehow related with these changes.

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-8920](https://jira.corp.magento.com/browse/ENGCOM-8920) has been created to process this Pull Request

**Comment by mrtuvn** [comment]
@magento run Database Compare

**Comment by mrtuvn** [comment]
Re-targeted PR branch to 2.4-develop as internal discussed with @gabrieldagama

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests EE

File: lib/internal/Magento/Framework/App/Response/Http.php [hunk 4]
```diff
@@ -131,7 +133,7 @@ public function sendVary()
      */
     public function setPublicHeaders($ttl)
     {
-        if ($ttl < 0 || !preg_match('/^[0-9]+$/', $ttl)) {
+        if ($ttl < 0 || !is_numeric($ttl)) {
```
Comment (gabrieldagama) [inline lib/internal/Magento/Framework/App/Response/Http.php]: We are not looking for code changes with these issues, please revert as it was.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/App/Response/Http.php (hunk 4 above)
Comment (mrtuvn) [reply lib/internal/Magento/Framework/App/Response/Http.php]: This change introduce since i added strict_type at the first line of fine! This change pass test too should i revert strict_type in only this

Comment (gabrieldagama) [reply lib/internal/Magento/Framework/App/Response/Http.php]: In this case, let's create a separate PR to add the strict type and the code change. On this scope, we are looking just for API marking.

Comment (mrtuvn) [reply lib/internal/Magento/Framework/App/Response/Http.php]: updating it

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B

**Comment by mrtuvn** [comment]
@gabrieldagama all green tests and ready!

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento import code to https://github.com/magento-engcom/magento2ce

**Comment by magento-engcom-team** [comment]
@gabrieldagama the branch with code successfully imported into`magento-engcom/magento2ce` repository. Branch name: `imported-magento-magento2-32140`.
