### PR TITLE
fix: do not forcefully set area in template if it is already set, fixes #14968, fixes #13530

### LINKED ISSUE #13530: "Template file 'header.html' is not found" error while trying to save Design Configuration.
### Preconditions
1. Magento `2.2-develop` branch, current commit: f18377b9e59
2. PHP 7.0.27

### Steps to reproduce
1. Setup a clean Magento from the `2.2-develop` using commit f18377b9e59
2. Go into the backend to Content => Design => Configuration
3. Open either the Global or Website scoped configuration
4. Click 'Save and Continue'

### Expected result
1. Configuration should be saved without errors

### Actual result
1. We are getting the error: `Something went wrong while saving this configuration: Template file 'header.html' is not found.`

### Discussion
Curiously enough, this only happens on the Global and Website scope, when trying the same on the Storeview scope, it works and we don't see this error.

### LINKED ISSUE #14968: Can't change the applied theme in 2.2.4
### Preconditions
1. Magento 2.2.4
2. PHP 7.1

### Steps to reproduce
1. Go to Content > Design > Configuration
2. Edit the Store View and try to change the "Applied theme" to another
3. Save Configuration

### Expected result
1. Change the theme

### Actual result
1. Appears the error: "Something went wrong while saving this configuration: Area is already set"

### PR DESCRIPTION
**Pull request by DanielRuf**
### Description
This reverts the addition of the enforced area in https://github.com/magento/magento2/commit/d3aef7c3eef658baa00d3233d0352b5fed0f1cbe which caused https://github.com/magento/magento2/issues/14968 and introduced this regression

### Fixed Issues (if relevant)

1. magento/magento2#14968: Can't change the applied theme in 2.2.4
2. magento/magento2#13530: "Template file 'header.html' is not found" error while trying to save Design Configuration.

### Manual testing scenarios

1. comment / disable line 117 in app/code/Magento/Theme/Model/Design/Config/Validator.php
2. change theme in store view

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by hostep** [comment]
For completeness sake, this PR also fixes https://github.com/magento/magento2/issues/13530 (which was already fixed by d3aef7c3eef658baa00d3233d0352b5fed0f1cbe, but that was an incomplete fix)

**Comment by DanielRuf** [comment]
> For completeness sake, this PR also fixes #13530 (which was already fixed by d3aef7c, but that was an incomplete fix)

Thanks for the reference, updated the list in the PR comment to link to it.

File: app/code/Magento/Email/Model/AbstractTemplate.php [hunk 1]
```diff
@@ -534,10 +534,9 @@ protected function cancelDesignConfig()
      */
     public function setForcedArea($templateId)
     {
-        if ($this->area) {
-            throw new \LogicException(__('Area is already set'));
+        if (!isset($this->area)) {
```
Comment (orlangur) [inline app/code/Magento/Email/Model/AbstractTemplate.php:537]: Can `$this->area` be empty and not `null`? Looks like simple `if (!$this->area)` is sufficient here.

File: app/code/Magento/Email/Model/AbstractTemplate.php [hunk 2]
```diff
@@ -534,10 +534,9 @@ protected function cancelDesignConfig()
      */
     public function setForcedArea($templateId)
     {
-        if ($this->area) {
-            throw new \LogicException(__('Area is already set'));
```
Comment (orlangur) [inline app/code/Magento/Email/Model/AbstractTemplate.php:538]: Was there any logic in this exception before? Any idea why it was introduced?

**Review by orlangur — CHANGES_REQUESTED** [review]

File: app/code/Magento/Email/Model/AbstractTemplate.php (hunk 1 above)
Comment (DanielRuf) [reply app/code/Magento/Email/Model/AbstractTemplate.php:537]: Not that I knew, it is either set or `null` according to the class where it is set in the constructor.

Comment (orlangur) [reply app/code/Magento/Email/Model/AbstractTemplate.php:537]: Ok, then simplify condition please. Commit amend is preferable.

File: app/code/Magento/Email/Model/AbstractTemplate.php (hunk 2 above)
Comment (DanielRuf) [reply app/code/Magento/Email/Model/AbstractTemplate.php:538]: This was still the original code from 3 years ago which was untouched. The annotations and exception class are not correct imo but should be solved in another PR.

Comment (DanielRuf) [reply app/code/Magento/Email/Model/AbstractTemplate.php:538]: Check the blame view of the file in the original repo and you see that the code was never really touched ;-)

File: app/code/Magento/Email/Model/AbstractTemplate.php (hunk 1 above)
Comment (DanielRuf) [reply app/code/Magento/Email/Model/AbstractTemplate.php:537]: empty and isset check are different, what should I change here? It can just be null or set and isset checks for it already.

**Comment by magento-engcom-team** [comment]
Hi @DanielRuf. Thank you for your contribution. 
Changes from your Pull Request will be available with the upcoming 2.2.6 release.

File: app/code/Magento/Email/Model/AbstractTemplate.php (hunk 1 above)
Comment (orlangur) [reply app/code/Magento/Email/Model/AbstractTemplate.php:537]: @DanielRuf I meant that there is no reason to change `if ($this->area) {`

Comment (DanielRuf) [reply app/code/Magento/Email/Model/AbstractTemplate.php:537]: isset is more strict and still correct so I think we can keep it like this.

**Comment by legweilo** [comment]
Hi guys,

a small module to fix it without touching the core:

https://github.com/pfortin-expertime/MageFix-Misc

Enjoy ;)

File: app/code/Magento/Email/Model/AbstractTemplate.php (hunk 2 above)
Comment (hitesh-wagento) [reply app/code/Magento/Email/Model/AbstractTemplate.php:538]: @DanielRuf Is there any patch available for temporary. I need to fix this in my Magento v.2.2.4.

Comment (DanielRuf) [reply app/code/Magento/Email/Model/AbstractTemplate.php:538]: @hitesh-wagento simply add `.patch` to the pull/number URL and you get https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/15137.patch

**Comment by DanielRuf** [comment]
> Hi guys,
> 
> a small module to fix it without touching the core:
> 
> pfortin-expertime/MageFix-Misc
> 
> Enjoy ;)

A composer patch would be better ;-)

**Comment by 0xpwn** [comment]
@DanielRuf Can you please explain in short how to apply this patch using composer-patches? 

I have the following in my `composer.json`:
```javascript
{
  "config": {
    "preferred-install": "source"
  },
  "extra": {
    "patches": {
      "magento/product-community-edition": {
        "Fix force switch theme": "https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/15137.patch"
      }
    }
  }
}
```
But I get the following errors:
```bash
composer update magento/product-community-edition -vvv

  - Applying patches for magento/product-community-edition
    https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/15137.patch (Fix force switch theme)
Downloading https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/15137.patch
patch '-p1' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
Executing command (CWD): patch '-p1' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
patch: **** Can't change to directory  : No such file or directory

patch '-p0' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
Executing command (CWD): patch '-p0' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
patch: **** Can't change to directory  : No such file or directory

patch '-p2' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
Executing command (CWD): patch '-p2' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
patch: **** Can't change to directory  : No such file or directory

patch '-p4' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
Executing command (CWD): patch '-p4' --no-backup-if-mismatch -d '' < '/var/folders/n1/0cl9jxm90lg1r5qkrqnwf3580000gn/T/5b2ce62c2819b.patch'
patch: **** Can't change to directory  : No such file or directory

   Could not apply patch! Skipping. The error was: Cannot apply patch https://patch-diff.githubusercontent.com/raw/magento/magento2/pull/15137.patch



  [ErrorException]
  file_put_contents(/PATCHES.txt): failed to open stream: Permission denied
```

**Comment by DanielRuf** [comment]
> file_put_contents(/PATCHES.txt): failed to open stream: Permission denied

Looks like some chown / rights issues.

**Comment by hostep** [comment]
@1x0: a patch won't just work from Github, since the file paths in the patch won't match the composer installation (`app/code/Magento/Theme/` vs `vendor/magento/module-theme/`).

You can find information about how to create, edit and apply patches using this recently introduced Knowledge Base article from Magento: https://support.magento.com/hc/en-us/articles/360005484154
Hope this helps :)

**Comment by DanielRuf** [comment]
> (app/code/Magento/Theme/ vs vendor/magento/module-theme/).

Ah right forgot that the Git repo and composer based installs are different but we can still use app/code to overwrite the original files.

Changing the file paths in the patch file should be sufficient.

**Comment by DanielRuf** [comment]
> Edit the file and remove vendor/<VENDOR>/<PACKAGE> from all paths so that they are relative to the vendor/<VENDOR>/<PACKAGE> directory.

Simply forgot this one =)

**Comment by ihor-sviziev** [comment]
FYI I created squashed commit that can used for composer patches:
`https://github.com/ihor-sviziev/magento2/commit/e4ec8adef586c615cda168175ad8950c701b0874.patch`

**Comment by hostep** [comment]
@ihor-sviziev : @sidolov also already did that on 16 May, you can view his commit if you scroll up a bit, see: https://github.com/magento/magento2/commit/7019a0a1392095185505ff3ca7b97dd3e9cb4ef2

And it's available on here as well: https://magento.com/tech-resources/download (MAGETWO-93036), don't know if this got communicated or something, because I only found out about that by accident.

But thanks anyways! :)

**Comment by ihor-sviziev** [comment]
Hi @hostep,
We tried to apply this patch from commit 7019a0a with composer patches and got an error. Reason is simple commit that you showed - when you trying to use it as a patch - it contains changes both form magneto email and magneto theme modules + reverting changes in magento theme also. While mine contains only changes in magento theme because it contains squashed chanages into 1 commit

**Comment by DanielRuf** [comment]
There should be just one file changed. Do you use Magento 2.2.5?

**Comment by DanielRuf** [comment]
Only `app/code/Magento/Email/Model/AbstractTemplate.php` should be affected.

**Comment by ihor-sviziev** [comment]
@DanielRuf sure, just take a look at https://github.com/magento/magento2/commit/7019a0a1392095185505ff3ca7b97dd3e9cb4ef2.patch - it contains all changes form all commits - adds changes to magneto theme, removes changed files in magento theme and adds changes to magneto email.
That's why it's better to squash commits into single one when you have final result

**Comment by DanielRuf** [comment]
Try https://github.com/magento/magento2/pull/15137.diff if the other one is problematic.

**Comment by DanielRuf** [comment]
Because the other applies all commits one by one (they are not squashed, take a look at the commits tab).

**Comment by DanielRuf** [comment]
Also the other should be problematic, the result should be the same (in general).
