### PR TITLE
Fix new iTxt && zTxt segment creation for PNG image XMP && IPTC segments

### LINKED ISSUE #1743: Some images are shown as broken after added description to it in the Media Gallery
### Preconditions (*)

1. Install Magento with Adobe Stock Integration
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. Enhanced Media Gallery Enabled

### Steps to reproduce (*)

1. Go to Content - Media Gallery
2. Upload png image
3. Edit uploaded image
4. Add some description -> Save
5. Reload the page
6. Open View Details for this image

### Expected result (*)

Image should display correctly

### Actual result (*)

1. Image is broken 
image

### PR DESCRIPTION
**Pull request by Nazar65**
### Description (*)

New  zTXt && iTXt  chunks should be placed before IEND chunk

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1743: Some images are shown as broken after added description to it in the Media Gallery 

### Manual testing scenarios (*)
1. Go to Content - Media Gallery
2. Upload png image
3. Edit uploaded image
4. Add some description -> Save
5. Reload the page
6. Open View Details for this image

**Image should display correctly**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/MediaGalleryMetadata/Model/Png/Segment/WriteXmp.php [hunk 1]
```diff
@@ -97,15 +97,19 @@ public function execute(FileInterface $file, MetadataInterface $metadata): FileI
...
      *
      * @param SegmentInterface[] $segments
      * @param SegmentInterface $xmpSegment
      * @return SegmentInterface[]
      */
     private function insertPngXmpSegment(array $segments, SegmentInterface $xmpSegment): array
     {
-        return array_merge(array_slice($segments, 0, 2), [$xmpSegment], array_slice($segments, 2));
+        return array_merge(
+            array_slice($segments, 0, count($segments) - 1),
```
Comment (sivaschenko) [inline app/code/Magento/MediaGalleryMetadata/Model/Png/Segment/WriteXmp.php]: I think extracting the variable `$iendSegmentIndex = count($segments) - 1` would not only avoid double `count` call but also positively affect the code readability

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @Nazar65 ! By any chance, do you have a png image that can be used to verify the fix that can be added to the integration tests dataset?

File: app/code/Magento/MediaGalleryMetadata/Model/Png/Segment/WriteXmp.php (hunk 1 above)
Comment (Nazar65) [reply app/code/Magento/MediaGalleryMetadata/Model/Png/Segment/WriteXmp.php]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed 
Checked on images with different extensions. All images are displayed correctly
Screenshot_92

Manual testing [scenario](https://studio.cucumber.io/projects/131313/test-plan/folders/1054245/scenarios/5088663)
