### PR TITLE
change error to code is reserved key instead of code already exists

### LINKED ISSUE #28479: Product attributes product_type, type_id cannot be created/edited form admin
### Preconditions (*)

1. Magento 2.3.5-p1

### Steps to reproduce (*)

1. _IF_ product attributes with following code does not exist `product_type` or `type_id` then attempt to create any of them
2. _ELSE_ edit any of them and change anything

### Expected result (*)

- Attribute is not saved. Error message is shown
-  text:  _Code "product_type" is a reserved key and cannot be used as attribute code._
- text:  _Code "type_idis" a reserved key and cannot be used as attribute code._

### Actual result (*)

1. Either of following messages appear `An attribute with this code already exists.` _OR_ `An attribute with the same code (product_type) already exists.`
product_type
type_id

**It's** due to following line of code https://github.com/magento/magento2/blob/39012d4ea79157cb12eef348cc3448d955c0ecc5/app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php#L130 implemented in https://github.com/magento/magento2/commit/ca0da34ee2691bfaca1c74d94a0db33377d4e54c#diff-9ff38a88c1abf86286f77b64c8bc9b38 and https://github.com/magento/magento2/commit/b9d13e69c4928a0b6d740845bed305a399a42fd5#diff-9ff38a88c1abf86286f77b64c8bc9b38

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by AbdulRahmanAbouzaid**
### Description (*)

Change error message caused by creating product attribute with `product_type` and `type_id` codes to be more descriptive.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28479

### Manual testing scenarios (*)

1. Go to `Stores` > `Attributes` > `Product`
2. Create new attribute with `product_type` or `type_id` code

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Let's move reserved attributes to the private constant.

Please consider covering this change with MFTF test.

**Comment by AbdulRahmanAbouzaid** [comment]
@lenaorobei changes and test provided. Can you please review it again?

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run all tests

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run all tests

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Functional Tests CE

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php [hunk 1]
```diff
@@ -127,11 +128,14 @@ public function execute()
             $attributeCode
         );
 
-        if ($attribute->getId() && !$attributeId || $attributeCode === 'product_type' || $attributeCode === 'type_id') {
-            $message = strlen($this->getRequest()->getParam('attribute_code'))
-                ? __('An attribute with this code already exists.')
-                : __('An attribute with the same code (%1) already exists.', $attributeCode);
-
+        if ($attribute->getId() && !$attributeId || in_array($attributeCode, static::RESERVED_CODES)) {
+            if (in_array($attributeCode, static::RESERVED_CODES)) {
```
Comment (lenaorobei) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php]: Let's simplify logic in this condition. The same `in_array` is being called twice. 
Please use `self` instead of `static` for constant access.

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run all tests

**Comment by AbdulRahmanAbouzaid** [comment]
@lenaorobei Changes provided

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Functional Tests B2B

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Functional Tests CE

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Functional Tests EE

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php [hunk 2]
```diff
@@ -127,11 +128,16 @@ public function execute()
             $attributeCode
         );
 
-        if ($attribute->getId() && !$attributeId || $attributeCode === 'product_type' || $attributeCode === 'type_id') {
+        if (in_array($attributeCode, self::RESERVED_CODES)) {
```
Comment (lenaorobei) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php]:
```suggestion
        if (in_array($attributeCode, self::RESERVED_CODES, true)) {
```

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php [hunk 3]
```diff
@@ -23,6 +23,7 @@
 class Validate extends AttributeAction implements HttpGetActionInterface, HttpPostActionInterface
 {
     const DEFAULT_MESSAGE_KEY = 'message';
+    const RESERVED_CODES = ['product_type', 'type_id'];
```
Comment (lenaorobei) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php]:
```suggestion
   private const RESERVED_ATTRIBUTE_CODES = ['product_type', 'type_id'];
```

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php [hunk 4]
```diff
@@ -127,11 +128,16 @@ public function execute()
             $attributeCode
         );
 
-        if ($attribute->getId() && !$attributeId || $attributeCode === 'product_type' || $attributeCode === 'type_id') {
+        if (in_array($attributeCode, self::RESERVED_CODES, true)) {
```
Comment (lenaorobei) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php]:
```suggestion
        if (in_array($attributeCode, self:: RESERVED_ATTRIBUTE_CODES, true)) {
```

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php [hunk 5]
```diff
@@ -127,11 +128,16 @@ public function execute()
             $attributeCode
         );
 
-        if ($attribute->getId() && !$attributeId || $attributeCode === 'product_type' || $attributeCode === 'type_id') {
+        if (in_array($attributeCode, self:: RESERVED_ATTRIBUTE_CODES, true)) {
```
Comment (lenaorobei) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Attribute/Validate.php]:
```suggestion
        if (in_array($attributeCode, self::RESERVED_ATTRIBUTE_CODES, true)) {
```

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run all tests

**Comment by lenaorobei** [comment]
Please see Integration and Static builds failures. Looks like they were caused by your changes.

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't impact other areas.

**Comment by engcom-Echo** [comment]
Hi @AbdulRahmanAbouzaid. Can you please fix "Static test"?

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Static Tests

**Comment by lenaorobei** [comment]
@magento run all tests

**Review by lenaorobei — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lenaorobei, thank you for the review.
[ENGCOM-8178](https://jira.corp.magento.com/browse/ENGCOM-8178) has been created to process this Pull Request
:eight_spoked_asterisk: @lenaorobei, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run Functional Tests CE

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @AbdulRahmanAbouzaid .

Could you add this phrase `Code (%1) is a reserved key and cannot be used as attribute code.` to the translation file?
Thanks!

**Comment by AbdulRahmanAbouzaid** [comment]
@magento run all tests

**Comment by AbdulRahmanAbouzaid** [comment]
@engcom-Alfa phrase added to the translation file

**Review by lenaorobei — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to Stores > Attributes > Product;
2. Create new attribute with _**product_type**_ or _**type_id**_ code;

**Before:** :heavy_multiplication_x: Either of following messages appear `An attribute with this code already exists.` OR `An attribute with the same code (product_type) already exists`.

Screenshot from 2020-09-18 14-16-10

**After:** :heavy_check_mark: Attribute is not saved. Error message is shown

:heavy_check_mark: text: Code "`product_type`" is a reserved key and cannot be used as an attribute code.

Screenshot from 2020-09-18 15-18-47

:heavy_check_mark: text: Code "`type_id`" a reserved key and cannot be used as attribute code.

Screenshot from 2020-09-18 15-20-04

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests
