### PR TITLE
#21853: Allow mview indexers to use different entity columns.

### LINKED ISSUE #21853: Not possible to use different column name in multiple indexers for subscription
### Preconditions (*)

1. Magento 2.1.4 EE (and looking at the code I can see the same in 2.2.4 CE + 2.3.x dev CE)
2. Magento catalogsearch_fulltext indexer set to update by schedule

### Steps to reproduce (*)

1. Create custom indexer and mview on cataloginventory_stock_item with entity_column="item_id" instead of product_id used in catalogsearch_fulltext and set it to update by schedule
```
<view id="custom_stock_indexer" class="Acquia\CommerceManager\Model\Indexer\Stock" group="indexer">
        <subscriptions>
            <table name="cataloginventory_stock_item" entity_column="item_id" />
        </subscriptions>
    </view>
```

### Expected result (*)

1. Trigger should use item_id for custom indexer and product_id for catalogsearch_fulltext

### Actual result (*)

1. Trigger uses column name from the indexer last set to "update by schedule" (as per the steps to reproduce above it uses item_id for both)

### PR DESCRIPTION
**Pull request by nikunjkotecha**
Fixes: #21853 

### Related Pull Requests
https://github.com/magento/partners-magento2ee/pull/413

This is not final expected change and only here to show the issue and proposed direction for the fix.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=21857) <br/>All committers have signed the CLA.

**Comment by magento-engcom-team** [comment]
Hi @nikunjkotecha. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by orlangur** [comment]
@akaplya could you check if current behavior is intentional?

**Comment by aleron75** [comment]
Hello, I just experiencing the same issue and IMO it's not an intentional behavior since the result changes depending on the way you set the indexing mode on all the indexes or on a single one.

**Comment by josefbehr** [comment]
@magento-engcom-team How shall we proceed with this? Merge this proposed change for the time being, or is further work required?

**Comment by ihor-sviziev** [comment]
@sdzhepa @slavvka,
This PR got stuck for almost 1 year. 
Could you check what's wrong with it? Should we get approval?

**Comment by ihor-sviziev** [comment]
@slavvka you moved this PR to "on hold", could you describe why and what we're waiting for?

**Comment by slavvka** [comment]
@ihor-sviziev sorry for not having added the explanation. We are waiting for the review from Magento architect team

**Comment by ihor-sviziev** [comment]
@nikunjkotecha while we're waiting for Architecture team review - could you sign Adobe CLA?

**Comment by nikunjkotecha** [comment]
done

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 1]
```diff
@@ -117,8 +117,19 @@ public function create()
 
             // Add statements for linked views
             foreach ($this->getLinkedViews() as $view) {
+                // Store current column name for reverting back later.
+                $originalColumnName = $this->getColumnName();
```
Comment (lenaorobei) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php]: This solution looks like we are trying to hack the subscription logic by changing object property and misuse the `columnName `.
What we actually need is subscription column name, not the changelog column name (which is all the time the same).

**Review by lenaorobei — CHANGES_REQUESTED** [review]
Could you please change the logic in order to read the correct column name in the `buildStatement` method instead of `create` and `delete`.

The issue is caused because thе changelog is missing subscription column name.

**Comment by ihor-sviziev** [comment]
Hi @nikunjkotecha,
Will you be able to update your PR?

**Comment by nikunjkotecha** [comment]
> Hi @nikunjkotecha,
> Will you be able to update your PR?

I think yes, comment @lenaorobei is good enough for me to understand the place where the changes are expected. I'll spend time over weekend on this.

Please expect to have more discussion rounds, I'm not Magento expert and my bread and butter as of now is Drupal :D

File: lib/internal/Magento/Framework/Mview/View/Subscription.php (hunk 1 above)
Comment (nikunjkotecha) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: @lenaorobei I looked at the code again and your comment and it's a bit confusing
1/ It seems we both agree we need to use the subscription column name
2/ I'm not sure why you mention `not the changelog column name`, we need two column names - changelog column is for the changelog table and that's not going to change (even you mentioned same). What we need is to change how we read the subscription column name

My understanding, Subscription is created once for all the subscribers together and whichever subscription we modify last - columnName is used from that and re-used for all the triggers.

I've tried to simplify the code to make it look not (or less) hacky but to me it seems changes are required in the same direction as I've taken or a major rework would be required in how the subscriptions are created (refactor how the statement is built for linked views)

**Comment by ihor-sviziev** [comment]
@lenaorobei please review https://github.com/magento/magento2/pull/21857#discussion_r407189127

File: lib/internal/Magento/Framework/Mview/View/Subscription.php (hunk 1 above)
Comment (lenaorobei) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: You are right, we need both changelog and subscription column names, but `$this->getColumnName()` is changelog column, not the subscription one. 
I recommended to move the logic of getting its name to the `buildStatement` method in order to cover both cases - create and delete.

Comment (nikunjkotecha) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: We don't have any object / data available as of now in buildStatement to get the column name of the linked view for which buildStatement is called.

We can pass full view object or the way I've done to pass the subscription name, please advice

Comment (lenaorobei) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: I thought we can get `view` from the `changelog`.

Comment (nikunjkotecha) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: not at-least as per the interface

https://github.com/magento/magento2/blob/2.4-develop/lib/internal/Magento/Framework/Mview/View/ChangelogInterface.php

I may be wrong, please guide if I'm missing something here

Comment (lenaorobei) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: Got it.
Let's pass the view object then.

Comment (nikunjkotecha) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: Updated

**Comment by lenaorobei** [comment]
@nikunjkotecha looks like changes in this PR caused multiple tests failures. Could you please address that?

**Comment by lenaorobei** [comment]
Closing this PR due to inactivity. Please feel free to reopen if you are going to continue working on it.
Thank you.

**Comment by nikunjkotecha** [comment]
@lenaorobei Action item is on reviewers and maintainers to merge, can you please help understand if there is pending from my side?

**Comment by lenaorobei** [comment]
Provided changes caused integration and static tests failures which need to be addressed in order to move forward with this PR.

**Comment by nikunjkotecha** [comment]
ok, is the review passing? I'll start looking into this once you confirm the approach and pass the review

**Comment by lenaorobei** [comment]
Approach looks good to me.

**Comment by lenaorobei** [comment]
@magento run all tests

**Comment by nikunjkotecha** [comment]
@magento run all tests

**Comment by nikunjkotecha** [comment]
@magento run all tests

**Comment by nikunjkotecha** [comment]
@lenaorobei @ihor-sviziev @slavvka @orlangur @akaplya

Can someone please help here understand with the tests and to understand it's impact? I've very limited knowledge of Magento CORE.

I would really appreciate if someone pairs up and helps here in fixing the problem instead of PR staying here for long just because it's not passing tests and I've limited knowledge to fix them, I'm completely fine sharing the credits (or even if none are given).

**Comment by ihor-sviziev** [comment]
Hi @engcom-Charlie @engcom-Delta could you help with fixing the tests?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Moving this PR to the right state. Tests to be fixed.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8474](https://jira.corp.magento.com/browse/ENGCOM-8474) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@nikunjkotecha thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 2]
```diff
@@ -193,11 +191,23 @@ protected function getLinkedViews()
...
      * @return string
      */
-    protected function buildStatement($event, $changelog)
+    protected function buildStatement($event, $view)
     {
+        // Get the subscription for the specific view and specific table.
+        // We will use column name from it.
+        $subscriptions = $view->getSubscriptions() ?? [];
+        if (empty($subscriptions[$this->getTableName()])) {
+            return '';
```
Comment (gabrieldagama) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php]: Wouldn't be better to throw an exception here instead?

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 3]
```diff
@@ -236,7 +246,7 @@ protected function buildStatement($event, $changelog)
             $trigger,
             $this->connection->quoteIdentifier($this->resource->getTableName($changelog->getName())),
             $this->connection->quoteIdentifier($changelog->getColumnName()),
-            $this->connection->quoteIdentifier($this->getColumnName())
+            $this->connection->quoteIdentifier($subscription['column'])
```
Comment (gabrieldagama) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php]: Since we are dealing with arrays here, wouldn't be better to check if the key exists and throw an exception if not?

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 4]
```diff
@@ -193,11 +191,23 @@ protected function getLinkedViews()
...
-     * @param \Magento\Framework\Mview\View\ChangelogInterface $changelog
+     * @param \Magento\Framework\Mview\ViewInterface $view
      * @return string
      */
-    protected function buildStatement($event, $changelog)
+    protected function buildStatement($event, $view)
     {
+        // Get the subscription for the specific view and specific table.
+        // We will use column name from it.
+        $subscriptions = $view->getSubscriptions() ?? [];
```
Comment (gabrieldagama) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php]: I guess since the goal here is to get the `$subscription['column']` I would encapsulate this logic in a private function, at least it keeps the buildStatement a little simpler.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @nikunjkotecha, thanks for contributing!

I'm not sure if I'm missing something here, but shouldn't the `Subscription` object receive the correct table and column name on it's constructor? If the values on those properties aren't correct, maybe we should review how the object is being created.

Please let me know your thoughts, maybe I misunderstood something.

Cc @engcom-Charlie

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Mview/View/GetSubscriptionStatement.php [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+
+use Magento\Framework\App\ResourceConnection;
+use Magento\Framework\DB\Adapter\AdapterInterface;
+use Magento\Framework\DB\Ddl\Trigger;
+use Magento\Framework\Mview\ViewInterface;
+
+/**
+ * Returns subscription statement
+ */
+class GetSubscriptionStatement
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Mview/View/GetSubscriptionStatement.php]: Can we cover this class with some kind of automated test?

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 6]
```diff
@@ -188,26 +198,32 @@ protected function getLinkedViews()
...
+        );
+    }
 
+    /**
+     * Build trigger statement for INSERT, UPDATE, DELETE events
+     *
+     * @param string $event
+     * @param ChangelogInterface $changelog
+     * @return string
+     * @deprecated see \Magento\Framework\Mview\View\GetSubscriptionStatement
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php]: Could add some description why it was deprecated and use `@see \Magento\Framework\Mview\View\GetSubscriptionStatement` for reference?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests, Functional Tests B2B, Functional Tests CE

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 7]
```diff
@@ -193,11 +193,14 @@ protected function getLinkedViews()
      * Build trigger statement for INSERT, UPDATE, DELETE events
      *
      * @param string $event
-     * @param \Magento\Framework\Mview\View\ChangelogInterface $changelog
+     * @param ViewInterface $view
      * @return string
      */
-    protected function buildStatement($event, $changelog)
+    protected function buildStatement($event, $view)
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php]: Do you believe it's backward compatible change of changing argument type for existing protected method?
As for me it's not, and I saw your implementation where building statement was extracted to separate model, that approach looked better to me

**Comment by engcom-Charlie** [comment]
@ihor-sviziev looks like it's approved, please see https://github.com/magento/magento2/pull/21857#discussion_r407686618.
Extracting to a separate model is good for CE but on EE we have a lot of failures and it's too complicated for this issue since we have staging and need to use a different buildStatement() realizations which dependent on the table name.

**Comment by ihor-sviziev** [comment]
@gabrieldagama are you sure it's fine to change argument type for protected method?

**Comment by gabrieldagama** [comment]
@ihor-sviziev you are right, this change is backwards-incompatible, but, this class is not marked as API, so it is acceptable to make such changes.

**Comment by ihor-sviziev** [comment]
> @ihor-sviziev you are right, this change is backward-incompatible, but, this class is not marked as API, so I believe it is acceptable to make such changes.

In this case  - can we define argument types for changed methods?

File: lib/internal/Magento/Framework/Mview/View/Subscription.php (hunk 7 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php]: As we discussed with @gabrieldagama  - this changes is allowed since this class isn't marked with `@api` tag.
Could you define argument & return types here?

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests EE

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

one more time

**Comment by ihor-sviziev** [comment]
@engcom-Charlie the b2b tests failing. could you check why?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8474](https://jira.corp.magento.com/browse/ENGCOM-8474) has been created to process this Pull Request

File: lib/internal/Magento/Framework/Mview/View/Subscription.php [hunk 8]
```diff
@@ -250,10 +255,26 @@ protected function buildStatement($event, $changelog)
...
+     * Returns subscription column name by view
+     *
+     * @param ViewInterface $view
+     * @return string
+     */
+    private function getSubscriptionColumn(ViewInterface $view): string
+    {
+        $subscriptions = $view->getSubscriptions();
+        if (!isset($subscriptions[$this->getTableName()]['column'])) {
+            throw new \RuntimeException(sprintf('Column name for view with id "%s" doesn\'t exist', $view->getId()));
```
Comment (gabrieldagama) [inline lib/internal/Magento/Framework/Mview/View/Subscription.php:340]: We probably should catch this exception somewhere, as it is I guess it would return an error to the user and not useful message, we should add a proper error message for the user (wherever we catch this exception), and probably log a more descriptive error on logs.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, thanks for updating this PR.

Please have a look at my comment below and let me know your thoughts.

File: lib/internal/Magento/Framework/Mview/View/Subscription.php (hunk 8 above)
Comment (engcom-Charlie) [reply lib/internal/Magento/Framework/Mview/View/Subscription.php:340]: Hi @gabrieldagama, the exception is already being handled here
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Indexer/Controller/Adminhtml/Indexer/MassChangelog.php#L40
Could you please take a look?
Thank you.

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8474](https://jira.corp.magento.com/browse/ENGCOM-8474) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
QA not applicable. Moving this PR to _Extended Testing_ column

**Comment by engcom-Bravo** [comment]
### Manual testing scenario
1. Create a custom indexer that uses `item_id` for _catalogsearch_fulltext_
Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Mview/etc/mview.xsd">
    <view id="custom_stock_indexer" class="User\ModuleA\Model\CustomIndexer" group="indexer">
        <subscriptions>
            <table name="cataloginventory_stock_item" entity_column="item_id" />
        </subscriptions>
    </view>
</config>
```
2. Create two products, so that one of the products had different values in `item_id` and `product_id`. _2_ and _3_ for example. 
dif_ids
This is done for the visibility of the issue. Use the following steps:
- Go to Admin Panel and create two Simple Products
- Open database table `cataloginventory_stock_item`
- Delete the second line, in the table, which is for the second product
- From Admin Panel, open the second products page
- Change the _Quantity_, for example, and **Save** the product
Now the values in `item_id` and `product_id` should be different 
3. From Admin Panel, go to _System - Index Management_ and set _Catalog Search_ and _Custom indexer_ on **UPDATE BY SCHEDULE**
4. In PHP Storm, set breakpoint at lines 
- `173.  foreach ($this->dimensionProvider->getIterator() as $dimension)` of the file _{/.../app/code/Magento/CatalogSearch/Model/Indexer/Fulltext.php_ 
Selection_008
- and on the `execute` method of your Custom Indexer
execute
5. From Admin Panel, change the _Quantity_, for example, and **Save** the product
6. Run `bin/magento cron:run`
7. Observe the input parameter of the execute method 

**BEFORE** applying changes provided in the PR, In the Fulltext search execute, the input parameter is array with _2_ (value of `product_id` column)
entity_id_1
In the Custom indexer the input parameter is array with _2_ (value of `product_id` column)
entity_id_2

**AFTER** switching to the PR, 
In the Fulltext search execute, the input parameter is array with _4_ (value of `product_id` column)
after1
In the Custom indexer the input parameter is array with 2 (value of item_id column)
after2

Also tested by changing the `entity_column` to _qty_ in _mview.xml_
qty

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8474](https://jira.corp.magento.com/browse/ENGCOM-8474) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

The result is the same as in the report above https://github.com/magento/magento2/pull/21857#issuecomment-745238352

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Comment by gabrieldagama** [comment]
@magento run all tests
