### PR TITLE
Unable to insert widget with text value which contains }} string

### LINKED ISSUE #12087: Unable to insert widget with text value which contains }} string
### Preconditions

1. Magento 2.4-develop

### Steps to reproduce

1. Go to admin **Content -> Pages**
1. Click **Add New Page**
1. Set **Page Title** to `Page Title`
1. Expand **Content** section
1. In the content field, click **Insert Widget** button
1. Choose any widget which has at least one text input, e.g. **Catalog Products List**
1. Set widget title: `Title}}`
1. Click **Insert Widget**
1. Click **Save Page**
1. Go in frontend to see the page: \<base-url\>/page-title 

### Expected result

1. No errors

### Actual result

1. Widget content is incorrectly parsed
image

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#12087

### Manual testing scenarios (*)

1. Go to admin Content -> Pages
2. Click Add New Page
3. Set Page Title to Page Title
4. Expand Content section
5. In the content field, click Insert Widget button
6. Choose any widget which has at least one text input, e.g. Catalog Products List
7. Set widget title: Title}}
8. Click Insert Widget
9. Click Save Page
10. Go in frontend to see the page: <base-url>/page-title
11. Make sure that on page exist Widget with title "Title}}"

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run Static Tests

**Comment by engcom-Kilo** [comment]
@magento run Static Tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Widget/Model/Widget.php [hunk 1]
```diff
@@ -456,4 +460,65 @@ protected function sortParameters($firstElement, $secondElement)
...
+     *
+     * @param string $string
+     * @return string|string[]
+     */
+    private function encodeReservedChars($string)
+    {
+        $map = [
+            '{' => urlencode('{'),
+            '}' => urlencode('}')
+        ];
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]: I guess it would be better to have this as internal property. If we need to add a new char to this we would have to add it to encode and decode functions, what do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Kilo, thanks for the pull request, it looks good! Please follow a small comments on it. Also, can we cover it with MFTF tests?

Thanks!

File: app/code/Magento/Widget/Model/Widget.php [hunk 2]
```diff
@@ -456,4 +460,65 @@ protected function sortParameters($firstElement, $secondElement)
...
         return $aOrder < $bOrder ? -1 : ($aOrder > $bOrder ? 1 : 0);
     }
+
+    /**
+     * Encode reserved chars
+     *
+     * @param string $string
+     * @return string|string[]
+     */
+    private function encodeReservedChars($string)
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]: Let's add return type here.

File: app/code/Magento/Widget/Model/Widget.php [hunk 3]
```diff
@@ -456,4 +460,65 @@ protected function sortParameters($firstElement, $secondElement)
...
+        );
+    }
+
+    /**
+     * Decode reserved chars
+     *
+     * @param string $string
+     * @return array
+     */
+    public function decodeReservedChars($string)
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]: Let's add return type here.

File: app/code/Magento/Widget/Model/Widget.php [hunk 4]
```diff
@@ -456,4 +460,65 @@ protected function sortParameters($firstElement, $secondElement)
...
+    }
+
+    /**
+     * Is text type Widget parameter
+     *
+     * @param \Magento\Framework\DataObject $widget
+     * @param string $name
+     * @return bool
+     */
+    private function isTextType($widget, $name)
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]: Let's add return type here.

File: app/code/Magento/Widget/Block/Adminhtml/Widget/Options.php [hunk 5]
```diff
@@ -158,6 +159,10 @@ protected function _addField($parameter)
             $data['value'] = $parameter->getValue();
         }
 
+        if ($parameter->getType() == 'text' && $data['value'] != '') {
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Block/Adminhtml/Widget/Options.php]: To avoid the ` @SuppressWarnings(PHPMD.ExcessiveMethodLength)` we can create a private method and extract the IFs to handle the `$data['value']`, what do you think?

File: app/code/Magento/Widget/Model/Widget.php [hunk 6]
```diff
@@ -456,4 +460,65 @@ protected function sortParameters($firstElement, $secondElement)
...
+    {
+        $parameters = $widget->getParameters();
+
+        if (isset($parameters[$name]) && is_object($parameters[$name])) {
+            $type = $parameters[$name]->getType();
+            if ($type == 'text') {
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]:
```suggestion
            if ($type === 'text') {
```

**Review by gabrieldagama — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Widget/Model/Widget.php [hunk 7]
```diff
@@ -131,7 +143,7 @@ public function getWidgetByClassType($type)
      */
     public function getConfigAsXml($type)
     {
-        return $this->getXmlElementByType($type);
+        return $this->getWidgetByClassType($type);
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]: This seems BIC, changing the return type from `null|\Magento\Framework\Simplexml\Element` to `null|array`

File: app/code/Magento/Widget/Model/Widget.php [hunk 8]
```diff
@@ -296,42 +308,66 @@ public function getWidgetsArray($filters = [])
...
-            } elseif (trim($value) == '') {
-                $parameters = $widget->getParameters();
-                if (isset($parameters[$name]) && is_object($parameters[$name])) {
-                    $value = $parameters[$name]->getValue();
-                }
-            }
-            if (isset($value)) {
-                $directive .= sprintf(' %s="%s"', $name, $this->escaper->escapeHtmlAttr($value, false));
-            }
+            $directiveParams .= $value === null ? '' : $this->getDirectiveParam($widget, $name, $value);
```
Comment (gabrieldagama) [inline app/code/Magento/Widget/Model/Widget.php]: To avoid the ternary operator here, wouldn't be better to use an array_filter before the foreach? Like this:
```
array_filter($params, function($value) {
    return $value !== null;
})
```
It would be one step more before the foreach but since here we are processing just one widget I guess the performance impact is almost none and it would improve readability. What do you think?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Charlie, thanks for the updates here, it looks good! Pleases follow some small comments below, also, can you cover this PR with tests?

Thanks!

File: app/code/Magento/Widget/Model/Widget.php (hunk 7 above)
Comment (engcom-Charlie) [reply app/code/Magento/Widget/Model/Widget.php]: @gabrieldagama I changed `getXmlElementByType` to `getWidgetByClassType` because such i found in `obsolete_methods`.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
@engcom-Kilo thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Go to admin Content -> Pages
2. Click Add New Page
3. Set Page Title to `Page Title`
4. Expand **Content** section
5. n the content field, click Insert Widget button
6. Choose any widget which has at least one text input, e.g. **Catalog Products List**
7. Set widget title: `Title}}`
8. Click Insert Widget
9. Click Save Page
10. Go in frontend to see the page: _/page-title_
Make sure that on page exist Widget with title "`Title}}`"

**Before:** :heavy_multiplication_x: Widget content is incorrectly parsed

Screenshot from 2020-09-07 09-50-54
Screenshot from 2020-09-07 09-39-48

**After:** :heavy_check_mark: The Widget with the title "Title}}" exists on the page

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Widget/Model/Widget.php (hunk 7 above)
Comment (gabrieldagama) [reply app/code/Magento/Widget/Model/Widget.php]: If the `getWidgetByClassType` is really a substitute for `getXmlElementByType` let's create a new method and deprecate the old one.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8132](https://jira.corp.magento.com/browse/ENGCOM-8132) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

widget title:` Title}}`

**After:** :heavy_check_mark:  The Widget with the title "Title}}" exists on the page

Screenshot from 2020-09-10 14-32-51

widget title:` {{Title`

**After:** :heavy_check_mark:  The Widget with the title "{{Title" exists on the page

Screenshot from 2020-09-10 14-35-41
