### PR TITLE
Deploy all used locales

### LINKED ISSUE #29218: [Issue] Deploy all used locales
This issue is automatically created based on existing pull request: magento/magento2#28922: Deploy all used locales

---------

### Preconditions: (*)

`bin/magento setup:static-content:deploy --language=all` currently only
deploys en_US, instead of the requested "all". This pull request aims to deploy all used languages for the frontend and all configured languages by admin users, when no language parameter is given. en_US is always additionally deployed by default.

### Steps to reproduce (*)

1. Configure multiple store views with different locales.
2. Configure a locale other than en_US for your admin user.
3. run `bin/magento setup:static-content:deploy --language=all` and verify that all configured languages, plus en_US are deployed.
4. run `bin/magento setup:static-content:deploy --language=all --exclude-language=en_US` and verify that en_US is skipped.
5. run `bin/magento setup:static-content:deploy en_US` and verify that only en_US is deployed
6. run `bin/magento setup:static-content:deploy --language=en_US` and verify that only en_US is deployed
7. run `bin/magento setup:static-content:deploy -l en_US` and verify that only en_US is deployed
8. run `bin/magento setup:static-content:deploy --language=en_US en_UK` and verify that only en_UK is deployed as the languages argument precedes over the language option

**Actual Result:**

**Expected Result:**

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by AntonEvers**
### Description (*)

`bin/magento setup:static-content:deploy --language=all` currently only
deploys en_US, instead of the requested "all". This pull request aims to deploy all used languages for the frontend and all configured languages by admin users, when no language parameter is given. en_US is always additionally deployed by default.

### Manual testing scenarios (*)

1. Configure multiple store views with different locales.
2. Configure a locale other than en_US for your admin user.
3. run `bin/magento setup:static-content:deploy --language=all` and verify that all configured languages, plus en_US are deployed.
4. run `bin/magento setup:static-content:deploy --language=all --exclude-language=en_US` and verify that en_US is skipped.
5. run `bin/magento setup:static-content:deploy en_US` and verify that only en_US is deployed
6. run `bin/magento setup:static-content:deploy --language=en_US` and verify that only en_US is deployed
7. run `bin/magento setup:static-content:deploy -l en_US` and verify that only en_US is deployed
8. run `bin/magento setup:static-content:deploy --language=en_US en_UK` and verify that only en_UK is deployed as the languages argument precedes over the language option

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29218: Deploy all used locales

### CODE REVIEW

**Comment by AntonEvers** [comment]
@magento run all tests

**Comment by AntonEvers** [comment]
@magento run Unit Tests

**Comment by AntonEvers** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
Hi @AntonEvers. Thanks for collaboration. This PR was reviewed on Community Contribution Triage meeting. The recording of the meeting you can look by the [link](https://www.youtube.com/watch?v=gsefmmeDMWM&list=PLDvMskiz68Q2BLkj0-xzjuFl7ZVti9Quj&index=2&t=639s)

File: app/code/Magento/Deploy/Package/PackagePool.php [hunk 1]
```diff
@@ -41,22 +46,46 @@ class PackagePool
...
+        ?StoreView $storeView = null,
+        ?UserCollection $userCollection = null,
+        ?Locale $locale = null
     ) {
         $this->collector = $collector;
         $themeCollection->clear()->resetConstraints();
         $this->themes = $themeCollection->getItems();
         $this->packageFactory = $packageFactory;
+        $this->storeView = $storeView ?: ObjectManager::getInstance()->get(StoreView::class);
+        $this->userCollection = $userCollection ?: ObjectManager::getInstance()->get(UserCollection::class);
```
Comment (ihor-sviziev) [inline app/code/Magento/Deploy/Package/PackagePool.php]: collection should not be used in constructor as this object will be shared with other places and state will be kept that will lead to unexpected issues. 
Instead we need to use collection factory that will be automatically generated for the collection

File: app/code/Magento/Deploy/Package/PackagePool.php [hunk 2]
```diff
@@ -241,6 +270,47 @@ private function ensureRequiredLocales(array $options)
...
+     * Get used store and admin user locales.
+     *
+     * @return array
+     * @throws InvalidArgumentException if unknown locale is provided by the store configuration
+     */
+    private function getUsedLocales()
+    {
+        $usedLocales = array_merge(
+            $this->storeView->retrieveLocales(),
+            $this->getAdminUserInterfaceLocales()
```
Comment (ihor-sviziev) [inline app/code/Magento/Deploy/Package/PackagePool.php]: Let's assume we have only en_us locale on backend, but 5 locales on the frontend. Seems like this change will cause generating static content for those 5 locales that are used on frontend, which is redundant.
I think we need to differentiate frontend and backend locales.

Please correct me if I'm wrong.

File: app/code/Magento/Deploy/Package/PackagePool.php [hunk 3]
```diff
@@ -241,6 +270,47 @@ private function ensureRequiredLocales(array $options)
...
+
+    /**
+     * Get admin user locales
+     *
+     * @return array
+     */
+    private function getAdminUserInterfaceLocales()
+    {
+        $locales = [AppInterface::DISTRO_LOCALE_CODE];
+        foreach ($this->userCollection as $user) {
```
Comment (ihor-sviziev) [inline app/code/Magento/Deploy/Package/PackagePool.php]: Right now static content deploy could be ran on build environment that not contains any DB, details here https://devdocs.magento.com/guides/v2.4/config-guide/deployment/ .
Looks like this change brings back dependency to DB and breaks this ability. Could you double check it?
Rather than that I would suggest getting list of locales from config.php.
I'm not sure if we already could define list of locales used in admin in `config.php` file, but even if it doesn't - I think we could add such option.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@AntonEvers thank you so much for your contribution!
This is really important improvement!

File: app/code/Magento/Deploy/Package/PackagePool.php (hunk 2 above)
Comment (AntonEvers) [reply app/code/Magento/Deploy/Package/PackagePool.php]: This is indeed a welcome improvement and I will look into adding it to the PR. If it can be done without too big of an impact.

File: app/code/Magento/Deploy/Package/PackagePool.php (hunk 1 above)
Comment (AntonEvers) [reply app/code/Magento/Deploy/Package/PackagePool.php]: The userCollection is now a factory

File: app/code/Magento/Deploy/Package/PackagePool.php (hunk 2 above)
Comment (AntonEvers) [reply app/code/Magento/Deploy/Package/PackagePool.php]: This improvement is now part of the PR

File: app/code/Magento/Deploy/Package/PackagePool.php (hunk 3 above)
Comment (AntonEvers) [reply app/code/Magento/Deploy/Package/PackagePool.php]: The dependency on the DB has been removed by adding the following code:

```php
$connections = $this->deploymentConfig->get(ConfigOptionsListConstants::CONFIG_PATH_DB_CONNECTIONS, []);
if (empty($connections)) {
    return $this->usedAdminLocales;
}
```

Admin locales can now be added using the following `app/etc/env.php` config:
```php
    'force_deploy_admin_locales' => [
        'en_GB',
        'de_DE',
    ]
```

**Comment by AntonEvers** [comment]
@ihor-sviziev please let me know if this needs some cleaning up / relocation of logic. I can imagine that the coupling of objects is getting larger than desirable at the moment.

**Comment by AntonEvers** [comment]
@magento run all tests

**Comment by AntonEvers** [comment]
> @ihor-sviziev please let me know if this needs some cleaning up / relocation of logic. I can imagine that the coupling of objects is getting larger than desirable at the moment.

I went ahead and cleaned up a little. Please let me know if you see any issues with this.

**Comment by AntonEvers** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by AntonEvers** [comment]
@magento run Static Tests

File: lib/internal/Magento/Framework/Config/ConfigOptionsListConstants.php [hunk 4]
```diff
@@ -52,6 +52,11 @@ class ConfigOptionsListConstants
      */
     const CONFIG_PATH_FORCE_HTML_MINIFICATION = 'force_html_minification';
 
+    /**
+     * Parameter to force deploying certain languages for the admin, without any users having configured them yet.
+     */
+    const CONFIG_PATH_FORCE_ADMIN_LOCALE = 'force_deploy_admin_locales';
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Config/ConfigOptionsListConstants.php]: Unfortunately adding new constant to existing class is not backward compatible change and we can't accept it except cases when we don't have any other options.

I see we using this constant only in one case - I think we can safely move it to `LocaleResolver` class.

Also I don't like "force" here, maybe let's rename it to something like "admin_locales_for_deploy"?

**Comment by AntonEvers** [comment]
@magento run Unit Tests, Static Tests

**Comment by AntonEvers** [comment]
> @AntonEvers from first look - looks good, but let’s wait for test results. Also would be good to cover these changes with some automated tests, I think we need to have integration test there, similar to this https://github.com/magento/magento2/blob/40a787632f36ca67f8fff8c451e1e8d1bdbaf9f6/dev/tests/integration/testsuite/Magento/Setup/Console/Command/DependenciesShowFrameworkCommandTest.php will you be able to cover your change with such test?

Hi @ihor-sviziev, I am adding unit tests, integration tests are not yet present for this command, and I would like to keep the scope of this PR as small as possible. Would not like it to be delayed or failing because of the addition of such new testing.

So hopefully the unit tests will suffice.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Unit test looks good.

Please review my comments above & fix failing static test

File: lib/internal/Magento/Framework/Config/ConfigOptionsListConstants.php (hunk 4 above)
Comment (AntonEvers) [reply lib/internal/Magento/Framework/Config/ConfigOptionsListConstants.php]: @ihor-sviziev resolved

@magento run Semantic Version Checker, Static Tests, Unit Tests

**Comment by AntonEvers** [comment]
@magento run Semantic Version Checker, Static Tests, Unit Tests

**Comment by AntonEvers** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@AntonEvers really good job! now changes looks good. Please fix static tests and I’ll approve your PR.

**Comment by AntonEvers** [comment]
@magento run Static Tests

**Comment by AntonEvers** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]
Good job! Thank you so much for this improvement!

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7853](https://jira.corp.magento.com/browse/ENGCOM-7853) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
@magento create issue

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Configure multiple store views with different locales ( in my case **en_US**, **de_DE** and **fr_FR**);
2. Configure a locale other than en_US for your admin user.
3. Run in console: `bin/magento setup:static-content:deploy --language=all`;

**Before:** :heavy_multiplication_x:  only **en_US** are deployed;



**After:** :heavy_check_mark: All configured languages are deployed



4. Run in console:`bin/magento setup:static-content:deploy --language=all --exclude-language=en_US`

**After:** :heavy_check_mark: All configured languages except English are deployed



5.  Run in console: `bin/magento setup:static-content:deploy en_US`

**After:** :heavy_check_mark: Only en_US is deployed

Screenshot from 2020-07-21 12-59-55

6. Run in console: `bin/magento setup:static-content:deploy -l en_US`

**After:** :heavy_check_mark: Only en_US is deployed

Screenshot from 2020-07-21 12-59-55

7. Run in console: `bin/magento setup:static-content:deploy --language=en_US de_DE`

**After:** :heavy_check_mark: Only de_DE is deployed as the languages argument precedes over the language option

Screenshot from 2020-07-21 13-07-53
