### PR TITLE
Fix of Asynchronous opetations status issue

### LINKED ISSUE #29718: Wrong handling some of asynchronous bulk operations and related mysql queue messages in Magento 2.4.0
### Preconditions (*)

1. Magento version: **2.4.0** 
2. Configured cron for running message queue consumers.

### Steps to reproduce (*)
1. On the product grid in the backend perform massaction to update attribute values for couple products ("check" products and select "Update Attributes" action from "Actions" dropdown).
2. Set values for needed attributes or/and assign products to websites and save.
3. After the page reloads will be displayed a message  like "Task "Update attributes for N selected products": 1 item(s) have been scheduled for an update."
4. Wait some time and reload the backend page.

### Expected result (*)
1. Displayed messages like "1 item(s) have been successfully updated...".
2. Attribute values for related products updated.
2. In DB new record in "magento_bulk" and new record(s) in "magento_operation" table (operations related to the bulk).
3. New record(s) in the  "queue_message" (related to the queues "product_action_attribute.update" and/or product_action_attribute.website.update) and new related record(s) in the "queue_message_status" table with status "4". 

### Actual result (*)

1. In system messages still displayed a message like "Task "Update attributes for N selected products": 1 item(s) have been scheduled for an update."
2. Attribute values for the products updated.
3. A new record in "message_bulk" table but no related record(s) in "magento_operation" table.
4. New related records in "queue_message" and "queue_message_status" tables but records in the last table with error stauts (status value "6").
5. In magento system.logs added string with error:  _main.CRITICAL: Message has been rejected: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'operation_key' cannot be null, query was: INSERT INTO `magento_operation` (`id`, `bulk_uuid`, `topic_name`, `serialized_data`, `result_serialized_data`, `status`, `error_code`, `result_message`, `operation_key`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) [] []_

During debugging I found out that since Magento 2.4.0 version into "magento_operation" table was added new required (not nullable) column 'operation_key'. But neither controller action which schedules updated product attributes update bulk (\Magento\Catalog\Controller\Adminhtml\Product\Action\Attribute\Save::publish()) nor consumer which executes related messages and updates bulk status(\Magento\Catalog\Model\Attribute\Backend\Consumer::process()) does setting "operation_key" value into related operation. And during an attempt to save operation in the consumer (app/code/Magento/Catalog/Model/Attribute/Backend/Consumer.php:140) trows exception. As result operation is not saved and the status of the reladed message in the "queue_message_status" saved with value "6".

Also, the same problem for code that pushes/handles bulks related to the "media.storage.catalog.image.resize" queue.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by nuzil**
### Description (*)
Fix of Asynchronous opetations status issue. When using MYSQL Async queues. Caused by provided in 2.4 release new database field, which is not required to have for Mysql queues.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#29718

### Manual testing scenarios (*)
See Issue.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: dev/tests/integration/testsuite/Magento/Catalog/Model/Attribute/Backend/ConsumerTest.php [hunk 1]
```diff
@@ -0,0 +1,149 @@
...
+        $this->publisherMock = $this->getMockForAbstractClass(BulkPublisherInterface::class);
+
+        $this->bulkManagement = $this->objectManager->create(
+            BulkManagement::class,
+            [
+                'publisher' => $this->publisherMock
+            ]
+        );
+        $this->bulkStatus = $this->objectManager->get(BulkStatus::class);
+        $catalogProductMock = $this->createMock(\Magento\Catalog\Helper\Product::class);
```
Comment (rogyar) [inline dev/tests/integration/testsuite/Magento/Catalog/Model/Attribute/Backend/ConsumerTest.php]: Hi @nuzil. What do you think about using imports everywhere instead of FQN? Currently, we use both. But I believe we may make the code a little bit more readable by using the same approach for all places.

Just a minor suggestion

**Comment by rogyar** [comment]
@magento run all tests

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Comment by VladimirZaets** [comment]
@magento I am working on it

**Review by sidolov — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-8108](https://jira.corp.magento.com/browse/ENGCOM-8108) has been created to process this Pull Request
:eight_spoked_asterisk: @sidolov, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Charlie** [comment]
Hi @nuzil, can you please fix static tests?
Thank you.

**Review by engcom-Charlie — CHANGES_REQUESTED** [review]
@nuzil please fix static failures.
Thank you.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magento run Integration tests

**Comment by nuzil** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@engcom-Charlie 
Looks like failed tests are not connected to PR

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8108](https://jira.corp.magento.com/browse/ENGCOM-8108) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

1. :heavy_check_mark: Displayed messages like "1 item(s) have been successfully updated...".

Screenshot from 2020-09-21 13-54-31

2. :heavy_check_mark:  Attribute values for related products updated.

3. :heavy_check_mark: New record(s) in the "queue_message" (related to the queues "product_action_attribute.update" and/or product_action_attribute.website.update) and new related record(s) in the "queue_message_status" table with status "4".




4. :heavy_check_mark:  No errors in `system.log` file
