### PR TITLE
[PHPDOC] Fix bad phpdoc for Magento\Framework\Message\ManagerInterface

### LINKED ISSUE #39593: [Issue] [PHPDOC] Fix bad phpdoc for Magento\Framework\Message\ManagerInterface
This issue is automatically created based on existing pull request: magento/magento2#39153: [PHPDOC] Fix bad phpdoc for Magento\Framework\Message\ManagerInterface

---------
### Description (*)

This PR fix the bad phpdoc for `\Magento\Framework\Message\ManagerInterface` and remove all duplicate phpdoc in `\Magento\Framework\Message\Manager` (use inheritdoc syntaxe).

Actually all `add*Message` functions (addErrorMessage,  addSuccess, addWarningMessage, ...) accept a `string` value in `$message` variable. 

This PR allows to pass either a `\Magento\Framework\Phrase` or a `string`.

Here is an example where the type `\Magento\Framework\Phrase` is used :

https://github.com/magento/magento2/blob/0cfe4a36b72cde1ecd9613b70bac0d34a2f8f1ed/app/code/Magento/Checkout/Controller/Cart/Delete.php#L38

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :(

Capture d’écran du 2024-09-10 14-39-16

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by dimitriBouteille**
### Description (*)

This PR fix the bad phpdoc for `\Magento\Framework\Message\ManagerInterface` and remove all duplicate phpdoc in `\Magento\Framework\Message\Manager` (use inheritdoc syntaxe).

Actually all `add*Message` functions (addErrorMessage,  addSuccess, addWarningMessage, ...) accept a `string` value in `$message` variable. 

This PR allows to pass either a `\Magento\Framework\Phrase` or a `string`.

Here is an example where the type `\Magento\Framework\Phrase` is used :

https://github.com/magento/magento2/blob/0cfe4a36b72cde1ecd9613b70bac0d34a2f8f1ed/app/code/Magento/Checkout/Controller/Cart/Delete.php#L38

For example, with PHPSTAN is very complicated to setup the project with level 5 or higher :(

Capture d’écran du 2024-09-10 14-39-16

### Related Pull Requests

None

### Fixed Issues (if relevant)

None

### Manual testing scenarios (*)

Setup PHPSTAN with level 5 or higher and run check.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#39593: [PHPDOC] Fix bad phpdoc for Magento\Framework\Message\ManagerInterface

### CODE REVIEW

**Comment by dimitriBouteille** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @dimitriBouteille,

Thanks for the contribution!

The changes look good to us. However, please address the failed tests, particularly the static tests.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@engcom-Hotel, I have fixed the static test failures. Requesting for the review.

Thank you!

**Comment by dimitriBouteille** [comment]
Hi @engcom-Charlie 

I see the MR in `Progress: needs update`, do I need to do something else?

**Comment by engcom-Charlie** [comment]
> Hi @engcom-Charlie
> 
> I see the MR in `Progress: needs update`, do I need to do something else?

Hi @dimitriBouteille,

The bot assigned Progress: needs update label to this PR because there was a review change requested [here](https://github.com/magento/magento2/pull/39153#pullrequestreview-2506034221). I have taken care of static test failures now so removing the same.

File: lib/internal/Magento/Framework/Message/Manager.php [hunk 1]
```diff
@@ -79,16 +81,16 @@ public function __construct(
...
     ) {
         $this->session = $session;
         $this->messageFactory = $messageFactory;
         $this->messagesFactory = $messagesFactory;
         $this->eventManager = $eventManager;
         $this->logger = $logger;
         $this->defaultGroup = $defaultGroup;
-        $this->exceptionMessageFactory = $exceptionMessageFactory ?: ObjectManager::getInstance()
-            ->get(ExceptionMessageLookupFactory::class);
+        $this->exceptionMessageFactory = $exceptionMessageFactory ?: $exceptionMessageLookupFactory;
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Message/Manager.php]: To make this change backward compatible, please use ObjectManager to initialize `$exceptionMessageLookupFactory`

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @dimitriBouteille,

Please refer to my review comment below.

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@engcom-Hotel the review comments has been taken care and I have fixed the static test failures too hence requesting for the review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
No manual testing is required here, as only the bad doc blocks are getting updated here. Currently moving this PR to Extended Testing as the build is failing.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
The Integration test failures are the known issues.
[Run 1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/8f82610ed279d42193cdd7ead5209cfd/Integration/console-error-logs.html) and [Run 2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/8f82610ed279d42193cdd7ead5209cfd/Integration/console-error-logs.html)

**Known Issue:**
[AC-13584](https://jira.corp.adobe.com/browse/AC-13584)

One of the test failure of Functional CE in the recent 2 builds is not consistent and the consistent one is a known issue. The failures are neither part of this PR nor failing because of the PR changes. Hence moving this PR to Merge in progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/49fc9286695b52064ef79467cb7082cb/Functional/allure-report-ce/index.html#categories/e93c564a2dcd5e30ee0e0e811a828c2b/d58fef795b7f04e7/
image


**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/94391ff564ee797fd51baccb033093cc/Functional/allure-report-ce/index.html#categories

image


Known Issue:
[AC-13608](https://jira.corp.adobe.com/browse/AC-13608): StorefrontCreateCustomerWithInvalidDataTest

**Comment by ihor-sviziev** [comment]
@magento create issue

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 2]
```diff
@@ -50,7 +50,7 @@ public function addMessages(array $messages, $group = null);
     /**
      * Adds new error message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 3]
```diff
@@ -61,7 +61,7 @@ public function addError($message, $group = null);
     /**
      * Adds new warning message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 4]
```diff
@@ -72,7 +72,7 @@ public function addWarning($message, $group = null);
     /**
      * Adds new notice message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 5]
```diff
@@ -83,7 +83,7 @@ public function addNotice($message, $group = null);
     /**
      * Adds new success message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 6]
```diff
@@ -94,7 +94,7 @@ public function addSuccess($message, $group = null);
     /**
      * Adds new error message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 7]
```diff
@@ -103,7 +103,7 @@ public function addErrorMessage($message, $group = null);
     /**
      * Adds new warning message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 8]
```diff
@@ -112,7 +112,7 @@ public function addWarningMessage($message, $group = null);
     /**
      * Adds new notice message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

File: lib/internal/Magento/Framework/Message/ManagerInterface.php [hunk 9]
```diff
@@ -121,7 +121,7 @@ public function addNoticeMessage($message, $group = null);
     /**
      * Adds new success message
      *
-     * @param string $message
+     * @param string|\Magento\Framework\Phrase $message
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/ManagerInterface.php]:
```suggestion
     * @param string|\Stringable $message
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Based on discussion in https://github.com/magento/magento2/pull/39572#pullrequestreview-2586329086 and https://github.com/magento/magento2/pull/39572#issuecomment-2627298859
we agreed to use a `\Stringable` interface.

Let's update this PR to make it more consistent in all places

**Comment by dimitriBouteille** [comment]
@ihor-sviziev Done :rocket:

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Message/Manager.php [hunk 10]
```diff
@@ -79,16 +85,18 @@ public function __construct(
         Event\ManagerInterface $eventManager,
         LoggerInterface $logger,
         $defaultGroup = self::DEFAULT_GROUP,
-        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null
+        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null,
+        ?ExceptionMessageLookupFactory $exceptionMessageLookupFactory = null
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/Manager.php]: @dimitriBouteille, I just wonder why it's needed.

File: lib/internal/Magento/Framework/Message/Manager.php [hunk 11]
```diff
@@ -79,16 +85,18 @@ public function __construct(
...
         $this->messageFactory = $messageFactory;
         $this->messagesFactory = $messagesFactory;
         $this->eventManager = $eventManager;
         $this->logger = $logger;
         $this->defaultGroup = $defaultGroup;
-        $this->exceptionMessageFactory = $exceptionMessageFactory ?: ObjectManager::getInstance()
-            ->get(ExceptionMessageLookupFactory::class);
+        $this->exceptionMessageFactory = $exceptionMessageFactory ?:
+            ($this->exceptionMessageLookupFactory = $exceptionMessageLookupFactory ?:
+                ObjectManager::getInstance()->get(ExceptionMessageLookupFactory::class));
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/Manager.php]: and this?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 10 above)
Comment (dimitriBouteille) [reply lib/internal/Magento/Framework/Message/Manager.php]: I don't kown, is not my code 😂

**Comment by engcom-Charlie** [comment]
As @ihor-sviziev started reviewing the PR again, moving it back to Changes Requested from Merge in Progress.

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 10 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Message/Manager.php]: @engcom-Charlie could you please explain this?

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 11 above)
Comment (dimitriBouteille) [reply lib/internal/Magento/Framework/Message/Manager.php]: Same, not my code 😂

https://github.com/magento/magento2/pull/39153/commits/c8abbb92ac1b581d388ce1875e5e925b4249187f

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 10 above)
Comment (engcom-Charlie) [reply lib/internal/Magento/Framework/Message/Manager.php]: @ihor-sviziev on prior implementation, in https://github.com/magento/magento2/pull/39153/commits/0c33ab925541ca1cc1ab68c1bfaf92fe97ba58ae, PR was showing [static](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/88de68b01ca0359a43b11b6cac8973b3/Statics/console-error-logs.html) test failures which we have conveyed in [here](https://github.com/magento/magento2/pull/39153#pullrequestreview-2506034221). We have fixed them in [here](https://github.com/magento/magento2/commit/c8abbb92ac1b581d388ce1875e5e925b4249187f)

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 11 above)
Comment (engcom-Charlie) [reply lib/internal/Magento/Framework/Message/Manager.php]: @ihor-sviziev, as per [this](https://github.com/magento/magento2/pull/39153#pullrequestreview-2517351517) review comment, I have implemented these changes.

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Message/Manager.php]: Ok, I looked on it deeper - and see that it was added to fix the following static test failure:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/25b42fa255012f82d219680ffcfcce6b/Statics/console-error-logs.html
```
PHP Code Sniffer detected 1 violation(s): 

FILE: /var/www/html/lib/internal/Magento/Framework/Message/Manager.php
------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------
 24 | WARNING | Visibility must be declared on all constants if your project supports PHP 7.1 or later
 91 | ERROR   | Class ExceptionMessageLookupFactory needs to be requested in constructor, otherwise compiler will not
    |         | be able to find and generate this class
------------------------------------------------------------------------------------------------------------------------
```

---
I reviewed the static test - and it try to detect auto-generated factory and complain about it. And it looks just like the class name.
Ref to static test https://github.com/magento/magento-coding-standard/blob/d7ece6da506db4fadaa63c7ae31d15f1d9ff1443/Magento2/Sniffs/PHP/AutogeneratedClassNotInConstructorSniff.php#L92


---
However, in this specific case, the class ExceptionMessageLookupFactory actually NOT auto-generated, it's located in https://github.com/magento/magento2/blob/d253a44cee2ac9b3d433bb1b2d86ed3000e40a4f/lib/internal/Magento/Framework/Message/ExceptionMessageLookupFactory.php#L9.

So that, this is a false-positive, that has to be ignored, and the changes has to be reverted.

```suggestion
        $this->exceptionMessageFactory = $exceptionMessageFactory ?: ObjectManager::getInstance()
            ->get(ExceptionMessageLookupFactory::class);
```

@engcom-Charlie could you please fix that?

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 10 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Message/Manager.php]: As desribed in https://github.com/magento/magento2/pull/39153/files#r1950728162, this change should be reverted.

```suggestion
        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null
```

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 11 above)
Comment (engcom-Charlie) [reply lib/internal/Magento/Framework/Message/Manager.php]: @ihor-sviziev thank you for this input. I aggre with false positive case of isClassAutogenerated but fhe function validateRequestedClass() also check for isConstructorParameter().  what do you think about this.

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Message/Manager.php]: @engcom-Charlie The constructor asking for the interface, while this class requires a specific factory, that implements that interface - as for me - as to me, in this specific case, all is good, we can ignore it.

Comment (engcom-Charlie) [reply lib/internal/Magento/Framework/Message/Manager.php]: Okay @ihor-sviziev. I have reverted c8abbb9. Please review it, I will proceed further after the build result.

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Message/Manager.php [hunk 12]
```diff
@@ -79,7 +79,7 @@ public function __construct(
         Event\ManagerInterface $eventManager,
         LoggerInterface $logger,
         $defaultGroup = self::DEFAULT_GROUP,
-        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null
+        ExceptionMessageFactoryInterface $exceptionMessageFactory = null
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Message/Manager.php]: Let's revert this change:
```suggestion
        ?ExceptionMessageFactoryInterface $exceptionMessageFactory = null
```

File: lib/internal/Magento/Framework/Message/Manager.php (hunk 11 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Message/Manager.php]: @engcom-Charlie, I see you also removed `?` from the beginning of the constructor argument, which isn't correct.

Also, I think we need to ignore the line on which static test failed, e.g. this should work:
```php
        $this->exceptionMessageFactory = $exceptionMessageFactory ?: ObjectManager::getInstance()
            ->get(ExceptionMessageLookupFactory::class); // phpcs:ignore
```

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests, Functional Tests CE, Functional Tests EE

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Charlie** [comment]
The review changes have been implemented and approved hence moving it to Ready for Testing.

**Comment by engcom-Charlie** [comment]
No manual testing is required here, as only the bad doc blocks are getting updated. Currently moving this PR to Extended Testing as the build is failing.

**Comment by engcom-Charlie** [comment]
@magento run WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Unit Tests

**Comment by engcom-Charlie** [comment]
Hi @dimitriBouteille,

As I am working on the build stabilization activity of this PR, requesting you to please don't merge latest codebase in this PR.  If any input needed from your end will let you know.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Integration Tests

**Comment by engcom-Charlie** [comment]
One of the **Functional B2B** test failure is inconsistent in the last two builds, it seem to be flaky and the other one is a known issue. They neither part of PR nor failing because of the PR changes. 

**Run 1:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/6b368458733182aecc9a07f0fcf2b7a6/Functional/allure-report-b2b/index.html#categories/2fc037f47773dd7551f2e766bbf34efa/d01814eab6700437/

image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/b8a9c797d4d64520188c53b5cfae1e14/Functional/allure-report-b2b/index.html#categories
image

**Known Issue:**
StorefrontAssertAsLowAsLabelTest: [ACQE-7389](https://jira.corp.adobe.com/browse/ACQE-7389)

One of the **Functional CE** test failure is inconsistent in the last two builds, it seem to be flaky . They neither part of PR nor failing because of the PR changes. Hence moving it to Merge In Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/81d5a862903c6903ed35b5ab74dc7190/Functional/allure-report-ce/index.html#categories
image


**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39153/3e5cd018f3060fafd0c32d7d158f7fc2/Functional/allure-report-ce/index.html#categories

image
