### PR TITLE
Insert design/footer/absolute_footer before </body> tag (Fixes #3333)

### LINKED ISSUE #3333: Footer Miscellaneous HTML Not working
I'm trying add a tracking code to a Magento2 using admin panel from

General -> Design -> Footer -> Miscellaneous HTML.

The data is getting saved properly, but it does not get displayed on the HTML (just before body closing tag).

I did a code base search for the config setting `absolute_footer` but could not find any reference of the system setting in the code.

### PR DESCRIPTION
**Pull request by stefandoorn**
The design/footer/absolute_footer content is not inserted before </body>. It is included in the config area of the admin, but in the rest of the code the 'absolute_footer' ain't used anywhere. This is a change to solve this issue. I'm not 100% sure this is the way Magento would like this feature to be inserted, but if so I'm happy to contribute.

### CODE REVIEW

File: app/code/Magento/Theme/Block/Html/Footer.php [hunk 1]
```diff
@@ -86,6 +93,22 @@ public function getCopyright()
     }
 
     /**
+     * Retrieve Miscellaneous HTML information
+     *
+     * @return string
+     */
+    public function getMiscellaneousHtml()
+    {
+        if (!$this->_misc) {
```
Comment (vkublytskyi) [inline app/code/Magento/Theme/Block/Html/Footer.php]: As `Magento\Framework\App\Config\ScopeConfigInterface::getValue` returns `mixed` value it's not safe to use this comparison to check is data loaded or not. In such cases (when value may be any type) additional property should be used.

File: app/code/Magento/Theme/Block/Html/Footer.php [hunk 2]
```diff
@@ -20,6 +20,13 @@ class Footer extends \Magento\Framework\View\Element\Template implements \Magent
     protected $_copyright;
 
     /**
+     * Miscellaneous HTML information
+     *
+     * @var string
+     */
+    protected $_misc;
```
Comment (vkublytskyi) [inline app/code/Magento/Theme/Block/Html/Footer.php]: Please declare new property as `private` if you don't have strong reasons to use `protected`.
As Magento 2 follows  [PSR-2](http://www.php-fig.org/psr/psr-2/) please do not use single underscores in **new** property names.
For more information see [Magento PHP Coding Standarts](http://devdocs.magento.com/guides/v2.0/coding-standards/code-standard-php.html)

Name of property is to general. Please use more descriptive names (e.g. $miscellaneousHtml)

File: app/code/Magento/Theme/view/frontend/templates/html/absolute_footer.phtml [hunk 3]
```diff
@@ -0,0 +1,10 @@
+<?php
+/**
+ * Copyright © 2015 Magento. All rights reserved.
+ * See COPYING.txt for license details.
+ */
+
+// @codingStandardsIgnoreFile
```
Comment (vkublytskyi) [inline app/code/Magento/Theme/view/frontend/templates/html/absolute_footer.phtml]: New files should not ignore coding standards

**Comment by vkublytskyi** [comment]
@stefandoorn, thank you for this PR. You 100% follows Magento way and your contribution helps us to achieve state of code that we strive to.
If possible, please correct your implementation to meet Magento current coding standards.

**Comment by stefandoorn** [comment]
@vkublytskyi Thanks. I will check the suggestions in the upcoming days.

**Comment by stefandoorn** [comment]
@vkublytskyi Adjustments have been made. Thanks.

**Comment by slavvka** [comment]
@stefandoorn, your PR has been merged. See 5e9691d, 0b47c71 and d46fb12. Thank you for your contribution to Magento 2!
