### PR TITLE
#37509 | Verification added to redis preloading to prevent array_comb…

### LINKED ISSUE #37509: Redis preloading fails when exec() returns false
### Preconditions and environment

- Magento 2.x
- Redis 6.0.10 (Probably every version of Redis)
- phpredis

### Steps to reproduce

1. Install Magento 2 as normal
2. Enable Redis in env.php under cache->frontend->default
3. Make sure to set `backend` option to `Magento\\Framework\\Cache\\Backend\\Redis`
4. Set `id_prefix` and `preload_keys`
5. Run `bin/magento cache:clean`

This might not reproduce the issue in a lot of the cases because in normal scenarios there would be no issues. This issue arises as an edge-case when `\Magento\Framework\Cache\Backend\Redis::load` is being called. 
`$this->preloadedData = array_filter(array_combine($this->preloadKeys, $redis->exec()));` expects the second parameter of `array_combine` to be an array, but `$redis->exec()` can return `false` in some cases. Leading to an unexpected exception and inability to run `cache:clean` or similar commands that preload keys in Redis.

### Expected result

I expect the cache:clean command to finish without an error.

### Actual result

The following exception is thrown:
`array_combine(): Argument #2 ($values) must be of type array, bool given`

### Additional information

The issue is not immediately apparent, but makes more sense when you look into what the `\Cm_Cache_Backend_Redis` class is doing, which is the class the Magento Redis adapter extends from. The `Cm_Cache_Backend_Redis` class pipes the requested method through to `Credis_Client`, which in turn pipes the request to phpredis. The method signature for `exec()` in `Credis_Client` tells us that the return value will always be of the type `array`, but when checking the implementation in phpredis, `exec()` can return false. Causing the preloading in Magento to fail.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by LeanderFS**
…ine receiving false as second argument

### Description (*)
This change will ensure the preloading code will continue to run even when `exec()` returns `false`.

### Fixed Issues (if relevant)
1. Fixes magento/magento2#37509

### Manual testing scenarios (*)
See #37509

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Cache/Backend/Redis.php [hunk 1]
```diff
@@ -51,7 +51,10 @@ public function load($id, $doNotTestCacheValidity = false)
                 $redis->hGet(self::PREFIX_KEY . $key, self::FIELD_DATA);
             }
 
-            $this->preloadedData = array_filter(array_combine($this->preloadKeys, $redis->exec()));
+            $redisResponse = $redis->exec();
+            $this->preloadedData = $redisResponse ?
```
Comment (engcom-Hotel) [inline lib/internal/Magento/Framework/Cache/Backend/Redis.php]: I suggest you check here if the `redisResponse` is an array, then only do the further action otherwise set an empty array.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @LeanderFS,

Please look into my review comments. Also can you please cover this change with some automated tests like unit tests by mocking the object?

Thanks

File: lib/internal/Magento/Framework/Cache/Backend/Redis.php (hunk 1 above)
Comment (engcom-Echo) [reply lib/internal/Magento/Framework/Cache/Backend/Redis.php]: `$redis->exec() `return array so not required.

Comment (engcom-Hotel) [reply lib/internal/Magento/Framework/Cache/Backend/Redis.php]: Here the method signature for `exec()` in `Credis_Client` class tells us that it returns `array` only but internally as per the documentation of [credis](https://github.com/colinmollenhour/credis), for better performance wraps the [phpredis](https://github.com/phpredis/phpredis) library when available. but when checking the implementation in phpredis, exec() can return Redis|array|false also. Thats why I asked to add a check here if the return value is array then only move further.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE

**Comment by engcom-Hotel** [comment]
Failed Functional tests are different in 2 consecutive runs:

**Functional Tests CE:**
image

image

**Functional Tests EE:**
image

image

Failed tests seem flaky to me, hence moving further with this PR.

Thanks

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
:heavy_check_mark: QA Passed

### Preconditions
- Magento 2.x
- Redis 6.0.10 (Probably every version of Redis)
- phpredis


### Manual Testing Scenario
1. Install Magento 2 as normal
2. Enable Redis in env.php under cache->frontend->default
3. Make sure to set `backend` option to `Magento\\Framework\\Cache\\Backend\\Redis`
4. Set `id_prefix` and `preload_keys`
5. Run `bin/magento cache:clean`

**Actual Result:** :heavy_check_mark:
image

**After:** :heavy_check_mark:  
image

**Before:** :heavy_multiplication_x: 

image

**Tested all the manual scenarios, no impact on regression testing.** 

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests CE

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE

**Comment by engcom-Hotel** [comment]
Failed tests are flaky, hence moved PR in `Merge in progress`. Please have a look at the below screenshot for reference:

image

Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests
