### PR TITLE
Fix validate-emails rule for ui component

### LINKED ISSUE #38528: [Issue] Fix validate-emails rule for ui component
This issue is automatically created based on existing pull request: magento/magento2#33470: Fix validate-emails rule for ui component

---------

### Description (*)

Fix validation rule `validate-emails` for using in ui-component:
- Fix wrong method `strip()` => `trim()`
- Sync logic with `lib/web/mage/validation.js`

Example usage:
```xml
<field name="description" formElement="textarea">
    <settings>
        <validation>
            <rule name="validate-emails" xsi:type="boolean">true</rule>
        </validation>
        <dataType>text</dataType>
        <label translate="true">Emails</label>
        <visible>true</visible>
        <dataScope>emails</dataScope>
    </settings>
</field>
```

image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by tuanpht**
### Description (*)

Fix validation rule `validate-emails` for using in ui-component:
- Fix wrong method `strip()` => `trim()`
- Sync logic with `lib/web/mage/validation.js`

Example usage:
```xml
<field name="description" formElement="textarea">
    <settings>
        <validation>
            <rule name="validate-emails" xsi:type="boolean">true</rule>
        </validation>
        <dataType>text</dataType>
        <label translate="true">Emails</label>
        <visible>true</visible>
        <dataScope>emails</dataScope>
    </settings>
</field>
```

image

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38528: Fix validate-emails rule for ui component

### CODE REVIEW

**Comment by tuanpht** [comment]
@magento run all tests

**Comment by tuanpht** [comment]
Failing Functional Tests are not related. What should I do?

File: app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js [hunk 1]
```diff
@@ -879,17 +879,18 @@ define([
             }
         ],
         'validate-emails': [
+            // TODO: logic is same in lib/web/mage/validation.js. Should we uniform?
```
Comment (Den4ik) [inline app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js]: Please remove comment

**Review by Den4ik — CHANGES_REQUESTED** [review]

File: app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js (hunk 1 above)
Comment (tuanpt-0634) [reply app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js:882]: Originally, I added to refer to duplicated logic in `lib/web/mage/validation.js`. Could you tell me why we should remove it, is it related to `TODO:` notation?

Comment (tuanpht) [reply app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js]: Originally, I added to refer to duplicated logic in `lib/web/mage/validation.js`. Could you tell me why we should remove it, is it related to `TODO:` notation?

Comment (Den4ik) [reply app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js]: @tuanpht In fact we have multiple duplicated code for validation and I don't see any real useful information in this comment. It's just increase file size

Comment (tuanpht) [reply app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js]: Ok, I thought Magento have feature "Minify JavaScript Files" which removes spaces, line breaks, and comments, but I haven't tried it yet

I had already mention the reference in commit message, so I will remove this comment

Comment (tuanpht) [reply app/code/Magento/Ui/view/base/web/js/lib/validation/rules.js]: I updated. Sorry, do I need to run test again?

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@tuanpht In my opinion all looks good

**Comment by tuanpht** [comment]
@magento run Unit Tests

**Comment by tuanpht** [comment]
@magento run WebAPI Tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Functional Tests B2B

**Comment by tuanpht** [comment]
@magento run WebAPI Tests

**Review by ArthurHW — APPROVED** [review]

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run Static Tests

**Comment by engcom-Dash** [comment]
Manual testing is not required as this change replaces the incorrect strip method with the correct trim method, ensuring proper string handling; the regex update also enhances email validation by supporting a wider range of characters, including special ones.

Builds are failed. Hence, moving this PR to Extended Testing.

**Comment by engcom-Dash** [comment]
@magento run Static Tests, Functional Tests B2B

**Comment by engcom-Dash** [comment]
@magento run Static Tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
Moving to merge in progress.
image

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Dash** [comment]
The Functional CE seems to be flaky and inconsistent. They are not failing because of the code changes done in PR nor part of this PR.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33470/e13f3af66c248df72928e671cc68dc43/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33470/58164762c1b0b8184a346610f16b92ef/Functional/allure-report-ce/index.html#categories/bdbf199525818fae7a8651db9eafe741

image

The Integration Tests Failures are consistent and its a known issue.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33470/35a6d39a8cdf048495c86b77c288afa6/Integration/console-error-logs.html

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/33470/85dc22782e571f502dbfb6c64b5d9765/Integration/console-error-logs.html

image

Known Issue: https://jira.corp.adobe.com/browse/AC-15195

Hence moving this PR in Merge in Progress.
