### PR TITLE
Fix mime type typo

### LINKED ISSUE #36899: [Issue] Fix mime type typo
This issue is automatically created based on existing pull request: magento/magento2#36669: Fix mime type typo

---------
This PR fixes a typo in `module-cms/Test/Unit/Model/Wysiwyg/Images/StorageTest.php`

### PR DESCRIPTION
**Pull request by ssx**
This PR fixes a typo in `module-cms/Test/Unit/Model/Wysiwyg/Images/StorageTest.php`

### Resolved issues:
1. [x] resolves magento/magento2#36899: Fix mime type typo

### CODE REVIEW

**Review by fredden — APPROVED** [review]
This looks like a partial duplicate of https://github.com/magento/magento2/pull/33514. I'm approving as the changes here look fine on their own.

**Comment by fredden** [comment]
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by Den4ik** [comment]
@fredden Thanks for the link. I have checked https://github.com/magento/magento2/pull/33514 and believe first one is preferable for merge rather then this PR. I'm voting for the first one

**Comment by RaghavendraTirumalasetti** [comment]
@magento run Static Tests

**Comment by RaghavendraTirumalasetti** [comment]
@magento run Integration Tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento create issue

File: app/code/Magento/Cms/Test/Unit/Model/Wysiwyg/Images/StorageTest.php [hunk 1]
```diff
@@ -42,9 +42,9 @@ class StorageTest extends TestCase
     /**
      * Directory paths samples
      */
-    const STORAGE_ROOT_DIR = '/storage/root/dir/';
+    private const STORAGE_ROOT_DIR = '/storage/root/dir/';
```
Comment (hostep) [inline app/code/Magento/Cms/Test/Unit/Model/Wysiwyg/Images/StorageTest.php]: <del>@engcom-Echo: Making previously public consts private is backwards incompatible. Custom code/modules might be using these consts.
Can you make them explicitly public again instead of private? Thanks! 🙂 </del>

Update: sorry, this is inside a Test class so my remark makes no sense, ignore my comments 😄 

Can somebody re-add the `Progress: accept` label here? It got auto-removed after my silly comment (no idea why that happens automatcically, but it is what it is ...)

**Comment by fredden** [comment]
@magento run all tests

**Comment by ssx** [comment]
@engcom-Hotel @engcom-Echo @engcom-Lima @engcom-Alfa considering the other PR didn't get merged, can we get this one merged?

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hi @ssx,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed

Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Dash** [comment]
@magento run all tests
