### PR TITLE
Issue 35925: Internal Server Error in /V1/creditmemo/refund API Endpoint

### LINKED ISSUE #35925: Internal Server Error in /V1/creditmemo/refund API Endpoint
### Preconditions and environment

- Magento version 2.4

### Steps to reproduce

1. Retrieve auth token from the admin endpoint /V1/integration/admin/
2. Request endpoint:

```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer' <AUTH TOKEN> -d '{"creditmemo": "", "offlineRequested": true}' -X POST http://<MAGENTO_URL>/pub/rest/default/V1/creditmemo/refund
```

### Expected result

Returns a 400 error as the request is malformed.

### Actual result

Returns a 500 status code.

### Additional information

output of var/log/system.log:
```
	[2022-08-01T11:50:13.339331+00:00] main.CRITICAL: Error: Call to a member function refund() on null in /magento/vendor/magento/module-sales/Model/Order/Creditmemo/RefundOperation.php:118
	Stack trace:
	#0 /magento/vendor/magento/module-sales/Model/Order/RefundAdapter.php(39): Magento\Sales\Model\Order\Creditmemo\RefundOperation->execute()
	#1 /magento/vendor/magento/module-sales/Model/Service/CreditmemoService.php(167): Magento\Sales\Model\Order\RefundAdapter->refund()
	#2 [internal function]: Magento\Sales\Model\Service\CreditmemoService->refund()
	#3 /magento/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
	#4 /magento/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
	#5 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
	#6 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
	#7 /magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
	#8 /magento/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
	#9 /magento/vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
	#10 /magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
	#11 /magento/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
	#12 /magento/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
	#13 {main} [] []
```

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#35925

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

File: app/code/Magento/Sales/Model/Service/CreditmemoService.php [hunk 1]
```diff
@@ -3,11 +3,12 @@
  * Copyright © Magento, Inc. All rights reserved.
  * See COPYING.txt for license details.
  */
+declare(strict_types=1);
 
 namespace Magento\Sales\Model\Service;
 
 /**
- * Class CreditmemoService
```
Comment (edenduong) [inline app/code/Magento/Sales/Model/Service/CreditmemoService.php:10]: I think we should not remove the Class CreditmemoService in comment. You can add description below the class comment.

File: app/code/Magento/Sales/Model/Service/CreditmemoService.php [hunk 2]
```diff
@@ -192,6 +193,12 @@ protected function validateForRefund(\Magento\Sales\Api\Data\CreditmemoInterface
             );
         }
 
+        if (!$creditmemo->getOrderId()) {
+            throw new \Magento\Framework\Exception\LocalizedException(
```
Comment (edenduong) [inline app/code/Magento/Sales/Model/Service/CreditmemoService.php]: Change to `Magento\Framework\Exception\NoSuchEntityException`

**Review by edenduong — CHANGES_REQUESTED** [review]
Thank you for your contribution. Could you please check my comment.

File: app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php [hunk 3]
```diff
@@ -204,6 +207,7 @@ public function testRefund()
             ->getMock();
 
         $creditMemoMock->expects($this->atLeastOnce())->method('getOrder')->willReturn($orderMock);
+        $creditMemoMock->expects($this->atLeastOnce())->method('getOrderId')->willReturn(true);
```
Comment (edenduong) [inline app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php]: it should be int instead of boolean

File: app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php [hunk 4]
```diff
@@ -267,12 +271,14 @@ public function testRefund()
...
     {
         $creditMemoMock = $this->getMockBuilder(CreditmemoInterface::class)
-            ->setMethods(['getId', 'getOrder', 'getState', 'getInvoice'])
+            ->setMethods(['getId', 'getOrder', 'getState', 'getInvoice', 'getOrderId'])
             ->disableOriginalConstructor()
             ->getMockForAbstractClass();
         $creditMemoMock->expects($this->once())->method('getId')->willReturn(444);
         $creditMemoMock->expects($this->once())->method('getState')
             ->willReturn(Creditmemo::STATE_OPEN);
+        $creditMemoMock->expects($this->once())->method('getOrderId')
```
Comment (edenduong) [inline app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php:280]: it should be int instead of boolean

File: app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php [hunk 5]
```diff
@@ -412,6 +432,8 @@ public function testMultiCurrencyRefundExpectsMoneyAvailableToReturn()
             ->getMock();
         $creditMemo->method('getOrder')
             ->willReturn($order);
+        $creditMemo->method('getOrderId')
```
Comment (edenduong) [inline app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php:435]: it should be int instead of boolean

**Review by edenduong — CHANGES_REQUESTED** [review]

File: app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php (hunk 5 above)
Comment (rogerdz) [reply app/code/Magento/Sales/Test/Unit/Model/Service/CreditmemoServiceTest.php:435]: Thank @edenduong, I added new commit

**Review by edenduong — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
@magento run Functional Tests EE

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
Install fresh Magento `2.4-develop`

**Manual testing scenario:**
- Retrieve auth token from the admin endpoint /V1/integration/admin/
- Send request of below payload using post method and endpoint as `/rest/default/V1/creditmemo/refund`. 
**Payload:**
```
{
    "creditmemo": "",
    "offlineRequested": true
}
```

**Before:** :heavy_multiplication_x: Getting 500 error in response.
Screenshot 2022-09-26 at 4 06 09 PM

**In logs:**
Screenshot 2022-09-26 at 4 06 57 PM


**After:** :heavy_check_mark:  Getting 400 error as expected.
Screenshot 2022-09-26 at 4 30 03 PM

As automation is covered no additional manual test case is required.
