### PR TITLE
#30255: Fixed "The coupon code has been accepted." message remains after a Coupon Code was removed

### LINKED ISSUE #30255: "The coupon code has been accepted." message remains after a Coupon Code was removed
Preconditions
1. Create simple product  

2. Create Customer with address
* First Name: John
* Last Name: Doe
* Email Address: john.doe@example.com(use real mail)
* Company: Magento
* Address: 6161 West Centinela Avenue
* City: Culver City
* State/Province: California (CA)
* Zip/Postal Code: 90230
* Country: United States
* Telephone: 555-55-555-55
 
3. Go to Admin -> Marketing -> Cart Price Rules: click "Add New Rule"
* Fill all required fields 
  * "Coupon" select Specific Coupon
  * "Coupon Code" =  1111 
* In "Action" section 
  * "Apply" select "Percent of product price discount"
  * "Discount Amount" =  50
* click "Save" button 

Steps:
 1. Go to admin -> sales -order -> create new order -> select customer
 2. Add Products => simple product
 3. Apply Coupon Code => 1111
 4. remove Coupon Code
 
(/) Expected result
"The coupon code has been accepted." message should disappear

(x) Actual result
"The coupon code has been accepted." message is still  present

### PR DESCRIPTION
**Pull request by shikhamis11**
Fixed #30255 "The coupon code has been accepted." message remains after a Coupon Code was removed

**Preconditions**

    Create simple product

    Create Customer with address

    First Name: John
    Last Name: Doe
    Email Address: john.doe@example.com(use real mail)
    Company: Magento
    Address: 6161 West Centinela Avenue
    City: Culver City
    State/Province: California (CA)
    Zip/Postal Code: 90230
    Country: United States
    Telephone: 555-55-555-55

    Go to Admin -> Marketing -> Cart Price Rules: click "Add New Rule"

    Fill all required fields
        "Coupon" select Specific Coupon
        "Coupon Code" = 1111
    In "Action" section
        "Apply" select "Percent of product price discount"
        "Discount Amount" = 50
    click "Save" button

**Steps:**

    Go to admin -> sales -order -> create new order -> select customer
    Add Products => simple product
    Apply Coupon Code => 1111
    remove Coupon Code

**(/) Expected result**
"The coupon code has been accepted." message should disappear

**(x) Actual result**
"The coupon code has been accepted." message is still present

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rodrigowebjump** [comment]
@magento give me test instance

**Comment by milindsingh** [comment]
#dmcdindia2020

**Comment by pramod-mishra** [comment]
#dmcdindia2020

**Comment by magento-engcom-team** [comment]
@pramod-mishra thank you for joining. Please accept team invitation [here](https://github.com/orgs/magento/invitation) and self-assign the issue.

**Comment by rodrigowebjump** [comment]
Hi @shikhamis11 Thanks for your contribution.

Please could you cover your fix by autotests (MFTF)? 
Thanks

**Comment by pramod-mishra** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
@rodrigowebjump Thanks for the review . I am working on to add MFTF coverage for the issue

**Comment by rodrigowebjump** [comment]
@magento give me 2.4-develop instance

**Comment by rodrigowebjump** [comment]
Hi @shikhamis11 

Apparently the issue is being caused because there is no message returned when the coupon is removed. 
A suggestion for this case is to return a message informing that the coupon was removed in the backend request process (like occurs in the storefront) 

The current JS behavior does not remove the previous message if a empty is received in the response. Since there is a lot of requests happening there, my recommendation is to not change this behavior for now because we can create some undesirable 
result.

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
@magento give me test instance

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by shikhamis11** [comment]
@magento run all tests

File: app/code/Magento/Sales/Controller/Adminhtml/Order/Create.php [hunk 1]
```diff
@@ -344,6 +344,8 @@ protected function _processActionData($action = null)
                     $this->messageManager->addSuccessMessage(__('The coupon code has been accepted.'));
                 }
             }
+        } elseif (isset($data['coupon']['code']) && empty($couponCode)) {
+                    $this->messageManager->addSuccessMessage(__('The coupon code has been removed.'));
```
Comment (gabrieldagama) [inline app/code/Magento/Sales/Controller/Adminhtml/Order/Create.php:348]:
```suggestion
        } elseif (isset($data['coupon']['code']) && empty($couponCode)) {
            $this->messageManager->addSuccessMessage(__('The coupon code has been removed.'));
```

Comment (gabrieldagama) [inline app/code/Magento/Sales/Controller/Adminhtml/Order/Create.php]:
```suggestion
        } elseif (isset($data['coupon']['code']) && empty($couponCode)) {
            $this->messageManager->addSuccessMessage(__('The coupon code has been removed.'));
```

**Review by gabrieldagama — COMMENTED** [review]
Hi @shikhamis11, thanks for the PR, we just need to adjust the code formatting.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Changing to the right column, waiting for contributor changes.

**Comment by shikhamis11** [comment]
@magento run all tests

File: app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+            <createData entity="SalesRuleSpecificCouponWithFixedDiscount" stepKey="createCartPriceRule"/>
+            <createData entity="SimpleSalesRuleCoupon" stepKey="createCouponForCartPriceRule">
+                <requiredEntity createDataKey="createCartPriceRule"/>
+            </createData>
+
+            <!-- Enable Bank Transfer payment -->
+            <magentoCLI command="config:set {{EnablePaymentBankTransferConfigData.path}} {{EnablePaymentBankTransferConfigData.value}}" stepKey="enableBankTransferPayment"/>
+
+            <!--Set default flat rate shipping method settings-->
+            <magentoCLI command="config:set {{EnableFlatRateConfigData.path}} {{EnableFlatRateConfigData.value}}" stepKey="enableFlatRate"/>
```
Comment (gabrieldagama) [inline app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: Don't we need to revert this state as well on after node?

File: app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+            <argument name="product" value="$$createSimpleProduct$$"/>
+        </actionGroup>
+
+        <!-- Apply coupon to the order -->
+        <actionGroup ref="AdminApplyCouponToOrderActionGroup" stepKey="applyCoupon">
+            <argument name="couponCode" value="$$createCouponForCartPriceRule.code$$"/>
+        </actionGroup>
+        
+        <!-- Remove coupon from the order -->
+        <actionGroup ref="AdminRemoveCouponFromOrderActionGroup" stepKey="removeCoupon"/>
```
Comment (gabrieldagama) [inline app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml:54]: I guess we need to assert that the message old message disappear and the new one shows up

File: app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml (hunk 2 above)
Comment (rodrigowebjump) [reply app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: I think that in this case you can use the following 

<createData entity="FlatRateShippingMethodDefault" stepKey="setDefaultFlatRateShippingMethod"/>

as used in 
https://github.com/magento/magento2/blob/1ee91ca2d9c6650c83f4b5f6abc1983fa1fef629/app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderWithSimpleProductTest.xml

https://github.com/magento/magento2/blob/1ee91ca2d9c6650c83f4b5f6abc1983fa1fef629/app/code/Magento/Sales/Test/Mftf/Test/AdminHoldCreatedOrderTest.xml


@gabrieldagama I don't see the revert of this flatrate set in other tests. Is this a good practice in this case or is not required?

Comment (rodrigowebjump) [reply app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: @shikhamis11 You can use the files I mentioned as a reference for before actions.

Comment (gabrieldagama) [reply app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: @rodrigowebjump Yeah, ideally we should leave the application state as we found before the test ran, the reason for that is basically to avoid flaky tests. Other tests may rely on the "default" application state to pass successfully, and that may bring problems for us on PR processing.

**Comment by shikhamis11** [comment]
@engcom-Charlie yes it is ready 
I am waiting for review from @rodrigowebjump and @gabrieldagama

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+        <annotations>
+            <stories value="Create Order with offline payment methods"/>
+            <title value="Create Order to verify apply and remove coupon code test"/>
+            <description value="Create Order to verify apply and remove coupon code test"/>
+            <severity value="CRITICAL"/>
+            <testCaseId value="MC-37386"/>
+            <group value="sales"/>
+        </annotations>
+        <before>
+            <!-- Login as admin -->
```
Comment (gabrieldagama) [inline app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: Please remove the comments between the steps, they are pretty much the same content already on the stepKey attribute, I don't think it brings any benefit.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @shikhamis11, thanks for updating the PR, can you have a look at my comment below? It is a pretty small thing but would be nice to keep the test cleaner.

**Review by gabrieldagama — APPROVED** [review]

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8426](https://jira.corp.magento.com/browse/ENGCOM-8426) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Create Simple product;
2. Create Customer;
3. Go to Admin -> Marketing -> Cart Price Rules: click "Add New Rule"
```
Fill all required fields
    "Coupon" select Specific Coupon
    "Coupon Code" = 12345
In "Action" section
    "Apply" select "Percent of product price discount"
    "Discount Amount" = 50
click "Save" button
```

**Manual testing scenario:**

1. Go to admin -> sales -> orders -> create new order -> select customer
2. Add Products => simple product
3. Apply Coupon Code => 12345
4. remove Coupon Code

**Before:** :heavy_multiplication_x:  "The coupon code has been accepted." message is still present

Peek 2020-11-05 09-49

**After:** :heavy_check_mark: "The coupon code has been removed." message is present

Peek 2020-11-05 10-00

File: app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+
+<tests xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
+       xsi:noNamespaceSchemaLocation="urn:magento:mftf:Test/etc/testSchema.xsd">
+    <test name="AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest">
+        <annotations>
+            <stories value="Create Order with offline payment methods"/>
+            <title value="Create Order to verify apply and remove coupon code test"/>
+            <description value="Create Order to verify apply and remove coupon code test"/>
+            <severity value="CRITICAL"/>
+            <testCaseId value="MC-37386"/>
```
Comment (engcom-Charlie) [inline app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: @shikhamis11 could you please update `severity` and `testCaseId`?
Thank you.
```
            <severity value="AVERAGE"/>
            <testCaseId value="MC-38919"/>
```

**Comment by engcom-Charlie** [comment]
@magento run all tests

File: app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+                stepKey="enableBankTransferPayment"/>
+            <magentoCLI command="config:set {{EnableFlatRateConfigData.path}} {{EnableFlatRateConfigData.value}}"
+                        stepKey="enableFlatRate"/>
+        </before>
+        <after>
+            <magentoCLI
+                command="config:set {{DisablePaymentBankTransferConfigData.path}} {{DisablePaymentBankTransferConfigData.value}}"
+                stepKey="disableBankTransferPayment"/>
+            <magentoCLI command="config:set {{DisableFlatRateConfigData.path}} {{DisableFlatRateConfigData.value}}"
+                        stepKey="disableFlatRate"/>
```
Comment (gabrieldagama) [inline app/code/Magento/Sales/Test/Mftf/Test/AdminCreateOrderToVerifyApplyAndRemoveCouponCodeTest.xml]: I believe flat rate is enabled by default, by disabling it we may have made other tests flaky. I guess you can keep the CLI to enable it, but remove this one.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @shikhamis11, I believe we might have an issue with the mftf, can you check it?

**Comment by shikhamis11** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run Functional Tests EE

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8426](https://jira.corp.magento.com/browse/ENGCOM-8426) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed
