### PR TITLE
Magento 2.3 contact form not sending emails( No log entry).

### LINKED ISSUE #23645: Magento 2.3 contact form not sending emails( No log entry)
### Preconditions
Magento 2.4-develop

### Steps to reproduce (*)

- Add `throw new LocalizedException(__('test localized exception'));` before https://github.com/magento/magento2/blob/2268edc5cadfb7b0fbf0e998a23abd60a4608efb/app/code/Magento/Contact/Controller/Index/Post.php#L75
- Enter the contact form
- Send a message

### Expected result (*)
1. Exception with stack trace is logged

### Actual result (*)
1. No log entry in any of the Magento, PHP or Apache logs that provides any insight

**Original case:**
Preconditions
Magento 2.3.0, 2.3.1 or 2.3.2  CE

1. sendmail is installed and working (Courier-MTA on Debian 10)
2. php mail() command working fine
3. order status emails are being send fine

Steps to reproduce (*)

1. enter the contact form
2. send a message

Expected result (*)
1. email is sent

Actual result (*)
1**. as a user get a generic error message that email could not be sent**
2. **No log entry in any of the Magento, PHP or Apache logs that provides any insight**

Since order status emails can be sent, Magento is clearly capable of sending emails to users.
At the very least, there must be a log entry THAT something happend and best even provide inside what needs fixing. Currently there is no log entry at all. Not even on DEBUG level.

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/23645

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/23645

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Contact/Controller/Index/Post.php [hunk 1]
```diff
@@ -78,6 +75,7 @@ public function execute()
             );
             $this->dataPersistor->clear('contact_us');
         } catch (LocalizedException $e) {
+            $this->logger->error($e);
```
Comment (zakdma) [inline app/code/Magento/Contact/Controller/Index/Post.php]: I suppose we should not log LocalizedException. LocalizedException intended for showing to user, not for logging.
You should intercept real transport exception and log it. I suggest to do it here
\Magento\Framework\Mail\Transport::sendMessage
\Magento\Email\Model\Transport::sendMessage
 in catch section where actually MailException created

I'd also changed implementation and dont show real transport exception to user as it done 
```
throw new MailException(new Phrase($e->getMessage()), $e);
```
It can be potentially security issue. But create something like:
```
throw new MailException(new Phrase('Mail transport failure'), $e); // don't forget add translation
```

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/Contact/Controller/Index/Post.php (hunk 1 above)
Comment (engcom-Kilo) [reply app/code/Magento/Contact/Controller/Index/Post.php]: Done

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Email/Model/Transport.php [hunk 2]
```diff
@@ -100,7 +110,8 @@ public function sendMessage()
 
             $this->laminasTransport->send($laminasMessage);
         } catch (\Exception $e) {
-            throw new MailException(new Phrase($e->getMessage()), $e);
+            $this->logger->error($e->getMessage());
```
Comment (ihor-sviziev) [inline app/code/Magento/Email/Model/Transport.php]: I believe it's better to log whole exception, including the stack trace, otherwise it would be too hard to detect where the exception happened
```suggestion
            $this->logger->error($e);
```

File: lib/internal/Magento/Framework/Mail/Transport.php [hunk 3]
```diff
@@ -45,7 +56,8 @@ public function sendMessage()
                 LaminasMessage::fromString($this->message->getRawMessage())
             );
         } catch (\Exception $e) {
-            throw new MailException(new Phrase($e->getMessage()), $e);
+            $this->logger->error($e->getMessage());
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Mail/Transport.php]: same here
```suggestion
            $this->logger->error($e);
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/Email/Model/Transport.php (hunk 2 above)
Comment (engcom-Kilo) [reply app/code/Magento/Email/Model/Transport.php]: Changed

File: lib/internal/Magento/Framework/Mail/Transport.php (hunk 3 above)
Comment (engcom-Kilo) [reply lib/internal/Magento/Framework/Mail/Transport.php]: Done

**Comment by ihor-sviziev** [comment]
Looks good to me. Let's wait for test results

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9000](https://jira.corp.magento.com/browse/ENGCOM-9000) has been created to process this Pull Request

**Review by zakdma — APPROVED** [review]

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed

**Comment by dmitriyprime** [comment]
image

**Comment by ihor-sviziev** [comment]
Hey @dmitriyprime,
It looks like that's not OK that exception was thrown there. It wasn't expected. The correct behavior should be exception logged to var/exception.log or var/system.log file

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hey @dmitriyprime @engcom-Kilo ,
It looks like that's not OK that an exception was thrown there and a customer came to the report page. It wasn't expected. The correct behavior should be exception logged to var/exception.log or var/system.log file

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32730`.

File: app/code/Magento/Email/Model/Transport.php [hunk 4]
```diff
@@ -100,7 +110,8 @@ public function sendMessage()
 
             $this->laminasTransport->send($laminasMessage);
         } catch (\Exception $e) {
-            throw new MailException(new Phrase($e->getMessage()), $e);
+            $this->logger->error($e);
+            throw new MailException(new Phrase('Unable to send mail. Please try again later.'));
```
Comment (ihor-sviziev) [inline app/code/Magento/Email/Model/Transport.php:114]: @engcom-Kilo @zakdma, we have regression here. The original exception should be passed as a 2nd param here to understand why it failed, as it was in the past.

**Comment by tuyennn** [comment]
@ihor-sviziev This is completely useless pull request. With
```
throw new MailException(new Phrase($e->getMessage()), $e); 
```
we already knew what the exception was.

**Comment by ihor-sviziev** [comment]
@tuyennn, before this PR, we hadn't any log record about email sending failure.

File: app/code/Magento/Email/Model/Transport.php (hunk 4 above)
Comment (ihor-sviziev) [reply app/code/Magento/Email/Model/Transport.php:114]: FYI here is a PR that fixes this regression https://github.com/magento/magento2/pull/33419
