### PR TITLE
Customer address in admin order details like company name in not work website wise

### LINKED ISSUE #23254: Customer address in admin order details like company name in not work website wise
### Preconditions (*)
1. Magento version 2.2.7
1. On Multiwebsite 
1. In Admin view order details customer address information Billing and Shipping. Company name not showing website wise it only show when Show Company setting under customer configuration is set as optional in base website whose id is 1. If you go to different scope in setting and change to no for second website there is no changes occurred.

### Steps to reproduce (*)
1. In Admin view order details customer address information Billing and Shipping. Company name not showing website wise it only show when Show Company setting under customer configuration is set as optional in base website whose id is 1. If you go to different scope in setting and change to no for second website there is no changes occurred.
1. Attributes like company name, vat show etc depends on website whose id is 1 in admin order details. 
1. Suppose you have an order of france website and its id is website id is 2. If you change the setting in website scope like Show Company to Optional and in default Show Company is No then in France order in admin section customer address details Company name not visible. but when you change the setting in first website whose id is 1 then it show the company name in address admin order details.

### Expected result (*)
1. Company name, Show Fax etc attributes must show in order details customer address information website wise setting.

### Actual result (*)
1. Company name, Show Fax etc attributes work only on website whose id is 1.

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/23254

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/23254

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all test

**Comment by engcom-Kilo** [comment]
@magento run all test

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by nuzil — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @nuzil, thank you for the review.
[ENGCOM-9089](https://jira.corp.magento.com/browse/ENGCOM-9089) has been created to process this Pull Request

**Comment by dmitriyprime** [comment]
:heavy_check_mark: QA passed

**Before:**
before

**After:**
after

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-33004`.

File: app/code/Magento/Sales/Model/Order/Address/Renderer.php [hunk 1]
```diff
@@ -62,15 +70,15 @@ public function __construct(
      */
     public function format(Address $address, $type)
     {
-        $storeId = $address->getOrder()->getStoreId();
-        $this->addressConfig->setStore($storeId);
+        $orderStore = $address->getOrder()->getStore();
+        $this->storeManager->setCurrentStore($orderStore);
```
Comment (kanevbg) [inline app/code/Magento/Sales/Model/Order/Address/Renderer.php:74]: Changing the current store but not resetting results in lost context for following algorithms. So that's more of architectural issue then it is of concrete problem.
EDIT: I'd suggest to finally {} restore the original store ID in the store manager to prevent unexpected behavior on following algorithms (which may be custom/third-party).
