### PR TITLE
Fix filter placeholders for ui-select filter (frontend implementation)

### LINKED ISSUE #1780: "Active filters" shows the "Asset:" filter which is empty if switch to the Default View again
### Preconditions (*)

1. Install Magento 2.4-develop with Adobe Stock Integration and IMS
2. Configured integration in Stores -> Configuration -> Advanced-> System -> Adobe Stock Integration fieldset
3. New Media Gallery Enabled
4. Image added to a category
### Steps to reproduce (*)

1. Go to Content -> Media Gallery
2. Select the image that is added to the category by clicking on it
3. Click on three dots -> View Details 
4. Click on the link 'Categories..." in 'Used in' attribute
5. Delete the `?filters[asset_id]=[1]` part of request from address line -> Press `Enter` key
6. Click on the "Clear all" link
7. Wait for a few seconds and reload the page
8. Click on the "Default View" dropdown
9. Select the  "Default View" by clicking on it

### Expected result (*)

No Active filters

### Actual result (*)

"Active filters" shows the "Asset:" filter which is empty 
[Video](https://drive.google.com/file/d/1spREJfBLtRii0I0JujyHshz0E1Rjr59o/view?usp=sharing)
Screenshot_121

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1780: "Active filters" shows the "Asset:" filter which is empty if switch to the Default View again 

### Manual testing scenarios (*)
1. Verify asset filter placeholders in grids -> product, pages, blocks, categories
2. Verify asset filter placeholder with saved grid views in all listed grid (products,pages,blocks,categories)
3. Verify asset filter placeholders from saved in bookmarks filters in listed grids products,pages,blocks,categories)
4. Verify Used in filters place holders in standalone and slide panel media gallery with saved in bookmarks and saved in different grid views.
5. Verify url-filter applier by link from image view details thats used in  (products,pages,blocks,categories)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/Ui/view/base/web/js/grid/filters/elements/ui-select.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+            this.validateInitialValue();
+
+            return this;
+        },
+
+        /**
+         * Validate initial value actually exists
+         */
+        validateInitialValue: function () {
+            if (!_.isEmpty(this.value())) {
```
Comment (sivaschenko) [inline app/code/Magento/Ui/view/base/web/js/grid/filters/elements/ui-select.js]: Please revert the condition to avoid the else condition

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/GetSelected.php [hunk 2]
```diff
@@ -8,67 +8,77 @@
...
-        /** @var ProductInterface $product */
-        if (!empty($productCollection->getFirstItem()->getData())) {
-            $product = $productCollection->getFirstItem();
-            $option = [
-                'value' => $productId,
-                'label' => $product->getName(),
-                'is_active' => $product->getStatus(),
-                'path' => $product->getSku(),
-            ];
+        $productIds = $this->getRequest()->getParam('ids');
```
Comment (sivaschenko) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/GetSelected.php]: This is backward incompatible change. Please keep this controller as it is and introduce a new controller to MediaGalleryCatalogUi module

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the PR @Nazar65 ! Looks awesome!

Please see my review comments.

Does the url-filter-applier works fine with these changes as well?

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/GetSelected.php (hunk 2 above)
Comment (Nazar65) [reply app/code/Magento/Catalog/Controller/Adminhtml/Product/GetSelected.php]: ok

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@Nazar65 nice job!

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8094](https://jira.corp.magento.com/browse/ENGCOM-8094) has been created to process this Pull Request

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

Checked the: 
- Asset filter placeholders in _Product_, _Pages_, _Blocks_, _Categories_ grids :heavy_check_mark: 
- Asset filter placeholder with saved grid views in all listed grid (products,pages,blocks,categories) :heavy_check_mark:
- Used in filters place holders in standalone and slide panel media gallery with saved in bookmarks and saved in different grid views :heavy_check_mark:

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1320712/scenarios/5146730
