### PR TITLE
magento/magento2#38933: Putting csp_whitelist.xml in theme does not work and creates intermittent issue #38933

### LINKED ISSUE #38933: Putting csp_whitelist.xml in theme does not work and creates intermittent issue
### Preconditions and environment

- 2.4.7 and 2.4-develop

### Steps to reproduce

* Put csp_whitelist.xml under your frontend theme's etc/ directory. (You can put this in Luma theme too. Just any theme will work)
* Clear your cache
* Without doing anything else Open your admin page
* now open  frontend and check csp headers

### Expected result

Domains listed in your custom csp_whitelist.xml under theme should have reflected on frontend

### Actual result

If admin is hit first after cache flush, domains under your csp_whitelist.xml under theme are not seen on frontend.

### Additional information

This bug happens because contents of csp_whitelist.xml in theme are stored in global cache. 
Lets see how this works right now.
CSP cache is maintained area wise.  For example, you will find 3 files in your cache
```
var/cache/mage--8/mage---06a_FRONTEND__CSP_WHITELIST_CONFIG
var/cache/mage--2/mage---06a_GLOBAL__CSP_WHITELIST_CONFIG
var/cache/mage--a/mage---06a_ADMINHTML__CSP_WHITELIST_CONFIG
```

Now the bug happens because of  `app/code/Magento/Csp/Model/Collector/CspWhitelistXml/FileResolver.php`

```
public function get($filename, $scope)
    {
         $configs = $this->moduleFileResolver->get($filename, $scope);
        if ($scope === 'global') {
            $files = [];
            $theme = $this->theme;
            while ($theme) {
                /** @var CustomizationInterface $info */
                $info = $this->themeInfoFactory->create(['theme' => $theme]);
                $file = $info->getThemeFilesPath() .'/etc/' .$filename;
                if ($this->rootDir->isExist($file)) {
                    $files[] = $file;
                }
                $theme = $theme->getParentTheme();
            }
            $configs = $this->iteratorFactory->create(
                ['paths' => array_reverse($files), 'existingIterator' => $configs]
            );
        }

        return $configs;
    }
```
 
 ` if ($scope === 'global')` leads to csp_whitelist config in theme being put in global cache. 
 After cache flush if admin request lands on server, $theme variable is set to Magento/backend . 
 In this case, your file in frontend theme wont be read. Global cache is then populated according to Magento/backend
 
 The behavior completely depends on which area request lands first, frontend or admin. This leads to poor developer experience too.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by NitrogenUA**
### Description (*)
- Implemented caching of CSP whitelist per website area.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38933

### Manual testing scenarios (*)

- Put csp_whitelist.xml under your frontend theme's etc/ directory. (You can put this in Luma theme too. Just any theme will work).
- Clear Magento 2 cache.
- Open Magento 2 admin area page. Using browser DevTools take note of CSP definitions response header.
- Open Magento 2 storefront, for instance in separate browser tab. Using browser DevTools take note of CSP definitions response header.
- Verify that theme's CSP whitelist is in effect on Magento 2 storefront by comparing CSP definition headers from each request.

### Expected result
Magento 2 storefront CSP whitelist is applied even if admin area was accessed first after the cache reset.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by NitrogenUA** [comment]
@magento run all tests

**Comment by NitrogenUA** [comment]
@magento run all tests

**Comment by NitrogenUA** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by NitrogenUA** [comment]
@magento run Functional Tests B2B, Integration Tests

**Comment by NitrogenUA** [comment]
@engcom-Hotel PR is ready for review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Csp/Model/Collector/CspWhitelistXml/FileResolver.php [hunk 1]
```diff
@@ -1,22 +1,22 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Csp/Model/Collector/CspWhitelistXml/FileResolver.php]:
```suggestion
 * Copyright 2020 Adobe
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @NitrogenUA,

Please add some automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

**Comment by engcom-Dash** [comment]
@NitrogenUA I am taking care of the automated test creation. Thank You!

**Comment by Den4ik** [comment]
@engcom-Dash this is great, thanks

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+     * @var CustomizationInterface
+     */
+    private $customizationInterfaceMock;
+
+    protected function setUp(): void
+    {
+        $this->moduleFileResolverMock = $this->getMockBuilder(FileResolverInterface::class)
+            ->disableOriginalConstructor()
+            ->onlyMethods(['get'])
+            ->getMockForAbstractClass();
```
Comment (engcom-Hotel) [inline app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]: `getMockForAbstractClass` method has been deprecated, please use alternative.

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php [hunk 3]
```diff
@@ -0,0 +1,221 @@
...
+            $this->customizationFactoryMock,
+            $this->filesystemMock,
+            $this->iteratorFactoryMock
+        );
+    }
+
+    /**
+     * Test for get method with frontend scope.
+     *
+     * @param string $filename
```
Comment (engcom-Hotel) [inline app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]: PHPDoc comment signature is not complete

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php [hunk 4]
```diff
@@ -0,0 +1,221 @@
...
+                    'existingIterator' => $fileList
+                ]
+            )
+            ->willReturn($fileList);
+
+        $this->assertEquals($fileList, $this->model->get($filename, $scope));
+    }
+
+    /**
+     * Test for get method with global scope.
```
Comment (engcom-Hotel) [inline app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php:167]: PHPDoc comment signature is not complete

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php [hunk 5]
```diff
@@ -0,0 +1,221 @@
...
+     *
+     * @param string $filename
```
Comment (engcom-Hotel) [inline app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]:
```suggestion
     * @param string $fileName
```

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php [hunk 6]
```diff
@@ -0,0 +1,221 @@
...
+    {
+        $this->moduleFileResolverMock->expects($this->once())
+            ->method('get')
+            ->with($fileName, $scope)
+            ->willReturn($fileList);
+        $this->assertEquals($fileList, $this->model->get($fileName, $scope));
+    }
+
+    /**
+     * Data provider for get glocal scope tests.
```
Comment (engcom-Hotel) [inline app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]:
```suggestion
     * Data provider for get global scope tests.
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @engcom-Dash,

Please refer to my review comments below.

Thanks

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php (hunk 4 above)
Comment (engcom-Dash) [reply app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php:167]: Fixed

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php (hunk 2 above)
Comment (engcom-Dash) [reply app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]: Fixed

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php (hunk 3 above)
Comment (engcom-Dash) [reply app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]: Fixed

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php (hunk 5 above)
Comment (engcom-Dash) [reply app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]: Fixed

File: app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php (hunk 6 above)
Comment (engcom-Dash) [reply app/code/Magento/Csp/Test/Unit/Model/Collector/CspWhitelistXml/FileResolverTest.php]: Fixed

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Test failures for **Functional B2B** are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39672/630f1e8bfc5ea654dcf76a2a1c6f2db8/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39672/a6e3b697ff7d78b35e3bf03e6027e6c0/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image


Test failures for **Functional CE** are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39672/c114bc4a7a680086651bab6637315301/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image


Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39672/0267a0e951359763def1f920e1bf3509/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Hence moving this PR in Merge In Progress.
