### PR TITLE
Remove jobs no longer referenced in the codebase

### LINKED ISSUE #38217: Cleanup of cron_schedule database table doesn't cleanup non-existing jobs
### Preconditions and environment

- Magento version 2.4.6-p3 (but most likely all versions will be affected)

### Steps to reproduce

Explanation below how to trigger this with a cronjob from inside core Magento. But the most likely cases will come from 3rd party modules containing cronjobs, that were installed for a while and then removed again.

1. Have a Magento shop with MSI modules enabled
2. Have a working crontab and have it running for a couple of hours
3. Inspect the `cron_schedule` table and notice that the job `inventory_in_store_pickup_sales_send_order_notified_emails` is mentioned many times with status `success`
4. Now, disable all MSI modules in `app/etc/config.php` and run `bin/magento setup:upgrade`
5. Keep the crontab running for a few more hours
6. Inspect your `cron_schedule` table again

### Expected result

It's expected that all jobs that were successful and having run more than 60 minutes ago are removed from the `cron_schedule` table.

### Actual result

See that there are still jobs `inventory_in_store_pickup_sales_send_order_notified_emails` in the table with status success and being older then 60 minutes. Those don't get cleaned up because the MSI modules are no longer active and calling `getJobs()` [over here](https://github.com/magento/magento2/blob/2.4.6-p3/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L577) doesn't return jobs from inactive (or removed) modules.

### Additional information

Ideally, the cronjob cleanup should also figure out which jobs are in the `cron_schedule` table that are no longer found in the system and clean those up as well.
Or maybe this can be added in the existing Recurring data script that exists in the Magento_Cron module, as then it doesn't need to be checked every minute when the cron actually runs. Since removing and disabling modules requires a `bin/magento setup:upgrade` call anyway, it might be a good idea to only then check for outdated entries in that table and remove them...

And since the `cron_schedule` table receives a lot of queries the entire day, it's beneficial to performance that it contains as few rows as possible. Old data should be cleaned up automatically.

I found this in a shop where we have hundreds of entries from 2021 in the `cron_schedule` table for jobs that for a long time no longer existed.

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by fredden**
### Description
When upgrading a Magento website over time, some cron jobs are left in the `cron_schedule` table for jobs which no longer exist. This can happen when a module is removed, or when a module removes a cronjob, or when a module changes the name of one of its cronjobs.

This pull request adds a daily clean-up task to remove such jobs from the schedule. This means that left-over jobs are pruned safely and the database table does have useless data.

### Manual testing scenarios
1. Run the Magento cron so that `sitemap_generate` gets scheduled. This belongs to the `Magento_Sitemap` module.
1. Disable the `Magento_Sitemap` module.
1. Run the Magento cron.
1. Observe that there is (or not) a left-over entry for `sitemap_generate` in the `cron_schedule` database table.

## Related issues

Fixes https://github.com/magento/magento2/issues/38217

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

File: app/code/Magento/Cron/Cron/CleanOldJobs.php [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+        private readonly ScheduleFactory $scheduleFactory,
+    ) {
+    }
+
+    /**
+     * Run the 'clean_cron_schedule' cronjob
+     *
+     * @return void
+     */
+    public function execute(): void
```
Comment (kandy) [inline app/code/Magento/Cron/Cron/CleanOldJobs.php:43]: Can you clarify why we need the logic on top of https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L562

Comment (fredden) [reply app/code/Magento/Cron/Cron/CleanOldJobs.php:43]: @kandy the linked code only cleans up known jobs (see line 596) in known groups (see line 558). This pull request adds clean-up for unknown jobs / groups.

https://github.com/magento/magento2/blob/995a05c9c7bf661729d79a01ad1447370bf4f39f/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L596
https://github.com/magento/magento2/blob/995a05c9c7bf661729d79a01ad1447370bf4f39f/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L558

Comment (kandy) [reply app/code/Magento/Cron/Cron/CleanOldJobs.php:43]: ok, make sense 
thanks you for clarification

**Comment by hostep** [comment]
Nice! Good job!

@fredden: can you add https://github.com/magento/magento2/issues/38217 to the description of this PR? As this fixes that issue, so it automatically gets closed when this PR is merged.

**Comment by fredden** [comment]
>  add https://github.com/magento/magento2/issues/38217 to the description of this PR? As this fixes that issue

Yes, I'll update this later today. Thanks for highlighting; I hadn't seen that report before now.

> maybe we should add the cleanup of unknown jobs to the Recurring setup script that exists in the Cron module

I considered this approach too. This would catch most of the scenarios where groups or jobs are removed. There are two (main) reasons why I went with a periodic clean-up instead.

If the clean-up is in the `setup:...` process, then it should clean up all orphaned entries, not just "old" orphaned entries. This means that we immediately lose history for these jobs. When removing a module forever, this is typically fine; sufficient backing up of data is part of good maintenance. When a module simply renames a cronjob however (eg, to fix a typo), then losing history prematurely isn't ideal. (I'm thinking about the "timeline" view of a certain cronjobmanager module.)

The other reason for the periodic clean-up, is that I have seen modules dynamically create jobs, which then never get cleaned up by Magento when that module's configuration changes.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Unit Tests, WebAPI Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @fredden,

Thanks for the collaboration!

The changes looks good to me but it seems the Integration test has been failing due to changes. I request you to please check the same.

Thanks

**Comment by fredden** [comment]
@engcom-Hotel thanks for your note. I don't know why I added a circular reference here. I've removed it now.

**Comment by fredden** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Functional Tests CE, WebAPI Tests

**Comment by fredden** [comment]
> I don't know why I added a circular reference here. I've removed it now.

I've worked out that this was a typing error. I had intended to add a dependency on `Magento_Config`. I've adjusted the commits here to reflect this.

**Comment by fredden** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]
Failed tests seems flaky to me.

**Comment by engcom-Bravo** [comment]
Hi @fredden,

Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

As per the Description.


**Before:** :heavy_multiplication_x: 


Screenshot 2024-05-24 at 12 29 38





**After:** :heavy_check_mark:  


The Jobs for Disabled Modules are removed from the `cron_schedule` table from the database.

Builds are failed. Hence, moving this PR to **Extended Testing.**


Thanks.

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B,Functional Tests CE,Functional Tests EE are different on last two run on same commit.
Also it contains some known failure.

[ACQE-6523](https://jira.corp.adobe.com/browse/ACQE-6523) - AdminReorderWithCatalogPriceRuleDiscountTest
[ACQE-6331](https://jira.corp.adobe.com/browse/ACQE-6331) - StorefrontCreateOrderAllQuantityGroupedProductOptionDefaultStockTest

Functional Tests B2B
Run1
38693-b2b

Run2
38693-b2b2

Functional Tests CE
Run1
38693-ce

Run2
38693-ce2

Functional Tests EE
Run1
38693-ee

Run2
38693-ee2


Hence moving it to merge in progress

**Comment by MaximGns** [comment]
Questioning why you should execute this by using another cron job? I guess cronjobs that are removed/changed name is only discoverd after a setup upgrade, and would be better do run this job after a setup upgrade (during deployment to production for example). Some project will not build anything to production for months, therefore no cronjobs will be removed/changed by name in the meantime...

**Comment by fredden** [comment]
@MaximGns see https://github.com/magento/magento2/pull/38693#issuecomment-2092442675
