### PR TITLE
Optimize QuoteIdToMaskedQuoteId model and fix infinite loop

### LINKED ISSUE #133: \Klaviyo\Reclaim\Plugin\Api\CartSearchRepository::afterGetList Infinite Loop
### Steps to reproduce

All cart interactions below should be done via API

1. Create cart
2. Add at least one product to cart
3. Apply coupon code to cart (must be a code)
4. Edit the cart product in the admin panel
5. Reload cart

### Expected Result

`/rest/{{store}}/V1/carts/mine` should return your cart ID

### Actual Result

An infinite loop is triggered when a quote has `quote.coupon_code <> NULL AND quote.trigger_recollect = 1`

Summarizing the call stack triggered by this combination:
https://github.com/klaviyo/magento2-klaviyo/blob/4e63ccd99ce74d6f72839fcccf764553596a0d45/Plugin/Api/CartSearchRepository.php#L57

https://github.com/magento/magento2/blob/ab815b51dad2a89b120cc53b26eefaee80a336f3/app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php#L53

https://github.com/magento/magento2/blob/ab815b51dad2a89b120cc53b26eefaee80a336f3/app/code/Magento/Quote/Model/QuoteRepository.php#L136

https://github.com/magento/magento2/blob/ab815b51dad2a89b120cc53b26eefaee80a336f3/app/code/Magento/Quote/Model/Quote.php#L2461

☝️ Recollection is triggered here because editing a product in the quote sets `quote.trigger_recollect = 1`

During recollection https://github.com/magento/magento2/blob/ab815b51dad2a89b120cc53b26eefaee80a336f3/app/code/Magento/SalesRule/Observer/CouponCodeValidation.php#L66
validates the coupon code. The validation calls `CartRepositoryInterface::getList` which re-triggers your plugin.

```php
$found = $this->cartRepository->getList(
  $this->criteriaBuilder->addFilter('main_table.' . CartInterface::KEY_ENTITY_ID, $quote->getId())
    ->create()
)->getItems();
```

At this point the request is infinitely looping until it timeouts or exhausts memory.

### LINKED ISSUE #33675: Adding masked quote id to QuoteRepository::getList causing infinite loop
In the Klaviyo extension, we have a plugin that adds a masked quote id to quote search API requests. That looks like quite a small plugin that shouldn't cause any performance or functional damage.

In most cases, it works well, but sometimes we see that such request causing eating 100% CPU by the php-fpm, and Gateway Timeout issues after quite a long time 60 seconds.

Here is a link to the plugin in the Klaviyo extension (it uses API class, which is ok):
https://github.com/klaviyo/magento2-klaviyo/blob/3.0.5/Plugin/Api/CartSearchRepository.php

Detailed investigation showed that issue is coming from the following line:
https://github.com/magento/magento2/blob/afa216974bf1214ee860e7bb9eeaf0474aee1d4f/app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php#L50-L53

-> it goes to https://github.com/magento/magento2/blob/afa216974bf1214ee860e7bb9eeaf0474aee1d4f/app/code/Magento/Quote/Model/QuoteRepository.php#L121
-> and then to 
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Quote/Model/Quote.php#L912-L917

Looks pretty small and simple, right? Yes... but... here we have the recollect totals and re-saving quote
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Quote/Model/Quote.php#L2461-L2468

In case if the quote has `trigger_recollect` = 1:
we running the following code:
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Quote/Model/Quote/TotalsCollector.php#L146-L148

This code triggers an event:
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/Quote/Model/Quote/TotalsCollector.php#L263-L264

That execites an event observer:
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/SalesRule/etc/events.xml#L30-L32
https://github.com/magento/magento2/blob/7c6b6365a3c099509d6f6e6c306cb1821910aab0/app/code/Magento/SalesRule/Observer/CouponCodeValidation.php#L58-L79
That... runs `$this->cartRepository->getList` method... for which we just added a plugin for adding masked quote ids!

As a result - we have an infinite loop.

### Preconditions (*)
1. Magento 2.3.7 or 2.4-develop

### Steps to reproduce (*)
1. Install Klaviyo extension (tested on version 3.0.5)

    OR Add a plugin, that adds masked quote id to response for the cart search API, for example: 
    - https://github.com/klaviyo/magento2-klaviyo/blob/3.0.5/etc/webapi_rest/di.xml#L3-L5
    -  https://github.com/klaviyo/magento2-klaviyo/blob/3.0.5/Plugin/Api/CartSearchRepository.php
    
2. Create Cart Price Rule with coupon (let's give some 10% discount)
3. Add some product to the shopping cart, apply the coupon from step 2
4. Run the following code with and w/o Klaviyo extension:  
```bash
curl --location --request GET 'https://www.mymagento.com/index.php/rest/default/V1/carts/search?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2021-06-11+11%3A38%3A16&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=DESC&searchCriteria%5BcurrentPage%5D=1&searchCriteria%5BpageSize%5D=50' \
--header 'Authorization: Bearer dk6zp483qmck8omd7sov1r3b9is7kxh'
```

  Note: here is documentation on how to get access token https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html#request-token
    ✔ we successfully retrieved the list of carts

5. Go to admin, edit the Cart Price Rule that you created in step 2, do the following steps:
    - change the coupon code, save the rule
    - disable the cart price rule, save it
6. Run the code from step 4

### Expected result (*)
1. You should get the JSON with a list of carts

### Actual result (*)
1. ❌We have 504 Gateway Time-out error 
image

2. 

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [x] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #33676: Using QuoteIdToMaskedQuoteId shouldn't increase response time
In the Klaviyo extension, we have a plugin that adds a masked quote id to quote search API requests. That looks like quite a small plugin that shouldn't cause any performance damage. But, by just commenting fetching masked quote ID - I noticed that performance is improved more than 2 times.

Here is a link to the plugin in Klaviyo extension (it uses API class, which is ok):
https://github.com/klaviyo/magento2-klaviyo/blob/3.0.5/Plugin/Api/CartSearchRepository.php

Detailed investigation shown that issue is coming from the following line:
https://github.com/magento/magento2/blob/afa216974bf1214ee860e7bb9eeaf0474aee1d4f/app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php#L50-L53

Basically, that code fetches again all the quotes again, and all their quote items and so on just for... checking if such quote exists!

### Preconditions (*)

1. Magento 2.3.7 or 2.4-develop

### Steps to reproduce (*)
1. Install Klaviyo extension (tested on version 3.0.5)
2. Create at least 20 quotes
3. Run the following code with and w/o Klaviyo extension:
```bash 
curl --location --request GET 'https://www.mymagento.com/index.php/rest/default/V1/carts/search?searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bvalue%5D=2021-06-11+11%3A38%3A16&searchCriteria%5Bfilter_groups%5D%5B0%5D%5Bfilters%5D%5B0%5D%5Bcondition_type%5D=gt&searchCriteria%5BsortOrders%5D%5B0%5D%5Bfield%5D=updated_at&searchCriteria%5BsortOrders%5D%5B0%5D%5Bdirection%5D=DESC&searchCriteria%5BcurrentPage%5D=1&searchCriteria%5BpageSize%5D=50' \
--header 'Authorization: Bearer dk6zp483qmck8omd7sov1r3b9is7kxh'
```
Note: here is documentation on how to get access token https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html#request-token

### Expected result (*)

1. You should see approximately the same response time

### Actual result (*)

1. Response time slowed down at least 30% with an enabled module.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ihor-sviziev**
### Description (*)
This PR stops using cart repository and using tiny code that checks only if such a quote exists.

I compared the same request w/o and with changes from PR and got ~40% time response improvement (tested with Blackfire):
image

Also, it fixes the infinite loop described in #33675, as the logic was rewritten to small SQL queries.

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/33675
2. Fixes https://github.com/magento/magento2/issues/33676
3. Fixes https://github.com/klaviyo/magento2-klaviyo/issues/133

### Manual testing scenarios (*)
1. See issue details

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php [hunk 1]
```diff
@@ -19,43 +21,70 @@ class QuoteIdToMaskedQuoteId implements QuoteIdToMaskedQuoteIdInterface
...
         $quoteIdMask = $this->quoteIdMaskFactory->create();
         $this->quoteIdMaskResource->load($quoteIdMask, $quoteId, 'quote_id');
-        $maskedId = $quoteIdMask->getMaskedId() ?? '';
 
-        return $maskedId;
+        return $quoteIdMask->getMaskedId() ?? '';
+    }
+
+    /**
+     * This is tiny implementation similar to \Magento\Quote\Api\CartRepositoryInterface::get
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: OMG. MHI test failed.
image

This is a false positive, but it's way easier to fix it like this:

```suggestion
     * This is a tiny implementation similar to the get method in \Magento\Quote\Api\CartRepositoryInterface
```

Comment (ihor-sviziev) [reply app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: @sidolov @sivaschenko @gabrieldagama, could you report an issue to fix such false positives in MHI?

Edit: Sorry, I was wrong. it's caused by https://github.com/magento/magento2/pull/33324/files#diff-a296f73a345054450c461f6ad9eb0d3782c07fc3ab09215355f7676ea26a55b1R87.

**Comment by ihor-sviziev** [comment]
FYI We have test coverage for this functionality in https://github.com/magento/magento2/blob/f4db7d458884bcfc3d21b35b41f4fbe8e91bcb0f/dev/tests/integration/testsuite/Magento/Quote/Model/QuoteIdToMaskedQuoteIdTest.php

I think it's good enough to mark this PR with a "covered" label.

**Comment by ihor-sviziev** [comment]
@magneto run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Magento Health Index

File: app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php [hunk 2]
```diff
@@ -19,43 +21,70 @@ class QuoteIdToMaskedQuoteId implements QuoteIdToMaskedQuoteIdInterface
...
+    private function checkIfQuoteExists(int $quoteId): void
+    {
+        $quote = $this->cartFactory->create();
+
+        $quote
+            ->setStoreId($this->storeManager->getStore()->getId())
+            ->loadByIdWithoutStore($quoteId);
+
+        if (!$quote->getId()) {
+            throw NoSuchEntityException::singleField('cartId', $quoteId);
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: @gabrieldagama @sivaschenko @sidolov, any ideas on how we can ignore such cases in MHI tests?

Comment (Den4ik) [reply app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: I believe that we can ignore health check in this case

**Comment by Den4ik** [comment]
@magento run Integration Tests

File: app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php (hunk 2 above)
Comment (ihor-sviziev) [reply app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: As we discussed with @gabrieldagama in slack, we can't use these methods. We should deprecate them and provide a none static alternative instead. I won't do so as part of this PR.
As for now, I'll remove using these methods.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
Integration & WebAPI test failures look like false positives.

**Review by Den4ik — APPROVED** [review]
✅ Approved. Failed tests is not related to changes in PR.

@ihor-sviziev Thanks for work

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9130](https://jira.corp.magento.com/browse/ENGCOM-9130) has been created to process this Pull Request
:eight_spoked_asterisk: @Den4ik, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by Den4ik** [comment]
@magento run WebAPI Tests, Integration Tests

**Comment by Den4ik** [comment]
@magento run Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Integration Tests

File: app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php [hunk 3]
```diff
@@ -19,43 +21,78 @@ class QuoteIdToMaskedQuoteId implements QuoteIdToMaskedQuoteIdInterface
...
+     * @return void
+     * @throws NoSuchEntityException
+     */
+    private function checkIfQuoteExists(int $quoteId): void
+    {
+        $quote = $this->cartFactory->create();
+
+        $quote
+            ->setStoreId($this->storeManager->getStore()->getId())
+            ->loadByIdWithoutStore($quoteId);
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: I found an issue - this method runs "_afterLoad" method, which then could cause triggering collect totals:
https://github.com/magento/magento2/blob/646cfbf/app/code/Magento/Quote/Model/Quote.php#L2464-L2468

Comment (ihor-sviziev) [reply app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]: Fixed by using resource model

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Semantic Version Checker

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9130](https://jira.corp.magento.com/browse/ENGCOM-9130) has been created to process this Pull Request

**Comment by Den4ik** [comment]
As we discussed with @ihor-sviziev in Slack, solution could be moved into resource model https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Quote/Model/ResourceModel/Quote/QuoteIdMask.php.
Temporary mark as `Progress: need update`

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Quote/Model/ResourceModel/Quote.php [hunk 4]
```diff
@@ -316,4 +316,28 @@ public function save(\Magento\Framework\Model\AbstractModel $object)
...
+
+    /**
+     * Quickly check if quote exists
+     *
+     * Uses direct DB query due to performance reasons
+     *
+     * @param int $quoteId
+     * @return bool
+     */
+    public function isQuoteExists(int $quoteId): bool
```
Comment (eduard13) [inline app/code/Magento/Quote/Model/ResourceModel/Quote.php]: I believe `exists` as method name is more suitable in this case. Since we are already in `Quote` ResourceModel, there is no reason to double that info in method name as well.
```suggestion
    public function exists(int $quoteId): bool
```

File: app/code/Magento/Quote/Model/ResourceModel/Quote.php [hunk 5]
```diff
@@ -316,4 +316,28 @@ public function save(\Magento\Framework\Model\AbstractModel $object)
...
+        $idFieldName = $this->getIdFieldName();
+
+        $field = $connection->quoteIdentifier(sprintf('%s.%s', $mainTable, $idFieldName));
+        $select = $connection->select()
+            ->from($mainTable, [$idFieldName])
+            ->where($field . '=?', $quoteId);
+
+        $data = $connection->fetchOne($select);
+
+        return (bool)$data;
```
Comment (eduard13) [inline app/code/Magento/Quote/Model/ResourceModel/Quote.php]: Why not simplifying like this?

```suggestion
        return (bool) $connection->fetchOne($select);
```

File: app/code/Magento/Quote/Model/ResourceModel/Quote/QuoteIdMask.php [hunk 6]
```diff
@@ -22,4 +22,27 @@ protected function _construct()
...
+        $mainTable = $this->getMainTable();
+        $field = $connection->quoteIdentifier(sprintf('%s.%s', $mainTable, 'quote_id'));
+
+        $select = $connection->select()
+            ->from($mainTable, ['masked_id'])
+            ->where($field . '=?', $quoteId);
+
+        $result = $connection->fetchOne($select);
+
+        return $result ?: null;
```
Comment (eduard13) [inline app/code/Magento/Quote/Model/ResourceModel/Quote/QuoteIdMask.php:46]: Same here, we can simplify it like the following
```suggestion
        return $connection->fetchOne($select) ?: null;
```

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @ihor-sviziev, probably we should deliver these changes to 2.5 mainline, since these are BIC in my opinion. 
Also, I believe we should be able to cover it by some automated changes.

Thank you.

File: app/code/Magento/Quote/Model/ResourceModel/Quote.php (hunk 5 above)
Comment (ihor-sviziev) [reply app/code/Magento/Quote/Model/ResourceModel/Quote.php]: I would say like this:
```suggestion
        return (bool)$connection->fetchOne($select);
```

File: app/code/Magento/Quote/Model/ResourceModel/Quote.php (hunk 4 above)
Comment (ihor-sviziev) [reply app/code/Magento/Quote/Model/ResourceModel/Quote.php]: Maybe it's better to add "is" prefix?
```suggestion
    public function isExists(int $quoteId): bool
```

**Comment by ihor-sviziev** [comment]
note more note: the changes already covered with the integration test
https://github.com/magento/magento2/blob/2.4-develop/dev/tests/integration/testsuite/Magento/Quote/Model/QuoteIdToMaskedQuoteIdTest.php

File: app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php [hunk 7]
```diff
@@ -7,55 +7,54 @@
...
-        /* Check the quote exists to avoid database constraint issues */
-        $this->cartRepository->get($quoteId);
-
-        $quoteIdMask = $this->quoteIdMaskFactory->create();
-        $this->quoteIdMaskResource->load($quoteIdMask, $quoteId, 'quote_id');
-        $maskedId = $quoteIdMask->getMaskedId() ?? '';
-
-        return $maskedId;
+        // Check the quote exists to avoid database constraint issues
+        if (!$this->quoteResource->isQuoteExists($quoteId)) {
```
Comment (ihor-sviziev) [inline app/code/Magento/Quote/Model/QuoteIdToMaskedQuoteId.php]:
```suggestion
        if (!$this->quoteResource->isExists($quoteId)) {
```

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Quote/Model/ResourceModel/Quote.php (hunk 4 above)
Comment (eduard13) [reply app/code/Magento/Quote/Model/ResourceModel/Quote.php]: I don't think it's a good idea to have names with 2 verbs.
- isVirtual
- isBlocked

So, I'd stick to `exists` method name.

**Review by andrewbess — CHANGES_REQUESTED** [review]
Hello @ihor-sviziev 
Thank you for these changes.
Great job.
Could you please squash commits?
Thank you in advance.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Quote/Model/ResourceModel/Quote/QuoteIdMask.php (hunk 6 above)
Comment (Den4ik) [reply app/code/Magento/Quote/Model/ResourceModel/Quote/QuoteIdMask.php:46]: Previous implementation looks more readable for me.
But it's my subjective opinion :)

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@Den4ik @andrewbess @eduard13 i updated the PR with all requested changes. Please review

**Review by andrewbess — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @andrewbess, thank you for the review.
[ENGCOM-9130](https://jira.corp.magento.com/browse/ENGCOM-9130) has been created to process this Pull Request

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9130](https://jira.corp.magento.com/browse/ENGCOM-9130) has been created to process this Pull Request

**Review by eduard13 — APPROVED** [review]
Looks good 👍

**Comment by magento-engcom-team** [comment]
Hi @eduard13, thank you for the review.
[ENGCOM-9130](https://jira.corp.magento.com/browse/ENGCOM-9130) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Have Magento instance installed with sample data.
2. Install Klaviyo extension (tested on version 3.0.5)


**Manual testing scenario:**

1. Admin > Create Cart Price Rule with coupon (let's give some 10% discount)

2. Frontend > Add a product to the shopping cart and apply the above created discount coupon.
 
3. Use the POST Request _http://local.magento2.com/rest/default/V1/integration/admin/token_ to get the token

4. Use the GET carts request to validate its response _http://local.magento2.com/index.php/rest/default/V1/carts/search?searchCriteria[filter_groups][0][filters][0][field]=updated_at&searchCriteria[filter_groups][0][filters][0][condition_type]=gt&searchCriteria[sortOrders][0][field]=updated_at&searchCriteria[sortOrders][0][direction]=DESC&searchCriteria[currentPage]=1&searchCriteria[pageSize]=50&searchCriteria[filter_groups][0][filters][0][value]=2021-09-09_


**Before:** :heavy_multiplication_x: Request was responding with server error response as shown in below screenshot (It is slightly different that what shown in the above issue description)

image


**After:** :heavy_check_mark:  Responding with proper cart details

image


There is no additional testing is requited since it is a API request issue on a particular case. Also there is Auto Test - covered and hence no additional regression is required to it.

**Comment by ihor-sviziev** [comment]
@magento convert to patch for 2.4.3-p1

**Comment by ihor-sviziev** [comment]
@magento convert to patch for 2.4.3

**Comment by m2-github-services** [comment]
@ihor-sviziev changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-2.4.3

**Comment by m2-github-services** [comment]
@ihor-sviziev changes has been successfully converted for 2.4.3 version and pushed to the  converted-magento-magento2-2.4.3 branch. 

 You may submit a pull request using the link: https://github.com/magento/magento2/compare/2.4.3-release...magento:converted-magento-magento2-2.4.3

**Comment by sidolov** [comment]
@magento run Performance Acceptance Tests
