### PR TITLE
FIX #11022 in 2.1-develop: Filter Groups of search criteria parameter have not been included for further processing

### LINKED ISSUE #11022: GET v1/products/attribute-sets/sets/list inconsistent return result
### Preconditions
currently i'm using the magento 2.1.9 clean fresh install

### Steps to reproduce
i call the REST api with the following
http://URL/magento-219/rest/v1/products/attribute-sets/sets/list

### Expected result
expect the full list of attribute-sets to be returned

### Actual result
```
{"message":"%fieldName is a required field.","parameters":{"fieldName":"searchCriteria"}}
```

### Steps to reproduce with search fieldname filled in
i call the REST api with the following
http://URL/magento-219/rest/v1/products/attribute-sets/sets/list?searchCriteria[filter_groups][0][filters][0][field]=attribute_set_name&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=someAttributeSet

### Expected result
expect only someAttributeSet data returned

### Actual result
i get the full list of data, it completely **disregarded** my search query
```
{"items":[{"attribute_set_id":9,"attribute_set_name":"default2","sort_order":0,"entity_type_id":4},{"attribute_set_id":4,"attribute_set_name":"Default","sort_order":1,"entity_type_id":4}],"search_criteria":{"filter_groups":[{"filters":[{"field":"entity_type_code","value":"catalog_product","condition_type":"eq"}]}]},"total_count":2}
```

### PR DESCRIPTION
**Pull request by davidverholen**
### Description

The Filter Groups and the Sort Order of the $searchCriteria parameter have not been included in the searchCriteria Object that is finally provided for the eav set repository.

This Pull request sets the filtergroups and sort order in the searchCriteriaBuilder

### Fixed Issues (if relevant)

1. magento/magento2#11022: GET v1/products/attribute-sets/sets/list inconsistent return result

### Manual testing scenarios

1. Create an additional product attribute set
1. call to GET http://URL/rest/v1/products/attribute-sets/sets/list?searchCriteria[filter_groups][0][filters][0][field]=attribute_set_name&searchCriteria[filter_groups][0][filters][0][condition_type]=eq&searchCriteria[filter_groups][0][filters][0][value]=default
2. Result should be only the default attribute set (before it always returned all product attribute sets)

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

//cc @dmanners

### CODE REVIEW

**Review by dmanners — CHANGES_REQUESTED** [review]
This does not actually seem to fix this problem in 2.1

**Comment by dmanners** [comment]
@davidverholen after testing this with 2.1 it does not actually seem to fix the issue. When you call the described API endpoints you still get all the data back. Unlike the 2.2 fix which showed only those that match the search.

**Comment by davidverholen** [comment]
@dmanners the problem is, that the filters of the search criteria are ignored in the eav attribute repository getList function in 2.1.

I've added a workaround which should fix this until it's replaced by the CollectionProcessor in 2.2

File: app/code/Magento/Eav/Test/Unit/Model/AttributeSetRepositoryTest.php [hunk 1]
```diff
@@ -212,7 +212,7 @@ public function testGetList()
         $searchCriteriaMock = $this->getMock('\Magento\Framework\Api\SearchCriteriaInterface');
 
         $filterGroupMock = $this->getMock('\Magento\Framework\Api\Search\FilterGroup', [], [], '', false);
-        $searchCriteriaMock->expects($this->once())->method('getFilterGroups')->willReturn([$filterGroupMock]);
+        $searchCriteriaMock->expects($this->exactly(2))->method('getFilterGroups')->willReturn([$filterGroupMock]);
 
         $filterMock = $this->getMock('\Magento\Framework\Api\Filter', [], [], '', false);
         $filterGroupMock->expects($this->once())->method('getFilters')->willReturn([$filterMock]);
```
Comment (dmanners) [inline app/code/Magento/Eav/Test/Unit/Model/AttributeSetRepositoryTest.php]: @davidverholen I think this is the method that needs to be called more than once in the tests.
