### PR TITLE
Issue #19609 FIXED

### LINKED ISSUE #19609: config:set --lock-config does not act on other scopes
### Preconditions

1. Magento 2.2.7;

### Steps to reproduce

1. `php bin/magento config:set --lock-config general/store_information/name "Test lock"`;
2. `php bin/magento app:config:import`;
3. `php bin/magento cache:clean`;

### Expected result

Admin user should not be able to change the configuration.

### Actual result

Admin user is not able to change the configuration for the default store, but is able to change it for any other scope (i.e.: store view).

`app/etc/config.php` generated:
```php
<?php
return [
    'modules' => [
        // ...
    ],
    'system' => [
        'default' => [
            'general' => [
                'store_information' => [
                    'name' => 'Test lock'
                ]
            ]
        ]
    ]
];

```

### Comments

Using `--scope` and `--scope-code` with the `config:set` command, I can lock for that particular store as well, but then I need to duplicate all the settings for every single website and store view in the system, and it will not effect stores created after the configuration is locked. There is no way to tell Magento "don't change this configuration in *any* scope".

### PR DESCRIPTION
**Pull request by mahesh-rajawat**
i have preposed a solution to fix #19609 issue, if there is configuration field lock entry available for
default scope then all scopes filed will be readonly.

### Fixed Issues (if relevant)

1. #19609
2. ...

### Manual testing scenarios (*)

1. create an entry in app/config.php file using this command:
 `php bin/magento config:set --lock-config general/store_information/name "Test lock";`
2. then checked the other scopes, all are disabled now.
3. Removed the default entry and create a stores scope entry:
 `bin/magento config:set --scope=stores --scope-code=india --lock-config general/store_information/name "India"`
4. Field is disabled for this particular  scope.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

File: app/code/Magento/Config/Block/System/Config/Form.php [hunk 1]
```diff
@@ -366,9 +366,12 @@ protected function _initElement(
 
         $sharedClass = $this->_getSharedCssClass($field);
         $requiresClass = $this->_getRequiresCssClass($field, $fieldPrefix);
+        $isReadOnly = $this->isDefaultFieldReadOnly($path);
```
Comment (sivaschenko) [inline app/code/Magento/Config/Block/System/Config/Form.php]: It would be nice to move all the readonly check to a private function

File: app/code/Magento/Config/Block/System/Config/Form.php [hunk 2]
```diff
@@ -797,6 +800,24 @@ private function getAppConfig()
...
+     * Check Default Path Readonly
+     *
+     * @param string $path
+     * @return boolean
+     */
+    private function isDefaultFieldReadOnly($path)
+    {
+        $scope = $this->getScope();
+        $isReadOnly = false;
+        if ($scope !== ScopeConfigInterface::SCOPE_TYPE_DEFAULT) {
```
Comment (sivaschenko) [inline app/code/Magento/Config/Block/System/Config/Form.php]: I think this check is unnecessary, `$isReadOnly` value assigned inside the condition is correct for default scope

File: app/code/Magento/Config/Block/System/Config/Form.php [hunk 3]
```diff
@@ -366,9 +366,12 @@ protected function _initElement(
 
         $sharedClass = $this->_getSharedCssClass($field);
         $requiresClass = $this->_getRequiresCssClass($field, $fieldPrefix);
+        $isReadOnly = $this->isDefaultFieldReadOnly($path);
+        if (!$isReadOnly) {
+            $isReadOnly = $this->getElementVisibility()->isDisabled($field->getPath())
+                ?: $this->getSettingChecker()->isReadOnly($path, $this->getScope(), $this->getStringScopeCode());
```
Comment (sivaschenko) [inline app/code/Magento/Config/Block/System/Config/Form.php]: Please consider injecting `\Magento\Config\Model\Config\Reader\Source\Deployed\SettingChecker`as `\Magento\Theme\Model\Design\Config\DataProvider::getSettingChecker` method is deprecated

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Hi @maheshWebkul721 , thanks for your contribution! Please take a look at the code review comments

File: app/code/Magento/Config/Block/System/Config/Form.php (hunk 1 above)
Comment (mahesh-rajawat) [reply app/code/Magento/Config/Block/System/Config/Form.php]: I have fixed this, moved all checks in private function

File: app/code/Magento/Config/Block/System/Config/Form.php (hunk 2 above)
Comment (mahesh-rajawat) [reply app/code/Magento/Config/Block/System/Config/Form.php]: Removed this check.

File: app/code/Magento/Config/Block/System/Config/Form.php (hunk 3 above)
Comment (mahesh-rajawat) [reply app/code/Magento/Config/Block/System/Config/Form.php]: @sivaschenko do i need to inject `\Magento\Config\Model\Config\Reader\Source\Deployed\SettingChecker` in constructor?

Comment (sivaschenko) [reply app/code/Magento/Config/Block/System/Config/Form.php]: Hi @maheshWebkul721 , yes, please

Comment (mahesh-rajawat) [reply app/code/Magento/Config/Block/System/Config/Form.php]: @sivaschenko added!

**Comment by sivaschenko** [comment]
Hi @maheshWebkul721 please add a new dependency in a backward compatible way, please see the `Adding a constructor parameter` section and code example here:  https://devdocs.magento.com/guides/v2.3/contributor-guide/backward-compatible-development/#php

**Comment by mahesh-rajawat** [comment]
@sivaschenko added constructor parameter as per contribution guide.

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @maheshWebkul721. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.
