### PR TITLE
Fix "area code is not set" in all commands that depend on Payment/Helper/Data

### LINKED ISSUE #33760: Magento 2.4.2 composer upgrade broke after 2.4.3 released
I am currently in the process of upgrading Magento 2.2.6 to 2.4.2. I had a stable upgrade working prior to 2.4.3 being released. After Tuesday, August 10 when 2.4.3 was released, when I composer upgrade our installation with:

`composer require magento/product-community-edition 2.4.2 --no-update`
`composer require --dev phpunit/phpunit:^9 friendsofphp/php-cs-fixer:~2.16.0 lusitanian/oauth:~0.8.10 pdepend/pdepend:~2.7.1 sebastian/phpcpd:~5.0.0 squizlabs/php_codesniffer:3.5.4 --no-update`
`composer remove --dev sjparkinson/static-review fabpot/php-cs-fixer --no-update`
`composer require msp/recaptcha 2.2.2 --no-update`
`composer require picqer/php-barcode-generator --no-update`
`composer update`

I then enabled MSI modules. During `bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations` I had problems where each inconsistency would throw an error saying 'caused exception "Area code is not set"'. I fixed this problem by manually setting the state in `vendor/magento/module-inventory-reservation-cli/Command/CreateCompensations.php`. I did not have to do this workaround prior to Tuesday.

After fixing this bug it appears my paid extensions (which hasn't been upgraded yet) now have errors.
There may be more bugs but I currently can't browse the storefront due to these errors.

Was the repository for 2.4.2 updated with the release of 2.4.3? I went from having a stable upgrade to an upgrade full of errors and the only thing that has changed is the new version of Magento releasing.

### LINKED ISSUE #33908: [Issue] Fix "area code is not set" in all commands that depend on Payment/Helper/Data
This issue is automatically created based on existing pull request: magento/magento2#33726: Fix "area code is not set" in all commands that depend on Payment/Helper/Data

---------
### Description (*)
The Helper Magento\Payment\Helper\Data creates a new layout in the constructor. This is unneccessary and creates issues when   the helper is used without specifying the area code previously (eg in commands). 

**Edit:** Also there is no real workaround to fix this. You would need to set the area in the constructor, which in turn is called every time the command list is generated, triggering "area code is already set".

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. Create a custom Command, inject Magento\Sales\Model\Service\InvoiceService or the mentioned helper directly, or some class that depends on it
2. Dont specify an area, because its not always needed, or you dont actually intend to use the layout
3. Scratch your head why it fails with error "area code is not set"

### Questions or comments
I dont think a test case is neccessary for this change, because the only place $this->_layout is used, is in one single method as a fallback when no layout has been passed to getInfoBlock(). 

Maybe using the layoutfactory inside a constructor method should be prohibited at all, or at least trigger/log a warning message. It is troublesome to detect where the root issue comes from.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by marvinhinz**
### Description (*)
The Helper Magento\Payment\Helper\Data creates a new layout in the constructor. This is unneccessary and creates issues when   the helper is used without specifying the area code previously (eg in commands). 

**Edit:** Also there is no real workaround to fix this. You would need to set the area in the constructor, which in turn is called every time the command list is generated, triggering "area code is already set".

### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/33760

### Manual testing scenarios (*)

1. Create a custom Command, inject Magento\Sales\Model\Service\InvoiceService or the mentioned helper directly, or some class that depends on it
2. Dont specify an area, because its not always needed, or you dont actually intend to use the layout
3. Scratch your head why it fails with error "area code is not set"

### Questions or comments
I dont think a test case is neccessary for this change, because the only place $this->_layout is used, is in one single method as a fallback when no layout has been passed to getInfoBlock(). 

Maybe using the layoutfactory inside a constructor method should be prohibited at all, or at least trigger/log a warning message. It is troublesome to detect where the root issue comes from.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#33908: Fix "area code is not set" in all commands that depend on Payment/Helper/Data

### CODE REVIEW

**Comment by marvinhinz** [comment]
@magento run all tests

File: app/code/Magento/Payment/Helper/Data.php [hunk 1]
```diff
@@ -183,7 +176,7 @@ public function getMethodFormBlock(MethodInterface $method, LayoutInterface $lay
      */
     public function getInfoBlock(InfoInterface $info, LayoutInterface $layout = null)
     {
-        $layout = $layout ?: $this->_layout;
+        $layout = $layout ?: $layoutFactory->create();
```
Comment (hostep) [inline app/code/Magento/Payment/Helper/Data.php]: The `$layoutFactory` variable won't exist here, you'll need to store it in a private member in the constructor to be able to use it, right?

Comment (hostep) [reply app/code/Magento/Payment/Helper/Data.php]: Nevermind, I'm too slow 😆

Comment (marvinhinz) [reply app/code/Magento/Payment/Helper/Data.php]: Just realized after clicking on create pr :D

**Comment by marvinhinz** [comment]
@magento run all tests

File: app/code/Magento/Payment/Helper/Data.php [hunk 2]
```diff
@@ -32,11 +32,9 @@ class Data extends \Magento\Framework\App\Helper\AbstractHelper
     protected $_paymentConfig;
 
     /**
-     * Layout
-     *
-     * @var \Magento\Framework\View\LayoutInterface
+     * @var \Magento\Framework\View\LayoutFactory
      */
-    protected $_layout;
+    protected $_layoutFactory;
```
Comment (Den4ik) [inline app/code/Magento/Payment/Helper/Data.php]: Please don't rename exist properties in `@api` class. It's backward incompatible.
Just add another one private property and deprecate current

**Review by Den4ik — CHANGES_REQUESTED** [review]
@marvinhinz Thanks for your contribution.
Please look at my comment

File: app/code/Magento/Payment/Helper/Data.php (hunk 2 above)
Comment (marvinhinz) [reply app/code/Magento/Payment/Helper/Data.php]: done 👍🏼

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by marvinhinz** [comment]
Unit tests report "Expectation failed for method name is "create" when invoked 1 time(s). Method was expected to be called 1 times, actually called 0 times." in app/code/Magento/Payment/Test/Unit/Helper/DataTest.php:57

I guess the assertion in line 57 can be removed, as the result of the getInfoBlock function is checked in line 219. 
What do you think?

**Comment by Den4ik** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento create issue

**Comment by gabrieldagama** [comment]
@magento create issue

**Comment by lenaorobei** [comment]
@magento create issue

**Comment by lenaorobei** [comment]
@magento create issue

**Review by Den4ik — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @marvinhinz, @hostep, @Den4ik and @ihor-sviziev 
Thanks for your contribution and collaboration!

As per the above comment the fix is working absolutely fine, but due to merge conflicts, require your help resolving the conflicts and updating the ticket. So that we can take this PR forward for merging!

Thanks in advance!

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Static Tests

**Comment by Den4ik** [comment]
> @andrewbess any thoughts on why static tests are failing?

@ihor-sviziev I have fixed static tests and now it should be passed. I hope this PR will be proceed faster

**Comment by engcom-Alfa** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests, Magento Health Index, Sample Data Tests B2B, Static Tests, Unit Tests, WebAPI Tests
