### PR TITLE
Fix issue when ProductRepository::save method was loosing 2nd argument value

### LINKED ISSUE #31870: ProductRepository $saveOptions
### Preconditions (*)

1. 2.4.1 (possibly earlier versions too)

### Steps to reproduce (*)

1. [ProductRepositoryInterface](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Api/ProductRepositoryInterface.php#L26) defines $saveOptions as a bool which mandates [ProductRepository](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Model/ProductRepository.php#L516) to use it. 
2. [ConfigurableProduct ProductRepositorySave Plugin](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php#L58) does not return $saveOptions back to ProductRepository. 

### Expected result (*)

1. The plugin returns the same arguments back to the function it plugs in to regardless of whether those arguments get used. 

### Actual result (*)

1. The plugin returns only the product object in an array, the $saveOptions get ommitted. 

### Additional Information (*)
As per the [documentation](https://devdocs.magento.com/guides/v2.4/extension-dev-guide/plugins.html), If there are any arguments, the method should return an array of those arguments. But here it is not returning the `$saveOptions` variable.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ * ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

Since $saveOptions are not used by the save function, this does not cause any issue in the functionality of the function itself, though I have found that this function will break when using the following module https://github.com/creatuity/magento2-interceptors , which forms the basis for the following PR that may or may not get merged down the line: https://github.com/magento/magento2/pull/22826

An example of a correct implementation already exists in Magento 2 core: [Product Authorization](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Plugin/ProductAuthorization.php#L44)

### PR DESCRIPTION
**Pull request by rmsundar1**
### Description (*)

- \Magento\ConfigurableProduct\Model\Plugin\ProductRepositorySave::beforeSave before plugin not returning all the original params. This PR fixed and return all the function param as per the documentation.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31870

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rmsundar1** [comment]
@magento run unit test

**Comment by rmsundar1** [comment]
@magento run all tests

File: app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php [hunk 1]
```diff
@@ -60,7 +60,7 @@ public function beforeSave(
         ProductInterface $product,
         $saveOptions = false
     ): array {
-        $result[] = $product;
+        $result = [$product, $saveOptions];
```
Comment (ihor-sviziev) [inline app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]: It looks like we're not expecting to change any arguments for the "save" method, so I think it's better to replace the return type with "void" and don't change the method arguments.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you also write some integration tests that will test that options are getting saved with the `ProductRepository::save` method after your change?

**Comment by rmsundar1** [comment]
> Could you also write some integration tests that will test that options are getting saved with the `ProductRepository::save` method after your change?

@ihor-sviziev This plugin is doing validation and not changing data in the object, so I hope you meant the unit tests here, please confirm.

**Comment by ihor-sviziev** [comment]
@rmsundar1 if I got correctly - the original method save was all the time getting the false value for save options and wasn't doing so. The issue wasn't in the plug-in itself, but in the integration of plug-in and the original code. In order to prevent such issue in future - it's better to add integration test coverage for the case of saving options via repository

File: app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php (hunk 1 above)
Comment (Den4ik) [reply app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]: I'm agree with @ihor-sviziev. In fact we could remove unused params in plugin

**Review by Den4ik — CHANGES_REQUESTED** [review]

File: app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php (hunk 1 above)
Comment (rmsundar1) [reply app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]: @Den4ik @ihor-sviziev This argument is not been used in the \Magento\Catalog\Model\ProductRepository::save function itself, should we remove that param from the interface itself?

Comment (ihor-sviziev) [reply app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]: Ohhh. Interesting... in this case, why it's actually needed and what the issue you have?

Comment (Den4ik) [reply app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]: @rmsundar1 We could not remove unused parameter from repository in patch release because it's BIC. Plugin cleanup is good point for PR

File: app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php [hunk 2]
```diff
@@ -59,34 +59,24 @@ public function beforeSave(
...
-        if ($extensionAttributes === null) {
-            return $result;
-        }
-
-        $configurableLinks = (array) $extensionAttributes->getConfigurableProductLinks();
-        $configurableOptions = (array) $extensionAttributes->getConfigurableProductOptions();
+    ): void {
+        if ($product->getTypeId() === Configurable::TYPE_CODE
+            && null !== ($extensionAttributes = $product->getExtensionAttributes())
+        ) {
```
Comment (ihor-sviziev) [inline app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]:
```suggestion
        $extensionAttributes = $product->getExtensionAttributes();
        if (null !== $extensionAttributes && $product->getTypeId() === Configurable::TYPE_CODE) {
```

File: app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php [hunk 3]
```diff
@@ -150,52 +147,7 @@ public function testBeforeSaveWithoutOptions(): void
...
-            $this->plugin->beforeSave($this->productRepository, $this->product)[0]
-        );
-    }
-
-    /**
-     * Test saving a configurable product with same set of attribute values
-     *
-     * @return void
-     */
-    public function testBeforeSaveWithLinks(): void
```
Comment (ihor-sviziev) [inline app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php:164]: why was it removed?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php (hunk 3 above)
Comment (rmsundar1) [reply app/code/Magento/ConfigurableProduct/Test/Unit/Model/Plugin/ProductRepositorySaveTest.php:164]: @ihor-sviziev This case is already covered in `testBeforeSaveWithLinksWithDuplicateAttributes` function. Now ConfigurableProductLinks and ConfigurableProductOptions are mandatory to perform validation and  `testBeforeSaveWithLinks ` function is not passing enough argument to validate the exact case. So I removed that

**Comment by rmsundar1** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php [hunk 4]
```diff
@@ -59,34 +59,23 @@ public function beforeSave(
...
-            return $result;
-        }
-
-        $attributeCodes = [];
-        /** @var OptionInterface $configurableOption */
-        foreach ($configurableOptions as $configurableOption) {
-            $eavAttribute = $this->productAttributeRepository->get($configurableOption->getAttributeId());
-            $attributeCode = $eavAttribute->getAttributeCode();
-            $attributeCodes[] = $attributeCode;
+            if (!empty($configurableLinks) && !empty($configurableOptions)) {
```
Comment (Den4ik) [inline app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]: Previous behaviour allow one of variables `$configurableLinks` or `$configurableOptions` could be empty. Changes disallow that. By this way some of WebAPI tests are failed. Could you please check and fix this tests.

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @rmsundar1. Thanks for work on this PR.
Could you please check comment below

File: app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php (hunk 4 above)
Comment (ihor-sviziev) [reply app/code/Magento/ConfigurableProduct/Model/Plugin/ProductRepositorySave.php]:
```suggestion
            if (!empty($configurableLinks) || !empty($configurableOptions)) {
```

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Review by Den4ik — APPROVED** [review]

**Comment by rmsundar1** [comment]
Hi @engcom-Alfa,
Create a Before plugin for [ProductRepositoryInterface](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Catalog/Api/ProductRepositoryInterface.php#L26) with sortOrder value as 30 or some higher number and try to read the 2nd argument value in the execution. 

Expected result: 2nd argument $saveOptions should be available

Actual result: 2nd argument $saveOptions is getting ommitted

https://github.com/magento/magento2/issues/31870

**Comment by engcom-Alfa** [comment]
Hi @rmsundar1 and @ihor-sviziev 
I have tried to reproduce it and no issue is observed. Kindly check the [steps-followed here](https://github.com/magento/magento2/issues/31870#issuecomment-995588464).
Let me know if there is any change in my execution.

**Comment by ihor-sviziev** [comment]
@engcom-Alfa, any updates on testing?

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa, any updates on testing?

Yes as [commented above](https://github.com/magento/magento2/pull/34252#issuecomment-995613961), again placing all the details below: Please take a look and let me know how can we reproduce it.

As I have re-verified again, the $saveoptions is not getting omitted!
Please refer below steps that I have followed, and kindly let me know if anything needs to be added/changed.

**Using existing model:**

1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40 as shown in below screenshot
Screenshot 2021-12-16 at 2 35 39 PM

2. Placed the var_dump line of code in the configurableProduct>Model>Plugin>ProductRepositorySave.php file as shown in below screenshot.
Screenshot 2021-12-16 at 2 35 52 PM

3. Placed the var_dump line of code in Catalog>Model>ProductRepository.php file as shown in below screenshot.
Screenshot 2021-12-16 at 2 36 05 PM

4. Tried to add the configurable product through API request and found the $saveoptions has a value
 set to bool(false) as shown in the below screenshot.
Screenshot 2021-12-16 at 2 35 17 PM



**Using new custom plugin:**
5. Instead of that, created new plugin as shown in below 2 screenshots.
Screenshot 2021-12-16 at 2 37 00 PM

Screenshot 2021-12-16 at 2 38 30 PM

Still I am getting the same output as mentioned in the step 4 screenshot @rmsundar1

**Comment by rmsundar1** [comment]
@engcom-Alfa  Can you try passing `true` as second argument values, in your case looks like the default value(i.e., `false`) of the second argument is been used.

**Comment by engcom-Alfa** [comment]
> @engcom-Alfa Can you try passing `true` as second argument values, in your case looks like the default value(i.e., `false`) of the second argument is been used.

Hi @rmsundar1 thanks for your reply! I have retried with the below steps:

1. Placed the $save_options = true and var_dump lines of code in the _configurableProduct>Model>Plugin>ProductRepositorySave.php_ file as shown in below screenshot.
image

2. Placed the echo var_dump lines of code in the _configurableProduct>Model>Plugin>ProductRepositorySave.php_ file as shown in below screenshot.
image

3. Executed the Create Configurable product API request and noticed the below output as shown in screenshot
image

As you suggested to pass _true_ as second argument values, I have just considered in the way mentioned in step 1 above. Kindly let me know if you meant something different please ?
If we see the third step output screenshot, we are seeing _false_ output from _ProductRepositorySave.php:save_ method. is that the issue we are trying to solve in this PR? Should it return _true_ after the PR changes?

**Comment by rmsundar1** [comment]
> If we see the third step output screenshot, we are seeing false output from ProductRepositorySave.php:save method. is that the issue we are trying to solve in this PR? Should it return true after the PR changes?

@engcom-Alfa Yes correct.

**Comment by engcom-Alfa** [comment]
Hi @rmsundar1, @Den4ik and @ihor-sviziev 
Thanks for the collaboration & contribution!

:x: QA not Passed

_ProductRepository::save method is loosing second argument value_

**Manual Scenario Steps**
As mentioned in above [comment1](https://github.com/magento/magento2/pull/34252#issuecomment-1004164935) and [comment2](https://github.com/magento/magento2/pull/34252#issuecomment-1007404615) followed same steps (we can refer same above screenshots too)
1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40
2. Placed the $save_options = true and var_dump lines of code in the configurableProduct>Model>Plugin>ProductRepositorySave.php file
3. Placed the var_dump line of code in Catalog>Model>ProductRepository.php file
4. Tried to add the configurable product through API request


**:heavy_check_mark: Expected result After Fix** 
- Expected API response return values like:
`Inside before save -bool(true)
Inside save method--bool(true)`


**:x: Actual result After Fix** 
- API response has the return values like:
`Inside before save -bool(true)
Inside save method--bool(false)`

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Based on the above-comment requesting to cross check again please!

**Comment by ihor-sviziev** [comment]
@engcom-Alfa, your testing results don't look logical to me. It looks like some other plugin might cause a similar issue. Did you test it based on Magento Open Source?

**Comment by ishakhsuvarov** [comment]
Moving to `Extended Testing` to get tested again.

**Comment by engcom-Echo** [comment]
Hi @rmsundar1, @Den4ik and @ihor-sviziev 
Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

_ProductRepository::save method is loosing second argument value_

**Manual Scenario Steps**
1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40
2. Passed save_options = true and var_dump() in Catalog>Model>ProductRepository.php
4. Tried to add the configurable product through API request


**:heavy_check_mark: Expected result After Fix** 
- Expected API response return values like:
`Inside before save -bool(true)
Inside save method--bool(true)`


**:heavy_check_mark: Actual result After Fix** 
- API response has the return values like:
`Inside before save -bool(true)
Inside save method--bool(false)`

**Comment by engcom-Echo** [comment]
Hi @rmsundar1, @Den4ik and @ihor-sviziev 
Thanks for the collaboration & contribution!

:heavy_check_mark: QA Passed

_ProductRepository::save method is loosing second argument value_

**Manual Scenario Steps**
1. Referred the ConfigurableProduct module and its di.xml; Changed the sort order to 40
2. Passed save_options = true and var_dump() in Catalog>Model>ProductRepository.php
image

3. Tried to add the configurable product through API request
image


**Before:** :heavy_multiplication_x: 
image



**After:** :heavy_check_mark: 
image

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Integration Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B
