### PR TITLE
#36947 Fixed timezone of order_date field returned from graphql customerOrders query

### LINKED ISSUE #36947: customer Orders query shipment comments created_at is returned in +0 timezone not in store configured timezone
### Preconditions and environment

Magento 2.4.x

### Steps to reproduce

1. Configure your store with a timezone different from +0
2. Create a Shipment with a comment
3. Verify the comment created_at in the normal view phtml in the website
4. Call customer Orders query and check created_at field from shipment comment

### Expected result

The expected result is that the time from both view and query be the same and in our configured timezone

### Actual result

The actual result is that the time from view is right in our timezone, and in query it is in +0 timezone

### Additional information

In view phtml the created_at goes through a formatDate function
path: Magento_Sales::order/comments.phtml

In query processing, it does not
path: Magento\SalesGraphQl\Model\Resolver\Shipments line 65

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bartlomiejsz**
### Description (*)

The PR changes `order_date` field in `customerOrders` query to return date using store timezone instead of UTC.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#36947

### Manual testing scenarios (*)

1. Configure your store with a timezone different from +0
2. Create a Shipment with a comment
3. Verify the comment created_at in the normal view phtml in the website
4. Call customer Orders query and check created_at field from shipment comment

### Questions or comments

I believe no tests other than manual should be required here

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Review by engcom-Hotel — COMMENTED** [review]
Hello @Bartlomiejsz,

Kindly resolve the PR conflicts so we can proceed with further processing. In the meantime, we are moving this PR to "On Hold."

Thanks

**Comment by engcom-Hotel** [comment]
Hello @Bartlomiejsz,

Have you had a chance to look into this https://github.com/magento/magento2/pull/38264#pullrequestreview-2497966812?

Thanks

**Comment by Bartlomiejsz** [comment]
Hello @engcom-Hotel,

Not yet, I will take care of it today or tomorrow at the latest

Best regards

**Comment by Bartlomiejsz** [comment]
Hello @engcom-Hotel, conflicts resolved

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Bartlomiejsz,

Thanks for the contribution!

Please fix the failed tests, specifically webAPI test and static test. It seem they are failing due to PR changes.

Also please cover the changes with some automated tests in accordance to [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

**Comment by Bartlomiejsz** [comment]
@magento run all tests

**Comment by Bartlomiejsz** [comment]
@magento run all tests

File: app/code/Magento/SalesGraphQl/Model/Formatter/Order.php [hunk 1]
```diff
@@ -17,14 +20,19 @@
  */
 class Order
 {
+    private TimezoneInterface $timezone;
```
Comment (engcom-Hotel) [inline app/code/Magento/SalesGraphQl/Model/Formatter/Order.php]: Add doc-block as follows:

```suggestion
/**
     * @var TimezoneInterface $timezone
     */
    private TimezoneInterface $timezone;
```

File: app/code/Magento/SalesGraphQl/Model/Resolver/CreditMemo/CreditMemoComments.php [hunk 2]
```diff
@@ -7,17 +7,28 @@
...
+use Magento\Framework\Stdlib\DateTime;
+use Magento\Framework\Stdlib\DateTime\TimezoneInterface;
 use Magento\Sales\Api\Data\CreditmemoInterface;
 
 /**
  * Resolve credit memo comments
  */
 class CreditMemoComments implements ResolverInterface
 {
+    private TimezoneInterface $timezone;
```
Comment (engcom-Hotel) [inline app/code/Magento/SalesGraphQl/Model/Resolver/CreditMemo/CreditMemoComments.php]: Add here as well

File: app/code/Magento/SalesGraphQl/Model/Resolver/Invoices.php [hunk 3]
```diff
@@ -19,6 +22,14 @@
  */
 class Invoices implements ResolverInterface
 {
+    private TimezoneInterface $timezone;
```
Comment (engcom-Hotel) [inline app/code/Magento/SalesGraphQl/Model/Resolver/Invoices.php]: Same here

File: app/code/Magento/SalesGraphQl/Model/Resolver/Shipments.php [hunk 4]
```diff
@@ -19,6 +22,14 @@
  */
 class Shipments implements ResolverInterface
 {
+    private TimezoneInterface $timezone;
```
Comment (engcom-Hotel) [inline app/code/Magento/SalesGraphQl/Model/Resolver/Shipments.php]: Same here

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Bartlomiejsz,

Please fix the static test failures and take a look into my review comments below.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
> Hello @Bartlomiejsz,
> 
> Please fix the static test failures and take a look into my review comments below.
> 
> Thanks

@engcom-Hotel: I have fixed it. Moving it back to pending review.

cc: @Bartlomiejsz

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @Bartlomiejsz,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Configure your store with a timezone different from +0
- Create a Shipment with a comment
- Verify the comment created_at in the normal view phtml in the website
- Call customer Orders query and check created_at field from shipment comment


**Before:** :heavy_multiplication_x: 

Screenshot 2024-12-23 at 10 03 37 am



Screenshot 2024-12-23 at 10 03 17 am





**After:** :heavy_check_mark: 

Screenshot 2024-12-23 at 10 03 37 am

Screenshot 2024-12-23 at 10 23 08 am


Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE

**Comment by engcom-Dash** [comment]
The Functional B2B test failures seem to be flaky. They neither part of PR nor failing because of the PR changes, hence moving it to Merge in Progress.

EndToEndB2CLoggedInUserTestCest: This failure can also be seen in other PRs ([see here](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39004/4d1c3d53f61d35b83e974b6a26f7633f/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/e0a5ba7e9bc3639b/))

Run 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38264/72d60e414b51069b100a672815652a22/Functional/allure-report-b2b/index.html#categories/55e0aa33671c7658b2cdf6bcb3eb80e1/ea01e971fa54cbc1/
image

Run 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/38264/bad027bfbf0c5af8ce66245974aa7dd6/Functional/allure-report-b2b/index.html#categories/6ca9d315ebd9ab54dbe1fb9148ebdc1f/af11cf8e146f160f/
image
