### PR TITLE
Escape disabled modules in code compilation - setup:di:compile

### LINKED ISSUE #38241: Compiling code of disabled module
### Preconditions and environment

- Magento 2.4.*
- Disable extension doesn't exclude extension code from compiling.

### Steps to reproduce

1. Disable modules that have error or incompatible with system.
2. Run setup:di:compile command gives error if modules have some issue.

### Expected result

Expected: 
                Disable module doesn't compile code of disabled extension/module. if there's issue on code it shouldn't give compile error.

### Actual result

console compile command throwing errors of disable modules.

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [X] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by lucafuser**
### Description (*)

As disabled module is being compiled, so in this PR I've escaped disabled modules before code compilation.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38241

### Manual testing scenarios (*)

1. In `app/etc/config.php` set "0" to a module OR run `php bin/magento module:disable Vendor_Module`
2. Run `php bin/magento setup:di:compile`

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [X] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lucafuser** [comment]
@magento run all tests

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php [hunk 1]
```diff
@@ -1,29 +1,38 @@
 <?php
 /**
- * Copyright 2015 Adobe
+ * Copyright 2025 Adobe
```
Comment (in-session) [inline setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: Correct format should be:

```
/**
 * Copyright 2015 Adobe
 * All rights reserved.
 */
```
Source: https://developer.adobe.com/commerce/contributor/guides/code-contributions/backward-compatibility-policy/#adding-a-constructor-parameter

File: setup/src/Magento/Setup/Test/Unit/Console/Command/DiCompileCommandTest.php [hunk 2]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2025 Adobe
```
Comment (in-session) [inline setup/src/Magento/Setup/Test/Unit/Console/Command/DiCompileCommandTest.php]: 2015

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php [hunk 3]
```diff
@@ -156,20 +165,33 @@ protected function execute(InputInterface $input, OutputInterface $output)
         }
 
         $modulePaths = $this->componentRegistrar->getPaths(ComponentRegistrar::MODULE);
+        $moduleStatuses = $this->deploymentConfig->get(ConfigOptionsListConstants::KEY_MODULES);
+        if (!$moduleStatuses || !is_array($moduleStatuses)) {
+            return Cli::RETURN_FAILURE;
+        }
```
Comment (ihor-sviziev) [inline setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: I think we should write some message before returning a failure code, so that it will be clear why it failed

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php [hunk 4]
```diff
@@ -156,20 +165,33 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+        $enabledModuleStatuses = array_filter($moduleStatuses, function ($enabled) {
+            return $enabled === 1;
+        });
+        $enabledModules = array_keys($enabledModuleStatuses);
+
+        $modulePathsEnabled = array_filter($modulePaths, function ($path, $module) use ($enabledModules) {
+            return in_array($module, $enabledModules, true);
+        }, ARRAY_FILTER_USE_BOTH);
```
Comment (ihor-sviziev) [inline setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: This can be simplified like this:
```suggestion
        $modulePathsEnabled = array_filter($modulePaths, function ($path, $module) use ($moduleStatuses) {
            return ($moduleStatuses[$module] ?? 0) === 1;
        }, ARRAY_FILTER_USE_BOTH);
```

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php [hunk 5]
```diff
@@ -156,20 +165,33 @@ protected function execute(InputInterface $input, OutputInterface $output)
         }
 
         $modulePaths = $this->componentRegistrar->getPaths(ComponentRegistrar::MODULE);
+        $moduleStatuses = $this->deploymentConfig->get(ConfigOptionsListConstants::KEY_MODULES);
```
Comment (ihor-sviziev) [inline setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:168]: I just wonder how this behaves when the deployment config isn't available yet.

Comment (lucafuser) [reply setup/src/Magento/Setup/Console/Command/DiCompileCommand.php:168]: In case of deployment config not available, i think is correct to return a failure like initial checkEnvironment method   
https://github.com/magento/magento2/blob/7acdc6d549d56d2df3092179e56d4816dbd729d4/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php#L157

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php (hunk 1 above)
Comment (lucafuser) [reply setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: @in-session fixed

File: setup/src/Magento/Setup/Test/Unit/Console/Command/DiCompileCommandTest.php (hunk 2 above)
Comment (lucafuser) [reply setup/src/Magento/Setup/Test/Unit/Console/Command/DiCompileCommandTest.php]: Fixed

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php (hunk 3 above)
Comment (lucafuser) [reply setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: Ok, done

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php (hunk 4 above)
Comment (lucafuser) [reply setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: Done, thank you

**Comment by lucafuser** [comment]
@magento run all tests

File: setup/src/Magento/Setup/Console/Command/DiCompileCommand.php [hunk 6]
```diff
@@ -156,20 +165,31 @@ protected function execute(InputInterface $input, OutputInterface $output)
...
+
+        if (!$moduleStatuses || !is_array($moduleStatuses)) {
+            $output->writeln('<error>Deployment config not available.</error>');
+            return Cli::RETURN_FAILURE;
+        }
```
Comment (ihor-sviziev) [inline setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: As you pointed in https://github.com/magento/magento2/pull/39723/files#r1990180085, this was already checked in https://github.com/magento/magento2/blob/7acdc6d549d56d2df3092179e56d4816dbd729d4/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php#L157

I guess we can simply remove these lines
```suggestion
```

Comment (lucafuser) [reply setup/src/Magento/Setup/Console/Command/DiCompileCommand.php]: Done!

**Review by ihor-sviziev — APPROVED** [review]

**Comment by lucafuser** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hi @lucafuser

Thanks for collaboration & contribution!

<h3>✔️  QA Passed </h3>

**Preconditions:**

Install fresh Magento 2.4-develop

**Steps to Reproduce:**

1. Disable modules that have error or incompatible with system. In app/etc/config.php set "0" to a module OR run php bin/magento module:disable Vendor_Module
2. Run setup:di:compile command gives error if modules have some issue.

**Before:** ❌ 
 Created a custom module and set it as 0 in app/etc/config.php and injected some class files in constructor which does not exists

image


PR-39723-1


<h4>After: ✔️  </h4>



Builds are failed hence moving this PR in **Extended Testing.**

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by engcom-Dash** [comment]
Test failures for Functional B2B are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: [Allure Report B2B](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39723/d84041be35af309665ea7dbda72e9be9/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d)

image


Build 2: [Allure Report B2B](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39723/f875e44fc32750b29618213481505693/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741)

image

Hence, moving this pr in Merge In Progress.

Thanks.
