### PR TITLE
Removed fileinfo extension dependency from CMS module

### LINKED ISSUE #16531: [Magento 2.2.5 - 2.3.x] Upload fails in image uploader
### Additional Triage information 
- Issue was re-verified on the lates `2.3-develop` (16 Oct 2019) for more details see https://github.com/magento/magento2/issues/16531#issuecomment-542557283

**Summary**
When uploading an image in the uploader, the error "File validation failed." is shown. This error appeared after updating to 2.2.5.

**Preconditions**
PHP Version 7.0.1
Magento ver. 2.2.5
Make function "mime_content_type" undefined

**Steps to reproduce**
1. Edit a block
2. Select the image uploader ("Insert Image" button or the one in the editor)
3. Select an image from your hd and upload it.

**Expected result**
An added image in the gallery

**Actual result**
An error is shown: "File validation failed." No image is uploaded.

I tried different kind of filetypes. In 2.2.4 and previous versions there was no problem, the only thing that changed is the updated version.

### LINKED ISSUE #24332: [Magento 2.3.2] Upload fails in image uploader
**Preconditions:**
Magento 2.4-develop
Php 7.3
_fileinfo_ php extension is disabled

**Steps to reproduce:**

1. Go to Admin -> Content -> Pages;
2. Open "Home Page" to edit (for ex.);
3. Expand the **Content** tab;
4. Select the image uploader ("Insert Image" button or the one in the editor);
5. Select an image from your HD and upload it.

**Actual Result:** :heavy_multiplication_x:  Error: Call to undefined function _mime_content_type()_

:heavy_multiplication_x:  An error is shown: "File validation failed." No image is uploaded.

Screenshot from 2020-09-08 10-59-21

**Expected Result:** :heavy_check_mark: An image must be uploaded without errors

Screenshot from 2020-09-18 15-54-24

The temp uploaded file, i.e., '/tmp/sdfds5we23e', which has no extension, is trying to get the extension thus failing to verify against the validTypes array

### LINKED ISSUE #29852: [Magento 2.3.5 p2] Upload fails in image uploader
### Preconditions (*)

1.magento 2.3.5 p2
2.php 7.3

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

**show this error please help ASAP**

**"Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/designoneonline/public_html/shop/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php:365 Stack trace: #0 /home/designoneonline/public_html/shop/generated/code/Magento/Cms/Model/Wysiwyg/Images/Storage/Interceptor.php(37): Magento\Cms\Model\Wysiwyg\Images\Storage->getFilesCollection('/home/designone...', NULL) #1 /home/designoneonline/public_html/shop/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(60): Magento\Cms\Model\Wysiwyg\Images\Storage\Interceptor->getFilesCollection('/home/designone...', NULL) #2 /home/designoneonline/public_html/shop/vendor/magento/module-cms/Block/Adminhtml/Wysiwyg/Images/Content/Files.php(74): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFiles() #3 /home/designoneonline/public_html/shop/vendor/magento/module-cms/view/adminhtml/templates/browser/content/files.phtml(13): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Files->getFilesCount() #4 /home/designoneonl in /home/designoneonline/public_html/shop/vendor/magento/module-cms/Model/Wysiwyg/Images/Storage.php on line 365"**

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will remove the dependency of fileinfo extension from the CMS

### Fixed Issues (if relevant)

1. Fixes magento/magento2#24332
2. Fixes https://github.com/magento/magento2/issues/16531
3. Fixes https://github.com/magento/magento2/issues/29852

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by konarshankar07** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php [hunk 1]
```diff
@@ -197,6 +204,7 @@ public function __construct(
         array $data = [],
         \Magento\Framework\Filesystem\DriverInterface $file = null,
         \Magento\Framework\Filesystem\Io\File $ioFile = null,
+        \Magento\Framework\File\Mime $mime = null,
```
Comment (VladimirZaets) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php]: The new optional parameter should be added to the end of the parameters list. Please move it after `\Psr\Log\LoggerInterface $logger = null`

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @konarshankar07, thanks for collaboration. Please take a look at my review comments and please fix the tests

**Comment by konarshankar07** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php (hunk 1 above)
Comment (konarshankar07) [reply app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php]: I've moved the optional parameter at the end of the parameter list

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
Hi, @konarshankar07 can you please fix static tests?
Thank you.

File: app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php [hunk 2]
```diff
@@ -22,6 +22,7 @@
  * @SuppressWarnings(PHPMD.TooManyFields)
  * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
  * @SuppressWarnings(PHPMD.CookieAndSessionMisuse)
+ * @SuppressWarnings(PHPMD.CyclomaticComplexity)
```
Comment (konarshankar07) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/Storage.php]: Hello @engcom-Charlie ,
I tried to suppress the warning to fix the static test but not able to see its working or not?
Can you please help me out?
Thanks

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for updates @konarshankar07 ! Can you please cover the `getFilesCollection` method with an integration test

**Comment by konarshankar07** [comment]
Hello @sivaschenko ,

The method is already covered with integration test https://github.com/magento/magento2/blob/d1ff2ca274000c45da44cf206a77a1ef78e39be0/dev/tests/integration/testsuite/Magento/Cms/Model/Wysiwyg/Images/StorageTest.php#L84

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8116](https://jira.corp.magento.com/browse/ENGCOM-8116) has been created to process this Pull Request

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @konarshankar07,
I just looked more detailed - seems like https://github.com/magento/magento2/blob/d1ff2ca274000c45da44cf206a77a1ef78e39be0/dev/tests/integration/testsuite/Magento/Cms/Model/Wysiwyg/Images/StorageTest.php#L84-L99 isn't testing that mime type is really set and it is correct. Would be better to test it on some real file with a real content

Could you update your PR accordingly?

**Comment by konarshankar07** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@konarshankar07 integration test still fails, please check it.

**Comment by konarshankar07** [comment]
Hello @ihor-sviziev ..
Yes, I know and working on it to improve the tests
Thanks

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8116](https://jira.corp.magento.com/browse/ENGCOM-8116) has been created to process this Pull Request

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by ihor-sviziev — DISMISSED** [review]
✔ Approved.

Failing tests looks not related to changes form this PR.

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8116](https://jira.corp.magento.com/browse/ENGCOM-8116) has been created to process this Pull Request

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
Hi @konarshankar07 .

Unfortunately, change does not seem to solve the problem completely.
The error has disappeared but the images are still not loading.

**Precondition:**

_fileinfo_ php extension is disabled

**Manual testing scenario:**

1. Go to Admin -> Content -> Pages;
2. Open "Home Page" to edit (for ex.);
3. Expand the **Content** tab;
4. Select the image uploader ("Insert Image" button or the one in the editor);
5. Select an image from your HD and upload it.

**Before:** :heavy_multiplication_x:  Error: Call to undefined function _mime_content_type()_

:heavy_multiplication_x:  An error is shown: "File validation failed." No image is uploaded.

Screenshot from 2020-09-08 10-59-21

**After:** :heavy_check_mark: No error: Error: Call to undefined function _mime_content_type()_

:heavy_multiplication_x: The error is still displayed: "File validation failed." No image is uploaded.

Screenshot from 2020-09-08 11-58-54

@konarshankar07 Could you take a look?

Thanks!

**Comment by konarshankar07** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/File/Mime.php [hunk 3]
```diff
@@ -108,6 +108,9 @@ public function getMimeType($file)
 
         if (function_exists('mime_content_type')) {
             $result = $this->getNativeMimeType($file);
+        } else {
+            $imageInfo = getimagesize($file);
+            $result = $imageInfo['mime'];
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/File/Mime.php:113]: Hi @konarshankar07,
Could you cover this change with some kind of test?

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/File/Mime.php [hunk 4]
```diff
@@ -108,6 +108,9 @@ public function getMimeType($file)
...
         }
 
         if (null === $result && isset($this->mimeTypes[$extension])) {
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/File/Mime.php:116]: Also not clear why this part wasn't executed? 😕

Comment (konarshankar07) [reply lib/internal/Magento/Framework/File/Mime.php:116]: It was executing but returning `application/octet-stream` cause the tmp file doesn't have any extension so we can't check the mime type if fileinfo extension is disabled and without file extension and its leads to file validation exception
https://github.com/magento/magento2/blob/5cd4345b76f7e7806124195aa8647e5c365cce1f/lib/internal/Magento/Framework/File/Mime.php#L113-L117

**Comment by konarshankar07** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8116](https://jira.corp.magento.com/browse/ENGCOM-8116) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Precondition:**

_fileinfo_ php extension is disabled

**Manual testing scenario:**

1. Go to Admin -> Content -> Pages;
2. Open "Home Page" to edit (for ex.);
3. Expand the **Content** tab;
4. Select the image uploader ("Insert Image" button or the one in the editor);
5. Select an image from your HD and upload it.

**Before:** :heavy_multiplication_x:  Error: Call to undefined function _mime_content_type()_

:heavy_multiplication_x:  An error is shown: "File validation failed." No image is uploaded.

Screenshot from 2020-09-08 10-59-21

**After:** :heavy_check_mark: An image was successfully uploaded and added to a page

Screenshot from 2020-09-18 15-54-24

Also, was tested with enabled _fileinfo_ extension, on blocks, widgets and everything works as expected.
