### PR TITLE
magento/magento2#39169: Special Price To Date is wrongly validated on applySpecialPrice

### LINKED ISSUE #39169: Special Price To Date is wrongly validated on applySpecialPrice
### Preconditions and environment

- Actually reproduced on Magento 2.4.4-p7 but nothing is changed in recent version 

### Steps to reproduce

Use Rest API to set special price 
/rest/default/V1/products/special-price

provide body like 
```json
{
  "prices": [
    {
      "price": 5,
      "store_id": 1,
      "sku": "1181",
      "price_from": "2024-08-02 17:00:00",
      "price_to": "2024-09-12 17:00:00",
      "extension_attributes": {}
    }
  ]
}
```
then check your price on front-end 
admin or whatever

your special price will be visible until tomorrow 17

so instead expire at 2024-09-12 17:00:00 it will expire on 2024-09-13 17:00:00

because of validation on Magento\Catalog\Model\Product\Type\Price::calculateSpecialPrice

```php
            if ($this->_localeDate->isScopeDateInInterval($store, $specialPriceFrom, $specialPriceTo)) {
                $finalPrice = min($finalPrice, (float) $specialPrice);
            }
```

instead of check in range from -> to 
it add to end date 1 day 

Magento\Framework\Stdlib\DateTime\Timezone::isScopeDateInInterval

maybe it can be used for other validation but for real not for calculateSpecialPrice it should be in range from -> to set by admin 

### Expected result

Product special price should expire on date set by admin or 3rd party system by REST API 

### Actual result

End date is missed and expire day after

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by KrasnoshchokBohdan**
### Description (*)

As the author of the issue mentioned, if we add a special price using POST <host>/rest/<store_code>/V1/products/special-price specifying in the request body date like "price_to": "2017-07-16 23:59:59" i.e. time including hours, minutes and seconds, then as a result we will get that the special price will be valid for one day longer than the specified date

this happens in the method \Magento\Framework\Stdlib\DateTime\Timezone::isScopeDateInInterval where there is code that literally adds +1 day

```
      if ($dateTo) {
            // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
            $toTimeStamp += 86400;
        }
```
according to the example from the [documentation](https://developer.adobe.com/commerce/webapi/rest/modules/catalog/catalog-pricing/) (where "price_to": "2017-07-16 23:59:59" including hours is specified) we get this execution
Screenshot 2025-03-01 at 12 35 20

therefore in this pull request I propose to skip adding 1 day in case in "price_to" specifies the time including hours

### Related Pull Requests

--

### Fixed Issues (if relevant)

1. Fixes magento/magento2#39169

### Manual testing scenarios (*)

1. add special price to product by POST <host>/rest/<store_code>/V1/products/special-price according [documentation](https://developer.adobe.com/commerce/webapi/rest/modules/catalog/catalog-pricing/)
2. check product price, it will have special price one day longer

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @KrasnoshchokBohdan,

Thanks for the contribution!

Please fix the failed static test and also please add an automated test in accordance to the [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/).

Thanks

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @KrasnoshchokBohdan,

Please also add some automated tests.

Thanks

File: lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php [hunk 1]
```diff
@@ -274,7 +274,7 @@ public function isScopeDateInInterval($scope, $dateFrom = null, $dateTo = null)
         $scopeTimeStamp = $this->scopeTimeStamp($scope);
         $fromTimeStamp = strtotime($dateFrom);
         $toTimeStamp = strtotime($dateTo);
-        if ($dateTo) {
+        if ($dateTo && date('H:i:s', strtotime($dateTo)) === '00:00:00') {
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Stdlib/DateTime/Timezone.php]: We will have the same +1 day result if use '00:00:00' in the API query. I'm not sure that it's correct solution

**Review by Den4ik — CHANGES_REQUESTED** [review]

**Comment by KrasnoshchokBohdan** [comment]
@Den4ik 

> We will have the same +1 day result if use '00:00:00' in the API query. I'm not sure that it's correct solution

pls provide more information

if we update special price with 
"price_to": "2025-07-18 00:00:00" we get "2025-07-18 23:59:59" and this is ok by my view 
but if we update with
"price_to": "2025-07-18 17:00:00" we get "2025-07-19 17:00:00" before fix 
and "2025-07-18 17:00:00" after

> your special price will be visible until tomorrow 17
> so instead expire at 2024-09-12 17:00:00 it will expire on 2024-09-13 17:00:00

https://github.com/magento/magento2/issues/39169 from description

how I tested it 

https://app.magento.test/rest/default/V1/products/special-price (app.magento.test replace with your base_url)
body
{
  "prices": [
    {
      "price": 100,
      "store_id": 0,
      "price_from": "2025-04-08 00:00:00",
      "price_to": "2025-07-18 17:00:00",
      "sku": "test-simple"  // your sku
    }
  ]
}
(date price_from should be not in future)

if we check with POST <host>/rest/<store_code>/V1/products/special-price-information
or in catalog_product_entity_datetime price_to date will be the same as in body (for example "2025-07-18 17:00:00")

but we should triger \Magento\Framework\Stdlib\DateTime\Timezone::isScopeDateInInterval
for this I'm using pdp page (with clean cache)

before fix
image

after fix 
image

**Comment by Den4ik** [comment]
@KrasnoshchokBohdan I mean `+86400` will add 24h to the request date.
> "price_to": "2025-07-18 00:00:00" we get "2025-07-18 23:59:59" and this is ok by my view

After the fix `"price_to": "2025-07-18 00:00:00"` will be `"price_to": "2025-07-19 00:00:00"`

**Comment by KrasnoshchokBohdan** [comment]
> After the fix "price_to": "2025-07-18 00:00:00" will be "price_to": "2025-07-19 00:00:00"
but it was the same before fix 

fix is only cofer 

> your special price will be visible until tomorrow 17
> so instead expire at 2024-09-12 17:00:00 it will expire on 2024-09-13 17:00:00

https://github.com/magento/magento2/issues/39169 from description

{
  "prices": [
    {
      "price": 100,
      "store_id": 0,
      "price_from": "2025-04-08 00:00:00",
      "price_to": "2025-07-18 00:00:00",
      "sku": "test-simple"
    }
  ]
}

no changes
image

after fix
image

sorry it seems I still don't understand the question

**Comment by KrasnoshchokBohdan** [comment]
@Den4ik 

> I haven't checked the source code more deeply, but I don't rule out that somewhere the time value may be thrown off and date become 2025-07-19

maybe you meen - date become 2025-07-17?
because, according to documentations 

https://experienceleague.adobe.com/en/docs/commerce-admin/catalog/products/pricing/product-price-special

> The special price goes into effect immediately after midnight at the beginning of the start date (00:01) and continues until just before midnight (23:59) on the day before the end date.

and I dont see any manipulation with special price date except the method we looking 
\Magento\Catalog\Pricing\Price\SpecialPrice::getValue
image

so maybe I should replace 
```
// fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
            $toTimeStamp += 86400;
```
to 
```
// fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
            $toTimeStamp -= 1;
```

image

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@Den4ik Hi, so should I change ?

```
if ($dateTo && date('H:i:s', strtotime($dateTo)) === '00:00:00') {
    // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
     $toTimeStamp += 86400;
}
```
to 

```
if ($dateTo && date('H:i:s', strtotime($dateTo)) === '00:00:00') {
    // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
     $toTimeStamp += 86399;
}
```

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests

**Comment by Den4ik** [comment]
> @Den4ik Hi, so should I change ?
> 
> ```
> if ($dateTo && date('H:i:s', strtotime($dateTo)) === '00:00:00') {
>     // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
>      $toTimeStamp += 86400;
> }
> ```
> 
> to
> 
> ```
> if ($dateTo && date('H:i:s', strtotime($dateTo)) === '00:00:00') {
>     // fix date YYYY-MM-DD 00:00:00 to YYYY-MM-DD 23:59:59
>      $toTimeStamp += 86399;
> }
> ```

Hi @KrasnoshchokBohdan 
Sorry for delay with response. I believe yes, we should use `86399`

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests B2B

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests B2B,Functional Tests CE

**Comment by engcom-Hotel** [comment]
As you are still working on this PR, we are moving this into `Changes Requested` bucket.

Thanks

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests

**Comment by KrasnoshchokBohdan** [comment]
On my view, failed tests not releted to this pull request (WebAPI and Integration was green before branch merge)

**Review by Den4ik — APPROVED** [review]
@KrasnoshchokBohdan Thanks for update.
Changes looks good for me.
Failed tests looks like unrelated to changes in PR. I'll rerun it to be sure that they are different on each tests execution.

**Review by Den4ik — CHANGES_REQUESTED** [review]
Sorry, @KrasnoshchokBohdan could you please check WebAPI tests, because they are related to updates

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Integration Tests

**Comment by engcom-Charlie** [comment]
HI @KrasnoshchokBohdan,

Thank you for your contribution!

As I can see that, you are working on the review comments and tests failures, also marked the PR as draft hence I am moving it to on Hold status. Please feel free to Open it once you are done with implementation.

**Comment by engcom-Charlie** [comment]
It seems that bot moved it to Review bucket, moving it back to On Hold

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@magento run Functional Tests B2B, Integration Tests, Magento Health Index

**Comment by KrasnoshchokBohdan** [comment]
@Den4ik @engcom-Hotel 
I encountered an issue where tests were breaking in scopes that don’t apply to custom prices, because the method \Magento\Framework\Stdlib\DateTime\Timezone::isScopeDateInInterval is used by several different classes. To address this, I tried another approach that, in my opinion, should only apply to custom prices. I would like to know your opinion on this.

**Comment by engcom-Hotel** [comment]
Hello @KrasnoshchokBohdan,

After reviewing the changes in the PR, it appears to offer a reasonable solution to the described issue by limiting the scope to custom prices and addressing the incorrect handling of the time component in `specialPriceTo`.

However, the duplication of logic (extract the `$specialPriceTo` adjustment logic into a reusable method or utility class) and the absence of automated tests should be addressed to enhance the robustness of the solution.

@Den4ik, looking forward to your thoughts on this.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @KrasnoshchokBohdan,

Is this PR is ready for review?

**Comment by KrasnoshchokBohdan** [comment]
Hello @engcom-Hotel! Thanks for the review and comment. I'll create new service class and unit test for it.

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
Hi @KrasnoshchokBohdan,
Thanks fro update. Please ping when PR will be ready fro review.

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Hotel @Den4ik Hi, please take a look at the latest changes, I look forward to your feedback.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
Hi @KrasnoshchokBohdan 
Thanks for updates.
As I mentioned earlier looks like we will have wrong result if I specify `00:00:00` in the request.
For example, I send request with `price_from: 2025-05-11 00:00:00; price_to: 2025-05-12 00:00:00`
In my opinion, expected result should affect only 1 full day 2025-05-11, but in fact it affect 2 days. On the other hand this logic introduced in https://github.com/magento/magento2/commit/c6856aa94c8f354b32629c0f894a55c708deb3b0 11 years ago starting from first Magento release.
So, I'm ok with the fix for specific time case (for example, `17:00:00`)
Lets wait tests result

File: app/code/Magento/Catalog/Model/Product/Type/Price.php [hunk 2]
```diff
@@ -88,6 +89,11 @@ class Price implements ResetAfterRequestInterface
      */
     private $tierPriceExtensionFactory;
 
+    /**
+     * @var SpecialPriceService|null
+     */
+    protected ?SpecialPriceService $specialPriceService;
```
Comment (Den4ik) [inline app/code/Magento/Catalog/Model/Product/Type/Price.php]: Should be private

File: app/code/Magento/Catalog/Pricing/Price/SpecialPrice.php [hunk 3]
```diff
@@ -21,29 +23,38 @@ class SpecialPrice extends AbstractPrice implements SpecialPriceInterface, BaseP
...
 
     /**
      * @var TimezoneInterface
      */
     protected $localeDate;
 
+    /**
+     * @var SpecialPriceService
+     */
+    protected SpecialPriceService $specialPriceService;
```
Comment (Den4ik) [inline app/code/Magento/Catalog/Pricing/Price/SpecialPrice.php]: Should be private

File: app/code/Magento/Catalog/Service/SpecialPriceService.php [hunk 4]
```diff
@@ -0,0 +1,38 @@
+<?php
+/**
+ * Copyright 2025 Adobe
+ * All Rights Reserved.
+ */
+declare(strict_types=1);
+
+namespace Magento\Catalog\Service;
```
Comment (Den4ik) [inline app/code/Magento/Catalog/Service/SpecialPriceService.php]: namespace `Magento\Catalog\Service` is obsolete. Please move to different namespace to pass static tests

**Review by Den4ik — CHANGES_REQUESTED** [review]
@KrasnoshchokBohdan Please check my comments

**Comment by engcom-Hotel** [comment]
@magento run Database Compare

File: app/code/Magento/Catalog/Model/Product/Type/Price.php (hunk 2 above)
Comment (KrasnoshchokBohdan) [reply app/code/Magento/Catalog/Model/Product/Type/Price.php]: thanks for the comment, I would like to clarify, I use it in the child class \Magento\Bundle\Model\Product\Price so it is not private

Comment (Den4ik) [reply app/code/Magento/Catalog/Model/Product/Type/Price.php]: It will require Core Team approval.
cc @engcom-Hotel

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]
As I mentioned changes looks good for me.
Only one pointt that require attention is failed unit test.
@engcom-Hotel Do we need internal team approval for protected property?

**Review by Den4ik — CHANGES_REQUESTED** [review]
@KrasnoshchokBohdan Could you please check failed unit test

File: app/code/Magento/Catalog/Model/Product/Type/Price.php (hunk 2 above)
Comment (engcom-Hotel) [reply app/code/Magento/Catalog/Model/Product/Type/Price.php]: Hello @Den4ik, 

Thanks for highlighting this point.

Hello @KrasnoshchokBohdan,

Is it possible to make it `private` and if access in subclasses is needed, expose a protected getter as below:

```
protected function getSpecialPriceService(): ?SpecialPriceService
{
    return $this->specialPriceService;
}
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @KrasnoshchokBohdan,

Please refer the review comment below.

Thanks

**Comment by KrasnoshchokBohdan** [comment]
@magento run all tests

**Comment by KrasnoshchokBohdan** [comment]
@Den4ik I can't find this test probably it's only for EE and B2B, sorry
Magento\SalesRuleStaging\Test\Unit\Model\Plugin\DateResolverPluginTest::testBeforeGetFromDate
image

**Comment by Den4ik** [comment]
@magento run Static Tests

**Review by Den4ik — APPROVED** [review]

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @KrasnoshchokBohdan,

Thanks for making the changes. Just one small thing, static test is still failing. Request you to please fix that. Other failures seems flaky to me.

Thanks

**Comment by KrasnoshchokBohdan** [comment]
@magento run Database Compare, Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, Magento Health Index, Sample Data Tests B2B, Sample Data Tests CE, Sample Data Tests EE, Semantic Version Checker, Unit Tests, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by KrasnoshchokBohdan** [comment]
@engcom-Hotel Hi, I can't reproduce this issue in my local environment, but according to the screenshot, I assume that the problem is related to changes in \Magento\Catalog\Pricing\Price\SpecialPrice::PRICE_CODE. Therefore, I have rolled back those changes. (I previously changed this constant due to an error in static tests.)

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @KrasnoshchokBohdan,

It seems you have fixed the mentioned issue by @engcom-Bravo, but we can see some static tests are failing. 

Please fix those as well.

Thanks

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Dash** [comment]
The consistent test failures for **Functional B2B** are known Issues and JIRA is raised for them. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39690/8f42d3566719b9958325376679173f3c/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39690/287a336c87e5d0b284d3f8d478a1f240/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

**Known Issues:**
OrderWithMultipleConfigurableProductsAdditionalStockTest : [ACQE-8060](https://jira.corp.adobe.com/browse/ACQE-8060)
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)
StoreFrontSimpleProductWithSpecialAndTierDiscountPriceTest : [ACQE-7971](https://jira.corp.adobe.com/browse/ACQE-7971)

The consistent test failure for **Functional CE** is known Issues and JIRA is raised for the same. Other failures are inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39690/e517e2b946161599488a7d675914bbf4/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39690/b6ec0d558b51716982ef4f365b19bb1c/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

**Known Issues:**
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

The consistent test failure for **Functional EE** is known Issues and JIRA is raised for the same. Other failure is inconsistent and seems to be flaky. They neither part of PR nor failing because of the PR changes.

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39690/3049098b7d976dbc2eb8751f3e56e025/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39690/7de1f6d980021ed16813b17760fb9d7d/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

**Known Issues:**
EnablePaypalExpressCheckoutAndSubmitAnOrderUsingPaypalExpressCheckoutTest : [ACQE-8007](https://jira.corp.adobe.com/browse/ACQE-8007)

hence moving this PR in Merge In Progress
