### PR TITLE
Correctly handle order clause for reserved columns

### LINKED ISSUE #196: Sort by group results in Zend_Db_Statement_Exception
**Describe the bug**
`group` is both a reserved keyword in MariaDB (and probably MySQL 8) and a column name in the extended `cron_schedule` table, causing an exception when the ORM stitches together a query that sorts by `group` in the Cron Job Manager grid.

**To Reproduce**
1. Go to Cron Manager Dashboard grid from Magento admin (System > Tools > Cron Job Manager)
2. Initiate sort by 'Group' column
4. The following error is logged in `var/exception.log`:

```Next Zend_Db_Statement_Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'group ASC LIMIT 20' at line 1, query was: SELECT `main_table`.* FROM `cron_schedule` AS `main_table` ORDER BY group ASC LIMIT 20 in /vendor/magento/framework/DB/Statement/Pdo/Mysql.php```

**Expected behavior**
Grid is able to sort by group field.  Explicitly surrounding the `group` column identifier with tick quotes in the a direct SQL query appears to address this issue.

**Environment**
 - DB: MariaDB 10.4
 - Cron Job Manager Version - 1.15.1
 - Magento Version - 2.4.5-p1
 - PHP Version - 8.1.x

### LINKED ISSUE #37423: [Issue] Correctly handle order clause for reserved columns
This issue is automatically created based on existing pull request: magento/magento2#37387: Correctly handle order clause for reserved columns

---------
### Description

When using a default admin UI component to render a grid, columns in the data source are handled correctly, even when these are named reserved words (like `group`), however when sorting by such a column, an exception is thrown. This pull request resolves this by correctly escaping these reserved words when used in an 'order by' clause.

Error logged to `var/log/exception.log`:

```
[2023-04-17T19:05:44.755740+00:00] main.CRITICAL: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'group ASC
 LIMIT 20' at line 1 in /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:90
Stack trace:
#0 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(90): PDOStatement->execute()
#1 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(106): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}()
#2 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(91): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure))
#3 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#5 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#6 /var/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#7 /var/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#8 /var/www/magento2/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php(95): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#9 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query(Object(Magento\Framework\DB\Select), Array)
#10 /var/www/magento2/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php(1085): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array, 2)
#11 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php(21): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->fetchAll(Object(Magento\Framework\DB\Select), Array)
#12 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(782): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#13 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(677): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#14 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(383): Magento\Framework\Data\Collection\AbstractDb->getData()
#15 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(580): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->getData()
#16 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(365): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#17 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(565): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->loadWithFilter(false, false)
#18 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(356): Magento\Framework\Data\Collection\AbstractDb->load(false, false)
#19 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection.php(333): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->load()
#20 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(518): Magento\Framework\Data\Collection->getItems()
#21 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/DataProvider.php(252): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->getItems()
#22 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/DataProvider.php(286): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->searchResultToOutput(Object(Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor))
#23 /var/www/magento2/app/code/Magento/Ui/Component/Listing.php(38): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->getData()
#24 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Context.php(250): Magento\Ui\Component\Listing->getDataSourceData()
#25 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/ContentType/Json.php(69): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData(Object(Magento\Ui\Component\Listing))
#26 /var/www/magento2/app/code/Magento/Ui/Component/AbstractComponent.php(158): Magento\Framework\View\Element\UiComponent\ContentType\Json->render(Object(Magento\Ui\Component\Listing), 'templates/listi...')
#27 /var/www/magento2/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php(91): Magento\Ui\Component\AbstractComponent->render()
#28 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#29 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('execute', Array)
#30 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/magento2/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(23): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('execute', Array, Array)
#32 /var/www/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#33 /var/www/magento2/app/code/Magento/Backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('dispatch', Array)
#36 /var/www/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(145): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento2/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(41): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#40 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Magento\Framework\App\Request\Http))
#42 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor))
#43 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#45 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#46 /var/www/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#47 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /var/www/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#49 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#50 /var/www/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#51 {main}
```

### Fixed Issues
1. Fixes https://github.com/Ethan3600/magento2-CronjobManager/issues/196

### Manual testing scenarios
1. `composer require ethanyehuda/magento2-cronjobmanager`
1. `bin/magento setup:upgrade`
1. Navigate to the admin -> System -> Tools -> Cron Job Manager
1. Sort the grid by each column in turn
  - With the changes in this pull request applied, sorting by the "Group" column should work as expected. Without these changes, an exception is thrown and an error message is displayed in the admin.

### Questions or comments
I wasn't able to find a suitable list of reserved words in any libraries already listed as dependencies of Magento, nor any easily available that could be trivially included. If there are suggestions for replacing this hard-coded list of reserved words with an externally-maintained list, please let me know.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Description

When using a default admin UI component to render a grid, columns in the data source are handled correctly, even when these are named reserved words (like `group`), however when sorting by such a column, an exception is thrown. This pull request resolves this by correctly escaping these reserved words when used in an 'order by' clause.

Error logged to `var/log/exception.log`:

```
[2023-04-17T19:05:44.755740+00:00] main.CRITICAL: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'group ASC
 LIMIT 20' at line 1 in /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php:90
Stack trace:
#0 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(90): PDOStatement->execute()
#1 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(106): Magento\Framework\DB\Statement\Pdo\Mysql->Magento\Framework\DB\Statement\Pdo\{closure}()
#2 /var/www/magento2/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(91): Magento\Framework\DB\Statement\Pdo\Mysql->tryExecute(Object(Closure))
#3 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Statement.php(313): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#4 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#5 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#6 /var/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(564): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#7 /var/www/magento2/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(634): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT `main_ta...', Array)
#8 /var/www/magento2/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php(95): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#9 /var/www/magento2/vendor/magento/zend-db/library/Zend/Db/Adapter/Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->query(Object(Magento\Framework\DB\Select), Array)
#10 /var/www/magento2/generated/code/Magento/Framework/DB/Adapter/Pdo/Mysql/Interceptor.php(1085): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array, 2)
#11 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/Db/FetchStrategy/Query.php(21): Magento\Framework\DB\Adapter\Pdo\Mysql\Interceptor->fetchAll(Object(Magento\Framework\DB\Select), Array)
#12 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(782): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#13 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(677): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#14 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(383): Magento\Framework\Data\Collection\AbstractDb->getData()
#15 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(580): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->getData()
#16 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(365): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#17 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection/AbstractDb.php(565): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->loadWithFilter(false, false)
#18 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(356): Magento\Framework\Data\Collection\AbstractDb->load(false, false)
#19 /var/www/magento2/lib/internal/Magento/Framework/Data/Collection.php(333): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->load()
#20 /var/www/magento2/generated/code/Magento/Framework/View/Element/UiComponent/DataProvider/SearchResult/Interceptor.php(518): Magento\Framework\Data\Collection->getItems()
#21 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/DataProvider.php(252): Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor->getItems()
#22 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/DataProvider/DataProvider.php(286): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->searchResultToOutput(Object(Magento\Framework\View\Element\UiComponent\DataProvider\SearchResult\Interceptor))
#23 /var/www/magento2/app/code/Magento/Ui/Component/Listing.php(38): Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider->getData()
#24 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Context.php(250): Magento\Ui\Component\Listing->getDataSourceData()
#25 /var/www/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/ContentType/Json.php(69): Magento\Framework\View\Element\UiComponent\Context->getDataSourceData(Object(Magento\Ui\Component\Listing))
#26 /var/www/magento2/app/code/Magento/Ui/Component/AbstractComponent.php(158): Magento\Framework\View\Element\UiComponent\ContentType\Json->render(Object(Magento\Ui\Component\Listing), 'templates/listi...')
#27 /var/www/magento2/app/code/Magento/Ui/Controller/Adminhtml/Index/Render.php(91): Magento\Ui\Component\AbstractComponent->render()
#28 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Ui\Controller\Adminhtml\Index\Render->execute()
#29 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('execute', Array)
#30 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}()
#31 /var/www/magento2/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(23): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('execute', Array, Array)
#32 /var/www/magento2/lib/internal/Magento/Framework/App/Action/Action.php(111): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->execute()
#33 /var/www/magento2/app/code/Magento/Backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#35 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callParent('dispatch', Array)
#36 /var/www/magento2/app/code/Magento/Backend/App/Action/Plugin/Authentication.php(145): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#37 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#38 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /var/www/magento2/generated/code/Magento/Ui/Controller/Adminhtml/Index/Render/Interceptor.php(41): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#40 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(245): Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#41 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(212): Magento\Framework\App\FrontController->getActionResponse(Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor), Object(Magento\Framework\App\Request\Http))
#42 /var/www/magento2/lib/internal/Magento/Framework/App/FrontController.php(147): Magento\Framework\App\FrontController->processRequest(Object(Magento\Framework\App\Request\Http), Object(Magento\Ui\Controller\Adminhtml\Index\Render\Interceptor))
#43 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#44 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#45 /var/www/magento2/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#46 /var/www/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#47 /var/www/magento2/lib/internal/Magento/Framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#48 /var/www/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#49 /var/www/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#50 /var/www/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#51 {main}
```

### Fixed Issues
1. Fixes https://github.com/Ethan3600/magento2-CronjobManager/issues/196

### Manual testing scenarios
1. `composer require ethanyehuda/magento2-cronjobmanager`
1. `bin/magento setup:upgrade`
1. Navigate to the admin -> System -> Tools -> Cron Job Manager
1. Sort the grid by each column in turn
  - With the changes in this pull request applied, sorting by the "Group" column should work as expected. Without these changes, an exception is thrown and an error message is displayed in the admin.

### Questions or comments
I wasn't able to find a suitable list of reserved words in any libraries already listed as dependencies of Magento, nor any easily available that could be trivially included. If there are suggestions for replacing this hard-coded list of reserved words with an externally-maintained list, please let me know.

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37423: Correctly handle order clause for reserved columns

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Data/Collection/AbstractDb.php [hunk 1]
```diff
@@ -505,6 +666,9 @@ protected function _renderOrders()
     {
         if (!$this->_isOrdersRendered) {
             foreach ($this->_orders as $field => $direction) {
+                if (in_array(strtoupper($field), self::SQL_RESERVED_WORDS)) {
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: Hi @fredden,
Since this piece of code will be executed many-many times in Magento, it should be optimized.
To optimize the solution there, we should use `isset`.
https://stackoverflow.com/a/13483548/1839611
https://3v4l.org/Osndt

Also, please cover your changes with some automated test, I believe unit test should be fine there

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/Data/Collection/AbstractDb.php (hunk 1 above)
Comment (fredden) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: Thanks for the suggestion. ~I have changed the `in_array()` call to `isset()` instead.~ I'm investigating how to do this.

~For testing, I could not find an existing unit test for this file. Would you suggest I create a new unit test, or modify another to cover this? (If so, which unit test would you suggest modifying?)~
I have now found `lib/internal/Magento/Framework/Data/Test/Unit/Collection/DbTest.php`.

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: @fredden pay attention that data structure should change as well, the values should be as a keys to array

File: lib/internal/Magento/Framework/Data/Collection/AbstractDb.php [hunk 2]
```diff
@@ -505,8 +666,13 @@ protected function _renderOrders()
     {
         if (!$this->_isOrdersRendered) {
             foreach ($this->_orders as $field => $direction) {
+                if (isset(self::SQL_RESERVED_WORDS[strtoupper($field)])) {
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: Just wonder. Maybe we can escape it in all cases?

Comment (fredden) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: We can't blindly wrap the string in ticks. If it's a qualified column (eg `main_table.column_name`) or a function call then it will break.

File: lib/internal/Magento/Framework/Data/Collection/AbstractDb.php (hunk 1 above)
Comment (fredden) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: @ihor-sviziev, it looks like using `isset()` is significantly slower than `in_array()` in this case. I'm investigating other options to optimise this code.
https://3v4l.org/XUFoA#v8.2.5

Comment (fredden) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: Unfortunately using `isset()` means we need to use a more memory-intensive / expensive data structure for the list of reserved words. So, we're trading memory usage for less time spent per look-up.

**Comment by fredden** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Data/Collection/AbstractDb.php (hunk 1 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: I thought to not use array_flip on each iteration, but implement the well prepared array from the beginning, so that it won't affect performance

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Data/Collection/AbstractDb.php]: Here is an example: https://3v4l.org/hfjpa#v8.2.5
BTW you're absolutely right about a more expensive data structure, but it's too small diff, on 10000 items:
1. store values as array keys https://3v4l.org/Bv9c3#v8.2.5
> 649.9296875KB

2. Store values as values as array values: https://3v4l.org/PpbNW#v8.2.5
> 1029.9296875KB

Since we'll have way less data - it will way smaller diff

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@fredden, could you please fix/ignore static test failures?

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

1. Run `composer require ethanyehuda/magento2-cronjobmanager`
2. Run `bin/magento setup:upgrade`
3. Navigate to the **admin -> System -> Tools -> Cron Job Manager**
4. Sort the grid by each column in turn.

**Before:** :heavy_multiplication_x: Getting sql error in the `exception.log`on sorting "group"
Screenshot 2023-04-24 at 11 15 29 AM

Screenshot 2023-04-24 at 12 18 08 PM

**After:** :heavy_check_mark:  No error recorded in the `exception.log`.Now , able to sort by "Group"
Screenshot 2023-04-24 at 12 15 41 PM


Moving to **Merge in Progress.**

**Comment by engcom-Lima** [comment]
@magento create issue
