### PR TITLE
Email may not be sent if Magento has enabled asynchronous email sending on multiple websites.

### LINKED ISSUE #31950: Email may not be sent if Magento has enabled asynchronous email sending on multiple websites
### Preconditions (*)

1. Magento 2.4-develop;
1. Magento Open Source 2.4.0-p1  without sample data is installed;
2. There are two websites, each with one Store View;

### Steps to reproduce (*)

For convenience, I define two websites as follows:

A: Default Website
B: non-Default Website

1. Set "Stores > Configuration > Sales > Sales Emails > General Settings > Ansynchronous sending" to "**Enable**".
2. On A, set "Stores > Configuration > Sales > Sales Emails > Order > Enabled" to "**No**".
3. On B, set "Stores > Configuration > Sales > Sales Emails > Order > Enabled" to "**Yes**".
4. Complete the order on B.

### Expected result (*)

1. Order confirmation email is sent.

### Actual result (*)

1. Order confirmation email is **not** sent.

### Additional Information

* If asynchronous email sending is disabled, no problem.
* Invoice, Shipment, and Credit Memo emails have similar issues. However, Order Comments, Invoice Comments, Shipment Comments, Credit Memo Commets emails are sent successfully.
* If place an order through the storefront then messages are sent

### PR DESCRIPTION
**Pull request by engcom-Kilo**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/magento2/issues/31950

### Manual testing scenarios (*)

1. see https://github.com/magento/magento2/issues/31950

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php [hunk 1]
```diff
@@ -100,12 +100,11 @@ public function __construct(
      */
     public function send(Creditmemo $creditmemo, $forceSyncMode = false)
     {
+        $this->identityContainer->setStore($creditmemo->getStore());
```
Comment (ihor-sviziev) [inline app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php:103]: It feels more like a workaround as it's changing the shared object that was injected through DI. Right?

Could you provide info on where it used? Can we create a new identity container using the factory, set the correct store, and pass it further where it used?

Comment (engcom-Kilo) [reply app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php:103]: @ihor-sviziev 
It's not injected via di, CreditemmoSender extends from abstract Sender which has dependency on identity interface. Here we use creditmemo identity container implementation for this interface. As far as I found, the creditmemo identity container not used in other places.
As you may see, such workaround has been used from the beginning(and it's true for almost all senders, including abstract one), set store just been called to late which led to issues.
Yes, it'll be more cleaner to create creditmemo identity container via factory, but we already have coupling between objects to high for this sender and adding new dependency will make it even worse.

Comment (ihor-sviziev) [reply app/code/Magento/Sales/Model/Order/Email/Sender/CreditmemoSender.php:103]: Ok. I see there used `shared="false"` in order to prevent state changing. Let's keep it as is for now.

https://github.com/magento/magento2/blob/91aaeec6b2ea79f364b5614ac931972d00c085b0/app/code/Magento/Sales/etc/di.xml#L334

Note: seems like it used only here https://github.com/magento/magento2/blob/c4570d2efd58e4a2dd062994450c1e3decddd1b0/app/code/Magento/Sales/Model/Order/Email/Sender.php#L144-L150

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8807](https://jira.corp.magento.com/browse/ENGCOM-8807) has been created to process this Pull Request
:eight_spoked_asterisk: @ihor-sviziev, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by zakdma — APPROVED** [review]

**Comment by dmitriyprime** [comment]
@magento I am working on this

**Comment by dmitriyprime** [comment]
:heavy_check_mark:  QA passed
If asynchronous email sending is enabled on site B where "Stores > Configuration > Sales > Sales Emails > Order > Enabled" setting is set to "Yes" orders, invoices, shipments and credit memos email sending works as expected.

**Before:** 
before

**After:**
after

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32239`.
