### PR TITLE
GraphQL CORS Headers

### LINKED ISSUE #28561: GraphQL : CORS requests will fail without OPTIONS reponse
As a web developer, I want Magento to support the [CORS standard](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access*control*CORS) so that I can develop my applications according to defined best practices.

—
Original issue: https://github.com/magento/magento2/issues/8399

AC
* Implement CORS support as detailed here: https://enable-cors.org/server.html

### PR DESCRIPTION
**Pull request by michalderlatka**
### Description (*)
As a web developer, I want Magento to support the CORS standard so that I can develop my applications according to defined best practices.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#28561

### Manual testing scenarios (*)
1. go to admin > stores > configuration > services > graphql
2. enable CORS headers
3. Fill fields with data
4. save and clean cache
5. run graphQL query and confirm headers are added

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lenaorobei** [comment]
@magento run all tests

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/AbstractCorsHeaderProvider.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+
+namespace Magento\GraphQl\Controller\HttpResponse\Cors;
+
+
+use Magento\Framework\App\Response\HeaderProvider\AbstractHeaderProvider;
+use Magento\GraphQl\Model\Cors\ConfigurationInterface;
+
+class AbstractCorsHeaderProvider extends AbstractHeaderProvider
+{
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/AbstractCorsHeaderProvider.php]: can we not use inheritance here?

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+namespace Magento\GraphQl\Controller\HttpResponse\Cors;
+
+use Magento\Framework\App\Response\HeaderProvider\HeaderProviderInterface;
+use Magento\GraphQl\Model\Cors\ConfigurationInterface;
+
+class CorsAllowHeadersHeaderProvider implements HeaderProviderInterface
+{
+    protected $headerName = 'Access-Control-Allow-Headers';
+
+    protected $headerValue = '';
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php]: We should never use protected, but private, since we're not using inheritance now
goes for all the other classes

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php [hunk 3]
```diff
@@ -0,0 +1,43 @@
+<?php
+
+
+namespace Magento\GraphQl\Controller\HttpResponse\Cors;
+
+use Magento\Framework\App\Response\HeaderProvider\HeaderProviderInterface;
+use Magento\GraphQl\Model\Cors\ConfigurationInterface;
+
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php:12]: all classes need at least one short description (a good one)

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php [hunk 4]
```diff
@@ -0,0 +1,43 @@
+<?php
+
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php]: add copyright and strict declaration

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowMethodsHeaderProvider.php [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+
+use Magento\Framework\App\Response\HeaderProvider\HeaderProviderInterface;
+use Magento\GraphQl\Model\Cors\ConfigurationInterface;
+
+class CorsAllowMethodsHeaderProvider implements HeaderProviderInterface
+{
+    protected $headerName = 'Access-Control-Allow-Methods';
+
+    protected $headerValue = 'GET,POST,OPTIONS';
+
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowMethodsHeaderProvider.php:22]: if this value doesn't change it's best to use static private.
But, I would even use an array, and when used in method do implode(,)
also merge it with some values in the constructor so we can make it extensible

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsMaxAgeHeaderProvider.php [hunk 6]
```diff
@@ -0,0 +1,44 @@
...
+
+
+use Magento\Framework\App\Response\HeaderProvider\HeaderProviderInterface;
+use Magento\GraphQl\Model\Cors\ConfigurationInterface;
+
+class CorsMaxAgeHeaderProvider implements HeaderProviderInterface
+{
+    protected $headerName = 'Access-Control-Max-Age';
+
+    protected $headerValue = '86400';
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsMaxAgeHeaderProvider.php]: same as above

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowCredentialsHeaderProvider.php [hunk 7]
```diff
@@ -0,0 +1,38 @@
+<?php
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowCredentialsHeaderProvider.php:1]: code needs a small integration test

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php [hunk 8]
```diff
@@ -0,0 +1,49 @@
...
+    private $corsConfiguration;
+
+    public function __construct(
+        ConfigurationInterface $corsConfiguration,
+        string $headerName
+    ) {
+        $this->corsConfiguration = $corsConfiguration;
+        $this->headerName = $headerName;
+    }
+
```
Comment (cpartica) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowHeadersHeaderProvider.php:41]: also all methods need a description.
If not these things will trigger a static test failure

**Review by cpartica — CHANGES_REQUESTED** [review]
just a few "static failures" that need addressing, 
you'll see them in the builds that I just just ran https://github.com/magento/magento2/pull/28713/checks?check_run_id=797040005

**Comment by cpartica** [comment]
run all tests

**Comment by cpartica** [comment]
@magento run all tests

**Comment by michalderlatka** [comment]
@magento run all tests

**Comment by michalderlatka** [comment]
@magento run all tests

**Review by cpartica — DISMISSED** [review]

File: app/code/Magento/GraphQl/Model/Cors/ConfigurationInterface.php [hunk 9]
```diff
@@ -0,0 +1,56 @@
...
+ * Interface for configuration provider for GraphQL CORS settings
+ */
+interface ConfigurationInterface
+{
+    /**
+     * Are CORS headers enabled
+     *
+     * @return bool
+     */
+    public function isEnabled() : bool;
```
Comment (YevSent) [inline app/code/Magento/GraphQl/Model/Cors/ConfigurationInterface.php]: Redundant space after `)` and before `:`.

File: app/code/Magento/GraphQl/Model/Cors/Configuration.php [hunk 10]
```diff
@@ -0,0 +1,96 @@
...
+namespace Magento\GraphQl\Model\Cors;
+
+use Magento\Framework\App\Config\ScopeConfigInterface;
+
+/**
+ * Configuration provider for GraphQL CORS settings
+ */
+class Configuration implements ConfigurationInterface
+{
+    const XML_PATH_CORS_HEADERS_ENABLED = 'graphql/cors/enabled';
```
Comment (YevSent) [inline app/code/Magento/GraphQl/Model/Cors/Configuration.php]: Constants should have visibility scope.

File: app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowMethodsHeaderProvider.php [hunk 11]
```diff
@@ -0,0 +1,68 @@
...
+        $this->corsConfiguration = $corsConfiguration;
+        $this->headerName = $headerName;
+    }
+
+    /**
+     * Get name of header
+     *
+     * @return string
+     */
+    public function getName()
```
Comment (YevSent) [inline app/code/Magento/GraphQl/Controller/HttpResponse/Cors/CorsAllowMethodsHeaderProvider.php]: The method return type is missed.

File: app/code/Magento/GraphQl/etc/di.xml [hunk 12]
```diff
@@ -98,4 +98,31 @@
             <argument name="queryComplexity" xsi:type="number">300</argument>
         </arguments>
     </type>
+
+    <preference for="Magento\GraphQl\Model\Cors\ConfigurationInterface" type="Magento\GraphQl\Model\Cors\Configuration" />
+    <type name="\Magento\GraphQl\Controller\HttpResponse\Cors\CorsMaxAgeHeaderProvider">
```
Comment (YevSent) [inline app/code/Magento/GraphQl/etc/di.xml]: Redundant `\` in FQCN.

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php [hunk 13]
```diff
@@ -0,0 +1,126 @@
...
+        $objectManager = ObjectManager::getInstance();
+
+        $this->resourceConfig = $objectManager->get(Config::class);
+        $this->reinitConfig = $objectManager->get(ReinitableConfigInterface::class);
+        $this->scopeConfig = $objectManager->get(ScopeConfigInterface::class);
+    }
+
+    protected function tearDown(): void
+    {
+        parent::tearDown(); // TODO: Change the autogenerated stub
```
Comment (YevSent) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php]: `@TODO` annotations should be removed from code.

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php [hunk 14]
```diff
@@ -0,0 +1,126 @@
...
+        $headers = $this->getHeadersFromIntrospectionQuery();
+
+        self::assertArrayNotHasKey('Access-Control-Max-Age', $headers);
+        self::assertArrayNotHasKey('Access-Control-Allow-Credentials', $headers);
+        self::assertArrayNotHasKey('Access-Control-Allow-Headers', $headers);
+        self::assertArrayNotHasKey('Access-Control-Allow-Methods', $headers);
+        self::assertArrayNotHasKey('Access-Control-Allow-Origin', $headers);
+    }
+
+    private function getHeadersFromIntrospectionQuery()
```
Comment (YevSent) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php]: The method return type is missed.

Comment (cpartica) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php]: we don't usually do it on tests, but since we upgraded phpunit we might have to

**Review by cpartica — CHANGES_REQUESTED** [review]

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php (hunk 14 above)
Comment (YevSent) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/CorsHeadersTest.php]: It doesn't matter if a method is a test class method or a regular code. All code should follow the same semantic, the only exception is doc blocks, they can be omitted for test methods.

**Comment by michalderlatka** [comment]
@magento run all tests

**Review by cpartica — APPROVED** [review]
