### PR TITLE
Fix used in entities of the same type are displayed separately in delete warning

### LINKED ISSUE #1749: Used in entities of the same type are displayed separately in delete warning
### Steps to reproduce (*)
1. Add an image from media gallery to a category
2. Add another image from media gallery to a category
3. Try to delete both images together from the media gallery
4. See the delete confirmation popup

### Expected result (*)
Counts of asset usages should be aggregated by entity type: `Categories(2)` - only one `Categories` item should be displayed in the warning message

### Actual result (*)
image

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes magento/adobe-stock-integration#1749

### Manual testing scenarios (*)
1. Add an image from media gallery to a category
2. Add another image from media gallery to a category
3. Try to delete both images together from the media gallery
4. See the delete confirmation popup

**Counts of asset usages should be aggregated by entity type: `Categories(2)` - only one `Categories` item should be displayed in the warning message**

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

File: app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js [hunk 1]
```diff
@@ -68,7 +70,26 @@ define([
...
+         * @return {String}
+         */
+        usedInObjectToString: function (usedIn) {
+            var message = '',
+                count = 0;
+
+            $.each(usedIn, function (entityName, number) {
+                count++;
+                message += entityName + '(' + number + ')';
+                message += count !== Object.keys(usedIn).length ?  ', ' : '.';
```
Comment (sivaschenko) [inline app/code/Magento/MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js]: I think it would be better readable if the object will be converted to an array and then rendered using `.join(', ') + '.'`

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @Nazar65 ! Please take a look at my comment

**Comment by sivaschenko** [comment]
Main affected functionality is covered by MFTF tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8004](https://jira.corp.magento.com/browse/ENGCOM-8004) has been created to process this Pull Request

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

Counts of asset usages is aggregated by entity type
Screenshot_84
