### PR TITLE
bug-fix #16074 - Fix theme change in middle of product page.

### LINKED ISSUE #16074: User agent exception not setting the correct templates for product pages.
### Preconditions
1. Magento 2.2.4
2. PHP 7.1.17
3. Redis 3.2.11
4. Mysql Ver 14.14 Distrib 5.6.39-83.1

### Steps to reproduce
1. Create a parent theme  ex: `parent` (extending or not the blank theme)
2. Create a child theme of `parent` for the desktop version ex: `desktop`
3. Create another child theme of `parent` for mobile devices ex: `mobile`
4. In all themes, create the `Magento_Theme/templates/html/footer.phtml` file with different content.
5. In the Admin section `Content -> Design -> Configuration` edit the _Global Scope_ and set the `desktop` theme as default. Click **Add New User Agent Rule** button and add an exception for `/(iPhone|iPod|iPad|Android)/i` to use the `mobile` theme.
6. In a browser visit the site with "Responsive Design Mode" enabled and change the user agent to one one of the above. **Note** that the categories pages, listings and CMS pages are working fine.
7. Visit a product page. **Note** that the `desktop` footer is loading regardless of the user agent.

### Expected result
What I find strange is that some templates are loading fine. For instance the header.phtml header will load proper one form the `mobile` theme based on the user agent but not the `footer.phtml` or the `absolute_footer.phtml`. 

### Actual result
1. The `footer.phtml` and `absolute_footer.phtml` templates are loading from the `desktop` theme instead of the `mobile` theme regardless of the user agent.

###Notes
For me, this has broken after upgrading to 2.2.4, on 2.1.10 it was working fine and it was loading the proper templates based on the user agent.

### PR DESCRIPTION
**Pull request by drew7721**
### Description (*)
When setting a design exception by user agent for front end, the exception works on all pages except the product page. This was caused by one of the blocks (product_viewed_counter) making a call that would reset the current theme design to the default theme when collecting product data.
See details on how to reproduce in issue #16074 .

The fix does not create any issues and all test continue to pass. There is no need to set the global theme to the default one at that point in the execution.

**Solution**: remove faulty line.

### Fixed Issues (if relevant)
1. magento/magento2#16074 User agent exception not setting the correct templates for product pages.
2. magento/magento2#14932  Invalid Template with Custom Theme Applied by User Agent
3. magento/magento2#7503 Category design / theme update not inheriting correctly on product pages
4. magento/magento2#7710 Custom theme doesn't apply XML layout updates when applied to a product
5. magento/magento2#8333 Use Design to get theme, because theme is changed after constr…

### Manual testing scenarios (*)
1. Set a different theme for iPhone user agent and the changes worked for the whole product page, including the footer.
2. Ran all tests. Including the one for the class containing the changes. Passed.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-engcom-team** [comment]
Hi @drew7721. Thank you for your contribution 
Here is some useful tips how you can test your changes using Magento test environment.
Add the comment under your pull request to deploy test or vanilla Magento instance:
- `@magento-engcom-team give me test instance` - deploy test instance based on PR changes
- `@magento-engcom-team give me 2.3-develop instance` - deploy vanilla Magento instance

For more details, please, review the [Magento Contributor Assistant](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#contributor-assist) documentation

**Comment by drew7721** [comment]
@magento-engcom-team give me test instance

**Comment by magento-engcom-team** [comment]
Hi @drew7721. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @drew7721, here is your [new Magento instance](http://34.228.235.121/pr-19124/).
Admin access: [http://34.228.235.121/pr-19124//admin](http://34.228.235.121/pr-19124//admin)
Login: `admin` Password: `123123q`

File: app/code/Magento/Catalog/Ui/DataProvider/Product/Listing/Collector/Image.php [hunk 1]
```diff
@@ -136,7 +136,6 @@ public function collect(ProductInterface $product, ProductRenderInterface $produ
     public function emulateImageCreating(ProductInterface $product, $imageCode, $storeId, ImageInterface $image)
     {
         $this->storeManager->setCurrentStore($storeId);
-        $this->design->setDefaultDesignTheme();
```
Comment (slavvka) [inline app/code/Magento/Catalog/Ui/DataProvider/Product/Listing/Collector/Image.php]: I assume that setting the default theme here was made intentionally. Thus after you change this will change the behavior. Maybe it makes sense to move setting the default theme to `collect` method and then restore the original  theme after that?

Comment (drew7721) [reply app/code/Magento/Catalog/Ui/DataProvider/Product/Listing/Collector/Image.php]: @slavvka yes, I agree. I've been trying to wrap my head around why there is a need change the current theme to the default one since the default one will be set anyhow. But I guess to maintain functionality it's best to fix this more defensively. I'll push the updated changes as per your suggestion.

**Comment by slavvka** [comment]
Could you consider covering the changed functionality with an automated test (preferably integration)?

**Comment by drew7721** [comment]
> Could you consider covering the changed functionality with an automated test (preferably integration)?

There is a Unit test written for that class.. They both pass. `Magento\Catalog\Test\Unit\Ui\DataProvider\Product\Listing\Collector\ImageTest`

**Comment by drew7721** [comment]
I guess when @sereban wrote that, he either did not think of the impact changing the theme would have on the rest of the blocks or he just assumed it will only be used trough async calls once the page is loaded. Either way, maybe he can enlighten us on his decision and why setting the theme to the default one is needed at that point, though it seems he has not been that active lately.

Regardless, it's obvious it has an undesired impact on the following blocks that will be rendered on the product page. IMO the image creation should be emulated in the current theme and not the default one and that line should simply be removed, but as per your suggestion @slavvka I think it satisfies all functionality.

**Comment by orlangur** [comment]
@drew7721,

> This was caused by one of the blocks (product_viewed_counter) making a call that would reset the current theme design to the default theme when collecting product data

Why the fix is not about fixing such block then but rather set theme in another class?

> Ran all tests. Including the one for the class containing the changes. Passed.

This is bad actually. It means that there is no test currently covering broken scenario.

**Comment by drew7721** [comment]
@orlangur ,
> 
> > This was caused by one of the blocks (product_viewed_counter) making a call that would reset the current theme design to the default theme when collecting product data
> 
> Why the fix is not about fixing such block then but rather set theme in another class?

It is true that [this block](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Block/Ui/ProductViewCounter.php#L132) does call the data provider(collector) to gather all the data. I don't think the issue lies in the block, but rather in the provider. Blocks should be able to call data providers without fearing that the global theme will be changed.

IMO fixing this in the block is like adding fresh paint over a rotten wall, it will cover it for now but further down the line the issue might/will happen again. I think that fixing the issue at the core is the best approach and will also avoid future issues.

> > Ran all tests. Including the one for the class containing the changes. Passed.
> 
> This is bad actually. It means that there is no test currently covering broken scenario.

I agree, but that should be a different issue, as this PR focuses on fixing the issue at hand, that the front end is broken. That being the main issue that this PR fixes. In my opinion a new issue/PR should be made for the missing tests.

**Comment by drew7721** [comment]
Also, on another note, this issue is relevant to 2.2.* as well so I'm  thinking that I should have done this PR against the 2.2-develop branch instead. Let me know if that would be better.

**Comment by drew7721** [comment]
@slavvka, thank you for the updates.

**Comment by slavvka** [comment]
> Also, on another note, this issue is relevant to 2.2.* as well so I'm thinking that I should have done this PR against the 2.2-develop branch instead. Let me know if that would be better.

No, that's okay. We want to have all fixes in 2.3 and then in 2.2

**Comment by orlangur** [comment]
@drew7721,

>  Blocks should be able to call data providers without fearing that the global theme will be changed.

So, where global theme is actually changed and why we cannot fix it?

> a new issue/PR should be made for the missing tests.

This never works. Automated tests are always to be delivered together with corresponding changes, that's the point. But first we should understand where is the correct place for the fix (probably you and Slava already understand this completely and I'm the only one unaware :)).

**Comment by drew7721** [comment]
@orlangur 😆 np, let me enlighten you. 

Issue resides [here](https://github.com/magento/magento2/blob/2.3-develop/app/code/Magento/Catalog/Ui/DataProvider/Product/Listing/Collector/Image.php#L139). See how it sets the default theme? That's a big No No! because we don't know where or when the call to that collector might be placed. So this might randomly change the theme.

Deleting the line might have done the job since the default theme will be used anyhow, but just to make sure it does not break any other functionality on any other branches out there, I agree with @slavvka that the current approach is best : storing the current theme in a var and setting it back when done.

❓ By the way, I really don't see why a "counter" needs that much information about the product. One might think that the `entity_id` and a `$count++` would be enough 🤣

**Comment by magento-engcom-team** [comment]
Hi @drew7721. Thank you for your contribution. 
We will aim to release these changes as part of 2.3.1. 
Please check the release notes for final confirmation.

**Comment by Ctucker9233** [comment]
@magento-engcom-team I'll create a backport for 2.2
