### PR TITLE
Replaced PHP8-only str_contains method.

### LINKED ISSUE #33680: Unsupported PHP 8 command in Magento
### Preconditions (*)

 
1. Magento 2.4.3 EE
1. PHP 7.4

### Steps to reproduce (*)
1. There is a PHP 8 (str_contains) command in \Magento\Framework\Filesystem\Directory\DenyListPathValidator:74 which is not officially supported yet ... so we have such errors during installation:

{{PHP Fatal error: Uncaught Error: Call to undefined function Magento\Framework\Filesystem\Directory\str_contains() in <...>/magento/vendor/magento/framework/Filesystem/Directory/DenyListPathValidator.php:74

This file (DenyListPathValidator) is initialized in \Magento\Framework\Filesystem\Directory\WriteFactory.php which may affect not only the above case

Expected result (*)

PHP 7 command, instead of PHP 8

Actual result (*)

PHP 8 command

### LINKED ISSUE #33755: Magento 2.4.2 to 2.4.3 Upgrade Issue use php 8 function
### Preconditions (*)

1. Try to upgrade from version 2.4.2-p1 to 2.4.3
2. MSI modules are disabled using a replace on composer.

### Steps to reproduce (*)
1. execute: composer require magento/product-community-edition=2.4.3 --no-update
3. execute : composer update

### Expected result (*)

1. Magento was updated to version 2.4.3

### Actual result (*)

1. Has got an error : 
`Fatal error: Uncaught Error: Call to undefined function Magento\Framework\Filesystem\Directory\str_contains() in /var/www/html/vendor/magento/framework/Filesystem/Directory/DenyListPathValidator.php:74
`
 Class \Magento\Framework\Filesystem\Directory\DenyListPathValidator use a PHP 8.0 function. (str_contains)

```
....
foreach ($this->fileDenyList as $file) {
            $baseName = pathinfo($actualPath, PATHINFO_BASENAME);
            if (str_contains($baseName, $file) || preg_match('#' . "\." . $file . '#', $fullPath)) {
                throw new ValidatorException(
                    new Phrase('"%1" is not a valid file path', [$path])
                );
            }
        }
```
### Notes
Based on requirement this version should work on PHP 7.4
https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html

And in the release note (https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html) you wrote:
Magento 2.4.3 is not yet compatible with PHP 8.x, but the following platform upgrades bring us closer to future compatibility with  PHP 8.x.

### LINKED ISSUE #33945: Error with PHP 8 str_contains function when upgrade to 2.4.3
### Preconditions (*)
1. Magento current version: enterprise 2.4.1-p1
2. Use PHP 7.4
3. Disable MSI modules

### Steps to reproduce (*)
1.Run composer command: `composer require magento/product-enterprise-edition=2.4.3 --no-update`
2.Run composer update command: `composer update`

### Expected result (*)
1. Upgrade to Magento EE 2.4.3 successfully

### Actual result (*)
1. An error exception appear
`Fatal error: Uncaught Error: Call to undefined function Magento\Framework\Filesystem\Directory\str_contains() in vendor/magento/framework/Filesystem/Directory/DenyListPathValidator.php:74`
image

### PR DESCRIPTION
**Pull request by reense**
### Description (*)
This PR removes the PHP8-only method str_contains and replaces it with the traditional stripos() check with false, which is available since PHP5.

The reason for using this older method are the Magento 2.4 system requirements: Magento 2.4 supports PHP7.4 which does not contain the str_contains method [source](https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html). The latest version of Magento, 2.4.3, does not even support PHP 8 [source](https://devdocs.magento.com/guides/v2.4/release-notes/open-source-2-4-3.html).

This issue has to be fixed, since it breaks upgrading a Magento instance on PHP 7.4. (see Manual error-reproducing scenario)

### Fixed Issues (if relevant)

1. Fixes magento/magento2#33680
2. Fixes https://github.com/magento/magento2/issues/33755
3. Fixes https://github.com/magento/magento2/issues/33945
### Manual error-reproducing scenario
1. Create a Magento installation on any version lower than 2.4.3.
2. Use PHP 7.4.
3. Run `composer require magento/product-community-edition=2.4.3 --no-update`
4. Run `composer update`
5. The update fails; saying `call to undefined method str_contains().`

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by bgorski — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @bgorski, thank you for the review.
[ENGCOM-9192](https://jira.corp.magento.com/browse/ENGCOM-9192) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@reense thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by bgorski** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php [hunk 1]
```diff
@@ -71,7 +71,7 @@ public function validate(
 
         foreach ($this->fileDenyList as $file) {
             $baseName = pathinfo($actualPath, PATHINFO_BASENAME);
-            if (str_contains($baseName, $file) || preg_match('#' . "\." . $file . '#', $fullPath)) {
+            if (stripos($baseName, $file) !== false || preg_match('#' . "\." . $file . '#', $fullPath)) {
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php]: As we already have the `symfony/polyfill-php80` in composer.lock file, I think it's better to add the `symfony/polyfill-php80` as a requirement to composer.json and use a new function.
https://github.com/magento/magento2/blob/9ae286d8a747f40fa0c89944f4aafc5cf4a5e9bb/composer.lock#L6645-L6727

If you still believe it should replaced with old function - please replace it with the equivalent:
`'' === $needle || false !== strpos($haystack, $needle);`
https://github.com/symfony/polyfill-php80/blob/1100343ed1a92e3a38f9ae122fc0eb21602547be/Php80.php#L93

PS: Currently, there is adding PHP 8 support in progress

Comment (reense) [reply lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php]: @ihor-sviziev  I have updated this pull request to reflect your suggestions.
I get that you guys are making progress on creating PHP 8.0 support! however, for now, PHP7.4 is still supported so I think using a function that is not in every PHP release is not a very good idea (for the time being).

File: lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php [hunk 2]
```diff
@@ -71,7 +71,7 @@ public function validate(
 
         foreach ($this->fileDenyList as $file) {
             $baseName = pathinfo($actualPath, PATHINFO_BASENAME);
-            if (str_contains($baseName, $file) || preg_match('#' . "\." . $file . '#', $fullPath)) {
+            if ('' === $needle || false !== strpos($haystack, $needle) || preg_match('#' . "\." . $file . '#', $fullPath)) {
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php]:
```suggestion
            if ('' === $file || false !== strpos($baseName, $file) || preg_match('#' . "\." . $file . '#', $fullPath)) {
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php [hunk 3]
```diff
@@ -71,7 +71,7 @@ public function validate(
 
         foreach ($this->fileDenyList as $file) {
             $baseName = pathinfo($actualPath, PATHINFO_BASENAME);
-            if (str_contains($baseName, $file) || preg_match('#' . "\." . $file . '#', $fullPath)) {
```
Comment (reense) [inline lib/internal/Magento/Framework/Filesystem/Directory/DenyListPathValidator.php:74]: @ihor-sviziev welp.. sorry I was (apparently) not paying enough attention when performing this change.

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
✖️ QA Failed

Hello @reense,

Thanks for the contribution!

I have tried to reproduce the issue but was unable to do so. I have tried the below steps in order to reproduce the issue:
1. Install Magento 2.4.2-P1 
2. Run command `composer require magento/product-community-edition=2.4.3 --no-update`
3. And then `composer update`
4. I have PHP 7.4 version installed in my system. Please refer the below screenshot for reference:
Screenshot 2021-08-31 at 6 16 52 PM

After following the above steps, the `composer update` command is running successfully. It might be because `symfony/polyfill-php80` library is already installed. It has the `str_contains` method in the bootstrap.php file.

Please let us know any further steps in order to reproduce the issue.

Thanks

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Unable to reproduce the issue. Please follow my comments on this [link](https://github.com/magento/magento2/pull/33886#issuecomment-909207080).

**Comment by nbennett25** [comment]
@engcom-Hotel I am able to reproduce the error with 2.4.2-p2, but was able to apply patch AC-384__Fix_Incompatible_PHP_Method__2.4.3_ce with success.

**Comment by ihor-sviziev** [comment]
@engcom-Hotel, There is the official hotfix for this issue
https://support.magento.com/hc/en-us/articles/4408021533069-Adobe-Commerce-upgrade-2-4-3-2-3-7-p1-PHP-Fatal-error-Hotfix

so you can check internal docs maybe of how to reproduce it.

**Comment by ihor-sviziev** [comment]
I just updated the PR to be equal to the official hotfix described here:
https://support.magento.com/hc/en-us/articles/4408021533069-Adobe-Commerce-upgrade-2-4-3-2-3-7-p1-PHP-Fatal-error-Hotfix
@magento run all tests

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9192](https://jira.corp.magento.com/browse/ENGCOM-9192) has been created to process this Pull Request

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9192](https://jira.corp.magento.com/browse/ENGCOM-9192) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
I tried to reproduce the issue using 2.4-develop and could not reproduce at all!
There is a way I found out to check the _str_contains()_ function compatibility
1. Disabled the str_contains() if statement block completely from the _bootstrap.php_ class, then executed the upgrade command.
 2. Definitely we get the error as defined in this PR report.
 Well, updated PR code changes will help in resolving the issue as well where we have to reset the  _bootstrap.php_ class changes before the re execution!
@ihor-sviziev @reense @engcom-Hotel

**Comment by engcom-Alfa** [comment]
@magento give me test instance
