### PR TITLE
Fix duplicate css when enable critical path

### LINKED ISSUE #26498: CSS shows up twice when Critical CSS Enabled
### Preconditions (*)

1. 2.3.4
2.

### Steps to reproduce (*)

1. Enable `use_css_critical_path`

### Expected result (*)

1. The stylesheets are only loaded once

### Actual result (*)

1. `styles-m.css`, `styles-l.css` and `print.css` styles show up multiple times in developer tools.

I have traced the problem to the following method:
`beforeSendResponse` in `module-theme/Controller/Result/AsyncCssPlugin.php`

This line appears to be re-inserting the original style tags:

```
$content = str_replace('</body', implode("\n", $cssMatches) . "\n</body", $content);
```

If you comment out this line, the HTML is as expected, with each style element existing only once and preventing double download of stylesheets.

I think there's some confusion over the implementation of the following technique:

```
<link rel="preload" as="style" media="all" onload="this.onload=null;this.rel='stylesheet'"href="...en_US/css/styles-m.css">
```

I would expect that the purpose of the onload method is that rather than needing one `<link>` to preload and a separate `<link>` at the bottom of the HTML to then achieve the affect of asynchronously loading the CSS, this behaviour can be achieved with just one `<link>` element. After `onload` event has fired, the `rel` attribute swaps and applies the CSS.

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

This PR continue great works https://github.com/magento/magento2/pull/27211 by @krzksz in latest codebase
This PR aim to bring patch fix issue css show twice. Before the fix magento place redundant link style at bottom of page before body close end

### Fixed Issues (if relevant)

1. Fixes magento/magento2#26498

### Manual testing scenarios (*)

1. Enable critical path css
2. Run deploy static content + clean cache
3. Go to homepage inspect in browser element "page-wrapper"
4. We will see 2 file styles-l.css have style apply for that element
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all test

@mrtuvn does this PR replace https://github.com/magento/magento2/pull/27211 or what is the purpose of it?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@ihor-sviziev just continue works by @krzksz after long inactive

**Comment by mrtuvn** [comment]
@magento run all tests

File: app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php [hunk 1]
```diff
@@ -32,48 +35,94 @@ public function __construct(ScopeConfigInterface $scopeConfig)
...
-                    );
-
-                    return $loadCssAsync;
-                },
-                $content
-            );
+        $content = (string)$httpResponse->getContent();
+        $headCloseTag = '</head>';
+
+        $headEndTagFound = strrpos($content, $headCloseTag) !== false;
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php]: From my experience `<body>` tag usually is much bigger than `<head>`, so I suggest to use `strpos` function instead
```suggestion
        $headEndTagFound = strpos($content, $headCloseTag) !== false;
```

File: app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php [hunk 2]
```diff
@@ -32,48 +35,94 @@ public function __construct(ScopeConfigInterface $scopeConfig)
...
+
+        return $result;
+    }
+
+    /**
+     * Extracts link tags found in given content.
+     *
+     * @param string $content
+     */
+    private function extractLinkTags(&$content): string
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php]:
```suggestion
    private function extractLinkTags(string &$content): string
```

File: app/code/Magento/Theme/Test/Unit/Controller/Result/AsyncCssPluginTest.php [hunk 3]
```diff
@@ -98,48 +137,61 @@ public function sendResponseDataProvider(): array
      * @param bool $isSetFlag
      * @param string $result
      * @return void
-     * @dataProvider sendResponseDataProvider
+     * @dataProvider renderResultDataProvider
      */
-    public function testBeforeSendResponse($content, $isSetFlag, $result): void
+    public function testAfterRenderResult($content, $isSetFlag, $result): void
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/Test/Unit/Controller/Result/AsyncCssPluginTest.php]:
```suggestion
    public function testAfterRenderResult(string $content, bool $isSetFlag, string $result): void
```

File: app/code/Magento/Theme/view/frontend/templates/js/css_rel_preload.phtml [hunk 4]
```diff
@@ -2,7 +2,10 @@
 /**
  * Copyright © Magento, Inc. All rights reserved.
  * See COPYING.txt for license details.
+ * @deprecated since 100.4.0
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/view/frontend/templates/js/css_rel_preload.phtml]:
```suggestion
 * @deprecated as polyfill isn't used anymore
 * @since 100.4.0
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @mrtuvn,
In general your changes looks good, but I have few suggestions, please review them

**Comment by ihor-sviziev** [comment]
Could you also squash your changes into one or few commits in order not to have 13 merge commits?

**Comment by mrtuvn** [comment]
i have squashed commits and repick all to one commit. Ready for review and test

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7678](https://jira.corp.magento.com/browse/ENGCOM-7678) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Enable critical path CSS ( Admin -> Stores -> Configuration -> Advanced -> Developer -> Css Settings, set **Use CSS critical path** to **Yes**);
2. Run deploy static content + clean cache;
3. Go to homepage inspect in browser element "page-wrapper"

**Before:** :heavy_multiplication_x: `styles-m.css` and `styles-l.css` styles show up multiple times in developer tools.

Screenshot from 2020-06-16 10-46-22

**After:** :heavy_check_mark: The stylesheets are only loaded once

Screenshot from 2020-06-16 11-34-57

:heavy_check_mark: all external stylesheets are located in the same order at the end of <head>, after inline critical CSS

screenshot_64

Also was tested on the Blank theme and with sample data.

**Comment by engcom-Charlie** [comment]
It needs to approve.
**Semantic Version Checker** failed because of `css_rel_preload_script` block was removed.

**Comment by mrtuvn** [comment]
@DrewML @omiroshnichenko Can you guys take a look on this Thanks

**Comment by mrtuvn** [comment]
@sshymko @lbajsarowicz what do you guys think can we need improve in code ?

File: app/code/Magento/Theme/view/frontend/templates/js/css_rel_preload.phtml [hunk 5]
```diff
@@ -2,7 +2,11 @@
 /**
  * Copyright © Magento, Inc. All rights reserved.
  * See COPYING.txt for license details.
+ * @deprecated as polyfill isn't used anymore
+ * @since 100.4.0
```
Comment (lbajsarowicz) [inline app/code/Magento/Theme/view/frontend/templates/js/css_rel_preload.phtml]: As far as I remember - the automated tool adds the Version number to `@deprecated`. It's enough if you add `@deprecated` then.

File: app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php [hunk 6]
```diff
@@ -32,48 +35,94 @@ public function __construct(ScopeConfigInterface $scopeConfig)
...
+
+            if (preg_match('@media=("|\')(.*?)\1@', $style, $mediaAttribute)) {
+                $media = $mediaAttribute[2];
             }
+            $media = $media ?? 'all';
+
+            $style = sprintf(
+                '<link rel="stylesheet" media="print"' .
+                ' onload="this.onload=null;this.media=\'%s\'"' .
+                ' href="%s">',
```
Comment (lbajsarowicz) [inline app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php]: Can't this be squashed into single line?

File: app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php [hunk 7]
```diff
@@ -32,48 +35,94 @@ public function __construct(ScopeConfigInterface $scopeConfig)
...
+            if (!preg_match('@rel=["\']stylesheet["\']@', $style)) {
+                // Link is not a stylesheet, search for another one after it.
+                $styleOpenPos = strpos($content, $styleOpen, $styleClosePos);
+                continue;
+            }
+            // Remove the link from HTML to add it before </head> tag later.
+            $content = str_replace($style, '', $content);
+
+            preg_match('@href=("|\')(.*?)\1@', $style, $hrefAttribute);
+            $href = $hrefAttribute[2];
```
Comment (lbajsarowicz) [inline app/code/Magento/Theme/Controller/Result/AsyncCssPlugin.php]: I'm not sure about this code behaviour when there's invalid syntax provided.
Would you mind adding extra condition:
```suggestion
            if (!preg_match('@href=("|\')(.*?)\1@', $style, $hrefAttribute)) {
                throw new \Exception('Invalid <style> syntax provided');
            }
            $href = $hrefAttribute[2];
```

or something similar.

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Just minor adjustments are necessary.

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

**Review by lbajsarowicz — DISMISSED** [review]
:heavy_check_mark: Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7678](https://jira.corp.magento.com/browse/ENGCOM-7678) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by engcom-Charlie** [comment]
It needs to approve.
Semantic Version Checker failed because of css_rel_preload_script block was removed.

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
hi any update on this

**Comment by mrtuvn** [comment]
@magento run Integration Tests

**Review by lbajsarowicz — DISMISSED** [review]
I find the errors reported by tests as unrelated.
:heavy_check_mark: Thank you for your contribution!

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7678](https://jira.corp.magento.com/browse/ENGCOM-7678) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@mrtuvn @lbajsarowicz this PR still waiting approval for SVC failure

**Comment by lbajsarowicz** [comment]
@ihor-sviziev I know, but from my side the CR is actually :heavy_check_mark: green. Now it's up to Magento Commeng to approve that :)

**Comment by mrtuvn** [comment]
@ihor-sviziev @lbajsarowicz seem we have fail on intergration tests
Screenshot from 2020-07-30 17-00-57

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

File: app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml [hunk 8]
```diff
@@ -18,7 +18,6 @@
                     <argument name="criticalCssViewModel" xsi:type="object">Magento\Theme\Block\Html\Header\CriticalCss</argument>
                 </arguments>
             </block>
-            <block name="css_rel_preload_script" ifconfig="dev/css/use_css_critical_path" template="Magento_Theme::js/css_rel_preload.phtml"/>
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml:21]: Unfortunately this is backward incompatible change that leads to SVC failure which is not allowed in patch releases. Could you revert block removal and just put the empty view file instead with only deprecation notice, so it will not output anything?

And in future this block could be removed in next 2.5 or 2.6 release

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml (hunk 8 above)
Comment (mrtuvn) [reply app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml:21]: i can remove this block in layout xml so we don't need to empty template
Could add some note in layout for later refactor

Comment (ihor-sviziev) [reply app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml:21]: good idea, but block with name `css_rel_preload_script` should be there.

Comment (mrtuvn) [reply app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml:21]: yes i have updated in latest commit

File: app/code/Magento/Theme/view/frontend/layout/default.xml [hunk 9]
```diff
@@ -101,7 +101,7 @@
         </referenceContainer>
         <referenceContainer name="main">
             <container name="content.top" label="Main Content Top">
-                <block name="main_css_preloader" as="main_css_preloader" template="Magento_Theme::html/main_css_preloader.phtml" ifconfig="dev/css/use_css_critical_path"/>
+                <block class="Magento\Framework\View\Element\Template" name="main_css_preloader" as="main_css_preloader" template="Magento_Theme::html/main_css_preloader.phtml" ifconfig="dev/css/use_css_critical_path"/>
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/view/frontend/layout/default.xml]: I believe we don’t need this change, as this is default block type

File: app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml (hunk 8 above)
Comment (ihor-sviziev) [reply app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml:21]: I think even adding remove statement could break customizations, I suggest to go with one of those solutions:
- update view to not output anything
- remove “template” from the block

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

File: app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml (hunk 8 above)
Comment (mrtuvn) [reply app/code/Magento/Theme/view/frontend/layout/default_head_blocks.xml:21]: ok i have removed it from template now deprecated template will not output anything

File: app/code/Magento/Theme/view/frontend/templates/html/main_css_preloader.phtml [hunk 10]
```diff
@@ -4,12 +4,18 @@
...
 
-/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
+/**
+ * @var \Magento\Framework\View\Element\Template $block
+ * @var \Magento\Framework\Escaper $escaper
+ * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
+ */
+
+$escaper = isset($escaper) ? $escaper : $block;
 ?>
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/view/frontend/templates/html/main_css_preloader.phtml:13]: I believe we don’t need this check, as it always available in magento 2.4

File: app/code/Magento/Theme/view/frontend/templates/js/css_rel_preload.phtml [hunk 11]
```diff
@@ -25,4 +26,3 @@
 
 script;
 ?>
```
Comment (ihor-sviziev) [inline app/code/Magento/Theme/view/frontend/templates/js/css_rel_preload.phtml]: I think we don’t need to close php tag in this file at all, also on line 8 too

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by lbajsarowicz** [comment]
@mrtuvn & @ihor-sviziev If only one test was failing, you don't need to re-run all of them. Only when you confirm that the only one that was failing now passes, you can run the rest, to make the PR green. It's generally worth to reduce the load for build servers of Magento, because this affects also the stability of the environment (unfortunately).

**Comment by ihor-sviziev** [comment]
@lbajsarowicz there was only one test failing, so I fixed it and re-ran all tests

**Comment by mrtuvn** [comment]
yes i'm totally agree with that. Run all tests can take lot of times but after change in commit magento will reset all stage builds. Hope we will have all green after run.

File: dev/tests/integration/testsuite/Magento/Framework/Interception/PluginListGeneratorTest.php [hunk 12]
```diff
@@ -94,7 +94,6 @@ public function testPluginListConfigGeneration()
             1 => [
                 0 => 'genericHeaderPlugin',
                 1 => 'asyncCssLoad',
```
Comment (mrtuvn) [inline dev/tests/integration/testsuite/Magento/Framework/Interception/PluginListGeneratorTest.php]: @ihor-sviziev seem after this change plugin name asyncCssLoad already changed to intercept class 
Magento\Framework\View\Result\Layout instead previously Magento\Framework\App\Response\Http. So we should remove item asyncCssLoad. Is that correct ?
Also we should update plugin list added by @lbajsarowicz in another commit

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@mrtuvn static test still failing, I believe we could just ignore this failure for now.

**Comment by mrtuvn** [comment]
@lbajsarowicz can you give me some suggest about last static fail in intergration php

**Comment by lbajsarowicz** [comment]
@mrtuvn 
```php
@SuppressWarnings(PHPMD.CouplingBetweenObjects)
```

**Comment by mrtuvn** [comment]
@ihor-sviziev @lbajsarowicz updated 
Thanks for your help

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
@magento run Static Tests

**Comment by mrtuvn** [comment]
@magento run Database Compare, Functional Tests CE, Functional Tests EE, Functional Tests B2B, Integration Tests, Magento Health Index, Sample Data Tests CE, Sample Data Tests EE, Sample Data Tests B2B, Unit Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
@magento run Semantic Version Checker, Database Compare

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-7678](https://jira.corp.magento.com/browse/ENGCOM-7678) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Enable critical path CSS ( Admin -> Stores -> Configuration -> Advanced -> Developer -> Css Settings, set **Use CSS critical path** to **Yes**);
2. Run deploy static content + clean cache;
3. Go to homepage inspect in browser element "page-wrapper"

**Before:** :heavy_multiplication_x: `styles-m.css` and `styles-l.css` styles show up multiple times in developer tools.



**After:** :heavy_check_mark: The stylesheets are only loaded once



:heavy_check_mark: all external stylesheets are located in the same order at the end of <head>, after inline critical CSS

screenshot_64

Also was tested on the Blank theme and with sample data.

**Comment by xanka** [comment]
Hi @mrtuvn Did you test on production mode?

**Comment by mrtuvn** [comment]
What problem with production that you got?
