### PR TITLE
Let background commands actually run in the background

### LINKED ISSUE #38359: [Issue] Let background commands actually run in the background
This issue is automatically created based on existing pull request: magento/magento2#37511: Let background commands actually run in the background

---------
### Update 2023-05-30
After discussion with @engcom-Charlie (thanks!), I set up the Magento Functional Testing Framework locally to investigate the specifics of this test. The report was that the test worked fine on the `2.4-develop` branch, but was failing on #32690, so it was suggested that the changes there were breaking this test, and that the test was fine as-is on `2.4-develop`. I thought this was a race condition, but it seems it's more complicated than a simple race condition.

The reason the test isn't failing on `2.4-develop` is because STDERR isn't being redirected for the child processes, so the testing framework wasn't actually generating background processes when it should have been. https://github.com/magento/magento2/pull/37511/commits/7d56fe499617d1ad03c77ecace4dfd7c60a4c3dd fixes that bug, which will mean that all other unreliable tests will now be failing here. Many of the test failures here will be fixed by https://github.com/magento/magento2-functional-testing-framework/pull/904

### Description
While working on https://github.com/magento/magento2/pull/32690#discussion_r1196637387, it was discovered  that the test `StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest` (from `Magento\AcceptanceTest\_default\Backend\StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest`) is unreliable. This pull request aims to improve the reliability of this test. While this is not a complete fix, it will improve the reliability.

**Why is the test unreliable?**
The test aims to ensure that indexers are correctly triggered / rebuilt when making changes in the admin. The general process goes: log into admin, make a change, run cron, witness result. It's the "run cron" step that is causing issues. The internals of that step spawns separate processes, and then returns. These separate processes will run in the background and will work, however there is a race condition between these background processes running to completion and the next step of the test being carried out. When the indexer process is quick, all is well. When the test framework gets to the next step before the background process complete, the test fails.

**How does this change help?**

This pull request turns the background process into a foreground process, so the test framework won't ever reach the next step until the "background" process finishes.

**Why is this change incomplete?**

There is no guarantee that a job has actually been scheduled. There is still an expectation that there is a  `indexer_update_all_views` job in the queue, ready to be executed. Usually this will be the case, however it's not guaranteed. Further test improvements are welcome in this area.

### Manual testing scenarios
Run the following PHP script. It should report success.
```php
#!/usr/bin/env php
<?php

use Magento\Framework\App\ObjectManager;
use Magento\Framework\Console\Cli;
use Magento\Framework\Shell\CommandRendererBackground;

$command = 'sleep 10';

require __DIR__ . '/app/bootstrap.php';
new Cli('Magento CLI');
$objectManager = ObjectManager::getInstance();
$commandRenderer = $objectManager->get(CommandRendererBackground::class);

$command = $commandRenderer->render($command);
$startTime = microtime(true);

echo "DEBUG: running `$command` ...\n";
$process = proc_open($command, [
    0 => ['pipe', 'r'],
    1 => ['pipe', 'w'],
    2 => ['pipe', 'w'],
], $pipes, getcwd());
fclose($pipes[0]); // STDIN
echo stream_get_contents($pipes[1]); // STDOUT
echo stream_get_contents($pipes[2]); // STDERR
proc_close($process);

$endTime = microtime(true);
$duration = $endTime - $startTime;
$result = $duration >= 5 ? 'fail' : 'pass';
printf('Test %sed. It took %.1f seconds to start a long-running background process.', $result, $duration);
echo "\n";
```

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by fredden**
### Update 2023-05-30
After discussion with @engcom-Charlie (thanks!), I set up the Magento Functional Testing Framework locally to investigate the specifics of this test. The report was that the test worked fine on the `2.4-develop` branch, but was failing on #32690, so it was suggested that the changes there were breaking this test, and that the test was fine as-is on `2.4-develop`. I thought this was a race condition, but it seems it's more complicated than a simple race condition.

The reason the test isn't failing on `2.4-develop` is because STDERR isn't being redirected for the child processes, so the testing framework wasn't actually generating background processes when it should have been. https://github.com/magento/magento2/pull/37511/commits/7d56fe499617d1ad03c77ecace4dfd7c60a4c3dd fixes that bug, which will mean that all other unreliable tests will now be failing here. Many of the test failures here will be fixed by https://github.com/magento/magento2-functional-testing-framework/pull/904

### Description
While working on https://github.com/magento/magento2/pull/32690#discussion_r1196637387, it was discovered  that the test `StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest` (from `Magento\AcceptanceTest\_default\Backend\StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest`) is unreliable. This pull request aims to improve the reliability of this test. While this is not a complete fix, it will improve the reliability.

**Why is the test unreliable?**
The test aims to ensure that indexers are correctly triggered / rebuilt when making changes in the admin. The general process goes: log into admin, make a change, run cron, witness result. It's the "run cron" step that is causing issues. The internals of that step spawns separate processes, and then returns. These separate processes will run in the background and will work, however there is a race condition between these background processes running to completion and the next step of the test being carried out. When the indexer process is quick, all is well. When the test framework gets to the next step before the background process complete, the test fails.

**How does this change help?**

This pull request turns the background process into a foreground process, so the test framework won't ever reach the next step until the "background" process finishes.

**Why is this change incomplete?**

There is no guarantee that a job has actually been scheduled. There is still an expectation that there is a  `indexer_update_all_views` job in the queue, ready to be executed. Usually this will be the case, however it's not guaranteed. Further test improvements are welcome in this area.

### Manual testing scenarios
Run the following PHP script. It should report success.
```php
#!/usr/bin/env php
<?php

use Magento\Framework\App\ObjectManager;
use Magento\Framework\Console\Cli;
use Magento\Framework\Shell\CommandRendererBackground;

$command = 'sleep 10';

require __DIR__ . '/app/bootstrap.php';
new Cli('Magento CLI');
$objectManager = ObjectManager::getInstance();
$commandRenderer = $objectManager->get(CommandRendererBackground::class);

$command = $commandRenderer->render($command);
$startTime = microtime(true);

echo "DEBUG: running `$command` ...\n";
$process = proc_open($command, [
    0 => ['pipe', 'r'],
    1 => ['pipe', 'w'],
    2 => ['pipe', 'w'],
], $pipes, getcwd());
fclose($pipes[0]); // STDIN
echo stream_get_contents($pipes[1]); // STDOUT
echo stream_get_contents($pipes[2]); // STDERR
proc_close($process);

$endTime = microtime(true);
$duration = $endTime - $startTime;
$result = $duration >= 5 ? 'fail' : 'pass';
printf('Test %sed. It took %.1f seconds to start a long-running background process.', $result, $duration);
echo "\n";
```

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [x] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#38359: Let background commands actually run in the background

### CODE REVIEW

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run WebAPI Tests

**Comment by fredden** [comment]
@magento run WebAPI Tests

**Comment by fredden** [comment]
@magento run WebAPI Tests

**Comment by fredden** [comment]
@magento run WebAPI Tests

**Comment by fredden** [comment]
@engcom-Hotel / @engcom-Charlie, given this has been mentioned several times in https://github.com/magento/magento2/pull/32690, and the automated testing suite is passing 100% here, please can you look to get this reviewed/merged to avoid further delays in https://github.com/magento/magento2/pull/32690?

**Comment by fredden** [comment]
@engcom-Charlie thanks very much for taking the time to discuss this and https://github.com/magento/magento2/pull/32690 with me today. I've updated the "manual testing" steps in this pull request as discussed. I will try to get the Magento Functional Testing Framework set up to run at my end to verify that these steps are sufficient to clearly show that the test is broken on the `2.4-develop` branch and fixed here. If changes are required to these steps, I'll update here and contact you on Slack as suggested.

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
Many of the test failures here will be fixed by https://github.com/magento/magento2-functional-testing-framework/pull/904

**Comment by fredden** [comment]
@magento run Static Tests, Unit Tests, Functional Tests CE

File: lib/internal/Magento/Framework/Shell/CommandRendererBackground.php [hunk 1]
```diff
@@ -35,6 +35,6 @@ public function render($command, array $arguments = [])
 
         return $this->osInfo->isWindows() ?
             'start /B "magento background task" ' . $command
-            : str_replace('2>&1', '> /dev/null &', $command);
+            : str_replace('2>&1', '2>/dev/null >/dev/null &', $command);
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Shell/CommandRendererBackground.php:38]: Could you explain why we're moving all the stderr to /dev/null?

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Shell/CommandRendererBackground.php:38]: Ah, already saw the answer in the description

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by fredden** [comment]
@engcom-Hotel tests here will fail until https://github.com/magento/magento2-functional-testing-framework/pull/904 gets released. I don't see any value in running the test-suite here before that is done.
See also https://github.com/magento/magento2/pull/37511#issuecomment-1568870581.

**Comment by engcom-Hotel** [comment]
Hello @fredden,

I have added a `Related Pull Requests` tag in the description. It should work now.

Thanks

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
Hello @fredden,

Thanks for the contribution!

In order to test the PR, we first tried to reproduce the issue in the 2.4-develop branch with mentioned manual testing scenarios in the main description.

We got the below error while running the `StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest` test:

image

Then we tried the same test with this PR by including the changes in the PR https://github.com/magento/magento2-functional-testing-framework/pull/904

But still, we are getting the same error:

image

Please let us know if we are missing anything.

Thanks

**Comment by fredden** [comment]
@engcom-Hotel perhaps 'sleep(65)' is longer than your HTTP time-out. Can you try with 'sleep(5)' (or without adding a sleep) instead?

**Comment by engcom-Hotel** [comment]
Hello @fredden,

Thanks for the reply!

We have tried to run the below test without `sleep` as well, but we are getting the same error:

```
```

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37511/5300636af9562244952af78a9b2b29d3/Functional/allure-report-ce/index.html#categories/eb45f6c3ca9acc5c3823024405728f06/90a24ae2b0143d3/

**Comment by engcom-Hotel** [comment]
Hello @fredden,

Thanks for the reply!

We have tried to run the below test without `sleep` as well, but we are getting the same error:

```
vendor/bin/mftf run:test StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest --remove
```
image

You can see the same failure has been occurring here [functional tests](https://public-results-storage-prod.magento-testing-service.engineering/reports//magento//magento2/pull/37511/5300636af9562244952af78a9b2b29d3/Functional/allure-report-ce/index.html#categories/eb45f6c3ca9acc5c3823024405728f06/90a24ae2b0143d3/)

Thanks

**Comment by fredden** [comment]
@engcom-Hotel thanks for looking into this. I think there are too many variables here to easily identify why you're getting these results. Let's get https://github.com/magento/magento2-functional-testing-framework/pull/904 merged in, and I can then update the `composer.lock` file here and test again.

**Comment by engcom-Charlie** [comment]
Hi @fredden,

As per the latest updates #[904](https://github.com/magento/magento2-functional-testing-framework/pull/904) is merged and as discussed with internal team member MFTF 4.3.2 release is done. The release tag is avaiable now.

I have updated the composer.json and composer.lock. Updated the other required changes too in composer.json after having discussion with MFTF team member. Removing the #904 from the Related PR now.

Thank you!

**Comment by fredden** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@fredden please try reverting change both in composer.json and composer.lock files and then run `composer update magento/magento2-functional-testing-framework` to update the only this depencency.

**Comment by fredden** [comment]
@ihor-sviziev I have already done that. I don't know why so many changes were made by @engcom-Charlie, but I reverted as many of these as I could in https://github.com/magento/magento2/pull/37511/commits/d78b6f8a621fa04e69ef917f970bfbf3b4e96227. I decided to keep the bump to the minimum version in `composer.json`, but this could be reverted if desired. Without that change it would be possible to install a version of the testing framework which consistently fails with the code in this repository.

The testing framework changed a number of its dependencies in version 4.3.0 here: https://github.com/magento/magento2-functional-testing-framework/commit/32615bc36c2c39608b7e57fcbdb5cd7187c5a8de - that's why so many other packages are also being upgraded / changed here.

**Comment by engcom-Charlie** [comment]
Hi @fredden,

As you can see, I have just added below 3 changes in composer.json.

"magento/magento2-functional-testing-framework": "^4.3.2",
"sebastian/comparator": "<=4.0.6",
"symfony/process": "<=v5.4.23"

Definatly the "magento/magento2-functional-testing-framework": "^4.3.2", change is required.

About rest of the 2 changes, as I have mentioned already that, after having a discussion with internal MFTF team; they only suggested to add these 2 packages also in this build.  Since they have analysed that with 4.3.2 there are some incompatibility issues with some of the packages, so there will be number of changes in the dependencies. 

FYI: These 2 dependencies anyhow soon going to be merged in composer.json from their few upcoming  PRs

Thank you!

**Comment by fredden** [comment]
@engcom-Charlie, thanks for the explanation. The `composer.json` changes for "sebastian/comparator" and "symfony/process" still sound out of scope here. It's unclear to me if you mean to say that (a) the MFTF package has an incorrect / incompatible set of requirements in its `composer.json` file (which should be fixed in the repository for that package, not here), or (b) there is an incompatibility in this project (Magento2) with the latest version of MFTF (which should be fixed in a separate pull request). In either case, the scope of this pull request is not to fix incompatibilities with the MFTF, but instead to resolve a flaw in the tests (not the framework) regarding processing of cron jobs.

As an aside, it would be better to list incompatible packages in the "conflict" section of `composer.json`, not as "require" entries with "<=". https://getcomposer.org/doc/04-schema.md#conflict

**Comment by fredden** [comment]
Looking at the automated test results here, I'm not convinced that the tooling at Adobe is using the prescribed version of the testing framework. How can this be verified?

**Comment by fredden** [comment]
@magento run WebAPI Tests

**Comment by ihor-sviziev** [comment]
Hi @fredden,
Looks like MFTF was already upgraded to latest version in https://github.com/magento/magento2/commit/ca30c47787db932b9431e42226bb918e95c932d9.
Could you pls resolve conflicts?

**Comment by fredden** [comment]
@magento run all tests

File: composer.lock [hunk 2]
```diff
@@ -4,7 +4,7 @@
         "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
         "This file is @generated automatically"
     ],
-    "content-hash": "df2bfe94e9160251d0a853ee3531942a",
+    "content-hash": "e10a62ff80f933f1f186f448e92a0229",
```
Comment (ihor-sviziev) [inline composer.lock]: I think we should revert this change

File: composer.json [hunk 3]
```diff
@@ -98,7 +98,7 @@
         "friendsofphp/php-cs-fixer": "^3.8",
         "lusitanian/oauth": "^0.8",
         "magento/magento-coding-standard": "*",
-        "magento/magento2-functional-testing-framework": "^4.3.0",
```
Comment (ihor-sviziev) [inline composer.json]: I think we should revert this change

File: composer.lock (hunk 2 above)
Comment (fredden) [reply composer.lock]: This is the result of running `composer update` with the new content in `composer.json`. It's correct if we're still modifying `composer.json` in this pull request.

File: composer.json (hunk 3 above)
Comment (fredden) [reply composer.json]: The changes in that package which are required for the correct functioning of the test suite here were released in version 4.3.2, so that's the minimum version we are compatible with. If we do not include this change, then the test-suite will consistently fail when using `composer update --prefer-lowest`.

https://github.com/magento/magento2-functional-testing-framework/pull/904#issuecomment-1598783540

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Could you please review functional test failures? It looks like some of them were caused by changes from this PR

**Comment by fredden** [comment]
@magento run Functional Tests CE

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by fredden** [comment]
@magento run Functional Tests CE

**Comment by fredden** [comment]
It seems that commits labelled 'ACQE-5351' have been added (without any pull requests) to the `2.4-develop` branch which replace indexer-related `<magentoCLI />` and `<magentoCron />` elements with an `<actionGroup />` element. Eg, 710601047612190c32f02c638066a7c375668e6f. @dhaecker, perhaps you can share some information here to explain why this has happened.

**Comment by dhaecker** [comment]
@fredden `ACQE-5351` was merged into `stability_control` branch as a part of the Stabilithon event. `stability_control` was then merged into `2.4-develop` in https://github.com/magento-commerce/magento2ce/pull/8449 and its related PRs. Please do not revert these changes :)

**Comment by fredden** [comment]
@dhaecker thanks for your comment. Please can you share some information about what "ACQE-5351" is? The link you have provided is private-to-adobe.

**Comment by fredden** [comment]
@magento run all tests

**Comment by dhaecker** [comment]
@fredden Oh sry I didn't notice that this was the public repo. 

The PRs that were merged in the internal repositories we all related to stabilizing MFTF tests. 

"ACQE-5351" specifically was a ticket to "Replace magentoCli commands for cron with magentoCron, replace magentoCli commands for reindexing with reindexing actiongroup, & replace magentoCron commands for indexing with reindexing actiongroup"

**Comment by fredden** [comment]
@magento run all tests

**Comment by fredden** [comment]
@magento run Functional Tests B2B, Unit Tests, WebAPI Tests

**Comment by ihor-sviziev** [comment]
Hi @fredden,
Could you please remind what's the status of this pull request? can I review it?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by fredden** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi,
Could you please fix the SVC failure? Let's use `comment` instead of removing some step.

**Comment by fredden** [comment]
@ihor-sviziev this looks like a false alert. Running cron (without any groups defined) twice is not the correct action, but running the index group once is correct.

**Comment by ihor-sviziev** [comment]
@fredden According to SVC failure, removing some steps is a backward incompatible change since other extensions might use it. Could you pls replace it with a comment (so nothing actually doing)

**Comment by ihor-sviziev** [comment]
@engcom-Charlie maybe you can point?

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by engcom-Charlie** [comment]
> @engcom-Charlie maybe you can point?

Sure, looking into it.

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
I have fixed the SVC failure. 

The Functional CE failure is different in recent 2 builds.

**Run 1:** 

https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37511/482408191f336700cc42fd0d0d1c13ef/Functional/allure-report-ce/index.html#categories/cb0e8d63c7885d1e5a307abbeed910d7/c1ea087d1ef0f04c/

**Run 2:** 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/37511/ed6c72138f16a266a74143e67564fda0/Functional/allure-report-ce/index.html#categories/8c83f0dae13477ff8e1544d1d798ceff/a9ed5b16ea28caba/

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Integration Tests, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Integration Tests, Static Tests, Unit Tests

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B, Unit Tests, WebAPI Tests

**Comment by fredden** [comment]
@magento run unit tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Charlie** [comment]
Hi @fredden,

We have tried to reproduce the issue as mentioned in the Manual testing scenarios. StorefrontVerifyProductAfterPartialReindexOnSeveralWebsitesTest test is working fine on local magento 2.4 develop instance after adding sleep too. Can you please check it once at your end and let us know if we are missing anything.

Screenshot 2024-01-02 at 2 35 13 PM
Screenshot 2024-01-02 at 2 37 01 PM
Screenshot 2024-01-02 at 2 37 34 PM
Screenshot 2024-01-02 at 2 37 50 PM

**Comment by fredden** [comment]
@engcom-Charlie it looks like I have not updated the steps to reproduce properly when the scope of this pull request changed. I'll put the following script into the description shortly. It reliably reproduces the problem in the `2.4-develop` branch, and works as expected on this branch.

```php
#!/usr/bin/env php
<?php

use Magento\Framework\App\ObjectManager;
use Magento\Framework\Console\Cli;
use Magento\Framework\Shell\CommandRendererBackground;

$command = 'sleep 10';

require __DIR__ . '/app/bootstrap.php';
new Cli('Magento CLI');
$objectManager = ObjectManager::getInstance();
$commandRenderer = $objectManager->get(CommandRendererBackground::class);

$command = $commandRenderer->render($command);
$startTime = microtime(true);

echo "DEBUG: running `$command` ...\n";
$process = proc_open($command, [
    0 => ['pipe', 'r'],
    1 => ['pipe', 'w'],
    2 => ['pipe', 'w'],
], $pipes, getcwd());
fclose($pipes[0]); // STDIN
echo stream_get_contents($pipes[1]); // STDOUT
echo stream_get_contents($pipes[2]); // STDERR
proc_close($process);

$endTime = microtime(true);
$duration = $endTime - $startTime;
$result = $duration >= 5 ? 'fail' : 'pass';
printf('Test %sed. It took %.1f seconds to start a long-running background process.', $result, $duration);
echo "\n";
```

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by engcom-Charlie** [comment]
@magento run Functional Tests CE

**Comment by engcom-Charlie** [comment]
HI @fredden,

Thank you for the updated Manual testing scenario.

:heavy_check_mark: QA Passed

**Before:** :heavy_multiplication_x:
I have executed the given script in latest magento 2.4-develop and the issue is reproducible. 
24dev

**After:** :heavy_check_mark:  
In PR branch the same script is working fine.
PR

As the build is green so moving it to Merge in Progress.

Thank you!

**Comment by engcom-Charlie** [comment]
@magento create issue

**Comment by engcom-Charlie** [comment]
It seems that bot moved it to testing hence moving it back to its previous status, Merge in Progress.

**Comment by engcom-Charlie** [comment]
@magento run Semantic Version Checker
