### PR TITLE
Fix Downloadable product after refund

### LINKED ISSUE #28388: Downloadable product is available in My Download Products tab after it has been partially refunded
### Preconditions (*)

1. Magento CE 2.3.5 wih sample data is installed.
2. Order with a download product and a product, requiring shipping, (e.g. simple product) is created.
3. The downloadable product is available in My Downloadable Products tab.

### Steps to reproduce (*)

1. Open this order page in Admin.
2. Perform a partial refund for the downloadable product (the other product is not refunded).
3. Go to My Downloadable Products tab.

### Expected result (*)

1. Downloadable product cannot be downloaded.

### Actual result (*)

1. Downloadable product still can be downloaded.
order page
My DP tab

### Additional information 
Issue also reproduce on the lates `2.4-develop` https://github.com/magento/magento2/issues/28388#issuecomment-635249996

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28388. Downloadable product is available in My Download Products tab after it has been partially refunded

### Manual testing scenarios (*)

1. Create order with a download product and a product, requiring shipping, (e.g. simple product) is created.
2. The downloadable product is available in My Downloadable Products tab.
3. Open this order page in Admin.
4. Perform a partial refund for the downloadable product (the other product is not refunded).
5. Go to My Downloadable Products tab.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
Hi @ProkopovVitaliy. Thanks for collaboration. Can you please fix failed tests? Also, can you please cover this functionality by functional or integration tests?

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests EE

**Comment by engcom-Kilo** [comment]
Working with MFTF test.

**Review by VladimirZaets — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @VladimirZaets, thank you for the review.
[ENGCOM-7679](https://jira.corp.magento.com/browse/ENGCOM-7679) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Has a Simple product;
2. Has a Downloadable product;
3. Has a customer in Storefront;

**Manual testing scenario:**

1. Create order with a download product and a product, requiring shipping, (e.g. simple product) is created;
2. Create a full invoice for the order;
3. Go to Storefront-> My Account -> My Downloadable Products 

**Actual Result:** :heavy_check_mark: The downloadable product can be downloaded.

screenshot_66
 
4. Perform a partial refund (credit memo) for the downloadable product (the other product is not refunded).

Screenshot from 2020-06-16 13-27-21

5. Go to Storefront-> My Account -> My Downloadable Products again

**Before:** :heavy_multiplication_x: After a refund, the Downloadable product still can be downloaded.

screenshot_65

**After:** :heavy_check_mark:  The Downloadable product cannot be downloaded.

Screenshot from 2020-06-16 13-27-39

Also tested with different stores, combinations with different types of products

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Failed Functional Tests EE not related to the changes in this PR

**Comment by slavvka** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests B2B

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — CHANGES_REQUESTED** [review]
@ProkopovVitaliy @engcom-Kilo @engcom-Alfa Guys, please take a close look at failing MFTF tests since they are failing when trying to deliver almost constantly. Something in the changes seems to make them more flaky

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Kilo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Kilo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Kilo** [comment]
@magento run all tests

File: app/code/Magento/Downloadable/Test/Unit/Observer/SetLinkStatusObserverTest.php [hunk 1]
```diff
@@ -189,7 +189,7 @@ public function testSetLinkStatusPending($orderState, array $orderStateMapping)
                 ]
             );
 
-        $this->itemsFactory->expects($this->once())
+        $this->itemsFactory->expects($this->any())
```
Comment (sidolov) [inline app/code/Magento/Downloadable/Test/Unit/Observer/SetLinkStatusObserverTest.php:192]: It's better to use atLeastOnce instead.

File: app/code/Magento/Downloadable/Test/Unit/Observer/SetLinkStatusObserverTest.php [hunk 2]
```diff
@@ -390,7 +524,7 @@ private function createLinkItemCollection(array $expectedOrderItemIds, array $it
             ->disableOriginalConstructor()
             ->setMethods(['addFieldToFilter'])
             ->getMock();
-        $linkItemCollection->expects($this->once())
+        $linkItemCollection->expects($this->any())
```
Comment (sidolov) [inline app/code/Magento/Downloadable/Test/Unit/Observer/SetLinkStatusObserverTest.php:527]: It's better to use atLeastOnce instead.

**Review by sidolov — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**

1. Has a Simple product;
2. Has a Downloadable product;
3. Has a customer in Storefront;

**Manual testing scenario:**

1. Create order with a download product and a product, requiring shipping, (e.g. simple product) is created;
2. Create a full invoice for the order;
 
3. Perform a partial refund (credit memo) for the downloadable product (the other product is not refunded).

Screenshot from 2020-06-16 13-27-21

4. Go to Storefront-> My Account -> My Downloadable Products again

**Before:** :heavy_multiplication_x: After a refund, the Downloadable product still can be downloaded.



**After:** :heavy_check_mark:  The Downloadable product cannot be downloaded.



Also tested with different stores, combinations with different types of products
