### PR TITLE
Resolved getting correct attribute code, label value of price type attribute in aggregations data of products GraphQl response #28878

### LINKED ISSUE #28878: Not getting correct attribute code, label value of price type attribute in aggregations data of products GraphQl response
### Preconditions (*)

1. Magento version: 2.3.5 -p1
2. Php version: 7.3.19

### Steps to reproduce (*)

1. create a price type product attribute at backend and set "Use in Layered Navigation" as "Filterable (with results)"
2. assign newly created attribute to attribute set
3. Fill newly created attribute for some products
4. Then check products query response aggregations data in graphql

### Expected result (*)

1. attribute_code and label must be same as saved at backend
expected

### Actual result (*)

attribute
issue

### PR DESCRIPTION
**Pull request by rani-priya**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#28878

### Manual testing scenarios (*)

1. create a price type product attribute at backend and set "Use in Layered Navigation" as "Filterable (with results)"
2. assign newly created attribute to attribute set
3. Fill newly created attribute for some products
4. Then check products query response aggregations data in graphql
5. in attribute_code and label is not correct for price type attribute in aggregations data

attribute

issue

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php [hunk 1]
```diff
@@ -90,7 +90,7 @@ public function getOptions(array $optionIds, ?int $storeId, array $attributeCode
                 Store::DEFAULT_STORE_ID
             );
 
-        $select->where('option_value.option_id IN (?)', $optionIds);
+        $select->where('a.attribute_code IN (?)', $attributeCodes);
```
Comment (Serializator) [inline app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: Using `$attributeCodes` instead of `$optionIds` makes the `$optionIds` unused. Considering the name of the method `getOptions` it seems highly unlikely that this should be the case.

In `Magento\CatalogGraphQl\DataProvider\Product\LayeredNavigation\Builder\Attribute` on line 158 this method is called with an array of option ids, these would be ignored.

Or maybe I'm wrong (I haven't looked to much into the issue) and this is the proper solution. In that case I'd like to ask to consider refactoring the method to remove `$optionIds` as an argument to prevent confusion in the future (might someone look at the method and ask the question "is this unused variable simply unused or should it be used and thus a bug").

Comment (rani-priya) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @Serializator could you please suggest the required solution for the same?

Comment (rani-priya) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @ihor-sviziev could you please suggest the required solution for issue #28878 ?

Comment (rani-priya) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @Serializator could you please review my last commit, I have made required changes.

Comment (Serializator) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @rani-webkul, good pull request 👍 🎉

**Review by Serializator — APPROVED** [review]

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php (hunk 1 above)
Comment (rani-priya) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @Serializator Thankyou for approving the changes.
But as I can see this pull request is not passing all the checks. Could you please let me know, If I am missing something?

Comment (Serializator) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @rani-webkul, I only see that the tests are waiting for a status report, none are failing yet.

Comment (rani-priya) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php]: @Serializator it's been 6 days but checks are not completing why?

**Comment by Serializator** [comment]
@magento run all tests

**Comment by rani-webkul** [comment]
Hi @Serializator 

Could you please help to solve "Functional Tests B2B " test failure.

**Comment by Serializator** [comment]
Hi @rani-webkul,

I don't believe the failure of "Functional Tests B2B" is related to changes made in this pull request, in my opinion you can safely "ignore" it (in the scope of this pull request).

- When I look at the test which is failing it doesn't seem (directly) related
- I see that the same test is failing in some other pull requests

**Comment by rani-webkul** [comment]
@Serializator could you please look into this issue https://github.com/magento/magento2/issues/28937

**Comment by rani-webkul** [comment]
@magento run all tests

**Review by glo82145 — COMMENTED** [review]
Automation test case is missing

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php [hunk 2]
```diff
@@ -94,7 +94,7 @@ public function getOptions(array $optionIds, ?int $storeId, array $attributeCode
 
         if (!empty($attributeCodes)) {
             $select->orWhere(
-                'a.attribute_code in (?) AND a.frontend_input = \'boolean\'',
+                'a.attribute_code in (?) AND a.frontend_input in (\'boolean\', \'price\')',
```
Comment (glo82145) [inline app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:97]: Automation test is missing

**Review by glo82145 — CHANGES_REQUESTED** [review]

**Comment by engcom-Charlie** [comment]
Hi @rani-priya,

Thank you for your contribution!

Can you please look into review comments.

Thank you!

File: app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php (hunk 2 above)
Comment (glo82145) [reply app/code/Magento/CatalogGraphQl/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php:97]: As automation test is already covered. .. approving this PR

**Review by glo82145 — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`
- PHP 8.1

**Manual testing scenario:**
1. Create a price type product attribute at backend and set "Use in Layered Navigation" as "Filterable (with results)"
2. Assign newly created attribute to attribute set
3. Fill newly created attribute for some products
4. Then check products query response aggregations data in graphql

**Query:**
```
{
  products(filter: {category_id: {eq: "3"}, price: {from: "30", to: "100"}, color: {eq: "49"}}, pageSize: 25) {
    aggregations {
      attribute_code
      count
      label
      options {
        label
        value
        count
      }
    }
    items {
      name
      sku
      price_range {
        minimum_price {
          regular_price {
            value
            currency
          }
        }
      }
    }
    page_info {
      page_size
    }
  }
}
```
**Before:** :heavy_multiplication_x:  Attribute code was not coming properly.
Attach screenshot:
Screenshot 2022-09-15 at 4 33 23 PM

**After:** :heavy_check_mark:  Attribute code now coming properly.
Attach screenshot
Screenshot 2022-09-15 at 4 38 18 PM

**Additionally tested:**
1. Created order.
2. Generated invoice.
3. Hold,unhold order.
4. Credit memo and Reordered the product.
Since it 's is minor change hence, no manual test case is required .
PR is working fine, hence, moving this PR to merge in progress.
Thanks

**Comment by engcom-Hotel** [comment]
@magento run WebAPI Tests
