### PR TITLE
[Backport] fix(Webapi Xml Renderer - 18361): removed the not needed ampersand re…

### LINKED ISSUE #18361: Customer last name is encoded twice in the XML interface
### Preconditions
1. Vanilla Magento 2.2.6 
2. PHP Version 7.0.31

### Steps to reproduce
1.  Create a customer via Backend with the last name "Foo & Bar Corp"
2. Create an order (via frontend is fine)
3. Export the order via XML interfcae

```
curl -XPOST -H 'Content-Type: application/json' http://hostname/rest/V1/integration/admin/token -d '{ "username": "admin_username", "password": "admin_password" }'
export B=code received above
 curl -X GET --header "Accept: application/xml" --header "Authorization: Bearer $B" "http://hostname/rest/english/V1/orders/1"
```

### Expected result
The `customer_lastname` tag should contain `Foo &amp; Bar Corp`

### Actual result
The `customer_lastname` tag contains `Foo &amp;amp Bar Corp`

### Summary
So I think at some point (2014) there was a bug in PHP (SimpleXML) that contained the issue with the ampersand, so that was a fix so that this won't influence any functionality. Currently, on 7.0+ this fix doesn't make sense and creates an error. 

### Proposed solution
`Magento\Framework\Webapi\Rest\Response\Renderer` class, `_formatValue` method. Delete the replacement of the ampersand. This solves the issue.

### PR DESCRIPTION
**Pull request by nickshatilo**
Fixes #18361 (ampersand xml serialisation issue)

### Description

As described in https://github.com/magento/magento2/issues/18361, the issue is about having the ampersand in any customer text field, and when using the WebApi, it causes an issue of doubling the encoding. I.e `&amp;amp;`, which is not the case in the XML format, so it should be resolved.

### Fixed Issues (if relevant)

1. magento/magento2#18361: Customer last name is encoded twice in the XML interface #18361

### Manual testing scenarios

1.  Create a customer via Backend with the last name "Foo & Bar Corp"
2. Create an order (via frontend is fine)
3. Export the order via XML interfcae

```
curl -XPOST -H 'Content-Type: application/json' http://hostname/rest/V1/integration/admin/token -d '{ "username": "admin_username", "password": "admin_password" }'
export B=code received above
 curl -X GET --header "Accept: application/xml" --header "Authorization: Bearer $B" "http://hostname/rest/english/V1/orders/1"
```
The `customer_lastname` tag should contain `Foo &amp; Bar Corp`

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### Original PR 
https://github.com/magento/magento2/pull/18380

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/magento2?pullRequest=18362) <br/>All committers have signed the CLA.

**Comment by rogyar** [comment]
Hi @nickshatilo. Thank you for your contribution. According to the contribution guidelines, we can accept changes to the 2.2-develop branch only if they are present in 2.3-develop branch (https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#rules). Please, consider creating the same PR to the 2.3-develop branch first. Thank you.

**Comment by nickshatilo** [comment]
@rogyar Please take a look: https://github.com/magento/magento2/pull/18380

File: lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php [hunk 1]
```diff
@@ -111,8 +111,7 @@ protected function _formatValue($value)
             /** Without the following transformation boolean values are rendered incorrectly */
             $value = $value ? 'true' : 'false';
         }
-        $replacementMap = ['&' => '&amp;'];
-        return str_replace(array_keys($replacementMap), array_values($replacementMap), $value);
+        return $value;
```
Comment (amenk) [inline lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php]: must be `return (string) $value` because the function can get passed floats as well (the docblock lies) -> this causes a regression with prices in the XML

**Review by amenk — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php (hunk 1 above)
Comment (nickshatilo) [reply lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php]: @amenk Fixed your comment.

Comment (amenk) [reply lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php]: I can't seem to see the change in this PR ? Do you have a link or did you forget to push?

Comment (nickshatilo) [reply lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php]: https://github.com/magento/magento2/pull/18362/commits/0f75306061dcf6dc2942d6e165e8ba17f2ce3f6c

Comment (amenk) [reply lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php]: A you disguised it as "added unit test" :-)

**Review by amenk — APPROVED** [review]

File: lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php (hunk 1 above)
Comment (nickshatilo) [reply lib/internal/Magento/Framework/Webapi/Rest/Response/Renderer/Xml.php]: @amenk Made an amend commit)

**Comment by nickshatilo** [comment]
@josefbehr @rogyar avGoncharuk  Can you please take a look?

**Comment by sidolov** [comment]
Hi @nickshatilo , I'm closing this PR because original PR (https://github.com/magento/magento2/pull/18380) was closed due to inactivity.
Please, reopen it if you wish to continue. 
Thnk you!

**Comment by sivaschenko** [comment]
Reopening as the original pull request is approved

**Review by sivaschenko — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-3929](https://jira.corp.magento.com/browse/ENGCOM-3929) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
Hi @nickshatilo. Thank you for your contribution. 
We will aim to release these changes as part of 2.2.8. 
Please check the release notes for final confirmation.

Please, consider to port this solution to 2.3 release line.
You may use [Porting tool](https://devdocs.magento.com/guides/v2.2/contributor-guide/contributing.html#porting-tool) to port commits automatically.
