### PR TITLE
Resolve Account sidebar current tab is not marked as Active (issue 24068)

### LINKED ISSUE #24068: Account sidebar current tab is not marked as Active
### Preconditions (*)

1. Magento 2.3.2
2. Sample data installed

### Steps to reproduce (*)

1. Login as customer. You can see below screen.
AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_36

2. Please note URL here.
a)  /customer/account/
b) As above screenshot, My Account tab selected as current tab.

3. Please add index/ after /customer/account/
So URL become like  /customer/account/index/
AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_40

You can see My Account tab is not marked as activate tab for /customer/account/index/. This issue available with whole sidebar tab in customer account section.

### Expected result (*)

1. My Account tab marked as activate tab for below both URLs.
a)  /customer/account/
b)  /customer/account/index/
2. Same thing with all other sidebar links.

### Actual result (*)

1. My Account tab is not marked as activate tab for below URL.
a)  /customer/account/index/
AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_40

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#24068: Account sidebar current tab is not marked as Active

- Solution: Should remove all "/index" and "/" redundant before compare the Url. Use `preg_replace`

### Fixed Issues (if relevant)

1. magento/magento2#24068: Account sidebar current tab is not marked as Active

### Manual testing scenarios (*)

1. Login as customer. You can see below screen.
AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_36

2. Please note URL here.
a)  /customer/account/
b) As above screenshot, My Account tab selected as current tab.

3. Please add index/ after /customer/account/
So URL become like  /customer/account/index/
AwesomeScreenshot-nlipoenfbbikpbjkfpfillcgkoblgpmj-upload html-2019-08-08_6_40

You can see My Account tab is not marked as activate tab for /customer/account/index/. This issue available with whole sidebar tab in customer account section.

#### Expected result

1. My Account tab marked as activate tab for below both URLs.
a)  /customer/account/
b)  /customer/account/index/
2. Same thing with all other sidebar links.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: lib/internal/Magento/Framework/View/Element/Html/Link/Current.php [hunk 1]
```diff
@@ -87,7 +87,9 @@ private function getMca()
      */
     public function isCurrent()
     {
-        return $this->getCurrent() || $this->getUrl($this->getPath()) == $this->getUrl($this->getMca());
+        return $this->getCurrent() ||
+            preg_replace('/(\/index|(\/))+($|\/$)/', '', $this->getUrl($this->getPath()))
```
Comment (swnsma) [inline lib/internal/Magento/Framework/View/Element/Html/Link/Current.php]: Could you please move this regexp to private constant?

**Review by swnsma — CHANGES_REQUESTED** [review]

File: lib/internal/Magento/Framework/View/Element/Html/Link/Current.php (hunk 1 above)
Comment (edenduong) [reply lib/internal/Magento/Framework/View/Element/Html/Link/Current.php]: Hello @swnsma  :  Does it satisfy the "Documentation of Backward Incompatible Changes" ? Thanks!
image

Comment (edenduong) [reply lib/internal/Magento/Framework/View/Element/Html/Link/Current.php]: Hello @swnsma: It can not pass the Semantic Test if I add the new constant to the @api class.

Comment (swnsma) [reply lib/internal/Magento/Framework/View/Element/Html/Link/Current.php]: @edenduong, I think everything should be OK, if we add this constant as `private` for our internal purposes.

Comment (edenduong) [reply lib/internal/Magento/Framework/View/Element/Html/Link/Current.php]: @swnsma: I have changed it. Please check it again. Thanks.

**Review by swnsma — APPROVED** [review]
Adding private constant is not BC break.
`Semantic Version Checker` need to be adjusted to differentiate private and not private constants.

**Comment by magento-engcom-team** [comment]
Hi @swnsma, thank you for the review.
[ENGCOM-5608](https://jira.corp.magento.com/browse/ENGCOM-5608) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed
