### PR TITLE
Log Aggregation fix on Checkout failure (group by reason, not Quote ID)

### LINKED ISSUE #37879: [Issue] Log Aggregation fix on Checkout failure (group by reason, not Quote ID)
This issue is automatically created based on existing pull request: magento/magento2#37871: Log Aggregation fix on Checkout failure (group by reason, not Quote ID)

---------

### Description (*)
More and more projects use log aggregation tools - either self-hosted like Kibana, or SaaS like NewRelic or Sentry. These solutions are not able to aggregate log messages correctly, when these include unique data - such as event ID or Quote ID. 

Event-specific details should be passed as a second attribute (`context`) of log method.

Before:
image

After

image

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Trigger Checkout failure
2. Validate log message - It should not include any details

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
More and more projects use log aggregation tools - either self-hosted like Kibana, or SaaS like NewRelic or Sentry. These solutions are not able to aggregate log messages correctly, when these include unique data - such as event ID or Quote ID. 

Event-specific details should be passed as a second attribute (`context`) of log method.

Before:
image

After

image

### Fixed Issues (if relevant)
N/A

### Manual testing scenarios (*)
1. Trigger Checkout failure
2. Validate log message - It should not include any details

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#37879: Log Aggregation fix on Checkout failure (group by reason, not Quote ID)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by convenient — APPROVED** [review]

**Comment by convenient** [comment]
sorry went on autopilot there and approved rather than 👍  😅

File: app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php [hunk 1]
```diff
@@ -139,9 +140,13 @@ public function savePaymentInformationAndPlaceOrder(
         }
         try {
             $orderId = $this->cartManagement->placeOrder($cartId);
-        } catch (\Magento\Framework\Exception\LocalizedException $e) {
+        } catch (LocalizedException $e) {
             $this->logger->critical(
-                'Placing an order with quote_id ' . $cartId . ' is failed: ' . $e->getMessage()
+                'Placing an Order failed (reason: '.  $e->getMessage() .')',
```
Comment (michalbiarda) [inline app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php:145]: I think "reason" might be moved to "context" too. Also, we could add boolean "is_guest_checkout" to the context as well.

File: app/code/Magento/Checkout/Model/PaymentInformationManagement.php [hunk 2]
```diff
@@ -152,7 +152,11 @@ public function savePaymentInformationAndPlaceOrder(
             $orderId = $this->cartManagement->placeOrder($cartId);
         } catch (LocalizedException $e) {
             $this->logger->critical(
-                'Placing an order with quote_id ' . $cartId . ' is failed: ' . $e->getMessage()
+                'Placing an Order failed (reason: '.  $e->getMessage() .')',
```
Comment (michalbiarda) [inline app/code/Magento/Checkout/Model/PaymentInformationManagement.php:155]: I think "reason" might be moved to "context" too. Also, we could add boolean "is_guest_checkout" to the context as well.

**Review by michalbiarda — COMMENTED** [review]
I like this change. I left in comments some ideas for further improvements.

File: app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php (hunk 1 above)
Comment (lbajsarowicz) [reply app/code/Magento/Checkout/Model/GuestPaymentInformationManagement.php:145]: `is_guest_checkout` is a great idea! 
Adding that now.

File: app/code/Magento/Checkout/Model/PaymentInformationManagement.php (hunk 2 above)
Comment (lbajsarowicz) [reply app/code/Magento/Checkout/Model/PaymentInformationManagement.php:155]: @magento run all tests

Comment (lbajsarowicz) [reply app/code/Magento/Checkout/Model/PaymentInformationManagement.php:155]: With `reason` I'll submit that as a separate PR, as this might bring discussion to the table, and I want this one to be merged asap

**Comment by lbajsarowicz** [comment]
@magento run all tests

**Review by tdgroot — APPROVED** [review]
👍

**Comment by engcom-Lima** [comment]
@magento create issue

File: app/code/Magento/Checkout/Model/PaymentInformationManagement.php (hunk 2 above)
Comment (ihor-sviziev) [reply app/code/Magento/Checkout/Model/PaymentInformationManagement.php:155]: I think keeping reason as a part of the message is a good idea.

**Review by ihor-sviziev — APPROVED** [review]
✔ Approved.

Failing tests look not related to changes from this PR.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
### :heavy_check_mark: QA Passed

**Manual testing scenario:**
1.   Trigger Checkout failure
2.   Validate log message - It should not include any details

**Before:** :heavy_multiplication_x: 
Screenshot 2023-08-28 at 11 40 19 AM

**After:** :heavy_check_mark:  
Screenshot 2023-08-28 at 11 50 19 AM

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests B2B and Functional Tests EE  build are green.Functional Tests CE failure are different on last two run.
Run1
Screenshot 2023-08-28 at 4 33 21 PM

Run2
37871-CE
