### PR TITLE
Issue with reorder when disabled reorder setting from admin issue25130

### LINKED ISSUE #25130: Issue with reorder when disabled reorder setting from admin
There is no check in reorder controller to validate the reorder configuration.

### Preconditions (*)

1. Magento 2.3.3

### Steps to reproduce (*)

1. Place order from frontend as a customer or guest
2. Open order view page from frontend
3. Login into admin panel
4. Disable reorder option from admin. Navigate to Store -> Configuration-> Sales -> Reorder -> Allow Order and set this to **NO**
5. Go to opened order view page and click on reorder.

Selection_011
Selection_009

### Expected result (*)

1. Reorder should be disabled and there should be some error message like Reorder is disabled

### Actual result (*)

1. Able to reorder. 
Selection_010

### PR DESCRIPTION
**Pull request by edenduong**
### Description (*)

1. Resolve magento/magento2#25130: Issue with reorder when disabled reorder setting from admin

### Fixed Issues (if relevant)

1. magento/magento2#25130: Issue with reorder when disabled reorder setting from admin

### Manual testing scenarios (*)

1. Place order from frontend as a customer or guest
2. Open order view page from frontend
3. Login into admin panel
4. Disable reorder option from admin. Navigate to Store -> Configuration-> Sales -> Reorder -> Allow Order and set this to **NO**
5. Go to opened order view page and click on reorder.

Selection_011
Selection_009

### Expected result (*)

1. Reorder should be disabled and there should be some error message Reorder is not available.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/Sales/Controller/AbstractController/Reorder.php [hunk 1]
```diff
@@ -4,16 +4,20 @@
...
 use Magento\Framework\Registry;
 use Magento\Framework\App\Action\HttpPostActionInterface;
+use Magento\Framework\App\ObjectManager;
+use Magento\Sales\Helper\Reorder as ReorderHelper;
 
 /**
  * Abstract class for controllers Reorder(Customer) and Reorder(Guest)
  *
- * @package Magento\Sales\Controller\AbstractController
+ * Class Magento\Sales\Controller\AbstractController\Reorder
```
Comment (lbajsarowicz) [inline app/code/Magento/Sales/Controller/AbstractController/Reorder.php]: You should remove that line (and the empty line above, too)

File: app/code/Magento/Sales/Controller/AbstractController/Reorder.php [hunk 2]
```diff
@@ -28,17 +32,27 @@ abstract class Reorder extends Action\Action implements HttpPostActionInterface
...
     public function __construct(
         Action\Context $context,
         OrderLoaderInterface $orderLoader,
-        Registry $registry
+        Registry $registry,
+        ReorderHelper $reorderHelper = null
     ) {
         $this->orderLoader = $orderLoader;
         $this->_coreRegistry = $registry;
+        $this->reorderHelper = $reorderHelper ?: ObjectManager::getInstance()->get(ReorderHelper::class);
```
Comment (lbajsarowicz) [inline app/code/Magento/Sales/Controller/AbstractController/Reorder.php:53]: :+1: for backward compatible DI.

File: app/code/Magento/Sales/Test/Unit/Controller/Guest/ReorderTest.php [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+                'orderLoader' => $this->orderLoaderMock,
+                'registry' => $this->registryMock
+            ]
+        );
+    }
+
+    /**
+     * Test execute() with the reorder is not allowed
+     */
+    public function testExecuteWithReorderIsNotAllowed()
```
Comment (lbajsarowicz) [inline app/code/Magento/Sales/Test/Unit/Controller/Guest/ReorderTest.php:114]: It's just recommendation to build test using the pattern:
* Given
* When
* Then

In your case:
```php
// Given
        $orderMock = $this->createMock(Order::class);
        $orderMock->method('getId')->willReturn(self::STUB_ORDER_ID);

        $this->orderLoaderMock->method('load')
            ->with($this->requestMock)
            ->willReturn($this->resultRedirectFactoryMock);

        $this->registryMock->expects($this->once())->method('registry')
            ->with('current_order')
            ->willReturn($orderMock);

// When
        $this->reorderHelperMock->method('canReorder')->with(self::STUB_ORDER_ID)
            ->willReturn(false);

// Then
        $resultRedirectMock = $this->createMock(Redirect::class);
        $this->resultRedirectFactoryMock->expects($this->once())->method('create')->willReturn($resultRedirectMock);
        $this->reorderHelperMock->method('canReorder')->with(self::STUB_ORDER_ID)
            ->willReturn(false);

        /** Expected Error Message */
        $this->messageManagerMock->expects($this->once())
            ->method('addErrorMessage')
            ->with('Reorder is not available.')->willReturnSelf();
        $resultRedirectMock->expects($this->once())
            ->method('setPath')
            ->with('checkout/cart')->willReturnSelf();

        /** Assert result */
        $this->assertEquals($resultRedirectMock, $this->reorder->execute());
```

I hope I haven't lost anything :-)

With such structure, it's easier to read tests, because you have clearly separated stuff that is responsible for preparing the context for test `Given`, the condition `When` and the assertions `Then`

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]

**Comment by edenduong** [comment]
@lbajsarowicz: I have changed the source code. Please check it again. Thanks :)

**Comment by edenduong** [comment]
Could you please take a look? Thanks @lbajsarowicz

**Review by lbajsarowicz — APPROVED** [review]
Thank you for your contribution.

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-6492](https://jira.corp.magento.com/browse/ENGCOM-6492) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

File: app/code/Magento/Sales/i18n/en_US.csv [hunk 4]
```diff
@@ -799,3 +799,5 @@ Refunds,Refunds
 "Allow Zero GrandTotal","Allow Zero GrandTotal"
 "Could not save the shipment tracking","Could not save the shipment tracking"
 "Please enter a coupon code!","Please enter a coupon code!"
+"Please enter a coupon code!","Please enter a coupon code!"
```
Comment (engcom-Alfa) [inline app/code/Magento/Sales/i18n/en_US.csv]: @edenduong Could you remove the duplicate phrase?

**Review by engcom-Alfa — CHANGES_REQUESTED** [review]
@edenduong See my comment

File: app/code/Magento/Sales/i18n/en_US.csv (hunk 4 above)
Comment (edenduong) [reply app/code/Magento/Sales/i18n/en_US.csv]: @engcom-Alfa: it is ok now. Thanks!

**Comment by edenduong** [comment]
> @edenduong See my comment

Thank you. Please check it again. @lbajsarowicz @engcom-Alfa

**Comment by engcom-Alfa** [comment]
@lbajsarowicz Could you review the last commit?

Thanks!

**Review by lbajsarowicz — APPROVED** [review]

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Comment by slavvka** [comment]
MHI failure (Global state usage defined at current file: Magento\Framework\Registry in Magento/Sales/Test/Unit/Controller/Guest/ReorderTest.php) is approved since it is mock for a dependency in the class
