### PR TITLE
Fixes for integration tests errors on PHP 8.1

### LINKED ISSUE #34568: [Magento OS] Fix fixtures for Integration Tests to be compatible with PHP 8.1
### Description (*)
We run builds on PHP 8.1 and have results provided below:
- Failed 298
- Broken 1672
- Passed 9915
- Skipped 179

Some problems related from wrong fixtures

### Related issue (*)
- Parent issue - magento/magento2#34567

### Expected result (*)

1. The count of failed and broken tests should be less then provided in description

### Actual result (*)

1. Current count of the failed and broken tests
- Failed 298
- Broken 1672
- Passed 9915
- Skipped 179

### PR DESCRIPTION
**Pull request by karyna-t**
### Description (*)
This PR adds fixes for the integration tests failures in fixtures (on PHP 8.1)

### Related Pull Requests
https://github.com/magento-commerce/magento2-infrastructure/pull/1624

### Fixed Issues
1. Fixes magento/magento2#34625

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Integration Tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Integration Tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by xmav** [comment]
@magento import pr to magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav an error occurred during the Pull Request import.

**Comment by andrewbess** [comment]
@magento run Unit Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Unit Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Integration Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by andrewbess** [comment]
@magento run Integration Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by andrewbess** [comment]
@magento run Integration Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by andrewbess** [comment]
@magento run Integration Tests with env PHP 8.1 with edition CE without extensions magento-commerce/inventory, magento-commerce/adobe-stock-integration, magento-commerce/security-package, magento-commerce/magento2-page-builder, magento-commerce/adobe-ims

**Comment by andrewbess** [comment]
@magento run Unit Tests, Integration Tests, Static Tests, WebAPI Tests, Semantic Version Checker with env PHP 8.1

**Comment by xmav** [comment]
@magento run all tests

**Comment by xmav** [comment]
@magento run all tests

**Comment by xmav** [comment]
@magento run static tests

**Comment by andrewbess** [comment]
@magento run Integration Tests with env PHP 8.1 without extensions magento-commerce/magento2-page-builder

**Comment by andrewbess** [comment]
@magento run Integration Tests with env PHP 8.1 with extensions magento-trigger/magento2-infrastructure:php81 without extensions magento-commerce/magento2-page-builder

**Comment by andrewbess** [comment]
@magento run Integration Tests, Unit Tests with env PHP 8.1 without extensions magento-commerce/magento2-page-builder

**Comment by karyna-tsymbal-atwix** [comment]
@magento run all tests

**Comment by karyna-tsymbal-atwix** [comment]
@magento run Integration Tests, Unit Tests with env PHP 8.1 without extensions magento-commerce/magento2-page-builder

File: dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php [hunk 1]
```diff
@@ -34,6 +34,37 @@ protected function tearDown(): void
...
+        $adapter->insert($tableName, [$columnId => 100]);
+
+        $select = $adapter->select()
+            ->from($tableName)
+            ->columns([$columnId])
+            ->limit(1);
+        $result = $adapter->fetchOne($select);
+
+        $isStringify = $adapter->getConfig()['driver_options'][\PDO::ATTR_STRINGIFY_FETCHES] ?? null;
+        if ($isStringify || $isStringify === null) {
```
Comment (xmav) [inline dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php]: few notes here:
- it is generally bad practice to have checks wrapped in conditional statement. It is good sign that you need to have two tests or use data provider
- Am I right that `PDO::ATTR_STRINGIFY_FETCHES` always will be true in this test ?(I don't see that we update config in test).

**Review by xmav — CHANGES_REQUESTED** [review]

File: dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php (hunk 1 above)
Comment (karyna-t) [reply dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php]: @xmav  It will always be true, but I think we'll have a possibility to pass 'false' when we add --db-stringify-fetches option for bin/install.
I can remove that condition if we're not going to add the option in the future.

Comment (xmav) [reply dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php]: yes please. remove it from this test. Config could be passed without extra method thought `__construct`
I would suggest to have test to verify that value set in code could be overwritten from config. May be `dev/tests/integration/testsuite/Magento/Framework/Model/ResourceModel/Type/Db/Pdo/MysqlTest.php` will be good place for this test

**Review by andrewbess — APPROVED** [review]

**Comment by andrewbess** [comment]
Hello @xmav 
The test has been fixed.
Could you please check it?
Thank you in advance.

File: dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php (hunk 1 above)
Comment (andrewbess) [reply dev/tests/integration/testsuite/Magento/Framework/DB/Adapter/Pdo/MysqlTest.php]: Hello @xmav 
Fixed, please check.
Thank you in advance

**Comment by xmav** [comment]
@magento run all tests

**Comment by xmav** [comment]
@magento import code to Magento-trigger/magento2ce

**Comment by m2-github-services** [comment]
@xmav the branch with the code is successfully imported into the `Magento-trigger/magento2ce` repository. Branch name: `imported-karyna-tsymbal-atwix-magento2-34575`.

**Comment by xmav** [comment]
Unit tests failure is expected on platform-health branch
FT build contain "random" failures and will be re-checked during delivery process
