### PR TITLE
Fix SQL query quoting/casting when type is passed to where function

### LINKED ISSUE #29590: [Issue] Fix SQL query quoting/casting when type is passed to where function
This issue is automatically created based on existing pull request: magento/magento2#27980: Fix SQL query quoting/casting when type is passed to where function

---------
Framework/DB/Select where function doesn't handle the "type" correctly.

### Preconditions (*)
The $type variable can be both string or int, so before comparing it to
'TYPE_CONDITION' string it has to be casted to avoid comparing integer zero
with string (0 == 'TYPE_CONDITION') which will wrongly return true,
and remove the information about type.

Pass type provided to where function down the chain to allow automatic
casting of arrays of values e.g. to int.

This fixes following cases:
1)
$select-->where('attr_table.store_id IN (?)', $storeIds, Zend_Db::INT_TYPE);
2)
$select-->where('attr_table.store_id = ?', $storeId, Zend_Db::INT_TYPE);
In both cases now passed value is correctly casted to int
(either single value, or each value from array)

### Steps to reproduce:

1. Make custom select like
`$select->from(['catalog_product_entity'], '*')->where('entity_id in (?)', ['1', 2, 3], \Zend_Db::INT_TYPE);`
2. Check sql
`$select->__toString()`

### Expected result (*)
SELECT `catalog_product_entity`.* FROM `catalog_product_entity` WHERE (entity_id in `(1, 2, 3)`);

### Actual result (*)
SELECT `catalog_product_entity`.* FROM `catalog_product_entity` WHERE (entity_id in `('1', 2, 3)`);

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by tmotyl**
Framework/DB/Select where function doesn't handle the "type" correctly.

### Description (*)
The $type variable can be both string or int, so before comparing it to
'TYPE_CONDITION' string it has to be casted to avoid comparing integer zero
with string (0 == 'TYPE_CONDITION') which will wrongly return true,
and remove the information about type.

Pass type provided to where function down the chain to allow automatic
casting of arrays of values e.g. to int.

This fixes following cases:
1)
$select-->where('attr_table.store_id IN (?)', $storeIds, Zend_Db::INT_TYPE);
2)
$select-->where('attr_table.store_id = ?', $storeId, Zend_Db::INT_TYPE);
In both cases now passed value is correctly casted to int
(either single value, or each value from array)

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Make custom select like
`$select->from(['catalog_product_entity'], '*')->where('entity_id in (?)', ['1', 2, 3], \Zend_Db::INT_TYPE);`
2. Check sql
`$select->__toString()`

### Expected result (*)
SELECT `catalog_product_entity`.* FROM `catalog_product_entity` WHERE (entity_id in `(1, 2, 3)`);

### Actual result (*)
SELECT `catalog_product_entity`.* FROM `catalog_product_entity` WHERE (entity_id in `('1', 2, 3)`);

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#29590: Fix SQL query quoting/casting when type is passed to where function

### CODE REVIEW

**Comment by tmotyl** [comment]
The test failures are unrelated to the change "MySQL server has gone away". Can somebody restart the tests?

**Comment by ihor-sviziev** [comment]
Related to https://github.com/magento/magento2/pull/27129 as it also partically doing the same.

File: lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php [hunk 1]
```diff
@@ -1475,10 +1475,10 @@ public function select()
      * Method revrited for handle empty arrays in value param
      *
      * @param string $text The text with a placeholder.
-     * @param mixed $value The value to quote.
-     * @param string $type OPTIONAL SQL datatype
+     * @param array|null|int|string|float|\Zend_Db_Expr|\Zend_Db_Select|\DateTimeInterface $value The value to quote.
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php]: I'd like to use `\Magento\Framework\DB\Sql\Expression` instead of `\Zend_Db_Expr` and `\Magento\Framework\DB\Select` instead of `\Zend_Db_Select` in order to have an ability to replace ZF1 implementation in future.
```suggestion
     * @param array|null|int|string|float|\Magento\Framework\DB\Sql\Expression|\Magento\Framework\DB\Select|\DateTimeInterface $value The value to quote.
```
Also would be good to import it, but github UI don't provide ability to do it

File: lib/internal/Magento/Framework/DB/Select.php [hunk 2]
```diff
@@ -107,19 +107,19 @@ public function __construct(
      * </code>
      *
      * @param string $cond The WHERE condition.
-     * @param string|array|null $value OPTIONAL An optional single or array value to quote into the condition.
-     * @param string|int|null $type OPTIONAL The type of the given value
+     * @param array|null|int|string|float|\Zend_Db_Expr|\Zend_Db_Select|\DateTimeInterface $value The value to quote.
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/DB/Select.php]:
```suggestion
     * @param array|null|int|string|float|\Magento\Framework\DB\Sql\Expression|\Magento\Framework\DB\Select|\DateTimeInterface $value The value to quote.
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by tmotyl** [comment]
> Related to #27129 as it also partically doing the same.

yes, I believe this patch is prerequisite to the other, as without it types for array are not interpreted correctly

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by tmotyl** [comment]
hmm these test failures look unrelated to the change

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @tmotyl,
Please fix static tests. All others are passing now

**Comment by tmotyl** [comment]
The static tests are failing that the line 
```
     * @param array|null|int|string|float|\Magento\Framework\DB\Sql\Expression|\Magento\Framework\DB\Select|\DateTimeInterface $value The value to quote.
```
is too long.
I can either add a use statement on top of the file and shorter the types in doc comment, or add //phpcs:ignore
Whatever your prefer.

**Comment by ihor-sviziev** [comment]
@tmotyl I think `mixed` there will be just more suitable, as potentially any object with '__toString()" method could be passed there. Is it make sense?

**Comment by tmotyl** [comment]
I can put mixed as it was before.
I just think mixed is not helpful neither for humans nor for static code analysis tools.
All these types have special handling somewhere in the function (or parent function) this is why 
I think its beneficial to have them specified explicitly.
Otherwise developer who want to pass value to where don't know what type can be passed into and have to dig through multiple levels of code until he finds it.

Please make the decision, I will follow it. I do not want to spend too much time on secondary topic in this patch.

**Comment by ihor-sviziev** [comment]
@tmotyl ok, make sense. Could you try to import Expression and Select classes? I think it should fit the limit

**Comment by tmotyl** [comment]
thanks, done

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Looks good. Failed Integration Tests & SVC looks false positive.

Will put this PR on hold till https://github.com/magento/magento2/pull/27129 will be merged as it contains similar changes and might have conflict between these PRs.

**Comment by kandy** [comment]
~/w/perf ❯❯❯ bin/mysql                                                                                                                                                 master ✭ ✖ ✱ ◼
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 28
Server version: 10.3.18-MariaDB-1:10.3.18+maria~bionic mariadb.org binary distribution

bash-5.0# bin/magento indexer:reset catalog_category_product &&  bin/magento indexer:reindex  catalog_category_product
Category Products indexer has been invalidated.
Category Products index has been rebuilt successfully in 00:02:24
Catalog Search index has been rebuilt successfully in 00:01:10

**Comment by sidolov** [comment]
@magento create issue

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8022](https://jira.corp.magento.com/browse/ENGCOM-8022) has been created to process this Pull Request

**Comment by magento-engcom-team** [comment]
@tmotyl thank you for contributing. Please accept Community Contributors team invitation [here](https://github.com/orgs/magento/invitation) to gain extended permissions for this repository.

**Comment by tmotyl** [comment]
@magento-engcom-team done

**Comment by engcom-Charlie** [comment]
:heavy_check_mark: QA Passed
Checked by the following steps, the results are the same:
1. Make custom select like
`$select->from(['catalog_product_entity'], '*')->where('entity_id in (?)', ['1', 2, 3], \Zend_Db::INT_TYPE);`
2. Check sql
`$select->__toString()`

before :heavy_multiplication_x::
SELECT `catalog_product_entity`.* FROM `catalog_product_entity` WHERE (entity_id in `('1', 2, 3)`);

after :heavy_check_mark::
SELECT `catalog_product_entity`.* FROM `catalog_product_entity` WHERE (entity_id in `(1, 2, 3)`);

**Comment by ihor-sviziev** [comment]
Would like to add that basically the same changes were already added as part of https://github.com/magento/magento2/pull/27129, so this PR will introduce phpdoc cleanup only.

**Comment by engcom-Charlie** [comment]
@magento run all tests

**Comment by engcom-Charlie** [comment]
@magento run all tests
