### PR TITLE
Disable captcha storefont config still load captcha js files

### LINKED ISSUE #32987: Disable captcha storefont config still load captcha js files
**Preconditions (*)**

- Magento Version - 2.4.2
- Default Magento Theme
- Captcha is disabled on Frontend 

**Steps to reproduce (*)**
- Do fresh Magento install - with or without demo Data
- Open developer tool, goto network tab
- Here you will see, unwanted js call for captcha  
image

**Expected result (*)**
- No Captcha related scripts should be called 

**My expected** 

- we don't need disable completely captcha module but if admin owner set config disable in backend both captcha blocks and js related may not visible in frontend

**Actual result (*)**
- 11 extra request of size 17.2 kB is getting called on page

### PR DESCRIPTION
**Pull request by rogerdz**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32987

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+    /**
+     * Remove template when loggin or disable captcha storefront
+     *
+     * @param AuthenticationPopup $subject
+     * @param string $result
+     * @return string
+     *
+     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
+     */
+    public function afterGetTemplate(
```
Comment (engcom-Hotel) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: Please specify return type declaration.

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+        AuthenticationPopup $subject,
+        $result
```
Comment (engcom-Hotel) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: Please add parameter type declaration.

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+
+        return $result;
+    }
+
+    /**
+     * Is logged in
+     *
+     * @return bool
+     */
+    private function isLoggedIn()
```
Comment (engcom-Hotel) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: Please specify return type declaration.

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+    public function __construct(
+        HelperCaptcha $helper,
+        HttpContext $httpContext
+    ) {
+        $this->helper = $helper;
+        $this->httpContext = $httpContext;
+    }
+
+    /**
+     * Remove template when loggin or disable captcha storefront
```
Comment (engcom-Hotel) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: Correct the typo from `loggin` to `login`

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+    private $httpContext;
+
+    /**
+     * CheckCaptchaOnStorefront constructor
+     *
+     * @param HelperCaptcha $helper
+     * @param HttpContext $httpContext
+     */
+    public function __construct(
+        HelperCaptcha $helper,
```
Comment (engcom-Hotel) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: Use [readonly](https://php.watch/versions/8.1/readonly#constructor-readonly) property here

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rogerdz,

Thank you for the contribution!

Please address the review comments mentioned below.Additionally it appears that the failed integration and static tests are caused by the changes in this PR. 

Kindly resolve those as well.

**Comment by rogerdz** [comment]
> Hello @rogerdz,
> 
> Thank you for the contribution!
> 
> Please address the review comments mentioned below.Additionally it appears that the failed integration and static tests are caused by the changes in this PR.
> 
> Kindly resolve those as well.

not yet, please fix your composer repo first
image

**Comment by engcom-Hotel** [comment]
Hello @rogerdz,

This is a known issue and there is an ongoing discussion on this [here](https://magentocommeng.slack.com/archives/C7KB93M32/p1736933306053669). Please refer to this chat for further information.

In the meantime, do you want us to continue with this PR, or should we wait for the composer-related issue to be fixed and then you continue to work on this issue?

Thanks

**Comment by rogerdz** [comment]
> do you want us to continue with this PR

Yes, thank you.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Integration Tests, Static Tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+
+    /**
+     * Is logged in
+     *
+     * @return bool
+     */
+    private function isLoggedIn(): ?bool
+    {
+        return $this->httpContext->getValue(Context::CONTEXT_AUTH);
+    }
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: I guess this check should be in the original class `\Magento\Customer\Block\Account\AuthenticationPopup`, or in the template file `Magento_Customer::account/authentication-popup.phtml`.

File: app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php [hunk 7]
```diff
@@ -0,0 +1,71 @@
...
+        AuthenticationPopup $subject,
+        ?string $result
+    ): string {
+        // Check the value for recaptcha_frontend/type_for/customer_login
+        $recaptchaType = $this->scopeConfig->getValue(
+            'recaptcha_frontend/type_for/customer_login',
+            ScopeInterface::SCOPE_WEBSITE
+        );
+
+        if ($this->isLoggedIn() || (!$this->helper->getConfig('enable') && $recaptchaType === null)) {
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/Plugin/CheckCaptchaOnStorefront.php]: I guess the logic about enabled form for custom login should be added at place, where we configure captcha fields in the customer login form.

I checked - currently it's configured using layout XML, so I guess it has to be moved from XML to some PHP code that will add needed parameters. https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml#L12-L56

----

I guess it should be something like this:

https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Checkout/Block/Onepage.php#L78-L85
https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Paypal/etc/frontend/di.xml#L197-L203
https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Paypal/Block/PayLater/LayoutProcessor.php#L20-L68

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @rogerdz @engcom-Hotel,
I believe the captcha module should not affect customer functionality. It is better to adjust the original functionality rather than introduce new plugins.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Customer/Block/Account/AuthenticationPopup.php [hunk 8]
```diff
@@ -24,21 +27,29 @@ class AuthenticationPopup extends \Magento\Framework\View\Element\Template
...
      * @param \Magento\Framework\Serialize\Serializer\Json|null $serializer
+     * @param HttpContext $httpContext
      * @throws \RuntimeException
      */
     public function __construct(
         \Magento\Framework\View\Element\Template\Context $context,
         array $data = [],
-        ?\Magento\Framework\Serialize\Serializer\Json $serializer = null
+        ?\Magento\Framework\Serialize\Serializer\Json $serializer = null,
+        HttpContext $httpContext = null
```
Comment (hostep) [inline app/code/Magento/Customer/Block/Account/AuthenticationPopup.php]: Can we update this type so it's explicitly nullable, this is a requirement for PHP 8.4 to not get deprecation errors.
So change `HttpContext` to `?HttpContext` please. Thanks! :) 

----

Wierd that static tests don't see this, or don't we check on PHP 8.4 compatibility yet?

_Update_, found reasons why:
- phpstan only complains about this when we execute it with PHP 8.4 and not with PHP 8.3, which kind of makes sense, so should we start running phpstan with all the versions of PHP supported in the codebase in the future?
- the PHPCompatibility ruleset from magento-coding-standards is very outdated, I've opened a new issue here about it: https://github.com/magento/magento-coding-standard/issues/491

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+    ) {
+    }
+
+    /**
+     * Remove captcha from checkout page if it is disabled
+     *
+     * @param array $jsLayout
+     * @return array
+     */
+    public function process($jsLayout): array
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php]:
```suggestion
    public function process(array $jsLayout): array
```

File: app/code/Magento/Customer/Block/Account/AuthenticationPopup.php [hunk 10]
```diff
@@ -48,6 +59,16 @@ public function __construct(
...
     {
+        // Check if captcha is not enabled and user is not logged in
+        if (!$this->_scopeConfig->getValue(
+            Form::XML_PATH_CUSTOMER_CAPTCHA_ENABLED,
+            ScopeInterface::SCOPE_STORE
+        ) && !$this->isLoggedIn()) {
+            if (isset($this->jsLayout['components']['authenticationPopup']['children']['captcha'])) {
+                unset($this->jsLayout['components']['authenticationPopup']['children']['captcha']);
+            }
+        }
```
Comment (ihor-sviziev) [inline app/code/Magento/Customer/Block/Account/AuthenticationPopup.php]: The logic you've just added is related to the captha extension, as it's added in that module in https://github.com/magento/magento2/blob/df37b871ebd2a7e23ae6dec8c084855a65fbcab1/app/code/Magento/Captcha/view/frontend/layout/default.xml#L10-L27

I would suggest doing the following:
1. add layoutProcessors as optional array option to constructor
2. Adjust getJsLayout function to something like this
```suggestion
        foreach ($this->layoutProcessors as $processor) { 
            $this->jsLayout = $processor->process($this->jsLayout); 
        }
```
This will make code as close as possible to https://github.com/magento/magento2/blob/c5614048eaaff80c1d4786b391e0c3cc55c7417c/app/code/Magento/Checkout/Block/Onepage.php#L78-L85
3. In the Capcha extension, create own layout processor for AuthenticationPopup and **add** all needed parameters through this class + remove the configuration code from layout.xml

**OR**
Do some plugin for this specific method in the captcha extension, and add needed parameters based on the configuration

File: app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php [hunk 11]
```diff
@@ -0,0 +1,48 @@
...
+                ['shippingAddress']['children']['customer-email']['children']['additional-login-form-fields']
+                ['children']['captcha'])) {
+                unset($jsLayout['components']['checkout']['children']['steps']['children']['shipping-step']['children']
+                    ['shippingAddress']['children']['customer-email']['children']['additional-login-form-fields']
+                    ['children']['captcha']);
+            }
+            if (isset($jsLayout['components']['authenticationPopup']['children']['captcha'])) {
+                unset($jsLayout['components']['authenticationPopup']['children']['captcha']);
+            }
+        }
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php]: I would suggest adding needed parameters rather than removing them (move from layout.xml), similar to 
https://github.com/magento/magento2/blob/b25fc6f39f584d527745b9d0149c5018c6854d9d/app/code/Magento/Paypal/Block/PayLater/LayoutProcessor.php#L70-L105

File: app/code/Magento/Customer/Block/Account/AuthenticationPopup.php [hunk 12]
```diff
@@ -48,6 +59,16 @@ public function __construct(
      */
     public function getJsLayout()
     {
+        // Check if captcha is not enabled and user is not logged in
+        if (!$this->_scopeConfig->getValue(
+            Form::XML_PATH_CUSTOMER_CAPTCHA_ENABLED,
+            ScopeInterface::SCOPE_STORE
+        ) && !$this->isLoggedIn()) {
```
Comment (ihor-sviziev) [inline app/code/Magento/Customer/Block/Account/AuthenticationPopup.php]: I don't think it can be related to whether the customer logged in or not. I would expect that this entire block won't be rendered then, but that's a separate issue.

File: app/code/Magento/Captcha/etc/frontend/di.xml [hunk 13]
```diff
@@ -37,4 +37,12 @@
     <type name="Magento\Sales\Api\OrderManagementInterface">
         <plugin name="reset_payment_attempts_after_order_is_placed_plugin" type="Magento\Captcha\Plugin\ResetPaymentAttemptsAfterOrderIsPlacedPlugin"/>
     </type>
+
+    <type name="Magento\Checkout\Block\Onepage">
+        <arguments>
+            <argument name="layoutProcessors" xsi:type="array">
+                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\CaptchaLayoutProcessor</item>
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/etc/frontend/di.xml]: I guess from the capthca module perspective, it's more "CheckoutLayoutProcessor" than "CaptchaLayoutProcessor".

File: app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php (hunk 9 above)
Comment (engcom-Hotel) [reply app/code/Magento/Captcha/Block/CaptchaLayoutProcessor.php]: Add `array` here showing error in PHPStorm because the interface doesn’t have this declaration. The error shown in PHPStorm is as follows:
image

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests EE, Functional Tests B2B

File: app/code/Magento/Captcha/view/frontend/layout/default.xml [hunk 14]
```diff
@@ -13,12 +13,7 @@
                     <item name="components" xsi:type="array">
                         <item name="authenticationPopup" xsi:type="array">
                             <item name="children" xsi:type="array">
-                                <item name="captcha" xsi:type="array">
-                                    <item name="component" xsi:type="string">Magento_Captcha/js/view/checkout/loginCaptcha</item>
-                                    <item name="displayArea" xsi:type="string">additional-login-form-fields</item>
-                                    <item name="formId" xsi:type="string">user_login</item>
-                                    <item name="configSource" xsi:type="string">checkout</item>
-                                </item>
+
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/view/frontend/layout/default.xml]: I guess we can remove this file now, and the result will be the same as the child element configured in the PHP file now, right?

File: app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml [hunk 15]
```diff
@@ -15,12 +15,7 @@
                             <item name="children" xsi:type="array">
                                 <item name="authentication" xsi:type="array">
                                     <item name="children" xsi:type="array">
-                                        <item name="captcha" xsi:type="array">
-                                            <item name="component" xsi:type="string">Magento_Captcha/js/view/checkout/loginCaptcha</item>
-                                            <item name="displayArea" xsi:type="string">additional-login-form-fields</item>
-                                            <item name="formId" xsi:type="string">user_login</item>
-                                            <item name="configSource" xsi:type="string">checkoutConfig</item>
-                                        </item>
+
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml]: I guess we can remove this file now, and the result will be the same as the child element configured in the PHP file now, right?

File: app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml [hunk 16]
```diff
@@ -33,12 +28,7 @@
                                                             <item name="children" xsi:type="array">
                                                                 <item name="additional-login-form-fields" xsi:type="array">
                                                                     <item name="children" xsi:type="array">
-                                                                        <item name="captcha" xsi:type="array">
-                                                                            <item name="component" xsi:type="string">Magento_Captcha/js/view/checkout/loginCaptcha</item>
-                                                                            <item name="displayArea" xsi:type="string">additional-login-form-fields</item>
-                                                                            <item name="formId" xsi:type="string">user_login</item>
-                                                                            <item name="configSource" xsi:type="string">checkoutConfig</item>
-                                                                        </item>
+
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/view/frontend/layout/checkout_index_index.xml]: same here, it's not adding any value

File: app/code/Magento/Captcha/etc/frontend/di.xml [hunk 17]
```diff
@@ -37,4 +37,18 @@
     <type name="Magento\Sales\Api\OrderManagementInterface">
         <plugin name="reset_payment_attempts_after_order_is_placed_plugin" type="Magento\Captcha\Plugin\ResetPaymentAttemptsAfterOrderIsPlacedPlugin"/>
     </type>
+    <type name="Magento\Checkout\Block\Onepage">
+        <arguments>
+            <argument name="layoutProcessors" xsi:type="array">
+                <item name="checkout_processor" xsi:type="object">Magento\Captcha\Block\CheckoutLayoutProcessor</item>
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/etc/frontend/di.xml]: In terms of checkout onepage block, it's more related to captaha, so let's change the name here
```suggestion
                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\CheckoutLayoutProcessor</item>
```

File: app/code/Magento/Captcha/etc/frontend/di.xml [hunk 18]
```diff
@@ -37,4 +37,18 @@
...
+            </argument>
+        </arguments>
+    </type>
+    <type name="Magento\Customer\Block\Account\AuthenticationPopup">
+        <arguments>
+            <argument name="layoutProcessors" xsi:type="array">
+                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\Checkout\LayoutProcessor</item>
```
Comment (ihor-sviziev) [inline app/code/Magento/Captcha/etc/frontend/di.xml]: The current name of the class is quite confusing:
- it's almost the same as  `Magento\Captcha\Block\CheckoutLayoutProcessor`, the differnce is the only one bachslash
- It's not linked anyhow to customer and to authentication popup
So I'm suggesting renaming the class/namespace + update it in di.xml to have something like this
```suggestion
                <item name="captcha_processor" xsi:type="object">Magento\Captcha\Block\Customer\AuthenticationPopup\LayoutProcessor</item>
```

File: app/code/Magento/Customer/Block/Account/AuthenticationPopup.php [hunk 19]
```diff
@@ -24,21 +27,37 @@ class AuthenticationPopup extends \Magento\Framework\View\Element\Template
...
+     * @param HttpContext $httpContext
+     * @param array $layoutProcessors
      * @throws \RuntimeException
      */
     public function __construct(
         \Magento\Framework\View\Element\Template\Context $context,
         array $data = [],
-        ?\Magento\Framework\Serialize\Serializer\Json $serializer = null
+        ?\Magento\Framework\Serialize\Serializer\Json $serializer = null,
+        ?HttpContext $httpContext = null,
```
Comment (ihor-sviziev) [inline app/code/Magento/Customer/Block/Account/AuthenticationPopup.php]: this parameter isn't used anymore, pls remove

File: app/code/Magento/Customer/Model/Form.php [hunk 20]
```diff
@@ -15,7 +15,7 @@ class Form extends \Magento\Eav\Model\Form
      * XML configuration paths for "Disable autocomplete on storefront" property
      */
     public const XML_PATH_ENABLE_AUTOCOMPLETE = 'customer/password/autocomplete_on_storefront';
-
+
```
Comment (ihor-sviziev) [inline app/code/Magento/Customer/Model/Form.php]: Pls revert this change
```suggestion

```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/Customer/Block/Account/AuthenticationPopup.php [hunk 21]
```diff
@@ -24,21 +27,34 @@ class AuthenticationPopup extends \Magento\Framework\View\Element\Template
      */
     private $serializer;
 
+    /**
+     * @var HttpContext
+     */
+    private $httpContext;
+
```
Comment (ihor-sviziev) [inline app/code/Magento/Customer/Block/Account/AuthenticationPopup.php]:
```suggestion
```

**Review by ihor-sviziev — APPROVED** [review]

**Comment by engcom-Hotel** [comment]
Hello @ihor-sviziev,

Thanks for approving the PR. Moving it to `ready for testing` bucket.

@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Unit Tests
