### PR TITLE
Extracted logic from wysiwyg OnInsert controller to a model

### LINKED ISSUE #1504: Typo / unneccessary string in billing input elements?
Before the new checkout came in, all billing checkout elements had the name of
billingAddress[*name*]
However right now an extra bit dropped in for all elements.
For example,
billingAddresscheckmo[postcode]
Is this intentional or a typo?

### LINKED ISSUE #1504: Insert rendition images to the content from media gallery instead of original images
### Story

https://github.com/magento/adobe-stock-integration/issues/1286

### Precoditions
1. Magento2 2.4-develop with ASI 2.1-develop is installed
2. Enhanced Media Gallery is enabled in `Stores Configuration -> Advanced -> System -> Media Gallery` fieldset
3. Rendition width and height are set in `Stores Configuration -> Advanced -> System -> Media Gallery Renditions` fieldset

### Steps to reproduce:
1. Upload an image that is higher/wider than the configured rendition width/height to the media gallery
2. Insert the image to the content

### Expected result
 - The rendition of the image instead of the original image should be inserted (from `.renditions` directory)
 - The rendition height/width should be reduced not to exceed configured rendition width and height
 - The rendition of the image should keep the original image aspect ratio
 - Used in information should be updated accordingly and displayed in the `Image Details` panel of media gallery

### PR DESCRIPTION
**Pull request by jmonteros422**
### Description (*)
This PR Extracts logic from Magento\Cms\Controller\Adminhtml\Wysiwyg\Images\OnInsert::execute() controller to Magento\Cms\Model\Wysiwyg\Images\PrepareImage::execute() model

### Dependent ASI Pull Request
PR: https://github.com/magento/adobe-stock-integration/pull/1756

### Fixed Issues
Fixes magento/adobe-stock-integration#1504: [2.1-develop] Insert rendition images to the content from media gallery instead of original images

### CODE REVIEW

**Comment by jmonteros422** [comment]
@magento run all tests

File: app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php [hunk 1]
```diff
@@ -13,17 +13,25 @@ class OnInsert extends \Magento\Cms\Controller\Adminhtml\Wysiwyg\Images
...
      * @param \Magento\Framework\Registry $coreRegistry
      * @param \Magento\Framework\Controller\Result\RawFactory $resultRawFactory
+     * @param \Magento\Cms\Model\Wysiwyg\Images\PrepareImage $prepareImage
      */
     public function __construct(
         \Magento\Backend\App\Action\Context $context,
         \Magento\Framework\Registry $coreRegistry,
-        \Magento\Framework\Controller\Result\RawFactory $resultRawFactory
+        \Magento\Framework\Controller\Result\RawFactory $resultRawFactory,
+        \Magento\Cms\Model\Wysiwyg\Images\PrepareImage $prepareImage
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php]: Please add the constructor dependency in a backwards-compatible way.

See "Adding a constructor parameter" section of https://devdocs.magento.com/contributor-guide/backward-compatible-development/

File: app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+ */
+
+declare(strict_types=1);
+
+namespace Magento\Cms\Model\Wysiwyg\Images;
+
+use Magento\Catalog\Helper\Data;
+use Magento\Cms\Helper\Wysiwyg\Images as ImagesHelper;
+
+class PrepareImage
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php]: Let's make the class name more meaningful
```suggestion
class GetInsertImageContent
```

File: app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php [hunk 3]
```diff
@@ -13,17 +13,25 @@ class OnInsert extends \Magento\Cms\Controller\Adminhtml\Wysiwyg\Images
      */
     protected $resultRawFactory;
 
+    /**
+     * @var \Magento\Cms\Model\Wysiwyg\Images\PrepareImage
+     */
+    protected $prepareImage;
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php]:
```suggestion
    protected $getInsterImageContent;
```

File: app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php [hunk 4]
```diff
@@ -34,26 +42,10 @@ public function __construct(
...
-        $this->_objectManager->get(\Magento\Catalog\Helper\Data::class)->setStoreId($storeId);
-        $imagesHelper->setStoreId($storeId);
-
-        if ($forceStaticPath) {
-            $image = parse_url($imagesHelper->getCurrentUrl() . $filename, PHP_URL_PATH);
-        } else {
-            $image = $imagesHelper->getImageHtmlDeclaration($filename, $asIs);
-        }
+        /** @var \Magento\Cms\Model\Wysiwyg\Images\PrepareImage $image */
+        $image = $this->prepareImage->execute($request->getParams());
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php]: I'd avoid one-use variables like `$image`

File: app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php [hunk 5]
```diff
@@ -34,26 +42,10 @@ public function __construct(
...
-
-        $this->_objectManager->get(\Magento\Catalog\Helper\Data::class)->setStoreId($storeId);
-        $imagesHelper->setStoreId($storeId);
-
-        if ($forceStaticPath) {
-            $image = parse_url($imagesHelper->getCurrentUrl() . $filename, PHP_URL_PATH);
-        } else {
-            $image = $imagesHelper->getImageHtmlDeclaration($filename, $asIs);
-        }
+        /** @var \Magento\Cms\Model\Wysiwyg\Images\PrepareImage $image */
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php]: Incorrect and not necessary annotation. `$image` is a string and that is already defined as a return type of called method

File: app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+    }
+
+    /**
+     * @param array $data
+     * @return string
+     */
+    public function execute(array $data): string
+    {
+        $filename = $this->imagesHelper->idDecode($data['filename']);
+        $storeId = (int)$data['store_id'];
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php]: Store id value was previously retrieved from `store` field

File: app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php [hunk 7]
```diff
@@ -0,0 +1,60 @@
...
+    ) {
+        $this->imagesHelper = $imagesHelper;
+        $this->catalogHelper = $catalogHelper;
+    }
+
+    /**
+     * @param array $data
+     * @return string
+     */
+    public function execute(array $data): string
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php]: It's better to have the meaningful parameters:
```suggestion
    public function execute(string $endcodedFilename, int $storeId, bool $forceStaticPath, bool $renderAsTag): string
```

File: app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+    {
+        $filename = $this->imagesHelper->idDecode($data['filename']);
+        $storeId = (int)$data['store_id'];
+
+        $this->catalogHelper->setStoreId($storeId);
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php]: Can you please check why this call to catalog helper is needed.

File: app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php [hunk 9]
```diff
@@ -0,0 +1,60 @@
...
+        $this->imagesHelper->setStoreId($storeId);
+
+        if ($data['force_static_path']) {
+            // phpcs:ignore Magento2.Functions.DiscouragedFunction
+            $image = parse_url($this->imagesHelper->getCurrentUrl() . $filename, PHP_URL_PATH);
+        } else {
+            $image = $this->imagesHelper->getImageHtmlDeclaration($filename, $data['as_is']);
+        }
+
+        return $image;
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php]: Possible to remove unnecessary variable and simplify the code
```suggestion
        if ($data['force_static_path']) {
            // phpcs:ignore Magento2.Functions.DiscouragedFunction
            return parse_url($this->imagesHelper->getCurrentUrl() . $filename, PHP_URL_PATH);
        }

        return $this->imagesHelper->getImageHtmlDeclaration($filename, $data['as_is']);
```

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the pull request @jmonteros422 ! Please see my comments.

I have removed the information about relation from this PR as it can be processed independently, ASI PR should still keep the relation information (until this PR is merged)

Also please cover the extracted model with an integration test

**Comment by jmonteros422** [comment]
@magento run all tests

File: app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php (hunk 8 above)
Comment (jmonteros422) [reply app/code/Magento/Cms/Model/Wysiwyg/Images/PrepareImage.php]: @sivaschenko , did a check on different store view with and without that call and seems to not change anything on the rendered text in the content. I just included it on the model to not miss anything out from the original class. Let me know your thoughts.

**Comment by jmonteros422** [comment]
@magento run all tests

File: app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php [hunk 10]
```diff
@@ -34,29 +43,18 @@ public function __construct(
...
-        }
+        $data = $this->getRequest()->getParams();
 
         /** @var \Magento\Framework\Controller\Result\Raw $resultRaw */
         $resultRaw = $this->resultRawFactory->create();
-        return $resultRaw->setContents($image);
+
+        return $resultRaw->setContents(
+            $this->getInsertImageContent->execute(
+                $data['filename'],
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php:56]: I think it would be good to add the parameter names to a constant (constant names should help with the readability of the code)

File: app/code/Magento/Cms/Model/Wysiwyg/Images/GetInsertImageContent.php [hunk 11]
```diff
@@ -0,0 +1,70 @@
...
+     */
+    public function execute(
+        string $encodedFilename,
+        bool $forceStaticPath,
+        bool $renderAsTag,
+        ?int $storeId = null
+    ): string {
+        $filename = $this->imagesHelper->idDecode($encodedFilename);
+
+        $this->catalogHelper->setStoreId($storeId);
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Model/Wysiwyg/Images/GetInsertImageContent.php:53]: I don't see the reason to set stored to catalog helper here. Considering your investigation this call can be removed

File: app/code/Magento/Cms/Test/Integration/Model/Wysiwyg/Images/GetInsertImageContentTest.php [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+        ?int $storeId = null
+    ): void {
+        $getImageForInsert = $this->getInsertImageContent->execute(
+            $encodedFilename,
+            $forceStaticPath,
+            $renderAsTag,
+            $storeId
+        );
+
+        if (!$forceStaticPath) {
```
Comment (sivaschenko) [inline app/code/Magento/Cms/Test/Integration/Model/Wysiwyg/Images/GetInsertImageContentTest.php]: The goal of the test is to verify the correct return from the model based on the input parameters.
Instead of keeping complex logic in the test, I'd pass the expected result from the data provider. That should simplify the test to one-line `$this->assertEquals($expectedResult, this->getInsertImageContent->execute(<params>)`.

Having the expected result in the data provider will also add a great benefit of clear understanding on how the model is actually working.

In case the result contains the dynamic parts depending on configuration, like hostname, these can be replaced in the expected result string before comparison.

**Review by sivaschenko — CHANGES_REQUESTED** [review]
Thanks for the updates @jmonteros422 ! Please see my comments

**Comment by jmonteros422** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sivaschenko, thank you for the review.
[ENGCOM-8070](https://jira.corp.magento.com/browse/ENGCOM-8070) has been created to process this Pull Request

**Comment by chalov-anton** [comment]
:heavy_check_mark: QA Passed

- the Used in is displayed correctly
used_in

- The reduced image is added to the Content and the image is used from _/pub/media/.renditions_ folder
rendition_folder

Manual testing scenario - https://studio.cucumber.io/projects/131313/test-plan/folders/1507933/scenarios/4296386

**Comment by sivaschenko** [comment]
@magento run Functional Tests B2B

**Comment by sivaschenko** [comment]
Previous tests failed as they have been triggered from dependent ASI PR

**Comment by sivaschenko** [comment]
@magento run all tests

File: app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php [hunk 13]
```diff
@@ -1,62 +1,63 @@
...
      */
     protected $resultRawFactory;
 
     /**
-     * @param \Magento\Backend\App\Action\Context $context
-     * @param \Magento\Framework\Registry $coreRegistry
-     * @param \Magento\Framework\Controller\Result\RawFactory $resultRawFactory
+     * @var GetInsertImageContent
+     */
+    protected $getInsertImageContent;
```
Comment (sidolov) [inline app/code/Magento/Cms/Controller/Adminhtml/Wysiwyg/Images/OnInsert.php]: Should be private.

**Review by sidolov — CHANGES_REQUESTED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sivaschenko** [comment]
@magento run all tests
