### PR TITLE
MC-40031: [UX] Configurations are not preserved on form reload when new configurable product creation fails

### LINKED ISSUE #32102: [UX] Configurations are not preserved on form reload when new configurable product creation fails
This is a usability issue.

1. Open backend
1. Go to products grid
1. Create configurable product with 1 attribute named "Configurable One"
1. Save product
1. Create new configurable product configuration basing on 5 attributes with only 2 variations each
1. Enter  "Configurable One" as name
1. Configure variations qty and prices (enter different price and qty for each vatiation)
1. CLick Save

(-) Actual: Form is reloaded. Error is displayed:
```
The value specified in the URL Key field would generate a URL that already exists.
```
The variations you configured have disappeared. Information that has to be entered manually and requires significant time is lost.

(/) Expected: To be identified by UX team.
- Form is reloaded, configurations are preserved.
OR
- Form is not reloaded, AJAX validation includes URL Key check.

### PR DESCRIPTION
**Pull request by namlier**
### Description (*)
This is a usability issue.

### Fixed Issues (if relevant)
1. Fixes magento/magento2/issues/32102

### Manual testing scenarios (*)

1. Open backend
2. Go to products grid
3. Create configurable product with 1 attribute named "Configurable One"
4. Save product
5. Create new configurable product configuration basing on 5 attributes with only 2 variations each
6. Enter "Configurable One" as name
7. Configure variations qty and prices (enter different price and qty for each vatiation)
8. CLick Save

 **Actual**: Form is reloaded. Error is displayed:
_The value specified in the URL Key field would generate a URL that already exists._
The variations you configured have disappeared. Information that has to be entered manually and requires significant time is lost.

**Expected**: To be identified by UX team.
- Form is reloaded, configurations are preserved.
OR
- Form is not reloaded, AJAX validation includes URL Key check.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php [hunk 1]
```diff
@@ -130,11 +158,18 @@ public function execute()
             $resource->getAttribute('news_from_date')->setMaxValue($product->getNewsToDate());
             $resource->getAttribute('custom_design_from')->setMaxValue($product->getCustomDesignTo());
 
+            $this->validateUrlKeyUniqueness($product);
```
Comment (zakdma) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: You should not perform validation in controller
It is better to do it inside
\Magento\Catalog\Model\ResourceModel\Product::validate

**Review by zakdma — CHANGES_REQUESTED** [review]

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests EE

**Comment by mastiuhin-olexandr** [comment]
@magneto run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php (hunk 1 above)
Comment (namlier) [reply app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: I think it should stay in controller, because other requests also has this validation.

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php [hunk 2]
```diff
@@ -73,14 +95,20 @@ public function __construct(
         \Magento\Catalog\Model\Product\Validator $productValidator,
         \Magento\Framework\Controller\Result\JsonFactory $resultJsonFactory,
         \Magento\Framework\View\LayoutFactory $layoutFactory,
-        \Magento\Catalog\Model\ProductFactory $productFactory
+        \Magento\Catalog\Model\ProductFactory $productFactory,
+        ProductUrlPathGenerator $productUrlPathGenerator,
+        UrlFinderInterface $urlFinder,
+        GetStoresListByWebsiteIds $getStoresListByWebsiteIds
```
Comment (zakdma) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: added constructor parameters should be nullable and should be initialized inside constructor

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php (hunk 2 above)
Comment (namlier) [reply app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: Thank you, fixed.

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Review by zakdma — APPROVED** [review]

**Comment by engcom-Oscar** [comment]
:heavy_check_mark: QA passed

Was checked case from Manual testing scenarios 

:x: **Before:**

Form is reloaded. Error is displayed: "The value specified in the URL Key field would generate a URL that already exists."
The variations you configured have disappeared. 

:heavy_check_mark: **After:**
Error is displayed: "The value specified in the URL Key field would generate a URL that already exists."
The variations you configured still present. 
Screenshot from 2021-02-23 13-20-28
Screenshot from 2021-02-23 13-20-21

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32194`.

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Static Tests, WebAPI Tests, Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php [hunk 3]
```diff
@@ -149,6 +184,45 @@ public function execute()
         return $this->resultJsonFactory->create()->setData($response);
     }
 
+    /**
+     * Validates Url Key uniqueness.
+     *
+     * @param ProductModel $product
+     * @throws UrlAlreadyExistsException
+     */
+    private function validateUrlKeyUniqueness(ProductModel $product): void
```
Comment (gabrieldagama) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: I believe we should create a new class/model for this validation, we may need to use it on another controller. This should be added to CatalogUrlRewrite module and used here, it will reduce complexity on the controller at least.

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php [hunk 4]
```diff
@@ -149,6 +184,45 @@ public function execute()
...
+                continue;
+            }
+
+            $urlPath = $this->productUrlPathGenerator->getUrlPathWithSuffix($product, $store->getId());
+
+            $urlRewrite = $this->urlFinder->findOneByData([
+                UrlRewrite::REQUEST_PATH => $urlPath,
+                UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
+                UrlRewrite::STORE_ID => $store->getId()
+            ]);
```
Comment (gabrieldagama) [inline app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: To reduce the impact of this, I believe we should use `findAllByData` and fetch all the data for all stores at once outside the foreach. As it is right now the time complexity of such would grow linear with the numbers of stores, where it can be just O(1).

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi, @mastiuhin-olexandr @zakdma can you have a look at my comments below?

Thanks!

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests CE, Functional Tests EE, WebAPI Tests

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests EE, WebAPI Tests

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php (hunk 4 above)
Comment (namlier) [reply app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: @gabrieldagama Fixed, please review the changes.

File: app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php (hunk 3 above)
Comment (namlier) [reply app/code/Magento/Catalog/Controller/Adminhtml/Product/Validate.php]: @gabrieldagama Fixed.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32194`.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+        }
+
+        $urlRewrites = $this->urlFinder->findAllByData($searchData);
+        $conflicts = [];
+
+        foreach ($urlRewrites as $urlRewrite) {
+            if (in_array($urlRewrite->getRequestPath(), $storeIdsToPathForSave)
+                && isset($storeIdsToPathForSave[$urlRewrite->getStoreId()])
+                && $storeIdsToPathForSave[$urlRewrite->getStoreId()] == $urlRewrite->getRequestPath()
+                && $product->getId() != $urlRewrite->getEntityId()) {
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Move
``` ) {```
to the next line

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php [hunk 6]
```diff
@@ -0,0 +1,97 @@
...
+        ];
+
+        foreach ($stores as $store) {
+            if (!in_array($store->getWebsiteId(), $product->getWebsiteIds())) {
+                continue;
+            }
+
+            $urlPath = $this->productUrlPathGenerator->getUrlPathWithSuffix($product, $store->getId());
+            $storeIdsToPathForSave[$store->getId()] = $urlPath;
+            $searchData[UrlRewrite::REQUEST_PATH][] = $urlPath;
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php:80]: add comma

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php [hunk 7]
```diff
@@ -0,0 +1,97 @@
...
+     * Find Url Key conflicts of a product.
+     *
+     * @param Product $product
+     * @return array Array of conflicting Url Keys.
+     */
+    public function findUrlKeyConflicts(Product $product): array
+    {
+        if (!$product->getUrlKey()) {
+            $urlKey = $this->productUrlPathGenerator->getUrlKey($product);
+            $product->setUrlKey($urlKey);
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: I suppose this UrlKey generation if t empty should not be in validator.

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php [hunk 8]
```diff
@@ -0,0 +1,97 @@
...
+        $this->storeManager = $storeManager;
+    }
+
+    /**
+     * Find Url Key conflicts of a product.
+     *
+     * @param Product $product
+     * @return array Array of conflicting Url Keys.
+     */
+    public function findUrlKeyConflicts(Product $product): array
```
Comment (gabrieldagama) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: A `Validator` class with a method `findUrlKeyConflicts` probably doesn't make much sense, I would recommend actually changing it to `validateUrlKeyConflicts` and throw the exception here. Make this method a void instead, there is no point to return the URL keys if they won't be used.

Comment (gabrieldagama) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Also, agree with Myroslav, the generation should happen on controller and be a parameter on this function. If the information from product that we need is just ID, probably just use it as parameter instead of whole product object.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php [hunk 9]
```diff
@@ -0,0 +1,97 @@
...
+            $searchData[UrlRewrite::REQUEST_PATH][] = $urlPath;
+        }
+
+        $urlRewrites = $this->urlFinder->findAllByData($searchData);
+        $conflicts = [];
+
+        foreach ($urlRewrites as $urlRewrite) {
+            if (in_array($urlRewrite->getRequestPath(), $storeIdsToPathForSave)
+                && isset($storeIdsToPathForSave[$urlRewrite->getStoreId()])
+                && $storeIdsToPathForSave[$urlRewrite->getStoreId()] == $urlRewrite->getRequestPath()
```
Comment (gabrieldagama) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Please use ===

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 5 above)
Comment (gabrieldagama) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Please use !==

**Review by gabrieldagama — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+            $urlKey = $this->productUrlPathGenerator->getUrlKey($product);
+            $product->setUrlKey($urlKey);
+        }
+
+        $stores = $this->storeManager->getStores();
+
+        $storeIdsToPathForSave = [];
+        $searchData = [
+            UrlRewrite::ENTITY_TYPE => ProductUrlRewriteGenerator::ENTITY_TYPE,
+            UrlRewrite::REQUEST_PATH => []
```
Comment (zakdma) [inline app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: add comma

**Review by zakdma — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 10 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Fixed.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 5 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Fixed.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 9 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Fixed

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 8 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: I am not sure that rework this to passing UrlKey parameter is a good idea. 

In this case the most of logic will stay in the controller. Because there is a function that is using for UrlPath generation
`$this->productUrlPathGenerator->getUrlPathWithSuffix($product, $store->getId());`,
that uses a product model. The only what will left in the validator is "findAllByData" and the pieace of program that checks found rewrites are not belong to a product.

The other pieace of program generating urlKey, generating urlPathes of stores, searching storeIds of websites (as workaround for performance) will be in the controller.

Please check the last changes and then confirm or deny that it should be reworked like you said before.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 5 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Thank you, fixed.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 7 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Thank you, fixed.

File: app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php (hunk 8 above)
Comment (namlier) [reply app/code/Magento/CatalogUrlRewrite/Model/Product/Validator.php]: Thank you, fixed. Validator now throws exception. And method renamed.

**Comment by mastiuhin-olexandr** [comment]
@magento run all tests

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B

**Comment by mastiuhin-olexandr** [comment]
@magento run Functional Tests B2B, WebAPI Tests

**Comment by mastiuhin-olexandr** [comment]
@magento run WebAPI Tests

**Review by zakdma — APPROVED** [review]

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-8808](https://jira.corp.magento.com/browse/ENGCOM-8808) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32194`.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import code to https://github.com/magento-tsg/magento2ce

**Comment by magento-engcom-team** [comment]
@zakdma the branch with code successfully imported into`magento-tsg/magento2ce` repository. Branch name: `imported-magento-magento2-32194`.
