### PR TITLE
Fix #27523: throw informative errors in setup:db:generate-patch

### LINKED ISSUE #27523: CLI Patch Generator: Lack of information what path cannot be created
### Preconditions (*)
1. When running CLI `setup:db:generate-patch` I'd like to know details of failure

### Steps to reproduce (*)
1. `setup:db:generate-patch My_Module PatchName`

### Expected result (*)
1. Information what path was used to create patch.

### Actual result (*)
1. image

### Additional Information
- Related DevDoc  [Convert install/upgrade data scripts to the data patch format](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/migration-commands.html#convert-installupgrade-data-scripts-to-the-data-patch-format)

### PR DESCRIPTION
**Pull request by korostii**
### Description (*)
In most cases, if there is indeed a write permission issue, the error does show the complete path to directory which cannot be created:
Screenshot from 2020-04-04 17-21-06
However, if the requested module *does not exist*, the console command will compile an invalid(incomplete) target path and will show a rather cryptic error message:
Screenshot from 2020-04-04 17-09-33

### Fixed Issues (if relevant)

1.  Fixes magento/magento2#27523: CLI Patch Generator: Lack of information what path cannot be created

### Manual testing scenarios (*)
1. Run `php bin/magento setup:db-declaration:generate-patch Vendor_Module SomePatch`, while there isn't any registered modules with name matching `Vendor_Module`
2. You should see an informative error message like `Cannot find a registered module with name "Vendor_Module" `

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

File: app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+use Magento\Framework\Filesystem\Directory\WriteFactory;
+use Magento\Framework\Filesystem\DirectoryList;
+use Symfony\Component\Console\Tester\CommandTester;
+
+class GeneratePatchCommandTest extends \PHPUnit\Framework\TestCase
+{
+    /**
+     * @var ComponentRegistrar
+     */
+    private $componentRegistrar;
```
Comment (rogyar) [inline app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php]: Please, add `mock` suffix to the mock properties

```suggestion
    private $componentRegistrarMock;
```

Comment (rogyar) [reply app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php]: It also applies to all other mock properties

File: app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+
+    /**
+     * @var DirectoryList
```
Comment (rogyar) [inline app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php]: Please, import `PHPUnit\Framework\MockObject\MockObject;` and use it for documenting properties
```suggestion
     * @var DirectoryList|MockObject
```

File: app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+    }
+
+    public function testExecute()
+    {
+        $this->componentRegistrar->expects($this->once())
+            ->method('getPath')
+            ->with('module', 'Vendor_Module')
+            ->willReturn('/long/path/to/Vendor/Module');
+
+        $read = $this->createMock(\Magento\Framework\Filesystem\Directory\Read::class);
```
Comment (rogyar) [inline app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php]: Please, import classes instead of using FQN

File: app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+                GeneratePatchCommand::MODULE_NAME => 'Vendor_Module',
+                GeneratePatchCommand::INPUT_KEY_PATCH_NAME => 'SomePatch'
+            ]
+        );
+        $this->assertContains('successfully generated', $commandTester->getDisplay());
+    }
+
+    /**
+     * @expectedException \RuntimeException
+     * @expectedExceptionMessage Not enough arguments
```
Comment (rogyar) [inline app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php]: Please, do not use annotations for exceptions. They are not compatible with PHPUnit 8 which is going to be supported soon. Use `$this->expectExceptionMessage(` instead

Comment (rogyar) [reply app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php]: The same applies to `@expectedException`

**Review by rogyar — CHANGES_REQUESTED** [review]

File: app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    public function testExecute()
+    {
+        $this->componentRegistrarMock->expects($this->once())
+            ->method('getPath')
+            ->with('module', 'Vendor_Module')
+            ->willReturn('/long/path/to/Vendor/Module');
+
+        $read = $this->createMock(Read::class);
```
Comment (rogyar) [inline app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php:69]: Hi @korostii. Thank you for fixing the issues mentioned earlier. There was a comment from me regarding suffixing mock properties with Mock suffix. The same applies to the variables. This suffix improves code readability by letting know straight away what object we are working on mock or a real instance.

Just a recommendation for the future 😉

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-7280](https://jira.corp.magento.com/browse/ENGCOM-7280) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Run: `php bin/magento setup:db-declaration:generate-patch Vendor_Module SomePatch`

**Before:**
Screenshot from 2020-04-09 14-33-36

**After:**
Screenshot from 2020-04-09 14-45-45

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Comment by engcom-Kilo** [comment]
Failed Functional Tests B2B, Static Tests, Unit Tests - not related to changes in this Pull Request.

**Comment by slavvka** [comment]
@magento run all tests

**Review by slavvka — CHANGES_REQUESTED** [review]
@korostii Please fix the failing tests after upgrade to PHP 7.4:
```
13:04:22 PHP Fatal error:  Declaration of Magento\Developer\Test\Unit\Console\Command\GeneratePatchCommandTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /var/www/html/app/code/Magento/Developer/Test/Unit/Console/Command/GeneratePatchCommandTest.php on line 47
```

**Comment by korostii** [comment]
> Please fix the failing tests after upgrade to PHP 7.4

Fixed.

**Comment by engcom-Kilo** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @sidolov, thank you for the review.
[ENGCOM-7280](https://jira.corp.magento.com/browse/ENGCOM-7280) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

Run: `php bin/magento setup:db-declaration:generate-patch Vendor_Module SomePatch`

**Before:**
Screenshot from 2020-04-09 14-33-36

**After:**
Screenshot from 2020-04-09 14-45-45
