### PR TITLE
magento/magento2#35371: Product page gives error because of url rewrites

### LINKED ISSUE #35371: Product page gives error because of url rewrites
### Preconditions (*)

1. Magento 2.4.1, 2.4.3 (this problem may exist from 2.3.3).
2. `Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Product URL Suffix` is empty.
3. `Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Category URL Suffix` is empty.
4. `Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Use Categories Path For Product URLs` is Yes.
5. `Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Generate "category/product" URL Rewrites` is No.
6. There is a category `Test Category` created under root category and `Test Sub Category` created under `Test Category`. There is a product `Test` and it is assigned to `Test Sub Category`. This is to make category url path have the product url path in it preceded by a forward slash (/). In this example the product url path is "**test**" and `Test Sub Category` url path is "test-category/**test**-sub-category"

### Steps to reproduce (*)

1. Go to `Test Sub Category`.
2. Click on product `Test`.

### Expected result (*)

1. The product page is loaded successfully.

### Actual result (*)

1. There is 404 error (on 2.4.3 or newer version) or 500 error (on older version than 2.4.3).

Looks like on line 173 in `\Magento\CatalogUrlRewrite\Model\Storage\DynamicStorage` function `str_replace` should not be used. We fixed it on our installation by changing that line to this:
```
$categoryPath = substr($requestPath, 0, -1 * strlen('/' . $productUrl));
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.4/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Himsoft**
### Description (*)

In situation when category with level > 2 have product url key at the beginning of its url key, str_replace(),  used in \Magento\CatalogUrlRewrite\Model\Storage\DynamicStorage::findProductRewriteByRequestPath, replaces all parts of the category path equal to the product url key.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35371

### Manual testing scenarios (*)

1. Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Product URL Suffix is empty.
2. Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Category URL Suffix is empty.
3. Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Use Categories Path For Product URLs is Yes.
4. Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Generate "category/product" URL Rewrites is No.
5. Create new category with name **Test Category** under root category (Catalog - Categories)
6. Create sub category with name **Test Sub Category** under new category and save (Catalog - Categories)
7. Create Product with name **Test** and assigned only new sub category and save
8. Go to **Test Sub Category**.
9. Click on product **Test**.

Before fix:
There is 404 error.

After fix:
The product page is loaded successfully.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run Functional Tests B2B

**Comment by Himsoft** [comment]
@magento run Functional Tests B2B

**Comment by Himsoft** [comment]
The failed tests are not related to fixes, they look like false positives, please pay attention to this during the review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

File: app/code/Magento/CatalogUrlRewrite/Model/Storage/DynamicStorage.php [hunk 1]
```diff
@@ -1,8 +1,10 @@
 <?php
+
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2025 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/CatalogUrlRewrite/Model/Storage/DynamicStorage.php]: It must be 2019, as the file has been created in this year only.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Himsoft,

Thank you for your contribution!

Please make the changes as per the below review comment, also add appropriate test data in its file to satisfy the PR changes.

Thanks

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@Himsoft Thank you for the contribution! 
Are you working on the test data changes mentioned in the [review-comment](https://github.com/magento/magento2/pull/39670#pullrequestreview-2720773924) to satisfy the PR changes ?

**Comment by Himsoft** [comment]
> @Himsoft Thank you for the contribution! Are you working on the test data changes mentioned in the [review-comment](https://github.com/magento/magento2/pull/39670#pullrequestreview-2720773924) to satisfy the PR changes ?

Yes, but I can't do it as fast as would like.

**Comment by engcom-Dash** [comment]
@Himsoft Thank you for the reply! I will go ahead and take care of the changes on my end.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by Himsoft** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@engcom-Hotel The test data changes has been added by @Himsoft. Hence Moving this PR to Pending Review.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
Hi @Himsoft,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed


**Preconditions:**

- Install fresh Magento **`2.4-develop`**

**Steps to reproduce**

- Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Product URL Suffix is empty.
- Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Category URL Suffix is empty.
- Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Use Categories Path For Product URLs is Yes.
- Stores -> Configuration -> Catalog -> Catalog -> Search Engine Optimization -> Generate "category/product" URL Rewrites is No.
- Create new category with name Test Category under root category (Catalog - Categories)
- Create sub category with name Test Sub Category under new category and save (Catalog - Categories)
- Create Product with name Test and assigned only new sub category and save
- Go to Test Sub Category.
- Click on product Test.


**Before:** :heavy_multiplication_x: 


Screenshot 2025-04-15 at 1 44 07 pm




**After:** :heavy_check_mark: 


Screenshot 2025-04-15 at 1 54 22 pm




Builds are failed. Hence, moving this PR to **Extended Testing**.

Thanks.

**Comment by engcom-Charlie** [comment]
The Functional B2B failures in recent 2 builds are not consistent. They are neither part of this PR nor failing because of the PR changes, seems to be flaky. Hence moving the PR to Merge in Progress.

**Run 1:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39670/679313557e07da76758e73510bff5861/Functional/allure-report-b2b/index.html#categories

image

**Run 2:**
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39670/e32d481670eba1686c75e2a87619f822/Functional/allure-report-b2b/index.html#categories/bdbf199525818fae7a8651db9eafe741

image
