### PR TITLE
magento/magento2#29926: Prices should be possibly hidden from products query results

### LINKED ISSUE #29926: Prices should be hidden from products query results when the category permissions chooses to hide them
`query{
products(search: "product"){
  total_count
	items {    
		name
		sku
    price_tiers {
      quantity
      final_price {
        value
      }
    }
    price_range {
      maximum_price {
        final_price {
          value
        }
      }
      minimum_price {
        final_price {
          value
        }
      }
    }
    special_price
	}
	}
}`

The product collection is processed properly. Processor is:
`Magento\CatalogPermissionsGraphQl\Model\Resolver\Products\DataProvider\Product\CollectionProcessor\CustomerGroupProcessor` 
This returns results by which the product property `can_show_price` is set correctly per the category permissions configuration.
However, the query above would still display the prices.
We need to return null, when on product level `can_show_prices` is `false` for the following fields
- price_range
- price_tiers
- special_price

### Preconditions (*)

1.
2.

### Steps to reproduce (*)

1.
2.

### Expected result (*)

1. [Screenshots, logs or description]
2.

### Actual result (*)

1. [Screenshots, logs or description]
2.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by pmarjan**
### Description (*)
Fixes https://github.com/magento/magento2/issues/29926

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by pmarjan** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/PriceRange.php [hunk 1]
```diff
@@ -130,4 +133,39 @@ private function formatPrice(float $regularPrice, float $finalPrice, StoreInterf
...
+    }
+
+    /**
+     * Format empty result
+     *
+     * @return array
+     */
+    private function formatEmptyResult(): array
+    {
+        return [
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/PriceRange.php:159]: If we could make the Money! type not mandatory, would be better.
We won't now though, because it's backward incompatible in schema.  I guess we never thought a price can be optional...

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php [hunk 2]
```diff
@@ -28,7 +28,10 @@ public function resolve(Field $field, $context, ResolveInfo $info, array $value
         /** @var PricingSpecialPrice $specialPrice */
         $specialPrice = $product->getPriceInfo()->getPrice(PricingSpecialPrice::PRICE_CODE);
 
-        if ($specialPrice->getValue()) {
+        if ((!$product->hasData('can_show_price')
+                || ($product->hasData('can_show_price') && $product->getData('can_show_price') === true)
```
Comment (cpartica) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php:32]: there's no constant in core for this right? if not..leave it like this

**Review by cpartica — APPROVED** [review]

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/PriceRange.php (hunk 1 above)
Comment (pmarjan) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Product/PriceRange.php:159]: Yes, so this seemed like the good approach under these circumstances.

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php (hunk 2 above)
Comment (pmarjan) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Product/SpecialPrice.php:32]: No, no constant as far I can see.

**Comment by pmarjan** [comment]
@magento run all tests

**Review by cpartica — APPROVED** [review]
