### PR TITLE
[GraphQl] 29168 TierPrices filtering

### LINKED ISSUE #29168: Tier prices filtering in GraphQl - prices for different customer group but same quantity are not filtered out
Execute this query, to search for product that already meets the pre-conditions below

`products(search: "[Product-name]"){
	items {    
    price_tiers {
     	final_price {
        currency
        value
      }
      quantity
     }
	  }
	}`

Preconditions, expected results and actual results, are all based on an example with colliding ALL CUSTOMER GROUPS with NOT LOGGED IN. 
Nevertheless, the problem is still present when colliding ALL CUSTOMER GROUPS group with any other group.

### Preconditions (*)

1. Have a product created that has tier prices set as
a. Website: All Websites, Group: All Groups, Quantity: 3, Price: Fixed, Value: 3
b. Website: All Websites, Group: Not Logged In, Quantity: 3, Price: Fixed, Value: 3.5

### Steps to reproduce (*)

1. Execute the query and watch for response

### Expected result (*)

1. There is only one "final_price" with "quantity" = 3 in the response
2. The lower price value for the given quantity is displayed only

### Actual result (*)

1. Quantity 3 is listed twice for the both customer groups

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Usik2203**
### Description (*)

This PR fixes issue with TierPrices filtering 
Screenshot 2020-08-19 at 14 31 29

**Result Before**
We see all prices for each quantity
Screenshot 2020-08-19 at 14 47 35

**Result After**
We see lower price for each quantity
Screenshot 2020-08-19 at 14 47 57

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29168>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Usik2203** [comment]
magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 1]
```diff
@@ -158,4 +158,45 @@ private function formatProductTierPrices(array $tierPrices, float $productPrice,
...
+
+    /**
+     * Returns true if first price is better
+     *
+     * @param float $firstPrice
+     * @param float $secondPrice
+     *
+     * @return bool
+     */
+    private function isFirstPriceBetter(float $firstPrice, float $secondPrice): bool
```
Comment (rogyar) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: I would not suggest creating a separate method for such a simple comparison. It makes code harder to read and introduces semantical complexity. In the future, if we will need more complex comparison we can always create a separate method. But on this stage, I would keep things simple

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 2]
```diff
@@ -158,4 +158,45 @@ private function formatProductTierPrices(array $tierPrices, float $productPrice,
...
+     * Select a lower price for each quantity
+     *
+     * @param ProductTierPriceInterface[] $tierPrices
+     *
+     * @return array
+     */
+    private function filterTierPrices(array $tierPrices): array
+    {
+        $qtyCache = [];
+        foreach ($tierPrices as $item => &$price) {
```
Comment (rogyar) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: We are passing the `&$price` variable by reference but it does not seem like we modify it somehow in the loop below. But I may miss something.

**Review by rogyar — CHANGES_REQUESTED** [review]
Hi @Usik2203. Please, check my recommendations below. 
Also, do you have covering this case by API-functional test in your plans?

**Comment by Usik2203** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 1 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 2 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Fixed**

**Comment by Usik2203** [comment]
Hi @rogyar 
I have applied your code review recommendations and added API test.
Thanks

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 2 above)
Comment (pmarjan) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: @Usik2203 
Both methods, `filterTierPrices` and `formatProductTierPrices`, which are called one after another, are using `foreach` to loop through the tier prices.

Given that this code executes when a query searches for products, please consider a situation where we might have large b2b catalog with plenty tiers for different customer groups and a relatively short search phrase, yielding plenty of results.
Having to loop twice through all tier prices in all search results, might lead to performance degradation.

I am wondering, could these two methods be somehow combined, so that we get the same results using `foreach` only once?

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 3]
```diff
@@ -158,4 +158,32 @@ private function formatProductTierPrices(array $tierPrices, float $productPrice,
         }
         return $tiers;
     }
+
+    /**
+     * Select a lower price for each quantity
```
Comment (pmarjan) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: Is maybe "Select the lowest price for each quantity" more accurate?

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 4]
```diff
@@ -101,6 +101,20 @@ public function testSecondStoreViewWithCurrencyRate()
         $this->assertEquals(round(7.25 * $rate, 2), $this->getValueForQuantity(5, $itemTiers));
     }
 
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/simple_product_with_price_tiers_for_multiple_groups.php
+     */
+    public function testGetLowersPrices()
```
Comment (pmarjan) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: Seems like a typo in the function name?

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php [hunk 5]
```diff
@@ -101,6 +101,20 @@ public function testSecondStoreViewWithCurrencyRate()
         $this->assertEquals(round(7.25 * $rate, 2), $this->getValueForQuantity(5, $itemTiers));
     }
 
+    /**
+     * @magentoApiDataFixture Magento/Catalog/_files/simple_product_with_price_tiers_for_multiple_groups.php
```
Comment (pmarjan) [inline dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: In this case, the same Test class uses two different fixtures with relatively indistinguishable names, which might confuse the person who reads the test functions.

Is it possible to edit as needed and then reuse `Magento/Catalog/_files/simple_product_with_tier_prices_for_multiple_groups.php` instead of adding new fixture file?

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php (hunk 4 above)
Comment (pmarjan) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: To ensure more scenarios are covered, could we possibly have test methods that specifically test for a given group, e.g. testGetLowestPriceForGuest and testGetLowestPriceForCustomer?

**Review by pmarjan — CHANGES_REQUESTED** [review]

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php (hunk 5 above)
Comment (Usik2203) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: **Done**

File: dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php (hunk 4 above)
Comment (Usik2203) [reply dev/tests/api-functional/testsuite/Magento/GraphQl/CatalogCustomer/PriceTiersTest.php]: **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 3 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 2 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: @pmarjan  Done

Comment (pmarjan) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: @Usik2203 
From "clarity of intent" perspective, when one reads through the "resolve" function alone, it seems as though formatProductTierPrices function does only what its name says. In fact this function's comment seems to support that.
But, that is misleading.

So, I am wondering can we have a function named like filterAndFormatProductTierPrices, that invokes a foreach loop, and inside this loop, one below the other filterTierPrices and formatProductTierPrices are called?

Check for example, when an unfortunate situation like we have, calls for two different things to be done in the same method:
`League\Flysystem\Filesystem::readAndDelete()`
internally first calls
`$this->read()`
and later
`$this->delete()`

**Review by rogyar — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @rogyar, thank you for the review.
[ENGCOM-8099](https://jira.corp.magento.com/browse/ENGCOM-8099) has been created to process this Pull Request

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 2 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: @pmarjan **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 6]
```diff
@@ -120,42 +120,89 @@ function () use ($productId, $context) {
...
+        array $tierPrices,
+        float $productPrice,
+        StoreInterface $store
+    ): array {
         $tiers = [];
+        $qtyCache = [];
+
+        foreach ($tierPrices as $key => $tierPrice) {
+            $this->formatProductTierPrices($productPrice, $store, $tierPrice, $tiers);
+            $this->filterTierPrices($tierPrices, $key, $tierPrice, $qtyCache, $tiers);
```
Comment (pmarjan) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: I wonder, can we call filterTierPrices and formatProductTierPrices in different order, and functionality is not affected? 

Seems like its possible, and then the order of execution of the internal private method matches both the filterAndFormatProductTierPrices function name and its comment.

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 7]
```diff
@@ -120,42 +120,89 @@ function () use ($productId, $context) {
...
+
+    /**
+     * Format tier prices for output
+     *
+     * @param float $productPrice
+     * @param StoreInterface $store
+     * @param ProductTierPriceInterface $tierPrice
+     * @param array $tiers
+     */
+    private function formatProductTierPrices(float $productPrice, StoreInterface $store, &$tierPrice, &$tiers)
```
Comment (pmarjan) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: I would rename this to formatTierPrices. Having "Product" in the name seems like superfluous information.

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 8]
```diff
@@ -120,42 +120,89 @@ function () use ($productId, $context) {
...
+     * Filter and format tier prices for output
      *
      * @param ProductTierPriceInterface[] $tierPrices
      * @param float $productPrice
      * @param StoreInterface $store
      * @return array
      */
-    private function formatProductTierPrices(array $tierPrices, float $productPrice, StoreInterface $store): array
-    {
+    private function filterAndFormatProductTierPrices(
```
Comment (pmarjan) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: An idea...

I would rename this to filterAndFormatTierPrices. Having "Product" in the name seems like superfluous information.

In this case, sounds irrelevant if the objects/data that we filter and format are a property of a product or not.

**Review by pmarjan — CHANGES_REQUESTED** [review]

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 8 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 7 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 6 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: Hi @pmarjan  I  tried call` filterTierPrices `and `formatTierPrices` in different order and got error in test.

**Comment by Usik2203** [comment]
@magento run all tests

**Review by pmarjan — APPROVED** [review]

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 9]
```diff
@@ -120,42 +120,89 @@ function () use ($productId, $context) {
```
Comment (cpartica) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php:134]: can you fix types on `$this->tiers->addProductFilter($productId)` ? `\Magento\CatalogCustomerGraphQl\Model\Resolver\Product\Price\Tiers::addProductFilter` has no strict types
` public function addProductFilter($productId): void`
would be
` public function addProductFilter(int $productId): void`

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 10]
```diff
@@ -120,42 +120,89 @@ function () use ($productId, $context) {
...
+
+    /**
+     * Format tier prices for output
+     *
+     * @param float $productPrice
+     * @param StoreInterface $store
+     * @param ProductTierPriceInterface $tierPrice
+     * @param array $tiers
+     */
+    private function formatTierPrices(float $productPrice, StoreInterface $store, &$tierPrice, &$tiers)
```
Comment (cpartica) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: we kind of prohibit passing params by reference &$tierPrice, &$tiers
You better want a function that returns something. You rarely want a function that returns 2 things.
formatTierPrices can return $tiers for example. 
Objects are passed by reference by default so you don't need  &$tierPrice to do $tierPrice->setValue
You can also do that outside formatTierPrices and don't set anything in tierPrice, just get
Plus you only need getValue and getQty  and getPercentageValue from it. You can use those params directly not by passing the whole tierPrice. 
From store you only need CurrencyCode not store.
Suddenly your method becomes: formatTierPricesValues(productPrice, tierPriceValue, TierPricePercentage, tierPriceQty): array (where array is $tiers)

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php [hunk 11]
```diff
@@ -120,42 +120,89 @@ function () use ($productId, $context) {
...
+     * @param int $key
+     * @param ProductTierPriceInterface $tierPriceItem
+     * @param array $qtyCache
+     * @param array $tiers
+     */
+    private function filterTierPrices(
+        array $tierPrices,
+        int $key,
+        ProductTierPriceInterface $tierPriceItem,
+        array &$qtyCache,
```
Comment (cpartica) [inline app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: $qtyCache doesn't need to be passed by reference
it can be part of your object \Magento\CatalogCustomerGraphQl\Model\Resolver\PriceTiers
by declaring a private $productTiersByQuanity[] //you can dcument that this acts like a cache
it can hold prices like $productTiersByQuanity[customerGroup][productId][qty] so it can be used for multiple products and if called multiple times for the same product, you can just fetch it and not even need to recalculate it.
not sure if customerGroup is required. probably not. you'l only get the relevant tiers for current customerGroup
of course filterTierPrices : array which is the filtered tiers, and you can pass formatted tiers from previous function return

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by Usik2203** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 9 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php:134]: **Done**

**Comment by Usik2203** [comment]
@magento run all tests

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 11 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Done**

File: app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php (hunk 10 above)
Comment (Usik2203) [reply app/code/Magento/CatalogCustomerGraphQl/Model/Resolver/PriceTiers.php]: **Done**

**Comment by o-iegorov** [comment]
@magento run Functional Tests CE, Integration Tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by o-iegorov** [comment]
@magento run Functional Tests EE

**Comment by Usik2203** [comment]
@magento run WebAPI Tests

**Comment by Usik2203** [comment]
@magento run all tests

**Comment by o-iegorov** [comment]
@magento run Functional Tests EE

**Review by cpartica — APPROVED** [review]
