### PR TITLE
Cron cleanup repeatedly hits deadlocks on large environments where groups can overlap

### LINKED ISSUE #8933: 1213 Deadlock found when trying to get lock
### Preconditions

1. Magento 2.1.3
2. Php 7.0.13-1 and Apache2

### Steps to reproduce

1.  Importing Product (Saving to Magento) from 3rd party API from CLI Script
2.  Run above process in parallel since too many products exist 
3.  Index - Update by Schedule. (Meaning no index works when importing product)

### Expected result

1. Product Should be successfully saved to the system

### Actual result

1. Following problem happen oftenly,
- PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock

2. If I try to edit product related value on Admin page while importing product, that error happen too.

### LINKED ISSUE #18409: Magento 2.2.5 - Cron Job Error. Sqlstate[40001]: Serialization failure: 1213 Deadlock
### Summary

 We are using Magento 2.2.5 and we are consistently receiving Cron Job Error. Sqlstate[40001]: Serialization failure: 1213 Deadlock. 

### Preconditions

1. Magento 2.2.5 
2. PHP 7.1.13

### Steps to Reproduce

1.  Setup cron job at server

### Expected Result

1. Cron Job Run Should be successfully
2.  No more pending jobs


### Actual Result

 [Magento\Framework\DB\Adapter\DeadlockException]                                                                                                                                                                                                                                                                                          
  SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction, query was: DELETE FROM `cron_schedule` WHERE (status = 'missed') AND (job_code in ('indexer_reindex_all_invalid', 'indexer_update_all_views', 'indexer_clean_all_changelogs')) AND (created_at < '2018-09-28 18:32:28')

### LINKED ISSUE #22438: Magento 2.3.1 Cron Deadlocks for cron_schedule
### Preconditions (*)
1. Magento 2.3.1
2. MSI

### Steps to reproduce (*)
1. Vanilla install
2. Run CRON every 1 minutes 3 jobs main, setup and upgrade

### Expected result (*)
1. No CRON problems, especially no deadlocks for a simple table .... truncating the table only works 1time ... need a structural solution or some kind of retry method

### Actual result (*)
1. See below

This really should not happen

https://magento.stackexchange.com/questions/270856/magento-2-v2-3-1-cron-causing-intermittent-deadlock-for-cron-schedule

https://magento.stackexchange.com/questions/238454/cron-job-error-sqlstate40001-serialization-failure-1213-deadlock-found-when?rq=1

https://magento.stackexchange.com/questions/203107/magento-2-cron-schedule-table-increasing-and-cpu-100

https://magento.stackexchange.com/questions/270813/magento-2-3-1-vanilla-cron-error-serialization-failure-1213-deadlock-found-whe

### LINKED ISSUE #23054: Cron job not running after crashed once
### Preconditions (*)
Magento EE 2.2.8
Crontab configured as per the documentation

### Steps to reproduce (*)
- An error makes the cron job indexer_update_all_views fail once (in my case, database unavailable)

### Expected result (*)
- Current run should be marked as failed in the table cron_schedule
- Next run should run correctly and status be updated at the end in cron_schedule

### Actual result (*)
Table cron_schedule is filled with pending jobs, no job for indexer_update_all_views is run (no output in var/log/cron.log, no status update in cron_schedule table.

Logs :
var/log/cron.log (last success + the error message)
```
[2019-05-29 11:25:10] report.INFO: Cron Job indexer_update_all_views is run [] []
[2019-05-29 11:28:03] report.ERROR: Cron Job indexer_update_all_views has an error: SQLSTATE[08S01]: Communication link failure: 1047 WSREP has not yet prepared node for application use, query was: SELECT `mview_state`.* FROM `mview_state` WHERE (`mview_state`.`view_id`='catalog_product_flat'). Statistics: {"sum":0,"count":1,"realmem":0,"emalloc":0,"realmem_start":182714368,"emalloc_start":180313880} [] []
```
=> And then no more logs about indexer_update_all_views, even if other jobs from the index group run correctly and output success in var/log/cron.log
Database recovered a minute after and query was OK

### PR DESCRIPTION
**Pull request by driskell**
We have two large installations, one Enterprise, one Community, both on 2.3.4, with some long running crons. Frequently the groups overlap and the DELETE operations in the cron cleanup cause deadlocks.

Examining the database environment we can see that some DELETE queries are using the job_code index whereas other are performing a scan as they attempt to use the status column. The ones using an index take exclusive locks on the index then proceed to filter, release, and lock the relevant PRIMARY key entries to take the rows. The queries not using the index take the PRIMARY key locks first then perform filtering and release them. This may not be an exact description but it's my current understanding of what's happening. As you can logically see when two queries run at the same time for two different groups it can cause a deadlock.

### Description (*)
I've tested this patch over time and it alleviates the deadlocks I'm seeing.

The patch changes the DELETE for cleanup so it does not use a range for the job_code. This makes the query more likely to use the job_code index, mostly on MySQL 5.7. However, depending on database contents, it can still ignore it if it finds status column is better, mostly on MySQL 5.6 which I tested too. Adding the status column to the job_code index resolves this and I have yet to see incorrect index behaviour.

The additional index also helps with the atomic job status update. Previously the left join to get the existing job status would not always use an index. And could deadlock also with the aforementioned DELETE cleanup queries. The new index on job_code and status makes this join always use the index.

Furthermore, I had issues on development environments which were built from snapshots, and frequently shutdown and restarted, where there would accumulate "running" jobs that never finish as those jobs were terminated whilst running, or were running at the time of the snapshot. This PR also adds a cleanup of those so that after 24 hours they become failed. This matches the logic in the atomic status update, which ignores running jobs older than 24 hours, allowing a new job to start (and was the cause of the buildup, as every day there was a chance of one additional running entry per job.)

### Related Pull Requests
1. This PR provides alternative fix for cleaning up running jobs that failed to the fix in this one: magento/magento2#24789: magento/magento2#23054:
2. This PR adds an index similar to PR. Not sure what issue was in this PR but it could be the UPDATE/LEFT JOIN slowness is similar as that can avoid using index without this PR magento/magento2#27391: magento/magento2#: Add a new index for `cron_schedule` table

### Fixed Issues (if relevant)
1. Does not fix OP issue but fixes issue in some comments: Fixes magento/magento2#8933 : 1213 Deadlock found when trying to get lock
2. Fixes magento/magento2#22438 : Magento 2.3.1 Cron Deadlocks for cron_schedule
3. Fixes magento/magento2#18409 : Magento 2.2.5 - Cron Job Error. SQLSTATE[40001]: Serialization failure: 1213 Deadlock
4. Fixes #23054
5. Related #25634 (High CPU can occur due to growing cron_schedule, which this PR resolves)
6. Related #26507 (High CPU can occur due to growing cron_schedule, which this PR resolves)
7. Related #26809 (High CPU can occur due to growing cron_schedule, which this PR resolves)

### Manual testing scenarios (*)
1. Unable to reproduce on demand but this steps hopefully are what we understand is the cause
2. Setup new Enterprise site and install several new modules with their own cron groups performing tasks taking at least 5 minutes and starting every 10 minutes - cron groups here are sync tasks with remote systems and stock update and product updates
3. Populate 1000s of products and 1000s of customers
3. Run cron every minute and set cron to email on failure
4. Leave running for a week, and notice emails with deadlocks

For running stale jobs:
1. Take database snapshot whilst jobs running and start it up on new environment
2. Periodically shutdown server whilst jobs are running, several times
3. Note even when cron not running, there are running jobs in the cron_schedule table
4. Note after a week these are still there

### Questions or comments
N/A

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by driskell** [comment]
Will aim to look at tests in next week or so if they need updating.

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php [hunk 1]
```diff
@@ -489,6 +489,7 @@ private function cleanupJobs($groupId, $currentTime)
         );
 
         $this->cleanupDisabledJobs($groupId);
+        $this->cleanupRunningJobs($groupId);
```
Comment (driskell) [inline app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php:554]: Happy to move this functionality to a new PR if it blocks the main deadlock issue.

File: app/code/Magento/Cron/Model/ResourceModel/Schedule.php [hunk 2]
```diff
@@ -69,8 +69,8 @@ public function trySetJobUniqueStatusAtomic($scheduleId, $newStatus, $currentSta
         // this condition added to avoid cron jobs locking after incorrect termination of running job
         $match = $connection->quoteInto(
             'existing.job_code = current.job_code ' .
-            'AND (existing.executed_at > UTC_TIMESTAMP() - INTERVAL 1 DAY OR existing.executed_at IS NULL) ' .
-            'AND existing.status = ?',
+            'AND existing.status = ? ' .
+            'AND (existing.executed_at > UTC_TIMESTAMP() - INTERVAL 1 DAY OR existing.executed_at IS NULL)',
```
Comment (driskell) [inline app/code/Magento/Cron/Model/ResourceModel/Schedule.php:74]: Moving to same order as index so easier to verify at a glance possible indexes

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php [hunk 3]
```diff
@@ -504,14 +505,17 @@ private function cleanupJobs($groupId, $currentTime)
...
-                ]
-            );
+            // Range is not guaranteed to use index for each group and could deadlock, so ensure we use the job_code+status index
+            foreach (array_keys($jobs) as $jobCode) {
+                $count += $connection->delete(
+                    $scheduleResource->getMainTable(),
+                    [
+                        'job_code = ?' => $jobCode,
+                        'status = ?' => $status,
+                        'created_at < ?' => $connection->formatDate($currentTime - $time)
```
Comment (kandy) [inline app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: I believe to fix problem better to replace `created_at` with `scheduled_at`  (see CRON_SCHEDULE_SCHEDULED_AT_STATUS index) and  it's  all
Also 2.3 branch have batch of improvements that can resolve problem, see https://github.com/magento/magento2/blob/2.3/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: That does not fix the issue. Already tested by adding new index for status and created_at.
Issue is as described where because the job_code is an array of values the index selection does not always select an index which separates the groups. So it is potential for one group to scan the rows belonging to another in order to locate the necessary rows to delete, and this is where deadlocks can occur as groups begin to scan each others rows.

This solution here I have confirmed resolved the issue in two environments. It's been running since I opened this PR and I have received no more deadlock errors.

Additionally, I see no changes in 2.3 branch that would resolve or impact the deadlock issue. I was getting deadlocks against 2.3.4.

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Any question let me know - it's been difficult to describe the behaviour of the indexes so I know it might not be fully clear 😬 Thanks for the input though it good to make sure I didn't miss anything.

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: OK I just spotted the deadlock retrier.

I guess it's a choice between resolving the issue or keeping that retrier workaround, or both. I'm never a fan of circuit breaker or retry loops when there's an actual solution available. Maybe both combined would be useful if I rebase so that the retrier is only needed in exceptional circumstances.

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: I do believe the current PR is a simpler approach too and the retrier just adds overheads and complexity to maintenance.

Comment (kandy) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Can I ask you to provide "explain" for queries before/after and version of MySQL you test with.  Because it's hard to believe that many queries works better then one (but some times it's )

File: app/code/Magento/Cron/Model/ResourceModel/Schedule.php (hunk 2 above)
Comment (kandy) [reply app/code/Magento/Cron/Model/ResourceModel/Schedule.php:74]: after back port from 2.3 will be delivered in 2.4 this changes will be irrelevant
Magento will use looks instead status field to  avoid simultaneous running jobs

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php (hunk 3 above)
Comment (kandy) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Also if you have some newrelic/munin/etc stats on this queries from production server will like to see it

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: MySQL 5.7 below.

*Deletion*

Before patch:

```
explain delete FROM `cron_schedule` WHERE (status = 'success') AND (job_code in ('process_email_queue', 'update_reports', 'generate_pos_images', 'process_tryagain', 'migrate_order_payments')) AND (created_at < '2020-04-27 05:43:11');
+----+-------------+---------------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------+
| id | select_type | table         | partitions | type  | possible_keys          | key                    | key_len | ref   | rows | filtered | Extra       |
+----+-------------+---------------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------+
|  1 | DELETE      | cron_schedule | NULL       | range | CRON_SCHEDULE_JOB_CODE | CRON_SCHEDULE_JOB_CODE | 767     | const |  881 |   100.00 | Using where |
+----+-------------+---------------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------+
1 row in set (0.00 sec)
```

After adding index but still using IN for job_code:

```
mysql> explain delete FROM `cron_schedule` WHERE (status = 'success') AND (job_code in ('process_email_queue', 'update_reports', 'generate_pos_images', 'process_tryagain', 'migrate_order_payments')) AND (created_at < '2020-04-27 05:43:11');
+----+-------------+---------------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------+
| id | select_type | table         | partitions | type  | possible_keys                 | key                           | key_len | ref         | rows | filtered | Extra       |
+----+-------------+---------------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------+
|  1 | DELETE      | cron_schedule | NULL       | range | CRON_SCHEDULE_JOB_CODE_STATUS | CRON_SCHEDULE_JOB_CODE_STATUS | 790     | const,const |   69 |   100.00 | Using where |
+----+-------------+---------------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------+
1 row in set (0.00 sec)
```

After patch for a single job_code:

```
mysql> explain delete FROM `cron_schedule` WHERE (status = 'success') AND (job_code = 'migrate_order_payments') AND (created_at < '2020-04-27 05:43:11');
+----+-------------+---------------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------+
| id | select_type | table         | partitions | type  | possible_keys                 | key                           | key_len | ref         | rows | filtered | Extra       |
+----+-------------+---------------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------+
|  1 | DELETE      | cron_schedule | NULL       | range | CRON_SCHEDULE_JOB_CODE_STATUS | CRON_SCHEDULE_JOB_CODE_STATUS | 790     | const,const |   20 |   100.00 | Using where |
+----+-------------+---------------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------+
1 row in set (0.00 sec)
```

*Atomic update of status*

Before patch:

```
explain UPDATE `cron_schedule` AS `current`  LEFT JOIN `cron_schedule` AS `existing` ON existing.job_code = current.job_code AND (existing.executed_at > UTC_TIMESTAMP() - INTERVAL 1 DAY OR existing.executed_at IS NULL) AND existing.status = 'running' SET `current`.`status` = 'running' WHERE (current.schedule_id = '8093526') AND (current.status = 'pending') AND (existing.schedule_id IS NULL);
+----+-------------+----------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------------------+
| id | select_type | table    | partitions | type  | possible_keys          | key                    | key_len | ref   | rows | filtered | Extra                   |
+----+-------------+----------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------------------+
|  1 | UPDATE      | current  | NULL       | const | PRIMARY                | PRIMARY                | 4       | const |    1 |   100.00 | NULL                    |
|  1 | SIMPLE      | existing | NULL       | ref   | CRON_SCHEDULE_JOB_CODE | CRON_SCHEDULE_JOB_CODE | 767     | const |  428 |    10.00 | Using where; Not exists |
+----+-------------+----------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------------------+
2 rows in set (0.00 sec)
```

After patch:

```
explain UPDATE `cron_schedule` AS `current`  LEFT JOIN `cron_schedule` AS `existing` ON existing.job_code = current.job_code AND (existing.executed_at > UTC_TIMESTAMP() - INTERVAL 1 DAY OR existing.executed_at IS NULL) AND existing.status = 'running' SET `current`.`status` = 'running' WHERE (current.schedule_id = '8093507') AND (current.status = 'pending') AND (existing.schedule_id IS NULL);
+----+-------------+----------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------------------+
| id | select_type | table    | partitions | type  | possible_keys                 | key                           | key_len | ref         | rows | filtered | Extra                   |
+----+-------------+----------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------------------+
|  1 | UPDATE      | current  | NULL       | const | PRIMARY                       | PRIMARY                       | 4       | const       |    1 |   100.00 | NULL                    |
|  1 | SIMPLE      | existing | NULL       | ref   | CRON_SCHEDULE_JOB_CODE_STATUS | CRON_SCHEDULE_JOB_CODE_STATUS | 790     | const,const |    1 |    10.00 | Using where; Not exists |
+----+-------------+----------+------------+-------+-------------------------------+-------------------------------+---------+-------------+------+----------+-------------------------+
2 rows in set (0.00 sec)
```

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: MySQL 5.6 is mostly same (of course output differs slightly) except the deletions.

Before patch:

```
mysql> explain DELETE FROM `cron_schedule` WHERE (status = 'status') AND (job_code in ('indexer_reindex_all_invalid', 'indexer_update_all_views', 'indexer_clean_all_changelogs')) AND (created_at < '2020-04-26 12:44:06');;
+----+-------------+---------------+------+------------------------+------+---------+------+------+-------------+
| id | select_type | table         | type | possible_keys          | key  | key_len | ref  | rows | Extra       |
+----+-------------+---------------+------+------------------------+------+---------+------+------+-------------+
|  1 | SIMPLE      | cron_schedule | ALL  | CRON_SCHEDULE_JOB_CODE | NULL | NULL    | NULL |   58 | Using where |
+----+-------------+---------------+------+------------------------+------+---------+------+------+-------------+
1 row in set (0.00 sec)
```

After patch:
(Does not always happen - seems to vary - randomly it does this - randomly it will in fact use the index - I included both variations I spotted when running this constantly over a period time.)

```
mysql> explain DELETE FROM `cron_schedule` WHERE (status = 'status') AND (job_code in ('indexer_reindex_all_invalid', 'indexer_update_all_views', 'indexer_clean_all_changelogs')) AND (created_at < '2020-04-26 12:44:06');;
+----+-------------+---------------+------+-------------------------------+------+---------+------+------+-------------+
| id | select_type | table         | type | possible_keys                 | key  | key_len | ref  | rows | Extra       |
+----+-------------+---------------+------+-------------------------------+------+---------+------+------+-------------+
|  1 | SIMPLE      | cron_schedule | ALL  | CRON_SCHEDULE_JOB_CODE_STATUS | NULL | NULL    | NULL |   12 | Using where |
+----+-------------+---------------+------+-------------------------------+------+---------+------+------+-------------+
1 row in set (0.00 sec)

mysql> explain DELETE FROM `cron_schedule` WHERE (status = 'status') AND (job_code in ('indexer_reindex_all_invalid', 'indexer_update_all_views', 'indexer_clean_all_changelogs')) AND (created_at < '2020-04-26 12:44:06');;
+----+-------------+---------------+-------+-------------------------------+-------------------------------+---------+-------------+------+-------------+
| id | select_type | table         | type  | possible_keys                 | key                           | key_len | ref         | rows | Extra       |
+----+-------------+---------------+-------+-------------------------------+-------------------------------+---------+-------------+------+-------------+
|  1 | SIMPLE      | cron_schedule | range | CRON_SCHEDULE_JOB_CODE_STATUS | CRON_SCHEDULE_JOB_CODE_STATUS | 790     | const,const |    3 | Using where |
+----+-------------+---------------+-------+-------------------------------+-------------------------------+---------+-------------+------+-------------+
1 row in set (0.00 sec)
```

After patch and changing to single, consistent plan:

```
mysql> explain DELETE FROM `cron_schedule` WHERE (status = 'status') AND (job_code = 'indexer_clean_all_changelogs') AND (created_at < '2020-04-26 12:44:06');;
+----+-------------+---------------+-------+-------------------------------+-------------------------------+---------+-------------+------+-------------+
| id | select_type | table         | type  | possible_keys                 | key                           | key_len | ref         | rows | Extra       |
+----+-------------+---------------+-------+-------------------------------+-------------------------------+---------+-------------+------+-------------+
|  1 | SIMPLE      | cron_schedule | range | CRON_SCHEDULE_JOB_CODE_STATUS | CRON_SCHEDULE_JOB_CODE_STATUS | 790     | const,const |    1 | Using where |
+----+-------------+---------------+-------+-------------------------------+-------------------------------+---------+-------------+------+-------------+
1 row in set (0.00 sec)
```

Comment (driskell) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Patch prevents deadlock on both the 5.6 and 5.7 systems.

Granted, for 5.7, you only need the index it seems.

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php [hunk 4]
```diff
@@ -636,6 +640,36 @@ private function cleanupDisabledJobs($groupId)
...
+            $connection->update(
+                $scheduleResource->getMainTable(),
+                [
+                    'status' => \Magento\Cron\Model\Schedule::STATUS_ERROR,
+                    'messages' => 'Time out'
+                ],
+                $connection->quoteInto(
+                    'job_code = ? ' .
+                    'AND status = ? ' .
+                    'AND (executed_at < UTC_TIMESTAMP() - INTERVAL 1 DAY)',
```
Comment (hostep) [inline app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: We should probably make this "1 day" interval configurable in a new field in the backend of Magento per cron group?
Maybe there are cronjob processes out there which take more then 1 day to complete, you never know...

Maybe also split this `cleanupRunningJobs` method out in a new PR, these are two different things, it might make it easier for reviewing if they are in two different PR's?

**Review by VladimirZaets — CHANGES_REQUESTED** [review]
@kandy Hi, do you have any concerns according to queries?
@hostep agree with you, but also we can deliver it as is, and in the second PR refactor and make configuration for it.
@driskell thanks for collaboration. Can you please take care of failed tests?

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php (hunk 3 above)
Comment (kandy) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Just for deletion, replacing `created_at` with  `scheduled_at`   do all work
```
mysql> desc DELETE FROM `cron_schedule` WHERE (status = 'status') AND (job_code in ('indexer_reindex_all_invalid', 'indexer_update_all_views', 'indexer_clean_all_changelogs')) AND (created_at < '2020-04-26 12:44:06');
+----+-------------+---------------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------+
| id | select_type | table         | partitions | type  | possible_keys          | key                    | key_len | ref   | rows | filtered | Extra       |
+----+-------------+---------------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------+
|  1 | DELETE      | cron_schedule | NULL       | range | CRON_SCHEDULE_JOB_CODE | CRON_SCHEDULE_JOB_CODE | 767     | const |    9 |   100.00 | Using where |
+----+-------------+---------------+------------+-------+------------------------+------------------------+---------+-------+------+----------+-------------+
1 row in set (0.00 sec)

mysql> explain DELETE FROM `cron_schedule` WHERE (status = 'status') AND (job_code in ('indexer_reindex_all_invalid', 'indexer_update_all_views', 'indexer_clean_all_changelogs')) AND (scheduled_at < '2020-04-26 12:44:06');
+----+-------------+---------------+------------+-------+----------------------------------------------------------+-----------------------------------+---------+-------+------+----------+-------------+
| id | select_type | table         | partitions | type  | possible_keys                                            | key                               | key_len | ref   | rows | filtered | Extra       |
+----+-------------+---------------+------------+-------+----------------------------------------------------------+-----------------------------------+---------+-------+------+----------+-------------+
|  1 | DELETE      | cron_schedule | NULL       | range | CRON_SCHEDULE_JOB_CODE,CRON_SCHEDULE_SCHEDULED_AT_STATUS | CRON_SCHEDULE_SCHEDULED_AT_STATUS | 5       | const |    1 |   100.00 | Using where |
+----+-------------+---------------+------------+-------+----------------------------------------------------------+-----------------------------------+---------+-------+------+----------+-------------+
1 row in set (0.00 sec)
```

**Comment by kandy** [comment]
I prefer to not change indexes in database, but use exists index and do not split one cleanup queries.
Other stuff looks good for me

**Comment by driskell** [comment]
> I prefer to not change indexes in database, but use exists index and do not split one cleanup queries.
> Other stuff looks good for me

That sounds very fair and it will definitely reduce the impact. I hope to get onto this this week and also look at the test. I'm fairly busy with paid work though so can't guarantee but that's my goal!

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @driskell,
I've just updated list of fixed issues - looks like it's quite big number!

I see that now your changes conflicts with 2.4-develop branch, there were merged related changes in https://github.com/magento/magento2/commit/a6c93fd0b98f5a976899a1dbfc8f1cf8d437f7a3. Could you confirm if this issue still reproducing after applying them?
If still yes - please resolve conflict and look at failing tests.

Definitely this is important fix, thank you for it!

**Comment by ihor-sviziev** [comment]
Hi @driskell,
Will you be able to continue working on your PR?

**Comment by ihor-sviziev** [comment]
Hi @engcom-Charlie,
Could you confirm that linked issues still reproducing on 2.4-develop? 
It looks to me as really important fix, but due to conflict i'm not sure if the issue wasn't fixed already.

**Comment by driskell** [comment]
I'm hoping to check into this today.

**Comment by driskell** [comment]
@ihor-sviziev 

I guess there's a conflict here in goals:

* 2.4-develop aims to suppress deadlocks and retry them - this accounts to a limited failsafe mechanism that could still surface if the deadlock repeats 5 times. I honestly believe the deadlocks are better off fixed. It seems strange to me that one would accept a greater complexity of code in an attempt to hide an error 99% of the time, rather than attempt to fix fully and predictably.

* This PR aimed to resolve the deadlock completely, for both MySQL 5.6 and MySQL 5.7 behaviours, and not require any deadlock retry code.

Secondly, with regards to the deadlock issues I see in our environments. There are 2 kinds. Deadlock on the taking of a job lock as per `ResourceModel/Schedule.php` - there is only an index for job_code and even though it's contained in the query we were seeing deadlocks due to in some cases MySQL believing a scan would be more efficient due to cardinalities of the indexes, and overlapping with locking of other jobs. This is not covered in the current 2.4-develop code. As I remember this was mostly an issue with MySQL 5.6.

Overall the above additional deadlock is why I modified the index. Yet there was a request to remove that change.

If we continue with this PR I'd much prefer to be able to make it do the following (almost opposite to what @kandy requested):
* Add status to the job_code index, to resolve the deadlock in attempting to get a lock.
* Split out the cleanup so it cleans each job individually and does not rely on unpredictable job_code
* Keep the deadlock retry but add warning logs to it - with a note to remove it if no deadlocks occur anymore

File: app/code/Magento/Cron/Model/ResourceModel/Schedule.php (hunk 2 above)
Comment (driskell) [reply app/code/Magento/Cron/Model/ResourceModel/Schedule.php:74]: I couldn't see any change in this area in 2.4

**Comment by ihor-sviziev** [comment]
@kandy 
I do agree with solution suggested by @driskell in https://github.com/magento/magento2/pull/28007#issuecomment-647377451. Could you review it and give your input?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by driskell** [comment]
@ihor-sviziev I pushed a test for the code that cleans up jobs left in a running state beyond the lock timeout, likely due to crash, or because database was migrated to a test platform whilst a cron was running.

Additionally fixed the tests to cover the warning from the retrier and the other changes..

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by kandy** [comment]
@driskell  @ihor-sviziev
I still suggest:
  - use the schedule_at field to increase the query speed instead of adding an index to a field that changes frequently - this will slow down the status entry in the table
- and still do not understand why many queries are better than one

**Review by kandy — CHANGES_REQUESTED** [review]
I agreed that what we have in 2.4 is not enough
I still suggest:
  - use the schedule_at field to increase the query speed instead of adding an index to a field that changes frequently - this will slow down writing the status of job in the table
- and still do not understand why many queries are better than one

**Comment by driskell** [comment]
It is difficult because it doesn’t always happen but even though the code is using columns from an index it doesn’t mean MySQL will use it.

In the case of the checking for existing running job query, this tends to ignore the systems index because the cardinality is very low and it then uses a table scan. For most part we see this only on MySQL 5.6. So making an index with both job code and status pretty prevents that deadlock for us. This query does not contain either created at or scheduled at.

For the delete query we see deadlocks for a similar reason. MySQL starts to table scan at times and this causes deadlocks. With the index above and changing the range to an constant it prevents deadlock for us on 5.6 and 5.7. However, I can see we did speak about swapping scheduled at and created at so I can quickly test this over the next few days on my 5.7 system without the splitting of the range into const.

Just to provide info I can’t test 5.6 anymore as we finished our rollout of 5.7 to the last servers whilst this was open.

https://dev.mysql.com/doc/refman/8.0/en/table-scan-avoidance.html
> You are comparing indexed columns with constant values and MySQL has calculated (based on the index tree) that the constants cover too large a part of the table and that a table scan would be faster. See Section 8.2.1.1, “WHERE Clause Optimization”.

In general the current indexes are not well-chosen for the purposes of the queries running which why I still think at a minimum there is a need for an improved index for the job lock. I’ll test the range query split again with the new suggested column on 5.7 @kandy as revisiting that it might be better

**Comment by kandy** [comment]
@driskell Thanks for the response. I appreciate your desire to improve Magento cron workflow and your deep research.

Please pay attention that minimal supported version of MySQL for 2.4 is 5.7, so there no need to investigate on 5.6 unless you want to back port it to 2.3

**Comment by driskell** [comment]
@kandy I agree. I'll ignore 5.6 going forwards.

However, having tested changing the query to scheduled_at, the index is still ignored in 5.7 at some points.

In my previous tests the combination of an index with job_code AND status, and then using constants in the query instead of a range for job_code (since it is the first part of the index), made it use the index predictably and reliably and avoid the deadlock.

(On a separate note the scheduled_at + status index seems rather odd - normally the ranged part would be as the second part of the index - potentially this is why this index isn't as useful as the constant part is after the ranged part)

```
SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to  
  get lock; try restarting transaction, query was: DELETE FROM `cron_schedule  
  ` WHERE (status = 'missed') AND (job_code in ('process_email_queue', 'gener  
  ate_pos_images', 'process_tryagain', 'migrate_order_payments', 'update_repo  
  rts')) AND (scheduled_at < '2020-06-23 22:28:04')   
```

**Comment by driskell** [comment]
@ihor-sviziev @kandy I've been experimenting more with alternative indexes (to replace all current ones) to avoid the splitting out of the job_code, and testing against 5.7. I'll update when I've finished.

**Comment by driskell** [comment]
@ihor-sviziev @kandy I found in the last 6 days no deadlocks with this new code. Specifically, once I adjusted the index to the new one with status>job_code>scheduled_at, I no longer saw deadlocks on the cleanup queries, and only saw deadlocks on the cron lock query where a cron took a little too long to run and overlapped slightly. By refactoring that to remove the update+join (which shared locks the join before exclusive locking for the update) to instead take exclusive locks with forUpdate for everything, I haven't seen that issue anymore.

So overall change since last reviews:

- No more splitting of the job_code - still uses IN query
- Refactor of the cron locking
- Replaced the two indexes with one shared index that covers all current queries run by the cron_schedule module, and ensured they follow MySQL recommendation of range part of the key being at the end (scheduled_at). 5.7 is able to do IN quite efficiently on the mid-part of the key and appears as (const,const) in queries (I think 5.6 didn't like this but that's now unsupported so no issue.)

Let me know what your thoughts are.

**Review by ihor-sviziev — COMMENTED** [review]
@driskell everything looks good from my side. Only one question - could you explain why you added commit transaction?

**Comment by driskell** [comment]
> @driskell everything looks good from my side. Only one question - could you explain why you added commit transaction?

Where abouts? There is a commit() because there is a startTransaction() followed by a forUpdate() to take exclusive lock on all found rows (rather than shared followed by exclusive which UPDATE LEFT JOIN does and which deadlocks on occasion where cron run overlaps.)

There is a commit() instead of a rollback() in the return where it does no update because it found a running cron already because if you rollback() and you're inside a larger transaction it breaks. In fact I kept getting issues with unclosed transactions when I tried it. So all code paths after the beginTransaction will commit. It shouldn't matter though.

**Comment by ihor-sviziev** [comment]
@driskell thank you for the explanation!

@kandy could your review the latest changes?

@magento run all tests

File: app/code/Magento/Cron/etc/db_schema.xml [hunk 5]
```diff
@@ -21,12 +21,10 @@
         <constraint xsi:type="primary" referenceId="PRIMARY">
             <column name="schedule_id"/>
         </constraint>
-        <index referenceId="CRON_SCHEDULE_JOB_CODE" indexType="btree">
+        <index referenceId="CRON_SCHEDULE_STATUS_JOB_CODE_SCHEDULED_AT" indexType="btree">
+            <column name="status"/>
```
Comment (kandy) [inline app/code/Magento/Cron/etc/db_schema.xml]: In SQL, cardinality refers to the number of distinct elements in a column.  All other considerations aside, when you are defining the key columns for your index, the column with the highest cardinality, or most distinct number of values, should go first.

**Review by kandy — CHANGES_REQUESTED** [review]

File: app/code/Magento/Cron/etc/db_schema.xml (hunk 5 above)
Comment (driskell) [reply app/code/Magento/Cron/etc/db_schema.xml]: Is this a statement or a request to change? What is the problem to be solved? How will this improve things? Do you mean switch status and job_code?

I can try switching status and job code to bring that higher cardinality forwards however the job code is a range query and generally speaking those would usually go to the right not the left.

Also I have done some analysis here and these queries run once a minute over less than a few thousand rows. So this feels like unnecessary optimisation.

Regardless, the status may have low  cardinality but the RUNNING and PENDING values are in fact low numbers, as such the result set is significantly reduced by the first part of the key anyway since those two values are very low numbers. The cleanup queries will need two parts to reduce significantly but as said they run less often.

I can swap but the range aspect of job_code was a concern.

I no longer have time to spend on this either so will need you to test this.

Comment (driskell) [reply app/code/Magento/Cron/etc/db_schema.xml]: Just out of wanting to learn about the behaviour in question I looked up cardinality ordering and could not find any substantive documentation or testing that confirms highest should be first except where not all parts of the key are always used. Most were stack overflow.

I did find other stack overflow links to indexing guides saying it makes no difference.

I guess I’m not understanding things or something but I fail to see any benefit.

As my current understanding goes, indexes are column stores so the status here is a column store of literally single digit size. Navigating the tree will be the same number if leafs no matter what order the index is as you still have to find the job code. Made the other way around it’s the same steps. It will also likely be much smaller in size as the top tree is smaller and not repeated fog the higher cardinality job code.

Maybe I’m missing something here. But I still believe the cost benefit time wise is not worth it as this isn’t a hot path by any means.

**Comment by driskell** [comment]
@kandy @ihor-sviziev I have pushed a swap to the index ordering to bring job_code first, managed to find some time in-between stuff to quickly test it and it looks to be still no deadlocks. Scheduled at being a proper range I left as the last. I don't think it makes a huge difference due to it not being hot path and I can't say I fully understand why it matters as the BTREE seems like it would still require the same number of traversals - but if it gets an agreement then I'm all for it!

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@kandy could you check this PR again? From y perspective looks good, but need to review and fix all failing tests.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @driskell,
I see that all concerns from @kandy were already fixed, and unfortunately he don't respond on asked review for a long time.

I believe we can go with this solution. Could you review & fix failing tests and I'll approve your PR to move it forward?

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Cron/Test/Unit/Observer/ProcessCronQueueObserverTest.php [hunk 6]
```diff
@@ -1078,11 +1078,29 @@ public function testMissedJobsCleanedInTime()
             )
             ->willReturn(1);
 
-        $this->scheduleResourceMock->expects($this->exactly(5))
+        $connectionMock->expects($this->once())
+            ->method('quoteInto')
+            ->with(
+                'status = ? AND job_code IN (?) AND (scheduled_at < UTC_TIMESTAMP() - INTERVAL 1 DAY)',
+                ['test_job1'],
+                'running'
```
Comment (driskell) [inline app/code/Magento/Cron/Test/Unit/Observer/ProcessCronQueueObserverTest.php]:
```suggestion
                'status = ? AND job_code IN (?) AND (scheduled_at < UTC_TIMESTAMP() - INTERVAL 1 DAY)',
                'running',
                ['test_job1']
```

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php [hunk 7]
```diff
@@ -696,6 +697,33 @@ private function cleanupDisabledJobs($groupId)
         }
     }
 
+    /**
+     * Cleanup jobs that were left in a running state due to an unexpected stop
+     *
+     * @param string $groupId
+     * @return void
+     */
+    private function cleanupRunningJobs($groupId)
```
Comment (sidolov) [inline app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Please, add strict types

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php [hunk 8]
```diff
@@ -696,6 +697,33 @@ private function cleanupDisabledJobs($groupId)
...
+        $scheduleResource = $this->_scheduleFactory->create()->getResource();
+        $connection = $scheduleResource->getConnection();
+
+        $jobs = $this->_config->getJobs();
+
+        $connection->update(
+            $scheduleResource->getTable('cron_schedule'),
+            [
+                'status' => \Magento\Cron\Model\Schedule::STATUS_ERROR,
+                'messages' => 'Time out'
```
Comment (sidolov) [inline app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php:718]: Should it be translated?

**Review by sidolov — CHANGES_REQUESTED** [review]

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php (hunk 8 above)
Comment (ihor-sviziev) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php:718]: I don't think it's a good idea to have translated messages in DB. I believe if needed - it could be translated on presentation layer (magento don't have it).

File: app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php (hunk 7 above)
Comment (ihor-sviziev) [reply app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php]: Added

**Comment by ihor-sviziev** [comment]
@magento run Static Tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8074](https://jira.corp.magento.com/browse/ENGCOM-8074) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
Hi @driskell,
Seems like we need to revert changes from https://github.com/magento/magento2/pull/27391 as they're fixing the same issue, what do you thing?

**Comment by driskell** [comment]
@ihor-sviziev Yes you're right. I did merge in 2.4-develop and saw that conflict but thought it was unrelated. In this PR we removed the status condition from the query as it now does a transactional lock. So yes I have now reverted that PR changes in this PR as the changes here would supersede it and fix not only the issues reported here but also the issue reported in #27391

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8074](https://jira.corp.magento.com/browse/ENGCOM-8074) has been created to process this Pull Request

File: app/code/Magento/Cron/etc/db_schema_whitelist.json [hunk 9]
```diff
@@ -13,7 +13,8 @@
         "index": {
             "CRON_SCHEDULE_JOB_CODE": true,
             "CRON_SCHEDULE_SCHEDULED_AT_STATUS": true,
-            "CRON_SCHEDULE_SCHEDULE_ID_STATUS": true
+            "CRON_SCHEDULE_SCHEDULE_ID_STATUS": true,
```
Comment (driskell) [inline app/code/Magento/Cron/etc/db_schema_whitelist.json:16]: @ihor-sviziev Thanks again for working through this.

Did it need this addition for tests? It's strange as in the db_schema.xml I reverted that index addition, it's not there in this PR anymore. Seems strange - maybe the test runner isn't seeing the removal properly?

Comment (ihor-sviziev) [reply app/code/Magento/Cron/etc/db_schema_whitelist.json:16]: Basically it was needed for fixing SVC failure.
In general this file contrails the list of indexes that it could manage. So as we don't have this index in the db_schema.xml anymore - it will be automatically removed. In case if it wasn't present in your DB - it will not be created also.

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
Hi all, updates on this PR.

We have set up two instances internally following the steps to reproduce from @driskell, one instance has the fixes from this PR and the other one doesn't.

We will leave it running for some time and get the results, we will be updating you as soon as we have the results.

Thanks.

**Comment by gabrieldagama** [comment]
@magento run Functional Tests B2B,Integration Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by ihor-sviziev** [comment]
@gabrieldagama any updates on this?

**Comment by ihor-sviziev** [comment]
@sidolov @gabrieldagama any updates on this?

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B

**Comment by gabrieldagama** [comment]
@ihor-sviziev I will be checking the results and report it here soon.

**Comment by ihor-sviziev** [comment]
@gabrieldagama any updates?

**Comment by gabrieldagama** [comment]
Hi @ihor-sviziev @driskell 

After leaving two instances running (Magento Cloud) with cronjobs updating thousands of products and stocks, one with the fix, and another without it, we were unable to see the error being reproduced on the vanilla instance, the instance with the code from this PR also didn't have any deadlock problems.

We've tried to follow the steps to reproduce to get the results but weren't able to, I will try to escalate this internally to see how we can proceed with such changes.

**Comment by ihor-sviziev** [comment]
@gabrieldagama I believe you have to have real production website with the orders and actual email sending through cron jobs, some other heavy corn jobs and so on, only in this case you'll see such issue, and unfortunately not every time

**Comment by jonnysowards** [comment]
@gabrieldagama If running a big enough database instance allowing for enough connections to the database to run simultaneously, Magento will never hit the deadlock. If running on a server with limited resources and not as many connections to the database, without this pull request, Magento will hit deadlocks after a few cron runs. We are running an instance with 87000 products. We have upped our resources and worked around this but Magento is using many more resources than necessary when this pull request is not applied.

**Comment by bubasuma** [comment]
Hi everyone,

I think some changes in this pull request are no longer actual for 2.4.x

Similar issue was fixed in scope of MC-25132 and the fix is already in 2.4.x (see commits here https://github.com/magento/magento2/search?q=MC-25132&type=commits). Magento no longer uses cron_schedule.status for locking, it now uses lock manager (\Magento\Framework\Lock\LockManagerInterface) to acquire lock.

Some WHERE clauses are not aligned with the new index columns order (job_code, status, scheduled_at). For instance in the new method ProcessCronQueueObserver::cleanupRunningJobs, the columns order in the WHERE clause is (status, job_code, scheduled_at) and same order can be observed in many other places in ProcessCronQueueObserver.

Additionally, I propose the following changes in \Magento\Cron\Model\ResourceModel\Schedule::trySetJobStatusAtomic since \Magento\Cron\Model\ResourceModel\Schedule::trySetJobUniqueStatusAtomic is not longer used.

```php
    public function trySetJobStatusAtomic($scheduleId, $newStatus, $currentStatus)
    {
        $connection = $this->getConnection();
        $select = $connection->select()
            ->from(
                $this->getTable('cron_schedule'),
                [
                    'status'
                ]
            )
            ->where(
                'schedule_id = ?',
                $scheduleId
            );
        $actualStatus = $connection->fetchOne($select);

        $result = false;
        if ($actualStatus === $currentStatus) {
            $result = $connection->update(
                $this->getTable('cron_schedule'),
                ['status' => $newStatus],
                ['schedule_id = ?' => $scheduleId]
            );
        }

        return (bool)$result;
    }
```

Please let me know your thoughts!

cc: @driskell  @ihor-sviziev

**Comment by driskell** [comment]
@bubasuma I can’t see what the proposed change is there but it looks to be no longer atomic. With a lock manager in use though maybe it isn’t needing to be but that makes a naming issue.

**Comment by bubasuma** [comment]
@driskell 
I am referring to these lines
https://github.com/magento/magento2/blob/dda5c72c9303f9476ce7041743c87079cada87f6/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L857
https://github.com/magento/magento2/blob/6dd0bb69333c549d2267cfc7a054eb66da1deadf/app/code/Magento/Cron/Model/Schedule.php#L294-L303

File: app/code/Magento/Cron/Model/DeadlockRetrier.php [hunk 10]
```diff
@@ -30,6 +44,7 @@ public function execute(callable $callback, AdapterInterface $connection)
             try {
                 return $callback();
             } catch (DeadlockException $e) {
+                $this->logger->warning(sprintf("Deadlock detected in cron cleanup: %s", $e->getMessage()));
```
Comment (bubasuma) [inline app/code/Magento/Cron/Model/DeadlockRetrier.php]: Deadlock retrier does not retry only DELETE queries but UPDATE queries as well.
https://github.com/magento/magento2/blob/6dd0bb69333c549d2267cfc7a054eb66da1deadf/app/code/Magento/Cron/Model/Schedule.php#L282-L291

```suggestion
                $this->logger->warning(sprintf("Deadlock detected in cron: %s", $e->getMessage()));
```

**Comment by driskell** [comment]
> @driskell
> I am referring to these lines
> 
> https://github.com/magento/magento2/blob/dda5c72c9303f9476ce7041743c87079cada87f6/app/code/Magento/Cron/Observer/ProcessCronQueueObserver.php#L857
> 
> 
> https://github.com/magento/magento2/blob/6dd0bb69333c549d2267cfc7a054eb66da1deadf/app/code/Magento/Cron/Model/Schedule.php#L294-L303

I'm sorry I'm not following. You said you "proposed following changes" and gave code for trySetJobStatusAtomic but these are code from two other functions. What is the change proposed exactly?

**Comment by bubasuma** [comment]
@driskell 
Sorry for confusion,
I am concerned about your changes in \Magento\Cron\Model\ResourceModel\Schedule::trySetJobUniqueStatusAtomic which is no longer used. It's fine to leave those changes but they have no impact on current code. The two lines of code I mentioned only demonstrate that job locking is now managed by Framework Lock Manager and that instead of trySetJobUniqueStatusAtomic, trySetJobStatusAtomic is now used to update the job status.

The proposed changes is for  \Magento\Cron\Model\ResourceModel\Schedule::trySetJobStatusAtomic (different from trySetJobUniqueStatusAtomic) which is actually used here. 
https://github.com/magento/magento2/blob/6dd0bb69333c549d2267cfc7a054eb66da1deadf/app/code/Magento/Cron/Model/Schedule.php#L294-L303

**Comment by driskell** [comment]
@bubasuma I think I understand now. I don't think that change would be necessary. If indeed the trySetJobStatusAtomic is behind a lock then there is no instance where the job won't be run so it should always update the status, as it does not. The reason trySetJobStatusUniqueAtomic was doing the forUpdate and checks was to "tie break" in the event multiple cron threads attempted to obtain the job. However, in this case, locker already has it.

Log change is definitely wise - you're right it is tried from multiple places. In all honesty I had hoped the retries could be removed.

I've never been happy personally with this retries as it only ever serves to make the "in the wild" occurrences rarer and more difficult to reproduce such that it happens so rarely due to the retries that diagnosis is practically impossible - though I guess the irony maybe to just throw more retries at it 😆

**Comment by sidolov** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

The overall functionality of cron has been tested and the jobs are performed properly.

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Magento Health Index, WebAPI Tests

**Comment by ihor-sviziev** [comment]
🎉 finally, this amazing fix got merged! Thank you so much @driskell for your contribution!
I hope it will not introduce any new issues.

**Comment by kilis** [comment]
[This](https://github.com/magento/magento2/issues/25987) issue still exists after this fix.

**Comment by hostep** [comment]
@kilis: you might need the changes from [MC-25132](https://github.com/magento/magento2/search?q=MC-25132&type=commits) as well, this was mentioned above in https://github.com/magento/magento2/pull/28007#issuecomment-732481542

**Comment by kilis** [comment]
@hostep 
I moved entire cron module from 2.4 to 2.3.5-p2 as a patch. I do not understand what else is missing.
[deadlock-fix.patch.txt](https://github.com/magento/magento2/files/5861934/deadlock-fix.patch.txt)

**Comment by hostep** [comment]
@kilis: me neither, sorry, I just tried to point you to a certain comment in case you didn't notice it.

If you can reproduce the problem on a Magento `2.4-develop` installation, I'd strongly suggest you open a new issue with detailed steps about how to reproduce it (even though that's probably hard to get right).
