### PR TITLE
magento/magento2#27952: missing store_name in GraphQL resolver - adde…

### LINKED ISSUE #27952: Missing store_name in GraphQl Resolver
### Preconditions (*)

1. Magento 2.3.4

### Steps to reproduce (*)

1. Request for store_name in storeConfig Query

### Expected result (*)

1. Return store name 
```json
{
  "data":{
       "storeConfig":{
               "root_category_id":2,
               "store_name": "Magento"
        }
}
```

### Actual result (*)

```json
{
  "data":{
       "storeConfig":{
               "root_category_id":2,
               "store_name": null
        }
}
```

As Mentioned in schema 'store_name' can be queried 

https://github.com/magento/magento2/blob/d4a90989db911a27af3aa9ce81c1f6d9f7b1f0f4/app/code/Magento/StoreGraphQl/etc/schema.graphqls#L33

But in `StoreConfigDataProvider.php` its not resolved

https://github.com/magento/magento2/blob/d4a90989db911a27af3aa9ce81c1f6d9f7b1f0f4/app/code/Magento/StoreGraphQl/Model/Resolver/Store/StoreConfigDataProvider.php#L71-L94

### PR DESCRIPTION
**Pull request by sasha19957099**
…d store_name

### Fixed Issues (if relevant)

1. Fixes magento/magento2#<issue_number>

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sasha19957099** [comment]
@magento run all tests

File: app/code/Magento/StoreGraphQl/Model/Resolver/Store/StoreConfigDataProvider.php [hunk 1]
```diff
@@ -55,11 +55,10 @@ public function __construct(
      */
     public function getStoreConfigData(StoreInterface $store): array
     {
-        $storeConfigData = array_merge(
-            $this->getBaseConfigData($store),
-            $this->getExtendedConfigData((int)$store->getId())
+        return array_merge(
```
Comment (danielrenaud) [inline app/code/Magento/StoreGraphQl/Model/Resolver/Store/StoreConfigDataProvider.php:58]: I don't think we should swap these, it will change behavior in a way we may not want. If store_name is getting overwritten, you should remove this in di.xml
``` <type name="Magento\StoreGraphQl\Model\Resolver\Store\StoreConfigDataProvider">
        <arguments>
            <argument name="extendedConfigData" xsi:type="array">
                <item name="store_name" xsi:type="string">store/information/name</item>
            </argument>
        </arguments>
    </type>```

File: app/code/Magento/StoreGraphQl/Model/Resolver/Store/StoreConfigDataProvider.php [hunk 2]
```diff
@@ -88,9 +87,9 @@ private function getBaseConfigData(StoreInterface $store) : array
             'secure_base_url' => $storeConfig->getSecureBaseUrl(),
             'secure_base_link_url' => $storeConfig->getSecureBaseLinkUrl(),
             'secure_base_static_url' => $storeConfig->getSecureBaseStaticUrl(),
-            'secure_base_media_url' => $storeConfig->getSecureBaseMediaUrl()
+            'secure_base_media_url' => $storeConfig->getSecureBaseMediaUrl(),
+            'store_name' => $storeConfig->getStoreName()
```
Comment (danielrenaud) [inline app/code/Magento/StoreGraphQl/Model/Resolver/Store/StoreConfigDataProvider.php]: While you're changes look correct, I just wonder if we could do it in a less disruptive way. The current approach introduces a backwards incompatible change because we're adding a new public method to an @api interface.

Could we just use $store->getName() here and avoid the changes outside of GraphQl area?

File: composer.lock [hunk 3]
```diff
@@ -4,7 +4,7 @@
         "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies",
         "This file is @generated automatically"
     ],
-    "content-hash": "e86af25d9a4a1942c437cca58f9f1efb",
+    "content-hash": "f3674961f96b48fdd025a6c94610c8eb",
```
Comment (danielrenaud) [inline composer.lock]: We shouldn't need to update composer.lock for this

**Review by danielrenaud — CHANGES_REQUESTED** [review]

File: composer.lock (hunk 3 above)
Comment (sasha19957099) [reply composer.lock]: yes, but without it, local static test fails

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run all tests

File: app/code/Magento/Store/Api/Data/StoreConfigInterface.php [hunk 4]
```diff
@@ -7,7 +7,7 @@
 
 /**
  * StoreConfig interface
- *
+ * Interface for store config
```
Comment (danielrenaud) [inline app/code/Magento/Store/Api/Data/StoreConfigInterface.php:9]: For each of these where you update the class description, can you remove the old, useless description. and add a new line
so for this one it would be
```
/**
 * Interface for store config
 *
 * @api
```

File: composer.lock (hunk 3 above)
Comment (danielrenaud) [reply composer.lock]: Ok, so actually this change matches the hash in mainline, so I don't know why it is showing up as a change here. Maybe just need to sync up your branch. But it should be fine.

**Review by danielrenaud — CHANGES_REQUESTED** [review]
looks good.
Just a minor static fix for class descriptions.

**Review by danielrenaud — APPROVED** [review]

**Comment by sasha19957099** [comment]
@magento run all tests
