### PR TITLE
Fix(admin): correct datepicker position inside modal-slide

### LINKED ISSUE #40169: 2.4.8-p2 datepicker - position is on the top of the website
### Preconditions and environment

- 2.4.8-p2

### Steps to reproduce

1. Enter admin portal
2. catalog->product -> edit a product
3. click datepicker

### Expected result

**the datepick calendar selector display in the top of the website, need to scroll to the top of website then can see the calendar selector**

Image

Image

### Actual result

the datepicker calendar selector will display near the datepicker button.

### Additional information

referrence issue ticket 2.4.8-p1 datepicker - position is wrong on touch devices #40083 

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### LINKED ISSUE #40468: [Issue] Fix(admin): correct datepicker position inside modal-slide
This issue is automatically created based on existing pull request: magento/magento2#40225: Fix(admin): correct datepicker position inside modal-slide

---------
### Description (*)
This pull request fixes an issue where the Magento datepicker does not display correctly inside admin modal dialogs.  
For example, this affected the Advanced Pricing section when editing or creating a product from the admin panel.

image

To solve this problem, the `_findPos` method of `$.datepicker` has been overridden to use `getBoundingClientRect()` for elements inside `.modal-slide`. This ensures that the datepicker is positioned correctly relative to the modal.

image

### Related Pull Requests
No related pull requests, but a related commit: https://github.com/magento/magento2/commit/15ce3863df0aa82dbffff10b3e5dd091e59f8be8#diff-19864376467a02afb70b63ab2fe8ca2c232de016f4ae9593c61f7af293dec403

### Fixed Issues (if relevant)
1. Fixes magento/magento2#40169 - restores proper datepicker behavior in admin modal dialogs while preserving the current logic for general datepickers. This resolves the previous issue where fixes for general dialogs broke modal dialogs.

### Manual testing scenarios (*)
1. Log in to the Magento admin panel.
2. Navigate to Catalog → Products.
3. Click Edit on any existing product, or Add Product to create a new one.
4. In the Price section, click Advanced Pricing.
5. Inside the modal, click in one of the date fields. The datepicker should appear correctly positioned relative to the input field.

### Questions or comments
No additional comments.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### PR DESCRIPTION
**Pull request by angelvilaplana**
### Description (*)
This pull request fixes an issue where the Magento datepicker does not display correctly inside admin modal dialogs.  
For example, this affected the Advanced Pricing section when editing or creating a product from the admin panel.

image

To solve this problem, the `_findPos` method of `$.datepicker` has been overridden to use `getBoundingClientRect()` for elements inside `.modal-slide`. This ensures that the datepicker is positioned correctly relative to the modal.

image

### Related Pull Requests
No related pull requests, but a related commit: https://github.com/magento/magento2/commit/15ce3863df0aa82dbffff10b3e5dd091e59f8be8#diff-19864376467a02afb70b63ab2fe8ca2c232de016f4ae9593c61f7af293dec403

### Fixed Issues (if relevant)
1. Fixes magento/magento2#40169 - restores proper datepicker behavior in admin modal dialogs while preserving the current logic for general datepickers. This resolves the previous issue where fixes for general dialogs broke modal dialogs.

### Manual testing scenarios (*)
1. Log in to the Magento admin panel.
2. Navigate to Catalog → Products.
3. Click Edit on any existing product, or Add Product to create a new one.
4. In the Price section, click Advanced Pricing.
5. Inside the modal, click in one of the date fields. The datepicker should appear correctly positioned relative to the input field.

### Questions or comments
No additional comments.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### Resolved issues:
1. [x] resolves magento/magento2#40468: Fix(admin): correct datepicker position inside modal-slide

### CODE REVIEW

File: lib/web/mage/calendar.js [hunk 1]
```diff
@@ -104,7 +104,8 @@ define([
 
         _overwriteFindPos: function () {
             $.datepicker.constructor.prototype._findPos = function (obj) {
-                var position = $(obj).offset();
+                let isInModalSlide = $(obj).closest('.modal-slide').length > 0,
```
Comment (sprankhub) [inline lib/web/mage/calendar.js]:
```suggestion
                var isInModalSlide = $(obj).closest('.modal-slide').length > 0,
```

I agree that in general, `let` / `const` is better. However, according to https://developer.adobe.com/commerce/php/coding-standards/js/#variable-declarations and looking at the other JS code in this folder, we should use `var`.

**Review by sprankhub — CHANGES_REQUESTED** [review]

File: lib/web/mage/calendar.js (hunk 1 above)
Comment (angelvilaplana) [reply lib/web/mage/calendar.js]: The change has been committed. Thanks for the comment @sprankhub. I wasn’t aware of this JavaScript standard.

**Review by sprankhub — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests
