### PR TITLE
Fix incompatibility with laminas-escaper (2.7.1)

### LINKED ISSUE #33346: Latest laminas/laminas-escaper (2.7.0 -> 2.7.1) breaks product and catalog category view pages
### Preconditions (*)

Install 2.4.2-p1 or run composer-update on an existing install that hasn't been run in hours since 2.7.1 was release. 

### Steps to reproduce (*)
View any page with callout for 

`<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>`

Might be more widespread than this, but this is how I noticed it.

Happened on a client's instance, thought it might be related to one of their many 3rd party extensions. Quickly installed a blank 2.4.2-p1 instance w/sample data. Saw the result

### Expected result (*)

Page loads

### Actual result (*)

Screenshot 2021-06-24 at 16-18-36 https 242test loc

Partial page load with stack trace output

`TypeError: rawurlencode() expects parameter 1 to be string, bool given in /shared/httpd/242test/htdocs/vendor/laminas/laminas-escaper/src/Escaper.php:246 Stack trace: #0 /shared/httpd/242test/htdocs/vendor/laminas/laminas-escaper/src/Escaper.php(246): rawurlencode(true) #1 /shared/httpd/242test/htdocs/vendor/magento/framework/Escaper.php(286): Laminas\Escaper\Escaper->escapeUrl(true) #2 /shared/httpd/242test/htdocs/vendor/magento/framework/Url/RouteParamsResolver.php(115): Magento\Framework\Escaper->encodeUrlParam(true) #3 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Url\RouteParamsResolver->setRouteParams(Array, false) #4 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Url\RouteParamsResolver\Interceptor->___callParent('setRouteParams', Array) #5 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Url\RouteParamsResolver\Interceptor->Magento\Framework\Interception\{closure}(Array, false) #6 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/Url/RouteParamsResolver/Interceptor.php(23): Magento\Framework\Url\RouteParamsResolver\Interceptor->___callPlugins('setRouteParams', Array, Array) #7 /shared/httpd/242test/htdocs/vendor/magento/framework/Url.php(716): Magento\Framework\Url\RouteParamsResolver\Interceptor->setRouteParams(Array, false) #8 /shared/httpd/242test/htdocs/vendor/magento/framework/Url.php(747): Magento\Framework\Url->_setRouteParams(Array, false) #9 /shared/httpd/242test/htdocs/vendor/magento/framework/Url.php(929): Magento\Framework\Url->getRouteUrl('', Array) #10 /shared/httpd/242test/htdocs/vendor/magento/framework/Url.php(873): Magento\Framework\Url->createUrl('', Array) #11 /shared/httpd/242test/htdocs/vendor/magento/module-catalog/Model/Product/Url.php(199): Magento\Framework\Url->getUrl('', Array) #12 /shared/httpd/242test/htdocs/vendor/magento/module-review/Block/Product/ReviewRenderer.php(149): Magento\Catalog\Model\Product\Url->getUrl(Object(Magento\Catalog\Model\Product\Interceptor), Array) #13 /shared/httpd/242test/htdocs/generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(59): Magento\Review\Block\Product\ReviewRenderer->getReviewsUrl(false) #14 /shared/httpd/242test/htdocs/vendor/magento/module-review/view/frontend/templates/helper/summary.phtml(12): Magento\Review\Block\Product\ReviewRenderer\Interceptor->getReviewsUrl() #15 /shared/httpd/242test/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/shared/httpd/2...') #16 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Review\Block\Product\ReviewRenderer\Interceptor), '/shared/httpd/2...', Array) #17 /shared/httpd/242test/htdocs/generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(122): Magento\Framework\View\Element\Template->fetchView('/shared/httpd/2...') #18 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/Template.php(303): Magento\Review\Block\Product\ReviewRenderer\Interceptor->fetchView('/shared/httpd/2...') #19 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #20 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #21 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #22 /shared/httpd/242test/htdocs/generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(347): Magento\Framework\View\Element\AbstractBlock->toHtml() #23 /shared/httpd/242test/htdocs/vendor/magento/module-review/Block/Product/ReviewRenderer.php(111): Magento\Review\Block\Product\ReviewRenderer\Interceptor->toHtml() #24 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Review\Block\Product\ReviewRenderer->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), 'default', true) #25 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Review\Block\Product\ReviewRenderer\Interceptor->___callParent('getReviewsSumma...', Array) #26 /shared/httpd/242test/htdocs/vendor/yotpo/magento2-module-yotpo-reviews/Plugin/Review/Block/Product/ReviewRenderer.php(32): Magento\Review\Block\Product\ReviewRenderer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false, true) #27 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Yotpo\Yotpo\Plugin\Review\Block\Product\ReviewRenderer->aroundGetReviewsSummaryHtml(Object(Magento\Review\Block\Product\ReviewRenderer\Interceptor), Object(Closure), Object(Magento\Catalog\Model\Product\Interceptor), false, true) #28 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Review\Block\Product\ReviewRenderer\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Catalog\Model\Product\Interceptor), false, true) #29 /shared/httpd/242test/htdocs/generated/code/Magento/Review/Block/Product/ReviewRenderer/Interceptor.php(32): Magento\Review\Block\Product\ReviewRenderer\Interceptor->___callPlugins('getReviewsSumma...', Array, NULL) #30 /shared/httpd/242test/htdocs/vendor/magento/module-catalog/Block/Product/AbstractProduct.php(221): Magento\Review\Block\Product\ReviewRenderer\Interceptor->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), false, true) #31 /shared/httpd/242test/htdocs/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(176): Magento\Catalog\Block\Product\AbstractProduct->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), false, true) #32 /shared/httpd/242test/htdocs/vendor/magento/module-catalog/view/frontend/templates/product/view/review.phtml(8): Magento\Catalog\Block\Product\View\Interceptor->getReviewsSummaryHtml(Object(Magento\Catalog\Model\Product\Interceptor), false, true) #33 /shared/httpd/242test/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/shared/httpd/2...') #34 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/Template.php(273): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Catalog\Block\Product\View\Interceptor), '/shared/httpd/2...', Array) #35 /shared/httpd/242test/htdocs/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(383): Magento\Framework\View\Element\Template->fetchView('/shared/httpd/2...') #36 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/Template.php(303): Magento\Catalog\Block\Product\View\Interceptor->fetchView('/shared/httpd/2...') #37 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(1111): Magento\Framework\View\Element\Template->_toHtml() #38 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(1115): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() #39 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(675): Magento\Framework\View\Element\AbstractBlock->_loadCache() #40 /shared/httpd/242test/htdocs/generated/code/Magento/Catalog/Block/Product/View/Interceptor.php(608): Magento\Framework\View\Element\AbstractBlock->toHtml() #41 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(578): Magento\Catalog\Block\Product\View\Interceptor->toHtml() #42 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('product.info.re...') #43 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('product.info.re...') #44 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.re...') #45 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('product.info.re...', false) #46 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.re...', false) #47 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('product.info.ma...', false) #48 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('product.info.ma...') #49 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('product.info.ma...') #50 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('product.info.ma...', false) #51 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('product.info.ma...', false) #52 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('content', false) #53 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('content') #54 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content') #55 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('content', false) #56 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('content', false) #57 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main', false) #58 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('main') #59 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main') #60 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('main', false) #61 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('main', false) #62 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('columns', false) #63 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('columns') #64 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('columns') #65 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('columns', false) #66 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('columns', false) #67 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('main.content', false) #68 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('main.content') #69 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.content') #70 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('main.content', false) #71 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('main.content', false) #72 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false) #73 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper') #74 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper') #75 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('page.wrapper', false) #76 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper', false) #77 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false) #78 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(149): Magento\Framework\View\Layout->renderNonCachedElement('root') #79 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root') #80 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(140): Magento\Framework\View\Layout->renderElement('root', true) #81 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout\Interceptor->renderElement('root') #82 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput() #83 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array) #84 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}() #85 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(347): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array) #86 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Result/Page.php(258): Magento\Framework\View\Layout\Interceptor->getOutput() #87 /shared/httpd/242test/htdocs/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor)) #88 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #89 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array) #90 /shared/httpd/242test/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor)) #91 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(95): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array) #92 /shared/httpd/242test/htdocs/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor)) #93 /shared/httpd/242test/htdocs/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #94 /shared/httpd/242test/htdocs/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #95 /shared/httpd/242test/htdocs/pub/index.php(29): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #96 {main}`

### Resolution (*)

Force composer to use 2.7.0 and reload page, page loads with no issues.

- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._

### PR DESCRIPTION
**Pull request by tufahu**
### Description
laminas/laminas-escaper 2.7.1 use strict types and it breaks magento framework escaper

### Fixed Issues
1. Fixes magento/magento2#33346

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Hi @tufahu,
Could you cover your changes with unit test?

**Comment by thomas-kl1** [comment]
@ihor-sviziev is it a kind of joke?

**Comment by ihor-sviziev** [comment]
@thomas-kl1, no, it's not. We definitely have a new case that isn't covered with any type of test. That's why we're having this issue.
I think it would be effortless to cover it with a unit test.

**Comment by hostep** [comment]
This is a super important fix, this needs to be turned into a hotfix ASAP in my opinion, maybe it's worth adding this to Magento's quality patches repo as well.

Thanks @tufahu !

**Comment by thomas-kl1** [comment]
> That's why we're having this issue.
I think it would be effortless to cover it with a unit test.

@ihor-sviziev maybe as a maintainer you could push for strict and proper type signatures in method. Such unit tests doesn't belongs there when it's well typed..

**Comment by tufahu** [comment]
Hey, i'm not sure how to correctly unit test this issue, i've tried my best.

**Review by thomas-kl1 — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@sivaschenko @gabrieldagama @sidolov, please set priority to p1 for this PR. It's super important. Otherwise, we'll have a lot of type errors here and there.

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-9133](https://jira.corp.magento.com/browse/ENGCOM-9133) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@thomas-kl1, yeah, that's true! It would be nice! But, unfortunately, we can't break so much backward compatibility. Adding strict types everywhere will cause not obvious issues, like this - TypeError in code that using this library and in some cases passes null or integer.

**Review by ghost — APPROVED** [review]
Work for me

**Review by Den4ik — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @Den4ik, thank you for the review.
[ENGCOM-9133](https://jira.corp.magento.com/browse/ENGCOM-9133) has been created to process this Pull Request

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by Den4ik** [comment]
Failed Unit Tests looks like non related

**Comment by hostep** [comment]
Would be nice if tests can also be run while `laminas/laminas-escaper` is at version 2.7.1 in the `composer.lock` file. With (and maybe first without?) this fix and look at the differences?

**Comment by ihor-sviziev** [comment]
@hostep i think it might be done as part of test process

**Comment by Den4ik** [comment]
@magento run functional Tests EE

**Comment by thomas-kl1** [comment]
> @thomas-kl1, yeah, that's true! It would be nice! But, unfortunately, we can't break so much backward compatibility. Adding strict types everywhere will cause not obvious issues, like this - TypeError in code that using this library and in some cases passes null or integer.

TypeError has only 3 reasons to happen, it's not obscure, and you can read, code and debug so it's ok :) if it comes to "we don't know why null or integer is passed" you should be worried about the Magento code base, not about strict types..

Anyway I've seen you "approved" related changes to remove "declare(strict_types=1);" in laminas escaper. It's obvious that it's simpler to try to modify third party libraries than actually trying to fix 2 lines of code in Magento (honestly that kind of fix should be an official patch within 5 hours after the discovery)

File: lib/internal/Magento/Framework/Escaper.php [hunk 1]
```diff
@@ -291,7 +291,7 @@ public function escapeUrl($string)
      */
     public function encodeUrlParam($string)
     {
-        return $this->getEscaper()->escapeUrl($string);
+        return $this->getEscaper()->escapeUrl((string)$string);
```
Comment (shyim) [inline lib/internal/Magento/Framework/Escaper.php:294]: I would recommend throwing a deprecation when the passed value is not a string. Casting anything to a string is a workaround and not a fix.

```
if (!is_string($string)) {
  trigger_error(sprintf('Argument #1 passed to %s:%s needs to be an string, but got %s. In future versions this will throw an error', __CLASS__, __METHOD__, gettype($string)), E_USER_DEPRECATED);
}

**Comment by carnage** [comment]
Upgrading to Laminas escaper 2.8.0 (release a few hours ago) will resolve this issue as well. 

Might be worth fixing the dependency in composer.json to ^2.8.0 either instead of or in addition to this PR.

**Comment by hostep** [comment]
Now that 2.8.0 of `laminas/laminas-escaper` is out, the priority of this PR can probably be lowerd a bit and we should probably now also investigate all callers of the `encodeUrlParam` and `escapeCss` methods in core Magento to make sure they always pass a string.
One such example is over here: https://github.com/magento/magento2/blob/2.4.2/lib/internal/Magento/Framework/Url/RouteParamsResolver.php#L114-L115 where you can pass any scalar value, so the string conversion should probably already be done over there.

File: lib/internal/Magento/Framework/Escaper.php (hunk 1 above)
Comment (orlangur) [reply lib/internal/Magento/Framework/Escaper.php:294]: Why do we add string casting for a method which was never intended to support anything but strings? https://github.com/magento/magento2/blob/94e140fc16ba280f80580ec8eba02e38cd11d98a/lib/internal/Magento/Framework/Escaper.php#L294 Adding proper type to method signature + fix incorrect usages seems more robust to me.

**Comment by orlangur** [comment]
> Adding strict types everywhere will cause not obvious issues, like this - TypeError in code that using this library and in some cases passes null or integer.

Which means bugs in code will be just hidden by such type casting. If we don't apply "fail fast" here at least we should address proper strict types in 2.5 immediately.

I don't think it was ever a P0 as there is an easy workaround of freezing incompatible dependency version. As a new version of laminas-escaper is released please no hacks in Magento code, just do a complete fix and mark bad version using https://getcomposer.org/doc/04-schema.md#conflict.

File: lib/internal/Magento/Framework/Escaper.php (hunk 1 above)
Comment (shyim) [reply lib/internal/Magento/Framework/Escaper.php:294]: Yes that's the wish of all developers. You need a little spot where this change has to be made known to the users. That's the idea behind the deprecation.

- Deprecate it
- On other version forbid that with typethint

**Comment by Den4ik** [comment]
> I don't think it was ever a P0 as there is an easy workaround of freezing incompatible dependency version. As a new version of laminas-escaper is released please no hacks in Magento code, just do a complete fix and mark bad version using https://getcomposer.org/doc/04-schema.md#conflict.

Totally agree with @orlangur in case of release `laminas-escaper` 2.8.0. Currently we don't need hot fix in code, updating `composer.json` and `composer.lock` is enough. I preferrer make correct fix that most likely will be backward incompatible and release it with 2.5

File: lib/internal/Magento/Framework/Escaper.php (hunk 1 above)
Comment (tufahu) [reply lib/internal/Magento/Framework/Escaper.php:294]: I totally agree with the workaround definition, until laminas 2.8.0 released.

Laminas 2.8.0 escaper is strict but the current callchain is not strict 100%, that's why our integer is auto coerced. So string conversion happens automatically instead of explicit way.

At the end we need a string because rawurlencode() works with strings. I guess we need to handle every argument pass as strict as we can, and @hostep 's suggestion is right that in RouteParamsResolver we can explicit cast url parts to strings.

Now i add one commit to just reverse the fast workaround

**Comment by tufahu** [comment]
I've reversed the forced cast at escaper, as @orlangur @Den4ik mentioned, the correct resolution is at composer and laminas-escaper 2.8.0 at the moment. Should i do something more here? If i can help something, please tell me, and thank you for your help.

**Comment by hostep** [comment]
We still have a problem on Magento `2.4-develop` branch btw: https://github.com/magento/magento2/issues/33346#issuecomment-869563626 (and following comments), so we can't just close the PR and do nothing

I think we can't add a return type of `string` to those method as those are probably backwards incompatible, the addition of `string` type for the arguments is probably backwards compatible since PHP 7.2 due to https://wiki.php.net/rfc/parameter-no-type-variance

**Comment by tufahu** [comment]
Yes you are right @hostep, in the develop branch the \Magento\Framework\Escaper becamed strict too. With laminas escaper 2.8.0 there will be a typeError also but in Magento Escaper. not at laminas. The current state of the PR could be correct for the resolution.

Magento 2.4.x is supported by php 7.3, 7.4.

**Comment by achatpc** [comment]
> Yes you are right @hostep, in the develop branch the \Magento\Framework\Escaper becamed strict too. With laminas escaper 2.8.0 there will be a typeError also but in Magento Escaper. not at laminas. The current state of the PR could be correct for the resolution.
> 
> Magento 2.4.x is supported by php 7.3, 7.4.

I confirm.

**Comment by alinolandry** [comment]
upgrade to laminas/laminas 2.8.0 fix the probem for me: 
`composer require laminas/laminas-escaper:2.8`

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
SVC failure should be approved.
@gabrieldagama @sidolov @sivaschenko, could you point how to get it merged w/o running into a too-long approval process?

**Comment by hostep** [comment]
In my opinion the PR needs to get changed a little bit and the return type of those two methods need to be removed again, I don't see why the return type fixes anything in scope of this problem?

Without the return type, the change is backwards compatible, see https://3v4l.org/ti9uU vs https://3v4l.org/IBGCK

File: lib/internal/Magento/Framework/Escaper.php [hunk 2]
```diff
@@ -289,7 +289,7 @@ public function escapeUrl($string)
      * @return string
      * @since 101.0.0
      */
-    public function encodeUrlParam($string)
+    public function encodeUrlParam(string $string): string
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Escaper.php]:
```suggestion
    public function encodeUrlParam(string $string)
```

File: lib/internal/Magento/Framework/Escaper.php [hunk 3]
```diff
@@ -328,7 +328,7 @@ function ($matches) {
      * @return string
      * @since 101.0.0
      */
-    public function escapeCss($string)
+    public function escapeCss(string $string): string
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Escaper.php]:
```suggestion
    public function escapeCss(string $string)
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Please remove return types due to backward compatibility. Here is more details: https://github.com/magento/magento2/pull/33353#issuecomment-874102821

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@magento run WebAPI Tests

**Comment by hostep** [comment]
Shouldn't Magento's SVC checker be changed, the failure on that check says this isn't a backwards compatible change:



Level | Target/Location | Code/Reason
-- | -- | --
MAJOR | Magento\Framework\Escaper::encodeUrlParam /lib/internal/Magento/Framework/Escaper.php:292 | V085 [public] Method parameter typing added.
MAJOR | Magento\Framework\Escaper::escapeCss /lib/internal/Magento/Framework/Escaper.php:331 | V085 [public] Method parameter typing added.


But I don't think that is true due to https://wiki.php.net/rfc/parameter-no-type-variance which was introduced in PHP 7.2

**Comment by ihor-sviziev** [comment]
> Shouldn't Magento's SVC checker be changed, the failure on that check says this isn't a backwards compatible change:
> 
> 
> 
> 
> 
> 
> 
> Level | Target/Location | Code/Reason
> 
> -- | -- | --
> 
> MAJOR | Magento\Framework\Escaper::encodeUrlParam /lib/internal/Magento/Framework/Escaper.php:292 | V085 [public] Method parameter typing added.
> 
> MAJOR | Magento\Framework\Escaper::escapeCss /lib/internal/Magento/Framework/Escaper.php:331 | V085 [public] Method parameter typing added.
> 
> 
> 
> 
> 
> But I don't think that is true due to https://wiki.php.net/rfc/parameter-no-type-variance which was introduced in PHP 7.2

@sivaschenko @sidolov @gabrieldagama, what do you think?

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
FYI SVC Failure is basically false positive, I reported an issue for improving it: https://github.com/magento/magento-semver/issues/63

**Comment by ihor-sviziev** [comment]
@sdzhepa, could you test this PR?

**Comment by sdzhepa** [comment]
Hello @ihor-sviziev 

Thank you for pinging me on it! and sorry for the delays.
I will do my best to speed up delivery for this PR.

And about the testing strategy, IMO regular manual testing is not applicable for such changes. Because it could be equal to full application regression testing. On the other hand changes on such level of application usually bring rather Fatal Errors or everything works as before. So I would propose
- put effort of Code review level
- after relay on all auto-test/builds (investigate and fix if any)
- deliver

**Review by andrewbess — APPROVED** [review]
Hello @tufahu 
Thank you for your contribution.
Great job.
The fixes have been checked with `laminas/laminas-escaper` versions 2.7.0, 2.7.1, 2.8.0.
The system works good for me.
The `laminas/laminas-escaper` will be updated to the latest version according to [this issue](https://github.com/magento/magento2/issues/33574).

cc @ihor-sviziev @sdzhepa

**Comment by andrewbess** [comment]
@magento run all tests

**Comment by hostep** [comment]
@andrewbess: out of curiosity: I noticed that Magento 2.3.7-p1, 2.4.2-p2 and 2.4.3 come with `laminas/laminas-escaper` pinned to version 2.7.0 and won't allow updates to a newer version anymore.

I'm hoping this will change again in 2.3.7-p2, 2.4.3-p1 and 2.4.4, correct?

**Comment by andrewbess** [comment]
Hello @hostep 
Thank you for your comment.
I'm hoping too.
I think we need to deliver this fix and update of the laminas-escaper there.
I'll work on that.

**Comment by sivaschenko** [comment]
@ihor-sviziev @andrewbess What is the reason for choosing backwards-incompatible change of declaring strict types over simply casting the argument to a string before passing it to laminas escaper?

**Comment by ihor-sviziev** [comment]
@sivaschenko pls ping me in Slack

**Comment by Den4ik** [comment]
It would be good to discuss in general channel with all members

**Comment by ihor-sviziev** [comment]
Hi,

As we discussed in Slack with @sivaschenko:
- the listed above case isn't fully correct, as the `\Magento\Framework\Escaper` isn't extending the Laminas class. More info https://github.com/magento/magento-semver/issues/63#issuecomment-889743723

File: lib/internal/Magento/Framework/Escaper.php [hunk 4]
```diff
@@ -289,7 +289,7 @@ public function escapeUrl($string)
      * @return string
      * @since 101.0.0
      */
-    public function encodeUrlParam($string)
+    public function encodeUrlParam(string $string)
     {
         return $this->getEscaper()->escapeUrl($string);
     }
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Escaper.php]:
```suggestion
    public function encodeUrlParam($string)
    {
        return $this->getEscaper()->escapeUrl((string)$string);
    }
```

File: lib/internal/Magento/Framework/Escaper.php [hunk 5]
```diff
@@ -328,7 +328,7 @@ function ($matches) {
      * @return string
      * @since 101.0.0
      */
-    public function escapeCss($string)
+    public function escapeCss(string $string)
     {
         return $this->getEscaper()->escapeCss($string);
     }
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Escaper.php]:
```suggestion
    public function escapeCss($string)
    {
        return $this->getEscaper()->escapeCss((string)$string);
    }
```

File: lib/internal/Magento/Framework/Test/Unit/EscaperTest.php [hunk 6]
```diff
@@ -364,6 +364,64 @@ public function testEscapeUrl(string $data, string $expected): void
...
+     * @return array
+     */
+    public function escapeCssDataProvider(): array
+    {
+        return [
+            [
+                'data'     => '*%string{foo}%::',
+                'expected' => '\2A \25 string\7B foo\7D \25 \3A \3A ',
+            ]
+        ];
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Test/Unit/EscaperTest.php]:
```suggestion
        return [
            [
                'data'     => 1,
                'expected' => '1',
            ],
            [
                'data'     => '*%string{foo}%::',
                'expected' => '\2A \25 string\7B foo\7D \25 \3A \3A ',
            ]
        ];
```

File: lib/internal/Magento/Framework/Test/Unit/EscaperTest.php [hunk 7]
```diff
@@ -364,6 +364,64 @@ public function testEscapeUrl(string $data, string $expected): void
...
+        return [
+            [
+                'data'     => "a3==",
+                'expected' => "a3%3D%3D",
+            ],
+            [
+                'data'     => "example string",
+                'expected' => "example%20string",
+            ]
+        ];
```
Comment (ihor-sviziev) [inline lib/internal/Magento/Framework/Test/Unit/EscaperTest.php]:
```suggestion
        return [
            [
                'data'     => "a3==",
                'expected' => "a3%3D%3D",
            ],
            [
                'data'     => "example string",
                'expected' => "example%20string",
            ],
            [
                'data'     => 1,
                'expected' => "1",
            ],
            [
                'data'     => null,
                'expected' => "",
            ]
        ];
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
Based on discussion with @sivaschenko (more detils see in https://github.com/magento/magento-semver/issues/63#issuecomment-889743723) - we should revert the adding strict types, as it will break backward compatibility for the cases when in the client code we have declared `strict_types=1`, but for some reason, using a different type.

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: lib/internal/Magento/Framework/Url/RouteParamsResolver.php [hunk 8]
```diff
@@ -112,7 +112,7 @@ public function setRouteParams(array $data, $unsetOldParams = true)
             } else {
                 $this->setRouteParam(
                     $this->getEscaper()->encodeUrlParam($key),
-                    $this->getEscaper()->encodeUrlParam($value)
+                    $this->getEscaper()->encodeUrlParam((string)$value)
```
Comment (Den4ik) [inline lib/internal/Magento/Framework/Url/RouteParamsResolver.php:115]: @ihor-sviziev With new changes we can rollback changes for this file

Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Url/RouteParamsResolver.php:115]: No need, it still suppose to be a string, right?

**Comment by ihor-sviziev** [comment]
@magento run MAGETWO-53858

**Comment by ihor-sviziev** [comment]
@magento run Unit Tests

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Integration Tests

File: lib/internal/Magento/Framework/Escaper.php (hunk 1 above)
Comment (ihor-sviziev) [reply lib/internal/Magento/Framework/Escaper.php:294]: as we can't declare argument types, it's a good idea to add deprecation notice. Unfortunately, it doesn't work for some reason. 

I'll continue working on it in https://github.com/magento/magento2/pull/33637

**Review by sivaschenko — APPROVED** [review]

**Review by ihor-sviziev — APPROVED** [review]

**Review by Den4ik — APPROVED** [review]

**Review by andrewbess — APPROVED** [review]

**Comment by mrtuvn** [comment]
Hi any queue or plan to sync this to mainline 2.4-develop
cc @sivaschenko @gabrieldagama
