### PR TITLE
Issue 35838: Customer is logged in but showing 404 error in frontend.

### LINKED ISSUE #35838: Customer is logged in but showing 404 error in frontend.
### Preconditions and environment
 - 2.3.x, 2.4.x CE and Adobe Commerce

Base64 - aHR0cDovL21hZ2VudG8yNDAubG9jYWwvY3VzdG9tZXIvYWNjb3VudC9sb2dpblBvc3Qv
Decoded Base64 - <http://magento240.local/customer/account/loginPost/>
### Steps to reproduce
1. Go to frontend.
1. Add `/customer/account/loginPost/` in your magento url. ex-<http://magento240.local/customer/account/loginPost/>
1. Now click on {**}S{*}*ign In** 
1. Give login id and password.

### Expected result

It should generate referer url to Customer dashboard page when referer URL header contains /loginPost.
### Actual result

It is not generating referrer url to customer dashboard page,It is showing 404 error page but customer is logged in.

**Attached video:** [Untitled_ Jul 29, 2022 3_00 PM.webm](https://user-images.githubusercontent.com/24892273/181730483-2e2f226d-7e83-4cf5-b101-49c7a7526ee1.webm)
### Additional information

*No response*
### Release note

*No response*
### Triage and priority
 - < > Severity: **S0** *- Affects critical data or functionality and leaves users without workaround.*
 - < > Severity: **S1** *- Affects critical data or functionality and forces users to employ a workaround.*
 - < > Severity: **S2** *- Affects non-critical data or functionality and forces users to employ a workaround.*
 - < > Severity: **S3** *- Affects non-critical data or functionality and does not force users to employ a workaround.*
 - < > Severity: **S4** *- Affects aesthetics, professional look and feel, “quality” or “usability”.*

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Remove referrer in url when current page 404, after  customer login will redirect to Customer dashboard

### Fixed Issues (if relevant)

1. Fixes magento/magento2#35838

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento run all tests

File: app/code/Magento/Customer/Model/Url.php [hunk 1]
```diff
@@ -256,4 +261,23 @@ private function getRequestReferrer()
         }
         return null;
     }
+
+    /**
+     *  Check if Referrer url is no route url
```
Comment (edenduong) [inline app/code/Magento/Customer/Model/Url.php]: Redundant 1 Space character after *

File: app/code/Magento/Customer/Model/Url.php [hunk 2]
```diff
@@ -256,4 +261,23 @@ private function getRequestReferrer()
...
+     *
+     * @param string $url
+     * @return bool
+     */
+    private function isNoRouteUrl($url)
+    {
+        $defaultNoRouteUrl = $this->scopeConfig->getValue(
+            'web/default/no_route',
```
Comment (edenduong) [inline app/code/Magento/Customer/Model/Url.php]: It is better if declare `private const XML_PATH_WEB_DEFAULT_NO_ROUTE = 'web/default/no_route'`

**Review by edenduong — CHANGES_REQUESTED** [review]
Thank you for your contribution.
Could you please check my comment.

**Comment by rogerdz** [comment]
@magento run all tests

File: app/code/Magento/Customer/Model/Url.php (hunk 2 above)
Comment (rogerdz) [reply app/code/Magento/Customer/Model/Url.php]: Thank you for your advice, I added change to new commit

**Review by edenduong — APPROVED** [review]

**Comment by engcom-Lima** [comment]
@magento give me 2.4-develop instance

**Comment by engcom-Lima** [comment]
@magento give me test instance

**Comment by engcom-Lima** [comment]
:heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento `2.4-develop`

**Manual testing scenario:**

1. Go to frontend.
2. Add /customer/account/loginPost/ in your magento url.
3. Now click on sign In
4. Give login id and password.

**Before:** :heavy_multiplication_x: Customer is logged in but getting 404 error in FE.

image

**After:** :heavy_check_mark:  Now redirecting it to cutomer dashboard page.

Screenshot 2022-12-19 at 2 52 52 PM

**Additionally tested scenerios:**
1. Created order from the customer page.
2. Added two products to the compare list.

No additional manual test case is required as a part of regression, as this issue is related to URL.

Builds are failed hence, moving to extended testing.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Echo** [comment]
Function Test B2B failures are different on last two run.
Run1
image

Run2
image

Hence Moving to `Merge In Progress`.

**Comment by engcom-Charlie** [comment]
Before merge, sending it to testing again as it got move to merge after testing more than a [year](https://github.com/magento/magento2/pull/36263#issuecomment-1360873717) ago.

**Comment by engcom-Delta** [comment]
@magento run all tests

**Comment by engcom-Delta** [comment]
### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** 

**Manual testing scenario:**

1.Go to frontend.
2.Add /customer/account/loginPost/ in your magento url.
3.Now click on sign In
4.Give login id and password.


**Before:** :heavy_multiplication_x: 


Screenshot 2024-04-05 at 2 50 50 PM

Screenshot 2024-04-05 at 2 51 18 PM

Screenshot 2024-04-05 at 2 51 42 PM

Screenshot 2024-04-05 at 2 51 56 PM

Screenshot 2024-04-05 at 2 52 48 PM



**After:** :heavy_check_mark:  


Screenshot 2024-04-05 at 3 01 37 PM

Screenshot 2024-04-05 at 3 02 07 PM

Screenshot 2024-04-05 at 3 02 27 PM

Screenshot 2024-04-05 at 3 02 44 PM



Builds are failed. Hence, moving this PR to **Extended Testing.**

**Comment by engcom-Echo** [comment]
@magento run  Functional Tests EE, Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
Functional Tests EE, Functional Tests CE,Functional Tests B2B build failure are different on last two run on same commit also it contain some known failures.

Functional Tests EE
Run1
36263-ee

Run2
36263-ee2

Functional Tests CE
Run1
36263-ce
Run2
36263-ce2

Functional Tests B2B
Run1
36263-b2b
Run2
36263-b2b2

Hence moving it to `merge in progress`.
