### PR TITLE
Fixing strict sprintf Phrases in php8

### LINKED ISSUE #34085: The problem with sprintf(Magento\Framwork\Phrase()) construction in PHP >= 8
### Description (*)
We found a problem with `sprintf(__())` and `sprintf(Magento\Framwork\Phrase())` construction in PHP >= 8.
The error looks like "Expected parameter of type 'string', 'Magento\Framework\Phrase' provided".
This problem should be found and fixed in Magento codebase.
Currently, there are about 20 problems with provided constructions.

We need to change constructions to `sprintf(__()->render())`.

### PR DESCRIPTION
**Pull request by eduard13**
### Description (*)
This PR aims to fix rendering the Phrases in sprintf, which gets only string param.

### Related Pull Requests
https://github.com/magento/magento2-page-builder/pull/780
https://github.com/magento/magento2-page-builder-ee/pull/193
https://github.com/magento/partners-magento2ee/pull/611

### Fixed Issues (if relevant)
1. Fixes magento/magento2/issues/34085

### Manual testing scenarios (*)
N/A

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by eduard13** [comment]
@magento run all tests

**Comment by eduard13** [comment]
@magento run Static Tests with extensions magento-commerce/security-package-b2b:platform-health

**Comment by eduard13** [comment]
@magento run all tests with extensions magento-commerce/security-package-b2b:platform-health

**Review by andrewbess — APPROVED** [review]

File: app/code/Magento/Dhl/Model/Carrier.php [hunk 1]
```diff
@@ -994,7 +994,7 @@ function (array $a, array $b): int {
                 $code = $bodyXml->xpath('//GetQuoteResponse/Note/Condition/ConditionCode');
                 if (isset($code[0]) && (int)$code[0] == self::CONDITION_CODE_SERVICE_DATE_UNAVAILABLE) {
                     $debugPoint['info'] = sprintf(
-                        __("DHL service is not available at %s date"),
+                        __("DHL service is not available at %s date")->render(),
                         $responseData['date']
                     );
```
Comment (Den4ik) [inline app/code/Magento/Dhl/Model/Carrier.php:999]: I see 2 possible solutions here:
1. skip `Phrase` usage, because it's log data and in my opinion log data should not be translated
```
$debugPoint['info'] = sprintf("DHL service is not available at %s date", $responseData['date']);
```
2. skip `sprintf` usage
```
$debugPoint['info'] = __("DHL service is not available at %1 date", $responseData['date']);
```

1 is more preferable for me.

File: app/code/Magento/Email/Model/Template/Filter.php [hunk 2]
```diff
@@ -1121,7 +1121,7 @@ public function filter($value)
             $this->resetAfterFilterCallbacks();
 
             if ($this->_appState->getMode() == State::MODE_DEVELOPER) {
-                $value = sprintf(__('Error filtering template: %s'), $e->getMessage());
+                $value = sprintf(__('Error filtering template: %s')->render(), $e->getMessage());
```
Comment (Den4ik) [inline app/code/Magento/Email/Model/Template/Filter.php:1124]:
```suggestion
                $value = __('Error filtering template: %1', $e->getMessage())->render();
```

File: app/code/Magento/Email/Model/Template/Filter.php [hunk 3]
```diff
@@ -1121,7 +1121,7 @@ public function filter($value)
...
             } else {
                 $value = (string) __("We're sorry, an error has occurred while generating this content.");
```
Comment (Den4ik) [inline app/code/Magento/Email/Model/Template/Filter.php:1126]: Also I recommend to change this line with `render()` usage to be the same with 1124 line

**Review by Den4ik — CHANGES_REQUESTED** [review]
@eduard13 Please check review comments

File: app/code/Magento/Dhl/Model/Carrier.php (hunk 1 above)
Comment (eduard13) [reply app/code/Magento/Dhl/Model/Carrier.php:999]: None of the suggested solutions aren't suitable:
1. Why log data shouldn't be translated? Changing the existing behaviour, isn't what we're looking for.
2. This is a BIC. This was already discussed internally, and it was decided to use the existing implementation.

**Review by Den4ik — APPROVED** [review]
✅ Approve it in current implementation due to no changes in behaviour.
But I'm extremely suggest don't use translation for log data

**Review by ihor-sviziev — APPROVED** [review]

**Comment by ihor-sviziev** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Static Tests
