### PR TITLE
Fix issue product name in minicart render wrong with special characters

### LINKED ISSUE #29075: Minicart product name - not covered cases
### Preconditions (*)
Magento 2.3.5, 2.4

Related to: https://github.com/magento/magento2/pull/13802

### Steps to reproduce (*)

1. Add product with special characters to cart
2. remove ifnot condition (or trigger usage of it in other way) in template https://github.com/magento/magento2/blob/024625e61887a252df56f027e42347d20860b253/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L24-L32
3. open minicart

Issue:
If you use `text: product_name` in https://github.com/magento/magento2/blob/024625e61887a252df56f027e42347d20860b253/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L30 when product name has special characters like double quotes it will render them wrongly.

By default in most cases template will use html binding if product has url.

But this should be replaced by `<span data-bind="html: product_name"></span>` or removed.

### Actual result (*)

---
Severity: S2/3 ?

### PR DESCRIPTION
**Pull request by mrtuvn**
### Description (*)

With product has url magento render name without problem. But in the case product without url will render product name in cart incorrectly. Ex: product with special characters like double quotes
This fix will cover the case products don't have url and render name correctly

### Fixed Issues (if relevant)

1. Fixes magento/magento2#29075

### Manual testing scenarios (*)

1. From backend admin create new product with name contain special character such as double quote, &, -, /
2. Clear cache go to frontend view new product

### Questions or comments

I have one question need clarify about knockout 
In template inside foreach loop when use $parent for reference to component i can't call to method that i have defined But if i used $parents[1] its work to call method! Any reason behind this ? i don't see any doc mention in magento official devdocs
Is that knockout context changed inside loop foreach ?
CC: @ihor-sviziev @omiroshnichenko @guz-anton

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@mrtuvn could you fix the failing static tests?

**Comment by mrtuvn** [comment]
@ihor-sviziev just find out this rule in validate code magento
https://devdocs.magento.com/guides/v2.4/extension-dev-guide/xss-protection.html

> In order to notify developers that these properties/function results may contain HTML, Magento requires (with the help of a static test) that you name such properties/functions using “UnsanitizedHtml” suffix.

**Comment by mrtuvn** [comment]
Need your opinions ! @lbajsarowicz @lenaorobei @sivaschenko

**Comment by ihor-sviziev** [comment]
@mrtuvn I believe we need to ignore these cases as we have html there for sure

**Comment by mrtuvn** [comment]
What should i do on this ? Not only the product name, still other place in this file fail static test 
https://github.com/magento/magento2/blob/32b520c3b34b2da7dc253ee1dd448cae4b072bc8/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L48
This line will violation static rule magento about html sanitize

**Comment by gabrieldagama** [comment]
The risk was set to`low` due to: the suggested changes shouldn't affect other areas.

**Comment by engcom-Charlie** [comment]
@mrtuvn please see https://devdocs.magento.com/guides/v2.4/extension-dev-guide/xss-protection.html about `Knockout templates` this should help you solve the problem.

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
@mrtuvn from what @engcom-Charlie shown above - seems like we need to change the variable name from `product_name` to `productNameUnsanitizedHtml`, revert change that was done in https://github.com/magento/magento2/pull/13802/files#diff-6502b94b418435d6341605ae8a37b46fR88 and add new variable `productNameUnsanitizedHtml` instead.
Could you do that?

**Comment by mrtuvn** [comment]
yes i can do that but seem need more effort that still have other variable like options
https://github.com/afirlejczyk/magento2/blob/764f0862f46204f649367728333f40f39509bd7c/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L45

this value seem previously passed validator check

**Comment by ihor-sviziev** [comment]
@mrtuvn can we move it to some method?  I believe if that method will be named correctly - it should not complain

**Comment by mrtuvn** [comment]
@ihor-sviziev 
I not sure how to pass static test in the 2 last line
https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L45
and Line 48

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by mrtuvn** [comment]
@magento run all tests

File: app/code/Magento/Checkout/CustomerData/DefaultItem.php [hunk 1]
```diff
@@ -92,7 +92,7 @@ protected function doGetItemData()
             'configure_url' => $this->getConfigureUrl(),
             'is_visible_in_site_visibility' => $this->item->getProduct()->isVisibleInSiteVisibility(),
             'product_id' => $this->item->getProduct()->getId(),
-            'product_name' => $productName,
+            'productNameUnsanitizedHtml' => $productName,
```
Comment (ihor-sviziev) [inline app/code/Magento/Checkout/CustomerData/DefaultItem.php]: I think we need to bring back product_name, probably would be better to have it not escaped. What do you thing ?

Comment (mrtuvn) [reply app/code/Magento/Checkout/CustomerData/DefaultItem.php]: yes i will revert that

**Comment by mrtuvn** [comment]
@nuzil @sivaschenko @sidolov
 Sorry for involved you guys here ! Can you guys give me some suggestion about my changes

File: app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        },
+
+        /**
+         * Prepare the product name value to be rendered as HTML
+         *
+         * @param {String} productName
+         * @return {String}
+         */
+        getProductNameUnsanitizedHtml: function (productName) {
+            return escaper.escapeHtml(productName, this.allowedTags);
```
Comment (ihor-sviziev) [inline app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: Looks like now we have 2 times escaping, am I correct? Does it works fine now?

**Review by ihor-sviziev — COMMENTED** [review]
Now your changes looks good to me. The only one thing is not clear to me - do we double escaping for product name now?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento run all tests

File: app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js (hunk 2 above)
Comment (mrtuvn) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: just seperate function name for clarify imo. Both function do the same task for escape html string

Comment (ihor-sviziev) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: I mean right now product name escaped on backend and on front end , isn’t it?

Comment (mrtuvn) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: should we return product name ? Current in this PR we have 2 time escape in product name
One from backend and one in knockout template when we call getProductNameUnsanitizedHtml

Comment (ihor-sviziev) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: I think it would be good, also please add comment that it’s escaped on backend

Comment (ihor-sviziev) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: Also would it complain if we’ll use name `getProductNameHtml`? I think it shouldn’t and it is better name for the function

Comment (mrtuvn) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: name method need have suffix UnsanitizedHtml otherwise static test will raise error
https://github.com/magento/magento2/blob/2.4-develop/dev/tests/static/framework/Magento/Sniffs/Html/HtmlBindingSniff.php#L79

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by mrtuvn** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

File: app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js (hunk 2 above)
Comment (ihor-sviziev) [reply app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: Ok, so I think we can leave there something like this:
```suggestion
            // product name already escaped on backend
            return productName;
```

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
Now changes looks good to me. Let's wait for test results. 

@magento run all tests

**Comment by mrtuvn** [comment]
Seem fail tests not related with changes

**Comment by mrtuvn** [comment]
rebase with mainline latest code base

**Comment by mrtuvn** [comment]
rebased branch with mainline latest code base

**Comment by mrtuvn** [comment]
@magento run all tests

**Comment by ihor-sviziev** [comment]
@magento give me test instance

**Comment by ihor-sviziev** [comment]
Hi @mrtuvn i was able to reproduce the issue that we’re getting in families mftf tests:
1. Add to cart following product https://966e75ea4c12ca3b7972ea3f76a857c8.instances.magento-community.engineering/sprite-yoga-companion-kit.html
2. Open mini cart and see that we don’t have a price and here is some warning without message
9CF0D6C9-2BEC-44CC-8717-22E0D5C57342

Could you take a look?

**Comment by mrtuvn** [comment]
In my opinion current this time we don't need touch more on this cart for fix problem. This issue happen only by customises
But soon in near future we possible need refactor code and add some additional for pass new validator for html escape
Should i close this or continuing ?

File: app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+        },
+
+        /**
+         * Prepare the given option value to be rendered as HTML
+         *
+         * @param {String} optionValue
+         * @return {String}
+         */
+        getOptionValueUnsanitizedHtml: function (optionValue) {
+            return escaper.escapeHtml(optionValue, this.allowedTags);
```
Comment (ihor-sviziev) [inline app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]:
```suggestion
            // option value should be already escaped on backend
            return optionValue;
```

File: app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js [hunk 4]
```diff
@@ -0,0 +1,43 @@
...
+    return Component.extend({
+        defaults: {
+            allowedTags: ['div', 'span', 'b', 'strong', 'i', 'em', 'u', 'a']
+        },
+
+        /** @inheritdoc */
+        initialize: function () {
+            this._super();
+        },
+
```
Comment (ihor-sviziev) [inline app/code/Magento/Checkout/view/frontend/web/js/view/cart-item-renderer.js]: I think we can remove it
```suggestion
```

**Review by ihor-sviziev — CHANGES_REQUESTED** [review]
I just analyzed this HTML one time ago - seems like option.value in cases that you changed should contain already escaped html, so it should come from backend.
I would suggest just to remove escaping on frontend and add comment that it should be already escaped on backend.

As result we'll just fix the issue with product_name and will not change anything related to option.value.

What do you thing?

**Comment by ihor-sviziev** [comment]
@magento run all tests

**Review by ihor-sviziev — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @ihor-sviziev, thank you for the review.
[ENGCOM-8215](https://jira.corp.magento.com/browse/ENGCOM-8215) has been created to process this Pull Request

**Comment by engcom-Alfa** [comment]
:heavy_check_mark: QA Passed

**Manual testing scenario:**

1. Add product with special characters to cart
2. remove ifnot condition (or trigger usage of it in other way) in template https://github.com/magento/magento2/blob/024625e61887a252df56f027e42347d20860b253/app/code/Magento/Checkout/view/frontend/web/template/minicart/item/default.html#L24-L32
3. open minicart

**Before:** :heavy_multiplication_x: incorrectly renderer product name in the cart 

Screenshot from 2020-09-21 12-59-50

**After:** :heavy_check_mark: correctly rendered product name in the cart

Screenshot from 2020-09-21 13-10-27
