### PR TITLE
Issue 31043: Elastic Search interferes with the default sort order of products (changing newest first to oldest first)

### LINKED ISSUE #31043: Elastic Search interferes with the default sort order of products (changing newest first to oldest first)
### Preconditions (*)
1. Magento 2.4-develop
2. 2.3.5-p1 is all I have tested this in so far.

### Steps to reproduce (*)
- Create a category in Magento with several products in it, all have the position in the category set to the value 1
image

- Go to category page

### Expected result (*)
1. The newest products in the database (the one with the highest entity_id) are shown first
image
2. The Order by for the SQL query for retrieving the products
```
 SELECT `e`.*, `cat_index`.`position` AS `cat_index_position`, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_category_product_index_store1` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=1 AND cat_index.visibility IN(2, 4) AND cat_index.category_id=33
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1' ORDER BY `cat_index`.`position` asc, `e`.`entity_id` DESC
```

### Actual result (*)
1. The oldest products(with the lower entity_id) are shown first
image
2. The Order by for the SQL query for retrieving the products
```
SELECT `e`.*, `price_index`.`price`, `price_index`.`tax_class_id`, `price_index`.`final_price`, IF(price_index.tier_price IS NOT NULL, LEAST(price_index.min_price, price_index.tier_price), price_index.min_price) AS `minimal_price`, `price_index`.`min_price`, `price_index`.`max_price`, `price_index`.`tier_price`, IFNULL(review_summary.reviews_count, 0) AS `reviews_count`, IFNULL(review_summary.rating_summary, 0) AS `rating_summary`, `stock_status_index`.`stock_status` AS `is_salable` FROM `catalog_product_entity` AS `e`
 INNER JOIN `catalog_product_index_price` AS `price_index` ON price_index.entity_id = e.entity_id AND price_index.customer_group_id = 0 AND price_index.website_id = '1'
 LEFT JOIN `review_entity_summary` AS `review_summary` ON e.entity_id = review_summary.entity_pk_value AND review_summary.store_id = 1 AND review_summary.entity_type = (SELECT `review_entity`.`entity_id` FROM `review_entity` WHERE (entity_code = 'product'))
 INNER JOIN `cataloginventory_stock_status` AS `stock_status_index` ON e.entity_id = stock_status_index.product_id AND stock_status_index.website_id = 0 AND stock_status_index.stock_id = 1 WHERE (stock_status_index.stock_status = 1) AND (e.entity_id IN (1201, 1202, 1203)) ORDER BY FIELD(e.entity_id,1201,1202,1203)
```

:warning: **Note**: In Magento 2.3.6 with `Search Engine=MySQL` the newest product in the database (the one with the highest entity_id) was shown first. With Magento 2.4-develop with `Search Engine= Elasticsearch 7` this behaviour changed. The oldest product is shown first, the newest last.

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

The severity of this issue will differ between niches but for some businesses, this is quite critical. Like designer or boutique fashion retailers where the target audience frequent the website to view the latest items to hit the fashion lines etc.

---

I can't believe there are not more reports of this... I did [ask the question](https://magento.stackexchange.com/questions/326729/elastic-search-v7-changing-magento-default-product-sort-position-in-categories) on Magento Stack Exchange and it is passed by will hardly any views and zero interaction.

I'm obviously assuming this is a bug and not meant to happen.

### PR DESCRIPTION
**Pull request by rogerdz**
### Description (*)

Add sorting condition by product id desc

### Additional Information

- To maintain backward compatibility, We are going to introduced a store configuration for the Sort Order. 
-  Path for config : **Stores-> Configuration -> Catalog-> Catalog-> Storefront -> Product Listing Sort by Order**

### Fixed Issues (if relevant)

1. Fixes magento/magento2#31043

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rogerdz** [comment]
@magento  run all tests

**Comment by rogerdz** [comment]
@magento give me test instance

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by Viper9x** [comment]
@magento give me test instance

**Comment by Viper9x** [comment]
@magento give me test instance

**Comment by Viper9x** [comment]
I confirmed this PR resolved issue #31043. Special thanks to @rogerdz for providing the fix.

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by rogerdz** [comment]
@magento run Functional Tests B2B, Functional Tests CE , Functional Tests EE

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by Den4ik** [comment]
@rogerdz Could you please resolve conflict?

**Comment by rogerdz** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @rogerdz,

The changes seems good to us, but please refer to the below review comments:
- It seems some automated tests are failing due to the changes
- Consider making the default sort order configurable if different deployments require different behaviors.
- Add/modify an integration test to assert search results default to descending order by entity_id.
- Update the comment above the line to specify "newest first" for clarity.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @rogerdz,

I wanted to check if you are working on the automated test coverage & the functional test failures. If not, Can I take care of them? Just let me know what works best for you. 

Also, please note that [As mentioned in the above review comment point 2](https://github.com/magento/magento2/pull/36900#pullrequestreview-2874733260) We should add a store configuration for sort order keeping default value as Ascending to maintain backward compatibility. For automated test we are going to add functional Test which will be handling the scenario for desc order.

Please let me know if I can proceed with the changes or not?

Thanks!

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Hello @engcom-Hotel I have fixed all the failed automated test because of the changes done in PR. Also added automated test to verify the descending sort order functionality. Also taken care of the review comments. The 4th point is not included in the changes becuase that is no longer applicable since we are fetching the value from configuration.

Could you please review the changes ? Moving this PR for review.

Thanks!

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Since we have introduced a new store configuration, SVC is failing because of it hence created internal approval [JIRA](https://jira.corp.adobe.com/browse/AC-15135) for the same.

SVC: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/d2058a4e8bad2a103834a381c079f900/SemanticVersionChecker/report-magento2.html

Screenshot 2025-07-14 at 2 26 01 PM

hence moving this PR in Pending Approval.

File: app/code/Magento/Catalog/Model/Config/Source/SortOrder.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    /**
+     * Retrieve option values array
+     *
+     * @return array
+     */
+    public function toOptionArray(): array
+    {
+        return [
+            ['value' => 'ASC', 'label' => __('Ascending')],
+            ['value' => 'DESC', 'label' => __('Descending')],
```
Comment (Den4ik) [inline app/code/Magento/Catalog/Model/Config/Source/SortOrder.php]: In my opinion constant usage `Select::SQL_ASC` or `Collection::SORT_ORDER_ASC` is more preferable

**Review by Den4ik — CHANGES_REQUESTED** [review]
Hi @rogerdz 
Could you please review my comment

**Comment by engcom-Dash** [comment]
Hello @Den4ik & @engcom-Hotel, I have updated the PR with requested changes.Could you please review the changes. The failing functional Tests are not related to the changes done in this PR.

Moving this PR to Pending review.

Thanks

**Review by Den4ik — APPROVED** [review]
Hi @rogerdz, @engcom-Dash 
Thanks for update. Changes looks good for me.
Failed Functional Tests seems are not related to changes.
Semantic Version check failed due to new element in system.xml

**Comment by engcom-Dash** [comment]
As the testing of this PR is already done, moving this PR to Extended Testing to further procced on this PR.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by engcom-Dash** [comment]
The consistent failures in Functional B2B are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes
 
Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/571e2866b5710188bd6fef735eea8f67/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/4ddc88672fb4dbae1ed2befe496c33cd/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Known Issues: 
AdminStagingDashboardProvideAbilityToViewEditForUpdatesWithCartPriceRuleTest [ACQE-8610](https://jira.corp.adobe.com/browse/ACQE-8610)
ViewportSwitcherMobileHTMLThroughBlockContentTypeTest [ACQE-8608](https://jira.corp.adobe.com/browse/ACQE-8608)
BlockRenderHTMLThroughBlockContentTypeTest [ACQE-8609](https://jira.corp.adobe.com/browse/ACQE-8609)
AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

The consistent failures in Functional CE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/214b8a8e9bd9615bdc7ccb0e4b1ea2cf/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/9bf822d97550e60e56d29b8b5754583d/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Known Issues: 
StorefrontDeleteSimpleAndVirtualProductFromMiniShoppingCartTest [ACQE-8560](https://jira.corp.adobe.com/browse/ACQE-8560)
ViewportSwitcherMobileHTMLThroughBlockContentTypeTest [ACQE-8608](https://jira.corp.adobe.com/browse/ACQE-8608)
BlockRenderHTMLThroughBlockContentTypeTest [ACQE-8609](https://jira.corp.adobe.com/browse/ACQE-8609)

The consistent failures in Functional EE are known issues and JIRA is open for the same. The other failures are inconsistent and flaky. They neither part of the PR nor failing because of the PR changes

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/b8952f3941cbfbeff483c92f05aaa68c/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/36900/ead899ab5ba8999ce32a9bd6d6302537/Functional/allure-report-ee/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Known Issues: 
AdminStagingDashboardProvideAbilityToViewEditForUpdatesWithCartPriceRuleTest [ACQE-8610](https://jira.corp.adobe.com/browse/ACQE-8610)
ViewportSwitcherMobileHTMLThroughBlockContentTypeTest [ACQE-8608](https://jira.corp.adobe.com/browse/ACQE-8608)
BlockRenderHTMLThroughBlockContentTypeTest [ACQE-8609](https://jira.corp.adobe.com/browse/ACQE-8609)
AssignCustomOrderStatusNotVisibleOnStorefrontTest [ACQE-8490](https://jira.corp.adobe.com/browse/ACQE-8490)

**Comment by engcom-Dash** [comment]
Also, We have received all the required approval on the [JIRA](https://jira.corp.adobe.com/browse/AC-15135). Hence moving this PR in **Merge In Progress**.
