### PR TITLE
28584 fixed issue category query does not handle fragments

### LINKED ISSUE #28584: Category query does not handle fragments
Category query does not return correct response when using fragments

Steps to reproduce:
- Create some categories
- Run Query:
```
{
  categoryList(filters: {ids: {eq: "10"}}) {
    ... on CategoryTree {
      id
      name
      url_path
    }
  }
}
```

Actual Response: 
```
{
  "data": {
    "categoryList": [
      {
        "id": 10,
        "name": null,
        "url_path": null
      }
    ]
  }
}
```

Expected response (should match response without using fragment)
```
{
  "data": {
    "categoryList": [
      {
        "id": 10,
        "name": "Sweaters",
        "url_path": "venia-tops/venia-sweaters"
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by munkhulzii**
Fixed issue #28584

fixed category query with inline fragments
fixed total_count of products in category

### CODE REVIEW

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php [hunk 1]
```diff
@@ -66,16 +67,44 @@ public function getQueryFields(FieldNode $fieldNode): array
...
     }
 
+    /**
+     * Add fields from inline fragment nodes
+     *
+     * @param InlineFragmentNode $inlineFraggmentField
+     * @param array $inlineFragmentFields
+     * @return string[]
+     */
+    private function addInlineFragmentFields(InlineFragmentNode $inlineFraggmentField, $inlineFragmentFields = [])
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: typo in $inlineFraggmentField

**Review by danielrenaud — CHANGES_REQUESTED** [review]
This looks good, and is working as expected for inline fragments.
However, it does not work for named fragements
e.g.
```
{
  categoryList(filters: {ids: {in: ["11"]}}) {
    ...Cat
  }
}

fragment Cat on CategoryTree {
  name
  position
  url_key
}
```

throws error:
```
Argument 2 passed to Magento\\CatalogGraphQl\\Model\\Resolver\\Products\\DataProvider\\CategoryTree::joinAttributesRecursively() must be an instance of GraphQL\\Language\\AST\\FieldNode, instance of GraphQL\\Language\\AST\\FragmentSpreadNode given, called in /Users/drenaud/valet-magento/partners/app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php on line 144
```

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php [hunk 2]
```diff
@@ -124,4 +170,12 @@ private function setSelectionsForFieldNode(FieldNode $fieldNode, array $selected
     {
         $this->queryFields[$fieldNode->name->value][$fieldNode->name->loc->start] = $selectedFields;
     }
+
+    /**
+     * @param ResolveInfo $resolverInfo
+     */
+    public function setResolverInfo(ResolveInfo $resolverInfo): void
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: I don't think we should set the resovlerInfo in this way. For one it introduces temporal coupling.
Can we pass down resolve info via methods arguments instead.

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php [hunk 3]
```diff
@@ -65,17 +74,54 @@ public function getQueryFields(FieldNode $fieldNode): array
             $selectedFields = [];
             /** @var FieldNode $field */
             foreach ($query as $field) {
-                if ($field->kind === 'InlineFragment') {
-                    continue;
+                if ($field->kind === NodeKind::INLINE_FRAGMENT) {
+                    $inlineFragmentFields = $this->addInlineFragmentFields($field);
+                    $selectedFields = array_merge($selectedFields, $inlineFragmentFields);
+                } elseif ($field->kind === NodeKind::FRAGMENT_SPREAD && isset($this->resolverInfo->fragments[$field->name->value])) {
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: Check line length

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php [hunk 4]
```diff
@@ -53,6 +54,11 @@ class CategoryTree
      */
     private $metadata;
 
+    /**
+     * @var ResolveInfo
+     */
+    private $resolverInfo;
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php]: Rather than setting this as a class member, can we pass it via method arguments

**Review by danielrenaud — CHANGES_REQUESTED** [review]
I think it would be preferable to pass resolveInfo down via methods arguments rather than setting it as a class member

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php (hunk 4 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php]: removed class member and used method argument

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php (hunk 3 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: fixed

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php (hunk 2 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: removed class member and used method argument

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php [hunk 5]
```diff
@@ -56,26 +60,70 @@ public function join(FieldNode $fieldNode, AbstractCollection $collection): void
      * Get an array of queried fields.
      *
      * @param FieldNode $fieldNode
+     * @param ResolveInfo $resolverInfo
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: You have a mismatch here, with param. "resovleInfo" vs "resovlerInfo". I would suggest to use resolveInfo everywhere to match the classname, but either way it should be consistent

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php [hunk 6]
```diff
@@ -56,26 +60,70 @@ public function join(FieldNode $fieldNode, AbstractCollection $collection): void
...
         if (null === $this->getFieldNodeSelections($fieldNode)) {
             $query = $fieldNode->selectionSet->selections;
             $selectedFields = [];
             /** @var FieldNode $field */
             foreach ($query as $field) {
-                if ($field->kind === 'InlineFragment') {
-                    continue;
+                if ($field->kind === NodeKind::INLINE_FRAGMENT) {
+                    $inlineFragmentFields = $this->addInlineFragmentFields($resolveInfo, $field);
+                    $selectedFields = array_merge($selectedFields, $inlineFragmentFields);
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: Can you run all tests. I think the use of array_merge inside a foreach loop will cause a static failure. Is it possible to refactor this to avoid that?

File: app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php [hunk 7]
```diff
@@ -17,22 +20,54 @@ class DepthCalculator
     /**
      * Calculate the total depth of a category tree inside a GraphQL request
      *
+     * @param ResolveInfo $resolveInfo
      * @param FieldNode $fieldNode
      * @return int
      */
-    public function calculate(FieldNode $fieldNode) : int
+    public function calculate(ResolveInfo $resolveInfo, FieldNode $fieldNode) : int
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php:27]: Can we swap the arguments in this method signature just so it is similar to other related public methods

**Review by danielrenaud — CHANGES_REQUESTED** [review]
Generally looks good, just a few minor comments. Please rerun builds, I think there will be some static failures to address.

File: app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php (hunk 7 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php:27]: Do you mean the $resolveInfo in second place here?

Comment (danielrenaud) [reply app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php:27]: Yes, in other methods where you've added resolveInfo to the input args, it had been placed last, so I think it would be good to do the same here for consistency

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php [hunk 8]
```diff
@@ -85,8 +86,8 @@ public function getTree(ResolveInfo $resolveInfo, int $rootCategoryId): \Iterato
     {
```
Comment (munkhulzii) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php:86]: @danielrenaud here in this existing method we have $resolveInfo as first param. Maybe I should better move it to the first for other methods?

Comment (danielrenaud) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/CategoryTree.php:86]: It's fine to leave all the parameters as you have them. It was just a suggestion to make the method signatures look more similar, but it's minor detail as these are not api methods or anything

File: app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php (hunk 6 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/AttributesJoiner.php]: I have moved the array_merge from loop

File: app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php (hunk 7 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/Category/DepthCalculator.php:27]: I will leave it for now as we decided in another comment.

**Comment by danielrenaud** [comment]
@magento run all tests

**Review by danielrenaud — APPROVED** [review]

**Review by danielrenaud — COMMENTED** [review]
check failing static tests.
unit tests are failing for some other reason, I wouldn't worry about them at this point

**Comment by munkhulzii** [comment]
@magento run all tests

**Comment by munkhulzii** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php [hunk 9]
```diff
@@ -110,7 +110,7 @@ public function getList(
         $searchResults = $this->searchResultsFactory->create();
         $searchResults->setSearchCriteria($searchCriteriaForCollection);
         $searchResults->setItems($collection->getItems());
-        $searchResults->setTotalCount($searchResult->getTotalCount());
+        $searchResults->setTotalCount($collection->getSize());
```
Comment (danielrenaud) [inline app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php]: Please check this change. It may need to be reverted, it seems to be the cause of web api test failure

**Review by danielrenaud — CHANGES_REQUESTED** [review]
Check web api functional tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php (hunk 9 above)
Comment (danielrenaud) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php]: I investigated this a bit. This change is causing the web api test failure. But there is another issue mixed up with it.
So I think we should not make this change in your PR. Instead we will address the other issue separately, and your builds will be green

**Comment by munkhulzii** [comment]
@magento run all tests

File: app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php (hunk 9 above)
Comment (munkhulzii) [reply app/code/Magento/CatalogGraphQl/Model/Resolver/Products/DataProvider/ProductSearch.php]: reverted this.

**Review by danielrenaud — APPROVED** [review]
