### PR TITLE
Fix issue #37348: Google GTag add ecommerce data fix.

### LINKED ISSUE #37348: GTag not send transaction prices and totals.
### Preconditions and environment

- Magento version: >= 2.4.5-p1, 2.4.5-p2, 2.4.6

### Steps to reproduce

1. Enable Gtag (Store - Configuration - Sales - Google API - GTag - Enable and add Gtag Key
2. Add product to cart and finish an order.
3. On success page you need capture OrderTrackingData which was send to Google Tag.

### Expected result

Currency need to be part of the order, not part of the "all" orders provided. Reference from Google Analytics docs: https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag#make_a_purchase_or_issue_a_refund

image

### Actual result

image

### Additional information

_No response_

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [X] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by Bashev**
1. Currency was moved to order object.
2. Escapers was changed to be in harmony of "non-deprecated" ones.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37348

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run all tests

**Comment by Bashev** [comment]
@magento run Sample Data Tests B2B, Sample Data Tests EE, Functional Tests B2B, Functional Tests EE, Integration Tests, Static Tests, Unit Tests, WebAPI Tests

**Comment by kasperth** [comment]
@Bashev Appreciate the good work you are putting into this.

I have also looked into this and found that by including currency and changing the number values to be outputted correctly (removing quotation marks, following [Google docs](https://developers.google.com/analytics/devguides/collection/ga4/set-up-ecommerce)), Google now reads it as e-commerce data and includes it as revenue.

Which issues are you facing? I thought about creating a simple PR, but it looks like you are being more thorough and solving more things than me.

**Comment by Bashev** [comment]
@kasperth if currency is not on the order level GA not recognize order amount and everytime is reported as 0. When move the currency inside the order start working properly. Your finding is correct,. During the fix i add additional things as coupons and discounts into the datalayer which will be send to GA.

Unfortunately some of these changes reflect to changes of `__construct` of the Ga Block, composer.json and as result this is the reason for failed jobs.

Someone from the team need to support this PR.

File: app/code/Magento/GoogleGtag/Block/Ga.php [hunk 1]
```diff
@@ -145,23 +157,48 @@ public function getOrdersTrackingData(): array
...
-            $result['orders'][] = [
+
+            $resultOrder = [
                 'transaction_id' =>  $order->getIncrementId(),
-                'affiliation' => $this->escapeJsQuote($this->_storeManager->getStore()->getFrontendName()),
-                'value' => number_format((float) $order->getGrandTotal(), 2),
-                'tax' => number_format((float) $order->getTaxAmount(), 2),
-                'shipping' => number_format((float) $order->getShippingAmount(), 2),
+                'currency' =>  $order->getOrderCurrencyCode(),
+                'value' => round($order->getGrandTotal(), 2),
```
Comment (bhoopatparmar) [inline app/code/Magento/GoogleGtag/Block/Ga.php]: @Bashev here `round($order->getGrandTotal(), 2)` throws an error as round() expects int/float but it is getting string value here. You need to add a datatype float here as well. **'`value' => round((float) $order->getGrandTotal(), 2),`**

Comment (Bashev) [reply app/code/Magento/GoogleGtag/Block/Ga.php]: @bhoopatparmar correct, thx.

**Comment by kasperth** [comment]
@Bashev I have a suggestion for your pull request. I can see that you are approaching two different things.
1. Fixing the revenue tracking (by implementing the currency code).
2. Enhancing and improving revenue tracking.

I suggest splitting this into two pull requests/issues, so these can be handled separately. This way, we can use the 1) fix for revenue as a patch, and shops can implement it ASAP, without having to rely on the improvements you are adding as well.

For example, we would like to use an official pull request to solve this using the patch module but are currently not able to, as we only need the currency fix. If we create our own PR with the currency fix, it will be closed as a duplicate.

I'll gladly assist in creating a PR with the currency code if you remove it from this one.

**Comment by Bashev** [comment]
@magento run Functional Tests B2B

**Comment by Bashev** [comment]
I have no idea how to solve this failing test, its only on B2B.

File: app/code/Magento/GoogleGtag/Block/Ga.php [hunk 2]
```diff
@@ -147,20 +147,22 @@ public function getOrdersTrackingData(): array
         foreach ($collection->getItems() as $order) {
             foreach ($order->getAllVisibleItems() as $item) {
                 $result['products'][] = [
-                    'item_id' => $this->escapeJsQuote($item->getSku()),
-                    'item_name' =>  $this->escapeJsQuote($item->getName()),
-                    'price' => number_format((float) $item->getPrice(), 2),
-                    'quantity' => (int)$item->getQtyOrdered(),
+                    'item_id' => $this->_escaper->escapeHtmlAttr($item->getSku()),
```
Comment (bhoopatparmar) [inline app/code/Magento/GoogleGtag/Block/Ga.php]: Hi @Bashev , wherever you've replaced `$this->escapeJsQuote` with `$this->_escaper->escapeHtmlAttr` is causing an issue and it replaces the white spaces of the string with **`&#x20;.`** So, can you please update it again with **$this->escapeJsQuote**

Comment (Bashev) [reply app/code/Magento/GoogleGtag/Block/Ga.php]: escapeJsQuote is deprecated.

Comment (bhoopatparmar) [reply app/code/Magento/GoogleGtag/Block/Ga.php]: So, Instead of `$this->_escaper->escapeHtmlAttr` you can use `$this->_escaper->escapeHtml` as it will not remove the white spaces in between from the string.

File: app/code/Magento/GoogleGtag/Block/Ga.php [hunk 3]
```diff
@@ -147,20 +147,22 @@ public function getOrdersTrackingData(): array
         foreach ($collection->getItems() as $order) {
             foreach ($order->getAllVisibleItems() as $item) {
                 $result['products'][] = [
-                    'item_id' => $this->escapeJsQuote($item->getSku()),
-                    'item_name' =>  $this->escapeJsQuote($item->getName()),
-                    'price' => number_format((float) $item->getPrice(), 2),
-                    'quantity' => (int)$item->getQtyOrdered(),
+                    'item_id' => $this->_escaper->escapeHtml($item->getSku()),
+                    'item_name' =>  $this->_escaper->escapeHtmlAttr($item->getName()),
```
Comment (bhoopatparmar) [inline app/code/Magento/GoogleGtag/Block/Ga.php]: Please update `$this->_escaper->escapeHtml` instead of `$this->_escaper->escapeHtmlAttr` here also.

File: app/code/Magento/GoogleGtag/Block/Ga.php [hunk 4]
```diff
@@ -147,20 +147,22 @@ public function getOrdersTrackingData(): array
...
+                    'affiliation' => $this->_escaper->escapeHtmlAttr(
```
Comment (bhoopatparmar) [inline app/code/Magento/GoogleGtag/Block/Ga.php]: Please update `$this->_escaper->escapeHtml` instead of `$this->_escaper->escapeHtmlAttr` here also.

**Comment by Bashev** [comment]
already fixed, with some minor differences.

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, Static Tests, Unit Tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @Bashev,

Thanks for the contribution!

Please look into the failed tests specifically unit test failure, it seems the failures are due to code changes.

Thanks

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failing Test are not related to PR changes and some of them are known failure.
Hence moving it to `Pending Review`

**Comment by engcom-Hotel** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE, WebAPI Tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
Hi @Bashev,

Thanks for the collaboration & contribution!

:x: QA not Passed

**:heavy_check_mark: Expected result After Fix** 


Coupon and Discount data should be present in gtag data



**:x: Actual result After Fix** 




Screenshot 2024-06-10 at 13 22 55


Screenshot 2024-06-10 at 12 53 01



Let us know if we are missing anything.

Thanks.

**Comment by Bashev** [comment]
@engcom-Bravo mentioned improvements are in separate PR https://github.com/magento/magento2/pull/37504 which was closed for unclear reason.

They are 2 separate PRs 
- this one fix only purchase value
- #37504 add discouns, coupons and brands (manufacturer)

**Comment by engcom-Bravo** [comment]
Hi @Bashev,

Thanks for your update.

:heavy_check_mark: QA Passed


**Before:** :heavy_multiplication_x:



Screenshot 2024-06-11 at 10 48 54




**After:** :heavy_check_mark: 


Screenshot 2024-06-11 at 10 48 43



Builds are failed. Hence, moving this PR to **Extended Testing.**

Thanks.

**Comment by engcom-Echo** [comment]
@magento run WebAPI Tests,Unit Tests,Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE,Integration Tests,WebAPI Tests

**Comment by engcom-Echo** [comment]
Functional Tests CE,Functional Tests EE,Functional Tests B2B failure contains some known failure and rest failure are different on last two run on same commit.
Functional Tests CE
Run1
37349-ce

Run2
Screenshot 2024-06-12 at 1 03 33 PM

Functional Tests EE
Run1
37349-ee

Run2
Screenshot 2024-06-12 at 1 03 50 PM

Functional Tests B2B 
Run1
37349-b2b

Run2
Screenshot 2024-06-12 at 2 01 25 PM


WebAPI Tests ,Integration Tests contains known failure.
Screenshot 2024-06-12 at 1 06 23 PM

Screenshot 2024-06-12 at 1 06 32 PM

Hence moving it to `merge in progress`
