### PR TITLE
Fixes #12584 Bundle Item price cannot differ per website

### LINKED ISSUE #12584: Bundle Item price cannot differ per website
### Preconditions

1. Magento 2.2-develop
2. Magento 2.1-develop

### Steps to reproduce

1. Set `Stores | Configuration | Catalog | Catalog | Price | Catalog Price Scope` to 'Website'
2. Create a second website, store and store view
3. Create a bundle product with option 'Dynamic Price': 'No'
4. Add it to both websites
5. Add a bundle item with price type 'fixed' and price '12'
6. Save the product
7. Use the dropdown on the top left to change scope to your second store view
8. Set the Bundle Item price to '10'
9. Save the product

### Expected result

1. The bundle item should have price '12' in the default scope and in the first store view
2. The bundle item should have price '10' in the second store view
3. Website specific prices should be saved in table `catalog_product_bundle_selection_price`

### Actual result

1. The bundle item has price '10' everywhere
2. There are no entries in `catalog_product_bundle_selection_price`
3. The price is only saved in `catalog_product_bundle_selection` which is not website specific

Tip: almost all logic is already in place, because if you add entries to the `catalog_product_bundle_selection_price` table manually, the bundle items do have different prices per website, until you save the product in the backend. Then the `catalog_product_bundle_selection_price` entry is deleted again and only the `catalog_product_bundle_selection` entry remains.

### PR DESCRIPTION
**Pull request by rain2o**
### Description
Bundle Item prices are missing their website id which is checked for in `\Magento\Bundle\Model\Selection::afterSave`. This check always failed.

I started with the changes from PR #12586 and updated it to fix the issue of the website-scoped price overriding the global price. 

### Related Pull Requests
#12586

### Fixed Issues
1. magento/magento2#12584: Bundle Item price cannot differ per website

### Manual testing scenarios

1. Set Stores | Configuration | Catalog | Catalog | Price | Catalog Price Scope to 'Website'
2. Create a second website, store and store view
3. Create a bundle product with option 'Dynamic Price': 'No'
4. Add it to both websites
5. Add a bundle item with price type 'fixed' and price '12'
6. Save the product
7. Use the dropdown on the top left to change scope to your second store view
8. Set the Bundle Item price to '10'
9. Save the product

**Expected result**
The bundle item should have price '12' in the default scope and in the first store view
The bundle item should have price '10' in the second store view

### Questions or comments
I tested this in multiple environments running Magento 2.4. Two out of three tested successfully. One of those environments throws an error when saving stock items (see below). Because this only happened in one environment I couldn't figure out if it was environmental or if there is another underlying issue related to this PR. It seems as though saving the Stock Item, even when updating an existing one, throws an error for a duplicate PRIMARY index. Which is strange as it is updating an existing entry.

```
The stock item was unable to be saved. Please try again. {"exception":"[object] (Magento\\Framework\\Exception\\CouldNotSaveException(code: 0): The stock item was unable to be saved. Please try again. at /var/www/html/app/code/Magento/CatalogInventory/Model/Stock/StockItemRepository.php:193, Magento\\Framework\\Exception\\LocalizedException(code: 0): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2047-0-1-5-9' for key 'PRIMARY', query was: UPDATE `catalog_product_index_price_bundle_sel_tmp`
 INNER JOIN `catalog_product_index_price_bundle_tmp` AS `i`
 INNER JOIN `catalog_product_entity` AS `parent_product` ON parent_product.entity_id = i.entity_id
 INNER JOIN `catalog_product_bundle_option` AS `bo` ON bo.parent_id = parent_product.entity_id
 INNER JOIN `catalog_product_bundle_selection` AS `bs` ON bs.option_id = bo.option_id
 INNER JOIN `catalog_product_bundle_selection_price` AS `bsp` ON bs.selection_id = bsp.selection_id AND bsp.website_id = i.website_id
SET `catalog_product_index_price_bundle_sel_tmp`.`entity_id` = `i`.`entity_id`, `catalog_product_index_price_bundle_sel_tmp`.`customer_group_id` = `i`.`customer_group_id`, `catalog_product_index_price_bundle_sel_tmp`.`website_id` = `i`.`website_id`, `catalog_product_index_price_bundle_sel_tmp`.`option_id` = `bo`.`option_id`, `catalog_product_index_price_bundle_sel_tmp`.`selection_id` = `bs`.`selection_id`, `catalog_product_index_price_bundle_sel_tmp`.`group_type` = IF(bo.type = 'select' OR bo.type = 'radio', 0, 1), `catalog_product_index_price_bundle_sel_tmp`.`is_required` = `bo`.`required`, `catalog_product_index_price_bundle_sel_tmp`.`price` = LEAST(IF(bsp.selection_price_type = 1, ROUND(i.price * (bsp.selection_price_value / 100),4), IF(i.special_price > 0 AND i.special_price < 100, ROUND(bsp.selection_price_value * (i.special_price / 100),4), bsp.selection_price_value))* bs.selection_qty, IFNULL((IF(i.base_tier IS NOT NULL, IF(bsp.selection_price_type = 1, ROUND(i.base_tier - (i.base_tier * (bsp.selection_price_value / 100)),4), IF(i.tier_percent > 0, ROUND((1 - i.tier_percent / 100) * bsp.selection_price_value,4), bsp.selection_price_value)) * bs.selection_qty, NULL)), IF(bsp.selection_price_type = 1, ROUND(i.price * (bsp.selection_price_value / 100),4), IF(i.special_price > 0 AND i.special_price < 100, ROUND(bsp.selection_price_value * (i.special_price / 100),4), bsp.selection_price_value))* bs.selection_qty)), `catalog_product_index_price_bundle_sel_tmp`.`tier_price` = IF(i.base_tier IS NOT NULL, IF(bsp.selection_price_type = 1, ROUND(i.base_tier - (i.base_tier * (bsp.selection_price_value / 100)),4), IF(i.tier_percent > 0, ROUND((1 - i.tier_percent / 100) * bsp.selection_price_value,4), bsp.selection_price_value)) * bs.selection_qty, NULL)
WHERE (i.price_type=1) at /var/www/html/app/code/Magento/Catalog/Model/Indexer/Product/Price/Action/Row.php:32
```

Removing the following lines from `\Magento\Bundle\Model\LinkManagement` causes this error to go away, so it seems related to it. I just can't figure out how/why.

```
if ($productLink->getWebsiteId() !== null) {
    $selectionModel->setWebsiteId($productLink->getWebsiteId());
}
```

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by rain2o** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rain2o. Thank you for your request. I'm working on Magento instance for you

File: app/code/Magento/Bundle/Model/Selection.php [hunk 1]
```diff
@@ -72,13 +74,30 @@ protected function _construct()
     }
 
     /**
-     * Processing object before save data
+     * Processin object before save data
```
Comment (lbajsarowicz) [inline app/code/Magento/Bundle/Model/Selection.php]: You've introduced typo

**Review by lbajsarowicz — CHANGES_REQUESTED** [review]
Could you provide Integration Tests that will also clarify the overview of the change?
Introduction of Automated Tests is part of our Definition of Done:
https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html

**Comment by rain2o** [comment]
> Could you provide Integration Tests that will also clarify the overview of the change?
> Introduction of Automated Tests is part of our Definition of Done:
> https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing_dod.html

@lbajsarowicz I am a little unfamiliar with the Integration tests. I will attempt to do so. I don't see any integration tests in the Bundle module, but I see some in `dev/tests/integration/testsuite/Magento/Bundle`. Should I be adding these tests inside the Bundle module directly, or in the testsuite under `dev/tests`?

**Comment by lbajsarowicz** [comment]
@rain2o Fix **Static Tests** then.
We will find help with Integration Tests.

**Comment by rain2o** [comment]
@lbajsarowicz Sure thing, thanks for the assist. I noticed the static tests that are failing also fail on the `2.4-develop` branch as well. Most seem to be things like code duplication between models and their respective test classes (e.g. `.../app/code/Magento/Customer/Model/Data/Address.php` and `.../app/code/Magento/TestModuleExtensionAttributes/Model/Data/FakeAddress.php`). 
Are these the tests I need to fix, as they are pre-existing? Just trying to make sure I'm clear on what I need to do.

**Comment by rain2o** [comment]
Sorry, I see the Allure test results now and it's more clear to me. I just can't seem to successfully run these tests locally to get the same results.

**Review by lbajsarowicz — DISMISSED** [review]

**Comment by magento-engcom-team** [comment]
Hi @lbajsarowicz, thank you for the review.
[ENGCOM-7141](https://jira.corp.magento.com/browse/ENGCOM-7141) has been created to process this Pull Request
:eight_spoked_asterisk: @lbajsarowicz, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Review by engcom-Bravo — CHANGES_REQUESTED** [review]
:x: QA Failed

Attempt to edit and save the price on the "Second" Store view, leads to ane error _"The stock item was unable to be saved. Please try again."_ 
unable_to save_stock

**Comment by rain2o** [comment]
>  QA Failed
> 
> Attempt to edit and save the price on the "Second" Store view, leads to ane error _"The stock item was unable to be saved. Please try again."_
> unable_to save_stock

Yes, this is the problem I noted in the PR that I discovered when testing in one environment. I wasn't sure if it was duplicatable. From what I can tell, the Stock Item repository is failing when saving an existing stock item. Even when I try directly getting, modifying, and saving a stock item it fails. As this PR didn't touch anything with Stock Items I'm not really sure what is causing this. Any thoughts?

**Comment by craig-bartlett** [comment]
Please excuse my scattered thoughts - this has been plaguing me for the last few days and is way above my understanding, but thought I should share my findings in case they are useful.

I don't know if this is of any help to anyone but I think the SQL error is thrown by the bundle price indexer (app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php) due to [this commit](https://github.com/magento/magento2/commit/9af3b12b87692f538917e7ff28232503f8846f2f) rather than your fix.

We have the same duplicate entry error when running the indexer on catalog_product_price since updating from 2.3.3-p1 to 2.3.5-p1. As we migrated from M1, we already had rows in the catalog_product_bundle_selection_price table. As a test I tried truncating that table and the indexer runs without error, and it also works when indexing with the 2.3.3 indexer code. If we manually add a row back in, the error returns. **I tested this on a fresh install of 2.3.5-p1 with the sample data. Manually adding a single row to catalog_product_bundle_selection_price causes the same error.**

In particular I expect it's [line 519 here](https://github.com/magento/magento2/blob/2.3/app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php#L519) which results in:

```
UPDATE `catalog_product_index_price_bundle_sel_tmp`
 INNER JOIN `catalog_product_index_price_bundle_tmp` AS `i`
 INNER JOIN `catalog_product_entity` AS `parent_product` ON parent_product.entity_id = i.entity_id
 INNER JOIN `catalog_product_bundle_option` AS `bo` ON bo.parent_id = parent_product.entity_id
 INNER JOIN `catalog_product_bundle_selection` AS `bs` ON bs.option_id = bo.option_id
 INNER JOIN `catalog_product_bundle_selection_price` AS `bsp` ON bs.selection_id = bsp.selection_id AND bsp.website_id = i.website_id
SET `catalog_product_index_price_bundle_sel_tmp`.`entity_id` = `i`.`entity_id`, `catalog_product_index_price_bundle_sel_tmp`.`customer_group_id` = `i`.`customer_group_id`, `catalog_product_index_price_bundle_sel_tmp`.`website_id` = `i`.`website_id`, `catalog_product_index_price_bundle_sel_tmp`.`option_id` = `bo`.`option_id`, `catalog_product_index_price_bundle_sel_tmp`.`selection_id` = `bs`.`selection_id`, `catalog_product_index_price_bundle_sel_tmp`.`group_type` = IF(bo.type = 'select' OR bo.type = 'radio', 0, 1), `catalog_product_index_price_bundle_sel_tmp`.`is_required` = `bo`.`required`, `catalog_product_index_price_bundle_sel_tmp`.`price` = LEAST(IF(bsp.selection_price_type = 1, ROUND(i.price * (bsp.selection_price_value / 100),4), IF(i.special_price > 0 AND i.special_price < 100, ROUND(bsp.selection_price_value * (i.special_price / 100),4), bsp.selection_price_value))* bs.selection_qty, IFNULL((IF(i.base_tier IS NOT NULL, IF(bsp.selection_price_type = 1, ROUND(i.base_tier - (i.base_tier * (bsp.selection_price_value / 100)),4), IF(i.tier_percent > 0, ROUND((1 - i.tier_percent / 100) * bsp.selection_price_value,4), bsp.selection_price_value)) * bs.selection_qty, NULL)), IF(bsp.selection_price_type = 1, ROUND(i.price * (bsp.selection_price_value / 100),4), IF(i.special_price > 0 AND i.special_price < 100, ROUND(bsp.selection_price_value * (i.special_price / 100),4), bsp.selection_price_value))* bs.selection_qty)), 
	`catalog_product_index_price_bundle_sel_tmp`.`tier_price` = IF(i.base_tier IS NOT NULL, IF(bsp.selection_price_type = 1, ROUND(i.base_tier - (i.base_tier * (bsp.selection_price_value / 100)),4), IF(i.tier_percent > 0, ROUND((1 - i.tier_percent / 100) * bsp.selection_price_value,4), bsp.selection_price_value)) * bs.selection_qty, NULL)
WHERE (i.price_type=1)
````

Something seems off with this. When the catalog_product_bundle_selection_price table is empty, the last inner join catalog_product_bundle_selection_price results in no rows being updated. Add a single row and in our case, it tried to update 192 rows in catalog_product_index_price_bundle_sel_tmp which only has 48 rows. I also noticed that the INSERT that is run before this has an ON DUPLICATE KEY clause, but of course the UPDATE cannot do this but still tries to update the fields used in the key.

I may be wrong but I wondered if it's down to the first inner join being a cross join?

Hope this is useful to someone with more skill than myself :)

**Comment by rain2o** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rain2o. Thank you for your request. I'm working on Magento instance for you

**Comment by rain2o** [comment]
@lbajsarowicz Does the Magento test environment command not work anymore? I haven't received one the past 2 times I requested one.

**Comment by lbajsarowicz** [comment]
@slavvka Any ideas about the technical issue?

**Comment by rain2o** [comment]
Any update on this @slavvka  or @lbajsarowicz ? I'd like to try and test this in a new test environment to make sure it works across multiple environments before submitting for re-review.

**Comment by craig-bartlett** [comment]
Are the test environments still broken? Would be nice to get this merged :)

File: app/code/Magento/Bundle/Model/LinkManagement.php [hunk 2]
```diff
@@ -418,4 +421,17 @@ private function getOptions(ProductInterface $product)
 
         return $optionCollection->appendSelections($selectionCollection, true);
     }
+
+    /**
+     * Get MetadataPool instance
+     *
+     * @return MetadataPool
+     */
+    private function getMetadataPool()
```
Comment (sidolov) [inline app/code/Magento/Bundle/Model/LinkManagement.php]: Why you need this method? Metadatapool os already injected.

**Review by sidolov — CHANGES_REQUESTED** [review]

File: app/code/Magento/Bundle/Model/LinkManagement.php (hunk 2 above)
Comment (rain2o) [reply app/code/Magento/Bundle/Model/LinkManagement.php]: @sidolov I didn't add this. It looks like this file was reworked after I opened this pull request, including the removal of this function. In commit [e535d373ddad664d7484acf841f94f50fd85c8fa](https://github.com/magento/magento2/commit/e535d373ddad664d7484acf841f94f50fd85c8fa#diff-9af9e82493d309f07e54230e0b313a71). I'll cleanup this file to be up-to-date with this rework.

**Comment by rain2o** [comment]
@magento give me test instance

**Comment by magento-engcom-team** [comment]
Hi @rain2o. Thank you for your request. I'm working on Magento instance for you

**Comment by magento-engcom-team** [comment]
Hi @rain2o, here is your [new Magento instance](https://pr-27315.instances.magento-community.engineering).
Admin access: [https://pr-27315.instances.magento-community.engineering/admin_05a7](https://pr-27315.instances.magento-community.engineering/admin_05a7)
Login: `a24061c4` Password: `a5ee15e3f1cb`
Instance will be terminated in up to 3 hours.

**Comment by rain2o** [comment]
I tested this in the new Magento instance, but I wasn't able to do a full test as it appears the Cron doesn't run in the test environment that the Magento bot spins up. A full re-index is required for the pricing data, after adding a 2nd website/store and trying to change prices per website level. Is there a way to get the test environment with the Cron running to fully test this? 

As a note, I have tested in a local instance already, but as previously mentioned there was an issue that I didn't receive in my local instance that others did, so I wanted to test in a cloud test instance to make sure the error does not occur again. Otherwise, can someone else test this in a fresh instance to ensure that error is in fact gone?

**Comment by craig-bartlett** [comment]
Hi @rain2o , I can test it in a fresh install and let you know shortly :)

**Comment by craig-bartlett** [comment]
Hi again @rain2o - I've tested in a fresh local instance and it indeed works fine for me too. No errors on indexing and the prices per site/store work correctly.

**Comment by rain2o** [comment]
Thanks @craig-bartlett  for the extra testing! 

@sidolov I believe this is ready to be reviewed again. The requested updates have been made and we have tested in multiple instances and so far all tests have been successful.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@rain2o are you going to continue progress on that? Thanks!

**Comment by rain2o** [comment]
@engcom-Echo yes, I will work on fixing the tests as soon as I am able to. This pull request process has taken a long time, so other priorities have taken over my time. I'm working on getting back to this soon. If anyone would like to assist that would be fantastic.

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
I will take care of test coverage.

**Comment by rain2o** [comment]
> I will take care of test coverage.

Thanks for the assist @engcom-Echo

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
Failed functional tests not related to the changes in this PR

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

File: app/code/Magento/Bundle/Model/Option/SaveAction.php [hunk 3]
```diff
@@ -93,7 +105,7 @@ public function save(ProductInterface $bundleProduct, OptionInterface $option)
             }
         } else {
             if (!$existingOption->getOptionId()) {
-                throw new NoSuchEntityException(
+                throw new \Magento\Framework\Exception\NoSuchEntityException(
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/Option/SaveAction.php]: Can we import this instead of having the full path? Just to align with other changes on the PR.

File: app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php [hunk 4]
```diff
@@ -455,6 +455,42 @@ private function getBaseBundleSelectionPriceSelect(): Select
         return $select;
     }
 
+    /**
+     * Get base select for bundle selection price update
+     *
+     * @return Select
+     * @throws \Exception
+     */
+    private function getBaseBundleSelectionPriceUpdateSelect(): Select
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php:465]: Can you provide some details on the changes from this query and the `getBaseBundleSelectionPriceSelect`? It is important to understand your thinking on this one.

File: app/code/Magento/Bundle/Model/Option/SaveAction.php [hunk 5]
```diff
@@ -135,13 +147,14 @@ private function updateOptionSelection(ProductInterface $product, OptionInterfac
         if (is_array($option->getProductLinks())) {
             $productLinks = $option->getProductLinks();
             foreach ($productLinks as $productLink) {
+                $productLink->setWebsiteId($this->storeManager->getStore($product->getStoreId())->getWebsiteId());
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/Option/SaveAction.php]: Shouldn't we add such set on the `save` method on this class as well? Or is it just relevant when we update an option?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @rain2o, thanks for the pull request! Can you have a look at my comments below?

File: app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php (hunk 4 above)
Comment (craig-bartlett) [reply app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php:465]: Hi, I believe this is based on my suggested change here - https://github.com/craig-bartlett/magento2/commit/8fdd190644794887c6e5f8737789b8b8817af46f?diff=unified

I tried to explain the issue and fix briefly here https://github.com/magento/magento2/issues/12584#issuecomment-632052495 and more in depth here https://github.com/magento/magento2/pull/27315#issuecomment-630866505

Essentially it adds more ON clauses to the joins to ensure it only tries to update existing rows, fixing the issue regarding duplicate keys when saving stock as seen by @rain2o in his original pull request.

File: app/code/Magento/Bundle/Model/Option/SaveAction.php (hunk 5 above)
Comment (rain2o) [reply app/code/Magento/Bundle/Model/Option/SaveAction.php]: @gabrieldagama I believe it is only relevant when updating an option, unless I am missing something. The only time this isn't called from `save` I believe is when creating the product options, and I think you need to create them at the root level before editing any store/website scopes, correct?

File: app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php (hunk 4 above)
Comment (rain2o) [reply app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php:465]: Thanks for the info @craig-bartlett

@gabrieldagama does that help answer your question? Would you like me to add some additional comments to the docblock to make it more clear moving forward?

Comment (gabrieldagama) [reply app/code/Magento/Bundle/Model/ResourceModel/Indexer/Price.php:465]: It does help @rain2o, thanks @craig-bartlett. I believe that is fine, we just need to understand be reasons for the changes.

File: app/code/Magento/Bundle/Model/Option/SaveAction.php (hunk 5 above)
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/Option/SaveAction.php]: This method `$option->getProductLinks();` return `LinkInterface` so we will need to have the `setWebsiteId` and `getWebsiteId` to the interface and DTO. Be aware that we need to implement it on a backwards compatible way.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @rain2o, I've done a review on this and it seems fine, we just need to apply this change https://github.com/magento/magento2/pull/27315#discussion_r494894457 and also I've got a small comment below that I believe we should address as well.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @rain2o,
Could you please check the previous comment and add requested changes.
Thank you.

**Comment by rain2o** [comment]
Hello @engcom-Hotel I will make the request updates as soon as possible. Currently under a Black Friday prep which is taking all of my time, but as soon as I have a chance I'll work on the requested changes.

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 6]
```diff
@@ -533,12 +542,15 @@ public function testAddChildCouldNotSave()
         $this->expectException(CouldNotSaveException::class);
 
         $productLink = $this->getMockBuilder(LinkInterface::class)
-            ->setMethods(['getSku', 'getOptionId', 'getSelectionId'])
+            ->setMethods(['getSku', 'getOptionId', 'getSelectionId', 'getWebSiteId'])
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: This method doesn't exist anymore on the Link, please remove it.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 7]
```diff
@@ -533,12 +542,15 @@ public function testAddChildCouldNotSave()
...
             ->disableOriginalConstructor()
             ->getMockForAbstractClass();
         $productLink->method('getSku')->willReturn('linked_product_sku');
         $productLink->method('getOptionId')->willReturn(1);
         $productLink->method('getSelectionId')->willReturn(1);
+        $store = $this->createMock(Store::class);
+        $this->storeManagerMock->expects($this->once())->method('getStore')->willReturn($store);
+        $store->expects($this->once())->method('getWebsiteId')->willReturn(100);
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: This method doesn't exist anymore on the Link, please remove it. Let's adjust the test to represent the recent changes.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 8]
```diff
@@ -610,12 +622,15 @@ static function () {
     public function testAddChild()
     {
         $productLink = $this->getMockBuilder(LinkInterface::class)
-            ->setMethods(['getSku', 'getOptionId', 'getSelectionId'])
+            ->setMethods(['getSku', 'getOptionId', 'getSelectionId', 'getWebSiteId'])
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: This method doesn't exist anymore on the Link, please remove it.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 9]
```diff
@@ -610,12 +622,15 @@ static function () {
...
             ->disableOriginalConstructor()
             ->getMockForAbstractClass();
         $productLink->method('getSku')->willReturn('linked_product_sku');
         $productLink->method('getOptionId')->willReturn(1);
         $productLink->method('getSelectionId')->willReturn(1);
+        $store = $this->createMock(Store::class);
+        $this->storeManagerMock->expects($this->once())->method('getStore')->willReturn($store);
+        $store->expects($this->once())->method('getWebsiteId')->willReturn(100);
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Same here.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 10]
```diff
@@ -686,9 +701,10 @@ public function testSaveChild()
         $linkProductId = 45;
         $parentProductId = 32;
         $bundleProductSku = 'bundleProductSku';
+        $websiteId = 100;
 
         $productLink = $this->getMockBuilder(LinkInterface::class)
-            ->setMethods(['getSku', 'getOptionId', 'getSelectionId'])
+            ->setMethods(['getSku', 'getOptionId', 'getSelectionId', 'getWebSiteId'])
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: This method doesn't exist anymore on the Link, please remove it.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 11]
```diff
@@ -702,6 +718,9 @@ public function testSaveChild()
             ->willReturn($canChangeQuantity);
         $productLink->method('getIsDefault')->willReturn($isDefault);
         $productLink->method('getSelectionId')->willReturn($optionId);
+        $store = $this->createMock(Store::class);
+        $this->storeManagerMock->expects($this->once())->method('getStore')->willReturn($store);
+        $store->expects($this->once())->method('getWebsiteId')->willReturn($websiteId);
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Same here.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 12]
```diff
@@ -740,7 +759,8 @@ public function testSaveChild()
                     'setSelectionPriceType',
                     'setSelectionPriceValue',
                     'setSelectionCanChangeQty',
-                    'setIsDefault'
+                    'setIsDefault',
+                    'setWebsiteId'
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: This method doesn't exist anymore on the Link, please remove it.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php [hunk 13]
```diff
@@ -758,6 +778,7 @@ public function testSaveChild()
         $selection->expects($this->once())->method('setSelectionPriceValue')->with($price);
         $selection->expects($this->once())->method('setSelectionCanChangeQty')->with($canChangeQuantity);
         $selection->expects($this->once())->method('setIsDefault')->with($isDefault);
+        $selection->expects($this->once())->method('setWebsiteId')->with($websiteId);
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Please review all the changes on this test to make sure it represents the latest changes.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Foxtrot, please have a look at my comments below.

Thaks!

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 8 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 10 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 12 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 13 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 9 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php:633]: The test will fail without this.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 7 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php:553]: The test will fail without this.

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 11 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 9 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 7 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

File: app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php (hunk 6 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Test/Unit/Model/LinkManagementTest.php]: Done

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

File: app/code/Magento/Bundle/Model/Option/SaveAction.php [hunk 14]
```diff
@@ -40,22 +44,31 @@ class SaveAction
      */
     private $linkManagement;
 
+    /**
+     * @var StoreManagerInterface
+     */
+    private $storeManager;
+
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/Option/SaveAction.php]: Apparently we are not using the `storeManager` in this class, can we remove it?

File: app/code/Magento/Bundle/Model/Selection.php [hunk 15]
```diff
@@ -20,6 +20,8 @@
  * @method \Magento\Bundle\Model\Selection setPosition(int $value)
  * @method int getIsDefault()
  * @method \Magento\Bundle\Model\Selection setIsDefault(int $value)
+ * @method int getWebsiteId()
+ * @method \Magento\Bundle\Model\Selection setWebsiteId(int $value)
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/Selection.php:24]: Since we aren't using this approach anymore, this can probably be removed.

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Foxtrot, thanks for working on this, can you have a look at my comments below?

File: app/code/Magento/Bundle/Model/Selection.php (hunk 15 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Model/Selection.php:24]: These methods are still used in another classes.

File: app/code/Magento/Bundle/Model/Option/SaveAction.php (hunk 14 above)
Comment (engcom-Foxtrot) [reply app/code/Magento/Bundle/Model/Option/SaveAction.php]: Done

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by engcom-Foxtrot** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by gabrieldagama** [comment]
@magento run all tests

File: app/code/Magento/Bundle/Model/LinkManagement.php [hunk 16]
```diff
@@ -239,6 +241,55 @@ protected function mapProductLinkToSelectionModel(
...
+        if ($productLink->getPrice() !== null) {
+            $selectionModel->setSelectionPriceValue($productLink->getPrice());
+        }
+        if ($productLink->getCanChangeQuantity() !== null) {
+            $selectionModel->setSelectionCanChangeQty($productLink->getCanChangeQuantity());
+        }
+        if ($productLink->getIsDefault() !== null) {
+            $selectionModel->setIsDefault($productLink->getIsDefault());
+        }
+        $selectionModel->setWebsiteId((int)$this->storeManager->getStore($parentProduct->getStoreId())->getWebsiteId());
```
Comment (gabrieldagama) [inline app/code/Magento/Bundle/Model/LinkManagement.php:286]: As I can see when we load the product on line 322 we are not using the `store_id`, in case of a product being assigned to multiple stores, would such approach still work?

**Review by gabrieldagama — CHANGES_REQUESTED** [review]
Hi @engcom-Foxtrot, thanks for updating this PR, can you have a look at my question below?

**Comment by gabrieldagama** [comment]
@magento run all tests

**Review by gabrieldagama — APPROVED** [review]

**Comment by magento-engcom-team** [comment]
Hi @gabrieldagama, thank you for the review.
[ENGCOM-7141](https://jira.corp.magento.com/browse/ENGCOM-7141) has been created to process this Pull Request
:eight_spoked_asterisk: @gabrieldagama, could you please add one of the following labels to the Pull Request?

| Label | Description |
|--------------------------------|-----------------------------------------------------------------|
| ```Auto-Tests: Covered``` | All changes in Pull Request is covered by auto-tests |
| ```Auto-Tests: Not Covered``` | Changes in Pull Request requires coverage by auto-tests |
| ```Auto-Tests: Not Required``` | Changes in Pull Request does not require coverage by auto-tests |

**Comment by gabrieldagama** [comment]
@magento run all tests

**Comment by engcom-Bravo** [comment]
:heavy_check_mark: QA Passed

### Manual testing scenarios

1. Go to _Stores - Configuration - Catalog - Catalog - Price_ and set _Catalog Price Scope_ to **Website**
per_website
2. Create a second Website, Store and Store view
3. Go to _Catalog - Products_ and Add a new bundle product
4. Set the following settings:
- _Dynamic Price_ - **No**
dynam_no

- _Products in Website_ - select all the available websites
websites
5. Add a bundle item with price type _fixed_ and price _12_ and **Save** the product
bundle_item
6. Change the **Scope** to the second store view.
7. Change the Bundle item price to 10, and **Save** the product
bundle_ite_10
8. Change the **Scope** to the third store view and check the Bundle Item price

**BEFORE** applying changes provided in the PR, the Bundle item price has been changed for all store views, which in this case was **10**

**AFTER** switching to the PR, the Bundle item price is changed only in the scope of a particular store view. In this case, the price remained *12**
bundle_ite_12
The entity is added to `catalog_product_bundle_selection_price` table in the database 
entity
