### PR TITLE
31253 default store breadcrumbs returned for products which in both root categories

### LINKED ISSUE #31253: Default store (Root category A) breadcrumbs are being returned for New Store (Root category B) when Product belongs to both root categories.
### Preconditions (*)

1. Magento 2.4.1
2. Two root categories exists in Admin-Categories
3. Two stores exists with different root categories for each of it
4. Each Stores should have atleast one store view.
5. Each Root category should have one sub-category.
5. Product should belong to both stores. i.e. Assign product to all root and sub categories.

### Steps to reproduce (*)

1. Query - 
```
{
  "store": "engchildren"
}
query {
  products(filter: { url_key: { eq: "gabrielle-micro-sleeve-top"} }){
   	items {
      categories {
        name
        id
        url_path
        breadcrumbs {
          category_id
          category_name
          category_level
        }
      }
    } 
  }
}
```

### Expected result (*)

1. Store specific data should be returned.

### Actual result (*)

1. Response - 
```
{
  "data": {
    "products": {
      "items": [
        {
          "categories": [
            {
              "name": "Default Category",
              "id": 2,
              "url_path": null,
              "breadcrumbs": null
            },
            {
              "name": "Women",
              "id": 20,
              "url_path": "women",
              "breadcrumbs": null
            },
            {
              "name": "Tops",
              "id": 21,
              "url_path": "women/tops-women",
              "breadcrumbs": [
                {
                  "category_id": 20,
                  "category_name": "Women",
                  "category_level": 2
                }
              ]
            },
            {
              "name": "Toddlers",
              "id": 51,
              "url_path": "toddlers",
              "breadcrumbs": null
            }
          ]
        }
      ]
    }
  }
}
```

---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by sasha19957099**
### Description (*)
Issue was related to the indexer catalog_category_product

### Fixed Issues (if relevant)
1. Fixes https://github.com/magento/magento2/issues/31253

### Manual testing scenarios (*)
Magento 2.4.1
1.Two root categories exists in Admin-Categories
2.Two stores exists with different root categories for each of it
3.Each Stores should have atleast one store view.
4.Each Root category should have one sub-category.
5.Product should belong to both stores. i.e. Assign product to all root and sub categories.
6.Run query
{
  "store": "engchildren"
}
query {
  products(filter: { url_key: { eq: "gabrielle-micro-sleeve-top"} }){
   	items {
      categories {
        name
        id
        url_path
        breadcrumbs {
          category_id
          category_name
          category_level
        }
      }
    } 
  }
}

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sasha19957099** [comment]
@magento run all tests

File: app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php [hunk 1]
```diff
@@ -379,13 +380,13 @@ private function addFilteringByChildProductsToSelect(Select $select, Store $stor
             []
         )->joinLeft(
             ['child_cpsd' => $this->getTable('catalog_product_entity_int')],
-            'child_cpsd.' . $linkField . ' = '. 'relation_product_entity.' . $linkField
+            'child_cpsd.' . $linkField . ' = ' . 'relation_product_entity.' . $linkField
```
Comment (cpartica) [inline app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php]: is there a safer alternative to this?
just concatenating strings as parameters to a mysql query could lead to a sql injection

File: dev/tests/integration/testsuite/Magento/Catalog/_files/product_in_two_root_categories_rollback.php [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+declare(strict_types=1);
+
+use Magento\Catalog\Api\CategoryRepositoryInterface;
+use Magento\Catalog\Model\ResourceModel\Category\Collection;
+use Magento\Catalog\Model\ResourceModel\Category\CollectionFactory;
+use Magento\TestFramework\Helper\Bootstrap;
+use Magento\TestFramework\Workaround\Override\Fixture\Resolver;
+
+//$objectManager = Bootstrap::getObjectManager();
```
Comment (cpartica) [inline dev/tests/integration/testsuite/Magento/Catalog/_files/product_in_two_root_categories_rollback.php]: don't forget to remove debug code

**Review by cpartica — CHANGES_REQUESTED** [review]

File: app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php [hunk 3]
```diff
@@ -171,7 +172,7 @@ protected function reindex()
     {
         foreach ($this->storeManager->getStores() as $store) {
             if ($this->getPathFromCategoryId($store->getRootCategoryId())) {
-                $this->currentStoreId = $store->getId();
+                $this->currentStore = $store;
```
Comment (cpartica) [inline app/code/Magento/Catalog/Model/Indexer/Category/Product/AbstractAction.php]: better to move this to a method that ensures a strict type return
that way when getCurrentStore is used it can throw an error is currentStore is empty

**Review by cpartica — CHANGES_REQUESTED** [review]

**Comment by sasha19957099** [comment]
@magento run all tests

**Comment by sasha19957099** [comment]
@magento run Functional Tests CE

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
Hi @sasha19957099 
Thank you for your contribution,

I tried to reproduce the same on 2.4-develop, But it is not reproducible.

Here are my findings :-
1. Two root categories exists in Admin-Categories
Screenshot 2022-01-04 at 2 46 01 PM

2. Setup 2 stores with having at-least one store view and two separate root categories
Screenshot 2022-01-04 at 2 41 30 PM

3. Product should belong to both stores. i.e. Assign product to all root and sub categories.
Screenshot 2022-01-04 at 2 47 52 PM

**Testing Scenarios:-**

**1. Without setting store value**
Query:
`query {
  products(filter: { url_key: { eq: "test-product"} }){
   	items {
      categories {
        name
        id
        url_path
        breadcrumbs {
          category_id
          category_name
          category_level
        }
      }
    } 
  }
}`

Result:- Data from both the sores are fetched
`{
  "data": {
    "products": {
      "items": [
        {
          "categories": [
            {
              "name": "Gear",
              "id": 3,
              "url_path": "gear",
              "breadcrumbs": null
            },
            {
              "name": "Bags",
              "id": 4,
              "url_path": "gear/bags",
              "breadcrumbs": [
                {
                  "category_id": 3,
                  "category_name": "Gear",
                  "category_level": 2
                }
              ]
            },
            {
              "name": "Root Category 2",
              "id": 41,
              "url_path": null,
              "breadcrumbs": null
            },
            {
              "name": "Sub Category 1",
              "id": 42,
              "url_path": "sub-category-1",
              "breadcrumbs": null
            }
          ]
        }
      ]
    }
  }
}`

**2. Setting store value**
Query: **Set Store as new/default in header**
`query {
  products(filter: { url_key: { eq: "test-product"} }){
   	items {
      categories {
        name
        id
        url_path
        breadcrumbs {
          category_id
          category_name
          category_level
        }
      }
    } 
  }
}`

Result: Store specific data is fetched, is this case I have set store value as **new** in the header and the we get the store view specific response
`{
  "data": {
    "products": {
      "items": [
        {
          "categories": [
            {
              "name": "Sub Category 1",
              "id": 42,
              "url_path": "sub-category-1",
              "breadcrumbs": null
            },
            {
              "name": "Child Category 1",
              "id": 43,
              "url_path": "sub-category-1/child-category-1",
              "breadcrumbs": [
                {
                  "category_id": 42,
                  "category_name": "Sub Category 1",
                  "category_level": 2
                }
              ]
            }
          ]
        }
      ]
    }
  }`

Hence closing this PR

You can try the same on mainline 2.4-develop, If still its reproducible, Please reopen and update if you wish to continue.

Thanks

**Comment by engcom-Lima** [comment]
Reopening this PR as after reverifying, the issue is reproducible

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
@magento run all tests

**Comment by engcom-Lima** [comment]
The code review points seem to be addressed, moving it into Pending Review column

Thanks!

**Comment by engcom-Charlie** [comment]
It seems that bot moved this PR from Pending Review to Changes Requested so moving back again to Pending Review.

**Comment by ishakhsuvarov** [comment]
@magento run all tests

File: dev/tests/integration/testsuite/Magento/Catalog/_files/product_in_two_root_categories.php [hunk 4]
```diff
@@ -0,0 +1,67 @@
+<?php
```
Comment (ishakhsuvarov) [inline dev/tests/integration/testsuite/Magento/Catalog/_files/product_in_two_root_categories.php:1]: Please use [parametrized fixture format](https://devdocs.magento.com/guides/v2.4/test/integration/parameterized_data_fixture.html)

File: dev/tests/integration/testsuite/Magento/Catalog/_files/product_in_two_root_categories_rollback.php [hunk 5]
```diff
@@ -0,0 +1,12 @@
+<?php
```
Comment (ishakhsuvarov) [inline dev/tests/integration/testsuite/Magento/Catalog/_files/product_in_two_root_categories_rollback.php:1]: Please use [parametrized fixture format](https://devdocs.magento.com/guides/v2.4/test/integration/parameterized_data_fixture.html)

**Review by ishakhsuvarov — CHANGES_REQUESTED** [review]

**Comment by engcom-Alfa** [comment]
Hi @sasha19957099 & @ishakhsuvarov Thanks for your contribution and collaboration.

As I have the latest updates from our internal team, our internal team resolving the PR comments to deliver within a short period along with 2.4.5 release itself in the scope of internal ticket `AC-2515`.

Any further updates will be posted here.

Thanks

**Comment by glo71317** [comment]
Based on priority I am working on this PR and fixing the PR comments and automation tests

**Comment by glo71317** [comment]
We raised internal PR-https://github.com/magento-gl/magento2ce/pull/303 along with this PR commits and covering the automation tests and resolved PR comments
Once Internal PR will get merged will notify here

**Comment by engcom-Alfa** [comment]
We raised internal PR-https://github.com/magento-gl/magento2ce/pull/303 along with this PR commits and covering the automation tests and resolved PR comments
Once Internal PR will get merged will notify here
