### PR TITLE
leading zeros doesn't accountable in the cart for the cart price rule…

### LINKED ISSUE #37919: Cart price rule with condition SKU doesn't take into account the "leading zeros" in the SKU (sku: 01234 is the same as 1234)
### Preconditions and environment

 Magento ver. 2.4.4

### Steps to reproduce

1. Create product with SKU: 1234
2. Create product with SKU: 01234
3. Create CART PRICE RULE (for example): 
- Specific coupon
- Coupon code: TESTSKU
- ACTION: percent of product price discount, 50% discount amount)
- Apply the rule only to cart items ... (SKU   is    01234)

5. Go to shop front and add product SKU 1234 to CART
6. On the cart page enter the coupon code TESTSKU

### Expected result

Discount for product with SKU: 1234 of 50% should NOT be applied.

### Actual result

Discount for product with SKU:  1234  IS applied (even the SKU is not in the CART PRICE RULE CONDITION).

### Additional information

It seems that Magento 2 doesn't recognize the leading zeros of SKU. 

From our diagnosis it seems that the problem is here:
\Magento\Rule\Model\Condition\AbstractCondition::_compareValues

### Release note

_No response_

### Triage and priority

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by magentoabu**
… issue fixed

### Fixed Issues (if relevant)

1. Fixes magento/magento2#37919

### Manual testing scenarios (*)

1. Create product with SKU: 1234..
2. Create product with SKU: 01234..
3. Create CART PRICE RULE (for example):
   Specific coupon
   Coupon code: TESTSKU
   ACTION: percent of product price discount, 50% discount amount)
   Apply the rule only to cart items ... (SKU is 01234).
4.Go to shop front and add product SKU 1234 to CART.
5.On the cart page enter the coupon code TESTSKU.
6.Discount for product with SKU: 1234 of 50% didn't applied.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magentoabu** [comment]
@magento run all tests

**Comment by nuzil** [comment]
@magentoabu  can you pls sign Adobe CLA?

**Comment by magentoabu** [comment]
> @magentoabu can you pls sign Adobe CLA?

@nuzil ,its done as Adobe CLA signed. Thanks

**Comment by nuzil** [comment]
@magentoabu if you can, can you check Static tests? Cause you changed file, it being validated and requires some comment modifications.
Also other tests failure connected to your change

**Comment by magentoabu** [comment]
@magento run all tests

**Comment by magentoabu** [comment]
@magento run Static Tests

**Comment by magentoabu** [comment]
@magento run Static Tests

**Comment by engcom-Hotel** [comment]
Hello @magentoabu,

As you are still working on this PR, moving this PR in changes requested.

Thanks

**Comment by engcom-Hotel** [comment]
Moving back to `Changes Requested`

**Comment by magentoabu** [comment]
@magento run all tests

**Comment by magentoabu** [comment]
@magento run all tests

**Comment by magentoabu** [comment]
@nuzil @engcom-Hotel Adobe CLA is signed and also fix the static tests, please review

**Comment by engcom-Hotel** [comment]
@magento run all tests

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @magentoabu,

Thanks for the contribution!

In accordance to [DOD](https://developer.adobe.com/commerce/contributor/guides/code-contributions/definition-of-done/#definition-of-done-1), please add an automated test for this fix.

Thanks

**Comment by magentoabu** [comment]
@engcom-Hotel  do you want me to write unit test or MFTF  test?

**Comment by engcom-Hotel** [comment]
Hello @magentoabu,

Anything is fine, but I would prefer MFTF for this functionality.

Thanks

**Comment by engcom-Hotel** [comment]
Hello @magentoabu,

Just a friendly reminder to add an automated test for this PR.

Thanks

**Comment by engcom-Dash** [comment]
@magentoabu I am taking care of the changes. Thank you!

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Unit Tests, WebAPI Tests, Integration Tests, Functional Tests B2B, Functional Tests EE, Functional Tests CE

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
Modified the implementation for the strings starting with "0". Also, added the unit tests. Hence moving this back to pending review.

File: app/code/Magento/Rule/Model/Condition/AbstractCondition.php [hunk 1]
```diff
@@ -886,6 +885,9 @@ public function validateAttribute($validatedValue)
     protected function _compareValues($validatedValue, $value, $strict = true)
     {
         if ($strict && is_numeric($validatedValue) && is_numeric($value)) {
+            if (preg_match('/^0\d+$/', $validatedValue) || preg_match('/^0\d+$/', $value)) {
```
Comment (engcom-Hotel) [inline app/code/Magento/Rule/Model/Condition/AbstractCondition.php]: We can simplified the code while maintaining the same logic as below:
```suggestion
           $pattern = '/^0\d+$/';
        if ((preg_match($pattern, $validatedValue) || preg_match($pattern, $value))) {
```

File: app/code/Magento/Rule/Model/Condition/AbstractCondition.php [hunk 2]
```diff
@@ -1,9 +1,8 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Rule/Model/Condition/AbstractCondition.php]:
```suggestion
 * Copyright 2011 Adobe
```

File: app/code/Magento/Rule/Test/Unit/Model/Condition/AbstractConditionTest.php [hunk 3]
```diff
@@ -1,7 +1,7 @@
 <?php
 /**
- * Copyright © Magento, Inc. All rights reserved.
- * See COPYING.txt for license details.
+ * Copyright 2015 Adobe
```
Comment (engcom-Hotel) [inline app/code/Magento/Rule/Test/Unit/Model/Condition/AbstractConditionTest.php]:
```suggestion
 * Copyright 2014 Adobe
```

File: app/code/Magento/Rule/Test/Unit/Model/Condition/AbstractConditionTest.php [hunk 4]
```diff
@@ -65,6 +65,9 @@ public static function validateAttributeDataProvider()
             [null, '==', 0, false],
             [null, '==', 0.00, false],
 
+            ['0123', '===', '123', false],
```
Comment (engcom-Hotel) [inline app/code/Magento/Rule/Test/Unit/Model/Condition/AbstractConditionTest.php:69]: In addition of the above test cases, shall we add more test cases as below to cover wide range of scenarios:

```
// Test cases for strict equality with leading zeros
['000123', '===', '123', false],
['123', '===', '000123', false],
['0123', '===', '0123', true]

// Test cases for strict equality with different numeric types
[123, '===', '123', false],
['123', '===', 123, false]
```

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @engcom-Dash & @magentoabu,

Please refer to the below review comments.

Thanks

File: app/code/Magento/Rule/Test/Unit/Model/Condition/AbstractConditionTest.php (hunk 3 above)
Comment (engcom-Dash) [reply app/code/Magento/Rule/Test/Unit/Model/Condition/AbstractConditionTest.php]: Changed the copyright PR to 2013 as per file creationg date.

**Comment by engcom-Dash** [comment]
@magento run all tests

**Review by engcom-Hotel — APPROVED** [review]

**Comment by engcom-Bravo** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run all tests

**Comment by engcom-Dash** [comment]
@magento run Functional Tests B2B, Functional Tests CE, Functional Tests EE

**Comment by engcom-Dash** [comment]
The test failures for functional CE are inconsistent. For the Functional B2B test cases , consistent test failures are not related to the code changes done in this PR. Hence moving this PR in Merge In Progress.

Functional Tests CE: 

Build 1:
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39525/d643717691fb2bfdb475ae1d6f5c2671/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Build 2: 
https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39525/860edab68cb8f9d8360cb79985a35691/Functional/allure-report-ce/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image

Functional Tests B2B:

Build 1: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39525/4bf0f7f94fa317c801efb12dc079480e/Functional/allure-report-b2b/index.html

image

Build 2: https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/magento2/pull/39525/82ba4dc9fffaa0909a1499089e9fcde8/Functional/allure-report-b2b/index.html#categories/8fb3a91ba5aaf9de24cc8a92edc82b5d

image
